### ISSUE TITLE
Undefined symbol: _FIREmailPasswordAuthProviderID

### ISSUE THREAD

**Issue by nightroadcosplay** [firebase/firebase-ios-sdk#3052] opened 2019-05-22 09:56 UTC
I upgraded to last version and when i try to build the project i get this error:

Undefined symbols for architecture arm64:
  "_FIREmailPasswordAuthProviderID", referenced from:
      ___35-[FIREmailEntryViewController next]_block_invoke in FirebaseAuthUI(FIREmailEntryViewController.o)
      ___74-[FIRAuthPickerViewController handleAccountLinkingForEmail:newCredential:]_block_invoke in FirebaseAuthUI(FIRAuthPickerViewController.o)

I tried reinstalling the pods, but still got the error.

**Comment by maksymmalyhin** [comment] 2019-05-22 10:06
@nightroadcosplay Thank you for the report. Will it be possible to share your Podfile and Podfile.lock or (even better) a test project to reproduce the issue?

**Comment by nightroadcosplay** [comment] 2019-05-22 10:19
[Podfile.zip](https://github.com/firebase/firebase-ios-sdk/files/3206910/Podfile.zip)

Here are Podefile and Podfile.lock

**Comment by ryanwilson** [comment] 2019-05-22 11:57
Looks like the project is picking up an old version of FirebaseUI because of the `pod 'FBSDKCoreKit', '~> 4.44.1'` requirement. The new version of FirebaseUI requires 5.0 or above. I'm not sure why the version of FirebaseUI you're getting is so old, though.

Relevant Podspec:
https://github.com/firebase/FirebaseUI-iOS/blob/36860d6241737d015d65a34e301953d6297a300e/FirebaseUI.podspec#L112

**Comment by nightroadcosplay** [comment] 2019-05-22 12:19
> Looks like the project is picking up an old version of FirebaseUI because of the `pod 'FBSDKCoreKit', '~> 4.44.1'` requirement. The new version of FirebaseUI requires 5.0 or above. I'm not sure why the version of FirebaseUI you're getting is so old, though.
> 
> Relevant Podspec:
> https://github.com/firebase/FirebaseUI-iOS/blob/36860d6241737d015d65a34e301953d6297a300e/FirebaseUI.podspec#L112

Thank you, it was from that pod. Now i got the 7.0.0 FirebaseUI version.

**Comment by ryanwilson** [comment] 2019-05-22 12:22
Great! Is the issue resolved for you then?

**Comment by nightroadcosplay** [comment] 2019-05-22 12:23
Yes! Thank you for your help.

**Comment by ryanwilson** [comment] 2019-05-22 12:23
You're very welcome. Closing the issue now, if you run into anything else please open another one!

**Closed by ryanwilson** 2019-05-22 12:23 UTC
Labels: api: auth
