### ISSUE TITLE
engagement_time_msec is missing while manually reporting screen_view

### ISSUE THREAD

**Issue by dmi3j** [firebase/firebase-ios-sdk#7083] opened 2020-12-03 10:23 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2 (12B45b)
  * Firebase SDK version: 7.1.0
  * Installation method: `CocoaPods` 
  * Firebase Component: Analytics 

#### Steps to reproduce:

I'm trying manually report _AnalyticsEventScreenView_ event to track screen time. 

The parameter **engagement_time_msec** is missing in **screen_view** event. Yet there is an event **user_engagement** and it has this parameter.  I can see this in Big Query

<img width="801" alt="bigquery" src="https://user-images.githubusercontent.com/120496/100995931-21cb3f00-3561-11eb-8397-05dc5536f0e2.png">

Same in Xcode console output: 

```
2020-12-03 11:56:44.557168+0200 mBanking-TEST[1839:1346574] 7.1.0 - [Firebase/Analytics][I-ACS023072] Event logged. Event name, event params: user_engagement (_e), {
    engagement_time_msec (_et) = 14831;
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen (_sn) = xxx;
    ga_screen_class (_sc) = xxx;
    ga_screen_id (_si) = -2990450748203631440;
}
...
2020-12-03 11:56:44.650222+0200 mBanking-TEST[1839:1346575] 7.1.0 - [Firebase/Analytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = app;
    ga_previous_class (_pc) = xxx;
    ga_previous_id (_pi) = -2990450748203631439;
    ga_realtime (_r) = 1;
    ga_screen (_sn) = screen_onbo_phone;
    ga_screen_class (_sc) = xxx;
    ga_screen_id (_si) = -2990450748203631438;
}
```

Tried to set _FirebaseScreenReportingEnabled_ in true, false or even removed completely from Info.plist. No affect. 

According to https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html the **engagement_time_msec** parameter should automatically be reported with **screen_view**

#### Relevant Code:

```
        Analytics.logEvent(AnalyticsEventScreenView,
                           parameters: [AnalyticsParameterScreenName: "xxx",
                                        AnalyticsParameterScreenClass: "xxx"])
```

**Comment by dmi3j** [comment] 2020-12-14 10:56
Anyone can help with this?

**Comment by paulb777** [comment] 2020-12-14 15:43
@dmi3j Sorry about the delay. The issue is tracked internally at b/175579248

**Comment by dmi3j** [comment] 2020-12-14 15:48
That's great! It's just not clear from status if something is going on behind the scene or not. I do imagine the amount of work you have and do not expect to receive fix or workaround immediately. I just need to understand if this is a real issue and will be fixed at some point, or we should find some other way to solve it in our company. Anyway, thank you for the effort!

**Comment by allenktv** [comment] 2020-12-14 18:30
Thanks for reporting the issue @dmi3j. 

Looks like the issue is with the [blog post](https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html) you linked, since the feature to add `engagement_time_msec` to `screen_view` events is enabled on Android, however it is not yet available for iOS. We will correct this on our end, and I will close this bug now since this isn't an issue with the iOS SDK itself. We appreciate your help!

**Closed by allenktv** 2020-12-14 18:30 UTC
Labels: api: analytics
