### ISSUE TITLE
Crashes on +[GULAppEnvironmentUtil isAppStoreReceiptSandbox]

### ISSUE THREAD

**Issue by ChengJingH** [firebase/firebase-ios-sdk#9901] opened 2022-06-13 07:21 UTC
### [REQUIRED] Step 1: Describe your environment
  * Firebase SDK version: __7.9.0__
  * Installation method: `CocoaPods `
  * Firebase Component: __Analytics,  DynamicLinks__
  * Target platform(s): `iOS`

#### Steps to reproduce:

Stack Info:

```
FutuNiuniu +[GULAppEnvironmentUtil isAppStoreReceiptSandbox] (GULAppEnvironmentUtil.m:0)
FutuNiuniu +[GULAppEnvironmentUtil isFromAppStore] (GULAppEnvironmentUtil.m:165)
FutuNiuniu +[FIRFirebaseUserAgent environmentComponents] (FIRFirebaseUserAgent.m:96)
FutuNiuniu -[FIRFirebaseUserAgent environmentComponents] (FIRFirebaseUserAgent.m:0)
FutuNiuniu -[FIRFirebaseUserAgent firebaseUserAgent] (FIRFirebaseUserAgent.m:0)
FutuNiuniu +[FIRApp firebaseUserAgent] (FIRApp.m:0)
FutuNiuniu +[FIRCoreDiagnosticsConnector logCoreTelemetryWithOptions:] (FIRCoreDiagnosticsConnector.m:0)
FutuNiuniu -[FIRApp logCoreTelemetryIfEnabled]_block_invoke (FIRApp.m:851)
ibdispatch.dylib __dispatch_call_block_and_release + 24
libdispatch.dylib __dispatch_client_callout + 16
libdispatch.dylib __dispatch_root_queue_drain + 640
libdispatch.dylib __dispatch_worker_thread2 + 172
libsystem_pthread.dylib __pthread_wqthread + 224
```

**Comment by paulb777** [comment] 2022-06-13 14:09
@ChengJingH Are you using Firebase C++?  This looks like a duplicate of #8795 that is solved in recent versions.

If that's not the issue, please share the Podfile and Podfile.lock.

**Closed** 2022-06-27 01:04 UTC
Labels: api: core, needs-info, no-recent-activity
