### ISSUE TITLE
[Firestore] Potential cache issue with Snapshot listener results.

### ISSUE THREAD

**Issue by joerozek** [firebase/firebase-ios-sdk#1045] opened 2018-04-08 18:33 UTC
### Environment

  * Xcode version: 9.3
  * Firebase SDK version: 4.11 (also reproduced in 4.4 before updating)
  * Firebase Component: Firestore
  * Component version: 0.10.4  (also reproduce in 0.8 before update )

#### Steps to reproduce:

I have a snapshot listener set up to watch a query.  When I delete a record that the query matches. 
 the listener fires three times.  I've confirmed I've only added the listener once. Having the listener fire three times isn't the problem, it's that the results are inconsistent (see output), and it causes the delete record to reappear and then disappear again.  

#### Relevant Code:

Attached listener
```
// userId, restaurantId, are autogen ids (strings)  checkInTime is a date.
let query =Firestore.firestore().collection("visits").whereField("userId", isEqualTo: userId).whereField("restaurantId", isEqualTo: restaurantId).whereField("checkInTime", isGreaterThanOrEqualTo: startOfDay).order(by: "checkInTime")

let listener = query.addSnapshotListener() { snapshot, error in
                print("LISTENER FIRING!!!!!!!!!")
                print("from cache: \(String(describing: snapshot?.metadata.isFromCache))")
                print("pending writes: \(String(describing: snapshot?.metadata.hasPendingWrites))")
                print("number of records: \(String(describing: snapshot?.documents.count))")
}
```
Code to delete record from swipe action
```
func tableView(_ tableView: UITableView, leadingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
        
        let delete = UIContextualAction(style: .destructive, title: "Delete") { (action, view, success:@escaping (Bool) -> Void) in
            
            let cell = tableView.cellForRow(at: indexPath) as? VisitCell
            guard let visit = cell?.visit else {
                return
            }
            
            print("going to delete from firebase" )
            Firestore.firestore().collection("visits").document(visit.visitId!).delete(completion: { (error) in
                print("deleted from firebase" )

            })
            success(true)
        }
}
```

#### Output of prints()
```
going to delete from firebase
LISTENER FIRING!!!!!!!!!
from cache: Optional(false)
pending writes: Optional(false)
number of records: Optional(0)
 
deleted from firebase
LISTENER FIRING!!!!!!!!!
from cache: Optional(true)
pending writes: Optional(false)
number of records: Optional(1)
 
LISTENER FIRING!!!!!!!!!
from cache: Optional(false)
pending writes: Optional(false)
number of records: Optional(0)
```

There are 0 records fetched (not from cache) then suddenly 1 record (from cache) then 0 records again the UITableView flickers, the record is removed then shows up again and then disappears right away.  
I would expect that the cache should have been updated after the first fetch that wasn't from cache.

**Comment by mikelehen** [comment] 2018-04-09 13:19
Thanks for the report!  I believe this is likely a manifestation of a known issue that we're working on.  We'll update here once it's resolved.

@wilhuff I think this will be fixed by b/33446471.

**Comment by joerozek** [comment] 2018-04-09 16:25
Thanks

**Comment by benjaminpwarren** [comment] 2018-04-18 07:48
I'm having a similar issue where an onSnapshot fires multiple times, the first time with only one of the expected docs, the second time with all of the expected docs. Could this be related?

Note: I'm not writing/deleting any data, this is just when I set up the listener on page load.

**Comment by mikelehen** [comment] 2018-04-20 15:30
@benjaminpwarren Hrm. Offhand that doesn't sound like the same issue. The issue this was referring to was specific to deletes.  If you could open a separate issue with as much detail (ideally repro code) as you can, that would be great.

**Comment by mikegilroy** [comment] 2018-05-21 15:40
I am experiencing the exact same issue that @joerozek has reported but on a newer version of the SDK/Firestore. Steps to reproduce are identical. 

- Xcode version: 9.3
- Firebase SDK version: 5.0
- Firebase Component: Firestore
- Component version: 0.12.1

**Comment by sargunv** [comment] 2018-06-06 04:42
Is there any known workaround for now other than ignoring fromCache=true events?

**Comment by mikegilroy** [comment] 2018-06-06 09:18
@sargunv I used throttling to mask the UI flickering that the multiple responses cause, as I still wanted cached results to come through when the user was offline for example. I set the throttling delay to 0.5 seconds and that seemed to get rid of the flickering in the majority of cases where internet connection was ok. It's not a full-proof solution but it's working as a good mask of the issue until fixed for me. I wrote a blog post on the throttling technique I used if useful too: https://www.craftappco.com/blog/2018/5/30/simple-throttling-in-swift

**Comment by sicbb** [comment] 2018-07-26 18:42
Same issue here and it's very annoying.

`listener = Firestore.firestore().collection("categories").whereField("userId", isEqualTo: currentUser.uid).addSnapshotListener() { (snapshot, error) in
            if let snapshot = snapshot {
                
                snapshot.documentChanges.forEach({ diff in
                    
                    print(snapshot.metadata.isFromCache, snapshot.metadata.hasPendingWrites)
                    
                    if (diff.type == .added) {
                        print("New: \(diff.document.data())")
                    }
                    
                    if (diff.type == .modified) {
                        print("Modified: \(diff.document.data())")
                    }
                    
                    if (diff.type == .removed) {
                        print("Removed: \(diff.document.data())")
                    }
                    
                })
                
            }
        }`

Result when i delete a category:

false false
Removed: ["description": Test, "name": AAA, "color": #F44336, "userId": XXX, "created": 2018-07-26T18:25:33Z]

true false
New: ["description": Test, "name": AAA, "color": #F44336, "userId": XXX, "created": 2018-07-26T18:25:33Z]

false false
Removed: ["description": Test, "name": AAA, "color": #F44336, "userId": XXX, "created": 2018-07-26T18:25:33Z]

Any idea's?

**Comment by mikelehen** [comment] 2018-08-07 14:30
I believe this issue should be addressed by https://github.com/firebase/firebase-ios-sdk/pull/1622 which has been included in the latest release.  I apologize for the long delay.  Please holler if you are still seeing issues.

**Closed by mikelehen** 2018-08-07 14:30 UTC
Labels: Firestore

**Comment by StackHelp** [comment] 2018-11-27 04:59
@mikelehen Still have an issue. Still it shows recipe even after I deleted it from firestore.

**Comment by mikelehen** [comment] 2018-11-27 16:24
@StackHelp Sorry you're running into an issue.  If you believe you're seeing a bug in the Firestore iOS SDK, please open a new issue with as much detail as you can including detailed repro instructions. Thanks!

**Comment by mayankjanmejay** [comment] 2018-12-05 22:41
Hi, I have the same issue but on Cloud Firestore Plugin for flutter. I am loading through only about a 1000 records and they take up to 30 seconds to a minute sometimes on a 100MBps internet connection to the tablet loading the data

**Comment by MasaYanagida** [comment] 2019-02-08 13:39
I faced the same issue, however it was the problem about indexing😅
The error shows : 
```UserInfo={NSLocalizedDescription=The query requires an index. You can create it here: https://console.firebase.google.com/project/xxx/database/firestore/indexes?create_index=xxxxxxxxx}```

**Comment by reimertz** [comment] 2019-03-25 15:42
I can confirm seeing these issues as well. 

```
Object {hasPendingWrites: false, fromCache: false}
Object {hasPendingWrites: false, fromCache: true} <-- Faulty.
Object {hasPendingWrites: false, fromCache: false}
```

**Comment by wilhuff** [comment] 2019-03-26 20:58
@reimertz Please file a new issue with as much information as you can, including what query you're running. We released a fix for the original issue here [in August](https://github.com/firebase/firebase-ios-sdk/issues/1045#issuecomment-411077192).

When posting the issue it's worth collecting the logs from the SDK, by [enabling logging](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Firestore#enablelogging_).

**Comment by epebojot** [comment] 2019-10-02 11:03
I just came here simply to check if I am correct but I, somehow found out the solution:

`db.collection("cities").doc("SF")
    .onSnapshot(function(doc) {
        // Only an example
        var source = doc.metadata.hasPendingWrites ? "Local" : "Server";
        console.log(source, " data: ", doc.data());
        // Solution
        switch(source) {
         case "Server":
                            /* Put your code here. Once it appears to be true that source is equal to "Server"
                                it will stop*/
                            break;
         case "Local":
                            /* Put your code here. Once it appears to be true that source is equal to "Local"
                                it will stop*/
                           break;
          default:
             // Leave this blank if you want
             break;
        }
    });`

**Work for me 100%**

**Comment by epebojot** [comment] 2019-10-02 11:12
I just came here simply to check if my solution is correct but I somehow found out the solution:
![code](https://user-images.githubusercontent.com/38276345/66039836-8dbeab80-e548-11e9-94b8-c9476b4102a5.png)

**Comment by morganchen12** [comment] 2019-10-02 17:31
Locking responses on this issue since it's gotten mostly off-topic responses. If you're running into a Firestore bug, please [file a new issue](https://github.com/firebase/firebase-ios-sdk/issues/new).
