### ISSUE TITLE
[FR]: Replace insecure API(s) calls

### ISSUE THREAD

**Issue by DariaSukhonosova2701** [firebase/firebase-ios-sdk#10730] opened 2023-01-24 11:05 UTC
### Description

Hello!

We are using FirebaseAnalytics and FirebaseCrashlytics in our iOS app. We got warning about using insecure API(s) from the penetration testing: **The binary may contain the following insecure API calls: _printf, _memcpy, _strlen, _sscanf, _fopen, _strncpy.** We found that `memcpy` is called from the Firebase SDK. Is it possible to replace `memcpy` with secure API?

### Firebase Product(s)

Analytics, Crashlytics

**Comment by rizafran** [comment] 2023-01-24 12:35
Hi @DariaSukhonosova2701, this looks like a duplicate of #8454. Please see the comment on the ticket for more details.

**Closed** 2023-01-24 12:38 UTC
Labels: type: feature request, api: crashlytics
