### ISSUE TITLE
Failed to upgrade Firebase SDK

### ISSUE THREAD

**Issue by Blurzschyter** [firebase/firebase-ios-sdk#7796] opened 2021-03-29 00:30 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: **12.4**
  * Firebase SDK version: **7.0.0**
  * Installation method: **CocoaPods**
  * Firebase Component: **Auth, Firestore, Analytics, Crashlytics, Performance**
  * Cocopods version : **1.10.1**

### [REQUIRED] Step 2: Describe the problem

I'm currently using **Firebase SDK 6.34.0** with my project with below pods, without encountering any issues. I'm using the same Xcode 12.4.

>   pod 'Firebase/Analytics', '~> 6.34.0'
>   pod 'Firebase/Auth'
>   pod 'Firebase/Firestore'
>   pod 'FirebaseFirestoreSwift'
>   pod 'Firebase/Crashlytics'
>   pod 'Firebase/Performance'

When I'm trying to upgrade the pod to **Firebase SDK version 7.0.0**, I encounter some issues when run the **_pod install_**

![Screenshot 2021-03-29 at 8 15 55 AM](https://user-images.githubusercontent.com/23515008/112773064-0e3f6900-9067-11eb-9716-1fde78783cc6.png)

Here is my podfile:-
>   pod 'Firebase/Analytics', '~> 7.0.0'
>   pod 'Firebase/Auth'
>   pod 'Firebase/Firestore'
>   pod 'FirebaseFirestoreSwift'
>   pod 'Firebase/Crashlytics'
>   pod 'Firebase/Performance'

After that, I also try to remove the Podfile.lock file and run pod install again. 

> rm -rf Podfile.lock
> pod install

I got the same previous error with some extra additional error.
![Screenshot 2021-03-29 at 8 19 29 AM](https://user-images.githubusercontent.com/23515008/112773163-827a0c80-9067-11eb-8686-20f336e12b1b.png)

Then, I also try to do the repo update

> pod repo update
> rm -rf Podfile.lock
> pod install

and I also get the same error. T_T
![Screenshot 2021-03-29 at 8 22 36 AM](https://user-images.githubusercontent.com/23515008/112773287-fd432780-9067-11eb-9f3e-c4ef49ec0c89.png)

Appreciate if anyone can assist me with issues. 
Thank you in advance ^_^

**Comment by paulb777** [comment] 2021-03-29 14:00
@Blurzschyter This is a duplicate of #7195. Please see the resolution at https://github.com/firebase/firebase-ios-sdk/issues/7195#issuecomment-748160262

**Closed** 2021-03-29 14:01 UTC
Labels: api: core
