### ISSUE TITLE
crash with call to FPRMakeFirstSessionVerbose_block_invoke

### ISSUE THREAD

**Issue by bluelagon** [firebase/firebase-ios-sdk#8139] opened 2021-05-24 08:34 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 7.10.0
  * Installation method: `CocoaPods`
  * Firebase Component: Performance, Crashlytics, Analytics 

### [REQUIRED] Step 2: Describe the problem

Hi, I get this rare crash generating this stack trace. The user has an iPhone SE (2nd generation) and is on iOS 14.5.1.

```
OS Version: iOS 14.5.1 (18E212)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 14

Application Specific Information:
-[__NSCFString isVerbose]: unrecognized selector sent to instance 0x28136e320

Thread 14 Crashed:
0   CoreFoundation                  0x326b495b4         __exceptionPreprocess
1   libobjc.A.dylib                 0x3501487a4         objc_exception_throw
2   CoreFoundation                  0x326a4ca98         -[NSObject(NSObject) doesNotRecognizeSelector:]
3   CoreFoundation                  0x326b4c108         ___forwarding___
4   CoreFoundation                  0x326b4e6ac         __forwarding_prep_0___
5   FirebasePerformance             0x1031ca23c         __FPRMakeFirstSessionVerbose_block_invoke (FPRProtoUtils.m:382)
6   CoreFoundation                  0x326ac7418         __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
7   CoreFoundation                  0x326a2226c         -[__NSArrayI enumerateObjectsWithOptions:usingBlock:]
8   FirebasePerformance             0x1031c9594         FPRMakeFirstSessionVerbose (FPRProtoUtils.m:381)
9   FirebasePerformance             0x1031c93f8         FPRGetTraceMetric (FPRProtoUtils.m:109)
10  FirebasePerformance             0x1031b76a8         __22-[FPRClient logTrace:]_block_invoke (FPRClient.m:161)
11  libdispatch.dylib               0x326446a50         _dispatch_call_block_and_release
12  libdispatch.dylib               0x3264487e8         _dispatch_client_callout
13  libdispatch.dylib               0x3264500e4         _dispatch_lane_serial_drain
14  libdispatch.dylib               0x326450bcc         _dispatch_lane_invoke
15  libdispatch.dylib               0x32645b488         _dispatch_workloop_worker_thread
16  libsystem_pthread.dylib         0x3be1997a0         _pthread_wqthread
17  libsystem_pthread.dylib         0x3be1a0748         start_wqthread

Thread 5 name: com.google.firebase.crashlytics.MachExceptionServer
0   libsystem_kernel.dylib          0x382d0a4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x382d09880         mach_msg
2   FirebaseCrashlytics             0x1030cff34         [inlined] FIRCLSMachExceptionReadMessage (FIRCLSMachException.c:194)
3   FirebaseCrashlytics             0x1030cff34         FIRCLSMachExceptionServer (FIRCLSMachException.c:170)
4   libsystem_pthread.dylib         0x3be197bfc         _pthread_start

Thread 8
0   libsystem_kernel.dylib          0x382d30b4c         fsync
1   Foundation                      0x329245bec         _NSWriteDataToFileWithExtendedAttributes
2   GoogleDataTransport             0x1032a8938         GDTCORWriteDataToFile (GDTCORPlatform.m:287)
3   GoogleDataTransport             0x1032a293c         __47-[GDTCORFlatFileStorage storeEvent:onComplete:]_block_invoke.60 (GDTCORFlatFileStorage.m:165)
4   libdispatch.dylib               0x326446a50         _dispatch_call_block_and_release
5   libdispatch.dylib               0x3264487e8         _dispatch_client_callout
6   libdispatch.dylib               0x32644ffd0         _dispatch_lane_serial_drain
7   libdispatch.dylib               0x326450bcc         _dispatch_lane_invoke
8   libdispatch.dylib               0x32645b488         _dispatch_workloop_worker_thread
9   libsystem_pthread.dylib         0x3be1997a0         _pthread_wqthread
```

**Comment by rizafran** [comment] 2021-05-24 17:31
Hi @bluelagon, could you provide the detailed steps to reproduce the issue? Also, can you share the version of the Performance SDK that is being used? Thanks.

**Comment by bluelagon** [comment] 2021-05-25 04:20
Hi @rizafran, I do not have steps to reproduce the issue, it's a rare crash, I have only one occurence of it. The Performance SDK version being used is the 7.10.0.

**Comment by rizafran** [comment] 2021-05-28 18:34
Thanks @bluelagon. Could you try updating the Firebase Performance to the [latest version ](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/CHANGELOG.md)which contains bug fixes and latest features, and see if you'll still encounter the issue?

**Comment by paulb777** [comment] 2021-06-04 14:47
Removed needs-info tag, since fix is in progress.

**Closed** 2021-06-07 23:04 UTC
Labels: api: performance
