### ISSUE TITLE
GoogleDataTransportCCTSupport GDTCCTConstructLogEvent crash

### ISSUE THREAD

**Issue by over140** [firebase/firebase-ios-sdk#5175] opened 2020-03-24 05:38 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.20.0
  * Firebase Component: Core, Analytics, Performance
  * Component version: FirebaseCore (6.6.4), FirebaseCoreDiagnostics (1.2.2), FirebasePerformance (3.1.10), GoogleDataTransport (5.0.0), GoogleDataTransportCCTSupport (2.0.0), FirebaseAnalytics (6.3.1)
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

  * Model: iPhone XR
  * Operating System Version: iOS 13.3.1

Firebase crash log:
```
Fatal Exception: NSInvalidArgumentException
*** -[_NSPlaceholderData initWithContentsOfURL:options:maxLength:error:]: nil URL argument

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1b10c496c __exceptionPreprocess
1  libobjc.A.dylib                0x1b0ddd028 objc_exception_throw
2  Foundation                     0x1b1384eac -[NSData(NSData) initWithContentsOfFile:options:maxLength:error:]
3  Foundation                     0x1b13b1548 +[NSData(NSData) dataWithContentsOfURL:options:error:]
4  Mixin                          0x102806cec GDTCCTConstructLogEvent + 151 (GDTCCTNanopbHelpers.m:151)
5  Mixin                          0x102806874 GDTCCTConstructLogRequest + 121 (GDTCCTNanopbHelpers.m:121)
6  Mixin                          0x102806688 __GDTCCTConstructBatchedLogRequest_block_invoke + 91 (GDTCCTNanopbHelpers.m:91)
7  CoreFoundation                 0x1b1114990 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
8  CoreFoundation                 0x1b0f94b58 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
9  Mixin                          0x1028065c4 GDTCCTConstructBatchedLogRequest + 99 (GDTCCTNanopbHelpers.m:99)
10 Mixin                          0x102809750 -[GDTCCTUploader constructRequestProtoFromPackage:] + 358 (GDTCCTUploader.m:358)
11 Mixin                          0x102809038 __32-[GDTCCTUploader uploadPackage:]_block_invoke.51 + 273 (GDTCCTUploader.m:273)
12 libdispatch.dylib              0x1b0d68b7c _dispatch_call_block_and_release
13 libdispatch.dylib              0x1b0d69fd8 _dispatch_client_callout
14 libdispatch.dylib              0x1b0d70450 _dispatch_lane_serial_drain
15 libdispatch.dylib              0x1b0d70e7c _dispatch_lane_invoke
16 libdispatch.dylib              0x1b0d79f20 _dispatch_workloop_worker_thread
17 libsystem_pthread.dylib        0x1b0dcf6d0 _pthread_wqthread
18 libsystem_pthread.dylib        0x1b0dd59e8 start_wqthread
```

**Comment by mikehaney24** [comment] 2020-03-24 08:10
Probably a duplicate of #5082, fixed in next release.

**Closed by mikehaney24** 2020-03-24 08:10 UTC
Labels: GoogleDataTransport, api: core
