### ISSUE TITLE
Crashed: com.google.firebase.firestore EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x5263696e61502ebf

### ISSUE THREAD

**Issue by sspogra** [firebase/firebase-ios-sdk#8623] opened 2021-09-04 18:06 UTC
```
Crashed: com.google.firebase.firestore
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x5263696e61502ebf
0
FirebaseFirestore
firebase::firestore::immutable::impl::LlrbNodeIterator<firebase::firestore::immutable::impl::LlrbNode<firebase::firestore::model::DocumentKey, firebase::firestore::model::MutableDocument> >::AccumulateLeft(firebase::firestore::immutable::impl::LlrbNode<firebase::firestore::model::DocumentKey, firebase::firestore::model::MutableDocument> const*, std::__1::stack<firebase::firestore::immutable::impl::LlrbNode<firebase::firestore::model::DocumentKey, firebase::firestore::model::MutableDocument> const*, std::__1::deque<firebase::firestore::immutable::impl::LlrbNode<firebase::firestore::model::DocumentKey, firebase::firestore::model::MutableDocument> const*, std::__1::allocator<firebase::firestore::immutable::impl::LlrbNode<firebase::firestore::model::DocumentKey, firebase::firestore::model::MutableDocument> const*> > >*) + 72
1
FirebaseFirestore
firebase::firestore::immutable::impl::LlrbNodeIterator<firebase::firestore::immutable::impl::LlrbNode<firebase::firestore::model::DocumentKey, firebase::firestore::model::MutableDocument> >::operator++() + 84
20
libsystem_pthread.dylib
start_wqthread + 8
```

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.6.1
  * Installation method: `CocoaPods 
  * Firebase Component: Database, Firestore, Messaging, Auth, Crashlytics, Analytics, Performance

When getting data from firestore app was crashed not everytime Its a random crash.

![image](https://user-images.githubusercontent.com/49437548/132104581-250a2e9a-b8bc-4f5a-b032-b5755c30b2f9.png)

**Comment by dconeybe** [comment] 2021-09-08 13:33
Hi @sspogra. Thank you for reporting this crash. Based on the information you provided, this appears to be a duplicate of #8607, which was fixed by #8610. Although the fix is not yet released, you could test it out by following the instructions here: https://github.com/firebase/firebase-ios-sdk/issues/8612#issuecomment-911882931.

In the Xcode screenshot you provided, the left pane is too small horizontally to see what methods are in the call stack. I'm guessing that one of them is `firebase::firestore::local::LevelDbRemoteDocumentCache::GetAllExisting` and, if that is true, then this bug is definitely fixed by #8610.

If you think that this is a different crash than the duplicate mentioned above, could you reproduce it under [Address Sanitizer](https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early)? This will help produce a more useful report of the invalid memory access.

**Closed** 2021-10-08 01:03 UTC
Labels: type: bug, api: firestore, needs-info, no-recent-activity
