### ISSUE TITLE
Invalid Code Signing for Mac Catalyst App 

### ISSUE THREAD

**Issue by girishw** [firebase/firebase-ios-sdk#7291] opened 2021-01-12 17:43 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 6.33.0
  * Installation method: CocoaPods 
  * Firebase Component: 

### [REQUIRED] Step 2: Describe the problem

I am able to archive my Mac Catalyst app and upload to App Store connect. However, I get an error message from App Store connect once uploaded: 

ITMS-90284: Invalid Code Signing - The executable 'MyApp.app/Contents/Frameworks/grpcpp.framework/Versions/A/Resources/gRPCCertificates-Cpp.bundle' must be signed with the certificate that is contained in the provisioning profile

There was a previous similar issue opened and closed without resolution : [#5053](https://github.com/firebase/firebase-ios-sdk/issues/5053)

I opened a DTS with Apple and here is the response I received: 

> This error sounds like there’s an executable Mach-O binary file inside the bundle that wasn’t signed correctly. However, the code signing issue isn’t the problem that requires attention, the real issue is the presence of the bundle with an executable in the first place.

> Resource bundles aren’t supported on iOS outside of specific scenarios with Swift Package Manager — there’s never been an Xcode template to create them and thus dictate their expected structure. Many apps and frameworks have attempted to create them by starting from the macOS bundle template, and modifying the contents until they are accepted by the iOS App Store. This isn’t supported, and is fragile when the system changes, as it has with the introduction of Mac Catalyst. Since no iOS template has ever existed to build a supported bundle for iOS, there isn’t a supported way to create one for Mac Catalyst apps — any resource files should be deployed to the framework bundle instead.

**Comment by paulb777** [comment] 2021-01-12 17:52
This looks like a duplicate of #3500. I think I'll improve its title.

**Comment by girishw** [comment] 2021-01-12 18:29
@paulb777  This is despite applying the workaround. The workaround allows me to build the archive but the problem comes up again once the app is uploaded to App Store Connect. 
![Screen Shot 2021-01-12 at 10 24 15 AM](https://user-images.githubusercontent.com/32910700/104356366-b7db7900-54c0-11eb-96b2-d0dedc7fc534.png)

**Comment by paulb777** [comment] 2021-01-12 18:32
Ugh! Thanks for clarifying. Reopening.

**Comment by girishw** [comment] 2021-01-12 18:41
Any workarounds for this issue? This is holding up a release.

**Comment by girishw** [comment] 2021-01-12 21:07
@paulb777 Any way to get this working?

**Comment by paulb777** [comment] 2021-01-12 21:20
@girishw Sorry, nothing concrete to offer currently. I would suggest experimenting with removing or packaging the gRPC bundle differently.

**Comment by delasign** [comment] 2021-03-27 18:02
Has this been figured out ? I just hit this wall on App Store connect

**Comment by girishw** [comment] 2021-03-28 16:58
You can work around this with : 

1, Selecting the team in Signing & Capabilities 
2, Selecting Sign to Run Locally under Signing Certificate

**Comment by delasign** [comment] 2021-03-28 20:06
@girishw thanks for the note. You're an exceptional Samaritan.

#1 failed.
#2 BINGO.

**Comment by morganchen12** [comment] 2021-07-21 21:59
Though this is still potentially an issue that can arise in the future, I'm going to close this ticket for now since it has a workaround and does not appear to be actionable by the Firebase team. If it regresses or the workaround stops working, please comment and I'll reopen or file a new issue.

**Closed by morganchen12** 2021-07-21 21:59 UTC
Labels: Catalyst, api: firestore
