### ISSUE TITLE
User Token works even after user deleted from Firebase Console

### ISSUE THREAD

**Issue by harishvitta** [firebase/firebase-ios-sdk#10042] opened 2022-07-26 16:17 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 8.15.0
  * Installation method: Swift Package Manager
  * Firebase Component: Auth 
  * Target platform(s): iOS

### [REQUIRED] Step 2: Describe the problem
- Is there a way to check if the current user is deleted using firebase SDK?
- I am deleting the user auth entry from the Firebase console.
- User Token works fine even after the user is deleted.
#### Steps to reproduce:

What happened? How can we make the problem occur?
I have deleted the user auth record from Firebase Console.

**Comment by morganchen12** [comment] 2022-07-26 17:14
afaik this is intended behavior and re-auth will cause the user to be signed out, but an Auth team member can explain in more detail.

**Comment by paulb777** [comment] 2024-01-06 16:53
Closing for staleness. Please comment or open a new issue to continue the discussion.

**Closed by paulb777** 2024-01-06 16:53 UTC
Labels: type: question, api: auth
