### ISSUE TITLE
FIRInstanceIDTokenManager.m line 285 

### ISSUE THREAD

**Issue by mxnmike** [firebase/firebase-ios-sdk#4203] opened 2019-10-31 00:41 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.10.0_____
  * Firebase Component: InstanceID_____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 4.2.5

### [REQUIRED] Step 3: Describe the problem
The app crashes while in use.

#### Steps to reproduce:

Randomly happens

#### Relevant Code:

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18478c98c __exceptionPreprocess
1  libobjc.A.dylib                0x1844b50a4 objc_exception_throw
2  CoreFoundation                 0x1847e23f8 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1847e24d0 -[__NSCFString hasSuffix:].cold.1
4  CoreFoundation                 0x18466c36c -[__NSCFTimer retain]
5  ActiveFit                      0x10062a098 -[FIRInstanceIDTokenManager checkTokenRefreshPolicyWithIID:] + 285 (FIRInstanceIDTokenManager.m:285)
6  ActiveFit                      0x100619b6c -[FIRInstanceID didCompleteConfigure] + 693 (FIRInstanceID.m:693)
7  ActiveFit                      0x100619aa0 -[FIRInstanceID configureInstanceIDWithOptions:] + 682 (FIRInstanceID.m:682)
8  ActiveFit                      0x100619900 __37+[FIRInstanceID componentsToRegister]_block_invoke + 653 (FIRInstanceID.m:653)
9  ActiveFit                      0x1005aa844 -[FIRComponentContainer instantiateInstanceForProtocol:withBlock:] + 148 (FIRComponentContainer.m:148)
10 ActiveFit                      0x1005aa9fc -[FIRComponentContainer instanceForProtocol:] + 182 (FIRComponentContainer.m:182)
11 ActiveFit                      0x1005aa738 -[FIRComponentContainer instantiateEagerComponents] + 125 (FIRComponentContainer.m:125)
12 ActiveFit                      0x1005a70cc +[FIRApp configureWithName:options:] + 197 (FIRApp.m:197)
13 ActiveFit                      0x1005a6d30 +[FIRApp configureWithOptions:] + 139 (FIRApp.m:139)
14 ActiveFit                      0x1005a6cb8 +[FIRApp configure] + 131 (FIRApp.m:131)
15 ActiveFit                      0x1004985fc FirebaseConnection.init() + 37 (FirebaseConnection.swift:37)
```

**Comment by chliangGoogle** [comment] 2019-10-31 00:44
This is a duplicate of #4167 which will be resolved in the next release.

**Closed by chliangGoogle** 2019-10-31 00:44 UTC
Labels: api: instanceid
