### ISSUE TITLE
app crashed in -[FIRCLSReportAdapter transportBytes]

### ISSUE THREAD

**Issue by dolphinsue319** [firebase/firebase-ios-sdk#8538] opened 2021-08-17 08:22 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 beta 5, 12.5.1
  * Firebase SDK version: 8.2.0
  * Installation method: `CocoaPods`
  * Firebase Component: Crashlytics

#### Steps to reproduce:

App crashed when just launched. This kind of crash happens much ofter after we start [sending non-fatal exceptions
](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#log-excepts)

#### Relevant Code:

![截圖 2021-08-17 16 07 47](https://user-images.githubusercontent.com/1606011/129690357-20feb6a2-7dc8-4bf9-bb6b-37bfe2478a22.png)
![截圖 2021-08-17 16 21 06](https://user-images.githubusercontent.com/1606011/129690634-7e60159e-e54d-4b97-8126-5415b4b6bf89.png)

Aug.19 16:31+08:00 crashed again, I PO information.
![截圖 2021-08-19 16 31 23](https://user-images.githubusercontent.com/1606011/130163476-08fc459b-980f-42d4-bd67-44364a246c81.png)

**Comment by paulb777** [comment] 2021-08-17 14:22
@dolphinsue319 Sorry about the trouble. Are you running on an M1 Mac? If so, this could be a duplicate of #8524 which is actually an issue with Xcode 13 beta 5.

**Comment by dolphinsue319** [comment] 2021-08-17 14:24
> @dolphinsue319 Sorry about the trouble. Are you running on an M1 Mac? If so, this could be a duplicate of #8524 which is actually an issue with Xcode 13 beta 5.

My Mac is Intel CPU, not M1.

**Comment by samedson** [comment] 2021-09-22 17:06
@dolphinsue319 are you still running into this issue on newer versions of Xcode 13?

**Comment by dolphinsue319** [comment] 2021-09-29 01:26
> @dolphinsue319 are you still running into this issue on newer versions of Xcode 13?

No, it's not appear in current Xcode 13 that is download from app store.

**Comment by morganchen12** [comment] 2021-09-30 01:48
Thanks for the update. I'll mark this issue as closed, but if it regresses comment here again and we'll re-open the issue.

**Closed by morganchen12** 2021-09-30 01:48 UTC
Labels: api: crashlytics, GoogleDataTransport, Xcode 13 - iOS 15
