### ISSUE TITLE
[InAppMessaging] Ignores target and scheduling & always shows message, at least on test device

### ISSUE THREAD

**Issue by xaphod** [firebase/firebase-ios-sdk#4701] opened 2020-01-17 19:03 UTC
### [READ] Step 1: Are you in the right place?
yup

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.15.0
  * Firebase Component: InAppMessaging
  * Component version: 0.16.0

#### Steps to reproduce:

1. Create first campaign: 
- set type as banner
- in "Target" set App = this app, and User Property "pro" does not contain "true"
- in "Scheduling" remove the default event onForeground, and add a custom event. Set a breakpoint in the code at the only place this custom event is ever reported
- set start date as now, end date as Feb 1
- save campaign as draft

2. On simulator: erase all content & settings
3. Start app on simulator: make sure custom event breakpoint is never hit [ok], make sure user property "pro" is set to "true" [ok]
4. Verify in web console's DebugView that simulator's user property "pro" = "true" [ok]
5. Stop app on simulator
6. Get instance ID from xcode console, re-open draft campaign from step #1, add instance ID as Test Device, hit test
7. Start app on simulator, verify custom event breakpoint is never hit [ok]

Expected behavior:
On the first screen of the app no message is shown because the custom event was never reported and also the user property excludes this user from being targeted

Actual behavior:
The banner/message is immediately shown on the first screen of the app, ignoring targeting and scheduling.

I have also tried on real devices, no difference from simulator.

Is this a bug or expected functionality of test devices? If the latter, how to test it? I cannot launch this campaign/code without testing that it works.

**Comment by xaphod** [comment] 2020-01-17 22:18
I worked out that because none of the users in production have InAppMessaging enabled yet (we've just added it to our code), that means I can publish the campaign without knowing if it works, since users cannot actually see it yet.

This has resulted in the expected behavior occurring, which is good. (There are some other bugs - the message itself, its view, is unreadable in some cases because it doesn't come down beneath the status bar... ie. the status bar text is over top of the message's title)

However this is still a bug: I need to be able to test the behavior of campaigns + my code to make sure the result is as desired, **before** campaigns go live and users can potentially see them (for example, if I had a bug and a message was accidentally displayed to ALL users that was intended for very few). I had assumed this was what "test devices" was for, but it appears this is either a bug affecting specifically "test devices", or, this intentional. If intentional, please let me know how to test before publishing the campaign.

**Comment by christibbs** [comment] 2020-01-17 23:45
Hey @xaphod. Our current test on device flow was designed for verifying message UI. It disregards targeting parameters and shows the test message upon foregrounding (for the given instance ID). We can definitely explore targeting in test on device messages as a feature, since it seems very useful in your case.

As for the status bar UI bug, which device were you seeing this on?

**Comment by xaphod** [comment] 2020-01-17 23:56
Hi Christibbs,

Ok - I think someone should write some text on the “test devices” UI that
indicates that scheduling & targeting will be ignored. The documentation
doesn’t appear to mention this either? i realize this is in beta but good
docs will help ppl get it working faster.

You are right that there needs to be a way to test messages with scheduling
& targeting working normaly before they are published, especially because
messages can be shown when events trigger, and localization can cause
unknown truncation issues (your preview UI doesn’t seem to show the loc’d
strings so I would need to test this on device)

Status bar bug: ipad pro 11” 2018, app = wifibooth. Want a TestFlight link
with a repro or a screenshot?

**Comment by xaphod** [comment] 2020-01-20 18:05
hey @christibbs do you want me to open a new bug for the display issue on ipad pro? it's pretty ugly

**Comment by christibbs** [comment] 2020-01-21 17:51
Sure, @xaphod. Thanks for reporting this.

Agreed that we should update the documentation and work on incorporating targeting into the test flow. I'll keep this bug open to track that.

**Comment by xaphod** [comment] 2020-01-21 19:08
You're welcome. I filed the banner display issue separately as https://github.com/firebase/firebase-ios-sdk/issues/4714

**Comment by christibbs** [comment] 2020-03-06 23:00
This is a larger project to consider targeting in our test on device flow. We are adding it to our roadmap.

**Comment by JasonAHeron** [comment] 2020-05-21 18:32
Closing this because this behavior is working as intended.

**Closed by JasonAHeron** 2020-05-21 18:32 UTC
Labels: api: inappmessaging, type: feature request
