### ISSUE TITLE
Updated remote config is not activated

### ISSUE THREAD

**Issue by Skoti** [firebase/firebase-ios-sdk#5506] opened 2020-04-30 10:03 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.21.0
  * Firebase Component: `Remote Config`
  * Component version: 4.4.9
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Make a change in the remote config via Firebase.
Run the app, set `minimumFetchInterval` to `0` and call: `fetchAndActivate`
The fetch is successful but it does not activate the config.
The active config still has old values.

#### Relevant Code:

```
        let settings = RemoteConfigSettings()
        settings.minimumFetchInterval = 0
        let remoteConfig = RemoteConfig.remoteConfig()
        remoteConfig.configSettings = settings
        remoteConfig.fetchAndActivate { status, error in
        }
```

I've noticed that this is happening due to not updated etag?

For some reason the response header contains the same `ETag` as in `_settings.lastETag`, even though the fetched config `state` is `UPDATE` and it contains 12 entries whereas the current active config has only 11 entries.
https://github.com/firebase/firebase-ios-sdk/blob/a2fbd12168415cca2404835729953c4432263847/FirebaseRemoteConfig/Sources/RCNFetch.m#L479-L483
Which means it does not set a new last etag update timestamp in here:
https://github.com/firebase/firebase-ios-sdk/blob/a2fbd12168415cca2404835729953c4432263847/FirebaseRemoteConfig/Sources/RCNConfigSettings.m#L123-L126
making this check still true:
https://github.com/firebase/firebase-ios-sdk/blob/a2fbd12168415cca2404835729953c4432263847/FirebaseRemoteConfig/Sources/FIRRemoteConfig.m#L296-L297
and return an erorr of: "Most recently fetched config is already activated"
which is wrong.

**Comment by erikeldridge** [comment] 2020-04-30 20:08
Hi @Skoti . Thx for looking into the service response and client code 👍 

One thing that's unclear to me is if the issue is that the etag header isn't changing across update responses, or if the client isn't updating its etag storage correctly.

Would you mind checking the etag header in the response before and after updating config in the console?

If the etag change when the config changes, then the service is working correctly and we can focus on the client.

Thx!

**Comment by paulb777** [comment] 2020-05-08 16:57
This could be a duplicate of #4740

**Comment by Skoti** [comment] 2020-05-10 11:04
I think what paulb mentions is something different. As there the fetch request does not happen at all whereas in my case it happens but it is not updating the config.
However, I cannot reproduce this easily now. It just happened two or three times. Maybe some previous actions resulted that I wound up in such a state.
I think we can close it for now. I will reopen if I find a more reliable repro steps.

**Comment by paulb777** [comment] 2020-05-11 14:14
My understanding is that there are two factors going on that make the code snippet cause confusing behavior.

1. `remoteConfig.configSettings = settings` is asynchronous so it doesn't actually impact the subsequent `fetchAndActivate`.
2. Even after changing to zero and rerunning, the previous `fetch` does not deactivate because it was run with the longer setting.

**Closed by paulb777** 2020-05-11 14:14 UTC
Labels: api: remoteconfig, needs-attention
