### ISSUE TITLE
ERROR_WEB_INTERNAL_ERROR

### ISSUE THREAD

**Issue by jhrasco** [firebase/firebase-ios-sdk#849] opened 2018-02-26 06:04 UTC
**Environment**

  * Xcode version: _9.2_
  * Firebase SDK version: 
  * Firebase Component: Auth, Core
  * Component version: _FirebaseAuth 4.4.2, FirebaseCore 4.0.14_

**Problem Description**

Getting the error below when trying to verify phone number using PhoneAuthProvider.

`Error Domain=FIRAuthErrorDomain Code=17062 "An internal error has occurred." UserInfo={NSLocalizedDescription=An internal error has occurred., error_name=ERROR_WEB_INTERNAL_ERROR}`

The Xcode project has 2 targets. Each target has different Firebase projects. Config files (GoogleService-Info.plist) are in different directories with each config pointing to different target as describe here: [Configure Multiple Projects](https://firebase.google.com/docs/configure/).

The verification method works perfectly fine on one target (com.company.project). However, on another target (com.company.project.dev), the error above is getting returned.

Any idea what causing the error? Thank you.

**Code Snippet**

```
func sendVerificationCode(to phoneNumber: String) {
    phoneAuthProvider.verifyPhoneNumber(phoneNumber, uiDelegate: nil, completion: { (verificationID, error) in
        // Error 17062 is returned when dev target (com.company.project.dev) is running.
        completion?(error)
    })
}
```

**Comment by morganchen12** [comment] 2018-02-26 07:02
IIRC this error is returned when the webview (most likely the view used for reCAPTCHA) returns an error. There should be logs following this error describing the failure cause in more detail.

**Comment by jhrasco** [comment] 2018-02-26 07:05
@morganchen12 The weird thing is that it works on the other target of the project which uses the same source code.

**Comment by paulb777** [comment] 2018-05-04 13:55
Closing for staleness. Please reopen if still a problem.

**Closed by paulb777** 2018-05-04 13:55 UTC
Labels: Auth

**Comment by aparkertg** [comment] 2019-04-24 02:57
I'm having this error as well. Changed the bundle identifier of the app, and created a new Firebase project and iOS app. Everything else works as before, to include email and google authentication. 

However when logging in with Firebase's phone auth on the simulator, I get this message:

FIRAuthErrorUserInfoNameKey=ERROR_WEB_INTERNAL_ERROR
[{"message":"Requests from this ios client application <empty> are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}

It is generate from this block:  
phoneAuthProvider.verifyPhoneNumber(phoneNumber, uiDelegate: nil, completion: { (verificationID, error) in
        // Error 
    })

As a note this worked perfectly fine on the old project bundle identifier on the simulator via reCAPTCHA

**Comment by abegehr** [comment] 2019-05-22 08:45
@paulb777 same problem here when using phone auth. I'm using https://rnfirebase.io/ which accesses the native ios framework.
@aparkertg did you solve the problem?

**Comment by morganchen12** [comment] 2019-05-22 19:01
PERMISSION_DENIED errors are different than the error originally reported in this issue, and may be caused by rate-limiting. Please file a new issue or [support ticket](https://firebase.google.com/support).

**Comment by aparkertg** [comment] 2019-05-22 19:12
@abegehr Yes I'm using unrestricted keys for the iOS Firebase project accessed through the Google cloud platform. This was the only work around that worked with phone auth on the simulator for me.

I went back and forth with Firebase Support on this. I deleted and recreated oAuth / API keys, and created new google plist files a few times to no avail. I didn't want to use unrestricted keys, but looks like it's not to much of an issue. See below snippets from our email exchange with the support reps recommendations.

**First Email:**
I see what you mean when you mentioned that using an unrestricted API key allows the flow, but a restricted one for iOS apps will block it.

I suppose that you have followed the steps [here](https://firebase.google.com/docs/auth/ios/phone-auth).

I can also see that you have two OAuth clientIDs for iOS with the same, are you using both? if that's not the case, could you remove the one that you don't use?

**Second Email:**
Could you also remove the clientIDs you're not using for Android and Web, and download your GoogleService-Info.plist again and replace the old one?

The reason I'd like to try this is that this error sometimes happens due to a mismatch between the clientIDs you have on your XCode project, and the ones on your Firebase project.

**Final Email:**
From my side, the only thing related is that reCAPTCHA will show the project's URL instead of the app's name in the verification SMS (expected behavior).

This is so even if APNS is not available (including on real devices), reCAPTCHA flow will be followed. Also, if APNS not correctly configured, it will default to the reCAPTCHA flow. Besides you can choose to purposely use the reCAPTCHA.

To use the reCAPTCHA path, you need to disable the Push Notifications in the XCode Project > Capabilities and disable Background Refresh in Settings app of your phone. (Out of the record, once I had a case where a developer had to change his bundleId, seems his XCode project kind of kept his previous configuration).

Here's a guide for configuring [APNS with FCM](https://firebase.google.com/docs/cloud-messaging/ios/certs).

Just as a sanity check, please make sure [FirebaseApp.configure()](https://firebase.google.com/docs/reference/swift/firebasecore/api/reference/Classes/FirebaseApp#/c:objc(cs)FIRApp(cm)configure), is after AppDelegate application(_:didFinishLaunchingWithOptions:)

As I mentioned before, these sometimes happen due to a mismatch between the Firebase project and XCode project clientIds.

Now for the restricted API keys, this is information from the engineers: all of the information in the Firebase config files are essentially public after the app is published. Anyone can break down the web/Android/iOS app and get all the configurations. They are essentially unique identifiers for Firebase and Google Cloud services. There is no ability to restrict usage of Firebase and Google Cloud services to a particular app. The primary way of restricting use of Firebase APIs is with Firebase Authentication. However, if you are concerned about abusive behavior, then you'll need to observe and report to us along with the relevant information.

**Comment by abegehr** [comment] 2019-05-30 01:25
Thank you for your answer @aparkertg!
Turns out for me the error was due to an improper dev provisioning profile. I didn't follow the instructions at [https://firebase.google.com/docs/cloud-messaging/ios/certs](https://firebase.google.com/docs/cloud-messaging/ios/certs) carefully enough at the first go.
