### ISSUE TITLE
Failed to get installations token Error 

### ISSUE THREAD

**Issue by sandeeppenchala-okta** [firebase/firebase-ios-sdk#12318] opened 2024-01-25 15:41 UTC
### Description

Hello Firebase, 

We recently started seeing an issues on macOS when trying to use Feature flags, suddenly Feature flags fetch is not working and getting Failed to get installations token. I am attaching the error log when we try to fetch the Feature flags.

`{"message": "Name: firebase-remote-config, Error message: downloadConfigFailure(Error Domain=com.google.remoteconfig.ErrorDomain Code=8003 "Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: The operation couldn’t be completed. SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=Underlying error: The operation couldn’t be completed. SecItemAdd (-25308), NSUnderlyingError=0x600003d0bae0 {Error Domain=com.gul.keychain.ErrorDomain Code=0 "SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=SecItemAdd (-25308)}}}." UserInfo={NSLocalizedDescription=Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: The operation couldn’t be completed. SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=Underlying error: The operation couldn’t be completed. SecItemAdd (-25308), NSUnderlyingError=0x600003d0bae0 {Error Domain=com.gul.keychain.ErrorDomain Code=0 "SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=SecItemAdd (-25308)}}}.})", "defaultProperties": "", "location": ""}} `

Please let me know what went wrong.

### Firebase SDK Version

9.6.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Remote Config

### Targeted Platforms

macOS

### Relevant Log Output

```shell
{"message": "Name: firebase-remote-config, Error message: downloadConfigFailure(Error Domain=com.google.remoteconfig.ErrorDomain Code=8003 "Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: The operation couldn’t be completed. SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=Underlying error: The operation couldn’t be completed. SecItemAdd (-25308), NSUnderlyingError=0x600003d0bae0 {Error Domain=com.gul.keychain.ErrorDomain Code=0 "SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=SecItemAdd (-25308)}}}." UserInfo={NSLocalizedDescription=Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: The operation couldn’t be completed. SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=Underlying error: The operation couldn’t be completed. SecItemAdd (-25308), NSUnderlyingError=0x600003d0bae0 {Error Domain=com.gul.keychain.ErrorDomain Code=0 "SecItemAdd (-25308)" UserInfo={NSLocalizedFailureReason=SecItemAdd (-25308)}}}.})", "defaultProperties": "", "location": ""}}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - _NIODataStructures (2.40.0)
  - AppCenter (5.0.4):
    - AppCenter/Analytics (= 5.0.4)
    - AppCenter/Crashes (= 5.0.4)
  - AppCenter/Analytics (5.0.4):
    - AppCenter/Core
  - AppCenter/Core (5.0.4)
  - AppCenter/Crashes (5.0.4):
    - AppCenter/Core
  - Base32 (1.1.2)
  - BlueCryptor (1.0.32)
  - BlueECC (1.2.5)
  - BlueRSA (1.0.200)
  - CNIOAtomics (2.40.0)
  - CNIOBoringSSL (2.19.0)
  - CNIOBoringSSLShims (2.19.0):
    - CNIOBoringSSL (= 2.19.0)
  - CNIODarwin (2.40.0)
  - CNIOHTTPParser (2.40.0)
  - CNIOLinux (2.40.0)
  - CNIOWindows (2.40.0)
  - CocoaLumberjack (3.6.2):
    - CocoaLumberjack/Core (= 3.6.2)
  - CocoaLumberjack/Core (3.6.2)
  - CocoaLumberjack/Swift (3.6.2):
    - CocoaLumberjack/Core
  - DirectAuth (1.1.0)
  - Firebase/AnalyticsWithoutAdIdSupport (9.6.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 9.6.0)
  - Firebase/CoreOnly (9.6.0):
    - FirebaseCore (= 9.6.0)
  - Firebase/Crashlytics (9.6.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 9.6.0)
  - Firebase/Messaging (9.6.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 9.6.0)
  - Firebase/RemoteConfig (9.6.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 9.6.0)
  - FirebaseABTesting (9.6.0):
    - FirebaseCore (~> 9.0)
  - FirebaseAnalytics/WithoutAdIdSupport (9.6.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleAppMeasurement/WithoutAdIdSupport (= 9.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (9.6.0):
    - FirebaseCoreDiagnostics (~> 9.0)
    - FirebaseCoreInternal (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (9.6.0):
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCoreInternal (9.6.0):
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
  - FirebaseCrashlytics (9.6.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (9.6.0):
    - FirebaseCore (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (9.6.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Reachability (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebasePerformance (9.6.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - FirebaseRemoteConfig (~> 9.0)
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/ISASwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (9.6.0):
    - FirebaseABTesting (~> 9.0)
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
  - GoogleAppMeasurement/WithoutAdIdSupport (9.6.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.5):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.12.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.12.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.12.0)
  - GoogleUtilities/Logger (7.12.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.12.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.12.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.12.0)"
  - GoogleUtilities/Reachability (7.12.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.12.0):
    - GoogleUtilities/Logger
  - GRDB.swift/SQLCipher (6.20.2):
    - SQLCipher (>= 3.4.2)
  - Instabug (11.2.0)
  - KituraContracts (1.2.1):
    - LoggerAPI (~> 1.7)
  - LoggerAPI (1.9.200):
    - Logging (~> 1.1)
  - Logging (1.4.0)
  - nanopb (2.30909.1):
    - nanopb/decode (= 2.30909.1)
    - nanopb/encode (= 2.30909.1)
  - nanopb/decode (2.30909.1)
  - nanopb/encode (2.30909.1)
  - OCMock (3.4.3)
  - okta-ios-utils/APIGroups (1.10.2):
    - okta-ios-utils/Categories
    - RNCryptor-objc (= 3.0.6)
    - SAMKeychain (= 1.5.2)
  - okta-ios-utils/Categories (1.10.2):
    - okta-ios-utils/Utils
    - RNCryptor-objc (= 3.0.6)
    - SAMKeychain (= 1.5.2)
  - okta-ios-utils/Core (1.10.2):
    - RNCryptor-objc (= 3.0.6)
    - SAMKeychain (= 1.5.2)
  - okta-ios-utils/ForceUpgrade (1.10.2):
    - okta-ios-utils/Core
    - okta-ios-utils/Logging
    - okta-ios-utils/UI
    - okta-ios-utils/Utils
    - RNCryptor-objc (= 3.0.6)
    - SAMKeychain (= 1.5.2)
  - okta-ios-utils/Logging (1.10.2):
    - CocoaLumberjack (~> 3.6.0)
    - RNCryptor-objc (= 3.0.6)
    - SAMKeychain (= 1.5.2)
  - okta-ios-utils/UI (1.10.2):
    - RNCryptor-objc (= 3.0.6)
    - SAMKeychain (= 1.5.2)
  - okta-ios-utils/Utils (1.10.2):
    - okta-ios-utils/Core
    - okta-ios-utils/Logging
    - RNCryptor-objc (= 3.0.6)
    - SAMKeychain (= 1.5.2)
  - OktaAnalytics (2.0.2):
    - AppCenter (~> 5)
    - OktaLogger/Core (~> 1)
    - OktaSQLiteStorage (~> 0.0.3)
  - OktaAppearance/Authenticator (0.0.1):
    - OktaLocalization
  - OktaAuthFoundation (1.2.0)
  - OktaConfig/Complete (2.2.8):
    - OktaConfig/Core
    - OktaConfig/FirebaseConfig
  - OktaConfig/Core (2.2.8)
  - OktaConfig/FirebaseConfig (2.2.8):
    - Firebase/RemoteConfig (~> 9.4)
    - OktaConfig/Core
  - OktaDeviceSDK/Complete (1.0.0):
    - GRDB.swift/SQLCipher (= 6.20.2)
    - OktaJWT (~> 2)
    - OktaLogger/FileLogger (~> 1)
    - OktaSQLiteStorage (= 0.0.5)
    - OktaStorage (~> 1)
    - SQLCipher (= 4.5.5)
  - OktaJWT (2.3.5)
  - OktaLocalization (0.0.1)
  - OktaLogger (1.3.13):
    - OktaLogger/Complete (= 1.3.13)
    - SwiftLint
  - OktaLogger/Complete (1.3.13):
    - OktaLogger/FileLogger
    - OktaLogger/FirebaseCrashlytics
    - OktaLogger/InstabugLogger
    - SwiftLint
  - OktaLogger/Core (1.3.13):
    - SwiftLint
  - OktaLogger/FileLogger (1.3.13):
    - CocoaLumberjack/Swift (~> 3.6.0)
    - OktaLogger/Core
    - SwiftLint
  - OktaLogger/FirebaseCrashlytics (1.3.13):
    - Firebase/Crashlytics (~> 9.0)
    - OktaLogger/Core
    - SwiftLint
  - OktaLogger/InstabugLogger (1.3.13):
    - Instabug (= 11.2.0)
    - OktaLogger/Core
    - SwiftLint
  - OktaOAuth2 (1.2.0):
    - OktaAuthFoundation (= 1.2.0)
  - OktaOidc (3.11.1):
    - OktaOidc/AppAuth (= 3.11.1)
    - OktaOidc/Okta (= 3.11.1)
  - OktaOidc/AppAuth (3.11.1)
  - OktaOidc/Okta (3.11.1):
    - OktaOidc/AppAuth
  - OktaSQLiteStorage (0.0.5):
    - GRDB.swift/SQLCipher (= 6.20.2)
    - SQLCipher (= 4.5.5)
  - OktaStorage (1.1.3)
  - OktaWebAuthenticationUI (1.2.0):
    - OktaAuthFoundation (= 1.2.0)
    - OktaOAuth2 (= 1.2.0)
  - OneTimePassword (3.2.0):
    - Base32 (~> 1.1.2)
  - Pendo (2.21.0.7028)
  - PromisesObjC (2.3.1)
  - Resolver (1.5.0)
  - RNCryptor-objc (3.0.6)
  - SAMKeychain (1.5.2)
  - SQLCipher (4.5.5):
    - SQLCipher/standard (= 4.5.5)
  - SQLCipher/common (4.5.5)
  - SQLCipher/standard (4.5.5):
    - SQLCipher/common
  - SwiftBase32 (0.8.0)
  - SwiftCBOR (0.4.6)
  - SwiftJWT (3.6.200):
    - BlueCryptor (~> 1.0)
    - BlueECC (~> 1.1)
    - BlueRSA (~> 1.0)
    - KituraContracts (~> 1.2)
    - LoggerAPI (~> 1.7)
  - SwiftLint (0.53.0)
  - SwiftNIO (2.40.0):
    - _NIODataStructures (= 2.40.0)
    - CNIOAtomics (= 2.40.0)
    - CNIODarwin (= 2.40.0)
    - CNIOLinux (= 2.40.0)
    - CNIOWindows (= 2.40.0)
    - SwiftNIOConcurrencyHelpers (= 2.40.0)
    - SwiftNIOCore (= 2.40.0)
    - SwiftNIOEmbedded (= 2.40.0)
    - SwiftNIOPosix (= 2.40.0)
  - SwiftNIOConcurrencyHelpers (2.40.0):
    - CNIOAtomics (= 2.40.0)
  - SwiftNIOCore (2.40.0):
    - CNIOAtomics (= 2.40.0)
    - CNIOLinux (= 2.40.0)
    - SwiftNIOConcurrencyHelpers (= 2.40.0)
  - SwiftNIOEmbedded (2.40.0):
    - _NIODataStructures (= 2.40.0)
    - CNIOAtomics (= 2.40.0)
    - CNIOLinux (= 2.40.0)
    - SwiftNIOConcurrencyHelpers (= 2.40.0)
    - SwiftNIOCore (= 2.40.0)
  - SwiftNIOFoundationCompat (2.40.0):
    - _NIODataStructures (= 2.40.0)
    - CNIOAtomics (= 2.40.0)
    - CNIODarwin (= 2.40.0)
    - CNIOLinux (= 2.40.0)
    - CNIOWindows (= 2.40.0)
    - SwiftNIO (= 2.40.0)
    - SwiftNIOConcurrencyHelpers (= 2.40.0)
    - SwiftNIOCore (= 2.40.0)
    - SwiftNIOEmbedded (= 2.40.0)
    - SwiftNIOPosix (= 2.40.0)
  - SwiftNIOHTTP1 (2.40.0):
    - _NIODataStructures (= 2.40.0)
    - CNIOAtomics (= 2.40.0)
    - CNIODarwin (= 2.40.0)
    - CNIOHTTPParser (= 2.40.0)
    - CNIOLinux (= 2.40.0)
    - CNIOWindows (= 2.40.0)
    - SwiftNIO (= 2.40.0)
    - SwiftNIOConcurrencyHelpers (= 2.40.0)
    - SwiftNIOCore (= 2.40.0)
    - SwiftNIOEmbedded (= 2.40.0)
    - SwiftNIOPosix (= 2.40.0)
  - SwiftNIOPosix (2.40.0):
    - _NIODataStructures (= 2.40.0)
    - CNIOAtomics (= 2.40.0)
    - CNIODarwin (= 2.40.0)
    - CNIOLinux (= 2.40.0)
    - CNIOWindows (= 2.40.0)
    - SwiftNIOConcurrencyHelpers (= 2.40.0)
    - SwiftNIOCore (= 2.40.0)
  - SwiftNIOSSL (2.19.0):
    - _NIODataStructures (< 3, >= 2.32.0)
    - CNIOAtomics (< 3, >= 2.32.0)
    - CNIOBoringSSL (= 2.19.0)
    - CNIOBoringSSLShims (= 2.19.0)
    - CNIODarwin (< 3, >= 2.32.0)
    - CNIOLinux (< 3, >= 2.32.0)
    - CNIOWindows (< 3, >= 2.32.0)
    - SwiftNIO (< 3, >= 2.32.0)
    - SwiftNIOConcurrencyHelpers (< 3, >= 2.32.0)
    - SwiftNIOCore (< 3, >= 2.32.0)
    - SwiftNIOEmbedded (< 3, >= 2.32.0)
    - SwiftNIOPosix (< 3, >= 2.32.0)
    - SwiftNIOTLS (< 3, >= 2.32.0)
  - SwiftNIOTLS (2.40.0):
    - _NIODataStructures (= 2.40.0)
    - CNIOAtomics (= 2.40.0)
    - CNIODarwin (= 2.40.0)
    - CNIOLinux (= 2.40.0)
    - CNIOWindows (= 2.40.0)
    - SwiftNIO (= 2.40.0)
    - SwiftNIOConcurrencyHelpers (= 2.40.0)
    - SwiftNIOCore (= 2.40.0)
    - SwiftNIOEmbedded (= 2.40.0)
    - SwiftNIOPosix (= 2.40.0)
  - ViewInspector (0.9.9)

DEPENDENCIES:
  - AppCenter (~> 5)
  - Firebase/AnalyticsWithoutAdIdSupport (= 9.6.0)
  - Firebase/Crashlytics (= 9.6.0)
  - Firebase/Messaging (= 9.6.0)
  - Firebase/RemoteConfig (= 9.6.0)
  - FirebasePerformance (= 9.6.0)
  - GRDB.swift/SQLCipher (~> 6.20.2)
  - Instabug (= 11.2.0)
  - OCMock (~> 3.4.3)
  - OktaLogger (= 1.3.13)
  - OktaOidc (= 3.11.1)
  - OktaSQLiteStorage (= 0.0.5)
  - OktaWebAuthenticationUI (= 1.2.0)
  - Pendo (= 2.21.0.7028)
  - Resolver (= 1.5.0)
  - SAMKeychain (= 1.5.2)
  - SQLCipher (~> 4.5.5)
  - SwiftBase32 (~> 0.8.0)
  - SwiftCBOR (= 0.4.6)
  - SwiftJWT (~> 3.6.2)
  - SwiftLint (= 0.53.0)
  - SwiftNIO (= 2.40.0)
  - SwiftNIOFoundationCompat (= 2.40)
  - SwiftNIOHTTP1 (= 2.40.0)
  - SwiftNIOSSL (= 2.19.0)
  - ViewInspector (= 0.9.9)

SPEC REPOS:
  trunk:
    - _NIODataStructures
    - AppCenter
    - Base32
    - BlueCryptor
    - BlueECC
    - BlueRSA
    - CNIOAtomics
    - CNIOBoringSSL
    - CNIOBoringSSLShims
    - CNIODarwin
    - CNIOHTTPParser
    - CNIOLinux
    - CNIOWindows
    - CocoaLumberjack
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebasePerformance
    - FirebaseRemoteConfig
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - GRDB.swift
    - Instabug
    - KituraContracts
    - LoggerAPI
    - Logging
    - nanopb
    - OCMock
    - OktaAnalytics
    - OktaAuthFoundation
    - OktaJWT
    - OktaLogger
    - OktaOAuth2
    - OktaOidc
    - OktaSQLiteStorage
    - OktaStorage
    - OktaWebAuthenticationUI
    - Pendo
    - PromisesObjC
    - Resolver
    - RNCryptor-objc
    - SAMKeychain
    - SQLCipher
    - SwiftBase32
    - SwiftCBOR
    - SwiftJWT
    - SwiftLint
    - SwiftNIO
    - SwiftNIOConcurrencyHelpers
    - SwiftNIOCore
    - SwiftNIOEmbedded
    - SwiftNIOFoundationCompat
    - SwiftNIOHTTP1
    - SwiftNIOPosix
    - SwiftNIOSSL
    - SwiftNIOTLS
    - ViewInspector



SPEC CHECKSUMS:
  _NIODataStructures: 3d45d8e70a1d17a15b1dc59d102c63dbc0525ffd
  AppCenter: 85c92db0759d2792a65eb61d6842d2e86611a49a
  Base32: 163c298644d184e89ca4e00a996bad6bf5166390
  BlueCryptor: b0aee3d9b8f367b49b30de11cda90e1735571c24
  BlueECC: 0d18e93347d3ec6d41416de21c1ffa4d4cd3c2cc
  BlueRSA: dfeef51db96bcc4edec654956c1581adbda4e6a3
  CNIOAtomics: 8edf08644e5e6fa0f021c239be9e8beb1cd9ef18
  CNIOBoringSSL: 2c9c96c2e95f15e83fb8d26b9738d939cc39ae33
  CNIOBoringSSLShims: c5c9346e7bbd1040f4f8793a35441dda7487539a
  CNIODarwin: 93850990d29f2626b05306c6c9309f9be0d74c2f
  CNIOHTTPParser: 8ce395236fa1d09ac3b4f4bcfba79b849b2ac684
  CNIOLinux: 62e3505f50de558c393dc2f273dde71dcce518da
  CNIOWindows: 3047f2d8165848a3936a0a755fee27c6b5ee479b
  CocoaLumberjack: bd155f2dd06c0e0b03f876f7a3ee55693122ec94
  DirectAuth: 816f9d6889ab0449b139a735c6bb065a90c165f3
  Firebase: 5ae8b7cf8efce559a653aef0ad95bab3f427c351
  FirebaseABTesting: 61826730ce9eee8781ba99a2b3420e9bce148dc9
  FirebaseAnalytics: 89ad762c6c3852a685794174757e2c60a36b6a82
  FirebaseCore: 2082fffcd855f95f883c0a1641133eb9bbe76d40
  FirebaseCoreDiagnostics: 99a495094b10a57eeb3ae8efa1665700ad0bdaa6
  FirebaseCoreInternal: bca76517fe1ed381e989f5e7d8abb0da8d85bed3
  FirebaseCrashlytics: 3210572ddb77801e5a0bd9d7bc890769f2066a0c
  FirebaseInstallations: 0a115432c4e223c5ab20b0dbbe4cbefa793a0e8e
  FirebaseMessaging: a4d7910e4af663c9cbfc1071c5bef34651690949
  FirebasePerformance: f1e62598cd98c88ce6c10e0d26223d18b85c26d6
  FirebaseRemoteConfig: ee09d77a7d7c7e31da6a0d1cf956cd611c85609c
  GoogleAppMeasurement: 6de2b1a69e4326eb82ee05d138f6a5cb7311bcb1
  GoogleDataTransport: 54dee9d48d14580407f8f5fbf2f496e92437a2f2
  GoogleUtilities: 0759d1a57ebb953965c2dfe0ba4c82e95ccc2e34
  GRDB.swift: 3eb7447131d897afb420d6877a45fd8bfca313c1
  Instabug: 2153fb2bc805bca730ce97251e3dc6cd04864171
  KituraContracts: e845e60dc8627ad0a76fa55ef20a45451d8f830b
  LoggerAPI: ad9c4a6f1e32f518fdb43a1347ac14d765ab5e3d
  Logging: beeb016c9c80cf77042d62e83495816847ef108b
  nanopb: d4d75c12cd1316f4a64e3c6963f879ecd4b5e0d5
  OCMock: 43565190abc78977ad44a61c0d20d7f0784d35ab
  okta-ios-utils: 67ce11b4b2e17e418f19672c07e48d8691a91f46
  OktaAnalytics: 11859f96f36472b229de6be82e53001b3b07e82e
  OktaAppearance: b84cb00f8798f8fd2a5b1d7c7f8739bea582320a
  OktaAuthFoundation: a90bf940c2a098bf409143f26d12e1d31ca07772
  OktaConfig: e2a6952c9abb7a68f4ecb99fc27eea08f626c7da
  OktaDeviceSDK: c3872e13a4f2cc36d81ce7d74065678e0297e5f7
  OktaJWT: d9934b947fd0742713557b9ab9e1a313d40751cc
  OktaLocalization: 068e8d05cba76ec93937dc91f00d505f6f62a740
  OktaLogger: 7182911930a14a369aca9a655de56b96c74d2b8e
  OktaOAuth2: 79e7438a8e4f7e5e70bc82c599108ab59de76921
  OktaOidc: 94d65a417fefbdd92441a6e8b8347e2db2ea885a
  OktaSQLiteStorage: 4761bb59ed2d6fc2ba6184a4fdd79f2fbeadc50c
  OktaStorage: d5b39f93156832a1baed052be537e9e79b3adf7a
  OktaWebAuthenticationUI: 6442001304564804fe61f8ef67394be3d8edd70f
  OneTimePassword: 9e9ab17be982ce0d4891c728d2ab738ab14d1c7e
  Pendo: 88b9c42bea339a20402e51ff9d46d36526649732
  PromisesObjC: c50d2056b5253dadbd6c2bea79b0674bd5a52fa4
  Resolver: 68984624572763018fd8ec7b8e3e8df0e3b6bba5
  RNCryptor-objc: d1b228f9c02e2173df063f0617684c134aed890e
  SAMKeychain: 1865333198217411f35327e8da61b43de79b635b
  SQLCipher: f2e96b3822e3006b379181a0e4fd145f6de29b56
  SwiftBase32: 723fd05e2fce776f2b98f26fe423bd20fa80e411
  SwiftCBOR: 7ccf87a679e1981d3232b171a462b8863a6cb12e
  SwiftJWT: 88c412708f58c169d431d344c87bc79a87c830ae
  SwiftLint: 5ce4d6a8ff83f1b5fd5ad5dbf30965d35af65e44
  SwiftNIO: 829958aab300642625091f82fc2f49cb7cf4ef24
  SwiftNIOConcurrencyHelpers: 697370136789b1074e4535eaae75cbd7f900370e
  SwiftNIOCore: 473fdfe746534d7aa25766916459eeaf6f92ef49
  SwiftNIOEmbedded: ffcb5147db67d9686c8366b7f8427b36132f2c8a
  SwiftNIOFoundationCompat: b9cdbea4806e4a12e9f66d9696fa3b98c4c3232b
  SwiftNIOHTTP1: ef56706550a1dc135ea69d65215b9941e643c23b
  SwiftNIOPosix: b49af4bdbecaadfadd5c93dfe28594d6722b75e4
  SwiftNIOSSL: d153c5a6fc5b2301b0519b4c4d037a9414212da6
  SwiftNIOTLS: 598af547490133e9aac52aed0c23c4a90c31dcfc
  ViewInspector: 0150f3c4900dc74b14344a985d6bb6c3f8e2e140

PODFILE CHECKSUM: 8ae71d9f014d63bf00eadd425740bec19f3fbaff

COCOAPODS: 1.14.3


```

</details>

**Comment by sandeeppenchala-okta** [comment] 2024-01-26 18:38
@paulb777 we tried uninstall and re-installing the app but didn't fix the issue because uninstalling won't delete Keychains

**Comment by SMYdamao** [comment] 2024-04-10 10:06
I also encountered this problem, who can provide a solution? Waiting online

**Comment by FurkanSimsir** [comment] 2024-04-22 12:42
I too experienced the same issue which appears to be tied to a keychain-related problem, possibly because Firebase may not permit keychain access from the simulator. 

The issue doesn't arise in production builds like TestFlight. I also discovered that enabling the Keychain Sharing Capability allows it to function in the simulator, though I'm uncertain of any potential implications.

**Comment by MichaelVerdon** [comment] 2024-11-29 09:52
This issue appears to be a duplicate of https://github.com/firebase/firebase-ios-sdk/issues/12291 so I am closing this. Feel free to reopen if needed and if so, please try it out on the latest Firebase version.

**Closed by MichaelVerdon** 2024-11-29 09:52 UTC
Labels: api: remoteconfig, macOS
