### ISSUE TITLE
FR: Add the ability for Firebase/Analytics

### ISSUE THREAD

**Issue by redimongo** [firebase/firebase-ios-sdk#6762] opened 2020-10-18 09:54 UTC
### Feature proposal

* Firebase Component: Analytics

Describe your use case and/or feature request here.

We currently use SwiftUI and have developed our app to work with iOS and tvOS however we have noticed that tvOS does not support analytics. How are we meant to track who is using our app via tvOS - I get it from a money point of view Google can put clickable ads in front of those people so why invest in the technology.

But surely Google understands the power of being able to track if a user is watching a video that is about cars or listening to pop music. This would help us in our iOS app as Google would have more user/household data.

I would love to see analytics come to tvOS

**Comment by paulb777** [comment] 2020-10-18 13:44
Closing as a duplicate of #2011. Please add a thumbs up there.

**Closed by paulb777** 2020-10-18 13:44 UTC
Labels: api: analytics, type: feature request
