### ISSUE TITLE
`FirebaseCoreExtension` pod is missing unless you install `Firebase/Storage` pod.

### ISSUE THREAD

**Issue by russellwheatley** [firebase/firebase-ios-sdk#9936] opened 2022-06-22 16:21 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 9.2.0 (Started to appear in => 9.0.0)
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Core
  * Target platform(s): ` iOS (haven't checked the others)`

#### Steps to reproduce:

At FlutterFire, we need to use the `FirebaseCoreExtension` pod which ought to come as a dependency of Core. It doesn't appear unless you also have `Firebase/Storage` pod installed.

I've created a repo with steps to follow to show you the reproduction. I believe it is a bug, but maybe it is by design.

#### Relevant Code:

https://github.com/invertase/firebasecoreextension-issue

**Comment by paulb777** [comment] 2022-06-22 16:25
This is by design. FirebaseCoreExtension is only needed for Firebase libraries with Swift implementations, which is currently Storage and Functions. 

I'll close the issue, but feel free to continue the discussion.

**Closed by paulb777** 2022-06-22 16:25 UTC
Labels: api: core
