### ISSUE TITLE
Firebase app crashes on startup (EXC_BREAKPOINT)

### ISSUE THREAD

**Issue by rawandahmad698** [firebase/firebase-ios-sdk#3283] opened 2019-06-28 22:57 UTC
I recently updated my project and all of my pods were updated aswell. I always keep a copy of my previous app version. 

My podfile: 

    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Firestore'
    pod 'Firebase/Performance'
    pod 'Firebase/Database'
    pod 'Firebase/InAppMessagingDisplay'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Analytics'

My AppDelegate: 

    override init() {
        FirebaseApp.configure()    
    }

This crash happens everytime i run the app on the simulator/physical device. And i get: 

[![Image][1]][1]

There is no error. Nothing to fix on my end, However it is stopping us from developing another version of the app.

  [1]: https://i.stack.imgur.com/1xCAM.png

**Stackoverflow  [*link*`](https://stackoverflow.com/questions/56813894/firebase-app-crashes-on-startup-exc-breakpoint)

**Comment by paulb777** [comment] 2019-06-29 00:49
We'll likely need at least a backtrace and ideally a reproducible example to help.

From this information, it looks like it might be a duplicate of #3270

**Comment by rawandahmad698** [comment] 2019-06-29 17:09
Hi @paulb777. I cannot show a reproducible example for this app. As i just installed the pods and ran the app in the simulator/physical device. No logic in the app, just a simple view with a black background.

**Comment by ivanvorobei** [comment] 2019-06-30 20:23
In all my apps this bug 
only in `iOS 13 Beta 2`
Crash in this line.

**Comment by andreaslindahl** [comment] 2019-07-01 08:11
Only crashes on iOS 13 for me as well.

**Comment by ryanwilson** [comment] 2019-07-02 14:48
Thanks for the reports - I am able to reproduce in beta 2 and will try to track down the issue.

@rawandahmad698 as a side note, `FirebaseApp.configure()` should go in `application(_:didFinishLaunchingWithOptions:)` and `AppDelegate` should not have an overridden `init` method.

**Comment by ivanvorobei** [comment] 2019-07-02 15:14
@ryanwilson How soon can we wait for the update?

**Comment by ryanwilson** [comment] 2019-07-02 15:18
@ivanvorobei for a status update, as soon as I discover the root issue and fix. I believe I have an idea as to what's going on (locking on a serial thread) but need to find the best solution to get around this, I'm not sure why it's only crashing on iOS 13.

For a patch to fix this, it depends on how long it takes but we're working hard on it and will report as soon as we know.

**Comment by paulb777** [comment] 2019-07-02 19:07
Closing in favor of the original #3270. Please follow conversation there.

**Closed by paulb777** 2019-07-02 19:07 UTC
Labels: api: instanceid
