### ISSUE TITLE
Can't compile with Xcode 13.2 beta 2

### ISSUE THREAD

**Issue by integer256** [firebase/firebase-ios-sdk#8990] opened 2021-11-20 18:06 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2 beta 2
  * Firebase SDK version: 8.8.0
  * Installation method: ` Swift Package Manager` (select one)
  * Firebase Component: Crashlytics

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Trying to compile it, [line 191](https://github.com/firebase/firebase-ios-sdk/blob/fb0a2e0a8ee5ff68783fba9db784a604fba433cc/Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m#L191) [line 238](https://github.com/firebase/firebase-ios-sdk/blob/fb0a2e0a8ee5ff68783fba9db784a604fba433cc/Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m#L238) and [line 300](https://github.com/firebase/firebase-ios-sdk/blob/fb0a2e0a8ee5ff68783fba9db784a604fba433cc/Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m#L191) outputs the error: `Expected a platform name here`

**Comment by paulb777** [comment] 2021-11-21 02:26
@integer256 Thanks for the report.

Please confirm the Xcode version.  I don't reproduce with Xcode 13.1 or Xcode 13.2 beta. 

Are you using Xcode 13.2 beta 2?

**Comment by mihaicris-adoreme** [comment] 2021-11-21 10:31
@paulb777 About me...I am using stable Xcode Version 13.1 (13A1030d)

**Comment by integer256** [comment] 2021-11-21 13:44
yes, @paulb777 I am using Xcode 13.2 beta 2

**Comment by ryanwilson** [comment] 2021-11-22 19:33
Hi @integer256, I tried to reproduce the issue by:

1. Created a new Xcode project using Xcode 13.2 beta 2
2. Added Crashlytics with SwiftPM in an iOS, Catalyst, and macOS target
3. Imported Firebase, and made an arbitrary Crashlytics API call.
4. Compiled successfully.

Can you please share anything that may be different in your setup, or a reproducible project? I'm curious if you create a brand new Xcode project and add Crashlytics if you run into the same error. That will help determine if it's an issue with your specific project as well.

**Comment by integer256** [comment] 2021-11-22 21:24
@ryanwilson thanks for checking.

Does your project has the `CLS_METRICKIT_SUPPORTED` flag on? Given that the conflicting code is under that compiler flag. 

In case you can not reproduce it with that flag on, I can setup a quick project to reproduce it

**Comment by paulb777** [comment] 2021-11-22 21:45
`CLS_METRIC_KIT_SUPPORTED` is defined in the source: 

Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h:#define CLS_METRICKIT_SUPPORTED (__has_include(<MetricKit/MetricKit.h>) && TARGET_OS_IOS)

A reproducible project would be helpful.

**Comment by ryanwilson** [comment] 2021-11-22 21:48
As @paulb777 mentioned, it's from [the source](https://github.com/firebase/firebase-ios-sdk/blob/edbd0129799f8eb1a2146070394a6e2f2d95b958/Crashlytics/Crashlytics/Helpers/FIRCLSCallStackTree.h#L17
). I verified that this is resolving as `1` in my local setup.

**Comment by integer256** [comment] 2021-11-23 19:04
1. To setup the project please first install Tuist:

`curl -Ls https://install.tuist.io | bash`

2. Then fetch the dependencies using:

`tuist dependencies fetch`

3. To generate the Xcode project (here is the error):

`tuist generate`

4. Open `FirebaseSpm.xcworkspace` with Xcode 13.2 Beta 2

5. Build the App target 

[firebase-spm.zip](https://github.com/firebase/firebase-ios-sdk/files/7590440/firebase-spm.zip)

**Comment by integer256** [comment] 2021-11-23 19:05
@paulb777 I am using Tuist.io because it is easy to create project and we use that tool at SoundCloud, but it happens the same using the Apple Tooling

**Comment by paulb777** [comment] 2021-11-23 19:55
Thanks for the repro case. Would you send us a version that doesn't depend pm tuist?  Otherwise I think the issue might be related to tuist?

**Comment by gistya** [comment] 2021-11-24 02:08
I should note, `TARGET_OS_IOS` is undefined in Xcode 13 when compiling with a deployment target of iOS 14 or higher.

**Comment by integer256** [comment] 2021-11-24 09:51
@gistya yes, I meant `Xcode 13.2 beta 2`. Thanks for the heads up

**Comment by ryanwilson** [comment] 2021-11-24 14:24
> I should note, `TARGET_OS_IOS` is undefined in Xcode 13 when compiling with a deployment target of iOS 14 or higher.

I don't believe that's the case otherwise a significant amount of our other code would break, you can verify it exists by looking at `TargetConditionals.h` (using `Cmd+Shift+O` to quick open the file). In the iOS 15.2 SDK I see it defined.

**Comment by integer256** [comment] 2021-12-03 17:23
@paulb777 did you give it a try to the project I sent you? Tuist is only creating the Xcode project files. It doesn't modify the Firebase SDK

**Comment by paulb777** [comment] 2021-12-03 17:39
@integer256 I gave a try and ran into issues using Tuist and didn't have the bandwidth to sort through.  As @ryanwilson pointed out, it looks like something in the build environment is corrupting `TARGET_OS_IOS` and we'll be happy to investigate if it's reproducible in a standalone Xcode project.

**Closed** 2021-12-17 02:03 UTC
Labels: api: crashlytics, needs-info, no-recent-activity
