### ISSUE TITLE
macOS code signing error

### ISSUE THREAD

**Issue by AndriyGo** [firebase/firebase-ios-sdk#2836] opened 2019-04-15 23:31 UTC
I am completely puzzled as to why I get a code signing error AFTER my binary is uploaded to the Mac App Store.

I have the following pods attachec to my macOS app:

```
pod 'FirebaseCore'
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'
    pod 'FirebaseFunctions'
```

after I upload my binary I receive the following error in an email:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Driving Theory Test 2019 (UK)". Please correct the following issues, then upload again.

Invalid Signature - The main app bundle Driving Theory Test 2019 (UK) at path Driving Theory Test 2019 (UK).app has following signing error(s): --prepared:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/GoogleUtilities.framework/Versions/Current/. --validated:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/GoogleUtilities.framework/Versions/Current/. --prepared:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework/Versions/Current/. --validated:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework/Versions/Current/. /Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app: embedded framework contains modified or invalid version In subcomponent: /Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Invalid Signature - The nested app bundle grpc at path Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework has following signing error(s): bundle format unrecognized, invalid, or unsuitable . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Invalid Signature - The nested app bundle grpcpp at path Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpcpp.framework has following signing error(s): bundle format unrecognized, invalid, or unsuitable . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Invalid Signature - The nested app bundle openssl_grpc at path Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework has following signing error(s): bundle format unrecognized, invalid, or unsuitable . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Unable to Sign - This package doesn't meet the current code signing requirements. For more information, see the Code Signing and Application Sandboxing Guide and Technical Note 2206.

Specifically, codesign generated the following error:

        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework/Versions/src: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpcpp.framework/Versions/src: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/crypto: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/ssl: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/third_party: bundle format unrecognized, invalid, or unsuitable
Malformed Framework - The framework bundle grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework) Info.plist for Versions/src is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle grpcpp (Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpcpp.framework) Info.plist for Versions/src is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle openssl_grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework) Info.plist for Versions/crypto is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle openssl_grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework) Info.plist for Versions/ssl is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle openssl_grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework) Info.plist for Versions/third_party is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Best regards,

The App Store Team
```

I am not surre if this is a right place to post my issue, but I hope that someone will be able to assist me or redirect me to the right place.

**Comment by paulb777** [comment] 2019-04-15 23:55
Looks like an issue related to dynamic frameworks. If it's possible for you, removing `use_frameworks!` from the Podfile might be a workaround.

**Comment by AndriyGo** [comment] 2019-04-16 00:23
@paulb777 thank you very much for your suggestion. I am now getting an error `
`

**Comment by wilhuff** [comment] 2019-04-16 00:50
Separately though it appears that you're getting portions of the gRPC source tree mixed into the output framework. `grpc.framework/Versions/src` isn't supposed to be there. I can see this in my local build intermediates as well.

While removing `use_frameworks!` could alleviate the problem by statically linking your binary, the root cause is that gRPC's pod is creating an invalid Framework.

**Comment by wilhuff** [comment] 2019-04-16 01:27
The CocoaPods-generated project appears to be broken (at least in my case). There's a section for copying public headers:

```
                D1BA65AC4BB74572A3CB5B695CD48A42 /* Copy ../../src/core/ext/filters/client_channel Public Headers */ = {
                        isa = PBXCopyFilesBuildPhase;
                        buildActionMask = 2147483647;
                        dstPath = "$(PUBLIC_HEADERS_FOLDER_PATH)/../../src/core/ext/filters/client_channel";
                        dstSubfolderSpec = 16;
                        files = (
                            ...
```

In my build for `gRPC-Core-macOS`, `PUBLIC_HEADERS_FOLDER_PATH` resolves to `grpc.framework/Versions/A/Headers` which is right, but copying into `../../` would be wrong and would generate this result.

Looking through the [gRPC-Core.podspec](https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec) there's no mention of `../..`, so I suspect that this is a bug in CocoaPods.

**Comment by paulb777** [comment] 2019-04-16 04:13
Does the version of CocoaPods make a difference?  `pod --version`

**Comment by wilhuff** [comment] 2019-04-16 15:00
I'm on 1.6.1.

**Comment by AndriyGo** [comment] 2019-04-16 15:12
I have upgraded to 1.6.1 but now `pod update` gets stuck during "Resolving dependencies" step. I thought that maybe newer version would fix the issue :(

**Comment by AndriyGo** [comment] 2019-04-16 15:26
I was having this issue on 1.5.x version.

**Comment by AndriyGo** [comment] 2019-04-17 13:15
@paulb777 @wilhuff so should I open this as an issue on CocoaPods GitHub page?

**Comment by paulb777** [comment] 2019-04-17 13:57
@AndriyGo It can't hurt to open a CocoaPods issue, although you should check if it's fixed in the CocoaPods 1.7.0 beta first. 

Either way I'll try to take a deeper look in the next few days.

**Comment by paulb777** [comment] 2019-04-17 17:01
Tracked, discussed and workaround at https://github.com/CocoaPods/CocoaPods/issues/7788

**Comment by paulb777** [comment] 2019-04-23 21:04
Resolved in https://github.com/CocoaPods/CocoaPods/issues/8719 and continued tracking in CocoaPods/CocoaPods#7788

**Closed by paulb777** 2019-04-23 21:04 UTC
Labels: GoogleUtilities, api: firestore, macOS
