### ISSUE TITLE
Archiving fails at Firestore  5.2.0 Pod (4 issues)

### ISSUE THREAD

**Issue by Rovel** [firebase/firebase-ios-sdk#1412] opened 2018-06-14 19:49 UTC
The app runs fine on the simulator and device, I already had sent it to the testflight in the past.
Today I just updated the firebase pods, tested it in the simulator and archived, by the end of the archive it fails pointing to the firestore pod

  * Xcode version: Version 9.4.1 (9F2000)
  * Firebase SDK version:  5.2.0
  * Firebase Component: Firestore
  * Component version: 5.2.0

#### Steps to reproduce:

1. Add Firebase/Firestore to the podfile (latest, mine was an upgrade)
2. pod install or update
3. Open Worskpace
2. Product -> Archive

#### Relevant Code:

*Error print*
![screen shot 2018-06-14 at 16 29 13](https://user-images.githubusercontent.com/2469500/41434724-17295d7e-6ff3-11e8-9ade-62d936e6d6a0.png)

*Podfile*
```
# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'xxx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for xxx
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'

  target 'xxx' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xxx' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

*Firestore @ Podfile.lock*
```
- Firebase/Firestore (5.2.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 0.12.3)
```

**Comment by paulb777** [comment] 2018-06-14 19:52
This is a duplicate of #1266. See the status and workarounds there.

**Closed by paulb777** 2018-06-14 19:52 UTC
Labels: Firestore
