### ISSUE TITLE
Crash on Main Thread: pb_check_proto3_default_value in Firebase Sessions with nanopb Encoding Error (iOS)

### ISSUE THREAD

**Issue by apoorv-trikha-ev** [firebase/firebase-ios-sdk#14091] opened 2024-11-12 04:25 UTC
### Description

Our iOS app experiences a recurring crash on the main thread during Firebase Sessions data encoding. The crash originates in the nanopb function pb_check_proto3_default_value, likely due to an issue with encoding default values in Protocol Buffers. This encoding error propagates through GoogleDataTransport, particularly affecting GDTCOREvent setDataObject:, and ultimately causes a fatal crash.

Key Details:

Firebase Components Involved: FirebaseSessions, FirebaseInstallations, GoogleDataTransport
Crash Location: Main thread
Observed SDK Versions: Firebase SDK version **10.21.0**

### Reproducing the issue

The issue is intermittent. Happened in prod and TestFlight builds of our app as well. We don't have any hard steps to reproduce. The app crashes as soon as it is launched.

### Firebase SDK Version

10.21.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
# Crashlytics - Stack trace
# Application: com.eagleview.FalconProd
# Platform: apple
# Version: 2.17.0 (24)
# Issue: 3425c2f51c062f1db3c2b0b105065610
# Session: 8c7ca7408d3d48d49f542ecfb31bcae0_DNE_0_v2
# Date: Mon Nov 11 2024 17:30:30 GMT+0530 (India Standard Time)

Crashed: com.apple.main-thread
0  nanopb                         0x6904 pb_check_proto3_default_value + 342
1  nanopb                         0x6074 pb_encode + 172
2  FirebaseSessions               0x413c (Missing UUID 695ae8a68da13b868459ebe687e43652)
3  FirebaseSessions               0xf030 (Missing UUID 695ae8a68da13b868459ebe687e43652)
4  FirebaseSessions               0xf2b8 (Missing UUID 695ae8a68da13b868459ebe687e43652)
5  GoogleDataTransport            0xdfd0 -[GDTCOREvent setDataObject:] + 68
6  GoogleDataTransport            0xde60 -[GDTCOREvent copy] + 72
7  GoogleDataTransport            0x1b070 -[GDTCORTransport sendEvent:onComplete:] + 44
8  FirebaseSessions               0xa740 (Missing UUID 695ae8a68da13b868459ebe687e43652)
9  FirebaseSessions               0x5ef0 (Missing UUID 695ae8a68da13b868459ebe687e43652)
10 FirebaseSessions               0x5f74 (Missing UUID 695ae8a68da13b868459ebe687e43652)
11 FirebaseSessions               0xd0bc (Missing UUID 695ae8a68da13b868459ebe687e43652)
12 FirebaseSessions               0xd2bc (Missing UUID 695ae8a68da13b868459ebe687e43652)
13 FirebaseSessions               0xaaf0 (Missing UUID 695ae8a68da13b868459ebe687e43652)
14 FirebaseSessions               0xa9b4 (Missing UUID 695ae8a68da13b868459ebe687e43652)
15 FirebaseInstallations          0x49c0 __49-[FIRInstallations installationIDWithCompletion:]_block_invoke + 56
16 FBLPromises                    0x5138 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.18 + 52
17 libdispatch.dylib              0x61c9c _dispatch_call_block_and_release + 24
18 libdispatch.dylib              0x62cc0 _dispatch_client_callout + 16
19 libdispatch.dylib              0x10584 _dispatch_main_queue_drain + 1048
20 libdispatch.dylib              0x1015c _dispatch_main_queue_callback_4CF$VARIANT$mp + 36
21 ???                            0x194077008 (Missing)
22 ???                            0x194074450 (Missing)
23 ???                            0x1940737d8 (Missing)
24 ???                            0x1d3aa4814 (Missing)
25 ???                            0x196570268 (Missing)
26 ???                            0x19661a90c (Missing)
27 ???                            0x1967711cc (Missing)
28 Falcon                         0x1fbb38 main (AppDelegate.swift)
29 ???                            0x1b55b7228 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1b58 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5224 mach_msg2_internal + 76
2  libsystem_kernel.dylib         0x51b0 mach_msg_overwrite + 492
3  libsystem_kernel.dylib         0x4fb8 mach_msg + 20
4  ???                            0x194074a74 (Missing)
5  ???                            0x1940740e4 (Missing)
6  ???                            0x1940737d8 (Missing)
7  ???                            0x19308f3a8 (Missing)
8  ???                            0x19308f224 (Missing)
9  ???                            0x196582e28 (Missing)
10 ???                            0x1930a3d44 (Missing)
11 libsystem_pthread.dylib        0x482c _pthread_start + 104
12 libsystem_pthread.dylib        0xcd8 thread_start + 8

pendo.api.initQueue
0  libsystem_kernel.dylib         0x7bdc __ulock_wait + 8
1  libdispatch.dylib              0x4a80 _dlock_wait + 52
2  libdispatch.dylib              0x4e40 _dispatch_group_wait_slow + 52
3  Pendo                          0x62db8 (Missing UUID 616ac5f9e74e3b2cb0377fcb87820a19)
4  Pendo                          0x624ac (Missing UUID 616ac5f9e74e3b2cb0377fcb87820a19)
5  Pendo                          0x62c64 (Missing UUID 616ac5f9e74e3b2cb0377fcb87820a19)
6  Pendo                          0x105398 (Missing UUID 616ac5f9e74e3b2cb0377fcb87820a19)
7  libdispatch.dylib              0x61c9c _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x62cc0 _dispatch_client_callout + 16
9  libdispatch.dylib              0xa3f8 _dispatch_lane_serial_drain$VARIANT$mp + 704
10 libdispatch.dylib              0xae74 _dispatch_lane_invoke$VARIANT$mp + 380
11 libdispatch.dylib              0x14794 _dispatch_root_queue_drain_deferred_wlh + 252
12 libdispatch.dylib              0x140a8 _dispatch_workloop_worker_thread + 404
13 libsystem_pthread.dylib        0x3534 _pthread_wqthread + 284
14 libsystem_pthread.dylib        0xccc start_wqthread + 8

com.apple.NSURLSession-work
0  libsystem_kernel.dylib         0x908c fsync + 8
1  ???                            0x1bb46f94c (Missing)
2  ???                            0x1bb47880c (Missing)
3  ???                            0x1bb46f518 (Missing)
4  ???                            0x1bb45fdb0 (Missing)
5  ???                            0x1bb45f97c (Missing)
6  ???                            0x1bb438e40 (Missing)
7  ???                            0x1bb459da8 (Missing)
8  ???                            0x1bb44ec24 (Missing)
9  ???                            0x1bb42bc4c (Missing)
10 ???                            0x19514e05c (Missing)
11 ???                            0x1952bf524 (Missing)
12 ???                            0x19514c79c (Missing)
13 ???                            0x19514bf58 (Missing)
14 ???                            0x19514bc40 (Missing)
15 ???                            0x19513152c (Missing)
16 ???                            0x195130fd0 (Missing)
17 ???                            0x195130b84 (Missing)
18 ???                            0x1951aad54 (Missing)
19 ???                            0x1951a5fdc (Missing)
20 libdispatch.dylib              0x10d0c _dispatch_block_async_invoke2 + 104
21 libdispatch.dylib              0x62cc0 _dispatch_client_callout + 16
22 libdispatch.dylib              0xa3f8 _dispatch_lane_serial_drain$VARIANT$mp + 704
23 libdispatch.dylib              0xae74 _dispatch_lane_invoke$VARIANT$mp + 380
24 libdispatch.dylib              0x14794 _dispatch_root_queue_drain_deferred_wlh + 252
25 libdispatch.dylib              0x140a8 _dispatch_workloop_worker_thread + 404
26 libsystem_pthread.dylib        0x3534 _pthread_wqthread + 284
27 libsystem_pthread.dylib        0xccc start_wqthread + 8

com.google.firebase.crashlytics.ios.binary-images
0  libsystem_kernel.dylib         0x5fa0 write + 8
1  FirebaseCrashlytics            0x16cb4 FIRCLSFileLoopWithWriteBlock + 56
2  FirebaseCrashlytics            0x16b54 FIRCLSFileWriteToFileDescriptor + 92
3  FirebaseCrashlytics            0x171ec FIRCLSFileWriteStringWithSuffix + 168
4  FirebaseCrashlytics            0x17040 FIRCLSFileWriteHashKey + 76
5  FirebaseCrashlytics            0xa828 FIRCLSProcessBinaryImageChange + 496
6  libdispatch.dylib              0x62cc0 _dispatch_client_callout + 16
7  libdispatch.dylib              0xa3f8 _dispatch_lane_serial_drain$VARIANT$mp + 704
8  libdispatch.dylib              0xae74 _dispatch_lane_invoke$VARIANT$mp + 380
9  libdispatch.dylib              0x14794 _dispatch_root_queue_drain_deferred_wlh + 252
10 libdispatch.dylib              0x140a8 _dispatch_workloop_worker_thread + 404
11 libsystem_pthread.dylib        0x3534 _pthread_wqthread + 284
12 libsystem_pthread.dylib        0xccc start_wqthread + 8

Thread
0  libdispatch.dylib              0x13c30 _dispatch_worker_thread2 + 152
1  libsystem_pthread.dylib        0x34f8 _pthread_wqthread + 224
2  libsystem_pthread.dylib        0xccc start_wqthread + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1b58 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5224 mach_msg2_internal + 76
2  libsystem_kernel.dylib         0x51b0 mach_msg_overwrite + 492
3  libsystem_kernel.dylib         0x4fb8 mach_msg + 20
4  ???                            0x194074a74 (Missing)
5  ???                            0x1940740e4 (Missing)
6  ???                            0x1940737d8 (Missing)
7  ???                            0x1951daee0 (Missing)
8  ???                            0x1930a3d44 (Missing)
9  libsystem_pthread.dylib        0x482c _pthread_start + 104
10 libsystem_pthread.dylib        0xcd8 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x217f8 FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x21bd8 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x18c7c FIRCLSHandler + 48
3  FirebaseCrashlytics            0x1b500 FIRCLSMachExceptionServer + 688
4  libsystem_pthread.dylib        0x482c _pthread_start + 104
5  libsystem_pthread.dylib        0xcd8 thread_start + 8

Thread
0  libsystem_pthread.dylib        0xcc4 start_wqthread + 8212622530

Thread
0  libsystem_pthread.dylib        0xcc4 start_wqthread + 8212622530
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - Apollo (0.52.0):
    - Apollo/Core (= 0.52.0)
  - Apollo/Core (0.52.0)
  - Firebase/CoreOnly (10.21.0):
    - FirebaseCore (= 10.21.0)
  - Firebase/Crashlytics (10.21.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.21.0)
  - FirebaseCore (10.21.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.25.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.25.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.21.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.25.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseSessions (10.25.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.13)
    - GoogleUtilities/UserDefaults (~> 7.13)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (7.1.0):
    - GoogleMaps/Maps (= 7.1.0)
  - GoogleMaps/Base (7.1.0)
  - GoogleMaps/Maps (7.1.0):
    - GoogleMaps/Base
  - GooglePlaces (7.1.0)
  - GoogleUtilities/Environment (7.13.2):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - "GoogleUtilities/NSData+zlib (7.13.2)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.2)
  - GoogleUtilities/UserDefaults (7.13.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - IQKeyboardManager (6.5.19)
  - JWTDecode (3.0.1)
  - LaunchDarkly (8.4.2):
    - LaunchDarkly/Core (= 8.4.2)
  - LaunchDarkly/Core (8.4.2):
    - LDSwiftEventSource (= 3.1.1)
  - LDSwiftEventSource (3.1.1)
  - lottie-ios (3.3.0)
  - MarqueeLabel (4.3.1)
  - MaterialComponents/AnimationTiming (124.2.0)
  - MaterialComponents/Availability (124.2.0)
  - MaterialComponents/private/Math (124.2.0)
  - "MaterialComponents/private/TextControlsPrivate+BaseStyle (124.2.0)":
    - MaterialComponents/AnimationTiming
    - MaterialComponents/private/Math
    - "MaterialComponents/private/TextControlsPrivate+Shared"
  - "MaterialComponents/private/TextControlsPrivate+FilledStyle (124.2.0)":
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Availability
    - MaterialComponents/private/Math
    - "MaterialComponents/private/TextControlsPrivate+Shared"
    - "MaterialComponents/private/TextControlsPrivate+UnderlinedStyle"
  - "MaterialComponents/private/TextControlsPrivate+OutlinedStyle (124.2.0)":
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Availability
    - MaterialComponents/private/Math
    - "MaterialComponents/private/TextControlsPrivate+Shared"
  - "MaterialComponents/private/TextControlsPrivate+Shared (124.2.0)":
    - MaterialComponents/AnimationTiming
    - MaterialComponents/private/Math
    - "MaterialComponents/TextControls+Enums"
  - "MaterialComponents/private/TextControlsPrivate+TextFields (124.2.0)":
    - MaterialComponents/private/Math
    - "MaterialComponents/private/TextControlsPrivate+Shared"
  - "MaterialComponents/private/TextControlsPrivate+UnderlinedStyle (124.2.0)":
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Availability
    - MaterialComponents/private/Math
    - "MaterialComponents/private/TextControlsPrivate+Shared"
  - "MaterialComponents/TextControls+BaseTextFields (124.2.0)":
    - "MaterialComponents/private/TextControlsPrivate+BaseStyle"
    - "MaterialComponents/private/TextControlsPrivate+Shared"
    - "MaterialComponents/private/TextControlsPrivate+TextFields"
    - MDFInternationalization
  - "MaterialComponents/TextControls+Enums (124.2.0)"
  - "MaterialComponents/TextControls+FilledTextFields (124.2.0)":
    - MaterialComponents/Availability
    - "MaterialComponents/private/TextControlsPrivate+FilledStyle"
    - "MaterialComponents/TextControls+BaseTextFields"
  - "MaterialComponents/TextControls+OutlinedTextFields (124.2.0)":
    - MaterialComponents/Availability
    - "MaterialComponents/private/TextControlsPrivate+OutlinedStyle"
    - "MaterialComponents/TextControls+BaseTextFields"
  - MDFInternationalization (3.0.0)
  - MicrosoftMapsSDK (1.2.0)
  - nanopb (2.30909.1):
    - nanopb/decode (= 2.30909.1)
    - nanopb/encode (= 2.30909.1)
  - nanopb/decode (2.30909.1)
  - nanopb/encode (2.30909.1)
  - OktaAuthFoundation (1.8.2)
  - OktaOAuth2 (1.8.2):
    - OktaAuthFoundation (= 1.8.2)
  - OktaWebAuthenticationUI (1.8.2):
    - OktaAuthFoundation (= 1.8.2)
    - OktaOAuth2 (= 1.8.2)
  - Pendo (3.2.0.8353)
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - ReachabilitySwift (5.2.2)
  - SimpleSwiftNumericKeyboard (0.1.4)
  - SkydioUISDK (24.5.13):
    - Apollo (= 0.52.0)
    - lottie-ios (= 3.3.0)
    - MarqueeLabel (= 4.3.1)
  - Zip (2.1.2)

DEPENDENCIES:
  - Firebase/Crashlytics (~> 10.21.0)
  - GoogleMaps (= 7.1.0)
  - GooglePlaces (= 7.1.0)
  - IQKeyboardManager (~> 6.5.17)
  - JWTDecode (~> 3.0.1)
  - LaunchDarkly (~> 8.4.0)
  - lottie-ios (= 3.3.0)
  - MarqueeLabel (= 4.3.1)
  - "MaterialComponents/TextControls+FilledTextFields"
  - "MaterialComponents/TextControls+OutlinedTextFields"
  - MicrosoftMapsSDK (~> 1.2.0)
  - OktaWebAuthenticationUI (= 1.8.2)
  - Pendo
  - ReachabilitySwift
  - SimpleSwiftNumericKeyboard
  - SkydioUISDK (= 24.5.13)
  - Zip (~> 2.1.2)

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - Apollo
    - Firebase
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseSessions
    - GoogleDataTransport
    - GoogleMaps
    - GooglePlaces
    - GoogleUtilities
    - IQKeyboardManager
    - JWTDecode
    - LaunchDarkly
    - LDSwiftEventSource
    - lottie-ios
    - MarqueeLabel
    - MaterialComponents
    - MDFInternationalization
    - MicrosoftMapsSDK
    - nanopb
    - OktaAuthFoundation
    - OktaOAuth2
    - OktaWebAuthenticationUI
    - Pendo
    - PromisesObjC
    - PromisesSwift
    - ReachabilitySwift
    - SimpleSwiftNumericKeyboard
    - Zip
  https://github.com/Skydio/skydio-specs-ios.git:
    - SkydioUISDK

SPEC CHECKSUMS:
  Apollo: a5819d504292e28089ef924e04392252d9319f9b
  Firebase: 4453b799f72f625384dc23f412d3be92b0e3b2a0
  FirebaseCore: 74f647ad9739ea75112ce6c3b3b91f5488ce1122
  FirebaseCoreExtension: 8a47811d0b155501559ef05d089518152a0a1677
  FirebaseCoreInternal: 910a81992c33715fec9263ca7381d59ab3a750b7
  FirebaseCrashlytics: 063b883186d7ccb1db1837c19113ca6294880c1b
  FirebaseInstallations: 91950fe859846fff0fbd296180909dd273103b09
  FirebaseSessions: c0939656253a1fa0e94ecc266ccf770cc8b33732
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleMaps: bc56ffb0324e345a2d91bac1a64a920f9c8f1b20
  GooglePlaces: 187946335ec3dc624de71c0a9ddcc712f19b0ee1
  GoogleUtilities: c56430aef51a1aa57b25da78c3f8397e522c67b7
  IQKeyboardManager: c8665b3396bd0b79402b4c573eac345a31c7d485
  JWTDecode: 2eed97c2fa46ccaf3049a787004eedf0be474a87
  LaunchDarkly: 558616e9df39fa2c840c3f6ff52d76c751ffa37b
  LDSwiftEventSource: 3f9ff84ca80677f9a4f8596757dcb50026e4a13c
  lottie-ios: 6ac74dcc09904798f59b18cb3075c089d76be9ae
  MarqueeLabel: da4b9cf619fe70c75d7bab4580b0b4a0b868aa6b
  MaterialComponents: 1a9b2d9d45b1601ae544de85089adc4c464306d4
  MDFInternationalization: d697c55307816222a55685c4ccb1044ffb030c12
  MicrosoftMapsSDK: c914b8c87b978d4665a00a5515bd35a43993429d
  nanopb: d4d75c12cd1316f4a64e3c6963f879ecd4b5e0d5
  OktaAuthFoundation: dc19dec586cfa710b6f65b40c0beff9b84ff9c45
  OktaOAuth2: fb5e51034c7160f10980e90ec05608e7ba90913f
  OktaWebAuthenticationUI: ba68d5b1083cc821df9084c635aa31f713e25735
  Pendo: 27691616fd09c7378d4ddf56d28b08e75fc3455a
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  ReachabilitySwift: 2128f3a8c9107e1ad33574c6e58e8285d460b149
  SimpleSwiftNumericKeyboard: c9239ab77b9da6917755ca219223923c4961e939
  SkydioUISDK: 13293ffbce1d61a11984670315625a662cef5653
  Zip: b3fef584b147b6e582b2256a9815c897d60ddc67

PODFILE CHECKSUM: f7347f94e8011981057bf52c9747e79eca1b4e4c

COCOAPODS: 1.12.1


```

</details>

**Comment by rizafran** [comment] 2024-11-12 13:51
Hi @apoorv-trikha-ev, this seems to be a duplicate of #11403. With this, please update your SDK version to a 10.22.0 or above.

**Closed by rizafran** 2024-11-12 13:51 UTC
Labels: GoogleDataTransport, sessions
