### ISSUE TITLE
Unable to use xcode 15.3

### ISSUE THREAD

**Issue by piajesse** [firebase/firebase-ios-sdk#12510] opened 2024-03-11 02:01 UTC
### Description

Just updated xcode to 15.3 and now I get these errors trying to compile my iOS app
<img width="337" alt="Screenshot 2024-03-10 at 6 49 51 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/44306072/1080f24d-9ec9-4ebf-baa2-b60cd6808d01">

### Firebase SDK Version

10.22.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Authentication, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - Alamofire (5.9.0)
  - BetterSegmentedControl (2.0.1)
  - CocoaLumberjack/Core (3.8.5)
  - CocoaLumberjack/Swift (3.8.5):
    - CocoaLumberjack/Core
  - CountryPickerView (3.3.0)
  - Firebase/AnalyticsWithoutAdIdSupport (10.22.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 10.22.0)
  - Firebase/CoreOnly (10.22.0):
    - FirebaseCore (= 10.22.0)
  - FirebaseAnalytics/WithoutAdIdSupport (10.22.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseCore (10.22.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreInternal (10.22.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.22.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.22.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleUtilities/AppDelegateSwizzler (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.0):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.0)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.0)
  - GoogleUtilities/Reachability (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - KeychainSwift (21.0.0)
  - KWVerificationCodeView (0.5.0)
  - linphone-sdk (5.2.114)
  - MarqueeLabel (4.5.0)
  - MTSlideToOpen (1.5.1)
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - NVActivityIndicatorView (5.1.1):
    - NVActivityIndicatorView/Base (= 5.1.1)
  - NVActivityIndicatorView/Base (5.1.1)
  - PanModal (1.2.7)
  - PhoneNumberKit (3.7.9):
    - PhoneNumberKit/PhoneNumberKitCore (= 3.7.9)
    - PhoneNumberKit/UIKit (= 3.7.9)
  - PhoneNumberKit/PhoneNumberKitCore (3.7.9)
  - PhoneNumberKit/UIKit (3.7.9):
    - PhoneNumberKit/PhoneNumberKitCore
  - PromisesObjC (2.4.0)
  - ReachabilitySwift (5.0.0)
  - RevenueCat (4.38.1)
  - SoundWave (0.1.5)
  - Spring (1.0.6)
  - Stripe (23.24.1):
    - StripeApplePay (= 23.24.1)
    - StripeCore (= 23.24.1)
    - StripePayments (= 23.24.1)
    - StripePaymentsUI (= 23.24.1)
    - StripeUICore (= 23.24.1)
  - StripeApplePay (23.24.1):
    - StripeCore (= 23.24.1)
  - StripeCore (23.24.1)
  - StripePayments (23.24.1):
    - StripeCore (= 23.24.1)
    - StripePayments/Stripe3DS2 (= 23.24.1)
  - StripePayments/Stripe3DS2 (23.24.1):
    - StripeCore (= 23.24.1)
  - StripePaymentSheet (23.24.1):
    - StripeApplePay (= 23.24.1)
    - StripeCore (= 23.24.1)
    - StripePayments (= 23.24.1)
    - StripePaymentsUI (= 23.24.1)
  - StripePaymentsUI (23.24.1):
    - StripeCore (= 23.24.1)
    - StripePayments (= 23.24.1)
    - StripeUICore (= 23.24.1)
  - StripeUICore (23.24.1):
    - StripeCore (= 23.24.1)
  - SwiftConfettiView (0.1.0)
  - SwiftMessages (10.0.0):
    - SwiftMessages/App (= 10.0.0)
  - SwiftMessages/App (10.0.0)
  - SwiftyGif (5.4.4)
  - SwipeableTabBarController (3.4.2)

DEPENDENCIES:
  - Alamofire (~> 5.2)
  - BetterSegmentedControl (~> 2.0)
  - CocoaLumberjack/Swift
  - CountryPickerView
  - Firebase/AnalyticsWithoutAdIdSupport
  - KeychainSwift
  - KWVerificationCodeView
  - linphone-sdk (~> 5.2.0)
  - MarqueeLabel
  - MTSlideToOpen
  - NVActivityIndicatorView
  - PanModal
  - PhoneNumberKit
  - ReachabilitySwift
  - RevenueCat
  - SoundWave (from `https://github.com/bastienFalcou/SoundWave.git`, branch `master`)
  - Spring (from `https://github.com/MengTo/Spring.git`)
  - Stripe
  - StripePaymentSheet
  - SwiftConfettiView
  - SwiftMessages
  - SwiftyGif
  - SwipeableTabBarController

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - Alamofire
    - BetterSegmentedControl
    - CocoaLumberjack
    - CountryPickerView
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - GoogleAppMeasurement
    - GoogleUtilities
    - KeychainSwift
    - KWVerificationCodeView
    - MarqueeLabel
    - MTSlideToOpen
    - nanopb
    - NVActivityIndicatorView
    - PanModal
    - PhoneNumberKit
    - PromisesObjC
    - ReachabilitySwift
    - RevenueCat
    - Stripe
    - StripeApplePay
    - StripeCore
    - StripePayments
    - StripePaymentSheet
    - StripePaymentsUI
    - StripeUICore
    - SwiftConfettiView
    - SwiftMessages
    - SwiftyGif
    - SwipeableTabBarController
  https://gitlab.linphone.org/BC/public/podspec.git:
    - linphone-sdk

EXTERNAL SOURCES:
  SoundWave:
    :branch: master
    :git: https://github.com/bastienFalcou/SoundWave.git
  Spring:
    :git: https://github.com/MengTo/Spring.git

CHECKOUT OPTIONS:
  SoundWave:
    :commit: fe79080d75f29c2258cfd3562c7c506f69036fbe
    :git: https://github.com/bastienFalcou/SoundWave.git
  Spring:
    :commit: 50d92a5b9e08848387ae95bf44c6ad20834f7083
    :git: https://github.com/MengTo/Spring.git

SPEC CHECKSUMS:
  Alamofire: 02b772c9910e8eba1a079227c32fbd9e46c90a24
  BetterSegmentedControl: 09607b27861d49cbce48b7673b74f9150a3d371a
  CocoaLumberjack: 6a459bc897d6d80bd1b8c78482ec7ad05dffc3f0
  CountryPickerView: 6322ada32a80b0cd721b0267282a5c24f406f263
  Firebase: 797fd7297b7e1be954432743a0b3f90038e45a71
  FirebaseAnalytics: 8d0ff929c63b7f72260f332b86ccf569776b75d3
  FirebaseCore: 0326ec9b05fbed8f8716cddbf0e36894a13837f7
  FirebaseCoreInternal: bca337352024b18424a61e478460547d46c4c753
  FirebaseInstallations: 763814908793c0da14c18b3dcffdec71e29ed55e
  GoogleAppMeasurement: ccefe3eac9b0aa27f96066809fb1a7fe4b462626
  GoogleUtilities: d053d902a8edaa9904e1bd00c37535385b8ed152
  KeychainSwift: 4a71a45c802fd9e73906457c2dcbdbdc06c9419d
  KWVerificationCodeView: 19ea2579877cc4937f5ee16d0e205d487bdb247d
  linphone-sdk: dfe70cd91cd826e1a6833f349525a305f11b438c
  MarqueeLabel: 4b46d196abd253448e830cbd976f9eacc3af0849
  MTSlideToOpen: dedc9abf1e377fef40544b84e5590d4981055030
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  NVActivityIndicatorView: 1f6c5687f1171810aa27a3296814dc2d7dec3667
  PanModal: 3e16ead1a907fb06f4df3f13492fd00149fa4974
  PhoneNumberKit: 9c8d546d65c3784721d575a29e712ae8b992fe79
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  ReachabilitySwift: 985039c6f7b23a1da463388634119492ff86c825
  RevenueCat: f1b4bce353e676260eddc65a34c9fdf595adf2f4
  SoundWave: ec1c8f45af75ca0c301cf7160e16d2db8023058d
  Spring: 3d113f14575ef79aec9c5f906dfa4f5001c03254
  Stripe: b7df79a977dd47748e7dd449d2e80ca8bc58b952
  StripeApplePay: ffc296e6eba1d9ce86e4b5c4733540bce6f1b3eb
  StripeCore: 7c9042ecbca0ef4e8073de00d3c84255d6b87e92
  StripePayments: 4fdc6b22595887753851aee425dc9aafad39e8ef
  StripePaymentSheet: 9f433a11fa6578939c555b6a56c87b7a958845d6
  StripePaymentsUI: 42a4c50bd30a19c102685eeb7269a52c71a79bb3
  StripeUICore: 510afeb8f0cb8ba5f99563a23c5ad6cc7f58a007
  SwiftConfettiView: 1bdbc2e6913b6b1c76d8070802b212508ad5c352
  SwiftMessages: d3540f0f981dfbac25bd2ae9a662effa48f76f92
  SwiftyGif: 93a1cc87bf3a51916001cf8f3d63835fb64c819f
  SwipeableTabBarController: 9a218bdee9426d1bfe36d7962f852024bb08d61b

PODFILE CHECKSUM: 6809b463e5b9ad2981d52594f3acd64185d7dbeb

COCOAPODS: 1.15.2

```

</details>

**Comment by rizafran** [comment] 2024-03-11 13:10
Hi @piajesse, I tried to reproduce the issue, but I successfully ran my project. Have you tried to clean build your project and restart Xcode?

**Comment by sarxhaUFT** [comment] 2024-03-11 13:27
It seem to be a problem with the Xcode 15.3 and Firebase
Have you tried of downloading 
Xcode 15.2 | Release | 15C500b
from https://xcodereleases.com/ and give it a try.

**Comment by paulb777** [comment] 2024-03-11 17:45
@garranhado Those frameworks aren't part of Firebase. Please follow https://github.com/googleanalytics/google-tag-manager-ios-sdk/issues/28.

**Comment by garranhado** [comment] 2024-03-11 18:18
@paulb777 GoogleAnalytics.framework is a Firebase framework

Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'MyApp.app/Frameworks/**GoogleAnalytics.framework**' is ''. (ID: ac5da7f8-e508-41ba-bb2d-4854cf458afe)

**Comment by avery100** [comment] 2024-03-12 15:52
Similar issue here: just updated my mac mini m2 pro to Sonoma 14.4, xcode Version 15.3 (15E204a), pulled the latest https://github.com/firebase/firebase-ios-sdk (10.22.1). I have a new device, a 15 Pro with 17.4 on it - the app works on that, and the standalone simulator app for 15.4 through 17.4 - the app works on those. It will NOT work on Preview simulators inside of xcode 15.3. Here are some screenshots: 

![Screenshot 2024-03-12 at 10 40 06 AM](https://github.com/firebase/firebase-ios-sdk/assets/669001/9b1d8901-1d10-46f7-9009-0566d50cb152)
![Screenshot 2024-03-12 at 11 35 41 AM](https://github.com/firebase/firebase-ios-sdk/assets/669001/45b45308-642d-4ade-bf3b-0149ec383a79)
![Screenshot 2024-03-12 at 11 09 26 AM](https://github.com/firebase/firebase-ios-sdk/assets/669001/acb1a1fd-989f-429d-85eb-91ca081ad314)

Things I've tried:
> Clean the builds
> Delete the DerivedData folder
> Update the dependencies to latest through Swift Package Manager.
> Toggle BuildActiveArchitectureOnly for both Debug and Release into all possible configurations.

I keep getting veered "Missing arm64 slice in the binary" way but any help would be greatly appreciated. 

Cheers!

**Comment by paulb777** [comment] 2024-03-13 03:06
@darkCloud77 Make sure you update Firebase and all its dependencies, including abseil, BoringSSL, and gRPC, to the latest versions

**Comment by rjuzaszek** [comment] 2024-03-13 16:16
Clearing & rebuilding project after updating to 10.22.1 fixed the problem for me

**Comment by thepantalion** [comment] 2024-03-15 12:02
After updating to Xcode 15.3, I had the same kind of issues @avery100 showed in their screenshots. Simulator (with iOS 17.4) would refuse to install a build of my project due to supposedly missing modules that were actually installed (through SPM only, no CocoaPods). The following errors were thrown upon installation: 

```
Failed to load Info.plist from bundle at path /Users/$username$/Library/Developer/CoreSimulator/Devices/$simulator-UUID$/data/Library/Caches/com.apple.mobile.installd.staging/temp.wl6itt/extracted/$appname$.app/Frameworks/FirebaseFirestoreInternal.framework; 
Extra info about "/Users/$username$/Library/Developer/CoreSimulator/Devices/$simulator-UUID$/data/Library/Caches/com.apple.mobile.installd.staging/temp.wl6itt/extracted/$appname$.app/Frameworks/FirebaseFirestoreInternal.framework/Info.plist": 
Couldn't stat /Users/$username$/Library/Developer/CoreSimulator/Devices/$simulator-UUID$/data/Library/Caches/com.apple.mobile.installd.staging/temp.wl6itt/extracted/$appname$.app/Frameworks/FirebaseFirestoreInternal.framework/Info.plist: No such file or directory 
 ```
```
no such file or directory: '/Users/$username$/Library/Developer/Xcode/DerivedData/$projectname$/Build/Intermediates.noindex/Previews/iphonesimulator/$appname$/Products/Debug-iphonesimulator/PackageFrameworks/GoogleSignIn.framework/GoogleSignIn'
```

Also SwiftUI previews were affected and the following type of errors were presented:
```
/Users/$username$/Xcode/$appname$/$appname$/Extensions/SwiftUIPreviews+Devices.swift Missing required module 'FirebaseFirestoreInternalWrapper'
```
```
Link GoogleSignIn (arm64):
    Undefined symbols for architecture arm64
```
```
framework 'FirebaseFirestore' not found
```

This happened with any version of Firebase and GoogleSignIn packages. 

Reverting back to Xcode 15.2 fixes all the presented issues and allows the project to build just fine with any version of Firebase (and GoogleSignIn in my case).

**Comment by ArturoLee** [comment] 2024-03-15 19:37
+1

@rjuzaszek What do you mean by clearing? I tried cleaning and resetting package caches.

**Comment by avery100** [comment] 2024-03-16 18:08
UPDATE: I was stuck in a loop on xcode 15.3 where no matter what architecture destination i selected arm64 or x86_64, including Rossetta, Preview builds would fail. 

I believe it is something in the way 15.3 builds previews has fundamentally changed, maybe this: 
ttps://forums.developer.apple.com/forums/thread/747938
https://developer.apple.com/documentation/xcode-release-notes/xcode-15_3-release-notes#Resolved-Issues

**I followed  @thepantalion's suggestion and downgraded back to xcode 15.2.**
https://xcodereleases.com/

**Make sure to set your command line tools to 15.2 as well.**
![xcode_issue152](https://github.com/firebase/firebase-ios-sdk/assets/669001/e5b24c87-19f5-4f72-b00d-31bd2b5a3fa4)

**Comment by paulb777** [comment] 2024-03-18 22:27
Closing this issue, since there are several partial issue reports here. 

If you have an issue with Xcode 15.3 with Firebase 10.22.0 or 10.22.1 other than https://github.com/firebase/firebase-ios-sdk/issues/12505 please open another issue with the template filled out.

**Closed by paulb777** 2024-03-18 22:27 UTC
Labels: needs-info

**Comment by rjuzaszek** [comment] 2024-03-19 10:56
> +1
> 
> @rjuzaszek What do you mean by clearing? I tried cleaning and resetting package caches.

Exactly: updating firebase package, deleting derived data, reinstalling pods, and clearing build data + fresh build did the job.
The first try was after updating to xc15.3 from 15.2 and the archiving result was the problem many encounter here, after I did my steps it went off just like that so I don't have much more insides unfortunately
