### ISSUE TITLE
UI broken on iOS 14 device

### ISSUE THREAD

**Issue by AM-lu** [firebase/firebase-ios-sdk#6967] opened 2020-11-13 11:05 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____Xcode 12.1
  * Firebase SDK version: _____6.34.0
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one) Cocoapods
  * Firebase Component: ___ In-app messaging__ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem
on ios14 devices, the UI will be broken like this. 
![IMG_0188](https://user-images.githubusercontent.com/29445786/99065568-eb964180-25ea-11eb-88a1-3764b9bc7b2b.PNG)

#### Steps to reproduce:

Show OS's permission dialog(like notification) after app launched, and then send analytics event to show in-app message,
then the in-app message dialog will be broken.

It seems like Firebase SDK calculates the window size when it is initialized.
But when this logic is started when os permission dialog is showed, the calculate will not work well.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by Mattijah** [comment] 2020-11-13 14:03
Duplicate of https://github.com/firebase/firebase-ios-sdk/issues/6803

**Comment by paulb777** [comment] 2020-11-13 15:53
Closing in favor of #6803 - cc: @christibbs

**Closed by paulb777** 2020-11-13 15:53 UTC
Labels: api: inappmessaging, iOS 14
