### ISSUE TITLE
Persisted queries should return ints instead of round doubles after int overwrites

### ISSUE THREAD

**Issue by collinjackson** [firebase/firebase-ios-sdk#91] opened 2017-06-20 03:42 UTC
This was originally flutter/flutter#10825 but it looks like a Firebase bug.

### Environment

  * Xcode version: 8.3.3
  * Firebase SDK version: 4.0.2
  * Library version: 4.0.0
  * Firebase Product: database

### Problem

Reduced test case:

```
#import "AppDelegate.h"
@import Firebase;
@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [FIRApp configure];
  [[FIRDatabase database] setPersistenceEnabled:YES];
  FIRDatabaseReference *ref = [[FIRDatabase database].reference child:@"counter"];
  [ref keepSynced:YES];
  [ref observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
    NSLog(@"Type of %@ is %d", snapshot.value, (int)CFNumberGetType((CFNumberRef)snapshot.value));
  }];
  [ref setValue:[NSNumber numberWithInt:42]];
  return YES;
}
@end
```

The first time this code runs, the snapshot value is an integer NSNumber. The second time, it's an NSDecimalNumber with a CFNumberType of kCFNumberDoubleType. Presumably this is because the persistent store is serializing numbers differently from the cloud Firebase. But Firebase queries should never yield doubles for round numbers like 42.

**Comment by schmidt-sebastian** [comment] 2017-06-21 19:02
Thanks for sending this issue!

I was able to reproduce your observations. It turns out that NSJSONSerialization returns floating point numbers if the value is a top-level value. While {foo:1} returns a long, {1} returns a double. We will get this fixed in the next release.

**Comment by schmidt-sebastian** [comment] 2017-06-27 17:05
Addressed with https://github.com/firebase/firebase-ios-sdk/pull/107

**Closed by schmidt-sebastian** 2017-06-27 17:05 UTC
Labels: Database
