### ISSUE TITLE
multiple upload-symbols with 100% cpu usage

### ISSUE THREAD

**Issue by kenji21** [firebase/firebase-ios-sdk#7042] opened 2020-11-26 09:18 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.1.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: upload-symbols/run (Auth, Core, Database, Firestore, Messaging, Storage, etc)

### [REQUIRED] Step 2: Describe the problem

<img width="832" alt="Screenshot" src="https://user-images.githubusercontent.com/1105089/100330672-90435680-2fcf-11eb-8da5-b470f6854a90.png">

#### Steps to reproduce:

What happened? How can we make the problem occur?
Just built & run project test target ten times in a row (or maybe having designable in the project could do this)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

![Screenshot 1](https://user-images.githubusercontent.com/1105089/100330892-cc76b700-2fcf-11eb-8410-3d17f7c419fc.png)

Ask people to tick the install only checkbox in the build phase, or better: determine if a build is an Archive one (uploading to the store... so we really need to upload symbols...) maybe like this (early exit for our linter script here):

```
if [[ "$BUILD_DIR" == *"IBDesignables"* ]] || [[ "$BUILD_DIR" == *"Previews"* ]] ; then
    echo "not linting for IBDesignables/SwiftUI Previews builds";
    exit 0
fi
```

As I was building for testing, App under unit test is correctly build, so the script phase was called

![Screenshot 2](https://user-images.githubusercontent.com/1105089/100331515-8d953100-2fd0-11eb-94f5-90c712e01071.png)

**Comment by samedson** [comment] 2020-11-30 15:02
Hey @kenji21, are you trying this out on a really large app? `upload-symbols` should run for a fairly short time on small apps, but can take longer on larger apps.

The reason we don't tell devs to check the "For install builds only" option is because many devs want crashes to show up in development, and first time onboarding requires `upload-symbols` to succeed so developers can make sure everything is set up correctly.

Using the `run` script makes `upload-symbols` run in the background. If you'd like it to run synchronously you can use:

`${PROJECT_DIR}/vendor/FirebaseCrashlytics/upload-symbols --build-phase`

**Comment by kenji21** [comment] 2020-11-30 15:07
Sure the project is 15k lines of swift. I don't want my unit tests to be runned slower (neither IBInspectable/SwiftUI previews builds)...
I think it is wasteful to upload symbols on each debug build... maybe you should just mention the checkbox in your README

**Comment by kjyv** [comment] 2022-01-12 16:42
I apparently reported the same issue over here:
https://github.com/firebase/firebase-unity-sdk/issues/81

However, with Unity, there is always a huge amount of il2cpp generated code and the issue is not so much the time it takes at 100% cpu but the amount of memory it fills. After a few seconds it fills all remaning memory available on my machine. It seems to not be limited to a resonable amount regarding how much memory the system has. It quickly makes the system unusable and even stalls the mouse cursor meaning upload-symbols can't do it's job because we have to kill it manually every time.

**Comment by kjyv** [comment] 2022-01-12 19:59
The Xcode project is generated, so anything that I change will be overridden the next time. The issue is not that upload-symbols is run, the issue is that it takes too much memory and cpu for big projects. It also doesn't do that every time, sometimes it is done without me noticing.

**Comment by kenji21** [comment] 2022-01-12 20:25
> It also doesn't do that every time, sometimes it is done without me noticing.

random issue, hardest one to fix, 100% cpu means an infinite loop, but why such a loop happens ? can it be caused by a clean of the build folder (e.g. dSYM disappearing from disk during upload) ?

**Comment by kenji21** [comment] 2022-01-12 20:27
maybe gathering a sample (from Activity Monitor) could give some clue

**Comment by samedson** [comment] 2022-10-11 17:24
For folks running into this, is it the case that the tool is completing the upload eventually, or is it really stuck in an infinite loop?

**Comment by kjyv** [comment] 2022-10-11 17:41
I'm no longer working on the project but what I've encountered was that it was staying at 100% for many minutes - waiting for it to finish was not realistically possible though as everything froze when the memory was used up. In order to reproduce, I recommend trying a default Unity sample project with Firebase added and just build it a few times.

**Comment by samedson** [comment] 2023-04-27 18:16
It seems it may still be an issue in https://github.com/firebase/firebase-ios-sdk/issues/11159. I'm going to close this and continue the investigation in the new issue

**Closed by samedson** 2023-04-27 18:16 UTC
Labels: type: feature request, api: crashlytics, Swift Package Manager, SwiftUI
