### ISSUE TITLE
CRASH When I call FirebaseApp.configure

### ISSUE THREAD

**Issue by Sylvan1903** [firebase/firebase-ios-sdk#12989] opened 2024-05-17 14:15 UTC
### Description

<img width="1768" alt="截屏2024-05-17 21 58 37" src="https://github.com/firebase/firebase-ios-sdk/assets/170111471/661f1cb7-9013-45f0-8d4e-a6369fd65fdd">

My app is doing well before i upgrade my Xcode to 15.3.
It crashed every time when I run code in Xcode 15.3. 
I just init Firebase and it crashed. 
I run app on my iPhone 13 Pro(iOS 17.4), not simulator
```
let options = FirebaseOptions(contentsOfFile: path!)
 FirebaseApp.configure(options: options!)
```

I can't debug my app now.

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2024-05-17 15:25
Looks like a duplicate of #12485

**Closed** 2024-05-31 01:04 UTC
Labels: api: dynamiclinks, needs-info, no-recent-activity
