### ISSUE TITLE
CoreData: warning: Property 'parameters' on Entity 'GAIHit' is using nil or an insecure NSValueTransformer

### ISSUE THREAD

**Issue by akcelotechnology** [firebase/firebase-ios-sdk#6217] opened 2020-08-06 02:26 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.29.0
  * Firebase Component: Analytics
  * Component version: 6.29.0
  * Installation method: `CocoaPodse`

### [REQUIRED] Step 2: Describe the problem

CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: warning: Property 'parameters' on Entity 'GAIHit' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

#### Steps to reproduce:

Call Analytics.logEvent("", parameters: nil)

**Comment by morganchen12** [comment] 2020-08-06 17:14
The root of this issue lies in GoogleAnalytics, which is a separate framework from Firebase Analytics and is not tied to the Firebase release cycle.

The fix should be pretty simple--GAIHit needs to conform to NSSecureUnarchiveFromData.

**Comment by morganchen12** [comment] 2020-08-06 23:25
On further inspection, it looks like something is going on in your project. Google Analytics doesn't use CoreData to store hit events, it instead stores them in sqlite like Firebase Analytics does. Can you share your full Podfile.lock or a project that reproduces this issue?

**Comment by akcelotechnology** [comment] 2020-08-06 23:49
After further investigation, it seems that the warning is coming from GoogleTagManager which seems that it's a dependency of Firebase Analytics? If I remove it from the project the warning goes away.



`PODS:
  - abseil/algorithm (0.20200225.0):
    - abseil/algorithm/algorithm (= 0.20200225.0)
    - abseil/algorithm/container (= 0.20200225.0)
  - abseil/algorithm/algorithm (0.20200225.0):
    - abseil/base/config
  - abseil/algorithm/container (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/base (0.20200225.0):
    - abseil/base/atomic_hook (= 0.20200225.0)
    - abseil/base/base (= 0.20200225.0)
    - abseil/base/base_internal (= 0.20200225.0)
    - abseil/base/bits (= 0.20200225.0)
    - abseil/base/config (= 0.20200225.0)
    - abseil/base/core_headers (= 0.20200225.0)
    - abseil/base/dynamic_annotations (= 0.20200225.0)
    - abseil/base/endian (= 0.20200225.0)
    - abseil/base/errno_saver (= 0.20200225.0)
    - abseil/base/exponential_biased (= 0.20200225.0)
    - abseil/base/log_severity (= 0.20200225.0)
    - abseil/base/malloc_internal (= 0.20200225.0)
    - abseil/base/periodic_sampler (= 0.20200225.0)
    - abseil/base/pretty_function (= 0.20200225.0)
    - abseil/base/raw_logging_internal (= 0.20200225.0)
    - abseil/base/spinlock_wait (= 0.20200225.0)
    - abseil/base/throw_delegate (= 0.20200225.0)
  - abseil/base/atomic_hook (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/base (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/log_severity
    - abseil/base/raw_logging_internal
    - abseil/base/spinlock_wait
    - abseil/meta/type_traits
  - abseil/base/base_internal (0.20200225.0):
    - abseil/base/config
    - abseil/meta/type_traits
  - abseil/base/bits (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/config (0.20200225.0)
  - abseil/base/core_headers (0.20200225.0):
    - abseil/base/config
  - abseil/base/dynamic_annotations (0.20200225.0)
  - abseil/base/endian (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/errno_saver (0.20200225.0):
    - abseil/base/config
  - abseil/base/exponential_biased (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/log_severity (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/malloc_internal (0.20200225.0):
    - abseil/base/base
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/raw_logging_internal
  - abseil/base/periodic_sampler (0.20200225.0):
    - abseil/base/core_headers
    - abseil/base/exponential_biased
  - abseil/base/pretty_function (0.20200225.0)
  - abseil/base/raw_logging_internal (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/log_severity
  - abseil/base/spinlock_wait (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/core_headers
    - abseil/base/errno_saver
  - abseil/base/throw_delegate (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/container/compressed_tuple (0.20200225.0):
    - abseil/utility/utility
  - abseil/container/inlined_vector (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/container/inlined_vector_internal
    - abseil/memory/memory
  - abseil/container/inlined_vector_internal (0.20200225.0):
    - abseil/base/core_headers
    - abseil/container/compressed_tuple
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/span
  - abseil/memory (0.20200225.0):
    - abseil/memory/memory (= 0.20200225.0)
  - abseil/memory/memory (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/meta (0.20200225.0):
    - abseil/meta/type_traits (= 0.20200225.0)
  - abseil/meta/type_traits (0.20200225.0):
    - abseil/base/config
  - abseil/numeric/int128 (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/strings/internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/meta/type_traits
  - abseil/strings/str_format (0.20200225.0):
    - abseil/strings/str_format_internal
  - abseil/strings/str_format_internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/types/span
  - abseil/strings/strings (0.20200225.0):
    - abseil/base/base
    - abseil/base/bits
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/base/throw_delegate
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/internal
  - abseil/time (0.20200225.0):
    - abseil/time/internal (= 0.20200225.0)
    - abseil/time/time (= 0.20200225.0)
  - abseil/time/internal (0.20200225.0):
    - abseil/time/internal/cctz (= 0.20200225.0)
  - abseil/time/internal/cctz (0.20200225.0):
    - abseil/time/internal/cctz/civil_time (= 0.20200225.0)
    - abseil/time/internal/cctz/time_zone (= 0.20200225.0)
  - abseil/time/internal/cctz/civil_time (0.20200225.0):
    - abseil/base/config
  - abseil/time/internal/cctz/time_zone (0.20200225.0):
    - abseil/base/config
    - abseil/time/internal/cctz/civil_time
  - abseil/time/time (0.20200225.0):
    - abseil/base/base
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/time/internal/cctz/civil_time
    - abseil/time/internal/cctz/time_zone
  - abseil/types (0.20200225.0):
    - abseil/types/any (= 0.20200225.0)
    - abseil/types/bad_any_cast (= 0.20200225.0)
    - abseil/types/bad_any_cast_impl (= 0.20200225.0)
    - abseil/types/bad_optional_access (= 0.20200225.0)
    - abseil/types/bad_variant_access (= 0.20200225.0)
    - abseil/types/compare (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - abseil/types/span (= 0.20200225.0)
    - abseil/types/variant (= 0.20200225.0)
  - abseil/types/any (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_any_cast
    - abseil/utility/utility
  - abseil/types/bad_any_cast (0.20200225.0):
    - abseil/base/config
    - abseil/types/bad_any_cast_impl
  - abseil/types/bad_any_cast_impl (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_optional_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_variant_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/compare (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/types/optional (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/bad_optional_access
    - abseil/utility/utility
  - abseil/types/span (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/meta/type_traits
  - abseil/types/variant (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_variant_access
    - abseil/utility/utility
  - abseil/utility/utility (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/meta/type_traits
  - Alamofire (5.2.2)
  - apptentive-ios (5.2.14)
  - BluedotPointSDK (15.3.0)
  - BoringSSL-GRPC (0.0.7):
    - BoringSSL-GRPC/Implementation (= 0.0.7)
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Implementation (0.0.7):
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Interface (0.0.7)
  - CocoaAsyncSocket (7.6.4)
  - CryptoSwift (1.3.1)
  - FBSDKCoreKit (7.1.1):
    - FBSDKCoreKit/Basics (= 7.1.1)
    - FBSDKCoreKit/Core (= 7.1.1)
  - FBSDKCoreKit/Basics (7.1.1)
  - FBSDKCoreKit/Core (7.1.1):
    - FBSDKCoreKit/Basics
  - Firebase/Analytics (6.29.0):
    - Firebase/Core
  - Firebase/Auth (6.29.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.7.1)
  - Firebase/Core (6.29.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.7.0)
  - Firebase/CoreOnly (6.29.0):
    - FirebaseCore (= 6.9.2)
  - Firebase/Crashlytics (6.29.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.3.1)
  - Firebase/Firestore (6.29.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.16.3)
  - Firebase/Messaging (6.29.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.6.1)
  - Firebase/RemoteConfig (6.29.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.8.0)
  - FirebaseABTesting (4.1.0):
    - FirebaseCore (~> 6.8)
  - FirebaseAnalytics (6.7.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.4)
    - GoogleAppMeasurement (= 6.7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30905.0)
  - FirebaseAuth (6.7.1):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (6.9.2):
    - FirebaseCoreDiagnostics (~> 1.3)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.5.0):
    - GoogleDataTransport (~> 7.0)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30905.0)
  - FirebaseCrashlytics (4.3.1):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleDataTransport (~> 7.0)
    - nanopb (~> 1.30905.0)
    - PromisesObjC (~> 1.2)
  - FirebaseFirestore (1.16.3):
    - abseil/algorithm (= 0.20200225.0)
    - abseil/base (= 0.20200225.0)
    - abseil/memory (= 0.20200225.0)
    - abseil/meta (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/time (= 0.20200225.0)
    - abseil/types (= 0.20200225.0)
    - FirebaseCore (~> 6.8)
    - "gRPC-C++ (~> 1.28.0)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 1.30905.0)
  - FirebaseInstallations (1.5.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.5.1):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
  - FirebaseMessaging (4.6.1):
    - FirebaseCore (~> 6.8)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Reachability (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseRemoteConfig (4.8.0):
    - FirebaseABTesting (~> 4.1)
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.1)
    - GoogleUtilities/Environment (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
  - GoogleAnalytics (3.17.0)
  - GoogleAppMeasurement (6.7.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30905.0)
  - GoogleDataTransport (7.1.0):
    - nanopb (~> 1.30905.0)
  - GoogleSymbolUtilities (1.1.2)
  - GoogleTagManager (7.1.3):
    - FirebaseAnalytics (~> 6.3)
    - GoogleAnalytics (~> 3.17)
    - GoogleUtilitiesLegacy (~> 1.3)
  - GoogleUtilities/AppDelegateSwizzler (6.7.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.1):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.7.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.7.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.1)"
  - GoogleUtilities/Reachability (6.7.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.7.1):
    - GoogleUtilities/Logger
  - GoogleUtilitiesLegacy (1.3.2):
    - GoogleSymbolUtilities (~> 1.1)
  - "gRPC-C++ (1.28.2)":
    - "gRPC-C++/Implementation (= 1.28.2)"
    - "gRPC-C++/Interface (= 1.28.2)"
  - "gRPC-C++/Implementation (1.28.2)":
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - "gRPC-C++/Interface (= 1.28.2)"
    - gRPC-Core (= 1.28.2)
  - "gRPC-C++/Interface (1.28.2)"
  - gRPC-Core (1.28.2):
    - gRPC-Core/Implementation (= 1.28.2)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Implementation (1.28.2):
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - BoringSSL-GRPC (= 0.0.7)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Interface (1.28.2)
  - GTMSessionFetcher/Core (1.4.0)
  - JustLog (3.0.5):
    - CocoaAsyncSocket (~> 7.6.3)
    - SwiftyBeaver (~> 1.8.3)
  - KochavaCoreiOS (3.17.0)
  - KochavaTrackeriOS (3.17.0):
    - KochavaCoreiOS (~> 3.16)
  - leveldb-library (1.22)
  - MarketingCloudSDK (7.2.1)
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - PromiseKit (6.13.1):
    - PromiseKit/CorePromise (= 6.13.1)
    - PromiseKit/Foundation (= 6.13.1)
    - PromiseKit/UIKit (= 6.13.1)
  - PromiseKit/CorePromise (6.13.1)
  - PromiseKit/Foundation (6.13.1):
    - PromiseKit/CorePromise
  - PromiseKit/UIKit (6.13.1):
    - PromiseKit/CorePromise
  - PromisesObjC (1.2.9)
  - Protobuf (3.12.0)
  - SpinnerView (0.1.1)
  - SwiftValidator (4.0.0)
  - SwiftyBeaver (1.8.4)
  - Typist (1.4.2)
  - WebViewJavascriptBridge (6.0.3)

DEPENDENCIES:
  - Alamofire
  - apptentive-ios (~> 5.2)
  - BluedotPointSDK
  - CryptoSwift
  - FBSDKCoreKit
  - Firebase/Analytics
  - Firebase/Auth
  - Firebase/Core
  - Firebase/Crashlytics
  - Firebase/Firestore
  - Firebase/Messaging
  - Firebase/RemoteConfig
  - GoogleTagManager
  - JustLog
  - KochavaTrackeriOS
  - MarketingCloudSDK
  - PromiseKit
  - Typist
  - WebViewJavascriptBridge

SPEC REPOS:
  trunk:
    - abseil
    - Alamofire
    - apptentive-ios
    - BluedotPointSDK
    - BoringSSL-GRPC
    - CocoaAsyncSocket
    - CryptoSwift
    - FBSDKCoreKit
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCrashlytics
    - FirebaseFirestore
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebaseRemoteConfig
    - GoogleAnalytics
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleSymbolUtilities
    - GoogleTagManager
    - GoogleUtilities
    - GoogleUtilitiesLegacy
    - "gRPC-C++"
    - gRPC-Core
    - GTMSessionFetcher
    - JustLog
    - KochavaCoreiOS
    - KochavaTrackeriOS
    - leveldb-library
    - MarketingCloudSDK
    - nanopb
    - PromiseKit
    - PromisesObjC
    - Protobuf
    - SwiftyBeaver
    - Typist
    - WebViewJavascriptBridge

EXTERNAL SOURCES:
CHECKOUT OPTIONS:

SPEC CHECKSUMS:
  abseil: 6c8eb7892aefa08d929b39f9bb108e5367e3228f
  Alamofire: 814429acc853c6c54ff123fc3d2ef66803823ce0
  apptentive-ios: 16951b1f9546bbae9165792679f865dc53bbe82f
  BluedotPointSDK: 729d468235468ed1737a0aa61106fbf3ac7b366a
  BoringSSL-GRPC: 8edf627ee524575e2f8d19d56f068b448eea3879
  CocoaAsyncSocket: 694058e7c0ed05a9e217d1b3c7ded962f4180845
  CryptoSwift: f12f037f6d0fcd6d48c96db0071b653de64e6c4d
  FBSDKCoreKit: b46507dc8b8cefed31d644e74d7cc30e2a715ef8
  Firebase: 57957c8d6eb3d8b80a560b1dc58be24724b89ff2
  FirebaseABTesting: 9e368b88c2f1c5d7a433828d9d224779b53207b6
  FirebaseAnalytics: aa522dce9fd93002ba1554467d23ce7092323000
  FirebaseAuth: a818d73466d51db897d3bf3c0f3baa3dae7fd4c0
  FirebaseCore: 7930a1946517d94256d857f97371ed993b55f7bd
  FirebaseCoreDiagnostics: 7535fe695737f8c5b350584292a70b7f8ff0357b
  FirebaseCrashlytics: 863c851b034baeb3116cd2c91743e37de2dcedfc
  FirebaseFirestore: 5ea7b0878363f9ec66bdcee0c29ad875d1b511ac
  FirebaseInstallations: 3c520c951305cbf9ca54eb891ff9e6d1fd384881
  FirebaseInstanceID: c4ad474b87787afd27d09541800620993b457d6f
  FirebaseMessaging: 942cfe05b4f53c95ab8959395ca35c200398b2f0
  FirebaseRemoteConfig: 521ff38593bed36fcb6f466fb6fffa99a753d783
  GoogleAnalytics: f42cc53a87a51fe94334821868d9c8481ff47a7b
  GoogleAppMeasurement: 345d365fd105e6682bf5084783a5352a3db26820
  GoogleDataTransport: af0c79193dc59acd37630b4833d0dc6912ae6bd5
  GoogleSymbolUtilities: 631ee17048aa5e9ab133470d768ea997a5ef9b96
  GoogleTagManager: a5b872a9aae225c83587cc526d816b0323961845
  GoogleUtilities: e121a3867449ce16b0e35ddf1797ea7a389ffdf2
  GoogleUtilitiesLegacy: 5501bedec1646bd284286eb5fc9453f7e23a12f4
  "gRPC-C++": 13d8ccef97d5c3c441b7e3c529ef28ebee86fad2
  gRPC-Core: 4afa11bfbedf7cdecd04de535a9e046893404ed5
  GTMSessionFetcher: 6f5c8abbab8a9bce4bb3f057e317728ec6182b10
  JustLog: d583795da0ed7da3c4adcd76c28031d4043a3258
  KochavaCoreiOS: 0dc05fb86adb2bd27f01e8b06e48e621ea789df3
  KochavaTrackeriOS: 3bc2417dd6b9e7bbe99b8acfee0f83e1447d7469
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  MarketingCloudSDK: 14cbb3e77f50c69aea078c6c70368ca29041eaee
  nanopb: c43f40fadfe79e8b8db116583945847910cbabc9
  PromiseKit: 28fda91c973cc377875d8c0ea4f973013c05b6db
  PromisesObjC: b48e0338dbbac2207e611750777895f7a5811b75
  Protobuf: 2793fcd0622a00b546c60e7cbbcc493e043e9bb9
  SpinnerView: 411d0af71d49975aab0e71764eb95f1b780bbb90
  SwiftValidator: 249b6b3ae3b294266c5b9de134d94f18f2d5aa47
  SwiftyBeaver: f9a9aba96a6a6166e21682377804d728b0d20b95
  Typist: 06465ab9867782aa6c81e38f073dfc01dab73deb
  WebViewJavascriptBridge: 7f5bc4d3581e672e8f32bd0f812d54bc69bb8e29

PODFILE CHECKSUM: c098f349c3e8e3bf0a4ba96fa9e07b421d3b8ef6

COCOAPODS: 1.9.3
`

**Comment by morganchen12** [comment] 2020-08-07 00:27
Thanks. TagManager uses CoreData to persist events and is definitely what's responsible for triggering this warning. I'll make a fix for it.

In the meantime, if you want to avoid this warning and don't need GoogleAnalytics in your project, you can simply remove GoogleAnalytics and log all of your app's events through FirebaseAnalytics instead.

**Comment by morganchen12** [comment] 2020-08-07 19:04
Googlers see internal change number cl/325478723

**Comment by morganchen12** [comment] 2020-08-07 20:35
The fix has been submitted to TagManager. TagManager operates on a different release schedule than Firebase, so you will not see the fix in the Firebase release notes.

**Closed** 2020-08-10 18:29 UTC
Labels: api: tagmanager

**Comment by enquel** [comment] 2020-09-07 15:54
@morganchen12 how can I apply the fix for GA for Unity? Which is obviously abandoned?
