### ISSUE TITLE
Xcode15 Beta1: Firebase iOS SDK: Unable to process Info.plist during build process

### ISSUE THREAD

**Issue by pavm035** [firebase/firebase-ios-sdk#11400] opened 2023-06-06 07:53 UTC
## Environment

- Xcode version: Xcode15 Beta1
- Firebase Component: Crashlytics
- Installation method: Swift Package Manager (SPM)
- Firebase SDK version: 10.4.0

## Problem

During the build process of my iOS application, I encountered an error related to processing the `Info.plist` file.

Here is the error message:
`error: Info.plist Error Unable to process Info.plist at path /Users/...../Info.plist
This could be a timing issue, make sure the Firebase run script build phase is the last build phase and no other scripts have moved RakutenIchiba.app from the location Xcode generated it. You can also add '$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)' as an "Input Files" dependency for your Firebase run script build phase.`

## Steps to Reproduce

1. [Add the steps you take to reproduce the issue. This could be setting up a new project, adding Firebase via SPM, adding a Run Script phase, etc.]

## What I've tried

- I've checked the order of Build Phases to make sure the Run Script phase for Firebase is the last phase.
- I've verified the location and reference of the `Info.plist` file.
- I've cleaned the project and cleared the derived data.
- [Add any other troubleshooting steps you've tried.]

Despite these attempts, the issue persists. Any guidance or suggestions to resolve this would be appreciated.

Thank you.

### Firebase SDK Version

10.4.0

### Xcode Version

15.0 Beta1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ninhgeocomply** [comment] 2023-06-06 11:24
I have the same issue too.

In my case the Xcode 15 doesn't copy the Info.plist to `/Users/...../` aka `/Users/{username}/Library/Developer/Xcode/DerivedData/{Scheme-...}/Build/Products/{...}-iphoneos/{App Name}.app/Info.plist`.

Workaround by copying the Info.plist to the build folder `/Users/...../` & rebuild.

**Comment by rizafran** [comment] 2023-06-06 19:01
Thanks for reporting, @pavm035. I tried to reproduce the issue, but I didn't encounter the same error. Is the issue only happen in Xcode 15 beta? Also, may I know if you've made any changes in your settings before the issue occurred?

**Comment by samedson** [comment] 2023-06-06 19:49
Hey I also wasn't able to reproduce this (I'm on Xcode Version 15.0 beta (15A5160n))

I do see the Info.plist in my app's binary:
![Screenshot 2023-06-06 at 3 45 55 PM](https://github.com/firebase/firebase-ios-sdk/assets/555046/b8bd66c1-3105-46bf-8574-594911f32ce6)

I wonder if there are new build settings that apply. Here are the settings for my app:
![Screenshot 2023-06-06 at 3 46 45 PM](https://github.com/firebase/firebase-ios-sdk/assets/555046/3d561d07-1c1e-47ec-8bbf-67c7ae918796)

If possible, can you check and see if any of your values differ for these settings?

**Comment by pavm035** [comment] 2023-06-06 23:44
> Thanks for reporting, @pavm035. I tried to reproduce the issue, but I didn't encounter the same error. Is the issue only happen in Xcode 15 beta? Also, may I know if you've made any changes in your settings before the issue occurred?

@rizafran  Yes this only happens in Xcode 15 beta and there are no any changes made

**Comment by hujunfeng** [comment] 2023-06-07 02:17
Also facing a similar issue with Xcode 15 beta. For me, it's consistently reproducible with a clean build.

**Comment by FlorianTousch** [comment] 2023-06-07 09:55
Same for me with xcode 15 beta1 !

**Comment by samedson** [comment] 2023-06-07 15:20
@pavm035, @hujunfeng, @FlorianTousch, could you take a look at the comment https://github.com/firebase/firebase-ios-sdk/issues/11400#issuecomment-1579353669 to see if our build settings match?

**Comment by FlorianTousch** [comment] 2023-06-07 15:36
Thanks for sharing, I fix my problem by deleting a Package !

This Package contained Fabric who's not supported 😅

**Comment by pavm035** [comment] 2023-06-07 20:28
> @pavm035, @hujunfeng, @FlorianTousch, could you take a look at the comment [#11400 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/11400#issuecomment-1579353669) to see if our build settings match?
> 
> Edit: No need to anymore - see the fix below: [#11400 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/11400#issuecomment-1581074907)

This will fix the issue, but it overrides your custom info.plist settings which we don't want

**Comment by pavm035** [comment] 2023-06-07 20:31
> I've found the setting that's causing the issue:
> 
> In Xcode 15, it looks like `User Script Sandboxing` is set to `YES` by default (it was set to `NO` by default in Xcode 14).
> 
> To workaround this issue, you can manually set it to `NO`: <img alt="Screenshot 2023-06-07 at 11 29 52 AM" width="1072" src="https://user-images.githubusercontent.com/555046/244119271-7031ed97-94af-47a5-a9dd-a39188ce9f38.png">
> 
> When I set it to NO, my `run` script succeeds.
> 
> I want to figure out if there's a way to set certain files as being accessibly by the Run Script.

For me this is already set to No, still same error.

BTW upload-symbols is the one who is causing this issue, if I comment on that execution everything seems to be fine but I can't see the script since it's binary

**Comment by samedson** [comment] 2023-06-07 20:51
@pavm035 2 questions:
 - When you do a "Show Package Contents" on your built `.app`, do you see the Info.plist file in there?
 - Also, if you put `echo $BUILT_PRODUCTS_DIR/$INFOPLIST_PATH` in your Run Script, for the path that spits out, does that correspond to your Info.plist?

<img width="610" alt="Screenshot 2023-06-07 at 4 49 34 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/555046/aee0ee1d-e445-4375-a340-a7172301a61e">

**Comment by pavm035** [comment] 2023-06-08 00:04
@samedson
- I don't see info.plist in built product(.app file)
- Yes `echo $BUILT_PRODUCTS_DIR/$INFOPLIST_PATH` points to the info.plist path in <package.app/Info.plist>

**Comment by siemensikkema** [comment] 2023-06-08 09:16
When supplying the input files to the run phase as per the documentation, Xcode 15 Beta 1 produces the error:

> Cycle inside [...]; building could produce unreliable results.

Xcodes seems to use what you put in the input files to determine the build order. When I move the input files into the script itself, the error goes away but the above problem mentioned in this GitHub issue appears together with the warning:

> DEBUG_INFORMATION_FORMAT should be set to dwarf-with-dsym for all configurations. This could also be a timing issue, make sure the Firebase run script build phase is the last build phase and no other scripts have moved the dSYM from the location Xcode generated it. Unable to process [...].app.dSYM at path /Users/[...]/Library/Developer/Xcode/DerivedData/[...]/Build/Products/[...]/[...].app.dSYM

What seems to be happening is that both the Info.plist and dSYM file are first put in place _after_ a successful build. The files are not there after a clean build producing the error but they first appear when building with the Crashlytics script commented out. This would mean that the script will always be one build behind and, in case of a clean build, will not not have either of the files available.

**Comment by samedson** [comment] 2023-06-08 20:06
We are working on some changes in `upload-symbols` to improve this experience. In the meantime, if you're running into issues, the best way to get unblocked is to set:

 - `User Script Sandboxing` to `NO
 - `Generate Info.plist File` to `YES`
 
 OR
 
 Run `upload-symbols` outside of the Xcode's Run Script Build Phase via shell script ([Instructions](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#upload-dsyms))

**Comment by pavm035** [comment] 2023-06-08 21:36
@samedson  For me `User Script Sandboxing to NO` is already set but however i can't use other one`Generate Info.plist File to YES` since i have custom plist  file to be processed. 

BTW i had lab session with apple folks about this issue and they mentioned that if we have any sample project which we can reproduces the issues then ask to rise feedback with this to take a look into this. So if you have sample project please share here or i try to create one and reproduce the issue over there

**Comment by JordanPJamieson** [comment] 2023-06-12 12:42
> Hey folks, just an update on this. We are working on some changes in `upload-symbols` to improve this experience. In the meantime, if you're running into issues, the best way to get unblocked is to either:
> 
> * Set both:
>   
>   * `User Script Sandboxing` to `NO`
>   * `Generate Info.plist File` to `YES`
> 
> OR
> 
> * Run `upload-symbols` outside of the Xcode's Run Script Build Phase via shell script ([Instructions](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#upload-dsyms))

Also running into this issue – glad it's being addressed.

Any timelines on when this may be resolved?

Thanks!

**Comment by samedson** [comment] 2023-06-12 18:17
@pavm035 you may be running into a bug - haven't been able to reproduce it. Can you post your build settings (with paths removed)? 

Here are my settings and I still see an Info.plist in the `.app` package

<img width="598" alt="Screenshot 2023-06-12 at 12 29 21 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/555046/a93eaec9-b0bd-4161-9636-0535bbfa07e0">

No ETA yet @JordanPJamieson but will try to have it out by the next release

**Comment by pavm035** [comment] 2023-06-13 03:55
@samedson  Here is the package settings
![Screenshot 2023-06-13 at 12 55 37](https://github.com/firebase/firebase-ios-sdk/assets/6092412/00db225c-5b55-4722-80ce-d86b33267aca)

**Comment by azarovalex** [comment] 2023-06-16 12:40
Also had issues with Xcode 15 because of a build phase that had '$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)' as an "Input Files" dependency.

A dirty workaround that works for me is to use
`INFOPLIST_PREPROCESS: YES`, `INFOPLIST_PREFIX_HEADER: $(BUILT_PRODUCTS_DIR)/Info.plist-Prefix.pch` and change the build step to create `$(BUILT_PRODUCTS_DIR)/Info.plist-Prefix.pch` with the values I want to appear in the final Info.plist, instead of modifying the Info.plist directly during the build phase.

**Comment by tanaakktungvt** [comment] 2023-06-21 02:07
> When supplying the input files to the run phase as per the documentation, Xcode 15 Beta 1 produces the error:
> 
> > Cycle inside [...]; building could produce unreliable results.
> 
> Xcode seems to use what you put in the input files to determine the build order. When I move the input files into the script itself, the error goes away but the above problem mentioned in this GitHub issue appears together with the warning:
> 
> > DEBUG_INFORMATION_FORMAT should be set to dwarf-with-dsym for all configurations. This could also be a timing issue, make sure the Firebase run script build phase is the last build phase and no other scripts have moved the dSYM from the location Xcode generated it. Unable to process [...].app.dSYM at path /Users/[...]/Library/Developer/Xcode/DerivedData/[...]/Build/Products/[...]/[...].app.dSYM
> 
> What seems to be happening is that both the Info.plist and dSYM file are first put in place _after_ a successful build. The files are not there after a clean build producing the error but they first appear when building with the Crashlytics script commented out. This would mean that the script will always be one build behind and, in case of a clean build, will not not have either of the files available.

same with me for with xcode 15 beta.

**Comment by mvn-trinnguyen-dn** [comment] 2023-06-21 04:12
I get an error with info.plist is empty when I run script of Crashlytics
![Screenshot 2023-06-21 at 11 09 16](https://github.com/firebase/firebase-ios-sdk/assets/67259315/7e1d4807-f110-4dd4-bf63-741abca1d190)
![Screenshot 2023-06-21 at 11 09 53](https://github.com/firebase/firebase-ios-sdk/assets/67259315/b04aec89-43df-4d3d-b655-3d19566c13e6)

**Comment by samedson** [comment] 2023-06-21 14:57
@pavm035 and others, I've uploaded a new build of upload-symbols to resolve these issues https://github.com/firebase/firebase-ios-sdk/pull/11463. Can you please try the new version of `upload-symbols` and see if it resolves your issues?

This version should
1. Support non-embedded / no Info.plist files (by not reading them)
2. Support `User Script Sandboxing`. You will need to update your `Input Files` or `Input File Lists` in your Run Script

Required Input Files:
```
$(BUILT_PRODUCTS_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist
$(BUILT_PRODUCTS_DIR)/$(EXECUTABLE_PATH)
${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}
${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
```

For more information, see the PR description for https://github.com/firebase/firebase-ios-sdk/pull/11463

**Comment by alrocha** [comment] 2023-06-27 12:32
> @pavm035 and others, I've uploaded a new build of upload-symbols to resolve these issues #11463. Can you please try the new version of `upload-symbols` and see if it resolves your issues?
> 
> This version should
> 
> 1. Support non-embedded / no Info.plist files (by not reading them)
> 2. Support `User Script Sandboxing`. You will need to update your `Input Files` or `Input File Lists` in your Run Script
> 
> Required Input Files:
> 
> ```
> $(BUILT_PRODUCTS_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist
> $(BUILT_PRODUCTS_DIR)/$(EXECUTABLE_PATH)
> ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}
> ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
> ```
> 
> For more information, see the PR description for #11463

Hi, thanks for the changes to fix the issue. 

I have updated to master and seems to work in the simulator, although when trying to run it  in a real device with iOS 17 Beta, is not working

<img width="898" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/8307263/b151f17f-459c-43ea-b509-c373a40304f7">

**Comment by ncooke3** [comment] 2023-06-27 16:39
The segmentation fault may be a different issue, #11413. @alrocha, are you using Firestore?

**Comment by alrocha** [comment] 2023-06-28 07:37
We don't @ncooke3, but might be related to some other Framework, I'll try to deep dive, couldn't find anything in apple forums.

**Comment by tanaakktungvt** [comment] 2023-06-29 01:42
> #11413
@alrocha 
build setting>other link flags add "-ld64"

**Comment by ncooke3** [comment] 2023-06-29 14:47
Thanks @tanaakktungvt, that solution seems to work for a lot of developers. Would you know why that is now needed on Xcode 15?

**Comment by tanaakktungvt** [comment] 2023-06-30 01:42
> 

https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking

> Thanks @tanaakktungvt, that solution seems to work for a lot of developers. Would you know why that is now needed on Xcode 15?
> 
> edit: seems like it's a workaround for a new linker bug ([comment](https://developer.apple.com/forums/thread/731089?answerId=756074022#756074022))

@ncooke3 
https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking
Apple just added new linker, the classic linker can still be work when using -ld64 flag

**Comment by pavm035** [comment] 2023-07-10 00:52
@samedson  Sorry for the delay, I have confirmed new upload symbols and it solved the issue. But i have one warning still not sure if it's related to this or a different one.
Thanks a lot for your effort on fixing this issue :)


![Screenshot 2023-07-10 at 9 46 48](https://github.com/firebase/firebase-ios-sdk/assets/6092412/fd265529-0b4b-4446-af39-dfd22249887d)

**Comment by srclima** [comment] 2023-07-14 23:43
Sigue igual con la Beta 4 =/

**Comment by samedson** [comment] 2023-07-24 19:36
@pavm035 sorry for the delay. That warning is unrelated, but you should just be able to update your project settings based on the warning and it will go away 👍 

@srclima if you're running into issues, you may check out this related issue that we need Apple's help to fix: https://github.com/firebase/firebase-ios-sdk/issues/11471

Closing this for now. For issues related to Xcode 15 that aren't plist related, feel free to check out the above issue or open a new one.

**Closed by samedson** 2023-07-24 19:36 UTC
Labels: api: crashlytics, needs-attention, Xcode 15 - iOS 17

**Comment by pavm035** [comment] 2023-07-25 00:10
@samedson  Thanks for the update, Do you gonna provide new version which includes this fix? if so would you please update the readme or relevant documentation for the instruction to following for input file list?
