### ISSUE TITLE
Xcode 14 & Firestore (9.6.0) Warning

### ISSUE THREAD

**Issue by Sunrise17** [firebase/firebase-ios-sdk#10226] opened 2022-09-16 08:19 UTC
### Description

I have installed the latest Firebase pod version as 9.6.0. I started to receive following Firestore (set_util.h) warning message in my iOS project as follows;

<img width="976" alt="Firestore" src="https://user-images.githubusercontent.com/26038249/190591429-30b6112c-ac38-4451-8924-1f4877d3d78e.png">

### Firebase SDK Version

9.6.0

### Xcode Version

14.0

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2022-09-16 10:49
Thanks for reporting, @Sunrise17. I suspect this was caused by the [recent release](https://firebase.google.com/support/release-notes/ios#cloud-firestore) in Firestore. I'll raise this to the team and see what we can do here.

**Comment by dconeybe** [comment] 2022-09-16 13:39
I've opened https://github.com/firebase/firebase-ios-sdk/pull/10227 to fix this warning.

**Comment by dconeybe** [comment] 2022-09-16 16:28
The fix will be included in the next release, which is scheduled for early October 2022.

**Closed** 2022-09-16 16:27 UTC
Labels: api: firestore
