### ISSUE TITLE
Firebase SDK continue send idfa to https://app-mesurement.com after full disabling collecting analytic data in pList

### ISSUE THREAD

**Issue by acoolaum** [firebase/firebase-ios-sdk#7061] opened 2020-11-13 09:29 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.14f
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Unknown
  * Other Firebase Components in use: FCM, Crashlytics
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac, Windows
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Firebase SDK continue send idfa to https://app-mesurement.com after full disabling collecting analytic data in pList 

#### Steps to reproduce:

1. Add Firebase App (Core), Firebase Cloud Messaging, Firebase Crashlytics
2. Disable collecting analytic data in pList
```
<key>FIREBASE_ANALYTICS_COLLECTION_DEACTIVATED</key>
<true/>
<key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key>
<false/>
```
3. Add link to AdSupport framework in x-code project (we use it for internal purposes)
4. Sniff outcoming application traffic on iOS device. You will see requests to **https://app-mesurement.com** which contains idfa string in body.

#### Relevant Code:

N/A

**Comment by chkuang-g** [comment] 2020-11-30 23:49
This seems to be an iOS SDK issue.  Let's transfer this to firebase-ios-sdk repo.

**Comment by chkuang-g** [comment] 2020-11-30 23:56
Dear firebase-ios-sdk support rotation,

To save your time, Firebase Unity SDK `6.16.1` is using Firebase iOS Pod version `6.32.2`.

Shawn

**Comment by paulb777** [comment] 2020-12-01 01:14
This is a duplicate of #5837 (Internal b/168251939) . Please follow the conversation there.

**Closed by paulb777** 2020-12-01 01:14 UTC
Labels: api: analytics
