### ISSUE TITLE
Memory Leaks seen [FIRInstanceIDKeychain.m]

### ISSUE THREAD

**Issue by Kush-Sharma** [firebase/firebase-ios-sdk#4368] opened 2019-11-20 11:16 UTC
Hi team,
After running the Xcode Instruments Leaks module on the app multiple times. I have seen this leak appear in almost all the runs:

<img width="1280" alt="Screen Shot 2019-11-21 at 12 09 07 AM" src="https://user-images.githubusercontent.com/27337204/69234120-373e2700-0bf3-11ea-98cb-cf9f6785cc96.png">

<img width="1280" alt="Screen Shot 2019-11-21 at 12 00 21 AM" src="https://user-images.githubusercontent.com/27337204/69233979-de6e8e80-0bf2-11ea-9573-4ae67d3a9678.png">

Firebase Pods in the application:
    pod 'Firebase/Analytics', '6.11.0'
    pod 'Firebase/Messaging', '6.11.0'
    pod 'Firebase/RemoteConfig', '6.11.0'
    pod 'FirebaseUI/Auth', '8.3.1'
    pod 'FirebaseUI/Google', '8.3.1'
    pod 'FirebaseUI/Facebook', '8.3.1'
    pod 'FirebaseUI/Email', '8.3.1'

Although it is a small leak still if it can be resolved, it will be appreciated.

**Comment by morganchen12** [comment] 2019-11-20 20:43
Looks like we're missing a `CFRelease(keychainQuery)` call.

**Comment by chliangGoogle** [comment] 2020-02-05 00:54
I think we released in the parent class that calls this method. Also I don't think I can reproduce. @Kush-Sharma  can you see if it still reproduce for you with the latest version?

**Comment by morganchen12** [comment] 2020-02-05 01:45
It may be helpful to add a comment to the code saying the CFRelease is called in the parent class.

**Comment by Kush-Sharma** [comment] 2020-02-12 02:58
This seems to have been resolved in the version **6.15.0** as I was unable to reproduce the leak after upgrading to that version.

**Comment by morganchen12** [comment] 2020-02-12 03:14
Thanks @Kush-Sharma, please let us know if it regresses and we'll re-open the issue.

**Closed by morganchen12** 2020-02-12 03:14 UTC
Labels: api: instanceid
