### ISSUE TITLE
App Crashes On Calling FirebaseApp.app()?.delete

### ISSUE THREAD

**Issue by Aishwaryalaxmi** [firebase/firebase-ios-sdk#4906] opened 2020-02-14 12:50 UTC
On calling the FirebaseApp.app()?.delete **kFirebaseInstallationsErrorDomain** will be thrown and application will be crashed. Please find the attached logs.
==================================
Xcode version - 11.0 
FirebaseAnalytics Version - 6.2.2
Firebase/CoreOnly - 6.16.0
FirebaseCore - 6.6.1
Firebase/Database - 6.16.0

====================================

<img width="924" alt="Screenshot 2020-02-14 at 6 11 35 PM" src="https://user-images.githubusercontent.com/22444085/74533043-a6a78680-4f56-11ea-88d4-feef0dfc70ae.png">

**Comment by maksymmalyhin** [comment] 2020-02-14 15:15
@Aishwaryalaxmi I am sorry to see you have the issue. 

From the first glance it looks like the reason of the issue is in the way Firebase Performance handles FirebaseApp deletion. We will investigate further to provide a solution for the issue.

A quick question. You didn't mention Firebase Performance in the list of used products. Did you just forget mentioning it or Firebase Performance was not supposed to be included in the project?

**Comment by Aishwaryalaxmi** [comment] 2020-02-14 15:28
@maksymmalyhin  We are using Firebase Performance (6.16.0 version).

**Comment by visumickey** [comment] 2020-02-18 12:26
@maksymmalyhin Looking at the stack trace, I don't think Firebase Performance is the cause of the crash. Firebase Performance is requesting the installations ID before dispatching performance events and that request seem to have caused the crash. Reassigning this to Installations ID team to have a look at the crash.

**Comment by andirayo** [comment] 2020-02-18 16:43
+Maksym Malyhin <mmaksym@google.com>
+FIS Engineering Team <fis-eng-team@google.com>

**Comment by paulb777** [comment] 2020-02-18 16:45
See discussion in #4909

**Comment by maksymmalyhin** [comment] 2020-02-18 16:58
There is a race condition in the ways `FirebaseApp ` and some SDKs like Performance, InstanceID, Analytics, etc. handle `FirebaseApp.delete()`: if a background task scheduled by an SDK and the SDK tries to access another SDK via [components](https://github.com/firebase/firebase-ios-sdk/blob/d9b7a33f0c0464e72e894aa7c207efc07dadbbbe/FirebaseCore/Sources/Private/FIRComponentContainer.h#L25) and the `FirebaseApp` is being deleted at the same time then the background task may either not get an instance or trigger creating another instance of the requested SDK with an inconsistent state of `FirebaseApp` which can lead to a crash or unexpected behaviour. 

I am working on a quick fix on Firebase Core level to mitigate the race condition consequences. The approach to eliminate the  race condition will be designed and discussed with SDK owners as a follow up.

**Comment by maksymmalyhin** [comment] 2020-02-18 19:27
@Aishwaryalaxmi Would you be able to try if #4918 fixes the issue for you? You'll need to modify your Podfile to use Firebase SDKs from GitHub master like:

```
pod 'Firebase', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :branch=>'mm/app-delete'
pod 'Firebase/Database', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :branch=>'mm/app-delete'
pod 'FirebaseCore', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :branch=>'mm/app-delete'
pod 'FirebasePerformance' # NOTE: replace `Firebase/Performance` by `FirebasePerformance` as it is a close source pod.
```

**Comment by maksymmalyhin** [comment] 2020-02-18 20:39
I cannot reproduce the issue in my test app after the fix, so I am closing the issue. Feel free to reopen with the steps to reproduce the issue (or ideally with a sample project) if you still have it after the fix.

**Closed by maksymmalyhin** 2020-02-18 20:39 UTC
Labels: api: core
