### ISSUE TITLE
[FR]Performance - Add support to cancel a FIRTrace

### ISSUE THREAD

**Issue by dangthaison91** [firebase/firebase-ios-sdk#6025] opened 2020-07-11 09:37 UTC
### Feature proposal

* Firebase Component: Performance
Currently, Performance only supports start/stop a Trace, but in some situations, we don't want to submit trace results and want to cancel it instead.

For example:
- Our App base on persisted user credential/access_token to determine App should navigate to **Login** or **MainTabbar** screen.
- We want to log time from **AppDelegate.didFinishLaunching -> MainTabbar.viewDidLoad**. Then, we start a trace in AppDelegate.didFinishLaunching.
- But we want to cancel trace when navigating to **Login** Screen.

Is there any way to cancel/not submit trace results to Firebase Server cause we don't want to bloat our tracing data with Login flow.

**Comment by morganchen12** [comment] 2020-07-13 17:14
Duplicate of https://github.com/firebase/firebase-ios-sdk/issues/1951

**Closed by morganchen12** 2020-07-13 17:14 UTC
Labels: api: performance, type: feature request
