### ISSUE TITLE
Crash prepareVerifyAssertionRequest

### ISSUE THREAD

**Issue by radvansky-tomas** [firebase/firebase-ios-sdk#2099] opened 2018-11-19 22:50 UTC
I am using firebasUI, everything worked well...but for some reason I cannot register using email+password anymore:

However exception is raised inside firebase auth:

```
- (void)prepareVerifyAssertionRequest:(FIRVerifyAssertionRequest *)request {
  [FIRAuthExceptionUtils raiseMethodNotImplementedExceptionWithReason:
      @"Attempt to call prepareVerifyAssertionRequest: on a FIREmailPasswordAuthCredential."];
}
```

Any changes on your side?!

**Comment by radvansky-tomas** [comment] 2018-11-19 23:05
Method is called from:

```
- (void)linkAndRetrieveDataWithCredential:(FIRAuthCredential *)credential
                               completion:(nullable FIRAuthDataResultCallback)completion
``` 


```
FIRAuthRequestConfiguration *requestConfiguration = self->_auth.requestConfiguration;
        FIRVerifyAssertionRequest *request =
            [[FIRVerifyAssertionRequest alloc] initWithProviderID:credential.provider
                                             requestConfiguration:requestConfiguration];
        **[credential prepareVerifyAssertionRequest:request];**
        request.accessToken = accessToken;
```

**Comment by radvansky-tomas** [comment] 2018-11-19 23:06
In my scenario I have anonym login...and after real registration process (using FirebaseUI + auto upgrade anonym users)

**Comment by radvansky-tomas** [comment] 2018-11-19 23:12
Removing exception

```
[FIRAuthExceptionUtils raiseMethodNotImplementedExceptionWithReason:
      @"Attempt to call prepareVerifyAssertionRequest: on a FIREmailPasswordAuthCredential."];
```

Completely resolves the issue, so can you explain its existence there ? Do we need to have any implementation there ?

**Comment by morganchen12** [comment] 2018-11-20 03:12
@renkelvin the crash seems to come from Auth, though it's triggered by FirebaseUI.

@radvansky-tomas can you add a complete stack trace?

**Comment by radvansky-tomas** [comment] 2018-11-20 04:17
@morganchen12 @renkelvin I've changed branch and did clean install (pods, derived data etc) and its gone...but still I have no idea what caused it AND what is the purpose of prepareVerifyAssertionRequest and its assertion in email/pass provider...could somebody give some explanation ? If it happen again I will post screenshots of stack trace, but as I already said flow was:

Anonym User -> Registration via email/pass -> upgrade anonym user

Which in fact called that link method, which contains prepareVerifyAssertionRequest, which is invalid for email. So I mean this can certainly happen again...

**Comment by radvansky-tomas** [comment] 2018-11-21 22:46
@renkelvin Started testing iPad application and crash is back:

![image](https://user-images.githubusercontent.com/12473664/48872021-2de97580-ee4c-11e8-9f34-6c91c22f134a.png)

**Comment by ishabazz** [comment] 2018-11-22 05:45
Having the exact same issue.  I'm certain that this used to work, but given that the code specifically says to throw an error, I'm not sure how.

**Comment by radvansky-tomas** [comment] 2018-11-23 02:05
@renkelvin @ishabazz So whats is the plan ?

**Comment by ishabazz** [comment] 2018-11-26 00:14
This is absolutely not the way to fix this, but it worked for me.
I changed line 984 of FIRUser.m from 

`if ([credential isKindOfClass:[FIREmailPasswordAuthCredential class]])`
to
`if ([(FIREmailPasswordAuthCredential*)credential  email] &&  [(FIREmailPasswordAuthCredential*)credential  password] )`

**Comment by radvansky-tomas** [comment] 2018-11-26 00:29
@ishabazz yeah I mean as I said, I can just bypass assertion and it will work...But I was looking for some proper solution from firebase team...as this seems pretty serious

**Comment by renkelvin** [comment] 2018-11-27 02:49
@ishabazz Could you help confirm that on `if ([credential isKindOfClass [FIREmailPasswordAuthCredential class]])`,`credential` is an instance of `FIREmailPasswordAuthCredential`?
"downcasting" is not the issue since `isKindOfClass:` check the class of the actual object, instead the pointer.

**Comment by radvansky-tomas** [comment] 2018-11-28 19:49
On my side there is correct class: <FIREmailPasswordAuthCredential: 0x600001ca3060>
But is still crashing on ipad

**Comment by radvansky-tomas** [comment] 2018-11-28 20:39
And Iam starting to think that issue is somewhere else: https://stackoverflow.com/questions/12386189/iskindofclass-doesnt-work-as-expected

And I am seeing similar console output on my side:
objc[4705]: Class FIREmailPasswordAuthCredential is implemented in both /Users/tr/Library/Developer/Xcode/DerivedData/timerush-gbxepiamopovhfhixqrcfwtzybfg/Build/Products/Debug-iphonesimulator/timerushframework.framework/timerushframework (0x10ea51330) and /Users/tr/Library/Developer/CoreSimulator/Devices/7CCB162C-FB5E-42B6-BADA-C001271E562E/data/Containers/Bundle/Application/752DF1AF-A91C-4BC9-A968-8BA7A05E4285/timerush-dev.app/timerush-dev (0x105a23788). One of the two will be used. Which one is undefined.

**Comment by paulb777** [comment] 2018-11-28 21:32
There's a good chance this is related to the `implemented in both` warning.  Please eliminate the warning and let's solve any resulting problems.

**Comment by renkelvin** [comment] 2018-12-04 01:47
@radvansky-tomas Hey, I couldn't reproduce the warning. According to your console log, it seems the duplicates are in timerushframework.framework and timerush-dev.app. Is is possible timerushframework.framework is a dependency of timerush-dev.app?

**Comment by radvansky-tomas** [comment] 2018-12-04 01:50
Thank you, yes...There is a bug in cocoa pods and way how firebase is structured. IE. if you have project with multiple targets -> app, watch, extensions and shared framework and you want to reference some dependencies in all of them and some not. Specially with firebase SDK when you cant really use them as dynamic frameworks in your custom pods. If anyone is interested, here is issue when I am trying to solve problem: https://github.com/CocoaPods/CocoaPods/issues/8321

**Comment by morganchen12** [comment] 2018-12-04 18:10
Closing since this isn't a Firebase issue, but feel free to continue discussing here.

**Closed by morganchen12** 2018-12-04 18:10 UTC
Labels: Auth
