### ISSUE TITLE
Latest release 10.23.1 missing Firebase.zip

### ISSUE THREAD

**Issue by guidedways** [firebase/firebase-ios-sdk#12718] opened 2024-04-06 00:25 UTC
### Description

Latest release 10.23.1 missing Firebase.zip file as part of assets

### Reproducing the issue

Click on Release page

### Firebase SDK Version

10.23.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by hansemannn** [comment] 2024-04-07 15:58
+1, The following link is invalid: https://github.com/firebase/firebase-ios-sdk/releases/download/10.23.1/Firebase.zip

**Comment by ncooke3** [comment] 2024-04-07 19:36
Dupe of #12686. Apologies for the confusion. There was no zip release for 10.23.1. The latest zip release is 10.23.**0**: https://github.com/firebase/firebase-ios-sdk/releases/download/10.23.0/Firebase.zip

The 10.24.0 zip release will be out this upcoming week.

**Comment by hansemannn** [comment] 2024-04-07 20:13
But then we cannot apply the critical bug fix related to the null-pointer crash introduce in 10.23.0. Therefore I'd kindly ask to reopen this until the binary is provided, as the 10.24.0 will likely cause new regressions again (minor releases in Firebase tend to do that, compared to patch releases.)

**Comment by ncooke3** [comment] 2024-04-08 14:26
Hi @hansemannn, since the Analytics SDK was the only SDK that changed in 10.23.1, I recommend downloading the following XCFrameworks from the CocoaPods distribution, and replacing the existing 10.23.0 XCFrameworks in your project.
- https://github.com/firebase/firebase-ios-sdk/blob/10.23.1/FirebaseAnalytics.podspec#L16 _(required)_
- https://github.com/firebase/firebase-ios-sdk/blob/10.23.1/GoogleAppMeasurement.podspec#L19 _(required)_
- https://github.com/firebase/firebase-ios-sdk/blob/10.23.1/GoogleAppMeasurementOnDeviceConversion.podspec#L20 _(only needed if you depend on `FirebaseAnalyticsOnDeviceConversion`)_

**Comment by paulb777** [comment] 2024-04-09 19:05
The 10.24.0 zip is now out. We have no plans to release a 10.23.2.

@hansemannn It is rare for us to introduce crashing bugs, and I can't find an instance of a crashing bug not reliably fixed in the subsequent minor release - https://firebase.google.com/support/release-notes/ios.

**Closed by paulb777** 2024-04-09 19:05 UTC
Labels: needs-info

**Comment by hansemannn** [comment] 2024-04-09 19:25
Thanks to the both of you! :-)
