### ISSUE TITLE
Crash - Bad Access - GULMutableDictionary

### ISSUE THREAD

**Issue by mberndt92** [firebase/firebase-ios-sdk#2351] opened 2019-02-05 14:15 UTC
### System Information
  * Xcode version: 10.1
  * Firebase SDK version: 5.15
  * Firebase Component: Networking
  * Component Version: 5.15

### Describe the problem
Firebase crashes our App inside the GULMutableDictionary class inside the method `removeObjectForKey` in line 61 with `EXC_BAD_ACCESS`.
#### Steps to reproduce:
There is no real go-to to reproduce it but it pops up every like 30 seconds to few minutes with almost 100% guarantee and at any given place inside our app, even without interaction.
I attached a screenshot for the crash in Xcode.

![screenshot 2019-02-05 at 15 06 40](https://user-images.githubusercontent.com/23187781/52279047-dd68bb00-2958-11e9-951b-770f0e623094.png)

**Comment by morganchen12** [comment] 2019-02-05 18:38
Duplicate of #1624

**Closed** 2019-02-20 21:21 UTC
Labels: GoogleUtilities
