### ISSUE TITLE
[FR]: Crashlytics support with Vision Pro

### ISSUE THREAD

**Issue by xtrachen** [firebase/firebase-ios-sdk#12432] opened 2024-02-27 06:40 UTC
### Description

1.my project ingeprate firebase with version 10.21
2.run app error with ""${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
"this script,the error is "Could not get platform name from build environment"
3.disable the script got a error log "<Warning>: 10.21.0 - [FirebaseSessions][I-SES000000] Found unknown OSName: "visionos" while converting."

how to fix it

### Firebase Product(s)

Analytics

**Comment by morganchen12** [comment] 2024-02-27 22:03
Duplicate of #12306.

**Closed** 2024-02-27 22:03 UTC
Labels: type: feature request, api: crashlytics, visionOS
