### ISSUE TITLE
FirebasePerformance FPRTraceBackgroundActivityTracker crash reports

### ISSUE THREAD

**Issue by taher-mosbah** [firebase/firebase-ios-sdk#6744] opened 2020-10-16 10:02 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.28.1
  * Firebase Component: Performance
  * Component version: 6.28.1
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem
Crash reports on Crashlytics:
```
0  libobjc.A.dylib                0x1abf1aeec objc_moveWeak + 208
1  CoreFoundation                 0x197eb6018 _CFXNotificationRegistrarAddObserver + 376
2  CoreFoundation                 0x197eb5e34 CFXNotificationRegistrarAdd + 560
3  CoreFoundation                 0x197ddfee4 _CFXNotificationRegisterObserver + 240
4  Foundation                     0x199074fcc -[NSNotificationCenter addObserver:selector:name:object:] + 420
5  App                            0x1007e8ee8 -[FPRTraceBackgroundActivityTracker init] + 4345630440
6  App                            0x1007f7140 -[FPRNetworkTrace start] + 4345688384
7  App                            0x1007fe0a4 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 4345716900
8  PlayerContainer                0x102aae43c __swift_memcpy3_1 + 16464
9  PlayerContainer                0x102aad9a4 __swift_memcpy3_1 + 13752
10 PlayerContainer                0x102a42030 globalinit_33_87BA326607EAFB276E73746DBA02F95A_func1 + 2376
11 PlayerContainer                0x102a45744 __swift_allocate_value_buffer + 444
12 PlayerContainer                0x102a42098 globalinit_33_87BA326607EAFB276E73746DBA02F95A_func1 + 2480
13 libdispatch.dylib              0x197a7efd0 _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x197a80ac8 _dispatch_client_callout + 20
15 libdispatch.dylib              0x197a87c08 _dispatch_lane_serial_drain + 580
16 libdispatch.dylib              0x197a88734 _dispatch_lane_invoke + 408
17 libdispatch.dylib              0x197a92528 _dispatch_workloop_worker_thread + 708
18 libsystem_pthread.dylib        0x1df3dc908 _pthread_wqthread + 276
19 libsystem_pthread.dylib        0x1df3e377c start_wqthread + 8
```

PS: We are having around 50 crashs per day all on iOS 14 and on low memory conditions RAM free < 50 MB

#### Steps to reproduce:
Cannot reproduce.

**Comment by maksymmalyhin** [comment] 2020-10-16 13:25
@taher-mosbah Thank you for the report. Could you please provide the following to help with the investigation:
1. The full crash report with other threads and the exception
2. A code snippet demonstrating how PlayerContainer sends the network request.

**Comment by taher-mosbah** [comment] 2020-10-16 15:20
thanks for the reply @maksymmalyhin, attached the full crash report (I can't see a download button to get full crash in TXT like we had in Crashlytics)
[Firebase crash.pdf](https://github.com/firebase/firebase-ios-sdk/files/5392545/Firebase.crash.pdf)

PlayerContainer is calling another SDK which I don't have access to its source, sorry.

**Comment by alikn** [comment] 2020-10-16 22:12
Thank you @taher-mosbah. Do you mind providing a few more pieces of information?
Specifically:
- Is the issue happening on background or foreground?
- Do you happen to know if the crash only happens during the app start or it can happen later?

Also, can you use the latest version of the sdk and see if the issue is still happening?

Thanks again.

**Comment by taher-mosbah** [comment] 2020-10-19 08:21
Thanks @alikn, the bug seem to happen on foreground (98% of occurrences)  and NOT during app start, according to Firebase logs most of the times with long sessions (> 1 hour) so it may be caused by a memory leak.

An update with the latest version of the SDK is in preparation but won't be in production before next month, will keep you updated.

**Comment by visumickey** [comment] 2020-10-22 20:35
Since the issue is happening on iOS 14 and the SDK version used is an older one (which was not iOS 14 tested), we would recommend to update to the newer version of perf SDK to let us know if you are still seeing this issue.

Marking this as closed for now. Please re-open if you still see this issue on the recent version of the perf SDK.

**Closed by visumickey** 2020-10-22 20:35 UTC
Labels: api: performance, needs-attention
