### ISSUE TITLE
FR: open source FirebaseInstanceID

### ISSUE THREAD

**Issue by herrernst** [firebase/firebase-ios-sdk#186] opened 2017-08-10 12:26 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 8.3
  * Firebase SDK version: 0.0.1
  * Library version: what's the difference?
  * Firebase Product: messaging

#### Steps to reproduce:

Messaging (and probably some other services) depend on FirebaseInstanceID (which is not open sourced yet). I'm using it like in the Podfile in your examples, locking to an older version of FirebaseInstanceID (which doesn't have dependency on the full closed source Firebase SDK): https://github.com/firebase/firebase-ios-sdk/blob/0297375121c3f13a4cfe23271793990b980bddee/Example/Podfile#L84-L86
What's the plan for this? Will FirebaseInstanceID open sourced in the near future and integrated into this open source SDK? Thanks.

**Comment by rsattar** [comment] 2017-08-10 17:02
@herrernst This is something we are interested in doing, but unfortunately we currently cannot for various reasons. I can't give a timeline on this, unfortunately!

What's the main desire to see it open-sourced from your end? Just curious. Thanks for the FR!

**Comment by herrernst** [comment] 2017-08-11 08:51
Thanks for your answer.
> What's the main desire to see it open-sourced from your end?

The generic reasons why to prefer open source over closed source: trust (I would like to see the code I include in my app to know what it does) and potential better debugging when there would be a problem.
I can live with it for now, only hope that the old 1.0.9 version of FirebaseInstanceID will not stop working anytime soon ;-)

**Comment by rsattar** [comment] 2017-08-11 16:33
Thanks for the response @herrernst! Your reasons make perfect sense, and that's why we've been open-sourcing our SDKs. The InstanceID SDK will have newer versions that will continue to work, though it will remain closed-source for now. The locking of the version to `1.0.9` was temporarily, will be fixed soon.

**Comment by gregbzh** [comment] 2017-11-02 14:47
Hello, I am currently porting Messaging on macOS. Since Messaging is using FirebaseInstanceID, and is currently only available for iOS, it could be nice to make it open source so we can use it also for macOS.

**Comment by herrernst** [comment] 2018-04-05 13:02
Any update on this? [FirebaseInstanceID 2.0.3](https://github.com/CocoaPods/Specs/blob/master/Specs/3/6/0/FirebaseInstanceID/2.0.3/FirebaseInstanceID.podspec.json) removed the dependency on FirebaseCore, but [2.0.8](https://github.com/CocoaPods/Specs/blob/master/Specs/3/6/0/FirebaseInstanceID/2.0.8/FirebaseInstanceID.podspec.json) added it again. Any reason why?

**Comment by paulb777** [comment] 2018-04-05 13:41
FirebaseInstanceID added dependencies to FirebaseCore for logging.

It's still the plan to open source FirebaseInstanceID but I can't give an update on timing.

**Comment by chliangGoogle** [comment] 2018-10-08 19:03
InstanceID use the [NSTimeZone localTimeZone] to get local timezone.

**Closed** 2019-02-21 18:51 UTC
Labels: InstanceID, Messaging, feature-request

**Comment by herrernst** [comment] 2019-03-07 10:13
Thanks for your effort! But when installing Firebase 5.18.0 with (the now open source) FirebaseInstanceID 3.6.0 via CocoaPods, I still get the precompiled framework binary without source (in contrast to e.g. FirebaseCore or FirebaseMessaging, where I get lots of *.m files). Am I expecting something wrong?

![screenshot 2019-03-07 at 11 00 20](https://user-images.githubusercontent.com/20795/53948888-254e3f80-40c9-11e9-89c2-827cc5a8cc15.png)

**Comment by paulb777** [comment] 2019-03-07 15:46
@herrernst Thanks for the report! We've reproduced and discovered a glitch in the release process and are hoping to get the right version out ASAP.

**Comment by herrernst** [comment] 2019-03-07 16:27
@paulb777 Thank you!

**Comment by paulb777** [comment] 2019-03-07 18:52
FirebaseInstanceID 3.7.0 is now available.  Thanks @herrernst for the report!

You may need to run `pod deintegrate` or `rm -rf Pods` before running `pod update`.

**Comment by herrernst** [comment] 2019-03-08 13:46
@paulb777 Thanks again. Source is now installed. Unfortunately, I have another problem. Something is broken when having "use_frameworks!" in the Podfile, my app crashes with "+[FIRInstanceIDCheckinPreferences preferencesFromKeychainContents:]: unrecognized selector sent to class 0x10f92f998".

It's reproducible in a fresh project:

* Create new Objective-C Single View App, close project
* `pod init`, add "pod 'FirebaseMessaging'" and uncomment "use_frameworks!", execute `pod install`
* Open workspace, add suitable GoogleService-Info.plist
* In app delegate:
````
#import <FirebaseCore/FirebaseCore.h>
#import <FirebaseMessaging/FirebaseMessaging.h>
````
and
````
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [FIRApp configure];
    NSLog(@"token: %@", [FIRMessaging messaging].APNSToken); // needed to trigger crash
    return YES;
}
````

**Comment by paulb777** [comment] 2019-03-08 17:56
@herrernst I'm not able to reproduce. Maybe there is some stale build state?  Are you able to see the crash in the Xcode debugger?

**Comment by herrernst** [comment] 2019-03-13 16:09
I've cleaned the project, still: 
![Screenshot 2019-03-13 at 16 34 58](https://user-images.githubusercontent.com/20795/54295143-c5690480-45b2-11e9-8fe2-92412c05765d.png)

**Comment by herrernst** [comment] 2019-03-13 16:10
Example project attached.
[TestFirebaseBuild.zip](https://github.com/firebase/firebase-ios-sdk/files/2962434/TestFirebaseBuild.zip)

**Comment by paulb777** [comment] 2019-03-19 17:52
@herrernst The `unrecognized selector` issue doesn't reproduce with CocoaPods 1.6.1. I reproduced it with CocoaPods 1.5.3 and worked around it there by adding `-ObjC` to the `Other Linker Flags` Build Setting.

**Comment by herrernst** [comment] 2019-03-20 17:30
@paulb777 Thanks for your help, after upgrading CocoaPods it's working now!!

**Comment by jkmathew** [comment] 2019-05-25 18:44
@paulb777 I am using firebase with flutter application. 
Still facing a crash with log
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FIRInstanceIDCheckinPreferences preferencesFromKeychainContents:]: unrecognized selector sent to class 0x102cfcaf8'`.

```
$pod --version
1.7.0
```
