### ISSUE TITLE
Bug: Firebase analytics sends 2 screen_view events, if you set screen name

### ISSUE THREAD

**Issue by ElyasNaranjeeSani** [firebase/firebase-ios-sdk#2181] opened 2018-12-12 15:47 UTC
* Xcode version: 10.1
  * Firebase SDK version: 5.14.0
  * Firebase Component: Analytics

#### Steps to reproduce:

Set a custom name for your screen and look at the DebugView dashboard. Your will see 2 `screen_view` events reported.
#### Note: 
This only happens only first time the view controller gets allocated and after view is allocated then it sends only one event if the view appears again.

#### Note 2: 
If you are trying to re-produce this by looking at debug-view tool in Firebase dashboard, another bug in dashboard may cause you think this is not happening. Because there is a bug in dashboard which you need to reload the page from your browser otherwise you see more duplicated events in DebugView's real time view. 

#### Comments: 
As I understood, `Analytics.setScreenName ` causes an event to be sent. (which needs to be discussed somewhere else as its not mentioned anywhere in docs that this triggers screen_view event and looks like just a simple set name as the function's name says too but seems its not).

By having this assumption that `Analytics.setScreenName` sends an event, as we call this func in `viewDidApear`  right after `super.viewDidAppear(animated)`, I'm just guessing that this is happening because maybe firebase is sending the screen_view event both in viewDidLoad and viewDidAppear. so this is why we get 2 events only first time the view controller gets allocated and after that we get only one event. 

#### Relevant Code:
I'm settings the screen name as below with setting the screenClass to nil.
```
 Analytics.setScreenName("blabla", screenClass: nil)
```

**Comment by ElyasNaranjeeSani** [comment] 2018-12-18 12:50
@htcgh any news on this?

**Comment by paulb777** [comment] 2018-12-18 14:51
Internally tracking at b/121187306

**Comment by allenktv** [comment] 2018-12-18 19:21
Looks like a duplicate of this [bug](https://github.com/firebase/firebase-ios-sdk/issues/1894). For that bug, the quickstart-app was showing the same duplicate screen view when calling setScreen manually.

To re-iterate from there: For iOS, we intercept screen changes to automatically log a screen view event. This is how we are able to do automatic screen view reporting. The first and second screen_view (FoodPickerViewController and ViewController without the "firebase_screen")  are logged because of this. The third screen_view event is due to the quickstart app [calling setScreen manually](https://github.com/firebase/quickstart-ios/blob/master/analytics/AnalyticsExample/ViewController.m#L50).

This is working as intended as of now, however we may want to re-visit this in the future and possibly do some sort of de-duping screen_view events based on parameters.

**Closed** 2018-12-18 19:33 UTC
Labels: Analytics

**Comment by sirshannon** [comment] 2019-02-09 19:04
I'm confused.
Are you saying you intend for us to have 2 screen views when we use setScreen or that you intend for us to not use setScreen?

If the only way to have a nice useable "screen" name value is to use setScreen but that won't prevent the nameless duplicate screen views, then we effectively can't set or use screen names at all without ruining the integrity of screen view analytics.

There is no way this is working as intended.  If it is, please help me understand your intentions around screen views and screen names.

**Comment by hbreumelhof** [comment] 2019-03-25 00:53
Is there not a way to allow us to disable automatic screen tracking so we can manually do it with the setScreen instead?

**Comment by nemdub** [comment] 2019-05-03 14:13
this is such bad behavior. Google is forcing us to move away from the original Google Analytics SDK, but the Firebase Analytics is a half-baked product! why, Google?

**Comment by rickydameliocroc** [comment] 2019-06-07 02:41
We have also encountered this bug, and it took me quite a while to figure out that it was the screen name setting which was causing the issue. I've since been in contact with some helpful Google support members who tell me this is **behaving as expected**.

I am astounded that this bug - **and it is a bug, no matter how you try to slice it** - has existed for so long, and that its presence to Google receives absolutely no concern or priority. It is embarrassing and has drastic consequences on measurement. In the iOS header documentation, the class actually tells you how to use this API, and doing so by their instructions **leads to duplicate events**.

**Here's a note to the misguided engineers who claim that this is not a problem:**
1. Marketers do not understand class names and we do not want to report our analytics in that way.
2. Some view controllers are used in various contexts, and therefore reporting the class name is largely useless.

FIX THIS NOW or LET US REPORT OUR OWN SCREENS ACCURATELY BY OURSELVES.

**Comment by fluidsonic** [comment] 2019-06-14 13:47
+1 on supporting manual-only tracking. The automatic one is quite unreliable and doesn't know about app specifics. Navigation controllers are tracked but that doesn't make sense. Events are sent or duplicated when the screen doesn't actually change (the parent controller could change or the navigation controller removes the screen from the window for a split-second to perform the parallax transition etc). App developers can develop even more complex view controllers where it's impossible for a framework to foresee what should get tracked and when.
It's even worse when multiple view controllers are visible at the same time.

Looking at how tracking currently works, manual tracking should be doable by manually sending `screen_view` + adding the screen parameters to all other events, isn't it?

**Comment by imediayala** [comment] 2019-06-18 16:39
I've also been running thru the same issue, it seems like the thread is now close.
So there's no other fix than manual tracking ???
        Analytics.setScreenName(screenName: String? screenClass: String?)
In that case how would i track defined parameters on each screen_view event?

**Comment by allenktv** [comment] 2019-06-18 16:42
Hi all, as mentioned in a previous comment here, this is a duplicate of: https://github.com/firebase/firebase-ios-sdk/issues/1894. We are actively working on this and that thread will be updated once there is a solution in place, thank you for your patience.
