### ISSUE TITLE
FCM refreshes messaging token multiple times per day

### ISSUE THREAD

**Issue by vladogrigorov** [firebase/firebase-ios-sdk#7475] opened 2021-02-08 13:21 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.3.0
  * Installation method: Zip file
  * Firebase Component: Cloud Messaging

### [REQUIRED] Step 2: Describe the problem
I have integrated FCM in my app and I'm able to send push notifications successfully. My app receives the updated messaging tokens through FIRMessagingDelegate:

- (void)messaging:(nonnull FIRMessaging *)messaging
    didReceiveRegistrationToken:(nullable NSString *)fcmToken;

Most app users send an updated token occasionally as expected. But a small part of the users send an updated messaging token multiple times a day. The documentation states that 

"The registration token may change when:

  * The app is restored on a new device
  * The user uninstalls/reinstall the app
  * The user clears app data."

I believe this is not the case, as the most acute cases send a new token each second the app is active, generating thousands of requests to my backend per day.

#### Steps to reproduce:
I cannot reproduce this issue in-house. It occurs to a small part of my users.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by chliangGoogle** [comment] 2021-02-08 20:34
@vladogrigorov Would it be possible some of the users are using an old Messaging SDKs? Because we had issue in the past that token kept getting refreshed.

**Comment by vladogrigorov** [comment] 2021-02-08 21:37
@chliangGoogle We update Firebase SDK frequently and there are quite a few versions out there. However, the users with the most updates (in the thousands) were all with the latest app version, which uses 7.3.0. That version was live in the App Store since Jan 20, but the flood of token updates began on Feb 2.

**Comment by chliangGoogle** [comment] 2021-02-17 01:36
Do you happen to have a token from the product device that have updated multiple times a day? You can send it to my email chliang@google.com and I can forward to my team to investigate further.

**Comment by vladogrigorov** [comment] 2021-02-17 08:01
I've sent you a log file with 5 token refreshes within 7 seconds. Thank you for looking into it.

**Comment by android-maker** [comment] 2021-03-02 23:43
Same issue is happening for our users ... as @vladogrigorov mentioned the flood of FCM push token started around Feb 2 for us as well. Is there a way to mitigate this issue as its leading to unnecessary request to our backend.

We use firebase-messaging:20.1.0 for all our customers.

**Comment by chliangGoogle** [comment] 2021-03-03 00:47
@android-maker Is this happening on android SDKs for you?

**Comment by android-maker** [comment] 2021-03-03 02:06
@chliangGoogle yes it’s happening on our android app.

**Comment by chliangGoogle** [comment] 2021-03-03 02:16
Are you able to reproduce locally with debugLog or getting a list of fcm token. You can send them to my email if you are not comfortable sharing here.

**Comment by android-maker** [comment] 2021-03-03 03:10
Hey @chliangGoogle , I have tried but not been able to reproduce locally but I can confirm that the traffic for fcm token update to my servers has increased by atleast 10-15 times the usual.

**Comment by android-maker** [comment] 2021-03-03 23:55
For short term mitigation can updating the firebase-messaging:20.1.0 dependency to the latest one help ?

**Comment by chliangGoogle** [comment] 2021-03-04 19:18
@android-maker Not really, I think this might be a backend issue since it happens on both iOS and Android. We are working with our backend team to figure it out.

**Comment by chliangGoogle** [comment] 2021-03-04 19:20
@android-maker Do you know the date the token refresh starting to happen for you?

**Comment by android-maker** [comment] 2021-03-04 19:43
@chliangGoogle the first spike I noticed was around 26th Jan,2021 for android. Can you please confirm if there is an increase in overall push token generation from FCM backend ?

**Comment by chliangGoogle** [comment] 2021-03-04 19:46
@android-maker Do you have any tokens refreshed during those time that you can send to me?

**Comment by android-maker** [comment] 2021-03-04 20:18
sent to your email.

**Comment by android-maker** [comment] 2021-03-05 19:29
@chliangGoogle are there any updates for this issue?

**Comment by chliangGoogle** [comment] 2021-03-05 20:01
@android-maker Thanks for the info. I'm routing it to our backend team to investigate the tokens you sent to us.

**Comment by android-maker** [comment] 2021-03-19 07:05
@chliangGoogle is thr any update with the issue??

**Comment by qbarev** [comment] 2021-09-13 10:01
Hello.
I had same issue at May 2021. 
Is there are any solutions?
Thank you.

**Comment by chliangGoogle** [comment] 2021-09-13 15:59
@qbarev Do you mind share with us the debugLog? Also are you using the latest SDK as we recently fix an issue related to token generation.

**Comment by qbarev** [comment] 2021-09-13 18:17
I have no access to logs unfortunately. 

I don't remember certain version of firebase. Maybe 8.0.0 and lower judging by the release dates.

Does this problem fixed in current version? (Or in 8.6.1) I have to ask because the problem is with a certain percentage of users and is difficult to reproduce.

Thank you.

**Comment by chliangGoogle** [comment] 2021-09-13 18:28
We can't reproduce on iOS and @android-maker reports this also happens on Android.

If you can reproduce with debugLog would be much easier for us to identify the issue.

**Comment by android-maker** [comment] 2021-09-13 21:16
@qbarev I fixed the problem by removing a call within my code (Android) where the token was deleted from the cache in the app and when you request a new token from FCM it basically generates a new one for you.  This was not linked to any particular SDK as it was happening across all SDKs for me. I think there was a change made in the FCM backend and its behavior was modified to generate a new token every-time a token request was made to FCM servers . Prior to beginning of this issue the FCM backend may be returning the cached token or something on those lines.

Best check you code and make sure you are not clearing the cache in the app for the variable which stores your FCM token.

**Comment by chliangGoogle** [comment] 2021-09-20 06:34
Since the original post owner hasn't responded for a while and @android-maker also had it fixed. Close this issue and please open a new one if your case is different than the original post. Thanks!

**Closed by chliangGoogle** 2021-09-20 06:34 UTC
Labels: api: messaging
