### ISSUE TITLE
Firebase/Performance crashes Password Autofill screen

### ISSUE THREAD

**Issue by Igor-Palaguta** [firebase/firebase-ios-sdk#2283] opened 2019-01-18 11:41 UTC
* Xcode version: 10.0
  * Firebase SDK version: 5.15.0
  * Firebase Component: Performance
  * Component version: 5.15.0

We have very frequent crash 0.5 % of all users who visited registration screen with password autofill fields. We started to have it after adding Firebase/Performance. Also we have confirmation from other developers that after removing Firebase/Performance it stopped crashing. Here is related discussion https://stackoverflow.com/a/54227163/2035054

**Comment by ryanwilson** [comment] 2019-01-18 13:33
Thanks for the report, also tracked internally at b/123065386.

@visumickey can you investigate and see if Perf is the cause or not? It doesn't look like there are Firebase references in the stack trace, but a few users seem to think Perf is the issue.

**Comment by visumickey** [comment] 2019-01-18 16:55
@Igor-Palaguta Can you share the detailed stack trace for this issue? Firebase performance does not have anything related to the UIActivity on the screen, so it is surprising to hear that the issue is related to UIActions. If this is predictably reproduce-able, can you share any sample app?

It would be helpful to understand the version of the Firebase Performance POD you are using. (Note: Firebase Performance will have its own version number in the Podfile.lock).

**Comment by Igor-Palaguta** [comment] 2019-01-18 17:24
@visumickey 

Cartfile.resolved
```shell
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "5.15.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "5.15.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" "5.15.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json" "5.15.0"
```

I could not replicate this issue, just can see crashes in fabric, but some people could do it: https://stackoverflow.com/questions/52879044/crash-in-uikitcore-uiviewcontroller-viewdidmovetowindowshouldappearordisappear#comment93141683_52879044

Yesterday in stackoverflow appeared answer that after removing Firebase/Performance issue gone.
I checked when we added Firebase/Performance (october 2018) and we have this crash exactly after integration. We did not change anything on screen where we have crash for a long time. I also asked one more developer who also have this issue, and he also confirmed that they use Firebase/Performance

**Comment by Batvos** [comment] 2019-01-19 00:39
@visumickey 

Hi,
 
Here is my test project https://github.com/Batvos/firebaseperfomanceissue where you can reproduce this crash.

**Comment by Igor-Palaguta** [comment] 2019-01-21 13:02
@Batvos test app looks empty

**Comment by Batvos** [comment] 2019-01-21 13:58
> @Batvos test app looks empty

Ops, Sorry. I don't how it happened:) I'll push a normal version today later

**Comment by Batvos** [comment] 2019-01-21 18:04
@Igor-Palaguta I've updated project. But you need download your own GoogleService-Info.plist file from firebase project and add it to the root of project. Also you need install pods.

**Comment by visumickey** [comment] 2019-01-25 00:31
This looks like a very tricky issue. We are able to reproduce the issue, but we are trying ways to find the root cause to have a fix on this. Will keep investigating this crash to arrive at a solution soon.

**Comment by donnellyk** [comment] 2019-02-05 22:58
Also seeing this crash when we added `Firebase/Performance`

**Comment by AnilVarghese** [comment] 2019-02-09 15:05
Indeed Firebase/Performance framework is causing the crash.
We are not supporting password autofill in our app, still it crashes. Looks like iOS is internally checking for availabilty of password autofill for textfiled with secure text entry.  We have disabled the firebase performance by setting `firebase_performance_collection_deactivated` to true in Info.plist  as a temporary solution.
 
To reproduce the crash, on sign up screen when the password textfield(secure text entry) is active put the app into background.

**Comment by xuaninbox** [comment] 2019-02-13 19:52
Any update on this issue?

**Comment by simonbengtsson** [comment] 2019-02-17 23:01
We use firebase performance and have this crash as well. I can't see anything about firebase performance in the crash logs however. I have been able to reproduce it, but not consistently.

[crashlog.txt](https://github.com/firebase/firebase-ios-sdk/files/2873513/crashlog.txt)

**Comment by visumickey** [comment] 2019-02-28 22:39
@Igor-Palaguta Need one more information to debug this further. Do we know the version of Firebase from where this issue has started spiking?

**Comment by Igor-Palaguta** [comment] 2019-03-01 10:38
@visumickey we started to use Firebase Performance since October 2018. And it was `5.10.0` version.

**Comment by bettola** [comment] 2019-03-01 14:40
We have the same crash on production app

**Comment by choiks14** [comment] 2019-03-06 02:17
same here

**Comment by visumickey** [comment] 2019-03-06 08:52
We have nailed down the issue here and we working on a fix for this. The upcoming release should have the fix rolled out.

**Comment by flaviobittenca** [comment] 2019-03-08 09:11
Hey @visumickey, do you have any perspective about when this fix will be released? This is the top crash for my side, unfortunately 😅

**Comment by visumickey** [comment] 2019-03-08 15:07
At this time, we are planning to have this launched at M45. Planned to be available to the developers March 19 (M45).

**Closed** 2019-03-19 21:55 UTC
Labels: api: performance
