### ISSUE TITLE
[Crash] Firebase FirebasePerformance 7.0.0

### ISSUE THREAD

**Issue by mariohahn** [firebase/firebase-ios-sdk#6886] opened 2020-11-03 09:44 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 7.0.0
  * Installation method: `CocoaPods`
  * Firebase Component: FirebasePerformance

### [REQUIRED] Step 2: Describe the problem

Since we added FirebasePerformance our app is crashing.
<img width="1243" alt="Bildschirmfoto 2020-11-03 um 10 39 14" src="https://user-images.githubusercontent.com/915933/97970045-36c97c80-1dc1-11eb-8619-21a835d3aa42.png">

**Comment by mariohahn** [comment] 2020-11-03 09:58
In our app we register a custom `URLProtocol` maybe that could be a reason for the issue?

**Comment by maksymmalyhin** [comment] 2020-11-03 14:52
Looks like a duplicate of #6734. Feel free to reopen if you think otherwise.

**Closed by maksymmalyhin** 2020-11-03 14:52 UTC
Labels: needs-triage
