### ISSUE TITLE
Crash: +[GULNetworkURLSession setSessionInFetcherMap:forSessionID:]

### ISSUE THREAD

**Issue by jfk056** [firebase/firebase-ios-sdk#11527] opened 2023-07-11 08:48 UTC
### Description

. Crashlytics report suggests early crash within 5s of starting the application exclusively on iOS 16. 

### Reproducing the issue

Don't have exact steps to reproduce

### Firebase SDK Version

10.9.0

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics, Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell
# Crashlytics - Stack trace
# Application: bundle.id
# Platform: apple
# Version: 1.0.5 (1)
# Date: Mon Jul 10 2023 14:33:57 GMT+0200 (Central European Summer Time)

com.apple.main-thread
0  CoreUI                         0x997b0 _findIndexForKey + 92
1  CoreUI                         0x1dc48 BOMTreeGetValueSize + 128
2  CoreUI                         0xabdc -[CUICommonAssetStorage assetForKey:] + 88
3  CoreUI                         0xa800 -[CUIStructuredThemeStore lookupAssetForKey:] + 48
4  CoreUI                         0xa670 -[CUIStructuredThemeStore renditionWithKey:usingKeySignature:] + 160
5  CoreUI                         0x897c -[_CUIInternalLinkRendition unslicedImage] + 68
6  CoreUI                         0x8858 -[CUIThemeRendition uncroppedImage] + 84
7  CoreUI                         0x7fa4 -[CUINamedVectorGlyph _lookupCatalogImageForIdiom:] + 356
8  CoreUI                         0x6f20 -[CUINamedVectorGlyph initWithName:scaleFactor:deviceIdiom:pointSize:fromCatalog:usingRenditionKey:fromTheme:] + 312
9  CoreUI                         0x644c -[CUICatalog namedVectorGlyphWithName:scaleFactor:deviceIdiom:layoutDirection:glyphSize:glyphWeight:glyphPointSize:appearanceName:] + 2576
10 UIKitCore                      0x9ba3c __78-[_UIAssetManager imageNamed:configuration:cachingOptions:attachCatalogImage:]_block_invoke_2 + 124
11 UIKitCore                      0xa1874 __82-[_UIAssetManager _lookUpObjectForTraitCollection:withAccessorWithAppearanceName:]_block_invoke + 80
12 UIKitCore                      0x179238 -[UITraitCollection _enumerateThemeAppearanceNamesForLookup:] + 240
13 UIKitCore                      0xc9550 -[_UIAssetManager _lookUpObjectForTraitCollection:withAccessorWithAppearanceName:] + 192
14 UIKitCore                      0xc7fa0 __78-[_UIAssetManager imageNamed:configuration:cachingOptions:attachCatalogImage:]_block_invoke + 596
15 UIKitCore                      0xc893c -[_UIAssetManager imageNamed:configuration:cachingOptions:attachCatalogImage:] + 300
16 UIKitCore                      0xc81cc -[UIImageAsset _withLock_imageWithConfiguration:] + 408
17 UIKitCore                      0xc7ffc -[UIImageAsset imageWithConfiguration:] + 56
18 UIKitCore                      0x6d23c -[UIImage imageWithConfiguration:] + 552
19 UIKitCore                      0x38dac -[UIButton _imageForState:applyingConfiguration:usesImageForNormalState:] + 224
20 UIKitCore                      0x170138 -[UIButtonLegacyVisualProvider _deriveTitleRect:imageRect:fromContentRect:calculatePositionForEmptyTitle:] + 252
21 UIKitCore                      0x170028 -[UIButtonLegacyVisualProvider imageRectForContentRect:] + 48
22 UIKitCore                      0x16ffc0 -[UIButton imageRectForContentRect:] + 72
23 UIKitCore                      0x3a8e8 -[UIButton pressFeedbackPosition] + 68
24 UIKitCore                      0x383f8 -[UIButtonLegacyVisualProvider layoutSubviews] + 172
25 UIKitCore                      0x3830c -[UIButton layoutSubviews] + 40
26 UIKitCore                      0x5020 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1980
27 QuartzCore                     0x99ec CA::Layer::layout_if_needed(CA::Transaction*) + 500
28 UIKitCore                      0xd21dc -[UIView(Hierarchy) layoutBelowIfNeeded] + 292
29 UIKitCore                      0x2755ec -[_UINavigationBarTransitionContextPop _prepareContentView] + 192
30 UIKitCore                      0x2622f4 -[_UINavigationBarTransitionContextPop prepare] + 136
31 UIKitCore                      0xfd8b8 -[_UINavigationBarVisualProviderModernIOS _performAnimationWithTransitionCompletion:transition:] + 1604
32 UIKitCore                      0x366cfc -[UINavigationBar _popNavigationItemWithTransitionAssistant:] + 216
33 UIKitCore                      0x366b94 -[UINavigationBar _popNavigationItemWithTransition:] + 224
34 UIKitCore                      0x366958 ___popViewControllerNormal_block_invoke + 332
35 UIKitCore                      0x787bb4 ___popViewControllerNormal_block_invoke_4 + 88
36 UIKitCore                      0x104874 __98-[UINavigationController _shouldSkipHostedRefreshControlUpdateSchedulingDeferredUpdateIfNecessary]_block_invoke + 40
37 UIKitCore                      0x1a70c4 -[UINavigationController _startDeferredTransitionIfNeeded:] + 880
38 UIKitCore                      0x1a6604 -[UINavigationController __viewWillLayoutSubviews] + 96
39 UIKitCore                      0x1a6568 -[UILayoutContainerView layoutSubviews] + 172
40 UIKitCore                      0x5020 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1980
41 QuartzCore                     0x99ec CA::Layer::layout_if_needed(CA::Transaction*) + 500
42 QuartzCore                     0x1d0a0 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 148
43 QuartzCore                     0x2e5b0 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 456
44 QuartzCore                     0x635ec CA::Transaction::commit() + 652
45 QuartzCore                     0x4c8cc CA::Transaction::flush_as_runloop_observer(bool) + 88
46 UIKitCore                      0x504b44 _UIApplicationFlushCATransaction + 52
47 UIKitCore                      0x652740 _UIUpdateSequenceRun + 84
48 UIKitCore                      0xc99fd0 schedulerStepScheduledMainSection + 172
49 UIKitCore                      0xc9919c runloopSourceCallback + 92
50 CoreFoundation                 0xd5f54 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
51 CoreFoundation                 0xe232c __CFRunLoopDoSource0 + 176
52 CoreFoundation                 0x66210 __CFRunLoopDoSources0 + 244
53 CoreFoundation                 0x7bba8 __CFRunLoopRun + 836
54 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
55 GraphicsServices               0x1368 GSEventRunModal + 164
56 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
57 UIKitCore                      0x3a2034 UIApplicationMain + 340
58 libswiftUIKit.dylib            0x35308 UIApplicationMain(_:_:_:_:) + 104
59 App                            0xb814 main + 4302059540 (HeaderNotificationsSectionController.swift:4302059540)
60 ???                            0x1d49e4960 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  Foundation                     0x42334 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x4221c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4d733c -[UIEventFetcher threadMain] + 436
10 Foundation                     0x5b808 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16cc _pthread_start + 148
12 libsystem_pthread.dylib        0xba4 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  App                          0x6364e0 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  App                          0x6368c0 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  App                          0x64434c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  App                          0x644b48 FIRCLSMachExceptionServer + 521 (FIRCLSMachException.c:521)
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

ComScore-Thread
0  libsystem_kernel.dylib         0x1680 __ulock_wait + 8
1  libdispatch.dylib              0x49cc _dlock_wait + 56
2  libdispatch.dylib              0x4780 _dispatch_thread_event_wait_slow + 56
3  libdispatch.dylib              0x13860 __DISPATCH_WAIT_FOR_QUEUE__ + 368
4  libdispatch.dylib              0x1340c _dispatch_sync_f_slow + 144
5  ComScore                       0xa6510 +[SCORHelper appWindowResolution] + 228
6  ComScore                       0x5a94 ComScore::EventManager::addPlatformLabels(ComScore::Event*) + 56
7  ComScore                       0x1a878 ComScore::EventManager::addLabels(ComScore::Event*, long long, ComScore::EventInfo const&, std::__1::shared_ptr<ComScore::Configuration>) + 1312
8  ComScore                       0x18f94 ComScore::EventManager::send(ComScore::Event*, long long, ComScore::EventInfo const&, std::__1::shared_ptr<ComScore::Configuration>) + 708
9  ComScore                       0x18b94 ComScore::EventManager::sendViewEvent(long long, ComScore::EventInfo const&, std::__1::shared_ptr<ComScore::Configuration>) + 136
10 ComScore                       0x54ab0 std::__1::__function::__func<ComScore::Core::sendViewEvent(ComScore::StringPairArray const&)::$_13, std::__1::allocator<ComScore::Core::sendViewEvent(ComScore::StringPairArray const&)::$_13>, void (ComScore::Task*, std::__1::shared_ptr<ComScore::Configuration>)>::operator()(ComScore::Task*&&, std::__1::shared_ptr<ComScore::Configuration>&&) + 172
11 ComScore                       0x569ec std::__1::__function::__func<ComScore::Core::newEventTask(std::__1::function<void (ComScore::Task*, std::__1::shared_ptr<ComScore::Configuration>)>)::$_28, std::__1::allocator<ComScore::Core::newEventTask(std::__1::function<void (ComScore::Task*, std::__1::shared_ptr<ComScore::Configuration>)>)::$_28>, void (ComScore::Task*)>::operator()(ComScore::Task*&&) + 448
12 ComScore                       0x13ec0 ComScore::Task::run() + 44
13 ComScore                       0x4ec90 ComScore::ContextTasksThread<ComScore::Core>::run() + 304
14 ComScore                       0x8ff84 ComScore::Thread::threadEntryPoint() + 104
15 ComScore                       0x945a0 threadEntryProc + 32
16 libsystem_pthread.dylib        0x16cc _pthread_start + 148
17 libsystem_pthread.dylib        0xba4 thread_start + 8

ComScore-NetworkThread
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8098 _pthread_cond_wait + 1276
2  ComScore                       0x8f6bc ComScore::WaitableEvent::wait(int) const + 152
3  ComScore                       0x4ec50 ComScore::ContextTasksThread<ComScore::Core>::run() + 240
4  ComScore                       0x8ff84 ComScore::Thread::threadEntryPoint() + 104
5  ComScore                       0x945a0 threadEntryProc + 32
6  libsystem_pthread.dylib        0x16cc _pthread_start + 148
7  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  CFNetwork                      0x2565a8 _CFURLStorageSessionDisableCache + 61088
8  Foundation                     0x5b808 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

WebThread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  WebCore                        0xbbcbe8 <redacted> + 756
8  libsystem_pthread.dylib        0x16cc _pthread_start + 148
9  libsystem_pthread.dylib        0xba4 thread_start + 8

GAIThread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7aaf0 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd34 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
7  Foundation                     0x42334 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x421c8 -[NSRunLoop(NSRunLoop) run] + 64
9  App                            0x8501d0 +[GAI threadMain:] + 4310729168
10 Foundation                     0x5b808 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16cc _pthread_start + 148
12 libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

LocalStorage
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0x4c784 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2032
3  WebKitLegacy                   0x2ca24 bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 248
4  WebKitLegacy                   0x30344 WebCore::StorageThread::threadEntryPoint() + 296
5  JavaScriptCore                 0x6ee5c WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
6  JavaScriptCore                 0x710e4 WTF::wtfThreadEntryPoint(void*) + 16
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_pthread.dylib        0xb90 start_wqthread + 254

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Crashed: com.google.fira.worker
0  libobjc.A.dylib                0x7798 objc_loadWeakRetained + 168
1  libobjc.A.dylib                0xacf4 objc_loadWeak + 24
2  Foundation                     0xa3c84 readARCWeakAt + 32
3  Foundation                     0x57da48 NSConcreteMapTable_reclaim + 172
4  Foundation                     0x10b60 -[NSConcreteMapTable grow] + 204
5  Foundation                     0x10928 -[NSConcreteMapTable setObject:forKey:] + 164
6  App                            0x41a8a8 +[GULNetworkURLSession setSessionInFetcherMap:forSessionID:] + 695 (GULNetworkURLSession.m:695)
7  App                            0x418e2c -[GULNetworkURLSession sessionIDFromAsyncGETRequest:completionHandler:] + 221 (GULNetworkURLSession.m:221)
8  App                            0x4177b8 -[GULNetwork getURL:headers:queue:usingBackgroundSession:completionHandler:] + 222 (GULNetwork.m:222)
9  App                            0x7df170 -[APMMeasurement fetchRemoteConfig] + 4310266224
10 App                            0x7d8ed0 -[APMMeasurement uploadData] + 4310240976
11 App                            0x7d7d10 __32-[APMMeasurement updateSchedule]_block_invoke_2 + 4310236432
12 App                            0x82d090 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4310585488
13 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
15 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
16 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
17 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
18 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
19 libsystem_pthread.dylib        0xb98 start_wqthread + 8

GULMutableDictionary
0  libsystem_kernel.dylib         0x1704 __ulock_wake + 8
1  libsystem_platform.dylib       0xfc0 _os_unfair_lock_unlock_slow + 56
2  App                            0x69ddbc -[GULObjectSwizzler dealloc] + 207 (GULObjectSwizzler.m:207)
3  libobjc.A.dylib                0x310b0 _object_remove_associations + 612
4  libobjc.A.dylib                0x62a8 objc_destructInstance + 96
5  libobjc.A.dylib                0xf994 _objc_rootDealloc + 80
6  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
8  libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
9  libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
10 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
11 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0xb90 start_wqthread + 254

APMExperimentWorkerQueue
0  libsystem_kernel.dylib         0x1680 __ulock_wait + 8
1  libsystem_platform.dylib       0x82c _os_unfair_lock_lock_slow + 172
2  libobjc.A.dylib                0x79b4 lookUpImpOrForward + 156
3  libobjc.A.dylib                0x20c4 _objc_msgSend_uncached + 68
4  App                            0x80c014 -[APMPBExperimentResponse initWithBuffer:] + 4310450196
5  App                            0x7bd3a4 -[APMETaskManager handleFetchingExperimentsResponse:data:error:] + 4310127524
6  App                            0x7bd274 __35-[APMETaskManager fetchExperiments]_block_invoke + 4310127220
7  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
8  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
9  libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
10 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
11 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
12 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
13 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.apple.CFNetwork.Connection
0  libsystem_kernel.dylib         0x1680 __ulock_wait + 8
1  libsystem_platform.dylib       0x82c _os_unfair_lock_lock_slow + 172
2  libobjc.A.dylib                0x2520 objc_object::sidetable_clearDeallocating() + 96
3  libobjc.A.dylib                0x62e4 objc_destructInstance + 156
4  libsystem_blocks.dylib         0x1d64 _Block_release + 268
5  Network                        0x7b3f90 nw_activity_activate + 212
6  Network                        0xa16484 nw_connection_start_activity + 88
7  CFNetwork                      0x18f3c CFURLRequestSetShouldPipelineHTTP + 1752
8  CFNetwork                      0x1a668c _CFNetworkErrorGetLocalizedDescription + 567264
9  CFNetwork                      0x182e98 _CFNetworkErrorGetLocalizedDescription + 421868
10 CFNetwork                      0x168db8 _CFNetworkErrorGetLocalizedDescription + 315148
11 CFNetwork                      0x250ffc _CFURLStorageSessionDisableCache + 39156
12 CFNetwork                      0x37738 CFURLRequestSetShouldStartSynchronously + 5848
13 CFNetwork                      0x4fd0c CFHTTPMessageCopyRequestURL + 6652
14 CFNetwork                      0xdd30 CFURLCacheSetMemoryCapacity + 544
15 CFNetwork                      0x13ff4 CFURLRequestSetHTTPHeaderFieldValue + 784
16 CFNetwork                      0x100934 CFURLDownloadCancel + 81072
17 CFNetwork                      0x16d608 _CFNetworkErrorGetLocalizedDescription + 333660
18 CFNetwork                      0x92da4 _CFHTTPMessageSetResponseProxyURL + 27920
19 CFNetwork                      0x1f0488 _CFNetworkHTTPConnectionCacheGetLimit + 123688
20 CFNetwork                      0x16d208 _CFNetworkErrorGetLocalizedDescription + 332636
21 CFNetwork                      0xa568 CFURLCacheSetDiskCapacity + 6028
22 libdispatch.dylib              0x13114 _dispatch_block_async_invoke2 + 148
23 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
24 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
25 libdispatch.dylib              0xc214 _dispatch_lane_invoke + 436
26 libdispatch.dylib              0xd4f8 _dispatch_workloop_invoke + 1780
27 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
28 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
29 libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1680 __ulock_wait + 8
1  libdispatch.dylib              0x49cc _dlock_wait + 56
2  libdispatch.dylib              0x46c8 _dispatch_wait_on_address + 140
3  libdispatch.dylib              0x4d7c _dispatch_group_wait_slow + 56
4  OneSignalCore                  0x88d0 __69-[OneSignalClient executeSimultaneousRequests:withSuccess:onFailure:]_block_invoke + 588
5  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
7  libdispatch.dylib              0x70c8 _dispatch_queue_override_invoke + 788
8  libdispatch.dylib              0x15a6c _dispatch_root_queue_drain + 396
9  libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
10 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
11 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

APMDefaultIdentitySupport
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  libdispatch.dylib              0x1f364 _dispatch_mach_send_and_wait_for_reply + 540
5  libdispatch.dylib              0x1f6ec dispatch_mach_send_with_result_and_wait_for_reply + 60
6  libxpc.dylib                   0x102e4 xpc_connection_send_message_with_reply_sync + 240
7  Foundation                     0xa3344 __NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__ + 16
8  Foundation                     0x3646c -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 2236
9  CoreFoundation                 0x1fd60 ___forwarding___ + 1016
10 CoreFoundation                 0x88350 _CF_forwarding_prep_0 + 96
11 CoreServices                   0x84b14 __56-[LSApplicationWorkspace deviceIdentifierForAdvertising]_block_invoke + 264
12 CoreServices                   0x49f4c _LSRetryForConnectionInterrupted + 56
13 CoreServices                   0x849a4 -[LSApplicationWorkspace deviceIdentifierForAdvertising] + 160
14 AdSupport                      0x1958 -[ASIdentifierManager advertisingIdentifier] + 156
15 App                            0x78fc90 -[APMPlatformIdentitySupport resettableDeviceID] + 4309941392
16 App                            0x7b4330 __47-[APMDefaultIdentitySupport resettableDeviceID]_block_invoke + 4310090544
17 libdispatch.dylib              0x13114 _dispatch_block_async_invoke2 + 148
18 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
19 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
20 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
21 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
22 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
23 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1050 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x141c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0xf63ec scavenger_thread_main + 1364
3  libsystem_pthread.dylib        0x16cc _pthread_start + 148
4  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.coremedia.rootQueue.47
0  libsystem_kernel.dylib         0xadc semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x45f4 _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x4bf4 _dispatch_semaphore_wait_slow + 76
3  libdispatch.dylib              0x15840 _dispatch_worker_thread + 324
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.coremedia.rootQueue.47
0  libsystem_kernel.dylib         0xadc semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x45f4 _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x4bf4 _dispatch_semaphore_wait_slow + 76
3  libdispatch.dylib              0x15840 _dispatch_worker_thread + 324
4  libsystem_pthread.dylib        0x16cc _pthread_start + 148
5  libsystem_pthread.dylib        0xba4 thread_start + 8
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by iudovenko** [comment] 2023-10-23 07:48
Same crash happened. Users on iOS 15-17. Happens after starting or expanding

**Comment by Brooksie18** [comment] 2023-10-23 07:53
Yes it does crash. Siri is also having problems.
 I will use pull repository for that. Thanks you guys for the hard work.

**Comment by vince4** [comment] 2024-03-18 08:53
We have a similar crash report in our app. Users affected are on iOS 15-17. 
It's not an early crash for us. 

### Firebase SDK Version
10.21.0 (but was also present on 9.6.0)

### Xcode Version
15.2

### Installation Method
Swift Package Manager

### Firebase Product(s)
FirebaseAnalyticsWithoutAdldSupport
FirebaseCrashlytics
FirebaseDynamicLinks
FirebaselnAppMessagingSwift-Beta
FirebasePerformance
FirebaseRemoteConfig
FirebaseRemoteConfiaSwift

### Targeted Platforms
iOS, iPadOS

**Comment by kgaidis** [comment] 2024-08-23 14:43
same here!

**Comment by MichaelVerdon** [comment] 2024-11-22 10:36
I am closing this issue as I have been unable to reproduce the issue and it has been floating around for some time. Please feel free to reopen this ticket if you are experiencing this on the newest version of Firebase.

**Closed by MichaelVerdon** 2024-11-22 10:36 UTC
Labels: api: analytics, api: performance, GoogleUtilities
