### ISSUE TITLE
Firebase A/B testing does not show correct user counts

### ISSUE THREAD

**Issue by phuc-nguyen4-tiki** [firebase/firebase-ios-sdk#4664] opened 2020-01-13 04:16 UTC
* Xcode version: 10.3
  * Firebase SDK version: 6.14.0
  * Firebase Component: Remote Config
  * Component version: 4.4.6

### [REQUIRED] Describe the problem

- When we run A/B testing for a specific remote config key with 50% for control group and 50% for test group.
![image](https://user-images.githubusercontent.com/53720418/72232747-a897c600-35f5-11ea-83cf-5c3e4ba1e773.png)

- But it usually show wrong number of users in both groups (is not equal to the percentage):
![image](https://user-images.githubusercontent.com/53720418/72232779-ec8acb00-35f5-11ea-8593-27c7259dabee.png)

#### Steps to reproduce:

Run the A/B test for a remote config key. Set control group and test group to 50%.
Wait for several days, see result that not equal.

**Comment by christibbs** [comment] 2020-02-12 19:31
Thanks for the report. We are aware of this issue and working on it.

**Comment by zporges** [comment] 2020-02-13 18:53
I'm experiencing a similar (but not identical) issue.

I also have an experiment in my app that I configured to have 50% of users set to be in the control group, and 50% in an experimental group. In the firebase console A/B testing page, it looks about correct - it says the groups are currently about 47% vs 53%.

But in my app, I take the result of what remoteConfig gives us and add it to a user property, and it is not evenly distributed. We're seeing about 27% of users in our control group, and 73% of users in our experimental group.

Anecdotally (talking to about 20 users), it seems like about 75% of users are being placed in our experimental group as well.

**Comment by phuc-nguyen4-tiki** [comment] 2020-02-16 08:59
@christibbs Thanks a lot, we are depending on Firebase A/B testing. Hope your team can fix asap.

**Comment by zporges** [comment] 2020-03-02 23:39
@christibbs, any update on this? It's been very disruptive for us.

**Comment by christibbs** [comment] 2020-03-16 21:15
Update on this: sorry for the delay.

The bug is actually in the web console (in aggregating the user count totals). This is being worked on. From what I'm told, you should be able to see accurate data when [fetching analytics data from BigQuery](https://firebase.google.com/docs/ab-testing/abtest-config#bigquery_data_export). But in production, the correct amount of users are being assigned.

I'll update this issue and close it when the console-side aggregation bug is fixed.

**Comment by zporges** [comment] 2020-03-16 21:55
I actually figured out my issue - I had configured an experiment to go to 50% of users, and I split those users into an experimental group and a control group. But the other 50% of users had the default value of being in the experimental group, which caused us to have a 75/25 split overall. Sorry about that!

**Comment by christibbs** [comment] 2020-03-16 22:15
@zporges OK, great. Will keep this open for @phuc-nguyen4-tiki's issue.

**Comment by phuc-nguyen4-tiki** [comment] 2020-03-17 00:58
@christibbs Great, Hope your team can help us.

**Comment by alectogeek** [comment] 2020-03-19 10:29
I faced the same issue. For a few days, everything went well, but then users counter froze on approximately 850 users. Any updates?

**Comment by ntemposd** [comment] 2020-08-19 10:01
I have a similar issue. I've configured my A/B test and the audience size was let's say, 100 users. However, the experiment is running for two days now and I get 0 users exposed. 😕

**Comment by Bej-Technologies** [comment] 2021-07-05 11:08
@ntemposd any updates on this? We are seeing the exact same issue. Our remote config works but in the AB-testing tab, we see no results even when testing on our own devices by uninstalling and installing the app multiple times.

**Comment by ntemposd** [comment] 2021-07-05 14:39
@Bej-Technologies it's been a long time since I'm not using Firebase, but if I recall well this was a misconfiguration issue on my side. I'm not sure though.

**Comment by paulb777** [comment] 2021-08-11 21:16
I'm going to close this issue for staleness. If the issue is still occurring with Firebase 8.x, please create a new issue with details and link to this one.

**Closed by paulb777** 2021-08-11 21:16 UTC
Labels: api: abtesting
