### ISSUE TITLE
Crash vector line 1518 firebase::firestore::util::ComparisonResult 

### ISSUE THREAD

**Issue by skaldic** [firebase/firebase-ios-sdk#6842] opened 2020-10-27 09:55 UTC
### Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.34
  * Installation method: `CocoaPods`
  * Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)

###  Step 2: Describe the problem
We have an issue with 9 crashes affecting 8 users. All are 100% in the background.

#### Steps to reproduce:
I have no steps only the crashlytics reports.

```
vector line 1518
firebase::firestore::util::ComparisonResult firebase::firestore::util::CompareContainer<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)
```

```
Crashed: com.google.firebase.firestore
0  MyApp                      0x1010e99b0 firebase::firestore::util::ComparisonResult firebase::firestore::util::CompareContainer<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) + 1518 (vector:1518)
1  MyApp                      0x1011652fc firebase::firestore::util::Empty std::__1::__lower_bound<firebase::firestore::immutable::impl::ArraySortedMap<firebase::firestore::model::DocumentKey, firebase::firestore::util::Empty, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> >::lower_bound(firebase::firestore::model::DocumentKey const&) const::'lambda'(std::__1::pair<firebase::firestore::model::DocumentKey, firebase::firestore::util::Empty> const&, firebase::firestore::model::DocumentKey const&)&, std::__1::pair<firebase::firestore::model::DocumentKey, firebase::firestore::util::Empty> const*, firebase::firestore::model::DocumentKey>(firebase::firestore::util::Empty, firebase::firestore::util::Empty, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> const&, firebase::firestore::model::DocumentKey) + 4184 (algorithm:4184)
2  MyApp                      0x1011641e0 firebase::firestore::immutable::impl::ArraySortedMap<firebase::firestore::model::DocumentKey, firebase::firestore::util::Empty, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> >::insert(firebase::firestore::model::DocumentKey const&, firebase::firestore::util::Empty const&) const + 179 (array_sorted_map.h:179)
3  MyApp                      0x101163cd4 firebase::firestore::immutable::SortedMap<firebase::firestore::model::DocumentKey, firebase::firestore::util::Empty, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> >::insert(firebase::firestore::model::DocumentKey const&, firebase::firestore::util::Empty const&) const + 371 (sorted_map.h:371)
4  MyApp                      0x10116ae54 firebase::firestore::immutable::SortedSet<firebase::firestore::model::DocumentKey, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> >::insert(firebase::firestore::model::DocumentKey const&) const + 87 (sorted_map.h:87)
5  MyApp                      0x101174c8c firebase::firestore::local::LocalDocumentsView::GetLocalViewOfDocuments(firebase::firestore::immutable::SortedMap<firebase::firestore::model::DocumentKey, absl::lts_2020_02_25::optional<firebase::firestore::model::MaybeDocument>, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> > const&) + 46 (model_fwd.h:46)
6  MyApp                      0x10117d504 std::__1::__function::__func<std::__1::enable_if<!(std::is_same<void, decltype(fp0())>::value), decltype(fp0())>::type firebase::firestore::local::Persistence::Run<firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7>(absl::lts_2020_02_25::string_view, firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7)::'lambda'(), std::__1::allocator<std::__1::enable_if<!(std::is_same<void, decltype(fp0())>::value), decltype(fp0())>::type firebase::firestore::local::Persistence::Run<firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7>(absl::lts_2020_02_25::string_view, firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7)::'lambda'()>, void ()>::operator()() + 4309538052
7  MyApp                      0x1011689e0 firebase::firestore::local::LevelDbPersistence::RunInternal(absl::lts_2020_02_25::string_view, std::__1::function<void ()>) + 2620 (memory:2620)
8  MyApp                      0x101179970 firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&) + 4309522800
9  MyApp                      0x1011c3038 firebase::firestore::core::SyncEngine::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&) + 4309823544
10 MyApp                      0x1011ae570 firebase::firestore::remote::RemoteStore::RaiseWatchSnapshot(firebase::firestore::model::SnapshotVersion const&) + 46 (model_fwd.h:46)
11 MyApp                      0x1011e0b70 firebase::firestore::remote::WatchStream::NotifyStreamResponse(grpc::ByteBuffer const&) + 2147 (memory:2147)
12 MyApp                      0x1011bc780 firebase::firestore::remote::Stream::OnStreamRead(grpc::ByteBuffer const&) + 2636 (memory:2636)
13 MyApp                      0x101149c70 std::__1::__function::__func<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0, std::__1::allocator<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0>, void ()>::operator()() + 1707 (functional:1707)
14 MyApp                      0x1010e8228 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 957 (atomic:957)
15 MyApp                      0x1011cb194 firebase::firestore::util::Task::ExecuteAndRelease() + 1846 (functional:1846)
16 libdispatch.dylib              0x18f81f524 _dispatch_client_callout + 16
17 libdispatch.dylib              0x18f7cb8a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
18 libdispatch.dylib              0x18f7cc294 _dispatch_lane_invoke$VARIANT$mp + 416
19 libdispatch.dylib              0x18f7d578c _dispatch_workloop_worker_thread + 588
20 libsystem_pthread.dylib        0x18f870b74 _pthread_wqthread + 272
21 libsystem_pthread.dylib        0x18f873740 start_wqthread + 8
```

```
com.apple.main-thread
0  libsystem_kernel.dylib         0x18f92d1d4 semaphore_wait_trap + 8
1  libdispatch.dylib              0x18f7c5c90 _dispatch_sema4_wait$VARIANT$mp + 24
2  libdispatch.dylib              0x18f7c62e8 _dispatch_semaphore_wait_slow + 140
3  CoreAnalytics                  0x194b06eb0 CoreAnalytics::Client::barrierSync() + 160
4  libsystem_c.dylib              0x18f79b7c8 __cxa_finalize_ranges + 400
5  libsystem_c.dylib              0x18f79bac8 exit + 24
6  UIKitCore                      0x193c12aa8 -[UIApplication terminateWithSuccess] + 502
7  UIKitCore                      0x1933b00d0 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 124
8  UIKitCore                      0x1933afd58 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 216
9  UIKitCore                      0x193c08b44 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
10 FrontBoardServices             0x194cd98a0 -[FBSUIApplicationWorkspaceShim workspaceShouldExit:withTransitionContext:] + 84
11 FrontBoardServices             0x194d049bc __83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_invoke_2 + 76
12 FrontBoardServices             0x194ceabfc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
13 FrontBoardServices             0x194d0494c __83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_invoke + 124
14 libdispatch.dylib              0x18f81f524 _dispatch_client_callout + 16
15 libdispatch.dylib              0x18f7c8434 _dispatch_block_invoke_direct$VARIANT$mp + 224
16 FrontBoardServices             0x194d29850 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
17 FrontBoardServices             0x194d2951c -[FBSSerialQueue _queue_performNextIfPossible] + 404
18 FrontBoardServices             0x194d29a44 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
19 CoreFoundation                 0x18fad7ad8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
20 CoreFoundation                 0x18fad7a30 __CFRunLoopDoSource0 + 80
21 CoreFoundation                 0x18fad7214 __CFRunLoopDoSources0 + 276
22 CoreFoundation                 0x18fad21e8 __CFRunLoopRun + 788
23 CoreFoundation                 0x18fad1ba8 CFRunLoopRunSpecific + 424
24 GraphicsServices               0x199c48344 GSEventRunModal + 160
25 UIKitCore                      0x193c0d3e4 UIApplicationMain + 1932
26 MyApp                      0x100c68984 main + 30 (CompanyLimits.swift:30)
27 libdyld.dylib                  0x18f9598f0 start + 4
```

```
com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x18f92d198 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f92c60c mach_msg + 72
2  CoreFoundation                 0x18fad7328 __CFRunLoopServiceMachPort + 148
3  CoreFoundation                 0x18fad235c __CFRunLoopRun + 1160
4  CoreFoundation                 0x18fad1ba8 CFRunLoopRunSpecific + 424
5  Foundation                     0x18fe2301c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
6  Foundation                     0x18fe22efc -[NSRunLoop(NSRunLoop) runUntilDate:] + 88
7  UIKitCore                      0x193cb057c -[UIEventFetcher threadMain] + 152
8  Foundation                     0x18ff51e20 __NSThread__start__ + 848
9  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
10 libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
com.google.firebase.crashlytics.MachExceptionServer
0  MyApp                      0x10105b23c FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
1  MyApp                      0x10105b620 FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
2  MyApp                      0x101051b6c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  MyApp                      0x1010545a4 FIRCLSMachExceptionServer + 524 (FIRCLSMachException.c:524)
4  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
5  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x18f92d198 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f92c60c mach_msg + 72
2  CoreFoundation                 0x18fad7328 __CFRunLoopServiceMachPort + 148
3  CoreFoundation                 0x18fad235c __CFRunLoopRun + 1160
4  CoreFoundation                 0x18fad1ba8 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x192d9f5d0 (Missing)
6  Foundation                     0x18ff51e20 __NSThread__start__ + 848
7  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
8  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
Thread
0  libsystem_kernel.dylib         0x18f94eb58 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x18f868ce4 _pthread_cond_wait$VARIANT$mp + 680
2  grpc                           0x1054583ac gpr_cv_wait + 149 (sync_posix.cc:149)
3  grpc                           0x1053ef9f8 grpc_core::Executor::ThreadMain(void*) + 231 (executor.cc:231)
4  grpc                           0x105462264 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 141 (thd_posix.cc:141)
5  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
6  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
Thread
0  libsystem_kernel.dylib         0x18f94eb58 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x18f868ce4 _pthread_cond_wait$VARIANT$mp + 680
2  grpc                           0x1054583ac gpr_cv_wait + 149 (sync_posix.cc:149)
3  grpc                           0x1053ef9f8 grpc_core::Executor::ThreadMain(void*) + 231 (executor.cc:231)
4  grpc                           0x105462264 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 141 (thd_posix.cc:141)
5  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
6  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
Thread
0  libsystem_kernel.dylib         0x18f94eb58 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x18f868ce4 _pthread_cond_wait$VARIANT$mp + 680
2  grpc                           0x10545839c gpr_cv_wait + 146 (sync_posix.cc:146)
3  grpc                           0x105465908 timer_thread(void*) + 84 (trace.h:84)
4  grpc                           0x105462264 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 141 (thd_posix.cc:141)
5  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
6  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
com.google.firebase.firestore.rpc
0  libsystem_kernel.dylib         0x18f951010 poll + 8
1  grpc                           0x1053ebe84 pollset_work(grpc_pollset*, grpc_pollset_worker**, long long) + 2928
2  grpc                           0x1053ede04 pollset_work(grpc_pollset*, grpc_pollset_worker**, long long) + 324 (ev_posix.cc:324)
3  grpc                           0x1053dfc1c cq_next(grpc_completion_queue*, gpr_timespec, void*) + 1059 (completion_queue.cc:1059)
4  grpcpp                         0x10558e268 grpc_impl::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) + 55 (completion_queue_cc.cc:55)
5  MyApp                      0x1010edc4c firebase::firestore::remote::Datastore::PollGrpcQueue() + 4308950092
6  MyApp                      0x1011cb194 firebase::firestore::util::Task::ExecuteAndRelease() + 1846 (functional:1846)
7  libdispatch.dylib              0x18f81f524 _dispatch_client_callout + 16
8  libdispatch.dylib              0x18f7cb8a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
9  libdispatch.dylib              0x18f7cc294 _dispatch_lane_invoke$VARIANT$mp + 416
10 libdispatch.dylib              0x18f7d578c _dispatch_workloop_worker_thread + 588
11 libsystem_pthread.dylib        0x18f870b74 _pthread_wqthread + 272
12 libsystem_pthread.dylib        0x18f873740 start_wqthread + 8
```

```
com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x18f92d198 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f92c60c mach_msg + 72
2  CoreFoundation                 0x18fad7328 __CFRunLoopServiceMachPort + 148
3  CoreFoundation                 0x18fad235c __CFRunLoopRun + 1160
4  CoreFoundation                 0x18fad1ba8 CFRunLoopRunSpecific + 424
5  Foundation                     0x18fe2301c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
6  MyApp                      0x101330414 -[_FSRRunLoopThread main] + 1854 (FSRWebSocket.m:1854)
7  Foundation                     0x18ff51e20 __NSThread__start__ + 848
8  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
9  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x18f94f014 select$DARWIN_EXTSN + 8
1  libsystem_kernel.dylib         0x18f94f014 __select + 8
2  CoreFoundation                 0x18fae4ff4 __CFSocketManager + 624
3  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
4  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
Thread
0  libsystem_kernel.dylib         0x18f94eb58 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x18f868ce4 _pthread_cond_wait$VARIANT$mp + 680
2  grpc                           0x10545839c gpr_cv_wait + 146 (sync_posix.cc:146)
3  grpc                           0x105465908 timer_thread(void*) + 84 (trace.h:84)
4  grpc                           0x105462264 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 141 (thd_posix.cc:141)
5  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
6  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x18f92d198 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f92c60c mach_msg + 72
2  CoreFoundation                 0x18fad7328 __CFRunLoopServiceMachPort + 148
3  CoreFoundation                 0x18fad235c __CFRunLoopRun + 1160
4  CoreFoundation                 0x18fad1ba8 CFRunLoopRunSpecific + 424
5  CoreFoundation                 0x18fad2904 CFRunLoopRun + 60
6  CoreMotion                     0x19c7666f4 CLClientCreateIso6709Notation + 150064
7  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
8  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x18f92d198 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f92c60c mach_msg + 72
2  CoreFoundation                 0x18fad7328 __CFRunLoopServiceMachPort + 148
3  CoreFoundation                 0x18fad235c __CFRunLoopRun + 1160
4  CoreFoundation                 0x18fad1ba8 CFRunLoopRunSpecific + 424
5  AVFAudio                       0x19c8a8a2c GenericRunLoopThread::Entry(void*) + 156
6  AVFAudio                       0x19c8f97a0 CAPThread::Entry(CAPThread*) + 204
7  libsystem_pthread.dylib        0x18f86fd98 _pthread_start + 156
8  libsystem_pthread.dylib        0x18f87374c thread_start + 8
```

```
Thread
0  libsystem_pthread.dylib        0x18f873738 start_wqthread + 190
```

```
Thread
0  libsystem_pthread.dylib        0x18f873738 start_wqthread + 190
```

```
Thread
0  libsystem_pthread.dylib        0x18f873738 start_wqthread + 190
```

```
Thread
0  libsystem_kernel.dylib         0x18f94f940 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18f870bc0 _pthread_wqthread + 348
2  libsystem_pthread.dylib        0x18f873740 start_wqthread + 8
```

```
Thread
0  libsystem_pthread.dylib        0x18f873738 start_wqthread + 190
```

```
Thread
0  libsystem_kernel.dylib         0x18f94f940 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18f870bc0 _pthread_wqthread + 348
2  libsystem_pthread.dylib        0x18f873740 start_wqthread + 8
```

```
NSOperationQueue 0x12b2b34a0 (QOS: UNSPECIFIED)
0  libsystem_kernel.dylib         0x18f92d1ec semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x18f7c5d0c _dispatch_sema4_timedwait$VARIANT$mp + 64
2  libdispatch.dylib              0x18f7c62a4 _dispatch_semaphore_wait_slow + 72
3  Leanplum                       0x1023187e8 __32-[LeanplumRequest sendRequests:]_block_invoke + 362 (LeanplumRequest.m:362)
4  Foundation                     0x18ff2e3f0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
5  Foundation                     0x18fe39710 -[NSBlockOperation main] + 84
6  Foundation                     0x18ff3064c __NSOPERATION_IS_INVOKING_MAIN__ + 20
7  Foundation                     0x18fe39414 -[NSOperation start] + 740
8  Foundation                     0x18ff31044 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
9  Foundation                     0x18ff30b10 __NSOQSchedule_f + 180
10 libdispatch.dylib              0x18f7d1c8c _dispatch_block_async_invoke2 + 104
11 libdispatch.dylib              0x18f81f524 _dispatch_client_callout + 16
12 libdispatch.dylib              0x18f7c7e98 _dispatch_continuation_pop$VARIANT$mp + 412
13 libdispatch.dylib              0x18f7c75ec _dispatch_async_redirect_invoke + 656
14 libdispatch.dylib              0x18f7d4438 _dispatch_root_queue_drain + 376
15 libdispatch.dylib              0x18f7d4bf8 _dispatch_worker_thread2 + 124
16 libsystem_pthread.dylib        0x18f870b38 _pthread_wqthread + 212
17 libsystem_pthread.dylib        0x18f873740 start_wqthread + 8
```

```
Thread
0  libsystem_kernel.dylib         0x18f94f940 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18f870bc0 _pthread_wqthread + 348
2  libsystem_pthread.dylib        0x18f873740 start_wqthread + 8
```

Thank you!

**Comment by wilhuff** [comment] 2020-10-27 16:34
This is a duplicate of #6844: when the application is terminating, the Firestore worker can be at an arbitrary point in its execution.

**Closed by wilhuff** 2020-10-27 16:34 UTC
Labels: api: firestore
