### ISSUE TITLE
Signing warnings in XCode 10 GM

### ISSUE THREAD

**Issue by fbandemer** [firebase/firebase-ios-sdk#1846] opened 2018-09-19 18:17 UTC
Hello,
i get this warnings when using building my application with Xcode10 GM

- "Skipping code signing because the target does not have an Info.plist file. (in target 'FirebaseCore')"
- "Skipping code signing because the target does not have an Info.plist file. (in target 'FirebaseDatabase')"
- "Skipping code signing because the target does not have an Info.plist file. (in target 'FirebaseMessaging')"

I've read several post in other forums to this issue but there seems to be no solution or workaround.

#### Environment
  * Xcode version: Xcode 10 GM
  * Firebase SDK version: 5.8.0
  * Firebase Component: Core, Database, Analytics, Messaging
  * Component version: Core(5.1.3),Database(5.0.3), Analytics(5.1.2), Messaging(3.1.1)

#### Steps to reproduce:

1. Install Xcode 10 GM
2. Init cocoapods
3. Install firebase component via podfile
4. Build the application

**Comment by morganchen12** [comment] 2018-09-27 02:59
What versions of CocoaPods are you both using?

**Comment by alexeybolv** [comment] 2018-09-27 05:00
> What versions of CocoaPods are you both using?

I have 1.5.3 version.

**Comment by fbandemer** [comment] 2018-09-27 05:30
> What versions of CocoaPods are you both using?

I have version 1.5.3 too.

**Comment by paulb777** [comment] 2018-09-27 14:20
We might need a Podfile and/or sample project to investigate. I haven't been able to repro with my sample.

**Comment by alexeybolv** [comment] 2018-09-27 14:43
Here is my podfile


source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'MyProject' do

use_frameworks!

pod 'Moya', '~> 11.0.2'
pod 'SDWebImage', '~> 4.4.2'
pod 'Firebase/Core', '~> 5.9.0'
pod 'Firebase/Messaging'
pod 'CSV.swift', '~> 2.2.1'

end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
	if config.name == 'Release'
      		config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
    	else
      		config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
   	end   
    end
end

**Comment by paulb777** [comment] 2018-10-01 14:09
I'm still not able to reproduce. Are you able to make it happen in an example you can share - like one of the quickstarts? - https://github.com/firebase/quickstart-ios

**Comment by djradev** [comment] 2018-10-02 20:49
I also see the same issue after I executed $pod update (v. 1.5.3). 

There is a warning in the following targets: FirebaseCore, FirebaseAuth, FirebaseDatabase, FirebaseDynamicLinks, FirebaseMessaging, FirebaseFirestore, FirebaseStorage.

Interestingly there isn't similar warning for targets like GoogleUtilities, which is a dependency for one of the above targets, I believe.

**Comment by paulb777** [comment] 2018-10-02 21:50
It seems to be related to the pods that are static frameworks. Static frameworks should be linked into the app before code signing, so shouldn't be involved in any code signing scripts.

I'm still looking for an example.

**Comment by djradev** [comment] 2018-10-02 23:11
One more (potentially important) thing - I only see the warnings when I build for simulator, when I build for a device - no warnings

**Comment by paulb777** [comment] 2018-10-08 22:51
I've reproduced and I'm investigating.

**Comment by paulb777** [comment] 2018-10-08 23:34
A workaround is change to the old build system:

- Open Xcode
- Select File upper-left next to Apple icon
- Open Workspace Settings
- Change the build system to Legacy Build System

**Comment by Horoshaya** [comment] 2018-11-02 11:56
Is it the best we can do to resolve this issue?

**Comment by paulb777** [comment] 2018-11-19 18:50
The issue is now fixed on CocoaPods master from https://github.com/CocoaPods/CocoaPods/pull/8287 and is planned to be in whichever CocoaPods release follows 1.6.0.beta.2

**Closed by paulb777** 2018-11-19 18:50 UTC
Labels: Infrastructure

**Comment by AdamDeveloper97579** [comment] 2019-01-25 06:01
[FireBase worning.pdf](https://github.com/firebase/firebase-ios-sdk/files/2794808/FireBase.worning.pdf)

**Comment by AdamDeveloper97579** [comment] 2019-01-25 06:02
Вот решение этой проблемы 
[FireBase worning.pdf](https://github.com/firebase/firebase-ios-sdk/files/2794809/FireBase.worning.pdf)
[FireBase.worning.pdf](https://github.com/firebase/firebase-ios-sdk/files/2794810/FireBase.worning.pdf)

**Comment by riley-usagi** [comment] 2019-01-25 14:17
> [FireBase worning.pdf](https://github.com/firebase/firebase-ios-sdk/files/2794808/FireBase.worning.pdf)

Только - warning, а не worning =)

But thank you for answer.

**Comment by AdamDeveloper97579** [comment] 2019-01-28 11:34
Я выбираю основной Info.plist ! Помоему он начинается non.info.plist .... Если я правильно запомнил
