### ISSUE TITLE
Mac Catalyst build failed with latest sdk (10.22) 

### ISSUE THREAD

**Issue by ubtang** [firebase/firebase-ios-sdk#12474] opened 2024-03-05 22:15 UTC
### Description

 I have installed the latest SDK for iOS (10.22) with swift package manager. iOS build is successful, but wasn't able to make framework embedded and sign (no embedded and sign option on the entry). So I wasn't able to get Privacy report for firebase. But failed to build on Mac Catalyst frome same code base, with message "Undefined symbols" and "Linker command failed with exit code 1".

### Reproducing the issue

1. use Swift package manager to get latest sdk (10.22)
2. build with target Mac catalyst

### Firebase SDK Version

10.22

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS, macCatalyst

### Relevant Log Output

```shell
Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)
```

### If using Swift Package Manager, the project's Package.resolved

 {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "fe09d61a539e11fdbe24f269bba10144b6145fe2",
        "version" : "10.22.0"
      }
    }, 

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment] 2024-03-05 23:20
I was unable to reproduce the build failure. Could you please provide a minimal, reproducible example?

Steps I took to reproduce:
1. Create app
2. Add Firebase 10.22 via SPM
3. Add Analytics
4. Build for macCatalyst
5. Build was successful (no linker error)

**Comment by ubtang** [comment] 2024-03-05 23:45
Thank you for the reply. One more question, we used to manually add Analytics framework to our app (total 12 .xcframework file, including FirebaseAnalyticsSwift.xcframework.  Do you have the link to download 10.22 sdk with swift support? I can only find the download link "https://firebase.google.com/download/ios", which not have "FirebaseAnalyticsSwift.xcframework". Also, if I use manually add framework, how do I make firebase show in privacy report. Thanks

**Comment by ncooke3** [comment] 2024-03-06 00:43
`FirebaseAnalyticsSwift` is no longer needed. It is no longer included in the Firebase zip. All of the API that used to live in it is now accessible by importing `FirebaseAnalytics`

> Also, if I use manually add framework, how do I make firebase show in privacy report. 

When dragging the xcframework into Xcode, select `Embed & Sign`. If the SDK has a privacy manifest, it's privacy information will appear in the privacy report (also, some SDKs have privacy manifests but do not collect data so they don't appear in the privacy report).

**Comment by malikyantizhanov** [comment] 2024-03-06 12:38
> I was unable to reproduce the build failure. Could you please provide a minimal, reproducible example?
> 
> 
> 
> Steps I took to reproduce:
> 
> 1. Create app
> 
> 2. Add Firebase 10.22 via SPM
> 
> 3. Add Analytics
> 
> 4. Build for macCatalyst
> 
> 5. Build was successful (no linker error)
> 
> 
> 
> 

Xcode 15.3?

**Comment by ubtang** [comment] 2024-03-06 14:57
@ncooke3 Thank you for the reply.  I have switch to other apps, building seems fine for Mac Catalyst. Just one of the app, keeping has "Undefined symbol" error.

**Comment by ubtang** [comment] 2024-03-06 17:21
@ncooke3 just want to update, manually adding framewwork works for Mac Catalyst build. Thank you for all the help.

**Comment by ncooke3** [comment] 2024-03-06 17:23
> > I was unable to reproduce the build failure. Could you please provide a minimal, reproducible example?
> > Steps I took to reproduce:
> > 
> > 1. Create app
> > 2. Add Firebase 10.22 via SPM
> > 3. Add Analytics
> > 4. Build for macCatalyst
> > 5. Build was successful (no linker error)
> 
> Xcode 15.3?
> 
> I have the same error for iOS, when I try to archive my app and push it to App Store Connect.

@malikyantizhanov, this sounds like https://github.com/firebase/firebase-ios-sdk/issues/12441. If that doesn't appear to match your issue, please open a new one and I'll triage.

**Comment by ncooke3** [comment] 2024-03-06 17:23
@ubtang, great! I'll close this issue then.

**Closed by ncooke3** 2024-03-06 17:23 UTC
Labels: needs-attention
