### ISSUE TITLE
157240716: Question/FR: Firebase Dynamic Links "socialmeta.page.link"

### ISSUE THREAD

**Issue by krisanthony** [firebase/firebase-ios-sdk#5333] opened 2020-04-09 22:33 UTC
### Feature proposal

* Firebase Component: Firebase Dynamic Links

When sharing a firebase dynamic link to slack, "socialmeta.page.link" and the firebase logo is visible in the link preview. Is it possible to customize or remove this?
<img width="203" alt="image" src="https://user-images.githubusercontent.com/8468153/78946393-7290a380-7a77-11ea-95c3-473771804527.png">

Adding social meta params to link builder like so, then using the `shorten` to produce final url that is shared:
```
linkBuilder.socialMetaTagParameters = DynamicLinkSocialMetaTagParameters()
linkBuilder.socialMetaTagParameters?.title = title
linkBuilder.socialMetaTagParameters?.imageURL = imageUrl
```

**Comment by morganchen12** [comment] 2020-04-10 18:05
iirc it's supposed to display your app icon, though I'm not sure where this gets specified. @dmandar can you clarify?

I'll update the docs [here](https://firebase.google.com/docs/dynamic-links/link-previews) once we get an answer.

**Comment by dmandar** [comment] 2020-04-10 21:36
+ @maxzhouous

**Comment by krisanthony** [comment] 2020-04-17 17:59
@dmandar looks like you may have meant @maxzhouus ?

**Comment by emanuel-lundman** [comment] 2020-08-14 08:12
no updates on this?

**Comment by diegoveloper** [comment] 2020-09-02 19:28
Any news about this issue? :/

**Comment by eldhosembabu** [comment] 2020-09-08 18:12
Seems like a feature request. Will pass the internal bug (b/157240716)to product team to prioritize.

**Comment by eldhosembabu** [comment] 2020-09-08 18:22
Also could you please share a sample FDL link for us to check where you have used the social meta tag parameters

**Comment by joyt** [comment] 2020-09-23 03:52
@eldhosembabu Here's an example: https://par.tf/5wa4 (see below screenshot of the preview looks like on Slack) - note that there is **no iOS or Android app** to deep link into here, it's just used as a short link to a web page.

As you can see, the social meta tags with title, description, & image are set but **unfortunately also the Firebase logo and "socialmeta.page.link" text**. It would be great if there were a way to customize whatever meta tags are being auto-generated here.
![image](https://user-images.githubusercontent.com/2513424/93964757-7450d980-fd2e-11ea-9090-d981dc23c714.png)

**Comment by sadew145** [comment] 2020-10-02 05:06
@morganchen12 any follow up on this issue? Thanks

**Comment by campey** [comment] 2020-10-13 16:34
This also occurs from me when creating links from the firebase console. [https://console.firebase.google.com/project/[project-name]/durablelinks/links/]

Found this thread when looking up the issue, so thought to share to perhaps help in resolution.

**Comment by oggam** [comment] 2020-10-27 09:32
Same issue on my side, any updates?

**Comment by tallneil** [comment] 2020-11-09 19:07
+1

**Comment by vikjovanov** [comment] 2020-11-17 15:11
+1

**Comment by deepak786** [comment] 2020-11-30 08:22
I also have a similar issue. The issue is not only from the Firebase Android or iOS SDK. 
This issue is actually with all the Firebase dynamic links and Slack.

if you are having the domain from .page.link then it shows that domain but if you have a custom domain then it shows the socialmeta.page.link.

<img width="461" alt="Screen Shot 2020-11-30 at 1 50 10 PM" src="https://user-images.githubusercontent.com/14223997/100585177-26021d00-3313-11eb-8cb2-14fd4d1b322a.png">
<img width="378" alt="Screen Shot 2020-11-30 at 1 51 01 PM" src="https://user-images.githubusercontent.com/14223997/100585182-28647700-3313-11eb-820b-2254384b49b3.png">

**Comment by theochampion** [comment] 2021-01-22 11:38
Any updates on this ? Having the same issue ? (when link generated on Android as well)

**Comment by tomasz-ludek** [comment] 2021-02-15 12:13
Any update? (the same issue here, for the custom domain)

**Comment by VuDo98** [comment] 2021-02-15 13:31
Hi, I found out that this happens because whenever you put in socialMetaData, firebase will generate a new html for you which is why it is should a diff icon and url. If you wants to fix this, exclude socialMetadata when create your dynamic link and add the metadata tag or handle it via dynamic link sdk in your actual website

@deepak786 @theochampion @tomasz-ludek

**Comment by luanccp** [comment] 2021-08-02 09:15
Any news about how to update the icon?

**Comment by GlebMaltsev** [comment] 2021-08-18 09:27
Any ETA when this will be fixed?

**Comment by echo3Dco** [comment] 2021-10-12 19:27
Any update on the icon fix?

**Comment by paulb777** [comment] 2021-11-11 17:38
@eldhosembabu Would you take a look?

**Comment by d3xt3r2909** [comment] 2021-11-16 12:35
Same thing

**Comment by naudej** [comment] 2022-03-24 13:34
+1

**Comment by courtneypresto** [comment] 2022-03-25 21:37
Also following this -- same issue for me. Any update?

**Comment by izakharov** [comment] 2022-05-11 09:07
Any updates on `socialmeta.page.link` for custom domains? still getting it in 2022 🥹

**Comment by Tom3652** [comment] 2022-05-28 14:09
+1

**Comment by rizafran** [comment] 2022-06-07 17:47
Hey everyone, sorry for the late revert. We'd like to confirm if the issue is happening on Slack only?

**Comment by Tom3652** [comment] 2022-06-08 12:09
I have tried iMessage, Discord, Whatsapp and slack and it's happening on Slack only for these social networks.

**Comment by cavalos0086** [comment] 2022-08-04 23:18
Hello everyone 👋 

I looked into this and I believe the issue is on Slack side. Specifically Slack not respecting `<meta property="og:url"` as mentioned on the Ope Graph Protocol. I have followed up with Slack regarding this and they are looking into it. Will keep this chat updated it with any progress. 

Sorry for the inconvenience.

**Comment by spinapplications** [comment] 2022-10-13 23:03
I'm seeing this issue in Android's Messages app too, i.e. socialmeta.page.link replacing the domain name.

**Comment by cavalos0086** [comment] 2022-10-14 11:47
@spinapplications thanks for your input. Could you share an FDL link which could reproduce this issue? 

Thanks

**Comment by spinapplications** [comment] 2022-10-14 20:07
@cavalos0086 Thank you for looking into this.

Here is an example link: https://whenavailable.com/event/zFfVT2etsoXqoTuV6

And here is how it appears in the Messages app on my Android:
![Screenshot_20221014-160216](https://user-images.githubusercontent.com/1852416/195932790-d2a842b5-114d-43ca-ac90-104eaef644ad.png)

**Comment by spinapplications** [comment] 2022-10-21 19:19
@cavalos0086 any thoughts?

**Comment by cavalos0086** [comment] 2022-10-21 19:29
@spinapplications sorry for the late reply. I was able to reproduce the issue yesterday. I will take a look today and follow up with updates.

**Comment by cavalos0086** [comment] 2022-10-24 20:45
@spinapplications Have you notice if this has worked correctly in the pass?

**Comment by spinapplications** [comment] 2022-10-24 21:21
@cavalos0086  No, I have not seen this work in the past. 
When using the socialMetaTag object in building the dynamic link the message always shows socialmeta.page.link, instead of the domain.

**Comment by cavalos0086** [comment] 2022-11-01 05:57
@spinapplications After checking, the issue seems to be on the Messaging app. I have created a bug for it but no ETA on when it would be fixed. I will update this chat whenever I get any updates.

**Comment by spinapplications** [comment] 2022-11-01 15:29
@cavalos0086 Thanks for the update.

**Comment by michelleyin96** [comment] 2022-12-27 03:07
Any update here? @cavalos0086

**Comment by cavalos0086** [comment] 2022-12-27 20:31
@michelleyin96 Sorry no new updates on this. Both teams have been notified and there seems to be so misalignment on the response as I commented before. https://github.com/firebase/firebase-ios-sdk/issues/5333#issuecomment-1205868785

I will add any new updates here.

**Comment by aditya-arre** [comment] 2023-03-22 08:47
Any update on this issue?

**Comment by evgeny-myasishchev** [comment] 2023-04-09 21:27
This is still happening, any plans to fix it?

**Comment by nijilrajkr** [comment] 2023-05-05 05:26
Any update on this ??

**Comment by DamiFlutter** [comment] 2023-06-06 09:58
wow no fix yet I still get this issue where sometimes it displays and sometimes it does not

**Comment by paulb777** [comment] 2023-07-11 03:08
Now that [Firebase DynamicLinks is planned to shut down](https://firebase.google.com/support/dynamic-links-faq), closing its feature requests.

**Closed by paulb777** 2023-07-11 03:08 UTC
Labels: type: feature request, api: dynamiclinks
