### ISSUE TITLE
App crashes after adding GoogleTagManager to project which is using Firebase Analytics

### ISSUE THREAD

**Issue by nickinade** [firebase/firebase-ios-sdk#5070] opened 2020-03-11 07:44 UTC
## [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.3.2
  * Firebase Component: GoogleTagManager
  * Component version: 7.1.2
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

I have project using Firebase Analytics. I have added Google Tag manager pod. Then, after I add GTM container to the project it crashes at start.

> 2020-03-11 08:37:53.405384+0100 10min4beauty[4002:72827] GoogleTagManager info: Loading container: GTM-TJXGVQQ

> 2020-03-11 08:37:53.406936+0100 10min4beauty[4002:72857] GoogleTagManager info: Attempting to load container GTM-TJXGVQQ from network
> 2020-03-11 08:37:54.004787+0100 10min4beauty[4002:72819] GoogleTagManager info: Processing logged event: gtm.load with parameters: (null)
> 2020-03-11 08:37:54.008475+0100 10min4beauty[4002:72819] GoogleTagManager info: Processing logged event: _vs with parameters: {
    "_o" = auto;
    "_sc" = UIViewController;
    "_si" = "-6942184988013378461";
}
> 2020-03-11 08:37:54.023672+0100 10min4beauty[4002:72819] GoogleTagManager info: Sending universal analytics hit: {
    "&t" = screenview;
    "&tid" =     {
        collectAdid = 0;
        enableFirebaseEcommerce = 0;
        enableRecaptchaOption = 0;
        enableUaRlsa = 0;
        enableUseInternalVersion = 0;
        trackingId = "UA-148523509-1";
    };
}
> 2020-03-11 08:37:54.024196+0100 10min4beauty[4002:72819] GoogleTagManager info: Processing logged event: _vs with parameters: {
    "_o" = auto;
    "_sc" = UIAlertController;
    "_si" = "-8014389997127696758";
}
> 2020-03-11 08:37:54.027343+0100 10min4beauty[4002:72924] [error] fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
> 2020-03-11 08:37:54.027525+0100 10min4beauty[4002:72924] [error] CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: warning: Property 'parameters' on Entity 'GAIHit' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
> 2020-03-11 08:37:54.039587+0100 10min4beauty[4002:72924] -[__NSDictionaryM length]: unrecognized selector sent to instance 0x600000495ae0
> 2020-03-11 08:37:54.041398+0100 10min4beauty[4002:72819] GoogleTagManager info: Sending universal analytics hit: {
    "&t" = screenview;
    "&tid" =     {
        collectAdid = 0;
        enableFirebaseEcommerce = 0;
        enableRecaptchaOption = 0;
        enableUaRlsa = 0;
        enableUseInternalVersion = 0;
        trackingId = "UA-148523509-1";
    };
}
> 2020-03-11 08:37:54.060328+0100 10min4beauty[4002:72924] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM length]: unrecognized selector sent to instance 0x600000495ae0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   10min4beauty                        0x000000010cc2b61f -[GAIBatchingDispatcher queueDispatch:] + 385
	6   10min4beauty                        0x000000010cc2b484 -[GAIBatchingDispatcher queueModel:] + 125
	7   Foundation                          0x00007fff25781c30 __NSThreadPerformPerform + 259
	8   CoreFoundation                      0x00007fff23bd4471 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff23bd439c __CFRunLoopDoSource0 + 76
	10  CoreFoundation                      0x00007fff23bd3b74 __CFRunLoopDoSources0 + 180
	11  CoreFoundation                      0x00007fff23bce87f __CFRunLoopRun + 1263
	12  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	13  Foundation                          0x00007fff2576b86f -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 211
	14  Foundation                          0x00007fff2576ba87 -[NSRunLoop(NSRunLoop) run] + 76
	15  10min4beauty                        0x000000010cc18d59 +[GAI threadMain:] + 62
	16  Foundation                          0x00007fff257817a7 __NSThread__start__ + 1047
	17  libsystem_pthread.dylib             0x00007fff52466e65 _pthread_start + 148
	18  libsystem_pthread.dylib             0x00007fff5246283b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Steps to reproduce:**

1. Run the app
2. Crash

What am I missing? Looks like everything should work fine.
Thanks for help

**Comment by ryanwilson** [comment] 2020-03-11 14:01
Thanks for the report. I'm not sure if this will make a difference or not at the moment but can you please update to the latest Firebase SDKs and see if that helps? `6.19.0` was just released yesterday. If it's still causing issues we can take another look!

**Comment by paulb777** [comment] 2020-03-11 14:23
Also GoogleTagManager 7.1.3 has been recently released.

**Comment by nickinade** [comment] 2020-03-11 15:06
> Thanks for the report. I'm not sure if this will make a difference or not at the moment but can you please update to the latest Firebase SDKs and see if that helps? `6.19.0` was just released yesterday. If it's still causing issues we can take another look!
> Also GoogleTagManager 7.1.3 has been recently released.

I have updated Firebase SDKs to `6.19.0` and GoogleTagManager to `7.1.3`. Still same issue.

**Comment by morganchen12** [comment] 2020-03-11 17:52
This is a duplicate of #200. There aren't any Firebase symbols in the crashing stack trace, so please file feedback at the Google Analytics tracker instead: https://issuetracker.google.com/issues?q=componentid:187400

**Closed by morganchen12** 2020-03-11 17:52 UTC
Labels: api: tagmanager, needs-attention
