### ISSUE TITLE
166129177: Firebase Dynamic Link: AppScheme://google/link/?dismiss=1&is_weak_match=1 on iOS 13.5.1

### ISSUE THREAD

**Issue by jyotigroomefy** [firebase/firebase-ios-sdk#6316] opened 2020-08-21 06:43 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _11.1____
  * Firebase SDK version: __6.10.0___
  * Firebase Component: _DynamicLinks____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _4.0.8____
  * Installation method: `CocoaPods` (select one)

### [REQUIRED] Step 2: Describe the problem
I have created the dynamic link from firebase console. When i click dynamic link, it redirects to app store and installing app from Xcode, I am getting url "AppScheme://google/link/?dismiss=1&is_weak_match=1" in the below function, when app is not installed.
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool

This was working perfectly, i am facing this issue from yesterday.

#### Steps to reproduce:

1. Create a dynamic link send it through an sms to another iphone.
2. Click the link
3. The preview page link opens in safari, then it redirects to Appstore.
4. After installation app from AppStore, i am not getting Deeplink url. I am getting only "AppScheme://google/link/?dismiss=1&is_weak_match=1"

#### Relevant Code:
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        print("i have received through custom scheme..\(url.absoluteString)")
        if let dynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
            if let url = dynamicLink.url{
                self.getReferrerFromUniversalLink(linkUrl: url)
            }
            return true
        }
}

**Comment by eldhosembabu** [comment] 2020-08-24 18:26
@jyotigroomefy Glad you have figured out the issue. Will check with backend team and get you answers on API Key expirations soon

**Comment by eldhosembabu** [comment] 2020-09-01 18:11
The API key is not having any expirations as such. The key will get expired only if gets deleted or regenerated manually.

Let us know if you see otherwise.

Closing this bug since the issue is resolved.

**Closed by eldhosembabu** 2020-09-01 18:11 UTC
Labels: api: dynamiclinks
