### ISSUE TITLE
iOS 12+ "Failed to recreate database file" - Analytics Unable to Start

### ISSUE THREAD

**Issue by martinsmithdev** [firebase/firebase-ios-sdk#3760] opened 2019-09-03 13:33 UTC
Hi all,

I have an error where analytics fails to start on iOS 12 (stack trace below). The project has its own implementation of SQLite3.h and SQLite3.c. Any ideas how I can fix ?

[Firebase/Analytics][I-ACS034002] Failed to recreate database file. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=3 "Database operation "prepare statement" failed with sqlite code 0 and error message "not an error"" UserInfo={NSLocalizedDescription=Database operation "prepare statement" failed with sqlite code 0 and error message "not an error", APMMonitorContext=prepare statement,0,A,2}
2019-09-03 14:23:59.378351+0100 Emerge[40304:2567261] 6.7.0 - [Firebase/Analytics][I-ACS012001] Failed to open database (Init)
2019-09-03 14:23:59.379825+0100 Emerge[40304:2567261] 6.7.0 - [Firebase/Analytics][I-ACS034002] Failed to recreate database file. Error: Error Domain=com.google.gmp.measurement2019-09-03 14:23:59.384055+0100 Emerge[40304:2567261] 6.7.0 - [Firebase/Analytics][I-ACS012001] Failed to open database (Init)

**Comment by paulb777** [comment] 2019-09-03 14:03
Update the internal version of sqlite3. Duplicate of and more info at #3321

**Closed by paulb777** 2019-09-03 14:03 UTC
Labels: needs-triage

**Comment by ukmunnithan** [comment] 2019-10-07 01:52
Hello, 
I have the same issue.. 
Could you please help me.. 
@paulb777: how can we update internal version of sqlite 3...
