### ISSUE TITLE
FirebasePerformance crash: EXC_BAD_ACCESS (crashed) KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by pavel-zaletski** [firebase/firebase-ios-sdk#12969] opened 2024-05-15 14:56 UTC
### Description

Crash message:
**EXC_BAD_ACCESS (crashed)
KERN_INVALID_ADDRESS
Attempted to dereference garbage pointer 0x8.**

From time to time we observe crashes in our app. Unfortunately we can't reproduce it locally. We see them only in Embrace tool

![image](https://github.com/firebase/firebase-ios-sdk/assets/150328679/2bd610b1-1335-48ec-b622-933421a0e2c3)
![image](https://github.com/firebase/firebase-ios-sdk/assets/150328679/ac2a5dda-c0f5-44a7-9fa3-2d625730af09)

The issue is similar to the following:
https://github.com/firebase/firebase-ios-sdk/issues/11403
https://github.com/firebase/firebase-ios-sdk/issues/12457

Recently we updated Firebase SDK to 10.24.0. But it did not help.

### Reproducing the issue

Can't reproduce it locally. Crashes were observed in Embrace tool

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Messaging, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by pavel-zaletski** [comment] 2024-05-21 12:47
Hello! Do you have any updates on this?

**Comment by pavel-zaletski** [comment] 2024-06-05 07:51
Any updates here?

**Comment by pavel-zaletski** [comment] 2024-08-16 09:01
Any updates?

**Comment by ncooke3** [comment] 2024-08-16 16:05
Hi @pavel-zaletski, have you had any luck reproducing this locally since opening the issue? Apple's [Finding Zombies](https://help.apple.com/instruments/mac/current/#/dev612e6956) guide may be helpful when trying to reproduce as the toolshould surface which object is receiving messages after deallocation. Another application state to try and target is sending a request before backgrounding the app.

**Comment by pavel-zaletski** [comment] 2024-08-23 16:07
Hi @ncooke3, unfortunately I was not able to reproduce it locally. We see this crash only in the Embrace tool on some of our users' devices.
I will try to use XCode Instruments tool (Finding Zombies) as you suggested.
Thanks.

**Comment by MichaelVerdon** [comment] 2024-11-18 14:33
Hey there, I am closing this issue as this issue has been floating around for a bit and we have not been able to reproduce it locally. I would recommend upgrading to the latest Firebase version but please feel free to reopen this if you encounter these issues on the latest version and we can try investigate it again.

**Closed by MichaelVerdon** 2024-11-18 14:33 UTC
Labels: api: performance, needs-attention
