### ISSUE TITLE
FDL: Dynamic Link can't be received on first install in China Mobile

### ISSUE THREAD

**Issue by LinXunFeng** [firebase/firebase-ios-sdk#11101] opened 2023-04-11 07:16 UTC
### Description

I got a error dynamic link when i install and open app in China Mobile.

```shell
MyAppSchema://google/link/?dismiss=1&is_weak_match=1
```

It fails to get dynamic link because of network access permissions.

```shell
Task <736A956C-D00A-4F5E-92E0-4406EA0CBB69>.<1> finished with error [-1009] Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。" UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x10da7acc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (Denied over Wi-Fi interface), interface: en0[802.11], ipv4, dns, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <736A956C-D00A-4F5E-92E0-4406EA0CBB69>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
	"LocalDataTask <736A956C-D00A-4F5E-92E0-4406EA0CBB69>.<1>"
), NSLocalizedDescription=似乎已断开与互联网的连接。, NSErrorFailingURLStringKey=https://firebasedynamiclinks.googleapis.com/v1/installAttribution?key=xxx, NSErrorFailingURLKey=https://firebasedynamiclinks.googleapis.com/v1/installAttribution?key=xxx, _kCFStreamErrorDomainKey=1}
```

### Firebase SDK Version

10.1.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by LinXunFeng** [comment] 2023-04-12 01:52
@rizafran I tried both ways and confirmed the issue

## The first way
FDL works well in iPhone(Hong Kong), because the iPhone(Hong Kong) will not pop up the network access permission dialog which is unique to iPhone(China mainland)

<img width="205" alt="image" src="https://user-images.githubusercontent.com/19367531/231320391-8d6ab11c-527c-4497-869a-e25cec6b7c33.png">

## The second way
1. app is not installed
2. click the dynamic link
3. AppStore is opened
4. install app from Xcode
5. pop up the network access permission dialog and  pasteboard access dialog
6. stop app in Xcode
7. click allow button in network access permission dialog
8. install app from Xcode again
9. pop up the pasteboard access dialog
10. click allow button in pasteboard access dialog
11. get the correct dynamic link

Through the above two ways, it can be determined that the problem is caused by the inaccessibility of the network.

**Comment by rizafran** [comment] 2023-04-12 13:43
@LinXunFeng, I'm sorry to hear that you are having trouble accessing Firebase from China. Based on the error you shared, it seems like you're having an issue related to network. We can't guarantee that FDL will work well, and we believe this may have been caused by networking conditions being blocked by China, rather than Google's infrastructure. Unfortunately we can't do much about this from our end, and we can't help you with a workaround. That being said, I'll now be closing this ticket.

**Closed by rizafran** 2023-04-12 13:43 UTC
Labels: api: dynamiclinks, needs-attention
