### ISSUE TITLE
The `snapshot.exists` returns `false` even if the document snapshot exists.

### ISSUE THREAD

**Issue by chauhan130** [firebase/firebase-ios-sdk#8944] opened 2021-11-09 06:04 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1 (13A1030d)
  * Firebase SDK version: Firebase/Firestore (8.9.1), Firebase/Auth (8.9.1), (I have used with 7.5.0 as well).
  * Installation method: `CocoaPods`
  * Firebase Component: Auth, Firestore

### [REQUIRED] Step 2: Describe the problem
We use firebase auth for authentication of the users in our app. Each user has corresponding document under the `Users` collection. The `Firebase.User.uid` is used as the documentId for that user for ease. 

Every time a user logs in (with Email/Password), I check if the document snapshot exists or not. If the snapshot exists, then I use that document otherwise create new document for that user.

But sometimes the `snapshot.exists` returns `false` even if the document is there. Also the `snapshot.data()` is also `nil`!

#### Steps to reproduce:
This issue happens every time our app is deleted and when the user first logs in. I am still trying to reproduce this on another demo project but it works fine there.

#### Relevant Code:

```
func getUserDetails(with authUser: Firebase.User, completion: @escaping UserFetchAPICompletion) {
    Firestore.firestore().collection("Users").document(authUser.uid).getDocument { (snapshot, error) in
        guard let snapshot = snapshot else {
            print("Could not fetch document snapshot. Error: \(error)")
            return
        }

        guard snapshot.exists else {
            // User is registered, but the user document does not exist in the firestore database.
            // Create empty document of this user and bail.
            self.createEmptyUserDocument(userId: authUser.uid)
            return
        }

        guard let userJson = snapshot.data() else {
            print("Snapshot data does not exist.")
            return
        }

        completion(.success(userJson))
    }
}
```

I confirm that the document does exist for that user for that exact userId. But the `document.snapshot.exists` returns `false`. When I restart the app, it again returns true and all consecutive logins do not have any issues.

**Comment by schmidt-sebastian** [comment] 2021-11-09 21:25
@chauhan130 Thanks for reporting this.

You are likely receiving a snapshot from cache when the data on the device does not match the data on the backend. You should be able to tell by inspecting the snapshot metadata (`snapshot.metadata.fromCache`).

You may want to fix this by always fetching data from the server. You can do this by invoking `getDocument:source` (https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/DocumentReference#getdocumentsource:completion:). 

Note that the overall approach is general is prone to data races if another client might create a document with the same document ID. I would advise you to execute this type of code in a transaction.

**Comment by chauhan130** [comment] 2021-11-10 14:11
Thank you @schmidt-sebastian for the response. I confirm that the response is not from the cache, as every time I delete the app and then reinstall and in very first attempt it returns `false`. Besides, I debugged the app as well:

<img width="433" alt="Debug" src="https://user-images.githubusercontent.com/1622768/141128424-6ec64587-1ac4-4e62-be2c-855f9a25f29b.png">
<img width="923" alt="Document" src="https://user-images.githubusercontent.com/1622768/141128433-5a6aca31-1bd1-4b20-98bd-5a55bb4845c8.png">

**Comment by schmidt-sebastian** [comment] 2021-11-11 21:57
Hm. Are you able to collect debug logs? That should show if the document was downloaded from the Server. You can enable debug logging by calling `enableLogging`: https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Firestore#enablelogging_:

**Comment by chauhan130** [comment] 2021-11-12 07:44
Sure. Here are logs I see for Firebase:

```
2021-11-12 12:42:44.640513+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Initializing. Current user: jps0a38SPyVgVET0VpUG7yC9kNs2
2021-11-12 12:42:44.644871+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Using /var/mobile/Containers/Data/Application/B1D6B762-3BD8-48A5-8E63-9830A2286B3C/Library/Application Support/firestore/__FIRAPP_DEFAULT/<project_name>/main for LevelDB storage
2021-11-12 12:42:44.753997+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Delete everything with prefix: 0 changes (0 bytes):>
2021-11-12 12:42:44.754647+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Delete everything with prefix: 0 changes (0 bytes):>
2021-11-12 12:42:44.754900+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Delete everything with prefix: 0 changes (0 bytes):>
2021-11-12 12:42:44.755330+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Delete everything with prefix: 0 changes (0 bytes):>
2021-11-12 12:42:44.755550+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Drop query cache: 2 changes (1 bytes):
  - Put [target_global:] (0 bytes)
  - Put [version:] (1 bytes)>
2021-11-12 12:42:44.756529+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Ensure sentinel rows: 1 changes (1 bytes):
  - Put [version:] (1 bytes)>
2021-11-12 12:42:44.756812+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction remove acknowledged mutations: 1 changes (1 bytes):
  - Put [version:] (1 bytes)>
2021-11-12 12:42:44.756980+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Ensure Collection Parents Index: 1 changes (1 bytes):
  - Put [version:] (1 bytes)>
2021-11-12 12:42:44.757597+0530 <project>[38649:4852085] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Start LevelDB: 0 changes (0 bytes):>
2021-11-12 12:42:44.769970+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Start MutationQueue: 0 changes (0 bytes):>
2021-11-12 12:42:44.770671+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2021-11-12 12:42:44.774313+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Locally write mutations: 3 changes (130 bytes):
  - Put [collection_parent: collection_id=Users] (0 bytes)
  - Put [document_mutation: user_id=jps0a38SPyVgVET0VpUG7yC9kNs2 path=Users/jps0a38SPyVgVET0VpUG7yC9kNs2 batch_id=1] (0 bytes)
  - Put [mutation: user_id=jps0a38SPyVgVET0VpUG7yC9kNs2 batch_id=1] (130 bytes)>
2021-11-12 12:42:44.774852+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NotifyLocalViewChanges: 0 changes (0 bytes):>
2021-11-12 12:42:44.775176+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2021-11-12 12:42:44.775330+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2021-11-12 12:42:44.775594+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] WriteStream (10d2280b8) start
2021-11-12 12:42:44.775771+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Auth][I-AUT000002] Token auto-refresh enabled.
2021-11-12 12:42:44.775975+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Auth][I-AUT000004] Token auto-refresh scheduled in 55:00 for the new token.
2021-11-12 12:42:44.776679+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Allocate target: 3 changes (97 bytes):
  - Put [query_target: canonical_id=Users/jps0a38SPyVgVET0VpUG7yC9kNs2|f:|ob:__name__asc target_id=2] (0 bytes)
  - Put [target: target_id=2] (91 bytes)
  - Put [target_global:] (6 bytes)>
2021-11-12 12:42:44.777148+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Using full collection scan to execute query: Query(canonical_id=Users/jps0a38SPyVgVET0VpUG7yC9kNs2|f:|ob:__name__asc)
2021-11-12 12:42:44.777371+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction ExecuteQuery: 0 changes (0 bytes):>
2021-11-12 12:42:44.778526+0530 <project>[38649:4852386] 7.5.0 - [Firebase/Firestore][I-FST000001] WatchStream (280882118) start
2021-11-12 12:42:44.778738+0530 <project>[38649:4852386] 7.5.0 - [Firebase/Firestore][I-FST000001] Creating Firestore stub.

2021-11-12 12:42:44.801529+0530 <project>[38649:4852386] 7.5.0 - [Firebase/Firestore][I-FST000001] WriteStream (10d2280b8) initial request: <WriteRequest 0x16ba9e410>: {
  database: "projects/<project_name>/databases/(default)"
}

2021-11-12 12:42:44.812465+0530 <project>[38649:4852386] 7.5.0 - [Firebase/Firestore][I-FST000001] WatchStream (280882118) watch: <ListenRequest 0x16ba9e338>: {
  database: "projects/<project_name>/databases/(default)"
  add_target {
    documents {
      documents: "projects/<project_name>/databases/(default)/documents/Users/jps0a38SPyVgVET0VpUG7yC9kNs2"
    }
    target_id: 2
  }
}
2021-11-12 12:42:45.046270+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] WriteStream (10d2280b8) headers (allowlisted): date: Fri, 12 Nov 2021 07:12:45 GMT
2021-11-12 12:42:45.046510+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] WriteStream (10d2280b8) response: <WriteResponse 0x16ba9e0d0>: {
  stream_id: "0"
  stream_token: "\031\020hB\002\201\364\265\265"
}
2021-11-12 12:42:45.046792+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Set stream token: 1 changes (11 bytes):
  - Put [mutation_queue: user_id=jps0a38SPyVgVET0VpUG7yC9kNs2] (11 bytes)>
2021-11-12 12:42:45.046993+0530 <project>[38649:4852380] 7.5.0 - [Firebase/Firestore][I-FST000001] WriteStream (10d2280b8) write request: <WriteRequest 0x16ba9de88>: {
  writes {
    update {
      name: "projects/<project_name>/databases/(default)/documents/Users/jps0a38SPyVgVET0VpUG7yC9kNs2"
    }
    update_mask {
    }
    current_document {
      exists: true
    }
    update_transforms {
      field_path: "last_login_at"
      set_to_server_value: REQUEST_TIME
    }
  }
  stream_token: "\031\020hB\002\201\364\265\265"
}
2021-11-12 12:42:45.365740+0530 <project>[38649:4852418] 7.5.0 - [Firebase/Firestore][I-FST000001] WatchStream (280882118) headers (allowlisted): date: Fri, 12 Nov 2021 07:12:45 GMT
2021-11-12 12:42:45.365960+0530 <project>[38649:4852418] 7.5.0 - [Firebase/Firestore][I-FST000001] WatchStream (280882118) response: <ListenResponse 0x16b86e098>: {
  target_change {
    target_change_type: ADD
    target_ids: 2
  }
}
2021-11-12 12:42:45.394497+0530 <project>[38649:4852086] 7.5.0 - [Firebase/Firestore][I-FST000001] WriteStream (10d2280b8) headers (allowlisted): date: Fri, 12 Nov 2021 07:12:45 GMT
2021-11-12 12:42:45.394774+0530 <project>[38649:4852086] 7.5.0 - [Firebase/Firestore][I-FST000001] WriteStream (10d2280b8) response: <WriteResponse 0x16ba9e0d0>: {
  stream_token: "\020\001\031\020hB\002\201\364\265\265"
  write_results {
    update_time {
      seconds: 1636701165
      nanos: 505775000
    }
    transform_results {
      timestamp_value {
        seconds: 1636701165
        nanos: 444000000
      }
    }
  }
  commit_time {
    seconds: 1636701165
    nanos: 505775000
  }
}
2021-11-12 12:42:45.399179+0530 <project>[38649:4852086] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Acknowledge batch: 6 changes (117 bytes):
  - Delete [document_mutation: user_id=jps0a38SPyVgVET0VpUG7yC9kNs2 path=Users/jps0a38SPyVgVET0VpUG7yC9kNs2 batch_id=1]
  - Delete [mutation: user_id=jps0a38SPyVgVET0VpUG7yC9kNs2 batch_id=1]
  - Put [document_target: path=Users/jps0a38SPyVgVET0VpUG7yC9kNs2 target_id=0] (1 bytes)
  - Put [mutation_queue: user_id=jps0a38SPyVgVET0VpUG7yC9kNs2] (13 bytes)
  - Put [remote_document: path=Users/jps0a38SPyVgVET0VpUG7yC9kNs2] (103 bytes)
  - Put [remote_document_read_time: path=Users snapshot_version=Timestamp(seconds=1636701165, nanoseconds=505775000) document_id=jps0a38SPyVgVET0VpUG7yC9kNs2] (0 bytes)>
2021-11-12 12:42:45.399589+0530 <project>[38649:4852086] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NotifyLocalViewChanges: 0 changes (0 bytes):>
2021-11-12 12:42:45.400772+0530 <project>[38649:4852086] 7.5.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2021-11-12 12:42:45.438036+0530 <project>[38649:4852418] 7.5.0 - [Firebase/Firestore][I-FST000001] WatchStream (280882118) headers (allowlisted): date: Fri, 12 Nov 2021 07:12:45 GMT
2021-11-12 12:42:45.441437+0530 <project>[38649:4852418] 7.5.0 - [Firebase/Firestore][I-FST000001] WatchStream (280882118) response: <ListenResponse 0x16b86e098>: {
  document_change {
    document {
      name: "projects/<project_name>/databases/(default)/documents/Users/jps0a38SPyVgVET0VpUG7yC9kNs2"
      // Other documents fields
      fields {
        key: "last_name"
        value {
          string_value: "Chauhan"
        }
      }
      fields {
        key: "first_name"
        value {
          string_value: "Sunil"
        }
      }
      fields {
        key: "company"
        value {
          string_value: "ABC Ltd."

        }
      }
(lldb) po snapshot.exists
false

(lldb) po authUser.uid
"jps0a38SPyVgVET0VpUG7yC9kNs2"

(lldb) po snapshot.documentID
"jps0a38SPyVgVET0VpUG7yC9kNs2"

(lldb) po snapshot.data()
nil

```

**Comment by schmidt-sebastian** [comment] 2021-11-12 17:25
@chauhan130 Thanks for providing the logs.

What is happening here is that you are issuing an `update()` before the SDK knows that the document exists. Since we do not have a local copy of the document, the update fails locally and is processed through the system as an "unknown document". Since you also have a listener open at the same time, this "unknown" document is then converted to a deleted document in the API layer. 

This is of course a bit unexpected and I will see if we can change this behavior for your use case without breaking any guarantees we have made in the past. For now, you should be able to work around this if you use a listener. The listener should receive two updates: the deleted document followed by the actual document (with the update applied).

Thanks for raising this.

**Comment by chauhan130** [comment] 2021-11-15 11:30
Yes! That was the problem! I now update the initial details about user after fetching the snapshot and it works now.

Thank you!

**Comment by schmidt-sebastian** [comment] 2021-12-21 18:33
Closing this for now. We can revisit this if we get more logs to help us diagnose the root cause.

**Closed by schmidt-sebastian** 2021-12-21 18:33 UTC
Labels: type: question, api: auth, api: firestore, needs-attention
