### ISSUE TITLE
I have a crash at GDTCCTNanopbHelpers.m line 151 when run on ios 13.3 

### ISSUE THREAD

**Issue by lehanphong** [firebase/firebase-ios-sdk#5176] opened 2020-03-24 08:50 UTC
This is log crash on Fabric, please check for me and fix (if need), thank!

OS Version: 13.3.1 (17D50)
Device: iPad mini 5 (WiFi)
RAM Free: 23.5%
Disk Free: 38.5%

#11. Crashed: com.twitter.crashlytics.ios.exception
0  VndirectTrading                0x104eb9edc CLSProcessRecordAllThreads + 4344979164
1  VndirectTrading                0x104eba2c4 CLSProcessRecordAllThreads + 4344980164
2  VndirectTrading                0x104ea9b30 CLSHandler + 4344912688
3  VndirectTrading                0x104eb84d4 __CLSExceptionRecord_block_invoke + 4344972500
4  libdispatch.dylib              0x18f257fd8 _dispatch_client_callout + 20
5  libdispatch.dylib              0x18f2647f4 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  VndirectTrading                0x104eb7f40 CLSExceptionRecord + 4344971072
7  VndirectTrading                0x104eb7d6c CLSExceptionRecordNSException + 4344970604
8  VndirectTrading                0x104eb7960 CLSTerminateHandler() + 4344969568
9  libc++abi.dylib                0x18f371634 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x18f3715c0 std::terminate() + 44
11 libobjc.A.dylib                0x18f2cb28c _objc_terminate() + 14
12 libdispatch.dylib              0x18f257fec _dispatch_client_callout + 40
13 libdispatch.dylib              0x18f25e450 _dispatch_lane_serial_drain + 568
14 libdispatch.dylib              0x18f25ee7c _dispatch_lane_invoke + 368
15 libdispatch.dylib              0x18f267f20 _dispatch_workloop_worker_thread + 580
16 libsystem_pthread.dylib        0x18f2bd6d0 _pthread_wqthread + 280
17 libsystem_pthread.dylib        0x18f2c39e8 start_wqthread + 8

--

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18f5b296c __exceptionPreprocess
1  libobjc.A.dylib                0x18f2cb028 objc_exception_throw
2  Foundation                     0x18f872eac -[NSData(NSData) initWithContentsOfFile:options:maxLength:error:]
3  Foundation                     0x18f89f548 +[NSData(NSData) dataWithContentsOfURL:options:error:]
4  VndirectTrading                0x105006a04 GDTCCTConstructLogEvent + 151 (GDTCCTNanopbHelpers.m:151)
5  VndirectTrading                0x10500658c GDTCCTConstructLogRequest + 121 (GDTCCTNanopbHelpers.m:121)
6  VndirectTrading                0x1050063a0 __GDTCCTConstructBatchedLogRequest_block_invoke + 91 (GDTCCTNanopbHelpers.m:91)
7  CoreFoundation                 0x18f602990 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
8  CoreFoundation                 0x18f482b58 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
9  VndirectTrading                0x1050062dc GDTCCTConstructBatchedLogRequest + 99 (GDTCCTNanopbHelpers.m:99)
10 VndirectTrading                0x105009468 -[GDTCCTUploader constructRequestProtoFromPackage:] + 358 (GDTCCTUploader.m:358)
11 VndirectTrading                0x105008d50 __32-[GDTCCTUploader uploadPackage:]_block_invoke.51 + 273 (GDTCCTUploader.m:273)
12 libdispatch.dylib              0x18f256b7c _dispatch_call_block_and_release
13 libdispatch.dylib              0x18f257fd8 _dispatch_client_callout
14 libdispatch.dylib              0x18f25e450 _dispatch_lane_serial_drain
15 libdispatch.dylib              0x18f25ee7c _dispatch_lane_invoke
16 libdispatch.dylib              0x18f267f20 _dispatch_workloop_worker_thread
17 libsystem_pthread.dylib        0x18f2bd6d0 _pthread_wqthread
18 libsystem_pthread.dylib        0x18f2c39e8 start_wqthread

#0. com.apple.main-thread
0  libsystem_malloc.dylib         0x18f29d3c0 nanov2_allocate + 12
1  libsystem_malloc.dylib         0x18f2a42d8 default_zone_calloc + 84
2  libsystem_malloc.dylib         0x18f2a18d4 malloc_zone_calloc + 148
3  libsystem_malloc.dylib         0x18f2a2270 calloc + 36
4  libobjc.A.dylib                0x18f2dcbd0 _objc_rootAllocWithZone + 40
5  Foundation                     0x18f88e698 +[NSISVariable variableWithDelegate:valueRestriction:shouldBeMinimized:] + 164
6  Foundation                     0x18f892ed8 -[NSContentSizeLayoutConstraint initWithLayoutItem:value:huggingPriority:compressionResistancePriority:orientation:] + 272
7  UIKitCore                      0x193a89df4 -[UIView(UIConstraintBasedLayout) _generateContentSizeConstraints] + 396
8  UIKitCore                      0x193a89984 -[UIView(UIConstraintBasedLayout) _updateContentSizeConstraints] + 384
9  UIKitCore                      0x193a93784 -[UIView(AdditionalLayoutSupport) _updateSystemConstraints] + 128
10 UIKitCore                      0x1930ba76c -[UIButton updateConstraints] + 3364
11 UIKitCore                      0x193a92464 -[UIView(AdditionalLayoutSupport) _sendUpdateConstraintsIfNecessaryForSecondPass:] + 504
12 UIKitCore                      0x193a92934 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 952
13 UIKitCore                      0x193a92818 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 668
14 UIKitCore                      0x193a92818 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 668
15 UIKitCore                      0x193a92818 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 668
16 Foundation                     0x18f88d85c -[NSISEngine withBehaviors:performModifications:] + 88
17 UIKitCore                      0x193a93094 __100-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:]_block_invoke + 104
18 UIKitCore                      0x193a91a34 -[UIView(AdditionalLayoutSupport) _withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:] + 128
19 UIKitCore                      0x193a92c90 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:] + 176
20 UIKitCore                      0x193a93b4c -[UIView(AdditionalLayoutSupport) _updateConstraintsAtEngineLevelIfNeededWithViewForVariableChangeNotifications:] + 436
21 UIKitCore                      0x193b52c00 -[UIView(Hierarchy) _updateConstraintsAsNecessaryAndApplyLayoutFromEngine] + 384
22 UIKitCore                      0x193b6692c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2280
23 libobjc.A.dylib                0x18f2c6a4c -[NSObject performSelector:withObject:] + 68
24 QuartzCore                     0x19617c55c -[CALayer layoutSublayers] + 292
25 QuartzCore                     0x19617c9ac CA::Layer::layout_if_needed(CA::Transaction*) + 484
26 UIKitCore                      0x193b52210 -[UIView(Hierarchy) layoutBelowIfNeeded] + 552
27 UIKitCore                      0x193b58d54 +[UIView(Animation) performWithoutAnimation:] + 104
28 UIKitCore                      0x1938a37b0 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 1124
29 UIKitCore                      0x193870088 -[UITableView _updateVisibleCellsNow:] + 2592
30 UIKitCore                      0x19388d838 -[UITableView layoutSubviews] + 164
31 UIKitCore                      0x193b668b0 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2156
32 libobjc.A.dylib                0x18f2c6a4c -[NSObject performSelector:withObject:] + 68
33 QuartzCore                     0x19617c55c -[CALayer layoutSublayers] + 292
34 QuartzCore                     0x19617c9ac CA::Layer::layout_if_needed(CA::Transaction*) + 484
35 QuartzCore                     0x19618f1bc CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 140
36 QuartzCore                     0x1960d3b00 CA::Context::commit_transaction(CA::Transaction*, double) + 308
37 QuartzCore                     0x1960fe910 CA::Transaction::commit() + 684
38 QuartzCore                     0x1960ff4e4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 96
39 CoreFoundation                 0x18f52d524 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
40 CoreFoundation                 0x18f5281c4 __CFRunLoopDoObservers + 420
41 CoreFoundation                 0x18f528774 __CFRunLoopRun + 1292
42 CoreFoundation                 0x18f527f40 CFRunLoopRunSpecific + 480
43 GraphicsServices               0x1997b8534 GSEventRunModal + 108
44 UIKitCore                      0x1936b3580 UIApplicationMain + 1940
45 VndirectTrading                0x104a95410 main + 17 (AppDelegate.swift:17)
46 libdyld.dylib                  0x18f3a6e18 start + 4

#1. Thread
0  libsystem_kernel.dylib         0x18f39dab4 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18f2bd71c _pthread_wqthread + 356
2  libsystem_pthread.dylib        0x18f2c39e8 start_wqthread + 8

#2. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x18f37ac04 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f37a020 mach_msg + 76
2  CoreFoundation                 0x18f52d964 __CFRunLoopServiceMachPort + 220
3  CoreFoundation                 0x18f5287fc __CFRunLoopRun + 1428
4  CoreFoundation                 0x18f527f40 CFRunLoopRunSpecific + 480
5  Foundation                     0x18f86d340 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
6  Foundation                     0x18f86d218 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x19374ee9c -[UIEventFetcher threadMain] + 156
8  Foundation                     0x18f86bfa4 -[NSThread main] + 40
9  Foundation                     0x18f9a7a74 __NSThread__start__ + 852
10 libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
11 libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#3. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x18f37ac04 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f37a020 mach_msg + 76
2  VndirectTrading                0x104ea5144 CLSMachExceptionServer + 4344893764
3  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
4  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#4. com.apple.CFStream.LegacyThread
0  libsystem_kernel.dylib         0x18f37ac04 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f37a020 mach_msg + 76
2  CoreFoundation                 0x18f52d964 __CFRunLoopServiceMachPort + 220
3  CoreFoundation                 0x18f5287fc __CFRunLoopRun + 1428
4  CoreFoundation                 0x18f527f40 CFRunLoopRunSpecific + 480
5  CoreFoundation                 0x18f546c48 _legacyStreamRunLoop_workThread + 264
6  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
7  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#5. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x18f37ac04 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f37a020 mach_msg + 76
2  CoreFoundation                 0x18f52d964 __CFRunLoopServiceMachPort + 220
3  CoreFoundation                 0x18f5287fc __CFRunLoopRun + 1428
4  CoreFoundation                 0x18f527f40 CFRunLoopRunSpecific + 480
5  CFNetwork                      0x19282d568 (Missing)
6  Foundation                     0x18f86bfa4 -[NSThread main] + 40
7  Foundation                     0x18f9a7a74 __NSThread__start__ + 852
8  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
9  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#6. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x18f37ac04 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f37a020 mach_msg + 76
2  CoreFoundation                 0x18f52d964 __CFRunLoopServiceMachPort + 220
3  CoreFoundation                 0x18f5287fc __CFRunLoopRun + 1428
4  CoreFoundation                 0x18f527f40 CFRunLoopRunSpecific + 480
5  Foundation                     0x18f86d340 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
6  VndirectTrading                0x10509f0d0 -[_SRRunLoopThread main] + 1742 (SRWebSocket.m:1742)
7  Foundation                     0x18f9a7a74 __NSThread__start__ + 852
8  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
9  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#7. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x18f37ac04 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f37a020 mach_msg + 76
2  CoreFoundation                 0x18f52d964 __CFRunLoopServiceMachPort + 220
3  CoreFoundation                 0x18f5287fc __CFRunLoopRun + 1428
4  CoreFoundation                 0x18f527f40 CFRunLoopRunSpecific + 480
5  Foundation                     0x18f86d340 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
6  VndirectTrading                0x1050b5fcc -[_FSRRunLoopThread main] + 1845 (FSRWebSocket.m:1845)
7  Foundation                     0x18f9a7a74 __NSThread__start__ + 852
8  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
9  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#8. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x18f39d188 __select + 8
1  CoreFoundation                 0x18f53b7b4 __CFSocketManager + 628
2  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
3  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#9. JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x18f39cccc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x18f2bf21c _pthread_cond_wait + 676
2  libc++.1.dylib                 0x18f3f1d04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  JavaScriptCore                 0x19e78d37c void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 104
4  JavaScriptCore                 0x19e790de0 bmalloc::Scavenger::threadRunLoop() + 196
5  JavaScriptCore                 0x19e790ad8 bmalloc::Scavenger::Scavenger(std::__1::lock_guard<bmalloc::Mutex>&) + 14
6  JavaScriptCore                 0x19e791e1c std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*) + 42
7  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
8  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#10. WebThread
0  libsystem_kernel.dylib         0x18f37ac04 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18f37a020 mach_msg + 76
2  CoreFoundation                 0x18f52d964 __CFRunLoopServiceMachPort + 220
3  CoreFoundation                 0x18f5287fc __CFRunLoopRun + 1428
4  CoreFoundation                 0x18f527f40 CFRunLoopRunSpecific + 480
5  WebCore                        0x197702820 RunWebThread(void*) + 564
6  libsystem_pthread.dylib        0x18f2bb840 _pthread_start + 168
7  libsystem_pthread.dylib        0x18f2c39f4 thread_start + 8

#11. Crashed: com.twitter.crashlytics.ios.exception
0  VndirectTrading                0x104eb9edc CLSProcessRecordAllThreads + 4344979164
1  VndirectTrading                0x104eba2c4 CLSProcessRecordAllThreads + 4344980164
2  VndirectTrading                0x104ea9b30 CLSHandler + 4344912688
3  VndirectTrading                0x104eb84d4 __CLSExceptionRecord_block_invoke + 4344972500
4  libdispatch.dylib              0x18f257fd8 _dispatch_client_callout + 20
5  libdispatch.dylib              0x18f2647f4 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  VndirectTrading                0x104eb7f40 CLSExceptionRecord + 4344971072
7  VndirectTrading                0x104eb7d6c CLSExceptionRecordNSException + 4344970604
8  VndirectTrading                0x104eb7960 CLSTerminateHandler() + 4344969568
9  libc++abi.dylib                0x18f371634 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x18f3715c0 std::terminate() + 44
11 libobjc.A.dylib                0x18f2cb28c _objc_terminate() + 14
12 libdispatch.dylib              0x18f257fec _dispatch_client_callout + 40
13 libdispatch.dylib              0x18f25e450 _dispatch_lane_serial_drain + 568
14 libdispatch.dylib              0x18f25ee7c _dispatch_lane_invoke + 368
15 libdispatch.dylib              0x18f267f20 _dispatch_workloop_worker_thread + 580
16 libsystem_pthread.dylib        0x18f2bd6d0 _pthread_wqthread + 280
17 libsystem_pthread.dylib        0x18f2c39e8 start_wqthread + 8

#12. Thread
0  libsystem_pthread.dylib        0x18f2c39e0 start_wqthread + 178

#13. Thread
0  libsystem_pthread.dylib        0x18f2c39e0 start_wqthread + 178

**Comment by paulb777** [comment] 2020-03-24 15:28
Should be a duplicate of #5082 for which the fix was released today in  GoogleDataTransportCCTSupport (2.0.1)

**Closed by paulb777** 2020-03-24 15:28 UTC
Labels: needs-triage
