### ISSUE TITLE
Crashed: com.google.fira.worker apmpb_init_measurement_bundle

### ISSUE THREAD

**Issue by Rcrosp** [firebase/firebase-ios-sdk#9339] opened 2022-02-13 11:46 UTC
com.google.fira.worker
0  libsystem_platform.dylib       0x7004 os_unfair_lock_lock_with_options$VARIANT$mp + 38
1  libsystem_malloc.dylib         0x2d60 tiny_malloc_should_clear + 124
2  libsystem_malloc.dylib         0x5ef8 szone_malloc_should_clear + 76
3  libsystem_malloc.dylib         0x4110 _malloc_zone_calloc + 80
4  0x1527910 apmpb_init_measurement_bundle + 4355275024
5  0x152866c apmpb_copy_measurement_bundle + 4355278444
6 0x1533504 -[APMPBMeasurementBundle initWithMessageInfo:] + 4355323140
7  0x15335ec -[APMPBMeasurementBundle initWithBuffer:] + 4355323372
8  0x14d9b64 __59-[APMDatabase queryRawEventsMetadataWithFingerprint:error:]_block_invoke + 4354956132
9  [APMDatabase dataTypesFromTableWithName:columnName:columnValue:error:createDataTypeBlock:] + 4354999292
10 APMDatabase queryRawEventsMetadataWithFingerprint:error:] + 4354955904
11 [APMDatabase insertIfNotExistsRawEventMetadata:error:] + 4354955380
12 [APMMeasurement(Event) writeEvent:isPublicEvent:isRealtime:] + 4355159632
13 [APMMeasurement(Event) writeEventOnWorkerQueue:]_block_invoke + 4355148992
14 APMSqliteStore performTransactionWithError:block:] + 4355402284
15 [APMDatabase performTransaction:] + 4354951200
16 APMMeasurement(Event) writeEventOnWorkerQueue:] + 4355148164
17 [APMMeasurement(Event) handleEventOnWorkerQueue:] + 4355146976
18 [APMMeasurement logEventOnWorkerQueue:notifyEventListeners:] + 4355205408
19 [APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 4355205328
20 [APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 4355204524
21 [APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4355357752
22 libdispatch.dylib              0x631a4 _dispatch_call_block_and_release + 24
23 libdispatch.dylib              0x641a8 _dispatch_client_callout + 16
24 libdispatch.dylib              0xa0e4 _dispatch_lane_serial_drain$VARIANT$mp + 644
25 libdispatch.dylib              0xab94 _dispatch_lane_invoke$VARIANT$mp + 408
26 libdispatch.dylib              0x14760 _dispatch_workloop_worker_thread + 632
27 libsystem_pthread.dylib        0x4e84 _pthread_wqthread + 284
28 libsystem_pthread.dylib        0x49f0 start_wqthread + 8

**Comment by Rcrosp** [comment] 2022-02-14 03:32
https://github.com/firebase/firebase-ios-sdk/labels/api:analyst

**Comment by Rcrosp** [comment] 2022-02-14 03:34
ok

**Comment by rizafran** [comment] 2022-02-14 14:05
Thanks for reporting, @Rcrosp. Please provide the other required information such as the SDK version used, installation method, and detailed steps to reproduce the issue.

**Comment by Rcrosp** [comment] 2022-02-21 11:59
pod 'Firebase/Messaging', '7.9.0'
  pod 'Firebase/Crashlytics', '7.9.0'
  pod 'Firebase/Performance', '7.9.0'
  pod 'Firebase/Analytics', '7.9.0‘
  pod 'Firebase/DynamicLinks', '7.9.0'

**Comment by Rcrosp** [comment] 2022-02-21 12:00
> Thanks for reporting, @Rcrosp. Please provide the other required information such as the SDK version used, installation method, and detailed steps to reproduce the issue.

iOS 14.6.0

**Comment by Rcrosp** [comment] 2022-02-21 12:06
> Hey @Rcrosp. We need more information to resolve this issue but there hasn't been an update in 5 weekdays. I'm marking the issue as stale and if there are no new updates in the next 5 days I will close it automatically.
> 
> If you have more information that will help us get to the bottom of this, just add a comment!


-[APMSqliteStore endTransaction]
Thread #1
__workq_kernreturn
Thread #2
__workq_kernreturn
com.apple.uikit.eventfetch-thread
mach_msg_trap
com.apple.NSURLConnectionLoader
mach_msg_trap
AVAudioSession Notify Thread
mach_msg_trap
com.apple.coreaudio.AQClient
mach_msg_trap
com.apple.CoreMotion.MotionThread
mach_msg_trap
JavaScriptCore bmalloc scavenger
__psynch_cvwait
com.google.firebase.crashlytics.MachExceptionServer
FIRCLSProcessRecordAllThreads
Thread #3
start_wqthread
Thread #4
start_wqthread

**Comment by rizafran** [comment] 2022-02-21 13:51
Thanks for sharing your details, @Rcrosp. Per checking, it seems that you're using an outdated SDK version. Could you try updating to the latest one and see if the issue persists?

**Comment by Rcrosp** [comment] 2022-02-22 02:13
> Thanks for sharing your details, @Rcrosp. Per checking, it seems that you're using an outdated SDK version. Could you try updating to the latest one and see if the issue persists?

our cocoapds is  1.10.0， but the new version is 1.11.2， because GoogleAppMeasurement need 1.11.2， can u provide the new that support  1.10.0。

**Comment by paulb777** [comment] 2022-02-22 02:17
Sorry, we require the more recent CocoaPods version for FirebaseAnalytics to support `xcframeworks` and Firebase development on Apple M1 Macs.

**Comment by Rcrosp** [comment] 2022-02-22 05:34
we need Firebase/Crashlytics in app，can we remove Firebase/Analytics ？

**Comment by Rcrosp** [comment] 2022-02-22 05:48
> we need Firebase/Crashlytics in app，can we remove Firebase/Analytics ？

**Comment by Rcrosp** [comment] 2022-02-22 05:58
> 

we couldn't update our cocoapods，because  our cocoapods are changed， how to resolve this issue？

**Comment by paulb777** [comment] 2022-02-22 14:57
Most of Crashlytics works without Analytics, but a few features depend on it. See https://firebase.googleblog.com/2020/09/crashlytics-analytics-together.html#:~:text=Some%20of%20these%20features%20include,visualize%20your%20apps%20key%20metrics.

**Comment by morganchen12** [comment] 2022-02-22 19:52
Closing since we have no plans to make Firebase 8+ available on older versions of CocoaPods, but feel free to continue discussion in this thread if you have further questions @Rcrosp.

**Closed by morganchen12** 2022-02-22 19:52 UTC
Labels: api: analytics
