### ISSUE TITLE
Messaging and Performance not working together on iOS 13

### ISSUE THREAD

**Issue by da-mian** [firebase/firebase-ios-sdk#3891] opened 2019-09-20 10:41 UTC
* Xcode version: 11 GM 2
  * Firebase SDK version: 6.8.1
  * Firebase Component: Messaging + Performance
  * Component version: FirebaseMessaging (4.1.4) & FirebasePerformance (3.1.4)

#### Steps to reproduce:

`func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)` is not called until the app is restarted. Only happens when importing `FirebasePerformance` into the project.

#### Relevant Code:

In the AppDelegate:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        window = UIWindow(frame: UIScreen.main.bounds)

        FirebaseApp.configure()
        Messaging.messaging().delegate = self
        UNUserNotificationCenter.current().delegate = self

        let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
        UNUserNotificationCenter.current().requestAuthorization(
          options: authOptions,
          completionHandler: {_, _ in })
        application.registerForRemoteNotifications()

        return true
    }
```

In Podfile

```
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
```

`func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)` Is not called in the first app start.
By removing `pod 'Firebase/Performance'` form the Podifile, the problem is gone.

When the problem occurs some error are logged like:

Task <14CEA9FB-0EEA-43EF-8AAE-C21EE06EA1FF>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])
6.8.1 - [Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=NSURLErrorDomain Code=-999 
6.8.1 - [Firebase/InstanceID][I-IID007007] Inconsistent state: NSURLSession has been invalidated

**Comment by chliangGoogle** [comment] 2019-09-20 21:24
@da-mian Are you running this on simulator or real devices?

**Comment by chliangGoogle** [comment] 2019-09-20 21:40
I can reproduce on simulator only and with messaging and perf in the pod at the same time.

**Comment by da-mian** [comment] 2019-09-20 21:44
I’m running on real device.

**Comment by visumickey** [comment] 2019-09-24 17:17
This is because of the issue where Firebase Performance intercepts the network request made by Messaging and we are able to reproduce this successfully. We are working on a fix for this. Will update shortly on this thread.

**Comment by GoranLilja** [comment] 2019-10-08 04:58
Any updates on this topic?

**Comment by visumickey** [comment] 2019-10-14 16:44
@GoranLilja We made some changes to Fireperf in the recent version (6.10.0). Can you check if the issue still happening? Ideally this issue should not be reproducible now.

**Comment by visumickey** [comment] 2019-10-14 19:08
We verified this issue with 6.10.0 version of Firebase release and this is not reproducible. So closing the issue. Please re-open if you still find this issue.

**Closed by visumickey** 2019-10-14 19:08 UTC
Labels: api: messaging, api: performance, iOS 13, needs-info
