### ISSUE TITLE
Functions chunky response

### ISSUE THREAD

**Issue by nmalevich** [firebase/firebase-ios-sdk#12914] opened 2024-05-08 13:50 UTC
### Description

I write response by chunks. On my local server it works, but Firebase Function return response only after "res.end()"

```
exports.cloudFunctionEntryPoint = async (req, res) => {
    setTimeout(()=>{
        res.write("1\n");
    }, 1000)
    setTimeout(()=>{
        res.write("2\n");
    }, 2000)
    setTimeout(()=>{
        res.write("3\n");
    }, 3000)
    setTimeout(()=>{
        res.write("4\n");
    }, 4000)
    setTimeout(()=>{
        res.write("5\n");
        res.end();
    }, 5000)
}
```

### Firebase SDK Version

10.25.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Functions

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2024-05-09 18:12
Hi @nmalevich, could you provide a code snippet of your Firebase Functions and iOS code invoking the function so I could reproduce it on my end? Thanks.

**Comment by nmalevich** [comment] 2024-05-10 11:10
Thank you for your reply. My general question about having possibility to implement streaming data(sending response by chunks)

**Comment by rizafran** [comment] 2024-05-28 11:31
@nmalevich, per checking, it looks like Cloud Functions does not support data streaming. They have a timeout limitation of up to max 10MB. You may refer to this [post](https://stackoverflow.com/a/73299271).

Closing this issue, but feel free to comment if you have any questions.

**Closed by rizafran** 2024-05-28 11:31 UTC
Labels: api: functions, needs-attention
