### ISSUE TITLE
iOS 17.0 beta4 Crashed:quic_recovery_declare_packets_lost

### ISSUE THREAD

**Issue by linziyiwj** [firebase/firebase-ios-sdk#11655] opened 2023-08-07 02:41 UTC
### Description

A large number of crashes occurred only on iOS 17.0 online from July 27, which is consistent with the release time of the 17.0 beta4 version.  The crash stack information is related to nw_connection..., Does anyone have the same problem and is there a solution? Thanks a lot

The following is the online crash stack information：
![image](https://github.com/firebase/firebase-ios-sdk/assets/39822433/b38e0155-6fdb-4877-9f96-79d2a165eb46)

### Firebase SDK Version

10.4.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Crashlytics, In-App Messaging, Performance, Remote Config, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment] 2023-08-08 16:55
The crashing thread is owned by an Apple framework and there's no Firebase symbols in this thread. Closing since it does not appear to be a crash caused by Firebase.

**Closed by morganchen12** 2023-08-08 16:55 UTC
Labels: Xcode 15 - iOS 17
