### ISSUE TITLE
Unable to install the Firebase iOS SDK (7.9.0) through SPM

### ISSUE THREAD

**Issue by cpdunphy** [firebase/firebase-ios-sdk#7777] opened 2021-03-24 13:27 UTC
### Environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.9.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Take your pick.. I could not get the option to select the desired components. 

### Problem

Unable to install the Firebase iOS SDK (7.9.0) through SPM. Failing with the error: `Failed to resolve dependencies`

This seems to be a problem isolated to 7.9.0, I am able to install 7.8.1 with no issues. I tried using different targeted iOS versions ranging from 13.0 - 14.4. 

Reseting the Package Cache had no effect.

```
Failed to resolve dependencies because no versions of firebase-ios-sdk match the requirement 7.9.1..<8.0.0 and package firebase-ios-sdk is required using a version-based requirement and it depends on unversion package grpc-swiftpm, firebase-ios-sdk >=7.9.0 is forbidden.
And because root depends on firebase-ios-sdk 7.9.0..<8.0.0, version solving failed.
```

#### Steps to reproduce:

1) Create a new project in Xcode. 
2) Add "https://github.com/firebase/firebase-ios-sdk.git" as a Package Dependency with the exact version of `7.9.0`.

Thanks for taking the time! I'm glad to see Firebase SwiftUI support extending through the new `FirebaseAnalyticsSwift` component as well. :)

**Comment by paulb777** [comment] 2021-03-24 14:19
@cpdunphy Thanks for the report. I've reproduced and we're investigating ...

**Comment by paulb777** [comment] 2021-03-24 14:25
It looks like a result of changing from version dependencies to hash dependencies in #7563. I'll work on a fix.

**Comment by cpdunphy** [comment] 2021-03-24 14:31
Sounds great! I appreciate the quick turnaround.

**Comment by timmythompsen** [comment] 2021-03-24 15:16
Im running into the same issue! Thanks for the quick fix everyone

**Comment by paulb777** [comment] 2021-03-24 15:39
I just published a 7.9.1 and verified that my test example is fixed with that.

For future reference, I first tried moving the 7.9.0 tag, but Xcode used a cached version of the repo and tag that didn't get reset even after removing `DerivedData`.

**Comment by rrozenv** [comment] 2021-03-24 17:03
@paulb777 I think I am having a related issue with boringssl-SwiftPM. Even after clearing derived data and resetting all package caches I am seeing a `openssl/arm_arch.h file not found`. I tried downgrading to 7.8.1 and it does not work there either 

![Screen Shot 2021-03-24 at 1 00 05 PM](https://user-images.githubusercontent.com/25207952/112352638-4e869c00-8ca1-11eb-9297-9f640801f56c.png)

**Comment by cpdunphy** [comment] 2021-03-24 17:53
@rrozenv I am running into the same issue that you described. (Downgrading to 7.8.1 does not work as well)

**Comment by paulb777** [comment] 2021-03-24 19:04
Reproduced when building for device. It's a result of https://github.com/firebase/boringSSL-SwiftPM/pull/1/files. 

Sorry about the churn.  We clearly have to improve our SPM testing and CI.

I'll work on a fix.

Note this issue should be Firestore only. Locking the BoringSSL-GRPC dependency to 0.0.7 should be a workaround and I'll try to get a 0.0.9 soon.

**Comment by paulb777** [comment] 2021-03-24 19:21
There is now a 0.0.9 update for BoringSSL-SwiftPM, but there is also a problem with the abseil dependency. I'll work on that one as well, and in the meantime, that needs to be force back to 0.20200225.0.  

I'll work through any other build issues and  do my best to get a complete resolution out later today.

**Comment by rrozenv** [comment] 2021-03-24 19:29
@paulb777 Thanks for taking a look. Is it possible if you could force Firebase 7.9.1 to point back to abseil 0.20200225.0? Or maybe create a separate branch where this is the case? Just want to have an interim solution so I'm not blocked. Really appreciate it.

**Comment by paulb777** [comment] 2021-03-24 20:41
@rrozenv I made an abseil 0.20200225.2 and my early tests successfully build after Swift Packages -> Update to Latest Package Versions.

I want to do more testing before making a Firebase 7.9.2 and would appreciate any feedback on if the latest versions resolve your issues.

**Comment by paulb777** [comment] 2021-03-24 21:01
It looks like fresh installs of 7.9.1 get the corrected abseil and boringssl versions. I've verified that the Firestore quickstart now builds and runs on device.  

Let me know if you see any additional issues or if you see the need for a 7.9.2 that forces the minimum versions of the corrected dependencies.

**Comment by rrozenv** [comment] 2021-03-24 21:03
@paulb777 abseil 0.20200225.2 seems to have done the trick. I don't think 7.9.2 is required. Thanks again

**Closed** 2021-03-24 21:31 UTC
Labels: Swift Package Manager

**Comment by paulb777** [comment] 2021-03-24 21:35
The Firestore device build issue is solved by https://github.com/firebase/abseil-cpp-SwiftPM/pull/3 and https://github.com/firebase/boringSSL-SwiftPM/pull/2 along with tag updates.

**Comment by unxavi** [comment] 2021-04-07 17:13
@paulb777 I'm getting this issue when I add the Firestore dependency with SPM with verion 7.10.0

I have cleared the derived data and as soon as I add FirebaseFirestore this compilation error comes. Should I do anything else? should I open a new issue?

**Comment by paulb777** [comment] 2021-04-07 17:27
@unxavi I'm not able to reproduce. 

Would you try `Swift Packages -> Update to Latest Package Versions` and note any version changes of the packages installed?

**Comment by unxavi** [comment] 2021-04-07 20:17
@paulb777 I think what did it to me was to `reset the package cache`. I also run the ` Swift Packages -> Update to Latest Package Versions` but well, seems to works, thanks a lot and sorry to make noise on the thread, it was driving me crazy all day. Thanks again
