### ISSUE TITLE
Auth from shared keychain causing problems to connect to firestore

### ISSUE THREAD

**Issue by moopoints** [firebase/firebase-ios-sdk#3185] opened 2019-06-13 14:50 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.2.0
  * Firebase Component: Core/Auth
  * Component version: 6.2.0

### [REQUIRED] Step 3: Describe the problem

I implemented the newly added cross-app auth with share ios keychain following the instructions here (https://firebase.google.com/docs/auth/ios/single-sign-on). Initially auth as well as the usage of listeners and cloud functions are working just fine, but then after a while (both on the simulator as well as actual devices), the connection cannot be created anymore. It's unclear to me whether this is caused by using users from shared access groups or simply a recent update to the firebase sdk. 

#### Steps to reproduce:

I have had a hard time to identify any correlating factors or immediate ways to reproduce this but will report back if I do. So far it looks like this is triggered by time (possibly auth tokens aren't renewing properly after an hour?). The error message is below. The error message appears even though the device/simulator definitely have internet connectivity. When this happens I still have access to the current user from Auth. 

Restarting the app won't fix this. Only signing out entirely and signing back in allows for a connection to be made again. I am using only google auth in this case. The error message is this:

6.2.0 - [Firebase/Firestore][I-FST000001] Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: An internal error has occurred, print and inspect the error details for more information.
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

**Comment by morganchen12** [comment] 2019-06-13 16:29
@moopoints, can you print the full error object and share the detailed description here?

**Comment by moopoints** [comment] 2019-06-13 17:12
I'm not sure how I can get a full error object. 

Here is the entire print from the log:

2019-06-13 13:10:14.939424-0400 app-name[4777:3498470] 6.2.0 - [Firebase/Firestore][I-FST000001] Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: An internal error has occurred, print and inspect the error details for more information.
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

At this point I can reproduce this error reliably and conclude that it's triggered by time. Immediately after auth all functions work just fine and I have access to the firestore backend. After roughly an hour the app isn't able to connect anymore, even though a connectivity surely exists.

**Comment by morganchen12** [comment] 2019-06-13 17:27
In your snapshot listener, do you receive an error object when this happens?

**Comment by moopoints** [comment] 2019-06-13 19:06
Nope, my listeners all return snapshots successfully. However they are missing the most recent items, indicating that they are fetching against the local cache.

**Comment by moopoints** [comment] 2019-06-14 16:55
Any further assistance with this? I can predictably reproduce this: the first hour I have a connection to Firestore with the shared access group user. After an hour no connection can be established anymore. Should I revert to the default auth and wait for this feature to move out of beta?

**Comment by morganchen12** [comment] 2019-06-14 17:09
For the time being, yes. We'll update this ticket when we find a workaround or solution.

**Comment by morganchen12** [comment] 2019-06-14 18:33
@moopoints, can you share your project or a sample that reproduces this issue?

**Comment by moopoints** [comment] 2019-06-15 14:28
I'm sorry, I wish I could share the project. Do you possibly have a sample project that has a working implementation?

**Comment by FE-Mars** [comment] 2019-06-16 13:41
flutter: PlatformException(Error 14, FIRFirestoreErrorDomain, Failed to get document because the client is offline.)

**Comment by morganchen12** [comment] 2019-06-17 20:49
You can try reproing using the [Firestore quickstart](https://github.com/firebase/quickstart-ios/tree/master/firestore), though it doesn't use a shared keychain.

**Comment by moopoints** [comment] 2019-06-21 01:46
This turns out to be a more general problem with auth. I reverted my code to the default auth (using GDSignin) and am not using shared keychain users anymore. I still have the same issue: auth and connection work perfectly fine for the first hour after signing in. Then I can't make any connection to firebase anymore. This has been an issue since I updated to 6.2.0 (I was previously on 5.x). I just updated to 6.3.0 and am unfortunately still experiencing the same issue. What's a good way to trouble shoot this? Error code below:

6.3.0 - [Firebase/Firestore][I-FST000001] Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: An internal error has occurred, print and inspect the error details for more information.
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

**Comment by morganchen12** [comment] 2019-06-21 17:08
Can [set the logging level to Debug](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:) and share your app's logs when the issue occurs?

**Comment by sliemeobn** [comment] 2019-06-26 21:54
I am seeing the same issue - here is what is was just sending to Firebase support about my issue (includes a detailed error message)

----
I did follow the documentation, and it mainly is/was working after changing to useUserAccessGroup. (app group, shared with my Notification Content Extension)

However, after a while (I guess when the token expires) it stops working and I get the following error message when I do a FirebaseFunctions call.

Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x7b0c000921f0 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 400;
    details =     (
                {
            "@type" = "type.googleapis.com/google.rpc.Help";
            links =             (
                                {
                    description = "Google developers console";
                    url = "https://console.developers.google.com";
                }
            );
        }
    );
    message = "API key not valid. Please pass a valid API key.";
    status = "INVALID_ARGUMENT";
}}}}

When I am in this state, I get this error in both the extension and the main app itself. At least Firestore and Functions then cannot do anything.
After I force an signOut/signIn it all works again.

**Comment by sliemeobn** [comment] 2019-06-26 22:08
how I can reproduce it:

- have an app and notification extension share an app group
- setUserAccessGroup to app group
- signIn
- call a firebase function (it works)
- wait one hour
- call firebase function again (it fails)

pretty nasty problem...

**Comment by renkelvin** [comment] 2019-06-27 23:19
This is a known issue and should be fixed in next release. https://github.com/firebase/firebase-ios-sdk/pull/3239

**Closed** 2019-06-27 23:22 UTC
Labels: api: auth, api: core
