### ISSUE TITLE
Firebase Database not pruning tracked queries

### ISSUE THREAD

**Issue by marcbaldwin** [firebase/firebase-ios-sdk#1518] opened 2018-07-11 16:45 UTC
* Xcode version: 9.4.1 (9F2000)
  * Firebase SDK version: 5.4.0
  * Firebase Component: Database
  * Component version: 5.4.0

### Description of the problem

The time it takes for the first callback to occur when observing a reference increases proportionally with the number of writes made. In some cases this means it takes nearly three minutes for the first callback to occur.

Note: Turning off persistence fixes the issue.

#### Steps to reproduce:

Enable persistence.
Observe a database reference
Make thousands of writes
Re-open the app, the time taken before the first callback of the reference will have increased

I profiled the app in instruments and narrowed down the cause to ```FTrackedQueryManager.initWithStorageEngine```

It loops through all tracked queries, in my case I had some 200,000 tracked queries. Looking at them in the debug viewer I noticed most were from writes which were made months ago.

It appears as though every time a write occurs a tracked query is added for the path of the write and is never removed, so overtime these tracked queries build up, leading to an ever increasing start up time for the FTrackedQueryManager.

There are functions to purge the cache but these are not public and they don't appear to be invoked when the Database is initialised.

#### Relevant Code:

```Swift
Database.database().isPersistenceEnabled = true
```

**Comment by morganchen12** [comment] 2018-07-11 17:19
@mikelehen the repro steps seem pretty ordinary, I'm surprised this hasn't shown up before. Is this a regression?

**Comment by mikelehen** [comment] 2018-07-11 18:19
This is probably related to https://github.com/firebase/firebase-ios-sdk/blob/c6b4b03fffc3cea7c9525e5c79dce28f52900521/Firebase/Database/Persistence/FPersistenceManager.m#L124

When you perform a write we add it to our cache, which includes adding it to our tracked queries (which helps us know that we have complete data for that location and can raise events for it if you listen in the future).

I believe our cache policy tries to keep only up to 1000 tracked queries (https://github.com/firebase/firebase-ios-sdk/blob/c6b4b03fffc3cea7c9525e5c79dce28f52900521/Firebase/Database/Persistence/FCachePolicy.m#L26) but we only check whether to prune the cache after every 1000 listen updates (see the line above).  So if your app only does writes (or mostly writes with very few listens or very infrequently-changing listens) then we may never attempt to prune the cache, allowing the tracked queries to grow...

A simple improvement may be to add a call to doPruneCheckAfterServerUpdate (https://github.com/firebase/firebase-ios-sdk/blob/c6b4b03fffc3cea7c9525e5c79dce28f52900521/Firebase/Database/Persistence/FPersistenceManager.m#L153) from applyUserWrite (https://github.com/firebase/firebase-ios-sdk/blob/c6b4b03fffc3cea7c9525e5c79dce28f52900521/Firebase/Database/Persistence/FPersistenceManager.m#L123). That way we'd do the prune check after each write and should actually limit you to ~1000 tracked queries.  [though we also should do some renaming of `afterServerUpdate` or at least add comments to explain what's going on]

@schmidt-sebastian officially maintains the Realtime Database SDK though I don't know if he has cycles to look into / implement / test this.  If you were so inclined, providing a PR might be more likely to get this fixed in the near-term. :-)

**Comment by marcbaldwin** [comment] 2018-07-12 13:17
Thanks @mikelehen for the speedy response. @schmidt-sebastian do you think you'll be able to have a look? If not I'd be happy to have a go at fixing it :)

Thanks!

**Comment by schmidt-sebastian** [comment] 2018-07-12 15:38
I can take a look at this next week or so. If you want to take a stab at it in the meantime, I would be more than happy to support you along the way. Thanks!

**Comment by marcbaldwin** [comment] 2018-07-13 09:18
Some more info...

After a write `FPersistenceManager.doPruneCheckAfterServerUpdate` is executed which checks to see if a prune is required according to its cache policy pacing in its `serverCacheUpdatesSinceLastPruneCheck` value.  However as the `serverCacheUpdatesSinceLastPruneCheck` is not persisted between app restarts, a prune will only occur after 1000 server updates during a single app session.

Some options:
 - Always perform a prune check (it doesn't appear to be a very CPU intensive task)
 - Reduce the maximum number of server updates before performing a prune
 - Persist the number of server updates since last prune check between app sessions
 - On first server update of any app session, always perform a prune

What do you suggest @schmidt-sebastian

**Comment by schmidt-sebastian** [comment] 2018-07-13 15:52
I would suggest you pick option 4 and perform a prune check at startup, and then once every 1000 operations. Since we target a wide range of mobile devices, it is sometimes very hard to predict what the perceived performance characteristics of changes in the persistence logic are.

**Comment by mikelehen** [comment] 2018-07-13 16:12
doPruneCheckAfterServerUpdate is actually pretty expensive because it has to iterate the entire database to estimate the cache size. It ends up calling https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Database/third_party/Wrap-leveldb/APLevelDB.mm#L289

So #4 is the most palatable of your options but it'll still slow down app starts for everybody.  And it'll still only help apps once they restart.  During the life of the app, if they're only doing writes (and not getting server updates) they'll never do another prune.

And so I still think my suggestion in https://github.com/firebase/firebase-ios-sdk/issues/1518#issuecomment-404264214 probably makes the most sense.

**Comment by marcbaldwin** [comment] 2018-07-13 16:34
Thanks for the input.

@mikelehen If `doPruneCheckAfterServerUpdate` is expensive then would it not be a bad idea to be calling it in`applyUserWrite`? In some cases our app might make multiple writes per second.

Could another option be to add a public method to perform a prune? Then users can perform it when it best suits the needs of their app. For example, I'd probably choose to do it after start-up and after an initial fetch from the database, or maybe when the app is sent to the background.

**Comment by mikelehen** [comment] 2018-07-13 16:58
@marcbaldwin Well, because of the `kFServerUpdatesBetweenCacheSizeChecks` counter in there it would still only do the expensive part of the check once every 1000 writes...  so you might see the occasional delayed write, but it shouldn't be too bad...  hopefully. :-)

Adding an API would certainly provide the most control for developers, but 1) ideally we'd solve this transparently for the majority of use cases without developers needing to change their code, and 2) adding an API is frankly more time-consuming and expensive. The Firebase APIs are carefully curated and there's an internal design / approval process that we'd need to go through to make changes.  It's certainly doable, but it's not something to be taken too lightly.

**Comment by marcbaldwin** [comment] 2018-07-24 14:10
@mikelehen @schmidt-sebastian sorry for the delayed response, I've been away on holiday.

@mikelehen calling `doPruneCheckAfterServerUpdate` from `applyUserWrite` still won't help unless our app performs 1000 writes or we change the if statement to account for the number of tracked queries.

```obj-c
// Current
- (void)doPruneCheckAfterServerUpdate {
    self.serverCacheUpdatesSinceLastPruneCheck++;
    if ([self.cachePolicy shouldCheckCacheSize: self.serverCacheUpdatesSinceLastPruneCheck]) {
```

```obj-c
/// proposed
- (void)doPruneCheckAfterServerUpdate {
    self.serverCacheUpdatesSinceLastPruneCheck++;
    if ([self.cachePolicy shouldCheckCacheSize: self.serverCacheUpdatesSinceLastPruneCheck 
                numberOfTrackedQueries: self.trackedQueryManager.numberOfPrunableQueries]) {
```

Thanks!

**Comment by mikelehen** [comment] 2018-07-24 19:07
@marcbaldwin Hrm.  Are you saying that your app is _not_ doing more than 1000 writes?  From your original statement about having 200,000 tracked queries, my assumption was that the pruning would kick in every time you reached ~1000, which should be sufficient to keep the performance good.

`self.trackedQueryManager.numberOfPrunableQueries` is an O(n) operation (it requires walking all of the tracked queries) and so doing it after every write or server update could impact performance significantly.

It also wouldn't help unless we also changed our current cache policy, since kFMaxNumberOfPrunableQueriesToKeep is set to 1000 (https://github.com/firebase/firebase-ios-sdk/blob/1d484d33a778a9778a728829a1e30dded4a3d68c/Firebase/Database/Persistence/FCachePolicy.m#L26).

**Comment by mikelehen** [comment] 2018-07-25 00:15
Out of curiosity, how many app sessions does it take for your app to hit 200,000?  I assumed there must be some action in your app that triggers a large number of writes and hopefully it'd (at least periodically?) exceed 1000 and the pruning would kick in.  It's not foolproof but I would expect it'd be good enough for most apps.

But yeah, persisting serverCacheUpdatesSinceLastPruneCheck would be more foolproof, dealing with the case of an app that accumulates many tracked queries over time but only a small number each app session. But I'm somewhat wary of making schema changes.  Most of our development effort is going into Cloud Firestore and we only have limited bandwidth to implement / test features for Realtime Database. Schema changes are more risky and time-consuming. :-/  

Also FWIW, persisting an extra value on every write / server update would make persistence a little slower...  so if most apps don't need it, it may not be the right trade-off.

**Comment by marcbaldwin** [comment] 2018-07-25 08:13
Depends on the user, but a few months most likely. Thing is even with 50,000 tracked queries it's still ~30 seconds of start-up time.

Anyway, if we perform the prune check on writes, I could just put a dirty hack in to our app to perform 1000 writes for users who are experiencing an incredibly slow start-up time.

I'll make a PR for the call to `doPruneCheckAfterServerUpdate` from `applyUserWrite` if you're happy with that?

**Comment by mikelehen** [comment] 2018-07-25 18:23
So thinking about this fresh today, I have a new suggestion (a tweak of previous things discussed above).

I don't want to call `self.trackedQueryManager.numberOfPrunableQueries` after every server update / write, but it would probably be fine to call it once at startup since startup already did the O(n) work to load the trackedQueries from persistence...  but I don't want to do the `serverCacheEstimatedSizeInBytes` work because that really is too expensive to do on startup.

So I suggest:
1. We extract lines 156 to 171 of `doPruneCheckAfterServerUpdate` into a new `doPruneCheck` method.
2. On startup (in `initWithStorageEngine`), we add code to check only the numberOfPrunableQueries, e.g.:
```
// Check if we have enough prunable queries to warrant doing a prune check on startup
// (but don't do the expensive work of estimating the cache size).
if ([self.cachePolicy shouldPruneCacheWithSize:0 
        numberOfTrackedQueries:self.trackedQueryManager.numberOfPrunableQueries]) {
  [self doPruneCheck];
}
```

What do you think?

**Comment by marcbaldwin** [comment] 2018-07-27 09:30
That sounds good to me. Are you going to do this or shall I?

**Comment by mikelehen** [comment] 2018-07-27 16:08
If you don't mind putting together a PR, that'd be great.

**Comment by marcbaldwin** [comment] 2018-07-30 15:42
@mikelehen trying out your suggestions.

If a prune is performed on start-up, the start-up time is just as bad as it was before! (I think it's O(n) where n is the number of items in the Database). So if during an app session there are >1000 writes/reads, they'll always get poor startup performance!

Looking at the prune function you can see it's incredibly inefficient (someone even left a TODO there). It scans the entire DB, and for each entry traverses the prune tree to see if it should prune it!

If we're going to prune on start-up, we need to optimise the prune function too. Is it possible to iterate the forest and remove from the DB? Or any other suggestions?

Thanks again

```swift
FLevelDBStorageEngine.m
````
```swift
- (void)pruneCache:(FPruneForest *)pruneForest atPath:(FPath *)path {
    // TODO: be more intelligent, don't scan entire database...

    __block NSUInteger pruned = 0;
    __block NSUInteger kept = 0;
    NSDate *start = [NSDate date];

    NSString *prefix = serverCacheKey(path);
    id<APLevelDBWriteBatch> batch = [self.serverCacheDB beginWriteBatch];


    [self.serverCacheDB enumerateKeysWithPrefix:prefix usingBlock:^(NSString *dbKey, BOOL *stop) {
        NSString *pathStr = [dbKey substringFromIndex:prefix.length];
        FPath *relativePath = [[FPath alloc] initWith:pathStr];
        if ([pruneForest shouldPruneUnkeptDescendantsAtPath:relativePath]) {
            pruned++;
            [batch removeKey:dbKey];
        } else {
            kept++;
        }
    }];
    BOOL success = [batch commit];
    if (!success) {
        FFWarn(@"I-RDB076021", @"Failed to prune cache on disk!");
    } else {
        NSTimeInterval time =  [start timeIntervalSinceNow]*-1000;
        FFDebug(@"I-RDB076022", @"Pruned %lu paths, kept %lu paths in %fms", (unsigned long)pruned, (unsigned long)kept, [start timeIntervalSinceNow]*-1000);
    }
}
```

**Comment by mikelehen** [comment] 2018-07-30 16:06
Oh, yes. pruning is O(n) and that's probably not avoidable... at least not without a rewrite which is unlikely to happen.

But if we prune on startup, then you should stay under 1000 queries, which should be pretty fast to prune, right?  In other words, yes you'll have O(1000) startup delays occasionally, but you'll never reach O(200k) like you're hitting right now.

Or are you saying that occasionally pruning at 1000 queries is too slow to accept?

**Comment by marcbaldwin** [comment] 2018-07-30 16:58
Yeah because pruning is O(number of entries in database) NOT O(number of prunable queries) it takes a loooooong time if your database has a lot of entries!

**Comment by mikelehen** [comment] 2018-07-30 17:57
Typically "number of entries in database" is proportional to "number of tracked queries" but if you have persisted queries with many results, there could be a lot of entries.

I am indeed getting scared that we can't make this change...  but I'm curious what kind of delays you're seeing for your use case.

**Comment by marcbaldwin** [comment] 2018-08-07 09:44
If a prune happens I was getting a delay of around 15 seconds for 1001 tracked queries, our app accumulates tracked queries pretty quickly, just not in one session, so perhaps every few sessions we'd get a start up time of around 15 seconds.

Do you guys have any time to look into this?

**Comment by mikelehen** [comment] 2018-08-08 19:03
Unfortunately probably not. :-(  It sounds like we haven't landed on a straightforward solution that'll meet your needs nicely and right now most of our SDK development effort is going into the new Firestore SDKs rather than Realtime Database, so we're not able to invest in large or risky changes.

At this point if you can come up with a solution that works for you, you could consider working off a fork of the codebase.  For instance if you don't care about these writes being automatically stored in the offline cache, you could just make https://github.com/firebase/firebase-ios-sdk/blob/c6b4b03fffc3cea7c9525e5c79dce28f52900521/Firebase/Database/Persistence/FPersistenceManager.m#L123 into a no-op.  From my understanding, this would prevent the pruned queries and cache from growing.

Sorry I don't have a better answer right now.

**Comment by morganchen12** [comment] 2018-11-07 22:52
Closing due to inactivity.

**Closed by morganchen12** 2018-11-07 22:52 UTC
Labels: Database
