### ISSUE TITLE
crash linked to FPRNetworkTrace

### ISSUE THREAD

**Issue by bluelagon** [firebase/firebase-ios-sdk#6896] opened 2020-11-04 16:27 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version: 7.0.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component:  Analytics, Crashlytics, Performance

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I did not manage to reproduce the crash but as I looked around a little bit, I found that the crash occured when on another thread did some job related to Firebase. 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

<img width="1163" alt="Capture d’écran 2020-11-04 à 17 21 49" src="https://user-images.githubusercontent.com/32433902/98137917-d3277800-1ec2-11eb-9fe2-d65a7a1a9c7d.png">
<img width="540" alt="Capture d’écran 2020-11-04 à 17 20 05" src="https://user-images.githubusercontent.com/32433902/98137598-762bc200-1ec2-11eb-92c2-c1b77ff0b996.png">
<img width="544" alt="Capture d’écran 2020-11-04 à 17 20 34" src="https://user-images.githubusercontent.com/32433902/98137663-880d6500-1ec2-11eb-83db-0a910b07df6f.png">
<img width="531" alt="Capture d’écran 2020-11-04 à 17 21 00" src="https://user-images.githubusercontent.com/32433902/98137746-a1aeac80-1ec2-11eb-826d-720971554c8f.png">

**Comment by maksymmalyhin** [comment] 2020-11-04 16:41
It looks like a duplicate of #6734 from the first glance.

**Comment by visumickey** [comment] 2020-11-04 18:33
Looking at the crashing stack trace, this is a duplicate of #6734 .

**Closed by visumickey** 2020-11-04 18:33 UTC
Labels: api: performance

**Comment by bluelagon** [comment] 2020-11-05 18:07
Thanks @maksymmalyhin & @visumickey
