### ISSUE TITLE
Firestore - Crash at Launch / Migration? 

### ISSUE THREAD

**Issue by fishandphil** [firebase/firebase-ios-sdk#10045] opened 2022-07-27 17:04 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.x
  * Firebase SDK version: 9.3.0
  * Installation method: `Zip file`
  * Firebase Component: Auth, Core, Firestore, Messaging, Storage
  * Target platform(s): `iOS | Catalyst`

### [REQUIRED] Step 2: Describe the problem

We're discovering a high volume of the following crash at startup of our iOS product on iOS 15.X. Something related to a Firestore migration? This is happening in our TestFlight version. We're pretty scared to push this live now. 

Do you need anything else from our side to advice why this migration is happening and why this would be crashing / how can we prevent it?

Thank you very much 

#### Relevant Code:

`Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x9904c __exceptionPreprocess
1  libobjc.A.dylib                0x15f54 objc_exception_throw
2  Foundation                     0x130834 -[NSMutableDictionary(NSMutableDictionary) initWithContentsOfFile:]
3  iOSFramework             0xe21918 firebase::firestore::util::ObjcThrowHandler(firebase::firestore::util::ExceptionType, char const*, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
4  iOSFramework             0xe213c4 firebase::firestore::util::Throw(firebase::firestore::util::ExceptionType, char const*, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
5  iOSFramework             0xe6ee74 firebase::firestore::util::internal::FailAssertion(char const*, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*)
6  iOSFramework             0xe6ef04 firebase::firestore::util::internal::FailAssertion(char const*, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*)
7  iOSFramework             0xed3b28 firebase::firestore::model::Mutation::CalculateOverlayMutation(firebase::firestore::model::MutableDocument const&, absl::lts_20211102::optional<firebase::firestore::model::FieldMask> const&)
8  iOSFramework             0xeac428 firebase::firestore::local::LocalDocumentsView::RecalculateAndSaveOverlays(std::__1::unordered_map<firebase::firestore::model::DocumentKey, firebase::firestore::model::MutableDocument*, firebase::firestore::model::DocumentKeyHash, std::__1::equal_to<firebase::firestore::model::DocumentKey>, std::__1::allocator<std::__1::pair<firebase::firestore::model::DocumentKey const, firebase::firestore::model::MutableDocument*> > >&&)
9  iOSFramework             0xeacba8 firebase::firestore::local::LocalDocumentsView::RecalculateAndSaveOverlays(firebase::firestore::immutable::SortedSet<firebase::firestore::model::DocumentKey, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> > const&)
10 iOSFramework             0xe98d8c std::__1::__function::__func<firebase::firestore::local::LevelDbOverlayMigrationManager::Run()::$_0, std::__1::allocator<firebase::firestore::local::LevelDbOverlayMigrationManager::Run()::$_0>, void ()>::operator()()
11 iOSFramework             0xe9cbbc firebase::firestore::local::LevelDbPersistence::RunInternal(absl::lts_20211102::string_view, std::__1::function<void ()>)
12 iOSFramework             0xe98754 firebase::firestore::local::LevelDbOverlayMigrationManager::Run()
13 iOSFramework             0xeb25d8 firebase::firestore::local::LocalStore::Start()
14 iOSFramework             0xe3c4ec firebase::firestore::core::FirestoreClient::Initialize(firebase::firestore::credentials::User const&, firebase::firestore::api::Settings const&)
15 iOSFramework             0xde1890 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&)
16 iOSFramework             0xf19340 firebase::firestore::util::Task::ExecuteAndRelease()
17 libdispatch.dylib              0x4660 _dispatch_client_callout
18 libdispatch.dylib              0xbde4 _dispatch_lane_serial_drain
19 libdispatch.dylib              0xc958 _dispatch_lane_invoke
20 libdispatch.dylib              0x171a8 _dispatch_workloop_worker_thread
21 libsystem_pthread.dylib        0x10f4 _pthread_wqthread
22 libsystem_pthread.dylib        0xe94 start_wqthread`

**Comment by MarkDuckworth** [comment] 2022-07-27 19:33
Hi @fishandphil, this appears to be a duplicate of #9985.

My understanding is that the issue was released in version 9.1.0 and will be fixed in the 9.4.0 release (around Aug 2). The fix is in the master branch, so if you need it sooner, then you can try to build your app from there.

**Closed by MarkDuckworth** 2022-07-27 19:33 UTC
Labels: api: firestore

**Comment by fishandphil** [comment] 2022-07-28 09:27
Thank you! sounds good. we'll wait for the update before releasing.

**Comment by fishandphil** [comment] 2022-08-04 17:25
Hi @MarkDuckworth 

From your message, we're on hold for the 9.4.0 released which you forecasted for august 2nd. Do you have an updated date for us? 

Thank you very much

**Comment by paulb777** [comment] 2022-08-04 17:32
9.4.0 released on Tuesday. Looks likes only the release notes are delayed.
