### ISSUE TITLE
configuring Firebase using FirebaseOptions(googleAppID:gcmSenderID:) produces   "Could not locate configuration file" and "Google App ID from GoogleService-Info.plist is empty" warnings

### ISSUE THREAD

**Issue by arielelkin** [firebase/firebase-ios-sdk#9201] opened 2022-01-12 16:14 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 8.10.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytiics
  * Target platform(s): `macOS`

### [REQUIRED] Step 2: Describe the problem

I configure `FirebaseApp` using `FirebaseOptions(googleAppID:gcmSenderID:)`:

```swift
        let fileopts = FirebaseOptions(googleAppID: "myAppID", gcmSenderID: "gcmSenderID")
        fileopts.apiKey = "myAPIKey"
        fileopts.projectID = "myProjectID"

        FirebaseCore.FirebaseApp.configure(options: fileopts)
```

 the following log is produced:

```
MyApp[44589:741323] 8.10.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
MyApp[44589:741321] 8.10.0 - [Firebase/Analytics][I-ACS020006] Google App ID from GoogleService-Info.plist is empty. Please, define GOOGLE_APP_ID in GoogleService-Info.plist for Analytics to work reliably. See https://goo.gl/txkZbE
MyApp[44589:741321] 8.10.0 - [Firebase/Analytics][I-ACS025020] Analytics requires Google App ID from GoogleService-Info.plist. Your data may be lost. Google App ID has been changed. Original, new ID: (nil), myAppIDxxxxxxxxxxxxx
MyApp[44589:741267] [Firebase/Crashlytics] Version 8.10.0
MyApp[44589:741325] [Metadata] unable to get a dev_t for store 1795162160.
MyApp[44589:741324] [logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
MyApp[44589:741324] [logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
MyApp[44589:741323] 8.10.0 - [Firebase/Analytics][I-ACS023007] Analytics v.8.10.0 started
```

I wouldn't expect Firebase to complain about locating its config file and reading values from it if I'm using `FirebaseOptions(googleAppID:gcmSenderID:)`

**Comment by ryanwilson** [comment] 2022-01-12 16:28
Thanks for the report and sorry for the troubles you're running into. This is a duplicate of #230. Unfortunately I don't have any updates to share related to it. Currently Analytics requires a static `GoogleService-Info.plist` to function properly.

**Comment by arielelkin** [comment] 2022-01-12 16:30
@ryanwilson does this mean that configuring `FirebaseApp` using `FirebaseOptions(googleAppID:gcmSenderID:):` has no effect?

**Comment by ryanwilson** [comment] 2022-01-12 16:36
For all other products, it works as expected. Analytics expects a static `GoogleService-Info.plist` file, so it may not work as expected. cc @htcgh

**Comment by arielelkin** [comment] 2022-01-13 09:12
@ryanwilson understood, in which case the documentation for `FirebaseOptions(googleAppID:gcmSenderID:):` should be updated to that effect.

**Comment by paulb777** [comment] 2022-01-13 17:32
Thanks @arielelkin I'll reopen to track updating the documentation.

**Closed** 2022-01-13 23:07 UTC
Labels: api: core, Docs
