### ISSUE TITLE
Firebase storage error 1200 over wifi only, LTE works perfectly

### ISSUE THREAD

**Issue by tennydesign** [firebase/firebase-ios-sdk#4950] opened 2020-02-21 08:00 UTC
This error started to pop this week. It is really weird. Code is just a simple putdata on Firebase Storage to save an image. (Swift 5 // XCode 11.3.1)

  * Xcode version: 11.3.1
  * Firebase SDK version: 3.5.0
  * Firebase Component: Storage 
  * Installation method: `CocoaPods 

```
    storageRef.putData(profileImageData, metadata: nil, completion: { (metadata, error) in
        if error != nil {
            print(error!)
            completion?(nil)
            return
        }
        storageRef.downloadURL(completion: { (url, error) in
            if error != nil {
                print(error!)
                completion?(nil)
                return
            }
            completion?(url?.absoluteString)
        })
    })
```

Then what I get back over LTE is: Success. What I get back over my home Wifi (xfinity-USA) is:

> 2020-02-16 13:44:49.944697-0800 persona[17889:5050090] Task <0E3D8C0D-6B4C-43CF-B897-E549E8D5301E>.<2> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made.

**Comment by morganchen12** [comment] 2020-02-21 08:09
Duplicate of #4913. Please follow the issue there.

**Closed by morganchen12** 2020-02-21 08:09 UTC
Labels: api: storage, needs-triage
