### ISSUE TITLE
Unable to upload to ASC with SPM - Error ITMS-90171: "Invalid Bundle Structure"

### ISSUE THREAD

**Issue by deanPGM** [firebase/firebase-ios-sdk#6409] opened 2020-09-07 09:55 UTC
* Xcode version: `12.0 beta 6 (12A8189n)`
  * Firebase SDK version: `6.32-spm-beta`
  * Firebase Component: `FirebaseAnalytics, FirebaseCrashlytics`
  * Component version: `6.32.0`
  * Installation method: `Swift Package Manager`

### [REQUIRED] Step 2: Describe the problem

I have added Firebase to an existing iOS project and attempted to upload to App Store Connect. During the upload phase, the binary is rejected due to the following errors:

![firebase-error](https://user-images.githubusercontent.com/2019053/92374139-3e3d1400-f0f7-11ea-9ee7-1be4584c7e93.png)

It looks like the binaries (`.framework`?) of `FIRAnalyticsConnector`, `GoogleAppMeasurement` & `FirebaseAnalytics` are potentially being incorrectly added to the application? 

![firebase-error2](https://user-images.githubusercontent.com/2019053/92375094-8b6db580-f0f8-11ea-97d2-3910b2de4d39.png)

#### Steps to reproduce:

* Followed instructions to integrate Firebase with SPM
* Attempt to upload project to App Store Connect for use on Testflight
* Binary is rejected from App Store Connect with errors.

**Comment by paulb777** [comment] 2020-09-07 14:13
This is likely a duplicate of #6360. Are you able to run on a device?  We're still looking for how to reproduce.

**Comment by deanPGM** [comment] 2020-09-07 14:31
Thanks for the quick reply. 

Yes, it runs on device fine, and I'm seeing the expected output in the Firebase console.

I'll experiment and see if I can reproduce in a blank project.

**Comment by deanPGM** [comment] 2020-09-07 23:45
I have integrated Firebase with a different project of mine, and can't reproduce. I'll investigate further and see what it is about this particular project that caused it.

**Comment by ryanwilson** [comment] 2020-09-08 13:23
One thing to check: are those libraries somehow added to the "Copy Bundle Resources" build setting? Seen by clicking your project name in the Xcode navigator, your app's target name, then clicking "Build Phases". That seems to be a common issue when getting that error message, although I'm not sure how they would have ended up there.

**Comment by deanPGM** [comment] 2020-09-08 13:30
Hi @ryanwilson - I can confirm they are not part of the "Copy Bundle Resources" phase, one of the first things I checked.

**Comment by paulb777** [comment] 2020-09-08 21:39
It looks like you've covered these - but just in case, see the answers at https://stackoverflow.com/questions/28621297/iphone-app-submitting-error-itms-90171-invalid-bundle-structure-cant-contain

**Comment by deanPGM** [comment] 2020-09-10 09:59
> It looks like you've covered these - but just in case, see the answers at https://stackoverflow.com/questions/28621297/iphone-app-submitting-error-itms-90171-invalid-bundle-structure-cant-contain

Thanks Paul. That link didn't have any advice that worked I'm afraid. In the meantime, I've integrated Firebase directly using the community catalyst builds which work fine for now. 

If it's any help to you or your team, I can share the private repo with you?

**Comment by ryanwilson** [comment] 2020-09-10 20:29
@deanPGM sure thing, you can email firebase-ios-github-6409 AT google DOT com (with the actual at sign and period, obviously) and the only people who have access is myself and @paulb777. That'd be greatly appreciated!

**Comment by paulb777** [comment] 2020-09-11 20:13
It's possible that updating and the #6360 [solution](https://github.com/firebase/firebase-ios-sdk/issues/6360#issuecomment-691271702) might solve this as well.

**Closed** 2020-09-25 01:04 UTC
Labels: Swift Package Manager, api: analytics, beta-software, needs-info, no-recent-activity
