### ISSUE TITLE
UI Tests no longer run after Firebase/Core pod install

### ISSUE THREAD

**Issue by MrAPolk** [firebase/firebase-ios-sdk#2147] opened 2018-12-05 09:31 UTC
### Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.13.0
  * Firebase Component: Core
  * Component version: 5.13.0
  * CocoaPods: 1.5.3

### Describe the problem

When I installed the Firebase Core pod and try and run my test target it runs my unit tests correctly buy fails to launch my UI tests giving the following error:

`BrokenFirebaseCoreUITests-Runner.app (80714) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: The test runner failed to load the test bundle. Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch.))`

I've noticed a few similar issue on [here](https://github.com/CocoaPods/CocoaPods/issues/6891) but none specifically mention just the UI Test target failing.

#### Steps to reproduce:

I've attached a test project that replicates the issue. Simply run the test target (CMD+U) to see the error.

[BrokenFirebaseCore.zip](https://github.com/firebase/firebase-ios-sdk/files/2648116/BrokenFirebaseCore.zip)

#### Relevant Code:

I found one workaround solutions which is to add `$(FRAMEWORK_SEARCH_PATHS)` to the UI Test target's Runpath search paths.

Is this workaround recommended?

**Comment by ryanwilson** [comment] 2018-12-05 13:08
Thanks for the report, and producing a repro! We can take a look today to see if this is expected or not. 

Also, thanks for adding the workaround! It doesn't sound unreasonable that it could be expected to include that, but it looks like the `inherit! :search_paths` is added appropriately in the Podfile.

Will update this issue when we figure things out.

**Comment by code-surf** [comment] 2018-12-05 14:56
Hi, this might be related to the issue I found:
https://github.com/firebase/firebase-ios-sdk/issues/2151

**Comment by paulb777** [comment] 2018-12-05 15:35
@MrAPolk Thanks for the report and great minimal, reproducible example.

This issue seems to be a CocoaPods bug and discussed at https://stackoverflow.com/questions/34990175/test-target-x-encountered-an-error-early-unexpected-exit-operation-never-finis.

Your workaround is the most popular answer.  I also verified that hujunfeng's answer of un-nesting the test target also works.

@code-surf - Thanks but doesn't seem related to #2151 since the pod version mismatch doesn't occur here.

I'm going to close the issue here since there are workarounds and this is likely a CocoaPods issue. The next step would be creating an issue on the [CocoaPods repo](https://github.com/CocoaPods/CocoaPods/issues).

**Closed by paulb777** 2018-12-05 15:35 UTC
Labels: Core

**Comment by paulb777** [comment] 2018-12-05 16:22
No difference with the latest CocoaPods 1.6.0.
