### ISSUE TITLE
Symbol not found: _objc_opt_respondsToSelector

### ISSUE THREAD

**Issue by jostster** [firebase/firebase-ios-sdk#7304] opened 2021-01-14 20:33 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Instance, Core, Database, Messaging, Storage, Crashlytics)

### [REQUIRED] Step 2: Describe the problem
When running crashlytics on watchOS 5.0 it crashes with `Symbol not found: _objc_opt_respondsToSelector` even though the selector should exist. While Crashlytics is only supported for watchOS 6.0, if an application also supports 5.0, all 5.0 devices will get this crash.

#### Steps to reproduce:

What happened? How can we make the problem occur?
Run the crashlytics test watchos application on a 5.3 simulator

#### Relevant Code:
Even with checks in place to not run the Firebase configureApp call, the mach-o load will still run all `+(void)load` calls which trigger this error.

#### Fix:
Wrap the `+(void)load` in checks to make sure it is only running on the min version or greater.

**Comment by paulb777** [comment] 2021-01-15 15:18
@jostster Thanks for the issue and PR. This approach doesn't seem right to me, however.   The Package.swift specifies the minimum versions [here](https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift#L29) and that should prevent the installation for any apps that require watchOS 5.  

As described, this sounds like a Swift Package Manager issue, and I don't think we should change the Firebase sources for it.

**Comment by jostster** [comment] 2021-01-15 15:55
Hello @paulb777,
I have a test project that uses cocoapods version and am able to replicate this with cocoapods as well

**Comment by paulb777** [comment] 2021-01-15 23:05
Hmm, watchOS must handle versioning differently than other platforms which don't allow apps with a higher minimum version to be installed. 

It seems that if that's the case, we should assert in one place in FirebaseCore since there could be other issues with watchOS 6 APIs not supported that were assumed by the build system.

Are you able to share a reproducible example?

**Comment by jostster** [comment] 2021-01-15 23:10
Attached is my test ios app with a watchos extension. I have removed the GoogleInfo.plist file.
[watch-crashlytics copy.zip](https://github.com/firebase/firebase-ios-sdk/files/5823333/watch-crashlytics.copy.zip)

**Comment by paulb777** [comment] 2021-01-16 00:23
Thanks! I've reproduced it. I still think this is an Xcode watchOS bug and will chat with more of the team next week to get additional input on the right approach.

**Comment by paulb777** [comment] 2021-01-19 17:09
Since this is likely an Xcode bug, It could be worth investigating how other watchOS SDKs address the issue of allowing libraries built for watchOS 6 to run on watchOS 5.

Either way, we can't accept the changes in #7305 since they are very likely covering up obvious crashes in favor of more subtle ones.

**Comment by elenadoty** [comment] 2021-02-09 18:00
Closing this issue as it does not seem that we can address it.

**Closed by elenadoty** 2021-02-09 18:00 UTC
Labels: api: crashlytics, watchOS
