### ISSUE TITLE
Crash -[FPRRemoteConfigFlags sessionSamplingRate], [FIRRemoteConfig configValueForKey:namespace:]

### ISSUE THREAD

**Issue by gusrota** [firebase/firebase-ios-sdk#3343] opened 2019-07-12 10:38 UTC
### SDK Versions
  * Xcode version: 10.2
  *Firebase version:
Firebase 6.3.0
FirebaseABTesting 3.0.0
FirebaseAnalytics 6.0.2
FirebaseCore 6.0.3
FirebaseInstanceID 4.2.0
FirebasePerformance 3.1.0
FirebaseRemoteConfig 4.1.0
GTMSessionFetcher 1.2.2
GoogleAppMeasurement 6.0.2
GoogleToolboxForMac 2.2.1
GoogleUtilities 6.2.1
Fabric 1.10.2

### Description
Couple of days ago released new version of app to App Store with updated Firebase SDK's (see version above). About 33 crashes a day reported for  -[FPRRemoteConfigFlags sessionSamplingRate] & [FIRRemoteConfig configValueForKey:namespace:]. I have not been able to replicate crash so sorry cannot provide crash data. The data I have from Crashlytics itself:

Crash only reported on iOS13
Issue is happening on multiple devices for different users 

### -[FPRRemoteConfigFlags sessionSamplingRate]

**key**
crash_info_entry_0
BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread

```
Crashed: com.google.GoogleConfigService.FIRRemoteConfig
0  libdispatch.dylib              0x1c269fbd8 __DISPATCH_WAIT_FOR_QUEUE__ + 452
1  ???                            0x52686201c269f800 (Missing)
2  ???                            0x0 (Missing)
3  APPNAME                      0x104eafd74 -[FPRRemoteConfigFlags sessionSamplingRate] + 4339219828
4  APPNAME                      0x104eaf408 -[FPRConfigurations sessionsSamplingPercentage] + 4339217416
5  APPNAME                      0x104ea8e80 -[FPRSessionManager isGaugeCollectionEnabledForSessionId:] + 4339191424
6  APPNAME                      0x104ea8d08 -[FPRSessionManager updateSessionId:] + 4339191048
7  APPNAME                      0x104ea8a28 -[FPRSessionManager initWithNotificationCenter:] + 4339190312
8  APPNAME                      0x104ea8984 __35+[FPRSessionManager sharedInstance]_block_invoke + 4339190148
9  libdispatch.dylib              0x1c269310c _dispatch_client_callout + 20
10 ???                            0x0 (Missing)
11 ???                            0x0 (Missing)
12 APPNAME                      0x104eba838 -[FPRNetworkTrace start] + 4339263544
13 APPNAME                      0x104ec182c __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 4339292204
14 APPNAME                      0x104ec17a8 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 4339292072
15 APPNAME                      0x104e98c70 -[FIRInstanceIDCheckinService checkinWithExistingCheckin:completion:] + 189 (FIRInstanceIDCheckinService.m:189)
16 APPNAME                      0x104e963b4 -[FIRInstanceIDAuthService fetchCheckinInfoWithHandler:] + 188 (FIRInstanceIDAuthService.m:188)
17 APPNAME                      0x104e8f6b8 -[FIRInstanceID tokenWithAuthorizedEntity:scope:options:handler:] + 368 (FIRInstanceID.m:368)
18 APPNAME                      0x104f439b8 -[RCNConfigFetch refreshInstanceIDTokenAndFetchCheckInInfoWithCompletionHandler:] + 4339825080
19 APPNAME                      0x104f43584 __74-[RCNConfigFetch fetchAllConfigsWithExpirationDuration:completionHandler:]_block_invoke + 4339824004
20 libdispatch.dylib              0x1c2691cb0 _dispatch_call_block_and_release + 32
21 ???                            0x41557081c2693000 (Missing)
22 ???                            0x772dd301c2699400 (Missing)
23 ???                            0x7524ba01c269a000 (Missing)
24 ???                            0x477efd01c26a3000 (Missing)
25 ???                            0x0 (Missing)
26 ???                            0x3a05cd01c26fec00 (Missing)
```

### -[FIRRemoteConfig configValueForKey:namespace:]

**key**
crash_info_entry_0
BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread
```
Crashed: com.google.GoogleConfigService.FIRRemoteConfig
0  libdispatch.dylib              0x1a3a7bf70 __DISPATCH_WAIT_FOR_QUEUE__ + 440
1  libdispatch.dylib              0x1a3a7bb18 _dispatch_sync_f_slow + 140
2  APPNAME                      0x1008c9404 -[FIRRemoteConfig configValueForKey:namespace:] + 4378252292
3  APPNAME                      0x100843d74 -[FPRRemoteConfigFlags sessionSamplingRate] + 4377705844
4  APPNAME                      0x100843408 -[FPRConfigurations sessionsSamplingPercentage] + 4377703432
5  APPNAME                      0x10083ce80 -[FPRSessionManager isGaugeCollectionEnabledForSessionId:] + 4377677440
6  APPNAME                      0x10083cd08 -[FPRSessionManager updateSessionId:] + 4377677064
7  APPNAME                      0x10083ca28 -[FPRSessionManager initWithNotificationCenter:] + 4377676328
8  APPNAME                      0x10083c984 __35+[FPRSessionManager sharedInstance]_block_invoke + 4377676164
9  libdispatch.dylib              0x1a3ac91ec _dispatch_client_callout + 16
10 libdispatch.dylib              0x1a3a709d0 _dispatch_once_callout + 28
11 APPNAME                      0x10083c928 +[FPRSessionManager sharedInstance] + 4377676072
12 APPNAME                      0x10084e838 -[FPRNetworkTrace start] + 4377749560
13 APPNAME                      0x10085582c __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 4377778220
14 APPNAME                      0x1008557a8 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke + 4377778088
15 APPNAME                      0x10082cc70 -[FIRInstanceIDCheckinService checkinWithExistingCheckin:completion:] + 189 (FIRInstanceIDCheckinService.m:189)
16 APPNAME                      0x10082a3b4 -[FIRInstanceIDAuthService fetchCheckinInfoWithHandler:] + 188 (FIRInstanceIDAuthService.m:188)
17 APPNAME                      0x1008236b8 -[FIRInstanceID tokenWithAuthorizedEntity:scope:options:handler:] + 368 (FIRInstanceID.m:368)
18 APPNAME                      0x1008d79b8 -[RCNConfigFetch refreshInstanceIDTokenAndFetchCheckInInfoWithCompletionHandler:] + 4378311096
19 APPNAME                      0x1008d7584 __74-[RCNConfigFetch fetchAllConfigsWithExpirationDuration:completionHandler:]_block_invoke + 4378310020
20 libdispatch.dylib              0x1a3ac8678 _dispatch_call_block_and_release + 24
21 libdispatch.dylib              0x1a3ac91ec _dispatch_client_callout + 16
22 libdispatch.dylib              0x1a3a75430 _dispatch_lane_serial_drain$VARIANT$mp + 608
23 libdispatch.dylib              0x1a3a75e24 _dispatch_lane_invoke$VARIANT$mp + 420
24 libdispatch.dylib              0x1a3a7f35c _dispatch_workloop_worker_thread + 588
25 libsystem_pthread.dylib        0x1a3b18f5c _pthread_wqthread + 304
26 libsystem_pthread.dylib        0x1a3b1baa0 start_wqthread + 8
```

**Comment by paulb777** [comment] 2019-07-12 13:50
This is a duplicate of #3270. Please update to Firebase 6.4.0 to resolve.

**Closed by paulb777** 2019-07-12 13:50 UTC
Labels: needs-triage

**Comment by gusrota** [comment] 2019-07-12 15:42
Thanks @paulb777 much appreciated. Had missed that issue.
