### ISSUE TITLE
Can't render SwiftUI canvas with Code Coverage Enabled

### ISSUE THREAD

**Issue by brandtdaniels** [firebase/firebase-ios-sdk#6219] opened 2020-08-06 20:58 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: ___11.6__
  * Firebase SDK version: _6.28____
  * Firebase Component: _Core____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: __6.9.1___
  * Installation method: `**CocoaPods** | Carthage | Zip file` (select one)

### [REQUIRED] Step 2: Describe the problem

Can't render SwiftUI canvas due to FirebaseCore

```
linker command failed with exit code 1 (use -v to see invocation)

----------------------------------------

LinkDylibError: Failed to build TemplateListView.swift

Linking failed: linker command failed with exit code 1 (use -v to see invocation)

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/SharedFrameworks-iphonesimulator'
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in FirebaseCore(FIRComponentType.o)
      ___llvm_profile_runtime_user in FirebaseCore(FIRConfiguration.o)
      ___llvm_profile_runtime_user in FirebaseCore(FIRDiagnosticsData.o)
      ___llvm_profile_runtime_user in FirebaseCore(FirebaseCore-dummy.o)
      ___llvm_profile_runtime_user in FirebaseCore(FIRAnalyticsConfiguration.o)
      ___llvm_profile_runtime_user in FirebaseCore(FIRBundleUtil.o)
      ___llvm_profile_runtime_user in FirebaseCore(FIRAppAssociationRegistration.o)
      ...
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Steps to reproduce:

Rendering SwiftUI Canvas. The current workaround is to disable code coverage in the build scheme

#### Relevant Code:

NA

**Comment by paulb777** [comment] 2020-08-08 01:07
A reproducible example would help us to diagnose

**Comment by brandtdaniels** [comment] 2020-08-10 18:16
Any SwiftUI examples seems to reproduce the issue. Here are some SO posts regarding the issue:

https://stackoverflow.com/questions/60440074/problems-with-firebase-and-swiftui-live-previews

This workaround worked my project:
https://stackoverflow.com/a/62355502/699002

**Comment by paulb777** [comment] 2020-08-10 21:47
I suspect that solving #2022 may resolve this.  Until then, the workarounds may be the best bet.

**Comment by paulb777** [comment] 2020-08-13 15:35
Also may be related this issue noted at https://forums.swift.org/t/swift-packages-in-multiple-targets-results-in-this-will-result-in-duplication-of-library-code-errors/34892/38:

`There is an entirely separate issue which happens only for Xcode previews which is related to all package products being built dynamically in Xcode 12 to enable previews. It is also something we're actively investigating. There is no workaround for this, since users do not have control over how builds for preview are being done.`

**Comment by ryanwilson** [comment] 2020-08-31 16:45
I was able to reproduce this issue and the workaround works for me as well.

Steps to reproduce:

1. Create a new SwiftUI iOS project in Xcode 12 b6. *Make sure to check the "Include Tests" box. Close the Xcode window.
2. `cd` into the directory, run `pod init`.
3. Add `pod 'FirebaseCore'` to the `Podfile`.
4. Run `pod update`.
5. Open the `.xcworkspace` generated from CocoaPods.
6. Edit the scheme of the main app: go to the "Test" section, Options, click the Code Coverage checkbox.
7. In `ContentView.swift`, add `import FirebaseCore` and replace the contents of `body` with:

```
var body: some View {
    Text("Hello, world!")
      .padding()
      .onAppear {
        // Use some arbitrary calls from `FirebaseCore`
        if let defaultApp = FirebaseApp.app() {
          print("Firebase configured! \(defaultApp.name)")
        } else {
          print("Firebase not configured.")
        }
      }
  }
```

8. Regenerate the SwiftUI Preview Canvas. Observe the failure.

**Comment by ryanwilson** [comment] 2020-08-31 16:48
@brandtdaniels hope you don't mind that I changed the title to make it easier to find for folks, and more accurately state the issue. Thanks again for the report.

**Comment by ryanwilson** [comment] 2020-11-06 18:17
TODO: Attempt to reproduce with Firebase 7, since dynamic frameworks are now used. Also check with Xcode 12.2 release candidate to see if the Xcode issue is resolved with static frameworks.

**Comment by brandtdaniels** [comment] 2020-12-10 22:27
Any updates on this?

**Comment by atereshkov** [comment] 2021-01-09 17:21
Same for me. Still an issue

**Comment by denisaionita** [comment] 2021-01-19 11:26
This is still an issue, it's most likely an Apple bug as I have found a few related issues on their forum, with weird workarounds(remove arm64 which was already done, validate workspace, set Build Active Architecture Only" to No and other such. Nothing worked or made sense for me and my project, and going through this thread I tried disabling the code coverage capability for my main scheme - and weirdly enough, that made the previews render.

**Comment by markst** [comment] 2021-02-17 06:42
Also an issue for me. Disabling the code coverage does not appear to resolve.

**Comment by tichise** [comment] 2021-03-26 07:11
I am now getting previews rendered with code coverage off.

**Comment by teh-nsd** [comment] 2021-04-14 10:50
I had the same issue with Canvas previews and can confirm that after I turned off Code coverage they now work.

**Comment by ryanwilson** [comment] 2021-04-26 15:10
TODO: Test this issue with Xcode 12.5 to see if it's resolved.

**Comment by ryanwilson** [comment] 2021-04-29 12:31
Hey everyone, I tested this with Xcode 12.5 with [my repro steps above](https://github.com/firebase/firebase-ios-sdk/issues/6219#issuecomment-683896871) and was unable to reproduce - I think this is resolved.

I'm going to close this now, but if you still see the same error using Xcode 12.5 please share steps to reproduce and I'll re-open the issue!

**Closed by ryanwilson** 2021-04-29 12:31 UTC
Labels: SwiftUI, api: core
