### ISSUE TITLE
Please support FirebaseUI in SPM

### ISSUE THREAD

**Issue by gallaugher** [firebase/firebase-ios-sdk#7824] opened 2021-04-02 14:21 UTC
### [READ] Guidelines

For large or ambiguous requests, such as significant breaking changes or use
cases that could be addressed by multiple different features, consider instead
starting a
[Pitch](https://github.com/firebase/firebase-ios-sdk/discussions/categories/pitches)
discussion for ideas that you'd like to discuss with the Firebase community to
flush out.

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: FirebaseUI support in SPM (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.
Hi!
My university iOS students at Boston College (alma mater of Marvin Chow + other leading Googlers), as well as anyone else using my textbook or YouTube videos, love using Firebase and Cloud Firestore. It's a required component of our class. We're switching to Swift Package Manager, but unfortunately FirebaseUI is not yet supported. Can you kindly add this to the list of Firebase packages so we can begin working with it? This is VERY much appreciated. Also - if you're short on interns for this, let me know & I'd be happy to pass on the word to my current & former students to help you bring on the updates & test things out.
Best wishes + thanks for considering escalating this. Lots of Cloud Firestore hackers are anxious to begin!
Prof. John Gallaugher - YouTube.com/profgallaugher - @gallaugher

**Comment by morganchen12** [comment] 2021-04-02 21:54
See https://github.com/firebase/FirebaseUI-iOS/issues/886 for previous discussion. SPM support for FirebaseUI is complete but untested, but should be usable for educational exercises. You'll have to use the `pb-spm` branch on the FirebaseUI repository for now; the changes should be merged to master (https://github.com/firebase/FirebaseUI-iOS/pull/942) soon.

**Comment by morganchen12** [comment] 2021-04-02 21:55
Closing as duplicate of https://github.com/firebase/FirebaseUI-iOS/issues/886

**Closed by morganchen12** 2021-04-02 21:55 UTC
Labels: Swift Package Manager, needs-triage, type: feature request

**Comment by gallaugher** [comment] 2021-04-06 19:23
Sorry if I'm missing something. I'm in the pb branch, see the URL as:
https://github.com/firebase/FirebaseUI-iOS/tree/pb-spm
but when I enter this in SPM I get the error:
"The remote repository could not be accessed: Make sure a valid repository exists at the specified location and that the correct credentials have been supplied." Is this the correct URL? Sorry if I've missed something basic.

**Comment by paulb777** [comment] 2021-04-06 20:15
The URL is https://github.com/firebase/FirebaseUI-iOS.git. The branch is pb-spm
