### ISSUE TITLE
Non-portable path warnings from Protobuf pod

### ISSUE THREAD

**Issue by OkiRules** [firebase/firebase-ios-sdk#2665] opened 2019-03-28 02:42 UTC
Please update for Swift 5 support.

Thanks!

**Comment by maksymmalyhin** [comment] 2019-03-28 14:11
@OkiRules Thank you for your request. For most of the components Swift 5 should be supported now. Would you be able to provide examples of the issues you have with Swift 5, please?

**Comment by OkiRules** [comment] 2019-03-29 09:23
<img width="266" alt="Screen Shot 2019-03-29 at 8 23 03 pm" src="https://user-images.githubusercontent.com/18746541/55222616-77b1f480-5260-11e9-966f-d5009e154574.png">

**Comment by paulb777** [comment] 2019-03-29 14:06
This is an Apple issue tracked at https://openradar.appspot.com/radar?id=6091887509241856. More discussion at https://github.com/protocolbuffers/protobuf/issues/3218.

We can investigate if we can find any better workarounds. In the meantime, it's safe to ignore the warnings.

**Comment by paulb777** [comment] 2019-03-29 14:10
I'm going to change the title since the issue is not related to Swift 5.

**Comment by paulb777** [comment] 2019-04-06 20:23
One workaround is adding `pod 'Protobuf', :inhibit_warnings => true` to the Podfile.

**Comment by paulb777** [comment] 2019-05-29 21:58
Sent https://github.com/protocolbuffers/protobuf/pull/6190

**Comment by iatman** [comment] 2019-08-04 03:25
It worked, it was enough to change the letter of the folder: Pods/Protobuf/objectivec/google/protobuf  (protobuf -> Protobuf)

**Comment by paulb777** [comment] 2019-08-06 15:45
protocolbuffers/protobuf#6464 in progress to fix

**Comment by devkokodev** [comment] 2019-08-08 08:50
I'm trying to install 'Firebase/Messaging' it install protobuf etc. I'm using swift 5, deployment ios 11 and i have this issues:
![Screen Shot 2019-08-08 at 10 44 49 AM](https://user-images.githubusercontent.com/53897025/62688744-beabb580-b9c9-11e9-857d-f881d86c1fe4.png)
![Screen Shot 2019-08-08 at 10 45 15 AM](https://user-images.githubusercontent.com/53897025/62688745-beabb580-b9c9-11e9-98c8-8709e84812cd.png)
![Screen Shot 2019-08-08 at 10 49 55 AM](https://user-images.githubusercontent.com/53897025/62689028-485b8300-b9ca-11e9-882c-f5ee776e80fa.png)


I've tried (cmd + shift + k) delete derived data, pod install, pod update, nothing solved this issue.
Any help?

**Comment by paulb777** [comment] 2019-08-08 14:26
@devkokodev That looks like a different issue. Perhaps, something in the configuration?  We'll likely need more information about reproducing to help. Please open another issue with that detail.

**Comment by BugsBunnyBR** [comment] 2019-08-12 19:33
So, now that the [PR](https://github.com/protocolbuffers/protobuf/pull/6464) in cocoapods is merged... all that is needed is to update the protobuf lib in this repository?
As far as I can tel https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMessaging.podspec#L52 is the current version, right? As the version differences are not so small, I image it should be with care. @paulb777 this is something in your radar, right?

**Comment by paulb777** [comment] 2019-08-12 19:45
@BugsBunnyBR A new Protobuf version with that [PR](https://github.com/protocolbuffers/protobuf/pull/6464) needs to be published to [CocoaPods](https://cocoapods.org/pods/Protobuf). Please enquire in the [Protobuf repo](https://github.com/protocolbuffers/protobuf/pull/6464) about their release plans.  Firebase will automatically pick up a subsequent Protobuf minor release on a `pod update`.

**Comment by BugsBunnyBR** [comment] 2019-08-12 20:02
I thought is was in this release https://github.com/protocolbuffers/protobuf/releases/tag/v3.9.1, but is looks like it is not here yet. Sorry for the misunderstanding.

**Comment by psyduck-scar4** [comment] 2019-08-17 13:37
> [protocolbuffers/protobuf#6464](https://github.com/protocolbuffers/protobuf/pull/6464) in progress to fix

Thank You!! this worked

**Comment by psyduck-scar4** [comment] 2019-08-17 13:37
> It worked, it was enough to change the letter of the folder: Pods/Protobuf/objectivec/google/protobuf (protobuf -> Protobuf)

thank you!!! this fixed it.

**Comment by navingp** [comment] 2019-08-24 09:06
@OkiRules did you resolved this **"Non-portable path warnings from Protobuf pod."**
your help is much appreciated.

**Comment by OkiRules** [comment] 2019-08-24 10:39
Not yet as the new build has not been updated for Cocoapods but when it is will inform you.

**Comment by navingp** [comment] 2019-08-25 05:33
@OkiRules Thanks for the quick reply..

**Comment by BugsBunnyBR** [comment] 2019-09-24 12:29
I think protocolbuffers released a version with the fix
https://github.com/protocolbuffers/protobuf/releases

Can someone take a look at the update process ?

**Comment by paulb777** [comment] 2019-09-24 13:44
@BugsBunnyBR The fix won't come until Protocol buffers releases 3.10.0.  3.9.2 was a single patch to 3.9.0 fix a crash issue (#3851).

**Comment by BugsBunnyBR** [comment] 2019-09-24 17:19
Ohh... I looked for the 6464 PR merge tag and it was in a release... but it was  for version for 3.10 **RC1**, I should more attention.

**Comment by paulb777** [comment] 2019-10-03 14:59
Protobuf 3.10.0 has been published to CocoaPods. Doing some additional Firebase integration testing today.

**Closed** 2019-10-04 14:53 UTC
Labels: api: firestore, api: messaging, type: bug
