### ISSUE TITLE
Crash on SetData, UpdateData, DeleteData in Firestore

### ISSUE THREAD

**Issue by Sunrise17** [firebase/firebase-ios-sdk#6065] opened 2020-07-17 05:48 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.27.0
  * Firebase Component: Firestore (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 1.16.0
  * Installation method: `CocoaPods` (select one)

#### Steps to reproduce:

I have received following crash reports during setting, updating, deleting data and adding Listener to Firestore. As i have checked the release notes that Listener issue has been solved in 6.28.1 version but, i am asking that all other problems are already being solved in that version. You can find crash reports as follows.

Setting Data;
<img width="1211" alt="SetData" src="https://user-images.githubusercontent.com/26038249/87752582-613efc00-c809-11ea-9e52-45a1bd19acb9.png">

Deleting Data;
<img width="1203" alt="DeleteData" src="https://user-images.githubusercontent.com/26038249/87752640-7caa0700-c809-11ea-922f-292f977276fd.png">

Updating Data;
<img width="1203" alt="UpdateData" src="https://user-images.githubusercontent.com/26038249/87752662-87649c00-c809-11ea-9cb0-78ff2cdea0c6.png">

Adding Listener;
<img width="1197" alt="AddListener" src="https://user-images.githubusercontent.com/26038249/87752669-90556d80-c809-11ea-8d90-66cf1b67b06a.png">

#### Relevant Code:
```
// TODO(you): code here to reproduce the problem
```

**Comment by morganchen12** [comment] 2020-07-17 16:11
Based on the stack traces, Firestore is behaving as expected and something is causing a crash in your app code in Firestore's callback handlers. Also, it looks like the callbacks are executing on the main thread as expected for Firebase 6.27.0, so it's likely not caused by the bug that was fixed in 6.28.1. Can you get the exception messages for these crashes?

**Comment by Sunrise17** [comment] 2020-07-17 16:14
@morganchen12 , as soon as i have updated to 6.28.1, i will check whether exceptions will be occured.

**Closed** 2020-07-31 01:03 UTC
Labels: api: firestore, closed-by-bot, needs-info, no-recent-activity
