### ISSUE TITLE
Swift Unit Tests fail to run after adding Firebase to the project.

### ISSUE THREAD

**Issue by EmperiorEric** [firebase/firebase-ios-sdk#1172] opened 2018-04-24 13:08 UTC
* Xcode version: 9.3 (9E145)
  * Firebase SDK version: latest (4.x)
  * Firebase Component: Remote Config and Core
  * Component version: latest

### [REQUIRED] Step 3: Describe the problem

Same as #58, the Firebase module is expected for Tests but isn't included. No Tests depend on the module. Also tracked in Cocoapods here https://github.com/CocoaPods/CocoaPods/issues/6891

We have a handful of other Pods like Realm, Crashlytics, etc. Those have been functioning fine with the same basic podfile setup. So while it feels like a Cocoapod's issue, its unique to Firebase for some reason.

#### Steps to reproduce:

I added Firebase to our Podfile, setup Firebase configure and a remote config test with a string value. Firebase worked as expected. Then after pushing CI noted the tests failed to build because of a missing Firebase dependency. Verified locally and received the same error listed in #58. Its unclear if this is a Firebase or Cocoapods issue so I am alerting both parties.

```
pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'
```

#### Steps tried
We were using Cocoapods 1.4.0 at the time. I updated to 1.5.0 and updated the project, but that did not solve the problem.

The workaround adding `${PODS_ROOT}/Firebase/Core/Sources` to our test target Header Search Paths did work.

**Comment by paulb777** [comment] 2018-04-24 13:33
Thanks for the report @EmperiorEric. Are you able to share a reproducible test case? We're likely to need that to make progress on this issue.

The other route would be trying the CocoaPods master branch since there have been some related changes for 1.5.1 and 1.6.0.

**Comment by paulb777** [comment] 2018-05-04 13:48
Closing for now. Will reopen with a repro case.

**Closed by paulb777** 2018-05-04 13:48 UTC
