### ISSUE TITLE
Mac App was upgraded from Fabric to FirebaseCashkit, but a problem was found with accessing individual private folders on the new Mac system (10.15.5)! Unable to receive report when user denied access!!

### ISSUE THREAD

**Issue by dinglingui** [firebase/firebase-ios-sdk#6141] opened 2020-07-28 02:36 UTC
* Xcode version: 11.6
  * Firebase Component: FirebaseCrashlytics
  * Installation method: Carthage（Github packs it himself）

The Mac application of the company's project also upgraded to FirebaseCashkit through Fabric, but a problem was found. In the new Mac system (10.15.5), a "yes" file would pop up every time it started and could not be opened. After clicking the "OK" button, a prompt for applying for permission to access the private folder would pop up! Sandbox mechanism was used in the project! (Attached is the screenshot!) Thanks again for your help! ! On the 10.15 system, access to folders is more restricted. I would like to confirm that your company has considered the user's privacy! Attached is the screenshot!

<img width="1234" alt="??2020-07-16 ??4 56 50" src="https://user-images.githubusercontent.com/15205170/88612414-bc9ca400-d0bd-11ea-8576-dc76cf40402f.png">
<img width="587" alt="??2020-07-17 ??3 06 41" src="https://user-images.githubusercontent.com/15205170/88612415-bdcdd100-d0bd-11ea-8544-fee286000915.png">
<img width="1235" alt="??2020-07-16 ??3 26 37" src="https://user-images.githubusercontent.com/15205170/88612394-b3133c00-d0bd-11ea-803f-40d8c149af9b.png">

**Comment by maksymmalyhin** [comment] 2020-07-28 13:51
@dinglingui Thank you for the report. The popup from the last screenshot looks very similar to the #5540. Could you please answer the questions from the [comment](https://github.com/firebase/firebase-ios-sdk/issues/5540#issuecomment-625279873) to get better understanding of your case.

I'm not sure about the popup on the first screenshot, I'm sorry, but I cannot read this language. Would it be possible to post the alert message English translation or just the text as is?

**Comment by morganchen12** [comment] 2020-07-28 16:45
@maksymmalyhin the popups, from top to bottom, are:

```
Unable to open the document "YES". The document does not exist.
```

```
AppName wants to use the secret stored in com.firebase.FIRInstallations.

The authenticity of AppName could not be verified. If you would like to provide access, enter your login password.
```

The second popup is a duplicate of ##5540.

I'm not sure what is causing the first popup. @dinglingui can you provide a sample project that reproduces this popup?

**Comment by dinglingui** [comment] 2020-08-03 05:47
> @dinglingui Thank you for the report. The popup from the last screenshot looks very similar to the #5540. Could you please answer the questions from the [comment](https://github.com/firebase/firebase-ios-sdk/issues/5540#issuecomment-625279873) to get better understanding of your case.
> 
> I'm not sure about the popup on the first screenshot, I'm sorry, but I cannot read this language. Would it be possible to post the alert message English translation or just the text as is?

Hello, I'm sorry I didn't pay attention to the language part! I put screenshots on Dropbox! See if you can read it?（https://www.dropbox.com/sh/gd8son31miqw2v0/AABzeQcWXbjLZm9hT3j5ypePa?dl=0）

**Comment by dinglingui** [comment] 2020-08-03 06:39
Hi @maksymmalyhin, thanks for the information.

**Comment by dinglingui** [comment] 2020-08-03 06:39
Hi @maksymmalyhin, thanks for the information.

**Comment by dinglingui** [comment] 2020-08-03 06:43
Hi @maksymmalyhin, thanks for the information.
In my opinion, when The Fabric framework was used in the past, this kind of prompt did not pop up. In my opinion, it is unreasonable to pop up this kind of prompt inexplicably, which will not be allowed for many operation users! Same problem with [#5540](https://github.com/firebase/firebase-ios-sdk/issues/5540) feedback

**Comment by ryanwilson** [comment] 2021-01-25 17:03
Hi @dinglingui, is this still an issue for you?

**Closed** 2021-02-08 02:03 UTC
Labels: api: crashlytics, api: installations, macOS, needs-info, no-recent-activity
