### ISSUE TITLE
Password reset email does not contain the isi param

### ISSUE THREAD

**Issue by rahulserver** [firebase/firebase-ios-sdk#4884] opened 2020-02-11 12:06 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1 (11C504)
  * Firebase SDK version:  FirebaseCore (6.6.1)
  * Firebase Component: Auth (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version:  6.4.3
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
The password reset email does not contain the isi parameter which means the link does not redirect to the app store page if app is not installed.
The code that does it is given below.
The generated link looks like this:
https://someonappsdev.page.link/?link=https://some-on-apps-534aa.firebaseapp.com/admin/auth/email?apiKey%3DAIzaSyCWf-pQkl9AkNAu9Xq6ZJ5qAVFkaNuYbxg%26mode%3DresetPassword%26oobCode%3DCL_7CReqRltXYiTIxmgBoq_V4z-wusnqOUEVDcfnv18AAAFvHuMoGg%26continueUrl%3Dhttps://some-on-apps-534aa.firebaseapp.com/admin/auth/email%26lang%3Dfr&apn=au.com.someonapps.app&amv&ibi=au.com.someonapps.driverApp&ifl=https://some-on-apps-534aa.firebaseapp.com/admin/auth/email?apiKey%3DAIzaSyCWf-pQkl9AkNAu9Xq6ZJ5qAVFkaNuYbxg%26mode%3DresetPassword%26oobCode%3DCL_7CReqRltXYiTIxmgBoq_V4z-wusnqOUEVDcfnv18AAAFvHuMoGg%26continueUrl%3Dhttps://some-on-apps-534aa.firebaseapp.com/admin/auth/email%26lang%3Dfr
(url is sanitised to rename few parts)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
self.firebaseAuth.useAppLanguage()
let actionCodeSettings = ActionCodeSettings()
actionCodeSettings.handleCodeInApp = true
actionCodeSettings.url = firebaseAppEmailDomain
actionCodeSettings.setIOSBundleID(Bundle.main.bundleIdentifier ?? "some.com.example.someApp")
actionCodeSettings.setAndroidPackageName("some.com.example.someApp", installIfNotAvailable: true, minimumVersion: nil)
self.firebaseAuth.sendPasswordReset(withEmail: email, actionCodeSettings: actionCodeSettings)
```
The screenshot of my firebase ios project is this:
![image](https://user-images.githubusercontent.com/5101740/74235392-e111e900-4cf4-11ea-9ba7-1202497c1873.png)

**Comment by rizafran** [comment] 2020-02-13 18:54
Thanks for reporting the issue, @rahulserver. I tried to replicate the issue on my end, and I can see that the isi parameter is not included in the URL. I also consulted this to the Auth team, and this is an intended behavior because isi is not required for reset password.

**Comment by OlivierVoyer** [comment] 2020-02-14 07:47
Hi @rizafran , I have the same issue as described by @rahulserver and the problem with that missing `isi` parameter in the generated URL is that the link is not opening the App Store page when clicked on a device with the app not being installed, instead it shows the Firebase Preview page. Note that when the app is there, it correctly opens the link inside the app. Do you have a solution for this? Thanks in advance

**Comment by morganchen12** [comment] 2020-02-17 20:01
@renkelvin looks like there's a behavior disparity between iOS and Android.

**Comment by rosalyntan** [comment] 2020-10-14 23:46
Closing this issue -- this is the intended behavior for iOS, and we do not have plans to support the `isi` param.

**Closed by rosalyntan** 2020-10-14 23:46 UTC
Labels: api: auth, type: feature request

**Comment by OlivierVoyer** [comment] 2020-10-15 06:16
A bit sad that the intended behavior for the reset password email handling would be to fail somehow when the app is not installed instead of gracefully redirect to the App Store app download page. Does that mean that developers have to create their own cloud callable, generate a dynamic link themselves with the correct redirections and target callable and then format an email to the user? Or is there any built-in way in Firebase that I am not aware of?
