### ISSUE TITLE
Firebase/Performance: unrealistic App Launch duration for "Unknown" connection type

### ISSUE THREAD

**Issue by nick130586** [firebase/firebase-ios-sdk#934] opened 2018-03-16 13:58 UTC
In some cases, device connection type is detected as "Unknown" for small percentage of users. App Launch Duration shows enormous numbers in such cases

![screen shot 2018-01-06 at 12 06 58 am](https://user-images.githubusercontent.com/168651/37524548-d622fab2-2932-11e8-8442-12ac98b67b89.png)
.

  * Xcode version: 9.x
  * iOS: 10, 11 
  * Firebase Component: Performance
  * Component version: 4.7

#### Steps to reproduce:

Unknown

**Comment by morganchen12** [comment] 2018-03-16 16:45
Filed b/75269150 internally, will keep this ticket updated.

**Comment by eshiehz** [comment] 2018-03-16 23:36
App start is measured from when the objc runtime initializes to the time the application is active.
https://firebase.google.com/docs/perf-mon/automatic#automatic_trace_definitions

There's a couple potential reasons for the long app start time:

1. Likely the user is backgrounding the app before it successfully becomes active.
2. "Unknown" connection indicates the devices doesn't have networking.  Verify your app doesn't have any blocking network calls in your app initialization.

**Comment by morganchen12** [comment] 2018-03-19 17:25
Closing as this seems to be intended behavior.

**Comment by eithan** [comment] 2018-03-19 21:06
Hi there, is there not a way to filter out timings in the case of a user backgrounding the app? It seems wrong to ever be recording timings like 7000 seconds. Unfortunately we even have a 90th percentile timing of 45000 seconds across all connection types. Can you consider reopening this and investigating a bit more if so? Thanks.

**Comment by eithan** [comment] 2018-07-09 16:01
Hello,
Curious if any progress has been made on this issue? In case it helps here is some data from the last 48 hours when looking at median timings by carrier:

Nextel (Telet) --> 6,180.97 s
Telemovil --> 4,252.30 s
T-Mobile/Mobimak --> 2,569.22 s
Swisscom --> 26,289.16 s
UNKNOWN [311530] --> 11,504.04 s
BSNL --> 66,080.97 s

**Comment by morganchen12** [comment] 2018-10-12 22:56
@visumickey

**Comment by morganchen12** [comment] 2018-11-07 23:06
@visumickey, can you take a look at this? It seems like it'd be best to just discard app launch traces if the user backgrounds mid-launch, since it just adds noise.

In the future we can revisit a way to include background-mid-launch traces in a less noisy way.

**Comment by nikodurand** [comment] 2019-09-23 08:04
Hi there,
we also have this issue, the problem is that we don't know which is the real performance of our application because 10% of sessions are not realistic. Very strange that it's not fixed, that's a real pain point for firebase on ios. Any fix to come ?

**Comment by visumickey** [comment] 2019-11-19 23:56
This seems to be an issue with the backgrounding enabled apps and Firebase Performance would be rolling out a fix for this to make sure the app start times are rightly calculated when launching the app from background. Expecting to roll this out in the next release. (Early december 2019)

**Comment by paulb777** [comment] 2019-12-17 18:27
Fix released with Firebase 6.14.0

**Closed by paulb777** 2019-12-17 18:27 UTC
Labels: api: performance, needs-attention
