### ISSUE TITLE
FR: Crashlytics key-value storage and user id should support nil values

### ISSUE THREAD

**Issue by ghugues** [firebase/firebase-ios-sdk#9212] opened 2022-01-16 16:37 UTC
### Feature proposal

* Firebase Component: Crashlytics

Crashlytics [allows to store a user id and arbitrary key/values](https://github.com/firebase/firebase-ios-sdk/blob/4377c7c574d2de2dde71fe3c2dfc8c2841a6f5d7/Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h#L77-L107) that will be sent along the next crash report. Currently this API is marked as non-nullable for the user id and custom values. It would be interesting to support nullable values as a way to remove a previously stored value. This is especially useful for the `setUserID:` method where it may be necessary to set this value to nil on logout.

The underlying API (`FIRCLSUserLoggingRecordUserKeyValue` and `FIRCLSUserLoggingRecordInternalKeyValue`) already supports this feature, so this is just a matter of adding the `nullable` annotation to the Objective-C header. In swift changing from the non nullable value to a nullable value should not be a breaking change.

**Comment by elenadoty** [comment] 2022-02-02 18:50
Hi @ghugues , 
Thanks for the feature request - what you describe is the intended behavior, we'll update it as soon as possible!

**Comment by paulb777** [comment] 2022-02-03 16:39
Fixed by #9289 and planned for 8.13.0

**Closed by paulb777** 2022-02-03 16:39 UTC
Labels: type: feature request, api: crashlytics, Swift API
