### ISSUE TITLE
Firestore stops syncing unexpectedly

### ISSUE THREAD

**Issue by businessengine** [firebase/firebase-ios-sdk#2293] opened 2019-01-19 07:54 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.15.0
  * Firebase Component: Firestore
  * Component version: 0.16.1

### [REQUIRED] Step 3: Describe the problem
Our app listen to 20+ collections, some of them are quite large with thousand of documents but not being updated frequently. We are not enabling offline persistence, put the app running for hours, sometime a day long or a few days without killing it.
Problem:
* Sometime the app (Firebase) won't sync data back to server, even the internet connection is fine. After killing and restart the app, it starts syncing again (of course the data which hasn't been synced from the last session was lost: this is expected).
* Sometime when returns to the app while it was in the background and being killed by iOS, the authentication is not persisted, user has to input username/password again.
Any ideas with this issue?

**Comment by wilhuff** [comment] 2019-01-23 18:35
This really sounds like you're describing two issues, one for Firestore and one for Auth. Could you kindly file the issue with the username/password separately?

Regarding the "won't sync data back to the server" issue, there's not really enough here for us to diagnose what's happening. Which calls are you making (setData, transaction, etc)? Are you writing continuously or just occasionally?

If you can, enable logging using [`Firestore.enableLogging(true)`](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Firestore#/c:objc(cs)FIRFirestore(cm)enableLogging:). These logs capture what the client is attempting to do and what's happening in response.

**Comment by yahmad** [comment] 2019-02-20 14:06
We have seen a similar issue in our iOS app, but can't give any specific reproduction steps as we have only seen it happen a couple of times in the past few months.

The app seems to break connection with Firestore, with all listeners across the app (including newly created ones) not providing server updates. This may be caused by the app being kept open for an extended period of time (though not confirmed). 

The app does not recover unless force quit and reopened. It doesn't seem to be an exponential backoff network retry issue, as we left the app open with a network connection for over 20 minutes at the last occurrence and I believe the exponential backoff is capped at 1 or 2 minutes?

I will try enabling logging, and see if we can capture the cause when we next see it. Might be a while before we see it again though.

**Comment by rsgowman** [comment] 2019-02-20 15:28
The exponential backoff should max out at 1 minute, plus a random jitter factor which could be as high as 1.5x. So 90s should be the absolute maximum backoff delay.

In addition to the logs, it might be helpful to know the network state too. i.e. were you on wifi or cell? Was the network disrupted at all during the test, and if so, for how long? If the cause of the failure has something to do with network transitions, then you *might* be able to provoke the failure by toggling your device's network state...

**Comment by businessengine** [comment] 2019-03-03 04:16
We deployed on iPad, WiFi network only, running for 12hours each day @rsgowman

**Comment by mikelehen** [comment] 2019-03-04 16:10
@businessengine Thanks!  Unfortunately we'll also still need the logs mentioned by @wilhuff  [above](https://github.com/firebase/firebase-ios-sdk/issues/2293#issuecomment-456916414) in order to get much traction on this issue.

**Comment by Tulleb** [comment] 2019-03-13 22:47
I think I am getting this problem as well: `setData` completion blocks are not always fired.

I don't use any authentication system: all my users are anonymous.

I am calling several (between 10 to 100) `setData` on different documents from the same collection one after another without ever getting into the completion block...

**Comment by fschaus** [comment] 2019-03-18 00:42
We've noticed the exact same problem (also on 5.15.0, but might have started to happen on previous versions) - basically if our app is in background for a fairly long-time firestore doesn't respond (no snapshotlistener being triggered). The only way to reconnect we've found so far is to kill the app and reload which is a terrible user experience.

Is there any way to monitor the connect status and "force" a reconnect if the app appears to be disconnected?

**Comment by wilhuff** [comment] 2019-03-20 20:57
@fschaus We should already be doing what you're describing. We're monitoring events from `SCNetworkReachability` and restarting our connection on changes. Could you please enable logging and send your logs? If they're large or sensitive, feel free to send to me by email at mcg@firebase.com.

**Comment by businessengine** [comment] 2019-03-20 23:12
Oh thanks for that information @wilhuff. We also realized on the SCNetworkReachability to determine if there is an active Internet connection. However, it doesn't work as expected sometime, especially when the internet connection is unstable (for area with slow, unstable network connection). You can see the screenshot below from our app, it shows OFFLINE, but the connection is still good (data is still being synced), however, after the OFFLINE/ONLINE being switched a few time (detected by SCNetworkReachability), the Firebase sync stops. Our customers reported similar situation: They saw the OFFLINE indicator, however, other apps, e.g Safari, Youtube are still working. Also the embeded webview within our app works fine, except the firebase sync and our indicator label (show Offline) - since both Firebase and our app realize on the SCNetworkReachability, so it would behave the same. Hope this gives you some clue.

![image](https://user-images.githubusercontent.com/578995/54724754-8d6c4d80-4bc0-11e9-9773-8a9431d1846d.png)

**Comment by wilhuff** [comment] 2019-03-20 23:26
If you can reproduce this please send logs. No amount of turning the network on and off again on my end is helping to reproduce this.

**Comment by businessengine** [comment] 2019-03-20 23:50
@wilhuff we have sent the log to mcg@firebase.com, Thank you!

**Comment by wilhuff** [comment] 2019-05-08 19:12
Closing for lack of data. @businessengine if you're able to supply a log that shows the things you're describing here we'll take a look.

**Closed by wilhuff** 2019-05-08 19:12 UTC
Labels: api: firestore
