### ISSUE TITLE
Crash -[GDTCCTUploader readyToUploadTarget:conditions:]

### ISSUE THREAD

**Issue by jc-paris** [firebase/firebase-ios-sdk#5464] opened 2020-04-27 08:15 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 11.3.1
  * Firebase SDK version: 6.22.0
  * Firebase Component: DynamicLinks
  * Component version: Analytics (6.4.1) / GoogleDataTransport (5.1.1) / DynamicLinks (4.0.8)
  * Installation method: `Zip file`

#### Steps to reproduce:

Crash after updating to Firebase 6.22.0.

<img width="598" alt="Screenshot 2020-04-27 at 10 13 00" src="https://user-images.githubusercontent.com/6810502/80349544-afc6a500-886f-11ea-8d9d-960de67f0f65.png">

<img width="819" alt="Screenshot 2020-04-27 at 10 13 29" src="https://user-images.githubusercontent.com/6810502/80349582-c0771b00-886f-11ea-97b4-9270425fc72c.png">

I've seen issue https://github.com/firebase/firebase-ios-sdk/issues/5449 and https://github.com/firebase/firebase-ios-sdk/issues/5312 but didn't find any clear solution.

**Comment by jc-paris** [comment] 2020-04-27 08:22
@mikehaney24 I've read this comment: https://github.com/firebase/firebase-ios-sdk/issues/5449#issuecomment-619148438

Should I update to Firebase 6.23.0 that use **GoogleDataTransport** 6.0.0 and **GoogleDataTransportCCTSupport** 3.0.0 ?

**Comment by maksymmalyhin** [comment] 2020-04-27 13:13
The crash report looks like a duplicate of #5449 and should be fixed in GoogleDataTransport 6.0.0 GoogleDataTransportCCTSupport 3.0.0. Please try to update to Firebase 6.23.0 and let us know if you still have the issue.

**Closed by maksymmalyhin** 2020-04-27 13:13 UTC
Labels: GoogleDataTransport

**Comment by jc-paris** [comment] 2020-04-27 14:23
Well that what I was asking because of the comment of @mikehaney24 in #5449...

> This issue is for those experiencing identical crashes after having upgraded to GoogleDataTransport >= 6.0.0 and GoogleDataTransportCCTSupport >= 3.0.0

From what he says, the issue appeared with those versions

**Comment by mikehaney24** [comment] 2020-04-27 16:05
Yes, upgrading should resolve the issue.
