### ISSUE TITLE
Screen view count with screen name decreased when used new sdk log screen view method

### ISSUE THREAD

**Issue by ChinjuJames12** [firebase/firebase-ios-sdk#6781] opened 2020-10-20 11:27 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____xcode 12
  * Firebase SDK version: ____ 6.30.0
  * Firebase Component: _____ Firebase analytics
  * Component version: _____6.30.0
  * Installation method: `CocoaPods 

### [REQUIRED] Step 2: Describe the problem

 For the new sdk i have changed logging screen view to new method Analytics.logEvent(AnalyticsEventScreenView, parameters: [AnalyticsParameterScreenName: screenName]) previously i have used  Analytics.setScreenName(screenName, screenClass: nil) 
Now iam experiencing a decrease in screen name count when used new log event method with updated sdk.

Also iam getting cannot log screen view event when app is not active debug log sometimes

```

**Comment by morganchen12** [comment] 2020-10-20 17:18
I suspect this may be related to how automatic screen view logging detects view presentations. @allenktv anything obvious that might be causing this?

**Comment by allenktv** [comment] 2020-10-20 17:22
Hi @ChinjuJames12, could you give some code snippets on how you are calling the API? And if you have logs on when you call the log screen view would be very helpful as well.

As for logging screen screen views when the app is not active, the SDK does not allow the screen view events to be logged when the app is in the background. Are you perhaps attempting to log screen views then?

**Comment by ChinjuJames12** [comment] 2020-10-20 19:56
Hi, This are the cases I will call the api.

Firstly my app is news app...so I got tob bar with categories and subcategories like https://github.com/rechsteiner/Parchment so when user move in between this tabs i will be calling log screen view api Analytics.logEvent(AnalyticsEventScreenView, parameters: [AnalyticsParameterScreenName:"will be sending current category name over there like sports,Home etc"]) 

Secondly  when user select an article from the listing will push to a new viewcontroller  and will call log screen view method over its viewdidappear Analytics.logEvent(AnalyticsEventScreenView, parameters: [AnalyticsParameterScreenName:" Reading news"]).


As for logging screen screen views when the app is not active, the SDK does not allow the screen view events to be logged when the app is in the background. Are you perhaps attempting to log screen views then? - yaa this one I have seen not logging in debugging view of previous version of sdk but now only started showing error like cannot log screen events when app is not active in Xcode debugging console so this is not causing screen view difference

**Comment by morganchen12** [comment] 2020-10-20 20:07
The usage you described sounds normal. It is possible if Analytics' automatic logging uses `viewWillAppear` that that may cause more screen_view events than `viewDidAppear`.

Can you share the app's debug logs when you try to log a screen view?

**Comment by ChinjuJames12** [comment] 2020-10-20 20:33
Attaching the logs getting in debug console 
[NewSdk.docx](https://github.com/firebase/firebase-ios-sdk/files/5411345/NewSdk.docx)
**The screen logging as in new sdk**
 2020-10-21 04:21:56.959368+0800 ChinaPress[19088:5979724] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 抢鲜, LaunchScreenController
 2020-10-21 04:21:56.959368+0800 ChinaPress[19088:5979724] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 抢鲜, LaunchScreenController
2020-10-21 04:22:05.302610+0800 ChinaPress[19088:5979721] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 阅读新闻, LaunchScreenController
[OldSdk.docx](https://github.com/firebase/firebase-ios-sdk/files/5411347/OldSdk.docx)
**The screen logging as in old sdk**
2020-10-21 04:12:11.416103+0800 ChinaPress[19074:5975982] 6.27.1 - [Firebase/Analytics][I-ACS031009] Set screen name and screen class: 抢鲜, LaunchScreenController
2020-10-21 04:12:11.430222+0800 ChinaPress[19074:5975998] 6.27.1 - [Firebase/Analytics][I-ACS031009] Set screen name and screen class: 主页, NewsListWithFlashNewsViewController
2020-10-21 04:12:23.775240+0800 ChinaPress[19074:5976016] 6.27.1 - [Firebase/Analytics][I-ACS031009] Set screen name and screen class: 阅读新闻, EMPageViewController

Here iam passing two of my categories name when open app also when click on listing will send 阅读新闻 .The word logs consist of this and when come pop back stopping it.

**Comment by ChinjuJames12** [comment] 2020-10-20 20:49
Also want to update some thing in my previous sdk i can see when on third click of article from listing saying duplicate view but i can see it successfully logged in debug view.
[OldFirebaseSdk.docx](https://github.com/firebase/firebase-ios-sdk/files/5411435/OldFirebaseSdk.docx)

2020-10-21 04:37:11.132543+0800 ChinaPress[19106:5985383] 6.27.1 - [Firebase/Analytics][I-ACS031009] Set screen name and screen class: 抢鲜, LaunchScreenController
2020-10-21 04:37:11.145275+0800 ChinaPress[19106:5985383] 6.27.1 - [Firebase/Analytics][I-ACS031009] Set screen name and screen class: 主页, NewsListWithFlashNewsViewController
2020-10-21 04:37:15.715137+0800 ChinaPress[19106:5985379] 6.27.1 - [Firebase/Analytics][I-ACS031009] Set screen name and screen class: 阅读新闻, EMPageViewController
2020-10-21 04:37:20.130717+0800 ChinaPress[19106:5985376] 6.27.1 - [Firebase/Analytics][I-ACS031009] Set screen name and screen class: 阅读新闻, NewsListWithFlashNewsViewController
2020-10-21 04:37:25.348242+0800 ChinaPress[19106:5985586] 6.27.1 - [Firebase/Analytics][I-ACS031004] Ignoring duplicate screen name and screen class: 阅读新闻, NewsListWithFlashNewsViewController
[NewFIREBASESDK.docx](https://github.com/firebase/firebase-ios-sdk/files/5411431/NewFIREBASESDK.docx)

But for new sdk not getting that warning
2020-10-21 04:38:12.033982+0800 ChinaPress[19123:5986613] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 抢鲜, LaunchScreenController
2020-10-21 04:38:12.047076+0800 ChinaPress[19123:5986613] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 主页, LaunchScreenController
2020-10-21 04:38:31.455803+0800 ChinaPress[19123:5986614] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 阅读新闻, LaunchScreenController
2020-10-21 04:38:35.728241+0800 ChinaPress[19123:5986614] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 阅读新闻, LaunchScreenController
2020-10-21 04:38:39.307432+0800 ChinaPress[19123:5986617] 6.30.0 - [Firebase/Analytics][I-ACS031029] Logging screen view with screen name and screen class: 阅读新闻, LaunchScreenController

**Comment by allenktv** [comment] 2020-10-20 21:28
Those logs look as expected. The reason why the old SDK has `Ignoring duplicate screen name and screen class` is due to the way `setScreenName` worked, where it automatically ignored screen view events with the same name and class even if they were set by the automatic screen tracking or by the API.

> "But when it comes to screen_views total count per day on event console the not set value seems increased and one with screen name seems decreased" 

When you mean not set, do you mean screen_name not set? If so, it could be due to the automatic screen views that occur when you switch screens. If you would like to decrease that so that you only have screens with names, I recommend following the [blog](https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html) and setting `FirebaseAutomaticScreenReportingEnabled` to NO in the info.plist

**Comment by ChinjuJames12** [comment] 2020-10-20 21:46
I mean (not set) Showing in screen_view increased and I can see a drop in one with screen names when used the new sdk

**Comment by ChinjuJames12** [comment] 2020-10-20 21:47
Do the new sdk with new api solved any duplicate screen names issue?

**Comment by allenktv** [comment] 2020-10-20 21:50
@ChinjuJames12 Yes, as mentioned above, by setting `FirebaseAutomaticScreenReportingEnabled` to NO, the automatic screen view events are not triggered and will remove (not set) screen names in the console, as well as remove duplicate screen views. The only time screen view events will be logged will be when the API is called manually

**Comment by ChinjuJames12** [comment] 2020-10-20 21:52
Do the new sdk with new api solved any duplicate screen names issue?
I have not changed any other codings in new version expect changed to new screen event method but the screen view with screen name decreased.

Do automatic collected screen views got screen names it will be marking as (not set) right

**Comment by morganchen12** [comment] 2020-10-20 22:06
Yes. You can fix the (not set) screen names by adding the `FirebaseAutomaticScreenReportingEnabled` key to your app's Info.plist and setting the value to NO.

**Comment by ChinjuJames12** [comment] 2020-10-20 22:16
Is there chance when I turn of FirebaseAutomaticScreenReportingEnabled the one with screen names count will come same as previous version count itself

**Comment by morganchen12** [comment] 2020-10-20 22:25
We haven't yet identified what's causing the decrease in total `screen_view` events for your app. If you're able to test with a sample application and reproduce the decrease in `screen_view` events by converting automatically logged screens to manually logged screens, that would be helpful.

**Comment by allenktv** [comment] 2020-10-20 22:26
@ChinjuJames12 When you say "decreased" screen views with screen name, are you saying the **total count** of screen_views with screen name has decreased? Or that the **percentage** of screen views with (not set) has increased?

**Comment by ChinjuJames12** [comment] 2020-10-20 22:32
<img width="638" alt="Screen Shot 2020-10-21 at 6 30 56 AM" src="https://user-images.githubusercontent.com/45812907/96651244-fc92c080-1366-11eb-8b68-b36ee1923038.png">
what I mean is (not set) increased and one with screen names decreased

**Comment by ChinjuJames12** [comment] 2020-10-20 22:34
@morganchen12 reproduce the decrease in screen_view events by converting automatically logged screens to manually logged screens

Means what yaa do automatically logged screens also can have names like 阅读新闻, like 主页

**Comment by ChinjuJames12** [comment] 2020-10-20 22:35
https://github.com/firebase/firebase-ios-sdk/issues/1894 is this bug fix in anyway can affect the one with screen names in new sdk

**Comment by allenktv** [comment] 2020-10-20 22:39
I see. Please read the [blog](https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html). The new API gives full control over screen views to the developer, and if the `AnalyticsParameterScreenName` is set on every call, you will not get any (not set) screen names in your console

**Comment by ChinjuJames12** [comment] 2020-10-20 22:47
@allenktv So in previous sdk the screen name saving don’t have full developer control it is mixed with automatic screen report also.

Please help yaa my client is asking why the count is decreased

**Comment by ChinjuJames12** [comment] 2020-10-20 22:56
> I see. Please read the [blog](https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html). The new API gives full control over screen views to the developer, and if the `AnalyticsParameterScreenName` is set on every call, you will not get any (not set) screen names in your console
Right now I have not turned off FirebaseAutomaticScreenReportingEnabled and Iam passing AnalyticsParameterScreenName with all api calls

**Comment by ChinjuJames12** [comment] 2020-10-21 00:46
I found the bug the sdk version used earlier  is Firebase/Analytics (6.27.1)
in which  can see the 阅读新闻 logged when press back button also...but from my code wise iam not sending it...
I cannot upload video over here if you give your mail id i will send video in which debug view logging it twice but from console sending it only one time

**Comment by allenktv** [comment] 2020-10-21 16:33
Since you say you are not setting `FirebaseAutomaticScreenReportingEnabled` to `NO`, the screen view event that is logged when you press the back button is from the automatic screen view reporting, and is not a bug.

I am closing this thread now since it has been established that the solution is to turn off automatic screen tracking.

**Closed by allenktv** 2020-10-21 16:33 UTC
Labels: api: analytics
