### ISSUE TITLE
Crash in FIRInstanceIDKeyPair

### ISSUE THREAD

**Issue by ninglinli1** [firebase/firebase-ios-sdk#2333] opened 2019-02-01 03:25 UTC
### [READ] Step 1: Are you in the right place?
YES

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase/Database = 4.8.2, Firebase/Storage = 4.8.2

### [REQUIRED] Step 3: Describe the problem
We saw 151 production crashes since January 32th, 2019.

#### Crash log:

CoreFoundation | CFDataGetBytePtr (CoreFoundation)
-- | --
Security | SecKeyCreateWithData (Security)
Security | SecKeyCreateFromAttributeDictionary (Security)
Security | SecTokenItemCreateFromAttributes (Security)
Security | SecItemResultCopyPrepared (Security)
Security | SecItemResultProcess (Security)
Security | __SecItemCopyMatching_block_invoke_2 (Security)
Security | __SecItemAuthDoQuery_block_invoke (Security)
Security | SecItemAuthDo (Security)
Security | SecItemAuthDoQuery (Security)
Security | __SecItemCopyMatching_block_invoke (Security)
Security | SecOSStatusWith (Security)
Security | SecItemCopyMatching (Security)
SHUtilities | Show CPU registers+[FIRInstanceIDKeyPair cachedKeyRefWithTag:]
SHUtilities | +[FIRInstanceIDKeyPair keyPairForPrivateKeyTag:publicKeyTag:error:]
SHUtilities | -[FIRInstanceIDKeyPairStore cachedKeyPairWithSubtype:error:]
SHUtilities | -[FIRInstanceIDKeyPairStore validCachedKeyPairWithSubtype:error:]
SHUtilities | -[FIRInstanceIDKeyPairStore loadKeyPairWithError:]
SHUtilities | -[FIRInstanceIDKeyPairStore appIdentityWithError:]
SHUtilities | -[FIRInstanceID(Private) appInstanceID:]
SHUtilities | -[FIRAIdentity firebaseInstanceID]
SHUtilities | -[FIRAMeasurement createRawEventMetadataWithUserAttributes:]
SHUtilities | __43-[FIRAMeasurement writeEventOnWorkerQueue:]_block_invoke.1030
SHUtilities | -[FIRASqliteStore performTransaction:]
SHUtilities | -[FIRAMeasurement writeEventOnWorkerQueue:]
SHUtilities | -[FIRAMeasurement handleEventOnWorkerQueue:]
SHUtilities | __52-[FIRAScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke
libdispa...ch.dylib | _dispatch_call_block_and_release (libdispatch.dylib)
libdispa...ch.dylib | _dispatch_client_callout (libdispatch.dylib)
libdispa...ch.dylib | _dispatch_queue_serial_drain (libdispatch.dylib)
libdispa...ch.dylib | _dispatch_queue_invoke (libdispatch.dylib)
libdispa...ch.dylib | _dispatch_root_queue_drain (libdispatch.dylib)
libdispa...ch.dylib | _dispatch_worker_thread3 (libdispatch.dylib)
libsyste...ad.dylib | _pthread_wqthread (libsystem_pthread.dylib)
libsyste...ad.dylib | start_wqthread (libsystem_pthread.dylib)

**Comment by ryanwilson** [comment] 2019-02-01 14:42
@ninglinli1 thanks for the report - the Firebase version `(4.8.1)` being used was released over a year ago (January 27, 2018) and InstanceID has changed quite a bit since then. Can you reproduce this on the latest version?

If you're not able to update the major version to the most recent (`5.16.0` as of this writing) try updating to the last `4.X` release - `4.13.0`.

**Comment by paulb777** [comment] 2019-02-20 21:23
Closing until there is evidence the issue exists in a recent release.

**Closed by paulb777** 2019-02-20 21:23 UTC
Labels: InstanceID
