### ISSUE TITLE
'The default FirebaseApp instance must be configured before the defaultFirebaseApp instance can be initialized. One way to ensure that is to call `[FIRApp configure];

### ISSUE THREAD

**Issue by LokeshV-Nuclei** [firebase/firebase-ios-sdk#6925] opened 2020-11-08 08:24 UTC
2:29
Terminating app due to uncaught exception 'com.firebase.installations', reason: 'The default FirebaseApp instance must be configured before the defaultFirebaseApp instance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'
*** First throw call stack:
(0x18bf93180 0x18b16b9f8 0x18be9d3a0 0x115c2fe54 0x115a77610 0x115a7753c 0x1047868ec 0x10478640c 0x104785738 0x10478515c 0x103f43f9c 0x103f438ec 0x103f44110 0x1b85be0f0 0x1b85bf854 0x1b85c4fe0 0x1b7e882a4 0x1b7e9083c 0x1b7e87f28 0x1b7e88818 0x1b7e86b64 0x1b7e8682c 0x1b7e8b36c 0x1b7e8c150 0x1b7e8b224 0x1b7e8ff24 0x1b85c35e8 0x1b81bfe04 0x18e90f9fc 0x18e91940c 0x18e918c14 0x119cf8c78 0x119cfc840 0x18e94a040 0x18e949cdc 0x18e94a294 0x18bf24f1c 0x18bf24e9c 0x18bf24784 0x18bf1f6c0 0x18bf1efb4 0x18e12079c 0x1b85c6c38 0x103f4b038 0x18b9e28e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by paulb777** [comment] 2020-11-08 15:55
Possible duplicate of #5425.  Please take a look at that issue and fill out the issue template.

**Comment by morganchen12** [comment] 2020-11-08 22:32
@LokeshV-Nuclei please also symbolicate the stack trace in your issue report.

**Closed** 2020-11-20 02:04 UTC
Labels: api: installations, needs-info, no-recent-activity

**Comment by LokeshV-Nuclei** [comment] 2020-12-02 12:02
Yes we are facing this issue.

**Comment by morganchen12** [comment] 2020-12-02 14:22
@LokeshV-Nuclei please see #5425. If this is a separate issue, please share a reproducible example project and we'll re-open this issue.
