### ISSUE TITLE
Duplicate messages can occur when two campaigns are triggered by different events in In-App Messaging

### ISSUE THREAD

**Issue by kouki-dan** [firebase/firebase-ios-sdk#9070] opened 2021-12-09 14:29 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.10.0
  * Installation method: `Swift Package Manager` 
  * Firebase Component: In-App Messaging 
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
Duplicate messages can occur when two campaigns are triggered by different events. (The first message must have an image to reproduce it.)

Setup like this in the console.
|First Event|Second Event|
|-|-|
|<img width="934" alt="スクリーンショット 2021-12-09 23 07 04" src="https://user-images.githubusercontent.com/1401711/145411325-d14fc25c-8a57-4af1-b62c-ad2ac3ac01b6.png">|<img width="913" alt="スクリーンショット 2021-12-09 23 07 35" src="https://user-images.githubusercontent.com/1401711/145411364-a5ccd7eb-ec5a-4177-9ee1-43d54caa477f.png">|

And trigger events consecutively like this code.

```swift
struct ContentView: View {
    var body: some View {
        Button("Trigger In-App") {
            InAppMessaging.inAppMessaging().triggerEvent("first_event")
            InAppMessaging.inAppMessaging().triggerEvent("second_event")
        }
            .padding()
    }
}
```

It shows multiple dialogs in a row.

https://user-images.githubusercontent.com/1401711/145411619-850d6c24-845f-4989-9217-24a5c06e1dee.mov

It seems [FIRIAMDisplayExecutor](https://github.com/firebase/firebase-ios-sdk/blob/c7f80c14c2ff207173f1a3ba294df12c019c266a/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m) checks message is displayed or not in this code.
https://github.com/firebase/firebase-ios-sdk/blob/c7f80c14c2ff207173f1a3ba294df12c019c266a/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m#L422-L428

However, `isMsgBeingDisplayed` becomes true only after the image has finished loading.
https://github.com/firebase/firebase-ios-sdk/blob/c7f80c14c2ff207173f1a3ba294df12c019c266a/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m#L665

I think if another event is triggered while loading the image in a first event, two dialogs are shown in the order in which the images were loaded.

And `_currentMsgBeingDisplayed` is set as last called `displayForMessage`. The last event(In this video, second event) may be treated as displayed. 
https://github.com/firebase/firebase-ios-sdk/blob/c7f80c14c2ff207173f1a3ba294df12c019c266a/FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m#L317-L336

Therefore, on the second tap in this video, it shows the first event.

I think the first tap will give me a first event message, and the second tap will give me a second event message.

#### Steps to reproduce:

- Set two campaigns with another event trigger and it has an image.
- Trigger events consecutively.

Minimum reproduce project is here: https://github.com/kouki-dan/InAppMessaging-Duplicate

**Comment by rizafran** [comment] 2021-12-23 10:44
Sorry for the late reply, @kouki-dan. I was able to reproduce the same behavior. Let me check with the team if it's intended or a bug. Thanks.

**Comment by rizafran** [comment] 2021-12-23 19:19
@kouki-dan, our engineers have been notified and will look into this. This is internally tracked in b/211895119. Thanks.

**Comment by eldhosembabu** [comment] 2021-12-23 20:37
This issue should be fixed in PR : https://github.com/firebase/firebase-ios-sdk/pull/9138

**Comment by eldhosembabu** [comment] 2022-01-05 19:03
Closing this issue since fix is merged. You can expect to see the fix in next release of SDK.

**Closed by eldhosembabu** 2022-01-05 19:03 UTC
Labels: api: inappmessaging, internal-bug-filed

**Comment by kouki-dan** [comment] 2022-01-08 03:01
Thank you!
