### ISSUE TITLE
Unable to install after SPM integration

### ISSUE THREAD

**Issue by martinobonfiglioli** [firebase/firebase-ios-sdk#6626] opened 2020-10-01 10:33 UTC
* Xcode version: Version 12.0.1 (12A7300)
  * Firebase SDK version: 6.34-spm-beta
  * Firebase Component: Analytics, Crashlytics
  * Component version: latest
  * Installation method: Swift Package Manager

#### Steps to reproduce:

Add dependencies through SMP with `https://github.com/firebase/firebase-ios-sdk.git` and selected branch `6.34-spm-beta`
Change the import from `#import` to `@import`
I already have `-Objc` to my linker flag 
Add the frameworks to my three targets needed

I got [this](https://www.dropbox.com/s/qxffu856tnad91c/Screenshot%202020-10-01%20at%2012.18.17.png?dl=0) error in the install:

Unable to install
No code signature found.
Error code: -402620388

**Comment by maksymmalyhin** [comment] 2020-10-01 12:37
@martinobonfiglioli Sorry you have an issue. From the first glance it looks like a generic app signing issue. Could you please confirm that the app can be installed to the device after removing Firebase? If no, I would suggest to check signing settings of the targets.

**Comment by martinobonfiglioli** [comment] 2020-10-01 12:42
Hi @maksymmalyhin 
I confirm that switching to the manual adding `.framework` I can install the app without issues.

I can add that yesterday I was working on integrations with `6.34-spm-beta` but I found a different problems that I can't remember. Today I can't find that branch so switching to the `6.33-spm-beta` and I had the install issue.

**Comment by maksymmalyhin** [comment] 2020-10-01 13:25
I was able to reproduce the issue with Analytics dependency.

**Comment by maksymmalyhin** [comment] 2020-10-01 15:24
The workaround mentioned on the [#6472(comment)](https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-697312879) fixed the issue for me.

@martinobonfiglioli I'm closing issue so far but feel free to continue conversation or reopen if it doesn't work for you.

**Closed by maksymmalyhin** 2020-10-01 15:24 UTC
Labels: Swift Package Manager, api: analytics, needs-attention

**Comment by martinobonfiglioli** [comment] 2020-10-01 15:59
Thanks @maksymmalyhin I'll follow what you have linked
