### ISSUE TITLE
Package manager doesn't list package

### ISSUE THREAD

**Issue by SharonGilmore** [firebase/firebase-ios-sdk#9234] opened 2022-01-20 10:42 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: any
  * Installation method: `Swift Package Manager`
  * Firebase Component: all
  * Target platform(s): `iOS`

#### Steps to reproduce:

Trying to install Firebase using Swift Package Manager, following the official instructions ([here](https://firebase.google.com/docs/ios/installation-methods#swift-package-manager)).

Step 2 says: In Xcode, install the Firebase libraries by navigating to File > Swift Packages > Add Package Dependency…

Firstly, the menu option 'Swift Packages' doesn't appear under 'File' in my version of XCode, but 'Add Packages' seems to take me to the correct window.

Then Step 3 says: In the prompt that appears, select the Firebase GitHub repository - no prompt appears for me.  I tried typing the given url into the search box at the top right, but it says 'Found 0 results'

I'm totally new to all this, so I've no idea whether I need to enable something first?  Here's what the packages screen looks like for me:

![Screenshot 2022-01-20 at 10 42 10](https://user-images.githubusercontent.com/3910274/150323456-ffd6f422-bfab-4402-8ff8-44ccf6475bc9.png)

**Comment by ryanwilson** [comment] 2022-01-20 15:36
Re: step 2 in the official instructions pointing to the wrong File menu, I have a fix pending for that and it should roll out soon. Thanks for catching it! It changed between Xcode 12 and 13 and we updated our GitHub docs but not the Firebase site docs.

**Comment by SharonGilmore** [comment] 2022-01-20 15:58
I think I've copied it correctly; I've triple-checked it.  Here's my screen when I paste it in:
![Screenshot 2022-01-20 at 15 56 42](https://user-images.githubusercontent.com/3910274/150374775-f825ba03-bad2-4089-81d2-cdb05722dadd.png)

**Comment by SharonGilmore** [comment] 2022-01-20 15:59
If I just type 'https://github.com/' I get lots of results, but as soon as I add the 'f' of 'firebase' I get no results

**Comment by ryanwilson** [comment] 2022-01-20 20:55
Just tried to reproduce on my end but was unable to. Apologies if this is a silly question, but did you hit the Return/Enter key? I remember being slightly frustrated that they require it without any "Search" button.

**Comment by SharonGilmore** [comment] 2022-01-21 09:26
> Just tried to reproduce on my end but was unable to. Apologies if this is a silly question, but did you hit the Return/Enter key? I remember being slightly frustrated that they require it without any "Search" button.

That does sound like something I'd forget, to be fair!  But, no, I've definitely hit Enter (several times, very hard!!)

**Comment by ryanwilson** [comment] 2022-01-21 14:18
@SharonGilmore Hmm... can you try a different git repo and see if that works for you? `https://github.com/google/GoogleUtilities.git` is a dependency of ours, can you see that pop up?

**Comment by SharonGilmore** [comment] 2022-01-21 16:11
Nothing there either, no.  But I tried on a different computer, and on that one both the firebase and the Google one appeared properly.  So it looks like it's my machine.

**Comment by ryanwilson** [comment] 2022-01-21 16:33
Okay at least we're getting somewhere! Can you try resetting the Package Caches, reboot your Mac, etc and see if that works? I'll close the issue since it's non-Firebase specific but feel free to keep the discussion going!

**Closed by ryanwilson** 2022-01-21 16:33 UTC
Labels: needs-attention, Swift Package Manager

**Comment by SharonGilmore** [comment] 2022-01-24 09:56
Still getting nothing after doing all that.  As I say, I got it working fine on another machine, so it must be my Mac rather than anything on your end.  Doesn't really matter as I'm able to use the other machine anyway, but if I come across a solution I'll post it here for future reference!

Thanks for your help!
