### ISSUE TITLE
adding firebase hangs when fetching grpc

### ISSUE THREAD

**Issue by ekimia** [firebase/firebase-ios-sdk#6606] opened 2020-09-29 21:52 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 6.330beta
  * Installation method: `Swift Package Manager`

### [REQUIRED] Step 2: Describe the problem
add the package according to instructions with the 6.33 or 6.32 beta branch specified. Hangs when resolving a grpc commit:

![image](https://user-images.githubusercontent.com/357513/94620389-671e7800-0263-11eb-9374-97312deeaeba.png)

#### Steps to reproduce:
See above

**Comment by paulb777** [comment] 2020-09-29 22:34
Hmm, I just re-confirmed that I can still successfully initialize, including checking out gRPC. Are you able to check out that git hash outside of SwiftPM?

I don't yet have access to Xcode 12.0.1. Does changing Xcode versions make a difference?

**Comment by ryanwilson** [comment] 2020-09-30 12:31
I've seen this happen before and it just takes a while, it eventually sorted itself out for me. We'll need to see if we can track down what's causing this and see if there are any workarounds we can have (like limiting the git history available, eliminating needless files, etc).

**Comment by ekimia** [comment] 2020-09-30 17:44
Going to let it go for longer. Yesterday it took an hour at the fetching step which is when I aborted it.

**Comment by ekimia** [comment] 2020-09-30 22:01
tried on another machine, after an hour it worked. On my main laptop however its still been working at it for over 2 hours.

**Comment by ekimia** [comment] 2020-09-30 22:02
@paulb777 yes i can check the commit out directly

**Comment by paulb777** [comment] 2020-09-30 22:42
Might be worth starting a discussion at https://forums.swift.org/tag/packagemanager since this is most likely an Xcode or SwiftPM issue.

**Comment by SergejLogis** [comment] 2020-10-05 12:54
We recently added Firebase SDK to our project via SPM, and since then SPM dependencies resolving takes 10+ minutes. The culprit is gRPC library which is 1 GB in size. We merely want to use Firebase Analytics for tracking events. Do we really need 1 GB library to be able to send FA events? And if we do, why does it take forever to download? 😕

**Comment by ryanwilson** [comment] 2020-10-05 14:15
This is definitely a usability issue and we'll do what we can on our side to fix it. There are some promising findings with a shallow clone which reduces the checked out `.git` folder alone from `272MB` to `10MB`. We're going to discuss the details of how we can roll this out in the most backwards compatible way and will update this thread soon when we have a plan.

> The culprit is gRPC library which is 1 GB in size.  We merely want to use Firebase Analytics for tracking events. Do we really need 1 GB library to be able to send FA events?

This is a consequence of SwiftPM only having a single manifest per repo at the moment, so every single dependency across Firebase needs to be included in the Package manifest and fetched beforehand. We have discussed putting each product in a different repo but determined it would be a worse overall experience: you'd need to go through the setup steps for every single Firebase SDK you use as opposed to doing it once, there would be N GitHub repos (one for each SDK) which would make issue management more confusing, more difficult to make cross SDK changes, etc. 

All that being said - we'll do as much as we can to make sure using SwiftPM is a great experience and as fast as possible. Thanks for your patience as we work through the bumps during the beta offering!

**Comment by paulb777** [comment] 2020-10-07 18:57
Thanks for your patience with this issue.

We just pushed a fix to the `6.34-spm-beta` that should substantially speed up loading three of the dependency repos (by using repos with most of the git metadata removed) I'd appreciate a confirmation that it addresses the hang as well.

**Comment by SergejLogis** [comment] 2020-10-08 10:31
Thanks, @paulb777! 
I happily confirm that gRPC now only takes few seconds to checkout! And the entire SPM packages update now takes **170 sec** instead of staggering **10+ minutes**!
Thank you very much! 🚀

**Closed** 2020-10-08 14:27 UTC
Labels: Swift Package Manager
