### ISSUE TITLE
Undefined symbols for architecture arm64: "_OBJC_CLASS_$_FIRAnalytics", referenced from:

### ISSUE THREAD

**Issue by pavm035** [firebase/firebase-ios-sdk#11156] opened 2023-04-21 06:20 UTC
### Description

When i try to link FirebaseAnalytics to my custom framework(SpaceXFramework) and main app target(FirebaseSupi) is getting the below error `Undefined symbol: _OBJC_CLASS_$_FIRAnalytics`, I'm not sure what causes this issue to occur, but we don't have an issue with other xcframeworks when we linked between the modules.

I have attached a sample project which reproduces the issue, please help me

https://filebin.net/zgah4p9tl13mwmzz/FirebaseSupi_2.zip

### Firebase SDK Version

10.4.0

### Xcode Version

14.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json



```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-04-22 14:28
I'm able to reproduce this. The app successfully links if FirebaseAnalytics is removed from the FirebaseSupi `Link with Libraries` Build Phase.

it looks like Xcode and SPM are transitioning how they link dependent binary targets to frameworks and apps using them.

Firebase definitely does not support this use case with CocoaPods. It's not possible to depend on a static binary library from both an app and a framework. More investigation is needed for Swift Package Manager.

To be robust across Xcode versions and package managers, binary dependencies like FirebaseAnalytics should not be depended on by frameworks.

**Comment by pavm035** [comment] 2023-04-22 14:57
Thanks for the quick check, I know if I unlink `FirebaseAnalytics` either from the framework or app it works fine. But our use case is like building `Analytics` module for our which contains Firebase analytics as one of the components along with other analytics(braze, adjust), So our main app sometimes needs a request module to perform Firebase tracking and also main app sometimes send logs to firebase directly  hence we need to link FirebaseAnalytics to both targets,

Next question is,
If main app rely completely on the analytics module is that good idea to link `FirebaseAnalytics` to framework directly and link module to main app?


ps: I have tried linking BrightCove iOS SDK which supports xcframeworks like `FirebaseAnalytics` but it does not have any issue if we link to main app and framework module

**Comment by paulb777** [comment] 2023-04-22 15:42
It looks like Brightcove distributes both dynamically-linked and statically linked frameworks from its podspecs at https://github.com/brightcove/BrightcoveSpecs. FirebaseAnalytics is only distributed as a statically linked framework.

**Comment by pavm035** [comment] 2023-04-23 01:06
Hmm right, thanks for clarifying.

BTW do you have any recommendations for the modular approach I mentioned above? basically, i want to link `FirebaseAnalytics` to the `Module/framework` and then link this module to the main app

**Comment by pavm035** [comment] 2023-04-27 07:35
@morganchen12  My project is configured with SPM so if i link this FirebaseAnalytics to two modules then error is started appearing

**Comment by morganchen12** [comment] 2023-04-27 21:04
I see. For static linkage, you can expose just the headers to your app target and link the Analytics binary itself into your framework. I'm not sure if SPM lets you do this, though.

**Comment by paulb777** [comment] 2023-08-08 21:10
Marking for Firebase 11 to consider switching Firebase's binary distributions to dynamic frameworks

**Comment by paulb777** [comment] 2024-05-29 00:13
Closing as a duplicate of #8945

**Closed by paulb777** 2024-05-29 00:13 UTC
Labels: api: analytics
