### ISSUE TITLE
No such module 'FirebaseAuth'

### ISSUE THREAD

**Issue by naticio** [firebase/firebase-ios-sdk#9014] opened 2021-11-25 17:14 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __13.1__
  * Firebase SDK version: __8.6.1 (8.0 next major)___
  * Installation method:  Swift Package Manager=
  * Firebase Component: ___Auth__ 
  * Target platform(s): All | iOS 

### [REQUIRED] Step 2: Describe the problem

No such module 'FirebaseAuth', cannot compile successfully

#### Steps to reproduce:

add sdk package
compile
https://github.com/naticio/Reny

**Comment by paulb777** [comment] 2021-11-25 19:09
The sample builds successfully for me. Please make sure you follow the [instructions](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md) and if you're still stuck, provide more details about reproducing.

**Comment by naticio** [comment] 2021-11-25 20:44
hi Paul, maybe because the last commit had the import FirebaseAuth commented, now its uncommented. can you try again?
 I followed the instructions but still not working, compiler only complains with FirebaseAuth but it's ok with Firebase, Firebase storage etc

I see I have firebase 8.9.1

I also tried to do it the old fashion way with cocoa pods  but pod init failed for whatever reason

then I cleaned build and deleted derived data but still doesn't work.

**Comment by paulb777** [comment] 2021-11-25 22:12
@naticio It looks like `FirebaseAuth` was not selected in the `Choose the Firebase products` step at https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md.  It can be fixed by adding as a dependency like in this screen shot:

<img width="1143" alt="Screen Shot 2021-11-25 at 2 09 00 PM" src="https://user-images.githubusercontent.com/73870/143503792-96aeb603-faf8-4490-a544-adc3fbd69ece.png">

and then the project builds successfully.

**Closed by paulb777** 2021-11-25 22:12 UTC
Labels: api: auth, needs-attention

**Comment by naticio** [comment] 2021-11-25 22:37
ugh I need to stop working and go and eat some turkey, thanks Paul!
