### ISSUE TITLE
Batch deletes trigger multiple observer callbacks instead of one

### ISSUE THREAD

**Issue by Alexookah** [firebase/firebase-ios-sdk#5955] opened 2020-07-01 15:57 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.8.0
  * Firebase Component: Firestore
  * Component version: 1.16.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When observing a whereFilter query, when multiple documents are deleted, the observer callback is called once for every deleted document, instead of being called once with multiple document changes (like additions and modifications do).

The performance of these callbacks is also very poor (OnWatchStreamChange uses 100% cpu).

Observing a whole collection (without a whereFilter) seems to be okay.

#### Steps to reproduce:

Observe a query that has many documents, then delete multiple documents (using a different device).
The observer callback will be run multiple times, once for each deleted document.

#### Relevant Code:

```
db.collection("myCol").whereField("foo", isEqualTo: "bar").addSnapshotListener { querySnapshot, error in 
    print(querySnapshot.documentChanges.count) // this prints "1" multiple times when documents are deleted
}
```

**Comment by thebrianchen** [comment] 2020-07-01 21:05
@Alexookah I've tried reproducing your issue in tests by deleting multiple documents using `WriteBatch` from another instance of Firestore to simulate using a different device (test [link](https://www.paste.org/107341)), but the snapshot listener consistently receives all the deletes in a single snapshot. Just to confirm, are you using `WriteBatch` for your batch deletes?

If so, can you provide a repro, or enable [verbose logging](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:) and share the logs from a local reproduction?

**Comment by Stratubas** [comment] 2020-07-02 00:23
@thebrianchen The batched delete is done in a cloud function using something like this:
```
const batch = db.batch();
for (const id of idsToDelete) {
    batch.delete(db.collection("myCol").doc(id));
}
await batch.commit();
```
and additions / modifications use similar code (the iOS only reads the data).

**Comment by Alexookah** [comment] 2020-07-03 09:13
@thebrianchen Using the Simulator the document deletions appear one by one, but using a real device (iPad), they come in small batches (20-50 documents) instead of 500 which is the batch size. For additions and modifications, both the simulator and the real device receive batches of 500 changes.

**Comment by thebrianchen** [comment] 2020-07-06 17:57
@Alexookah I tried reproducing it locally in a query with many documents and used a batch size of 500 without success. Could you enable verbose logging and share the logs from the batch deletes? Thanks!

**Comment by Alexookah** [comment] 2020-07-08 16:42
[Here are the verbose logs (zip file)](https://github.com/firebase/firebase-ios-sdk/files/4892014/debug-log.zip)

and this is my code:

    let now1 = Date()
    print("MAAAA before observe", now1)

    db.collection("pois").whereField("mapId", isEqualTo: mapId).addSnapshotListener { querySnapshot, error in
        guard let snapshot = querySnapshot else {
            log.error("Error fetching pois/mapid:\(mapId) snapshots: \(error!)")
            return
        }
        
        let now = Date()
        print("MAAAA \(snapshot.documentChanges.count) documentChanges to process ", now)
        
        snapshot.documentChanges.forEach { documentChange in
            let document = documentChange.document
            // plus code that uses the document...
        }
        print("MAAAA finished callback", Date().timeIntervalSince(now))
        print("MAAAA finished drawing", Date().timeIntervalSince(now1))
    }

**Comment by thebrianchen** [comment] 2020-07-16 01:34
Thanks for taking the time to record and share the logs with us! 

From the logs, it appears the multiple snapshots you are receiving are a consequence of the [limbo resolution](https://github.com/firebase/firebase-js-sdk/issues/2683#issuecomment-591756000) performed by the Firestore client. The 500 documents in the batch you deleted were marked as “removed” rather than “deleted” by the Firestore backend, which prompted the client to mark them as being in limbo. The client resolves the limbo documents by looking them up in batches, to avoid overloading the backend. Firestore raises a snapshot callback each time a batch is complete, which results in the multiple callbacks you are observing.

To tell which snapshot contains the guaranteed up-to-date server snapshot, you can include [metadata changes](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Query#/c:objc(cs)FIRQuery(im)addSnapshotListenerWithIncludeMetadataChanges:listener:) in your snapshot listener and filter out any snapshots that have the [isFromCache](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/SnapshotMetadata#isfromcache) property set to `YES`. To process complete snapshots, you’ll have to accumulate the intermediate snapshots and process them all at once.

As for the 100% CPU usage by `onWatchStreamChange`, we will analyze our usage and logic to see what optimizations we can make.

**Comment by morganchen12** [comment] 2020-08-13 20:10
Closing since this is working as intended.

**Closed by morganchen12** 2020-08-13 20:10 UTC
Labels: api: firestore
