### ISSUE TITLE
FirebaseInstanceID generates non-unique ID sometime

### ISSUE THREAD

**Issue by jayeshthadani** [firebase/firebase-ios-sdk#6578] opened 2020-09-28 06:59 UTC
Hi, 

I am using FirebaseInstanceID from Firebase iOS pod, version 5.20.1
We observed that instanceID was generated unique/same  on 3 different iOS devices.

These 3 devices were having different app installation as well, So unable to understand why same instanceID was provided for 3 different devices?

P.S: we also Firebase instance ID as well in Android app and never face such unique Instance ID issue ?

One guess I can make is we are running with older version of Firebase on iOS, But can you help confirm if such issue already exist in older version and by chance fixed in latest version ?

Thanks,

**Comment by ryanwilson** [comment] 2020-09-28 13:20
Hi @jayeshthadani - I haven't seen that issue before, but Firebase has mostly moved away from InstanceID and replaced it with FirebaseInstallations.

5.20.1 was released in March 2019, Firebase moved to a new major version in May of that year (and we're now preparing for 7.X release). The current version is 6.33.0.

Even if we were to figure out what the issue is here, I'm not certain we could do anything about it so I recommend updating to the latest Firebase version and validating the issue doesn't happen again with Installations. Thanks, and sorry for the trouble you're seeing!

**Comment by ryanwilson** [comment] 2020-09-28 13:21
cc @chliangGoogle in case there's anything else to add.

**Closed by ryanwilson** 2020-09-28 13:20 UTC
Labels: needs-triage
