### ISSUE TITLE
I can't run project in device after install firebase via Swift Packages

### ISSUE THREAD

**Issue by muaviya** [firebase/firebase-ios-sdk#6880] opened 2020-10-31 19:57 UTC
### [REQUIRED] Step 1: Describe your environment
  * iOS version: 14.1
  * Xcode version: 12.1 (12A7403)
  * Firebase SDK version: 7.0.0
  * Installation method: Swift Package Manager` (select one)
  * Firebase Component: Analytics

#### Steps to reproduce:

I can't run project in device after install firebase via Swift Packages

<img width="889" alt="Снимок экрана 2020-10-31 в 22 48 28" src="https://user-images.githubusercontent.com/4594192/97788722-0371cc80-1bcc-11eb-9795-256411005a10.png">

<img width="943" alt="Снимок экрана 2020-10-31 в 22 56 02" src="https://user-images.githubusercontent.com/4594192/97788746-43d14a80-1bcc-11eb-94f3-b0630695792e.png">

<img width="262" alt="Снимок экрана 2020-10-31 в 22 48 42" src="https://user-images.githubusercontent.com/4594192/97788751-4b90ef00-1bcc-11eb-9014-ed63571c5211.png">

**Comment by paulb777** [comment] 2020-10-31 20:42
Sorry about the issue.

This is a duplicate of #6626. See the discussion there and the ongoing discussion at #6472

**Closed by paulb777** 2020-10-31 20:42 UTC
Labels: needs-triage
