### ISSUE TITLE
We'll likely need repro steps to investigate this crash. The object being released in `objc_release` would be very helpful.

### ISSUE THREAD

**Issue by anilMakhijaEnphase** [firebase/firebase-ios-sdk#12392] opened 2024-02-15 07:30 UTC
We'll likely need repro steps to investigate this crash. The object being released in `objc_release` would be very helpful.

_Originally posted by @morganchen12 in https://github.com/firebase/firebase-ios-sdk/issues/12076#issuecomment-1802437446_

**Comment by rizafran** [comment] 2024-02-15 12:23
This seems like a duplicate of #12393. I'll be closing this as a duplicate.

**Closed by rizafran** 2024-02-15 12:23 UTC
