### ISSUE TITLE
Crashes on - [APMIdentity updateIdentifiers]

### ISSUE THREAD

**Issue by zw318** [firebase/firebase-ios-sdk#3744] opened 2019-09-02 06:49 UTC
![image](https://user-images.githubusercontent.com/48673240/64095032-3fbf5800-cd90-11e9-934b-4eb785991f6b.png)
![image](https://user-images.githubusercontent.com/48673240/64095150-96c52d00-cd90-11e9-9b1d-36fe1e807b3d.png)

please fix it.

**Comment by paulb777** [comment] 2019-09-02 15:12
Duplicate of #2575

**Closed by paulb777** 2019-09-02 15:12 UTC
Labels: needs-triage
