### ISSUE TITLE
[FIRApp defaultApp] with FCM triggers [FIRMessaging messaging] but the defaultApp is not yet initialised at this point

### ISSUE THREAD

**Issue by clausjoergensen** [firebase/firebase-ios-sdk#2950] opened 2019-05-07 05:35 UTC
* Xcode version: 10.2.1
  * Firebase SDK version:5.19.0
  * Firebase Component: Core
  * Component version: 5.19.0

The following stack will trigger this warning: `The default Firebase app has not yet been configured. Add [FIRApp configure]; (FirebaseApp.configure() in Swift) to your application initialisation. Read more: https://goo.gl/ctyzm8.` which is ironic, as the warning is being trigged by calling `[FIRApp configure` when FCM Messaging is enabled in the project.

This seems like a bug to me. And `[FIRApp configure]` is called as the first thing in `application:didFinishLaunchingWithOptions`.

```
#0	0x000000010c8f2c20 in +[FIRApp defaultApp] at Pods/FirebaseCore/Firebase/Core/FIRApp.m:192
#1	0x000000010c93028c in +[FIRMessaging messaging] at Pods/FirebaseMessaging/Firebase/Messaging/FIRMessaging.m:167
#2	0x000000010c3b5e58 in -[FIRInstanceID isFCMAutoInitEnabled] at Pods/FirebaseInstanceID/Firebase/InstanceID/FIRInstanceID.m:770
#3	0x000000010c3b5d10 in -[FIRInstanceID didCompleteConfigure] at Pods/FirebaseInstanceID/Firebase/InstanceID/FIRInstanceID.m:749
#4	0x000000010c3b5818 in -[FIRInstanceID configureInstanceIDWithOptions:app:] at Pods/FirebaseInstanceID/Firebase/InstanceID/FIRInstanceID.m:691
#5	0x000000010c3b55fc in +[FIRInstanceID configureWithApp:] at Pods/FirebaseInstanceID/Firebase/InstanceID/FIRInstanceID.m:673
#6	0x000000010c39c020 in +[FIRApp sendNotificationsToSDKs:] at Pods/FirebaseCore/Firebase/Core/FIRApp.m:427
#7	0x000000010c39a650 in +[FIRApp configureWithName:options:] at Pods/FirebaseCore/Firebase/Core/FIRApp.m:184
#8	0x000000010c39a1ec in +[FIRApp configureWithOptions:] at Pods/FirebaseCore/Firebase/Core/FIRApp.m:139
#9	0x000000010c39a118 in +[FIRApp configure] at Pods/FirebaseCore/Firebase/Core/FIRApp.m:125
```

Additional info:

`sDefaultApp` is a valid instance `<FIRApp: 0x282cbc2d0>` in `#7 +[FIRApp configureWithName:options:]` but nil at `#0 +[FIRApp defaultApp]`

**Comment by morganchen12** [comment] 2019-05-07 06:38
Do you have duplicate class implementation warnings in your app's logs?

**Comment by clausjoergensen** [comment] 2019-05-07 06:46
Yes, we have errors like `objc[41696]: Class FIRAnalyticsConnector is implemented in both InternalFrameworkA.framework/InternalFrameworkA (0x114961c20) and InternalFrameworkB.framework/InternalFrameworkB (0x1143b30e0). One of the two will be used. Which one is undefined.` for all the Firebase classes as we link it dynamically (with Pods) in two internal frameworks, which are then (also dynamically) linked into the main app.

I've been trying to solve that for a while, but we haven't been able to use the CocoaPods static swift library option yet. But I also never really understand why Firebase had this problem to begin with, since this is normally not an issue for dynamically linked framework.

**Comment by paulb777** [comment] 2019-05-07 14:08
Firebase uses statically linked frameworks and requires that any shared frameworks that link it also be static.

**Comment by clausjoergensen** [comment] 2019-05-07 14:40
Right, but it wasn't obvious that the FIRApp static instance problem would be related to the fact you're still using static linked frameworks.

Unfortunately we can't consume it as a static CocoaPod, because various frameworks (but most notoriously gRPC) doesn't support it yet. 

Firebase should probably be removed from CocoaPods given how many people keep reporting issues like #2707.

**Comment by paulb777** [comment] 2019-05-07 14:55
@clausjoergensen Firebase IS a set of static CocoaPods. And it's ok for a static library to depend on a dynamic library, so depending on gRPC works fine with Firebase.

The issue is that a library that depends on Firebase must be static. In your example, `InternalFramework` must be static to depend on Firebase.

The vast majority of iOS Firebase developers successfully access it via CocoaPods.  The experience is fine for app development.  Library development can be a bit challenging, but since CocoaPods 1.4.0, that experience also works as long as library developers build static libraries and/or work through the implications of static and dynamic linking.

**Comment by morganchen12** [comment] 2019-05-08 18:27
Closing since this seems to be a case of linking confusion and not an issue with Firebase. Please feel free to continue discussion here if your confusion is not resolved.

**Closed by morganchen12** 2019-05-08 18:27 UTC
Labels: type: question
