### ISSUE TITLE
Remove UIWebView references per ITMS-90809

### ISSUE THREAD

**Issue by xaphod** [firebase/firebase-ios-sdk#3779] opened 2019-09-05 07:11 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.7.0
  * Firebase Component: **DynamicLinks**
  * Component version: 4.0.3

### [REQUIRED] Step 3: 
This component references (allocs) **UIWebView**, which per ITMS-90809 is deprecated and throws warnings on app submission.

Specifically, see (only) `FIRDLJavaScriptExecutor.m`.

I am not sure if anyone is building apps on iOS 7 anymore when iOS 13 is right around the corner, but I am sure that Apple is going to soon start flat-out rejecting apps that instantiate UIWebViews (or make it a compile error in iOS 13 final, no clue).

Please remove all references to UIWebView, thanks!

**Comment by paulb777** [comment] 2019-09-05 14:09
Duplicate of #3722. The fix is going out in this weeks Firebase 6.8.0 (M55) release

**Closed by paulb777** 2019-09-05 14:09 UTC
Labels: api: dynamiclinks

**Comment by xaphod** [comment] 2019-09-05 14:45
Thanks and sorry: I forgot to search closed issues (didn't occur to me). Lesson learned.
