### ISSUE TITLE
tvOS Cloud-Synced Auth

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#8878] opened 2021-10-28 19:42 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.9.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth

#### Steps to reproduce:

Following [this](https://github.com/firebase/firebase-ios-sdk/pull/6924#issuecomment-772604212), I do share Auth over iCloud Keychain sync between iOS and macOS apps successfully.

However, if I try this with tvOS, it does not work. Does tvOS maybe not support Keychain Sharing?

Officially, tvOS supports it but there are some other users with [issues](https://developer.apple.com/forums/thread/18480).

I wonder if there could be an issue with Firebase's keychain access implementation.

#### Relevant Code:

```

    var tempUser: Firebase.User?
    do {
      try tempUser = Auth.auth().getStoredUser(forAccessGroup: accessGroupId)
    } catch let error as NSError {
      print("Error getting stored user: %@", error)
    }
    return tempUser // always nil
```

**Comment by nidegen** [comment] 2021-12-11 15:51
@ncooke3 any news here? Is this even supposed to be working?

**Comment by ncooke3** [comment] 2021-12-12 23:35
Hi @nidegen, apologies for the delay. No updates as of now. I'll look into it this week and report back.

**Comment by nidegen** [comment] 2021-12-13 08:19
No worries, thank you!

**Comment by weixifan** [comment] 2021-12-29 12:53
I filed an internal b/212482016 to track this.

**Comment by nidegen** [comment] 2021-12-30 07:19
nice! @weixifan so you can confirm this is not only an issue on my side, right?

**Comment by nidegen** [comment] 2022-01-18 16:40
Hi guys, how is it looking? Can you confirm this is a real bug?

**Comment by ncooke3** [comment] 2022-01-19 17:59
Hi @nidegen, sincere apologies for the delay. I'm working on reproducing the issue today. I have some questions:
1. Do you have an entitlements file associated with your tvOS target? Could you confirm that its contents match/correspond to that of your other targets?
2. Is an error being thrown? If so, could you share the underlying error message?
Thanks!

**Comment by nidegen** [comment] 2022-01-19 18:26
No worries! Unfortunately I am pretty sure everything is correct. I have it running for iOS and macOS. The thing is however that I am not sure if it is at all possible on tvOS. Some forum posts indicate that it could be unsupported: https://developer.apple.com/forums/thread/690714

So, I am still not sure if I should expect an error on my side or if I should give up:)

**Comment by nidegen** [comment] 2022-01-19 19:56
P.S.: There is no error, just `nil` on `Auth.auth().getStoredUser(forAccessGroup: accessGroupId)`

**Comment by ncooke3** [comment] 2022-01-20 21:31
Hi @nidegen,

I was able to reproduce the issue without using Firebase. I created three apps: an iOS app, a macOS app, and a tvOS app. I followed Apple's [Sharing Access to Keychain Items Among a Collection of Apps](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps?language=objc) documentation.

I was able to share and sync password data between iOS and macOS but couldn't get tvOS to work either. The underlying error code I'm seeing from the Apple's Security framework is `-25300`. This code is an `errSecItemNotFound` which I believe explains why Firebase is returning a `nil` user in your case.

I reproduced on a tvOS simulator. Are you using a physical tvOS device or the simulator?

**Comment by nidegen** [comment] 2022-01-20 21:40
Great but not great 😅 I tested both on a physical device but it seemed to behave the same. I tested with 8.11. as I hoped the macOS extension keychain fix would help on tvOS, but it remained the same.

**Comment by ncooke3** [comment] 2022-01-20 22:38
Ah, I was hoping that testing on a physical tvOS device would work but I guess not :(  Thanks for the thorough investigation.

It appears then that this issue isn't caused by Firebase and seems to be more on Apple's side– which is quite confusing since Apple's documentation indicates that this should be supported. 🤔 

I think the next step would be to file feedback with Apple as this seems like unexpected behavior. I'm going to close this issue but I'm happy to continue the conversation.

**Closed by ncooke3** 2022-01-20 22:38 UTC
Labels: api: auth, tvOS, internal-bug-filed

**Comment by nidegen** [comment] 2022-01-21 07:56
Yes, that confirms my suspicion. Should I file an Apple feedback? Can you maybe share your MWE?

**Comment by ncooke3** [comment] 2022-01-21 18:20
I'm packaging up my MWE and will share it when ready. I'll also file a feedback.

**Comment by nidegen** [comment] 2022-01-22 19:42
Done on a real Apple TV 4k. Same behaviour unfortunately.

<img width="849" alt="Screenshot 2022-01-22 at 20 39 20" src="https://user-images.githubusercontent.com/8779423/150653227-b8e35058-7621-4c85-b8d0-67dece662e35.png">

**Comment by ncooke3** [comment] 2022-01-22 22:16
Thanks a lot @nidegen– I appreciate the help! I filed a radar with Apple on my end. Hopefully we can get an answer for the community about keychain sharing on tvOS.  I'll keep this thread updated.

**Comment by nidegen** [comment] 2022-01-23 09:25
Great, did the same. Hope it will get fixed soon.

As a side note, while shared keychain is awesome I would be able to circumvent it if Phone Auth was available on tvOS too (macOS would be nice too). Would be great to see this happen too:)

**Comment by nidegen** [comment] 2022-01-27 07:31
Unfortunately, Apple updated the docs indicating tvOS is not supposed to sync over iCloud:( https://developer.apple.com/forums/thread/690714?answerId=702729022#702729022

**Comment by ncooke3** [comment] 2022-01-27 14:56
Thanks for the update! That is indeed unfortunate. Hopefully support is added in the future. 🤞
