### ISSUE TITLE
[6.34-spm-beta] Array Union issues

### ISSUE THREAD

**Issue by EliteTechnicalCare** [firebase/firebase-ios-sdk#6680] opened 2020-10-07 02:52 UTC
Array union with a singular object works fine, however it does not work with multiple objects 

```
var itemDataArray = [[String:Any]]()
            
            for _ in 1...itemQty {
                itemDataArray.append(itemData) //In our app this will add 10 items to the array
            }
            
            fs.collection("Accounts").document(playerUID).collection("Bag").document("Items").setData(["Inventory":FieldValue.arrayUnion(itemDataArray)], merge: true) { (error) in
                if let error = error {
                    errorMsg(error.localizedDescription, s: vc)
                    return
                }
            }
```

This will only add one item in the array on Firestore and ignore the rest

**Comment by thebrianchen** [comment] 2020-10-07 17:20
@EliteTechnicalCare Could you provide a small reproduction app or code snippet that reproduces this behavior, or enable [verbose logging](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:) and share the logs from a local reproduction?

Also, note that duplicate entries in the union array are only added once.

**Comment by EliteTechnicalCare** [comment] 2020-10-07 19:46
> Also, note that duplicate entries in the union array are only added once.

Ah so this is the issue then. Is there any way to disable this behavior?

**Comment by thebrianchen** [comment] 2020-10-07 20:09
> Ah so this is the issue then. Is there any way to disable this behavior?

`ArrayUnion` and `ArrayRemove` treat the array as a set, so unfortunately there is no way to disable the de-duping of your array. Depending on your use case, you would either have to read the document, add the duplicate elements, and write the document back, or slightly alter the data like you mentioned. I'm going to close this issue since we don't have plans to change the current behavior of FieldValues in that regard, but feel free to ask any other questions you may have!

**Closed by thebrianchen** 2020-10-07 20:09 UTC
Labels: api: firestore, needs-attention
