### ISSUE TITLE
Main thread crashing

### ISSUE THREAD

**Issue by tapanshah1** [firebase/firebase-ios-sdk#5068] opened 2020-03-11 05:37 UTC
PODS:
  - CocoaAsyncSocket (7.6.3)
  - CocoaLumberjack (3.6.0):
    - CocoaLumberjack/Core (= 3.6.0)
  - CocoaLumberjack/Core (3.6.0)
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - Fabric (1.10.2)
  - Firebase (6.15.0):
    - Firebase/Core (= 6.15.0)
  - Firebase/AdMob (6.15.0):
    - Firebase/CoreOnly
    - Google-Mobile-Ads-SDK (~> 7.50)
  - Firebase/Analytics (6.15.0):
    - Firebase/Core
  - Firebase/Auth (6.15.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.4.2)
  - Firebase/Core (6.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.2.1)
  - Firebase/CoreOnly (6.15.0):
    - FirebaseCore (= 6.6.0)
  - Firebase/Messaging (6.15.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.2.0)
  - FirebaseAnalytics (6.2.1):
    - FirebaseCore (~> 6.6)
    - FirebaseInstanceID (~> 4.3)
    - GoogleAppMeasurement (= 6.2.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseAuth (6.4.2):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.6.0):
    - FirebaseCoreDiagnostics (~> 1.2)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.2.0):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseInstallations (1.1.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.3.0):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
  - FirebaseMessaging (4.2.0):
    - FirebaseAnalyticsInterop (~> 1.5)
    - FirebaseCore (~> 6.6)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Reachability (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseUI/Auth (8.4.0):
    - Firebase/Auth (~> 6.0)
    - GoogleUtilities/UserDefaults
  - FirebaseUI/Phone (8.4.0):
    - FirebaseUI/Auth
  - FLAnimatedImage (1.0.12)
  - Google-Mobile-Ads-SDK (7.53.1):
    - GoogleAppMeasurement (~> 6.0)
  - GoogleAppMeasurement (6.2.1):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - GoogleDataTransport (3.3.0)
  - GoogleDataTransportCCTSupport (1.3.0):
    - GoogleDataTransport (~> 3.3)
    - nanopb (~> 0.3.901)
  - GoogleUtilities/AppDelegateSwizzler (6.5.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.5.0)
  - GoogleUtilities/Logger (6.5.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.5.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.5.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.5.0)"
  - GoogleUtilities/Reachability (6.5.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.5.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.3.1)
  - IQAudioRecorderController (1.2.3):
    - SCSiriWaveformView
  - KissXML (5.3.1):
    - KissXML/All (= 5.3.1)
  - KissXML/Additions (5.3.1):
    - KissXML/Core
  - KissXML/All (5.3.1):
    - KissXML/Additions
    - KissXML/Core
  - KissXML/Core (5.3.1)
  - libidn (1.35)
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - PromisesObjC (1.2.8)
  - Protobuf (3.11.2)
  - SCSiriWaveformView (1.1.1)
  - SVProgressHUD (2.2.5)
  - TwitterCore (2.8.0):
    - Fabric
  - TwitterKit (2.8.1):
    - TwitterCore (>= 2.8)
  - UICKeyChainStore (2.1.2)
  - XMPPFramework (4.0.0):
    - XMPPFramework/default (= 4.0.0)
  - XMPPFramework/default (4.0.0):
    - CocoaAsyncSocket (~> 7.6)
    - CocoaLumberjack
    - KissXML (~> 5.2)
    - libidn (~> 1.35)

DEPENDENCIES:
  - Crashlytics
  - Fabric
  - Firebase
  - Firebase/AdMob
  - Firebase/Analytics
  - Firebase/Auth
  - Firebase/Messaging
  - FirebaseUI/Phone
  - FLAnimatedImage (~> 1.0)
  - IQAudioRecorderController
  - SVProgressHUD
  - TwitterKit
  - UICKeyChainStore
  - XMPPFramework

SPEC REPOS:
  trunk:
    - CocoaAsyncSocket
    - CocoaLumberjack
    - Crashlytics
    - Fabric
    - Firebase
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebaseUI
    - FLAnimatedImage
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleUtilities
    - GTMSessionFetcher
    - IQAudioRecorderController
    - KissXML
    - libidn
    - nanopb
    - PromisesObjC
    - Protobuf
    - SCSiriWaveformView
    - SVProgressHUD
    - TwitterCore
    - TwitterKit
    - UICKeyChainStore
    - XMPPFramework

SPEC CHECKSUMS:
  CocoaAsyncSocket: eafaa68a7e0ec99ead0a7b35015e0bf25d2c8987
  CocoaLumberjack: 78b0c238666f4f58db069738ec176f4519557516
  Crashlytics: 540b7e5f5da5a042647227a5e3ac51d85eed06df
  Fabric: 706c8b8098fff96c33c0db69cbf81f9c551d0d74
  Firebase: 5d77105d9740a07ca6b16927ca971db7e860faaf
  FirebaseAnalytics: e83e64b1231dedcd9ddd4bdecd9bcfd6ba341679
  FirebaseAnalyticsInterop: 3f86269c38ae41f47afeb43ebf32a001f58fcdae
  FirebaseAuth: ce45d7c5d46bed90159f3a73b6efbe8976ed3573
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: 4aeb81ff53dcd9a3634ca725dc1fb8c2a4622046
  FirebaseCoreDiagnostics: 5e78803ab276bc5b50340e3c539c06c3de35c649
  FirebaseCoreDiagnosticsInterop: 296e2c5f5314500a850ad0b83e9e7c10b011a850
  FirebaseInstallations: 575cd32f2aec0feeb0e44f5d0110a09e5e60b47b
  FirebaseInstanceID: 6668efc1655a4052c083f287a7141f1ead12f9c2
  FirebaseMessaging: 448cf4c727f3c95f4f90816907d67306ba785cfe
  FirebaseUI: 433550cb9e3d03ec7ee2c25f87493f76358d9b68
  FLAnimatedImage: 4a0b56255d9b05f18b6dd7ee06871be5d3b89e31
  Google-Mobile-Ads-SDK: fac081606dbd438d8db57198b83ba8b5f875a601
  GoogleAppMeasurement: a08a43b8677b95ed51fcef880e36737334d804fd
  GoogleDataTransport: 574a983e829327d7c18f2627f65d9e80164ea8a4
  GoogleDataTransportCCTSupport: cad3cd6cdbdbad6b5c2c9206ec413402755faaaa
  GoogleUtilities: f8de7ddf8c706f58e9b405d53e38bbdaa2731e5a
  GTMSessionFetcher: cea130bbfe5a7edc8d06d3f0d17288c32ffe9925
  IQAudioRecorderController: 69a67c2e0b87bd8746cbb4de175fd7a0bf820009
  KissXML: 5c8e0f2e8b9f071d3e1ae123dec3eb5da615c10c
  libidn: e4576a956b797c584c77aaedfc6e3dd639b61bdc
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  PromisesObjC: c119f3cd559f50b7ae681fa59dc1acd19173b7e6
  Protobuf: dd1aaea7140debfe4dd0683fb8ef208e527ae153
  SCSiriWaveformView: 15b9dd6f94c7536e2032b34a35c6ff74d38c7411
  SVProgressHUD: 1428aafac632c1f86f62aa4243ec12008d7a51d6
  TwitterCore: e959987be23c767004d29eb7fab8d85d8585a2e5
  TwitterKit: 3b6044a7320340326a4098f3e37aa1dbaeb94942
  UICKeyChainStore: 85db518bb1d294366d15ec9b92a416c4e670518f
  XMPPFramework: 5d31ff9f73dce031b24bc49bcf88093627a3a86e

PODFILE CHECKSUM: ed1b1844bfdf5a4be98801f24d0a8d50556e0231

[issue_crash_.txt](https://github.com/firebase/firebase-ios-sdk/files/4316222/issue_crash_.txt)

**Comment by tapanshah1** [comment] 2020-03-11 05:38
Please find attached file.

**Comment by morganchen12** [comment] 2020-03-11 06:05
Here's the crashed thread:

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1b1c7c96c __exceptionPreprocess
1  libobjc.A.dylib                0x1b1995028 objc_exception_throw
2  Foundation                     0x1b21685e0 -[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints]
3  Foundation                     0x1b1f618c4 -[NSISEngine _optimizeWithoutRebuilding]
4  Foundation                     0x1b1f617d8 -[NSISEngine optimize]
5  Foundation                     0x1b1f61448 -[NSISEngine performPendingChangeNotifications]
6  UIKitCore                      0x1b620a824 -[UIView(Hierarchy) layoutSubviews]
7  UIKitCore                      0x1b621db1c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
8  libobjc.A.dylib                0x1b1990a4c -[NSObject performSelector:withObject:]
9  QuartzCore                     0x1b8833a9c -[CALayer layoutSublayers]
10 QuartzCore                     0x1b8833eec CA::Layer::layout_if_needed(CA::Transaction*)
11 QuartzCore                     0x1b8846614 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
12 QuartzCore                     0x1b878b1c4 CA::Context::commit_transaction(CA::Transaction*, double)
13 QuartzCore                     0x1b87b5fd0 CA::Transaction::commit()
14 QuartzCore                     0x1b87b6ba4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
15 CoreFoundation                 0x1b1bf7524 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
16 CoreFoundation                 0x1b1bf21c4 __CFRunLoopDoObservers
17 CoreFoundation                 0x1b1bf2774 __CFRunLoopRun
18 CoreFoundation                 0x1b1bf1f40 CFRunLoopRunSpecific
19 WebCore                        0x1b9db88f0 RunWebThread(void*)
20 libsystem_pthread.dylib        0x1b1985840 _pthread_start
21 libsystem_pthread.dylib        0x1b198d9f4 thread_start
```

Looks like autolayout is crashing your app somehow. There are no Firebase symbols in the crashing thread's stack trace, so I'm going to close this issue.

If you're able to reproduce this crash locally, the exception message should contain some additional info that may help you debug this.

**Closed by morganchen12** 2020-03-11 06:05 UTC
Labels: type: question
