### ISSUE TITLE
macOS target cannot build with Firebase version 10.23.1

### ISSUE THREAD

**Issue by anosidium** [firebase/firebase-ios-sdk#12701] opened 2024-04-04 13:57 UTC
### Description

I have a macOS Cocoa app and I updated Firebase to version 10.23.1 and it immediately failed with these warnings:

> Command CodeSign failed with a nonzero exit code

>Couldn't resolve framework symlink for '/Users/JohnAppleseed/Library/Developer/Xcode/DerivedData/MyApp-bnecjqkjbdbylgeoluktplyutzlr/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurementIdentitySupport/GoogleAppMeasurementIdentitySupport.xcframework/macos-arm64_x86_64/GoogleAppMeasurementIdentitySupport.framework/Versions/Current': readlink(/Users/JohnAppleseed/Library/Developer/Xcode/DerivedData/MyApp-bnecjqkjbdbylgeoluktplyutzlr/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurementIdentitySupport/GoogleAppMeasurementIdentitySupport.xcframework/macos-arm64_x86_64/GoogleAppMeasurementIdentitySupport.framework/Versions/Current): Invalid argument (22)

>Couldn't resolve framework symlink for '/Users/JohnAppleseed/Library/Developer/Xcode/DerivedData/MyApp-bnecjqkjbdbylgeoluktplyutzlr/SourcePackages/artifacts/firebase-ios-sdk/FirebaseAnalytics/FirebaseAnalytics.xcframework/macos-arm64_x86_64/FirebaseAnalytics.framework/Versions/Current': readlink(/Users/JohnAppleseed/Library/Developer/Xcode/DerivedData/MyApp-bnecjqkjbdbylgeoluktplyutzlr/SourcePackages/artifacts/firebase-ios-sdk/FirebaseAnalytics/FirebaseAnalytics.xcframework/macos-arm64_x86_64/FirebaseAnalytics.framework/Versions/Current): Invalid argument (22)

>Couldn't resolve framework symlink for '/Users/JohnAppleseed/Library/Developer/Xcode/DerivedData/MyApp-bnecjqkjbdbylgeoluktplyutzlr/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurement/GoogleAppMeasurement.xcframework/macos-arm64_x86_64/GoogleAppMeasurement.framework/Versions/Current': readlink(/Users/JohnAppleseed/Library/Developer/Xcode/DerivedData/MyApp-bnecjqkjbdbylgeoluktplyutzlr/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurement/GoogleAppMeasurement.xcframework/macos-arm64_x86_64/GoogleAppMeasurement.framework/Versions/Current): Invalid argument (22)

I tried:

- Build.
- Clean Build Folder.
- Deleting Project Build Data and Indexes.
- Deleting `/MyApp/MyApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` file.

None of that helped.

When I reverted Firebase to 10.23.0 using the "Exact Version" in Package Dependencies, it works perfectly fine. I have not submitted it to App Store Connect, I hope that it will pass the build processing. I was able to run the app locally on my Mac computer.

### Reproducing the issue

1. Update Firebase to version 10.23.1 using Swift Package Manager.
2. Try to run the app locally on the Mac computer.
3. Can't run the app because of aforementioned warnings.

### Firebase SDK Version

10.23.1

### Xcode Version

Version 15.3 (15E204a)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment] 2024-04-04 14:31
Hi @anosidium, thanks for reporting. There is a dupe of https://github.com/firebase/firebase-ios-sdk/issues/12668. there is a manual workaround described in https://github.com/firebase/firebase-ios-sdk/issues/12668#issue-2216710400's OP that may unblock you until 10.24.0 is released (due out next week).

**Closed by ncooke3** 2024-04-04 14:31 UTC
Labels: needs-triage
