### ISSUE TITLE
React Native iOS & Native iOS Analytics Build Failure

### ISSUE THREAD

**Issue by SaraChicaD** [firebase/firebase-ios-sdk#7566] opened 2021-02-19 17:17 UTC
### Step 1: Describe your environment

  * Xcode version: `12.3`
  * Firebase SDK version: on iOS whatever the version is [here](https://github.com/firebase/quickstart-ios/tree/master/analytics); for `@react-native-firebase/app` & `@react-native-firebase/analytics` it's `10.8.0`
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics

### Step 2: Describe the problem

I am a React Native developer utilizing `@react-native-firebase`, specifically for Analytics, and have successfully integrated it in Android, however have been unable to do so due to some strange errors on iOS. The problem is detailed [here](https://github.com/invertase/react-native-firebase/issues/4917#issue-809569330), there is a React Native example [here](https://github.com/SaraChicaD/FBAnalyticsTest).

#### Steps to reproduce:
1.) For [React Native](https://github.com/SaraChicaD/FBAnalyticsTest), run the install script: `yarn install && cd ios && pod install && cd .. && npm run ios`. You'll get this error:

```
▸ Touching RNFBApp.framework (in target 'RNFBApp' from project 'Pods')
▸ Processing RNFBAnalytics-Info.plist
▸ Linking RNFBAnalytics

❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_FIRAnalytics
> Referenced from: objc-class-ref in RNFBAnalyticsModule.o



❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
2.) When I utilized the iOS Analytics quickstart with `use_frameworks!` via XCode I got this error:

<img width="865" alt="error" src="https://user-images.githubusercontent.com/6945122/108536720-60d87900-72a2-11eb-82b5-5be66d2b5a03.png">

You can see my iOS repo [here](https://github.com/SaraChicaD/FirebaseAnalyticsiOSTest/tree/master).

The conversation I had on the React Native repo revolved around `use_frameworks`, as you can see [here](https://github.com/invertase/react-native-firebase/issues/4917#issuecomment-780722476).

#### Relevant Code:
In `/ios/Podfile`
```
use_frameworks!
```

**Comment by paulb777** [comment] 2021-02-19 22:55
The xcworkspace at https://github.com/SaraChicaD/FirebaseAnalyticsiOSTest/tree/master builds fine for me. I'm guessing there is something strange about the environment, but not sure what.

**Comment by SaraChicaD** [comment] 2021-02-19 23:14
Hi @paulb777 thanks, I can't get the `.xcodeproj` to run, that's what fails, do you have any leads on why one would build and the other won't? The default of the `@react-native-firebase` library fails for me the same way when I add Analytics -- so it's not just my app's environment -- so there's really nothing I can do on the Javascript end. Any ideas would be helpful.

> The xcworkspace at https://github.com/SaraChicaD/FirebaseAnalyticsiOSTest/tree/master builds fine for me. I'm guessing there is something strange about the environment, but not sure what.

**Comment by paulb777** [comment] 2021-02-19 23:18
Hi @SaraChicaD With CocoaPods, you should use the generated `.xcworkspace` not the `.xcodeproj`. to build and run.

**Comment by SaraChicaD** [comment] 2021-02-19 23:22
Thank you. The build is failing from the command line, via Pods, so I’m assuming that’s all firing correctly. I’m not an iOS developer so I was just trying to generate an example per the request of the JS maintainer. Again, any thoughts on these errors would be really helpful. 

> Hi @SaraChicaD With CocoaPods, you should use the generated `.xcworkspace` not the `.xcodeproj`. to build and run.

**Comment by paulb777** [comment] 2021-02-19 23:29
What is the command line?

**Comment by morganchen12** [comment] 2021-02-19 23:30
I was unable to build the react native project because my computer doesn't have the right set of devtools installed, but are you able to extract the xcodebuild invocation log from the `npm run ios` command?

**Comment by SaraChicaD** [comment] 2021-02-19 23:37
for context you can see step 1 in my issue:

yarn install && cd ios && pod install && cd .. && npm run ios

> What is the command line?

**Comment by SaraChicaD** [comment] 2021-02-22 18:49
@morganchen12 this is what i got from my `react-native` [project](https://github.com/SaraChicaD/FBAnalyticsTest) when i ran the `.xcworkspace`:

```
Ld /Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/RNFBAnalytics/RNFBAnalytics.framework/RNFBAnalytics normal (in target 'RNFBAnalytics' from project 'Pods')
    cd /Users/saraines/Desktop/FBAnalyticsTest/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios10.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -L/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/RNFBAnalytics -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/RNFBAnalytics -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/DoubleConversion -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/FirebaseCore -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/FirebaseCoreDiagnostics -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/FirebaseInstallations -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/Folly -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/GoogleDataTransport -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/GoogleUtilities -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/PromisesObjC -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/RNFBApp -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/React-Core -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/React-cxxreact -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/React-jsi -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/React-jsiexecutor -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/React-jsinspector -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/Yoga -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/glog -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/nanopb -F/Users/saraines/Desktop/FBAnalyticsTest/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/saraines/Desktop/FBAnalyticsTest/ios/Pods/GoogleAppMeasurement/Frameworks -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FirebaseAnalytics -F/Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleAppMeasurement -filelist /Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFBAnalytics.build/Objects-normal/x86_64/RNFBAnalytics.LinkFileList -install_name @rpath/RNFBAnalytics.framework/RNFBAnalytics -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFBAnalytics.build/Objects-normal/x86_64/RNFBAnalytics_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework StoreKit -framework Foundation -framework React -framework RNFBApp -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFBAnalytics.build/Objects-normal/x86_64/RNFBAnalytics_dependency_info.dat -o /Users/saraines/Library/Developer/Xcode/DerivedData/FBAnalyticsTest-bynqnyvddaqhrwghtgmsiczqsrhh/Build/Products/Debug-iphonesimulator/RNFBAnalytics/RNFBAnalytics.framework/RNFBAnalytics

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in RNFBAnalyticsModule.o
ld: symbol(s) not found for architecture x86_64
```

Here's a screenshot:

![Screen Shot 2021-02-22 at 12 48 31 PM](https://user-images.githubusercontent.com/6945122/108754997-4bff1e00-750c-11eb-993b-0f55c32e1dc5.png)


> I was unable to build the react native project because my computer doesn't have the right set of devtools installed, but are you able to extract the xcodebuild invocation log from the `npm run ios` command?

**Comment by morganchen12** [comment] 2021-02-23 22:32
Thanks, this screenshot helps narrow the issue down a little. The error occurs in linking the React Native Analytics module, which is totally outside of (and must occur before) your app's build/link process. Setting up the correct target structure and build/link flags is something CocoaPods is supposed to take care of for you, and though it looks like it's setting up the correct framework search path, the Analytics object symbol is still not being found.

Can you run `pod install` in the `ios` directory of the test project and push your changes there so I can build from Xcode directly?

**Comment by SaraChicaD** [comment] 2021-02-23 23:13
Hi @morganchen12 thank you so much, _really_ appreciate your reply! I went ahead and did just that in [this commit](https://github.com/SaraChicaD/FBAnalyticsTest/commit/24b7b989f61aae0583fd73bfb755e1ba9aae0a36).

> Thanks, this screenshot helps narrow the issue down a little. The error occurs in linking the React Native Analytics module, which is totally outside of (and must occur before) your app's build/link process. Setting up the correct target structure and build/link flags is something CocoaPods is supposed to take care of for you, and though it looks like it's setting up the correct framework search path, the Analytics object symbol is still not being found.
> 
> Can you run `pod install` in the `ios` directory of the test project and push your changes there so I can build from Xcode directly?

**Comment by morganchen12** [comment] 2021-02-27 00:21
After a lot of messing with the project, I haven't reached any meaningful conclusions. I was able to get a _different_ linker error by running `npm audit fix --force` at the root, and it looks like based on my searches on StackOverflow others were able to resolve those errors by clearing various build caches.

**Comment by mikehardy** [comment] 2021-03-01 20:11
Hello firebase-ios-sdk folks, I was the working with @SaraChicaD in the react-native-firebase repo on this, and I'm just catching up with the investigation over here. My goal there was to generate reproducible examples and *it appeared* that we had a reproducible failure using nothing but the firebase-ios-sdk ios quickstart though I did not personally attempt reproduction, so I thought it best to continue here.

May be that the issue reproducing with firebase-ios-sdk analytics quickstart was use of .xcodeproj vs .xcodeworkspace as it appears @paulb777 runs the quickstart fine

Continuing on the assumption that's correct and firebase-ios-sdk quickstart is fine, then I think yes, it goes back to react-native-firebase for reproduction. We had a mostly scripted repro based on it so we should be able to hunt this down. It appears it's time for me to actually attempt the reproduction myself to see what's going on!

The issues are all cross-linked so I won't forget to report back after checking it out

**Comment by mikehardy** [comment] 2021-03-03 22:13
I am still working on isolating the issue in @SaraChicaD 's actual project(s) but I can confirm a successful build + run with firebase-ios-sdk + react-native-firebase in Podfile `config = use_frameworks!` mode

https://github.com/mikehardy/rnfbdemo/commit/8f7a33921e77c882398fb1c607c0a6eee4501e70

This piece of documentation was the missing magic: https://rnfirebase.io/#allow-ios-static-frameworks

**Comment by paulb777** [comment] 2021-03-03 22:35
@mikehardy Thanks for the update. I'll close this issue, but feel free to add more comments if there's anything else for here.

**Closed by paulb777** 2021-03-03 22:35 UTC
Labels: api: analytics, react-native
