### ISSUE TITLE
Crashed: com.google.perf.FPREventsQueue (EXC_BAD_ACCESS KERN_INVALID_ADDRESS)

### ISSUE THREAD

**Issue by rahulOYO** [firebase/firebase-ios-sdk#4399] opened 2019-11-26 05:23 UTC
**[REQUIRED] Step 2: Describe your environment**
  * Xcode version: 10.3
  * Firebase SDK version: 6.13.0
  * Firebase Component: (Core, Performance)

Here is the snapshot for all firebase related versions:

```
- Firebase/Core (6.13.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.6)
  - Firebase/CoreOnly (6.13.0):
    - FirebaseCore (= 6.4.0)
  - Firebase/Performance (6.13.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.7)
  - FirebaseABTesting (3.1.2):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseAnalytics (6.1.6):
    - FirebaseCore (~> 6.4)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.6)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseAnalyticsInterop (1.4.0)
  - FirebaseCore (6.4.0):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnostics (1.1.1):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.1.0)
  - FirebaseInstanceID (4.2.7):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebasePerformance (3.1.7):
    - FirebaseCore (~> 6.4)
    - FirebaseInstanceID (~> 4.2)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.4.5):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
    - Protobuf (>= 3.9.2, ~> 3.9)
```

#### Steps to reproduce:

Although I can't reproduce the crash but I am getting a lot of crashes for my app on Crashlytics and those are in this queue only.

Stack trace of the FPREventQueue thread
```
Crashed: com.google.perf.FPREventsQueue
0  libobjc.A.dylib                0x189a52f70 objc_msgSend
1  CoreFoundation                 0x18aedf890 CFEqual
2  CoreFoundation                 0x18aedb2e8 CFBasicHashFindBucket
3  CoreFoundation                 0x18aedb130 CFDictionaryGetValue
4  (Missing)                      0x10c25377c (Missing)
5  (Missing)                      0x10c236530 (Missing)
6  our-app                        0x100fa7644 FPRGetApplicationInfoMessage
7  our-app                        0x100fa747c FPRGetPerfMetricMessage
8  our-app                        0x100fa5720 __29-[FPRClient logNetworkTrace:]_block_invoke
9  libdispatch.dylib              0x189e921fc _dispatch_call_block_and_release
10 libdispatch.dylib              0x189e921bc _dispatch_client_callout
11 libdispatch.dylib              0x189ea012c _dispatch_queue_serial_drain
12 libdispatch.dylib              0x189e959a4 _dispatch_queue_invoke
13 libdispatch.dylib              0x189ea234c _dispatch_root_queue_drain
14 libdispatch.dylib              0x189ea20ac _dispatch_worker_thread3
15 libsystem_pthread.dylib        0x18a09b2a0 _pthread_wqthread
16 libsystem_pthread.dylib        0x18a09ad8c start_wqthread
```

**Comment by visumickey** [comment] 2019-11-26 14:57
@rahulOYO Do you have any details about the pattern of these crashes? Does this happen only on a particular iOS version, or particular set of devices?

Also, any idea on the volume of this crash? At this time my guess is that this crash is related to the Protobuf packaging. Will continue to investigate more to see what could have caused this crash.

**Comment by rahulOYO** [comment] 2019-11-27 12:18
Hi,
It's on all iOS Versions:

iOS 12: 92%
iOS 11: 5%
iOS 10: 3%

The volume is quite less as of now, but its under the top crashes.
70 crashes to 53 Users

**Comment by visumickey** [comment] 2020-01-13 22:02
@rahulOYO  Can you share all the threads that were active during the time of crash? We are guessing a probable race condition in fetching a cached value that is leading to this crash. I'm suspecting this to be a duplicate of the github issue #4400. Depending on the stack trace will decide and mark this as a duplicate of each other.

**Comment by rahulOYO** [comment] 2020-01-23 09:09
Hi Team,

This crash is not occurring now. I will let you know if got reproduced again.
For now please close this issue.

Thanks

**Closed** 2020-01-23 13:18 UTC
Labels: api: performance
