### ISSUE TITLE
warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/iamc/Downloads/ios12/Libraries/libiPhone-lib.a

### ISSUE THREAD

**Issue by lizehuiyy** [firebase/firebase-ios-sdk#10687] opened 2023-01-14 06:54 UTC
### Description

I am a novice ios developer，I imported from unity to ios and imported 10.3.0 firebase library in unity. I don't know if it matters. I used cocoapods in xcode and installed firebase

Before the error is reported, I will be prompted to set the library file build setting Enable Bitcode to yes
Other libraries report errors. If I change enable bitcode to yes, I will not be prompted
But this question, yes or no, is useless

### Firebase SDK Version

10.3.0

### Xcode Version

14.2.0

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/iamc/Downloads/ios12/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: '/Users/iamc/Library/Developer/Xcode/DerivedData/Unity-iPhone-hjsciuwsfgvxhlftggavshljyifa/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics(FIRAnalytics.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/iamc/Library/Developer/Xcode/DerivedData/Unity-iPhone-hjsciuwsfgvxhlftggavshljyifa/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics' for architecture arm64
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```
PODS:
  - AppsFlyerFramework (6.8.1):
    - AppsFlyerFramework/Main (= 6.8.1)
  - AppsFlyerFramework/Main (6.8.1)
  - FacebookGamingServices (11.2.1):
    - FBSDKCoreKit (~> 11.2.1)
    - FBSDKCoreKit_Basics (~> 11.2.1)
    - LegacyGamingServices (~> 11.2.1)
  - FBAEMKit (11.2.1):
    - FBAEMKit/AEM (= 11.2.1)
  - FBAEMKit/AEM (11.2.1):
    - FBSDKCoreKit_Basics (~> 11.2.1)
  - FBSDKCoreKit (11.2.1):
    - FBSDKCoreKit/Core (= 11.2.1)
  - FBSDKCoreKit/Core (11.2.1):
    - FBAEMKit (~> 11.2.1)
    - FBSDKCoreKit_Basics (~> 11.2.1)
  - FBSDKCoreKit_Basics (11.2.1):
    - FBSDKCoreKit_Basics/Basics (= 11.2.1)
  - FBSDKCoreKit_Basics/Basics (11.2.1)
  - FBSDKGamingServicesKit (11.2.1):
    - FacebookGamingServices (~> 11.2.1)
    - LegacyGamingServices (~> 11.2.1)
  - FBSDKLoginKit (11.2.1):
    - FBSDKLoginKit/Login (= 11.2.1)
  - FBSDKLoginKit/Login (11.2.1):
    - FBSDKCoreKit (~> 11.2.1)
    - FBSDKCoreKit_Basics (~> 11.2.1)
  - FBSDKShareKit (11.2.1):
    - FBSDKShareKit/Share (= 11.2.1)
  - FBSDKShareKit/Share (11.2.1):
    - FBSDKCoreKit (~> 11.2.1)
    - FBSDKCoreKit_Basics (~> 11.2.1)
  - Firebase/Analytics (10.3.0):
    - Firebase/Core
  - Firebase/Core (10.3.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.3.0)
  - Firebase/CoreOnly (10.3.0):
    - FirebaseCore (= 10.3.0)
  - Firebase/Crashlytics (10.3.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.3.0)
  - Firebase/Messaging (10.3.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.3.0)
  - FirebaseAnalytics (10.3.0):
    - FirebaseAnalytics/AdIdSupport (= 10.3.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.3.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.3.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.3.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.3.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.3.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.3.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement (10.3.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.3.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.3.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - GoogleUtilities/Network (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.0):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.11.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.11.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.0)"
  - GoogleUtilities/Reachability (7.11.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.0):
    - GoogleUtilities/Logger
  - LegacyGamingServices (11.2.1):
    - FBSDKCoreKit (~> 11.2.1)
    - FBSDKCoreKit_Basics (~> 11.2.1)
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - PromisesObjC (2.1.1)

DEPENDENCIES:
  - AppsFlyerFramework (= 6.8.1)
  - FBAEMKit (~> 11.0)
  - FBSDKCoreKit (~> 11.0)
  - FBSDKCoreKit_Basics (~> 11.0)
  - FBSDKGamingServicesKit (~> 11.0)
  - FBSDKLoginKit (~> 11.0)
  - FBSDKShareKit (~> 11.0)
  - Firebase/Analytics (= 10.3.0)
  - Firebase/Core (= 10.3.0)
  - Firebase/Crashlytics (= 10.3.0)
  - Firebase/Messaging (= 10.3.0)

SPEC REPOS:
  trunk:
    - AppsFlyerFramework
    - FacebookGamingServices
    - FBAEMKit
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKGamingServicesKit
    - FBSDKLoginKit
    - FBSDKShareKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseMessaging
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - LegacyGamingServices
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  AppsFlyerFramework: a664325124485223296354b4eec335f5340a6df8
  FacebookGamingServices: 9466832aebd0fda8699dabbb6d51854d8406a21d
  FBAEMKit: 5de0a7aaa854eec69bb5be20795952a63d38a5f6
  FBSDKCoreKit: bf655f808b040ed66a72b9922911b39d703e64f4
  FBSDKCoreKit_Basics: 73ebe3a27eb688ac5b5aa7e99f68992993042115
  FBSDKGamingServicesKit: 2d4678be6df8dae6385f2b549be63a415d6545dc
  FBSDKLoginKit: 2e76831ef08d356b8f9150ea51cce865074ea304
  FBSDKShareKit: 1c8c3000880382ae005fe4a4e7eae9932db1a837
  Firebase: f92fc551ead69c94168d36c2b26188263860acd9
  FirebaseAnalytics: 036232b6a1e2918e5f67572417be1173576245f3
  FirebaseCore: 988754646ab3bd4bdcb740f1bfe26b9f6c0d5f2a
  FirebaseCoreInternal: 29b76f784d607df8b2a1259d73c3f04f1210137b
  FirebaseCrashlytics: f20d956f8229010b645e534693c39e0b7843c268
  FirebaseInstallations: e2f26126089dcf41e215f7b8925af8d953c7d602
  FirebaseMessaging: e345b219fd15d325f0cf2fef28cb8ce00d851b3f
  GoogleAppMeasurement: c7d6fff39bf2d829587d74088d582e32d75133c3
  GoogleDataTransport: 1c8145da7117bd68bbbed00cf304edb6a24de00f
  GoogleUtilities: c2bdc4cf2ce786c4d2e6b3bcfd599a25ca78f06f
  LegacyGamingServices: a270b52a4fcde24916fd16de20eaa75aba076e03
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  PromisesObjC: ab77feca74fa2823e7af4249b8326368e61014cb

PODFILE CHECKSUM: 4826fe8f15eef5d4731b5a0b47435a424bc1afc6

COCOAPODS: 1.11.3

</details>

**Comment by rizafran** [comment] 2023-01-16 10:54
Hi @lizehuiyy, your issue is a duplicate of https://github.com/firebase/firebase-unity-sdk/issues/556. With this, you may try the suggested solution [there](https://github.com/firebase/firebase-unity-sdk/issues/556#issuecomment-1380910581). I'll now be closing this. You may file a ticket in the Unity SDK repo if the issue persists.

**Closed by rizafran** 2023-01-16 10:54 UTC
Labels: api: analytics, Unity
