### ISSUE TITLE
Deadlock - [APMEManager dispatchSyncOnSerialQueue:]

### ISSUE THREAD

**Issue by sarsonj** [firebase/firebase-ios-sdk#4990] opened 2020-02-28 11:07 UTC
### Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.18.0
  * Installation method: CocoaPods

### Step 2: Describe the problem
Apps didn't start. It looks like firebase is blocking main thread.

#### Steps to reproduce:
App deadlocks on start. It happens on iOS 10 & iPhone 5

StackTrace:
```
#0	0x1d262554 in __ulock_wait ()
#1	0x05842b04 in _dispatch_ulock_wait ()
#2	0x05842c02 in _dispatch_thread_event_wait_slow ()
#3	0x0582d0d8 in _dispatch_barrier_sync_f_slow ()
#4	0x00348de4 in -[APMEManager dispatchSyncOnSerialQueue:] ()
#5	0x003462da in -[APMEManager registerSDKProperty:defaultFlags:] ()
#6	0x0037ed60 in -[APMRemoteConfig initWithAppID:database:measurementConfig:] ()
#7	0x0037ea60 in __34+[APMRemoteConfig defaultInstance]_block_invoke ()
#8	0x0581e452 in _dispatch_client_callout ()
#9	0x0581ef4e in dispatch_once_f ()
#10	0x0037ea20 in +[APMRemoteConfig defaultInstance] ()
#11	0x00365888 in +[APMMeasurement remoteConfig] ()
#12	0x003a584e in -[APMScreenViewReporter viewControllerDidAppear:] ()
#13	0x003a7032 in __44+[UIViewController(APMScreenClassName) load]_block_invoke_2 ()
#14	0x002ed9ba in __InstrumentViewDidAppear_block_invoke ()
#15	0x22cdd186 in -[UIViewController _setViewAppearState:isAnimating:] ()
#16	0x22d47d1a in __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke ()
#17	0x22d47cb2 in -[UIViewController _executeAfterAppearanceBlock] ()
#18	0x22f44a6c in _runAfterCACommitDeferredBlocks ()
#19	0x22f37c92 in _cleanUpAfterCAFlushAndRunDeferredBlocks ()
#20	0x22f4e778 in __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke_2 ()
#21	0x1da4ff14 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#22	0x1da4f924 in __CFRunLoopDoBlocks ()
#23	0x1da4df46 in __CFRunLoopRun ()
#24	0x1d9a11ae in CFRunLoopRunSpecific ()
#25	0x1d9a0fd0 in CFRunLoopRunInMode ()
#26	0x1f14bb40 in GSEventRunModal ()
```

**Comment by ryanwilson** [comment] 2020-02-28 14:46
Thanks for the report - looks like a FirebaseAnalytics issue. Filed internally at b/150447598.

**Comment by baolocdo** [comment] 2020-02-28 15:55
Do you have a full crash report? It will be more helpful to see the other threads as well. Thank you

**Comment by baolocdo** [comment] 2020-02-28 18:01
For the record, I found this https://forums.developer.apple.com/thread/113167. I'm just wondering whether you are debugging with older XCode and it's causing the same issue. 
I'm trying to debug it with some of our apps but I haven't seen the deadlocks. It would be nice to have more steps to reproduce it.

**Comment by sarsonj** [comment] 2020-02-28 19:03
Sorry, don't have full crash report anymore.

How I resolved it (maybe it helps)
- app uninstall didn't help
- iPhone restart didn't help
- reset advertising identifier helps - then deadlock disappeared

The deadlock happens inmmediatelly, when I called

FirebaseApp.configure()

for the record, Facebook init is just line bellow (AppEvents.activateApp()), but it should not interfere, right?

**Comment by baolocdo** [comment] 2020-02-28 19:47
Do you have any other Firebase SDKs? Would you mind providing the pod file? Thanks for helping us reproduce the issue.

**Comment by sarsonj** [comment] 2020-02-28 19:54
Here are pods in our project:

def mainAppSharedPods
  pod "PodAsset"
  pod 'ReachabilitySwift','~> 4.0'
  pod 'FBSDKCoreKit'
  pod 'lottie-ios', '3.1.2'
  pod "GoogleWebRTC"
  pod 'Starscream', "~> 3.0"
  pod 'CocoaAsyncSocket', '~> 7.0'
  pod 'BonMot'
  pod 'CocoaLumberjack/Swift', "~> 3.0"
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'iVersion', :configurations => ['release']
  pod "COSTouchVisualizer", :configurations => ['Debug']
  pod 'Then'
  pod 'SnapKit'
  pod 'SwiftGen'
  pod 'ProgressHUD'
  pod 'XMPPFramework'
  pod 'XMPPFramework/Swift'
  pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
  pod 'Valet'
  pod 'libopus'
end

**Comment by sarsonj** [comment] 2020-03-02 15:56
OK, it happens again, I have more debug info. The main thread:

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x1b996554 in __ulock_wait ()
#1	0x06866b04 in _dispatch_ulock_wait ()
#2	0x06866c02 in _dispatch_thread_event_wait_slow ()
#3	0x068510d8 in _dispatch_barrier_sync_f_slow ()
#4	0x005680c8 in -[APMEManager dispatchSyncOnSerialQueue:] ()
#5	0x005655e2 in -[APMEManager registerSDKProperty:defaultFlags:] ()
#6	0x0059e08c in -[APMRemoteConfig initWithAppID:database:measurementConfig:] ()
#7	0x0059dd8c in __34+[APMRemoteConfig defaultInstance]_block_invoke ()
#8	0x06842452 in _dispatch_client_callout ()
#9	0x06842f4e in dispatch_once_f ()
#10	0x0059dd4c in +[APMRemoteConfig defaultInstance] ()
#11	0x00584b8c in +[APMMeasurement remoteConfig] ()
#12	0x005c4b7a in -[APMScreenViewReporter viewControllerDidAppear:] ()
#13	0x005c635e in __44+[UIViewController(APMScreenClassName) load]_block_invoke_2 ()
#14	0x004fef3e in __InstrumentViewDidAppear_block_invoke ()
#15	0x21411186 in -[UIViewController _setViewAppearState:isAnimating:] ()
#16	0x2147bd1a in __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke ()
#17	0x2147bcb2 in -[UIViewController _executeAfterAppearanceBlock] ()
#18	0x21678a6c in _runAfterCACommitDeferredBlocks ()
#19	0x2166bc92 in _cleanUpAfterCAFlushAndRunDeferredBlocks ()
#20	0x21682778 in __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke_2 ()
#21	0x1c183f14 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#22	0x1c183924 in __CFRunLoopDoBlocks ()
#23	0x1c181f46 in __CFRunLoopRun ()
#24	0x1c0d51ae in CFRunLoopRunSpecific ()
#25	0x1c0d4fd0 in CFRunLoopRunInMode ()
#26	0x1d87fb40 in GSEventRunModal ()
#27	0x2145da52 in UIApplicationMain ()
#28	0x0016dc06 in main at /Users/sarsonj/work/ios/tt-monitor-ios/TTMonitor/Application/AppDelegate.swift:17
#29	0x1b8c24ea in start ()

And the APMEExperimentSerialQueue (this name doesn't make me feel save anyway...)

Thread 10 Queue : APMEExperimentSerialQueue (serial)
#0	0x1b996554 in __ulock_wait ()
#1	0x06866b04 in _dispatch_ulock_wait ()
#2	0x06866c02 in _dispatch_thread_event_wait_slow ()
#3	0x068510d8 in _dispatch_barrier_sync_f_slow ()
#4	0x0056bdf2 in -[APMETaskManager dispatchSyncOnWorkerQueue:] ()
#5	0x0056a988 in -[APMETaskManager startTaskManager] ()
#6	0x00565320 in __19-[APMEManager init]_block_invoke ()
#7	0x00567f86 in __42-[APMEManager dispatchAsyncOnSerialQueue:]_block_invoke ()
#8	0x06842466 in _dispatch_call_block_and_release ()
#9	0x0684e66e in _dispatch_queue_serial_drain ()
#10	0x06845a38 in _dispatch_queue_invoke ()
#11	0x0684eb30 in _dispatch_queue_override_invoke ()
#12	0x0685076a in _dispatch_root_queue_drain ()
#13	0x06850470 in _dispatch_worker_thread3 ()
#14	0x1ba4a87c in _pthread_wqthread ()
#15	0x1ba4a45c in start_wqthread ()
Enqueued from com.apple.main-thread (Thread 1) Queue : com.apple.main-thread (serial)
#0	0x0684c95e in _dispatch_queue_push ()
#1	0x00567f1a in -[APMEManager dispatchAsyncOnSerialQueue:] ()
#2	0x00565296 in -[APMEManager init] ()
#3	0x00564f4a in __29+[APMEManager sharedInstance]_block_invoke ()
#4	0x06842f4e in dispatch_once_f ()
#5	0x00564f14 in +[APMEManager sharedInstance] ()
#6	0x0059e06c in -[APMRemoteConfig initWithAppID:database:measurementConfig:] ()
#7	0x0059dd8c in __34+[APMRemoteConfig defaultInstance]_block_invoke ()
#8	0x06842452 in _dispatch_client_callout ()
#9	0x06842f4e in dispatch_once_f ()
#10	0x0059dd4c in +[APMRemoteConfig defaultInstance] ()
#11	0x00584b8c in +[APMMeasurement remoteConfig] ()
#12	0x005c4b7a in -[APMScreenViewReporter viewControllerDidAppear:] ()
#13	0x005c635e in __44+[UIViewController(APMScreenClassName) load]_block_invoke_2 ()
#14	0x004fef3e in __InstrumentViewDidAppear_block_invoke ()
#15	0x21411186 in -[UIViewController _setViewAppearState:isAnimating:] ()
#16	0x2147bd1a in __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke ()
#17	0x2147bcb2 in -[UIViewController _executeAfterAppearanceBlock] ()
#18	0x21678a6c in _runAfterCACommitDeferredBlocks ()
#19	0x2166bc92 in _cleanUpAfterCAFlushAndRunDeferredBlocks ()
#20	0x21682778 in __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke_2 ()
#21	0x1c183f14 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#22	0x1c183924 in __CFRunLoopDoBlocks ()
#23	0x1c181f46 in __CFRunLoopRun ()
#24	0x1c0d51ae in CFRunLoopRunSpecific ()
#25	0x1c0d4fd0 in CFRunLoopRunInMode ()
#26	0x1d87fb40 in GSEventRunModal ()
#27	0x2145da52 in UIApplicationMain ()
#28	0x0016dc06 in main at /Users/sarsonj/work/ios/tt-monitor-ios/TTMonitor/Application/AppDelegate.swift:17
#29	0x1b8c24ea in start ()

**Comment by baolocdo** [comment] 2020-03-02 21:57
Thanks for more information. I still haven't been able to reproduce it with our Quickstart app on older devices (with similar Podfile to yours). Do you have any sample project that can help us? If this is blocking your app release, please refrain from updating to the latest library.

**Comment by sarsonj** [comment] 2020-03-03 08:53
Thanks, which version should be "safe"? 6.17.0 or older?

**Comment by baolocdo** [comment] 2020-03-03 17:59
The current Firebase Analytics is 6.3.0. You can pin the version of Analytics to the previous one 6.2.2

**Comment by ryanwilson** [comment] 2020-03-16 14:12
This should be fixed in the next release of FirebaseAnalytics.

**Comment by paulb777** [comment] 2020-03-24 15:25
Released today.

**Closed by paulb777** 2020-03-24 15:25 UTC
Labels: api: analytics
