### ISSUE TITLE
Add privacy manifest to Installations&Messaging

### ISSUE THREAD

**Issue by tetsu888** [firebase/firebase-ios-sdk#12768] opened 2024-04-12 15:10 UTC
### Description

It appears that Installations & Messaging was missed when privacy manifests were added to the various modules in this repository.
I was expecting to see at least one entry for NSPrivacyAccessedAPICategoryUserDefaults.

FirebaseInstallations:
https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk++userDefaults+path%3AInstallation&type=code

FirebaseMessaging:
https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk++userDefaults+path%3A%2F%5EFirebaseMessaging%5C%2F%2F&type=code

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

### Firebase SDK Version

10.23.0

### Xcode Version

15.2

### Installation Method

CocoaPods

### Firebase Product(s)

Installations, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment] 2024-04-12 15:18
Thanks, @tetsu888. Both of these SDKs should have manifests for 10.23.0.
- https://github.com/firebase/firebase-ios-sdk/blob/fcf5ced6dae2d43fced2581e673cc3b59bdb8ffa/FirebaseMessaging.podspec#L49
- https://github.com/firebase/firebase-ios-sdk/blob/fcf5ced6dae2d43fced2581e673cc3b59bdb8ffa/FirebaseInstallations.podspec#L44

This may be a dupe of #12557. Could you build or archive your app and inspect the file tree? Within the app bundle, each of these SDKs should have a corresponding bundle that contains the manifest.

**Comment by ryo0126** [comment] 2024-04-25 04:48
Hi, I have the same problem on Messaging in 10.24.0.

Although in 10.24.0 many of the occurrences are for `GULUserDefaults`, which is no problem against Privacy Manifest, I can still see an occurrence for `UserDefaults` for example in `FirebaseMessaging/Apps/Shared/UserSettings.swfit` as in:

```swift
public final class UserSettings: ObservableObject {
  @Published public var isAutoInitEnabled: Bool = Messaging.messaging().isAutoInitEnabled {
    didSet { Messaging.messaging().isAutoInitEnabled = isAutoInitEnabled }
  }

  @Published public var shouldUseDelegateThanNotification: Bool = UserDefaults.standard
    .bool(forKey: "useDelegate") {
    didSet { UserDefaults.standard.set(shouldUseDelegateThanNotification, forKey: "useDelegate") }
  }
}
```

However the Privacy Manifest inside FirebaseMessaging doesn't include the reason for `UserDefaults`, so I think FirebaseMessaging should include the reason.

**Comment by ncooke3** [comment] 2024-04-26 16:52
> I see this information is FirebaseMessaging: /Pods/FirebaseMessaging/FirebaseMessaging/Sources/FIRMessaging.m /Pods/FirebaseMessaging/FirebaseMessaging/Sources/FIRMessagingPubSub.m /Pods/FirebaseMessaging/FirebaseMessaging/Sources/FIRMessagingUtilities.h /Pods/FirebaseMessaging/FirebaseMessaging/Sources/FIRMessagingUtilities.m /Pods/FirebaseMessaging/FirebaseMessaging/Sources/FIRMessaging_Private.h /Pods/FirebaseMessaging/FirebaseMessaging/Sources/Token/FIRMessagingCheckinPreferences.m 🛠️ Descriptions for the following required API reason(s) may be missing: 1 [0] NSPrivacyAccessedAPICategoryUserDefaults
> 
> FirebaseInstallations: /Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.m /Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.m 🛠️ Descriptions for the following required API reason(s) may be missing: 1 [0] NSPrivacyAccessedAPICategoryUserDefaults

@farxat60, neither Messaging or Installations should be using R.R. API. The tooling being used is finding false positives from a longtime dependency on GoogleUtilities, which offers an alternative implementation to workaround specific iOS issues with Foundation's NSUserDefaults implementation.

> FirebasePerformance: /Pods/FirebasePerformance/FirebasePerformance/Sources/Configurations/FPRConfigurations+Private.h /Pods/FirebasePerformance/FirebasePerformance/Sources/Configurations/FPRConfigurations.m /Pods/FirebasePerformance/FirebasePerformance/Sources/Configurations/FPRRemoteConfigFlags+Private.h 🛠️ Descriptions for the following required API reason(s) may be missing: 1 [0] NSPrivacyAccessedAPICategoryUserDefaults
> 
> FirebaseSessions: /Pods/FirebaseSessions/FirebaseSessions/Sources/Settings/SettingsCacheClient.swift 🛠️ Descriptions for the following required API reason(s) may be missing: 1 [0] NSPrivacyAccessedAPICategoryUserDefaults

In Firebase 10.25.0 (due out next week), these symbols will be removed.

**Comment by ncooke3** [comment] 2024-04-26 16:54
> Hi, I have the same problem on Messaging in 10.24.0.
> 
> Although in 10.24.0 many of the occurrences are for `GULUserDefaults`, which is no problem against Privacy Manifest, I can still see an occurrence for `UserDefaults` for example in `FirebaseMessaging/Apps/Shared/UserSettings.swfit` as in:
> 
> ```swift
> public final class UserSettings: ObservableObject {
>   @Published public var isAutoInitEnabled: Bool = Messaging.messaging().isAutoInitEnabled {
>     didSet { Messaging.messaging().isAutoInitEnabled = isAutoInitEnabled }
>   }
> 
>   @Published public var shouldUseDelegateThanNotification: Bool = UserDefaults.standard
>     .bool(forKey: "useDelegate") {
>     didSet { UserDefaults.standard.set(shouldUseDelegateThanNotification, forKey: "useDelegate") }
>   }
> }
> ```
> 
> However Privacy Manifest inside FirebaseMessaging doesn't include the reason for `UserDefaults`, so I think FirebaseMessaging should include the reason.

`FirebaseMessaging/Apps/Shared/UserSettings.swift` is part of a test app and is not included in the SDK's source code.

**Comment by ncooke3** [comment] 2024-04-26 16:55
I'm going to mark this as closed as both Messaging and Installations have privacy manifests with the necessary R.R. justifications.

**Closed by ncooke3** 2024-04-26 16:55 UTC
Labels: needs-info
