### ISSUE TITLE
Lexical or Preprocessor issues

### ISSUE THREAD

**Issue by tysun** [firebase/firebase-ios-sdk#6471] opened 2020-09-16 07:33 UTC
I have 16 Protobuf issues and 23 FirebaseFirestore issues. All are "**Non-portable path to file '<protobuf/Wrappers.pbobjc.h>'; specified path differs in case from file name on disk**" type messages.

iOS 13
Xcode 11.7

Please advise.

Thanks

![sc](https://user-images.githubusercontent.com/11150198/93306028-48b78600-f83a-11ea-8332-462a6dc5637e.png)

**Comment by morganchen12** [comment] 2020-09-16 15:43
Duplicate of https://github.com/firebase/firebase-ios-sdk/issues/2665. Please update your Protobuf dependency.

**Closed by morganchen12** 2020-09-16 15:43 UTC
Labels: needs-triage
