### ISSUE TITLE
Crash on Splash after integrating any version of Firebase 10.7 and above

### ISSUE THREAD

**Issue by alexandruLipiciOCS** [firebase/firebase-ios-sdk#11697] opened 2023-08-18 13:48 UTC
### Description

The issue is that after opening the application, the Firebase SDK crashes. To crash log will be attached above.

Here are some informations of what are we using:
- firebase working version: 10.5.0
- crashing versions: 10.7.0 and above
- integrated through SPM and CocoaPods and it’s the same
- we are integrating also Facebook SDK (Core and Login one)
- included Firebase packages: Core, Analytics, Crashlytics, Performance
- we use multiple GoogleService-Info.plist for each environment
- we tried several solutions suggested also on another firebase’s git issue and it didn’t work
- we cleared DerivedData, deintegrated pods project
 

Crash logs attached bellow.

### Reproducing the issue

The issue happens when the app is launching. It's crashing from the Splash.

### Firebase SDK Version

10.7 and above

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Crashlytics, Performance, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
While integrating with SPM:

2023-08-18 16:45:23.189257+0300 Paris2024[21429:2448374] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise firebaseInstallationID]: unrecognized selector sent to instance 0x6000035041e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112b5578b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00000001146fbb73 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112b648c4 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x0000000112b59c66 ___forwarding___ + 1443
	4   CoreFoundation                      0x0000000112b5be08 _CF_forwarding_prep_0 + 120
	5   Domain                              0x0000000126619bcf -[FIRInstallationsItem updateWithStoredItem:] + 79
	6   Domain                              0x00000001266288b1 __54-[FIRInstallationsStore installationForAppID:appName:]_block_invoke.23 + 209
	7   Domain                              0x000000012667f091 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.67 + 113
	8   Domain                              0x000000012667e88f __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 + 159
	9   libdispatch.dylib                   0x000000012151954f _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000012151a7ec _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000012152b7e9 _dispatch_main_queue_drain + 1725
	12  libdispatch.dylib                   0x000000012152b11e _dispatch_main_queue_callback_4CF + 31
	13  CoreFoundation                      0x0000000112ab36cc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x0000000112aadfbe __CFRunLoopRun + 2429
	15  CoreFoundation                      0x0000000112aad264 CFRunLoopRunSpecific + 560
	16  GraphicsServices                    0x000000012c04224e GSEventRunModal + 139
	17  UIKitCore                           0x00000001361817bf -[UIApplication _run] + 994
	18  UIKitCore                           0x00000001361865de UIApplicationMain + 123
	19  Paris2024                           0x000000010442d91f main + 63
	20  dyld                                0x0000000111e44384 start_sim + 10
	21  ???                                 0x0000000209b2941f 0x0 + 8752632863
)
libc++abi: terminating due to uncaught exception of type NSException
(lldb) 

While integrating with cocoapods:

2023-08-18 16:41:07.587548+0300 Paris2024[18211:2433915] 10.11.0 - [FirebasePerformance][I-PRF300005] URL length exceeds limits, truncating recorded URL - https://remote-data.asnapieu.com/api/remote-data/app/flh0Be5lQ4SyxEaxi3LeLw/ios.
2023-08-18 16:41:07.590271+0300 Paris2024[18211:2433474] 10.11.0 - [FirebaseAnalytics][I-ACS031010] Tracking view controller. Class, ID: SplashViewController, 7766667045315015863
2023-08-18 16:41:07.595530+0300 Paris2024[18211:2433548] 10.11.0 - [FirebaseAnalytics][I-ACS031006] View controller already tracked. Class, ID: SplashViewController, 7702413980447676900
2023-08-18 16:41:07.598149+0300 Paris2024[18211:2433474]  - <AppMeasurement>[I-ACS036000] Found unknown associated object: APMScreen
2023-08-18 16:41:07.598621+0300 Paris2024[18211:2433474]  - <AppMeasurement>[I-ACS036000] Found unknown associated object: APMScreen
2023-08-18 16:41:07.612456+0300 Paris2024[18211:2433474] -[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600001716ac0
2023-08-18 16:41:07.617508+0300 Paris2024[18211:2433474] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600001716ac0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001113fb78b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000114688b73 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011140a8c4 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00000001113ffc66 ___forwarding___ + 1443
	4   CoreFoundation                      0x0000000111401e08 _CF_forwarding_prep_0 + 120
	5   GoogleDataTransport                 0x000000011355bf32 -[GDTCCTUploadOperation updateNextUploadTimeWithResponse:forTarget:] + 114
	6   GoogleDataTransport                 0x000000011355ac8e __54-[GDTCCTUploadOperation uploadBatch:toTarget:storage:]_block_invoke + 94
	7   FBLPromises                         0x000000011291b441 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.44 + 113
	8   FBLPromises                         0x000000011291aa9f __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 + 159
	9   libdispatch.dylib                   0x000000011eec754f _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000011eec87ec _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000011eed0879 _dispatch_lane_serial_drain + 1574
	12  libdispatch.dylib                   0x000000011eed14a6 _dispatch_lane_invoke + 428
	13  libdispatch.dylib                   0x000000011eedf982 _dispatch_workloop_worker_thread + 962
	14  libsystem_pthread.dylib             0x00000001219a3c55 _pthread_wqthread + 327
	15  libsystem_pthread.dylib             0x00000001219a2bbf start_wqthread + 15
)
2023-08-18 16:41:07.619939+0300 Paris2024[18211:2433206] Attempted to create a task in a session that has been invalidated
libc++abi: terminating due to uncaught exception of type NSException
(lldb)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "object": {
    "pins": [
      {
        "package": "abseil",
        "repositoryURL": "https://github.com/google/abseil-cpp-binary.git",
        "state": {
          "branch": null,
          "revision": "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
          "version": "1.2022062300.0"
        }
      },
      {
        "package": "Alamofire",
        "repositoryURL": "https://github.com/Alamofire/Alamofire.git",
        "state": {
          "branch": null,
          "revision": "8dd85aee02e39dd280c75eef88ffdb86eed4b07b",
          "version": "5.6.2"
        }
      },
      {
        "package": "AlgoliaSearchClient",
        "repositoryURL": "https://github.com/algolia/algoliasearch-client-swift",
        "state": {
          "branch": null,
          "revision": "41c1d4fb748c77b2ee1fd18ead8baa3e9d81605e",
          "version": "8.18.1"
        }
      },
      {
        "package": "AppAuth",
        "repositoryURL": "https://github.com/openid/AppAuth-iOS.git",
        "state": {
          "branch": null,
          "revision": "71cde449f13d453227e687458144bde372d30fc7",
          "version": "1.6.2"
        }
      },
      {
        "package": "Boomerang",
        "repositoryURL": "https://github.com/synesthesia-it/Boomerang",
        "state": {
          "branch": "master",
          "revision": "a0ee6d294d1ba28be476345de48dce0248c6c28f",
          "version": null
        }
      },
      {
        "package": "Facebook",
        "repositoryURL": "https://github.com/facebook/facebook-ios-sdk",
        "state": {
          "branch": null,
          "revision": "c46ba480e9b176a950c428b1a1ec3fd57810f8fe",
          "version": "11.2.1"
        }
      },
      {
        "package": "Firebase",
        "repositoryURL": "https://github.com/firebase/firebase-ios-sdk",
        "state": {
          "branch": null,
          "revision": "e700a8f40c87c31cab7984875fcc1225d96b25bf",
          "version": "10.11.0"
        }
      },
      {
        "package": "GoogleAppMeasurement",
        "repositoryURL": "https://github.com/google/GoogleAppMeasurement.git",
        "state": {
          "branch": null,
          "revision": "62e3a0c09a75e2637f5300d46f05a59313f1c286",
          "version": "10.11.0"
        }
      },
      {
        "package": "GoogleDataTransport",
        "repositoryURL": "https://github.com/google/GoogleDataTransport.git",
        "state": {
          "branch": null,
          "revision": "98a00258d4518b7521253a70b7f70bb76d2120fe",
          "version": "9.2.4"
        }
      },
      {
        "package": "GoogleSignIn",
        "repositoryURL": "https://github.com/google/GoogleSignIn-iOS",
        "state": {
          "branch": null,
          "revision": "7932d33686c1dc4d7df7a919aae47361d1cdfda4",
          "version": "7.0.0"
        }
      },
      {
        "package": "GoogleUtilities",
        "repositoryURL": "https://github.com/google/GoogleUtilities.git",
        "state": {
          "branch": null,
          "revision": "58d03d22beae762eaddbd30cb5a61af90d4b309f",
          "version": "7.11.3"
        }
      },
      {
        "package": "gRPC",
        "repositoryURL": "https://github.com/google/grpc-binary.git",
        "state": {
          "branch": null,
          "revision": "f1b366129d1125be7db83247e003fc333104b569",
          "version": "1.50.2"
        }
      },
      {
        "package": "GTMSessionFetcher",
        "repositoryURL": "https://github.com/google/gtm-session-fetcher.git",
        "state": {
          "branch": null,
          "revision": "d415594121c9e8a4f9d79cecee0965cf35e74dbd",
          "version": "3.1.1"
        }
      },
      {
        "package": "GTMAppAuth",
        "repositoryURL": "https://github.com/google/GTMAppAuth.git",
        "state": {
          "branch": null,
          "revision": "cee3c709307912d040bd1e06ca919875a92339c6",
          "version": "2.0.0"
        }
      },
      {
        "package": "INSPhotoGallery",
        "repositoryURL": "https://github.com/m1entus/INSPhotoGallery",
        "state": {
          "branch": null,
          "revision": "f0a89f5d83dd47a0f109ae40c84c9567a5643165",
          "version": "1.2.9"
        }
      },
      {
        "package": "InstantSearch",
        "repositoryURL": "https://github.com/algolia/instantsearch-ios",
        "state": {
          "branch": null,
          "revision": "d34ff55926d70649e597260593839126feabcaf9",
          "version": "7.25.0"
        }
      },
      {
        "package": "InstantSearchTelemetry",
        "repositoryURL": "https://github.com/algolia/instantsearch-telemetry-native",
        "state": {
          "branch": null,
          "revision": "d9861ceb2fe25899a31672fb7c648ae8036d3221",
          "version": "0.1.3"
        }
      },
      {
        "package": "Branch",
        "repositoryURL": "https://github.com/BranchMetrics/ios-branch-sdk-spm",
        "state": {
          "branch": null,
          "revision": "2a430f24f7511b720f1d460560f42b7e4bcb99fd",
          "version": "1.43.2"
        }
      },
      {
        "package": "Airship",
        "repositoryURL": "https://github.com/urbanairship/ios-library",
        "state": {
          "branch": null,
          "revision": "2a953b4f4f6a2e5d41afcdf9eb0e914a66bee431",
          "version": "17.0.3"
        }
      },
      {
        "package": "KeychainAccess",
        "repositoryURL": "https://github.com/kishikawakatsumi/KeychainAccess",
        "state": {
          "branch": null,
          "revision": "84e546727d66f1adc5439debad16270d0fdd04e7",
          "version": "4.2.2"
        }
      },
      {
        "package": "Kingfisher",
        "repositoryURL": "https://github.com/onevcat/Kingfisher",
        "state": {
          "branch": null,
          "revision": "af4be924ad984cf4d16f4ae4df424e79a443d435",
          "version": "7.6.2"
        }
      },
      {
        "package": "leveldb",
        "repositoryURL": "https://github.com/firebase/leveldb.git",
        "state": {
          "branch": null,
          "revision": "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
          "version": "1.22.2"
        }
      },
      {
        "package": "Lottie",
        "repositoryURL": "https://github.com/airbnb/lottie-ios",
        "state": {
          "branch": null,
          "revision": "b4bd0604ded9574807f41b4004b57dd1226a30a4",
          "version": "3.5.0"
        }
      },
      {
        "package": "nanopb",
        "repositoryURL": "https://github.com/firebase/nanopb.git",
        "state": {
          "branch": null,
          "revision": "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
          "version": "2.30909.0"
        }
      },
      {
        "package": "Pageboy",
        "repositoryURL": "https://github.com/uias/Pageboy",
        "state": {
          "branch": null,
          "revision": "5522aa6ae88633f6c23cf504e9cd684e963822f1",
          "version": "4.0.2"
        }
      },
      {
        "package": "Promises",
        "repositoryURL": "https://github.com/google/promises.git",
        "state": {
          "branch": null,
          "revision": "ec957ccddbcc710ccc64c9dcbd4c7006fcf8b73a",
          "version": "2.2.0"
        }
      },
      {
        "package": "Pulley",
        "repositoryURL": "https://github.com/52inc/Pulley",
        "state": {
          "branch": null,
          "revision": "355bb7c53d4d430334422ad05a97fbe43ce326db",
          "version": "2.9.1"
        }
      },
      {
        "package": "RxDataSources",
        "repositoryURL": "https://github.com/RxSwiftCommunity/RxDataSources.git",
        "state": {
          "branch": null,
          "revision": "90c29b48b628479097fe775ed1966d75ac374518",
          "version": "5.0.2"
        }
      },
      {
        "package": "RxGesture",
        "repositoryURL": "https://github.com/RxSwiftCommunity/RxGesture.git",
        "state": {
          "branch": null,
          "revision": "1b137c576b4aaaab949235752278956697c9e4a0",
          "version": "4.0.4"
        }
      },
      {
        "package": "RxSwift",
        "repositoryURL": "https://github.com/ReactiveX/RxSwift.git",
        "state": {
          "branch": null,
          "revision": "b4307ba0b6425c0ba4178e138799946c3da594f8",
          "version": "6.5.0"
        }
      },
      {
        "package": "swift-log",
        "repositoryURL": "https://github.com/apple/swift-log.git",
        "state": {
          "branch": null,
          "revision": "32e8d724467f8fe623624570367e3d50c5638e46",
          "version": "1.5.2"
        }
      },
      {
        "package": "GoogleMobileAds",
        "repositoryURL": "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
        "state": {
          "branch": null,
          "revision": "886501bfff8bd8cc22899de2c1779e479c96f9ff",
          "version": "10.3.0"
        }
      },
      {
        "package": "GoogleUserMessagingPlatform",
        "repositoryURL": "https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git",
        "state": {
          "branch": null,
          "revision": "3b924ce3313a5fd2fc6a8dc889a8c38f76890fe3",
          "version": "2.0.0"
        }
      },
      {
        "package": "SwiftProtobuf",
        "repositoryURL": "https://github.com/apple/swift-protobuf.git",
        "state": {
          "branch": null,
          "revision": "f25867a208f459d3c5a06935dceb9083b11cd539",
          "version": "1.22.0"
        }
      },
      {
        "package": "SwiftRichString",
        "repositoryURL": "https://github.com/malcommac/SwiftRichString",
        "state": {
          "branch": null,
          "revision": "9bf4b5af6bb4386865636fc504d6c588c2b65040",
          "version": "3.7.2"
        }
      },
      {
        "package": "Tabman",
        "repositoryURL": "https://github.com/uias/Tabman",
        "state": {
          "branch": null,
          "revision": "6a87a2825939f5da06cf52a6582d67a646488cff",
          "version": "3.0.1"
        }
      },
      {
        "package": "Zip",
        "repositoryURL": "https://github.com/marmelroy/Zip",
        "state": {
          "branch": null,
          "revision": "bd19d974e8a38cc8d3a88c90c8a107386c3b8ccf",
          "version": "2.1.1"
        }
      }
    ]
  },
  "version": 1
}


```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - Analytics (4.1.6)
  - Firebase/Analytics (10.11.0):
    - Firebase/Core
  - Firebase/Core (10.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.11.0)
  - Firebase/CoreOnly (10.11.0):
    - FirebaseCore (= 10.11.0)
  - Firebase/Crashlytics (10.11.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.11.0)
  - Firebase/Performance (10.11.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 10.11.0)
  - FirebaseABTesting (10.11.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.11.0):
    - FirebaseAnalytics/AdIdSupport (= 10.11.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.11.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.11.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreExtension (10.11.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.11.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.11.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.11.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebasePerformance (10.11.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfig (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/ISASwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.11.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseRemoteConfigSwift (10.11.0):
    - FirebaseRemoteConfig (~> 10.0)
    - FirebaseSharedSwift (~> 10.0)
  - FirebaseSessions (10.11.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (10.11.0)
  - Gigya (1.5.2)
  - google-cast-sdk (4.7.0):
    - google-cast-sdk/Core (= 4.7.0)
    - Protobuf (~> 3.13)
  - google-cast-sdk/Core (4.7.0):
    - Protobuf (~> 3.13)
  - GoogleAds-IMA-iOS-SDK (3.18.4)
  - GoogleAppMeasurement (10.11.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.11.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.11.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.3):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (6.2.1):
    - GoogleMaps/Maps (= 6.2.1)
  - GoogleMaps/Base (6.2.1)
  - GoogleMaps/Maps (6.2.1):
    - GoogleMaps/Base
  - GoogleUtilities/AppDelegateSwizzler (7.11.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.1):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/ISASwizzler (7.11.1)
  - GoogleUtilities/Logger (7.11.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.1)"
  - GoogleUtilities/Reachability (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.1):
    - GoogleUtilities/Logger
  - INSNibLoading (1.0.2)
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - OneTrust-CMP-XCFramework (202304.1.0.0)
  - ownid-core-ios-sdk (2.1.0)
  - ownid-gigya-ios-sdk (2.1.0):
    - Gigya
    - ownid-core-ios-sdk (= 2.1.0)
  - pop (1.0.12)
  - PromisesObjC (2.2.0)
  - PromisesSwift (2.2.0):
    - PromisesObjC (= 2.2.0)
  - Protobuf (3.23.0)
  - SCSDKCameraKit (1.24.0)
  - SCSDKCameraKitReferenceSwiftUI (1.24.0):
    - SCSDKCameraKitReferenceUI (~> 1.24.0)
  - SCSDKCameraKitReferenceUI (1.24.0):
    - SCSDKCameraKit (~> 1.24.0)
  - SnapSDK/SCSDKCoreKit (2.4.0)
  - SnapSDK/SCSDKCreativeKit (2.4.0):
    - SnapSDK/SCSDKCoreKit
  - TTTAttributedLabel (2.0.0)
  - YouboraAVPlayerAdapter (6.7.0):
    - YouboraAVPlayerAdapter/Default (= 6.7.0)
    - YouboraLib (~> 6.5)
  - YouboraAVPlayerAdapter/Default (6.7.0):
    - YouboraLib (~> 6.5)
  - YouboraIMAAdapter (6.6.3):
    - GoogleAds-IMA-iOS-SDK (~> 3.13)
    - GoogleAds-IMA-tvOS-SDK (~> 4.3)
    - YouboraLib (~> 6.5)
  - YouboraLib (6.7.1)

DEPENDENCIES:
  - Analytics
  - Firebase/Analytics (= 10.11.0)
  - Firebase/Core (= 10.11.0)
  - Firebase/Crashlytics (= 10.11.0)
  - Firebase/Performance (= 10.11.0)
  - FirebaseRemoteConfigSwift (= 10.11.0)
  - Gigya (= 1.5.2)
  - google-cast-sdk (= 4.7.0)
  - GoogleAds-IMA-iOS-SDK (= 3.18.4)
  - GoogleMaps
  - INSNibLoading
  - OneTrust-CMP-XCFramework (~> 202304.1.0.0)
  - ownid-gigya-ios-sdk (= 2.1.0)
  - pop
  - SCSDKCameraKit
  - SCSDKCameraKitReferenceSwiftUI
  - SnapSDK/SCSDKCreativeKit (= 2.4.0)
  - TTTAttributedLabel
  - YouboraAVPlayerAdapter (= 6.7.0)
  - YouboraIMAAdapter

SPEC REPOS:
  trunk:
    - Analytics
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebasePerformance
    - FirebaseRemoteConfig
    - FirebaseRemoteConfigSwift
    - FirebaseSessions
    - FirebaseSharedSwift
    - Gigya
    - google-cast-sdk
    - GoogleAds-IMA-iOS-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GoogleUtilities
    - INSNibLoading
    - nanopb
    - OneTrust-CMP-XCFramework
    - ownid-core-ios-sdk
    - ownid-gigya-ios-sdk
    - pop
    - PromisesObjC
    - PromisesSwift
    - Protobuf
    - SCSDKCameraKit
    - SCSDKCameraKitReferenceSwiftUI
    - SCSDKCameraKitReferenceUI
    - SnapSDK
    - TTTAttributedLabel
    - YouboraAVPlayerAdapter
    - YouboraIMAAdapter
    - YouboraLib

SPEC CHECKSUMS:
  Analytics: eefe524436f904b8bb3f8c8c3425280e43b34efc
  Firebase: 31d9575c124839fb5abc0db6d39511cc1dab1b85
  FirebaseABTesting: 3f6b711718feb87346dc05f8c964601bc8fb2cf6
  FirebaseAnalytics: 6c6bf99e8854475bf1fa342028841be8ecd236da
  FirebaseCore: 62fd4d549f5e3f3bd52b7998721c5fa0557fb355
  FirebaseCoreExtension: cacdad57fdb60e0b86dcbcac058ec78237946759
  FirebaseCoreInternal: 9e46c82a14a3b3a25be4e1e151ce6d21536b89c0
  FirebaseCrashlytics: 5927efd92f7fb052b0ab1e673d2f0d97274cd442
  FirebaseInstallations: 2a2c6859354cbec0a228a863d4daf6de7c74ced4
  FirebasePerformance: 2e9aa0fb103d6c08403d20d135bf06b3adfb3454
  FirebaseRemoteConfig: 5f907cd5cf6f64d026c8bfd196a1086cbe1e95e2
  FirebaseRemoteConfigSwift: 02450f94bf89d0cc22b96e44c8e456c679ce997e
  FirebaseSessions: a62ba5c45284adb7714f4126cfbdb32b17c260bd
  FirebaseSharedSwift: c590d181c8b80ebf85f2606f4d366cf72f82f184
  Gigya: 030de6ed660df58730b0e188ea981cad02d82681
  google-cast-sdk: 6731e9a206ce43e0f4433d15598ad8a19f0371d5
  GoogleAds-IMA-iOS-SDK: b01284e3bf3d64ba948de6692ffda531452c3713
  GoogleAppMeasurement: d3dabccdb336fc0ae44b633c8abaa26559893cd9
  GoogleDataTransport: f0308f5905a745f94fb91fea9c6cbaf3831cb1bd
  GoogleMaps: 20d7b12be49a14287f797e88e0e31bc4156aaeb4
  GoogleUtilities: 9aa0ad5a7bc171f8bae016300bfcfa3fb8425749
  INSNibLoading: 0244d5b9c30d4642c77b31469cbfd905e8b1efb3
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  OneTrust-CMP-XCFramework: 6ba009d173203f5e74bb33708df5ddac6f3edc1c
  ownid-core-ios-sdk: 42096cb0aea330c8163ec29291290e8ad874f8ad
  ownid-gigya-ios-sdk: c6c5112a0eccab4d1831e82145f233b60bfb1e64
  pop: d582054913807fd11fd50bfe6a539d91c7e1a55a
  PromisesObjC: 09985d6d70fbe7878040aa746d78236e6946d2ef
  PromisesSwift: cf9eb58666a43bbe007302226e510b16c1e10959
  Protobuf: 43e3764cdf3609fdd00417649561565703437fdc
  SCSDKCameraKit: 7f8864857d4510a75bc08f83ff8ee4f7ea833959
  SCSDKCameraKitReferenceSwiftUI: 6d841cd23ce860a79dba4c13897022eee314d168
  SCSDKCameraKitReferenceUI: a6e2f239c2561799cda69eb49711cbfb7be9ae4d
  SnapSDK: e832716ff024b17b448f9bca5feeac5a3daed3ff
  TTTAttributedLabel: 8cffe8e127e4e82ff3af1e5386d4cd0ad000b656
  YouboraAVPlayerAdapter: f48516d2e5862e3f6b183471993be165cc8e8c77
  YouboraIMAAdapter: aed03e9cebc611875ba769315d6348dc040f9fd6
  YouboraLib: bec896cbfc74ce4a2243a6a55da099e7843f1242

PODFILE CHECKSUM: b6e3af552114f5c122ebe6145b210c6f99ce1d28

COCOAPODS: 1.12.1


```

</details>

**Comment by paulb777** [comment] 2023-08-18 14:48
This issue was fixed in Promises 2.3.1.  Please update the Swift package.

Alternatively, a workaround is to add `-ObjC` to the Other Linker Options Build Setting.

**Comment by alexandruLipiciOCS** [comment] 2023-08-21 09:16
We tried to integrate Promises 2.3.1 and `-ObjC` flag and we receive the same error

**Comment by paulb777** [comment] 2023-08-21 13:59
Strange. We'll likely need a reproducible example to help further.

**Comment by paulb777** [comment] 2023-08-21 14:02
One additional issue is that FirebaseAnalytics does not support the usage of multiple GoogleService-Info.plists. #230

**Comment by MarcoTagliafierro** [comment] 2023-08-22 14:13
Hi @paulb777, we have tried removing the additional GoogleService-Info.plists files present in the project (currently we have one per build scheme) but this had no effect on the error we are getting. We also tried naming the .plists file exactly GoogleService-Info.plists as suggested in some comments of the linked thread, but it didn't work as well

**Comment by paulb777** [comment] 2023-08-22 14:32
Are you seeing duplicate warnings or any other warnings in the console when the app loads?

**Comment by MarcoTagliafierro** [comment] 2023-08-22 14:58
I cannot see any duplicate warning. The only one related to FBLPromises is the following: 
`objc[98774]: Class FBLPromise is implemented in both .../Library/Developer/Xcode/DerivedData/Paris2024-.../Build/Products/STG Debug-iphonesimulator/PackageFrameworks/FBLPromises_-613B793C1E784BCF_PackageProduct.framework/FBLPromises_-613B793C1E784BCF_PackageProduct (0x1607085a0) and .../Library/Developer/Xcode/DerivedData/Paris2024-.../Build/Products/STG Debug-iphonesimulator/Domain.framework/Domain (0x1266eedb8). One of the two will be used. Which one is undefined.`

**Comment by paulb777** [comment] 2023-08-22 15:08
That warning could be related to the crash. It looks like you may be linking static library builds of Promises into both the app and the Domain dynamic framework.

**Comment by MarcoTagliafierro** [comment] 2023-08-29 07:09
The issue we were facing was caused by the presence of two libraries (Firebase and GoogleMobileAds), one imported via Pods and the other via SPM, that are both using the Promises SDK. Moving the both of them to Pods solved the issue. Thank you for your support!

**Closed** 2023-09-12 01:05 UTC
Labels: needs-info, no-recent-activity
