### ISSUE TITLE
Sign In With Apple credential doesn't update email

### ISSUE THREAD

**Issue by mozeryansky** [firebase/firebase-ios-sdk#6448] opened 2020-09-12 02:15 UTC
* Xcode version: Version 12.0 beta 6 (12A8189n)
  * Firebase SDK version: 6.31.0
  * Firebase Component: Auth
  * Installation method: Carthage

#### Steps to reproduce:

I am using Sign In With Apple using the `OAuthProvider` credential. I am able to login and confirm that Firebase Authentication console shows that the account is linked with Apple. However, when testing I removed my Apple ID and signed in with a new hidden email, but firebase kept the original email.

`authDataResult?.additionalUserInfo?.profile?["email"]` shows the new email that I used with Sign In With Apple, but the `authDataResult?.user.email` shows my original email.

#### Relevant Code:

I followed the example from https://peterfriese.dev/replicating-reminder-swiftui-firebase-part3/

@peterfriese 

I plan to use `updateEmail`, but this seems like a problem that should be handled by Firebase. Maybe instead of OAuthProvider there can be a AppleAuthProvider like there is GoogleAuthProvider/FacebookAuthProvider to handle this privacy requirements.

**Comment by malcolmdeck** [comment] 2020-09-21 18:24
Hey mozeryansky,

I think this is working as intended. Once you create an account with Firebase, the email used at account creation time is bound to the account, even if you unlink the provider that set that email. That's so that account recovery flows still have somewhere to send password reset links and the like. If this is causing problems for you, I think that the only solution is using `updateEmail` as you've suggested.

I'm going to close this issue for now, but if I've missed something about the issue (particularly with respect to the privacy concerns), please feel free to re-open this issue and comment with more detail. :)

Hope that helps!
~Malcolm

**Closed** 2020-09-21 18:25 UTC
Labels: api: auth
