### ISSUE TITLE
Firebase Crash on iPhone 5

### ISSUE THREAD

**Issue by EvenDu** [firebase/firebase-ios-sdk#3892] opened 2019-09-20 11:57 UTC
I have the problem on iPhone 5（only on iphone 5 ,OS 10.3.3):
   when I run the app in development that it is normal, but then I upload the app to TestFlight and download it,  the app will crash when the app launching。firebase Crashlytics give the  crash description like this:

 Crashed: com.google.firebase.firestore.data
0  Protobuf                       0xad7fd8 GPBCodedInputStreamReadDouble + 88 (GPBUtilities_PackagePrivate.h:88)
1  Protobuf                       0xad7fd1 GPBCodedInputStreamReadDouble + 103 (GPBCodedInputStream.m:103)
2  Protobuf                       0xb02fd1 -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2143 (GPBMessage.m:2143)
3  Protobuf                       0xad89c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
4  Protobuf                       0xadf1f7 ReadValue + 440 (GPBDictionary.m:440)
5  Protobuf                       0xadee57 GPBDictionaryReadEntry + 481 (GPBDictionary.m:481)
6  Protobuf                       0xad8a4d -[GPBCodedInputStream readMapEntry:extensionRegistry:field:parentMessage:] + 296 (GPBCodedInputStream.m:296)
7  Protobuf                       0xb02f47 -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2363 (GPBMessage.m:2363)
8  Protobuf                       0xad89c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
9  Protobuf                       0xb0314f -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2181 (GPBMessage.m:2181)
10 Protobuf                       0xad89c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
11 Protobuf                       0xb0347f MergeRepeatedNotPackedFieldFromCodedInputStream + 2294 (GPBMessage.m:2294)
12 Protobuf                       0xb02f6b -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2393 (GPBMessage.m:2393)
13 Protobuf                       0xad89c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
14 Protobuf                       0xb0314f -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2181 (GPBMessage.m:2181)
15 Protobuf                       0xad89c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
16 Protobuf                       0xadf1f7 ReadValue + 440 (GPBDictionary.m:440)
17 Protobuf                       0xadee57 GPBDictionaryReadEntry + 481 (GPBDictionary.m:481)
18 Protobuf                       0xad8a4d -[GPBCodedInputStream readMapEntry:extensionRegistry:field:parentMessage:] + 296 (GPBCodedInputStream.m:296)
19 Protobuf                       0xb02f47 -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2363 (GPBMessage.m:2363)
20 Protobuf                       0xad89c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
21 Protobuf                       0xb0314f -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2181 (GPBMessage.m:2181)
22 Protobuf                       0xad89c5 -[GPBCodedInputStream readMessage:extensionRegistry:] + 296 (GPBCodedInputStream.m:296)
23 Protobuf                       0xb0314f -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] + 2181 (GPBMessage.m:2181)
24 Protobuf                       0xb02647 -[GPBMessage mergeFromData:extensionRegistry:] + 1928 (GPBMessage.m:1928)
25 Protobuf                       0xaffd55 -[GPBMessage initWithData:extensionRegistry:error:] + 868 (GPBMessage.m:868)
26 Protobuf                       0xb0271b +[GPBMessage parseFromData:extensionRegistry:error:] + 1957 (GPBMessage.m:1957)
27 Protobuf                       0xb026e5 +[GPBMessage parseFromData:error:] + 1951 (GPBMessage.m:1951)
28 Invoices                       0x4650d7 firebase::firestore::remote::bridge::WatchStreamSerializer::ParseResponse(grpc::ByteBuffer const&, firebase::firestore::util::Status*) const + 97 (remote_objc_bridge.mm:97)
29 Invoices                       0x47ad6d firebase::firestore::remote::WatchStream::NotifyStreamResponse(grpc::ByteBuffer const&) + 83 (watch_stream.mm:83)
30 Invoices                       0x46f03b firebase::firestore::remote::Stream::OnStreamRead(grpc::ByteBuffer const&) + 2633 (memory:2633)
31 Invoices                       0x437f0d std::__1::__function::__func<firebase::firestore::remote::GrpcStream::NewCompletion(firebase::firestore::remote::GrpcCompletion::Type, std::__1::function<void (firebase::firestore::remote::GrpcCompletion const*)> const&)::$_3, std::__1::allocator<firebase::firestore::remote::GrpcStream::NewCompletion(firebase::firestore::remote::GrpcCompletion::Type, std::__1::function<void (firebase::firestore::remote::GrpcCompletion const*)> const&)::$_3>, void (bool, firebase::firestore::remote::GrpcCompletion const*)>::operator()(bool&&, firebase::firestore::remote::GrpcCompletion const*&&) + 1913 (functional:1913)
32 Invoices                       0x431907 std::__1::function<void (bool, firebase::firestore::remote::GrpcCompletion const*)>::operator()(bool, firebase::firestore::remote::GrpcCompletion const*) const + 1913 (functional:1913)
33 Invoices                       0x43186b std::__1::__function::__func<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0, std::__1::allocator<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0>, void ()>::operator()() + 71 (grpc_completion.cc:71)
34 Invoices                       0x392a11 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 1913 (functional:1913)
35 Invoices                       0x3a8ded firebase::firestore::util::internal::DispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&)::$_0::__invoke(void*) + 1862 (functional:1862)
36 libdispatch.dylib              0x1d97e59d _dispatch_queue_serial_drain + 854
37 libdispatch.dylib              0x1d974b71 _dispatch_queue_invoke + 886
38 libdispatch.dylib              0x1d97ea1f _dispatch_queue_override_invoke + 282
39 libdispatch.dylib              0x1d9801b5 _dispatch_root_queue_drain + 326
40 libdispatch.dylib              0x1d98000f _dispatch_worker_thread3 + 106
41 libsystem_pthread.dylib        0x1db2687d _pthread_wqthread + 1040
42 libsystem_pthread.dylib        0x1db2645c start_wqthread + 8

**Comment by paulb777** [comment] 2019-09-20 13:03
This is a dupe of #3851.  Please follow along there.

**Closed by paulb777** 2019-09-20 13:03 UTC
Labels: needs-triage
