### ISSUE TITLE
Bug: React native app crashing (since updating build environment to High Sierra 10.13.6)

### ISSUE THREAD

**Issue by tclarke-scottlogic** [firebase/firebase-ios-sdk#1602] opened 2018-07-30 09:55 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 4.13.0 (as per [react-native-firebase@4.1.0](https://github.com/invertase/react-native-firebase-docs/blob/master/docs/getting-started.md))
  * Firebase Component: Messaging? (Unsure, based on exception)

#### Steps to reproduce:

* Build application

* Start application in Simulator (iOS 11.4, iPhone X)

* After a short period of use, exception is thrown. After that, the same exception is thrown on startup until the simulator is erased

#### Relevant code:

Unsure, could you give me advice on what could be causing this, so I can help diagnose?

#### Relevant Exception:

```
2018-07-30 10:15:23.448287+0100 Acuris[18298:124858] -[__NSCFString setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7fc041a48400
2018-07-30 10:15:23.461250+0100 Acuris[18298:124858] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7fc041a48400'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010885e1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001078b0031 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001088df784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001087e0898 ___forwarding___ + 1432
	4   CoreFoundation                      0x00000001087e0278 _CF_forwarding_prep_0 + 120
	5   Acuris                              0x0000000102759eb1 -[FIRMessagingDataMessageManager parseDataMessage:] + 1222
	6   Acuris                              0x0000000102759971 -[FIRMessagingDataMessageManager processPacket:] + 242
	7   Acuris                              0x00000001027542a0 -[FIRMessagingClient connectionDidRecieveMessage:] + 83
	8   Acuris                              0x000000010275711c -[FIRMessagingConnection didReceiveDataMessageStanza:] + 79
	9   Acuris                              0x000000010275609e -[FIRMessagingConnection secureSocket:didReceiveData:withTag:] + 495
	10  Acuris                              0x000000010276889d -[FIRMessagingSecureSocket processCurrentInputBuffer:outOffset:] + 264
	11  Acuris                              0x00000001027684f1 -[FIRMessagingSecureSocket performRead] + 1180
	12  Acuris                              0x0000000102767b6c -[FIRMessagingSecureSocket stream:handleEvent:] + 343
	13  CoreFoundation                      0x0000000108821e24 _signalEventSync + 228
	14  CoreFoundation                      0x0000000108835321 _cfstream_solo_signalEventSync + 241
	15  CoreFoundation                      0x000000010881fce6 _CFStreamSignalEvent + 502
	16  CFNetwork                           0x0000000103c4e610 _ZN12SocketStream40dispatchSignalFromSocketCallbackUnlockedEP24SocketStreamSignalHolder + 58
	17  CFNetwork                           0x0000000103c525fd _ZN12SocketStream14socketCallbackEP10__CFSocketmPK8__CFDataPKv + 145
	18  CFNetwork                           0x0000000103c52530 _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv + 70
	19  CoreFoundation                      0x000000010881f94e __CFSocketPerformV0 + 1182
	20  CoreFoundation                      0x0000000108800bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	21  CoreFoundation                      0x00000001087e54af __CFRunLoopDoSources0 + 271
	22  CoreFoundation                      0x00000001087e4a6f __CFRunLoopRun + 1263
	23  CoreFoundation                      0x00000001087e430b CFRunLoopRunSpecific + 635
	24  GraphicsServices                    0x000000010b39fa73 GSEventRunModal + 62
	25  UIKit                               0x00000001050f5057 UIApplicationMain + 159
	26  Acuris                              0x000000010249627f main + 111
	27  libdyld.dylib                       0x000000010a98b955 start + 1
	28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by tclarke-scottlogic** [comment] 2018-07-30 13:59
Potentially related code:
```

      const messaging = this.app.messaging();

      const state = await messaging.hasPermission();
      logger.dev("Current FCM state", state);
      if (this.user.notificationsEnabled) {
        try {
          await messaging.requestPermission();
          logger.info("FCM permissions received");
        } catch (error) {
          logger.warn("FCM permissions failure", error);
        }
      }

      // Retrieve a device token
      try {
        const token = await messaging.getToken();
        logger.info("Received token from messaging", token);
        this.onTokenChanged(token);
        messaging.onTokenRefresh(t => this.onTokenChanged(t));
      } catch (error) {
        logger.error("FCM token request failed", error);
      }
```

**Comment by tclarke-scottlogic** [comment] 2018-07-31 15:41
@Salakar Already have done. I now have more information on the crash. It is down to `FIRMessagingDataMessageManager` expecting a dictionary when it's deserialised a string...

The lines in question are:
```
      NSString *key = [item.key substringFromIndex:[kMCSNotificationPrefix length]];
      if ([key length]) {
        if (!message[kDataMessageNotificationKey]) {
          message[kDataMessageNotificationKey] = [NSMutableDictionary dictionary];
        }
        message[kDataMessageNotificationKey][key] = item.value;
```

`po [message[kDataMessageNotificationKey] class]` in the debug console comes out as `__NSCFString`

`key` is `'e'`

message is:
```
{
    "collapse_key" = "com.acuris.app";
    from = 750107557867;
    "gcm.message_id" = "0:1533035326224726%73a2cce973a2cce9";
    matchType = immediate;
    notification = "{\"id\":\"MDZiZjdlNDljMDk4MjUwOWNhM2Y4MzYxODk3MjA1MjE=\",\"profile\":{\"profileId\":\"5b179c59b4c3d30023958faa\",\"profileName\":\"As much as possible EU\",\"matchType\":\"immediate\",\"product\":\"debtwire\",\"acurisUserId\":200910428,\"email\":\"thomas.clarke@acuris.com\",\"productDisplayName\":\"Debtwire\",\"deliveryMethods\":[\"email\",\"feed\",\"mobile\"]},\"contents\":[{\"shortContentId\":\"intel-prime-2680999\",\"mmgid\":\"prime-2680999\",\"headline\":\"House of Fraser Caa2 PDR appended with LD designation - Moody&apos;s\",\"publishDate\":\"2018-07-31T11:08:50.000Z\",\"productEditions\":[{\"edition\":\"Europe\",\"editionDisplayName\":\"Europe\",\"id\":\"8_1\",\"product\":\"Debtwire\"},{\"edition\":\"Europe\",\"editionDisplayName\":\"Europe\",\"id\":\"32_1\",\"product\":\"Debtwire\"}],\"dominantSector\":{\"mmgid\":\"prime-consumerretail\",\"name\":\"Consumer: Retail\"},\"dominantCountry\":{\"mmgid\":\"prime-GBR\",\"name\":\"United Kingdom\"},\"reportType\":{},\"contentCategories\":[\"headline\"],\"contentSubCategories\":[],\"isProprietary\":false}],\"created\":\"2018-07-31T11:08:44.189Z\",\"createdReverseMs\":-1533035324189,\"isTest\":false}";
    shortContentId = "intel-prime-2680999";
}
```

**Comment by tclarke-scottlogic** [comment] 2018-07-31 15:53
From server team:

> This is the payload:
```
{
  data: {
    matchId: "Yjk4ZTc3ZjU5NDI5ZjE5M2YzYmZjMzRiZTgxYzkxZTI=",
    matchType: "immediate",
    notification: "{"id":"Yjk4ZTc3ZjU5NDI5ZjE5M2YzYmZjMzRiZTgxYzkxZTI=","profile":{"profileId":"5ac35e6057fc7d00193b712a","profileName":"Munis All","matchType":"immediate","product":"debtwire","acurisUserId":200801055,"email":"test.mobile.registration@acuris.com","productDisplayName":"Debtwire","deliveryMethods":["desktop","email","feed","mobile"]},"contents":[{"shortContentId":"intel-prime-2681021","mmgid":"prime-2681021","headline":"PREPA, FOMB reach restructuring support agreement with bondholders","publishDate":"2018-07-31T11:59:00.000Z","productEditions":[{"edition":"North America","editionDisplayName":"Municipals","id":"512_2","product":"Debtwire"}],"dominantSector":{"mmgid":"prime-government","name":"Government"},"dominantCountry":{"mmgid":"prime-PRI","name":"Puerto Rico"},"reportType":{},"contentCategories":["headline"],"contentSubCategories":[],"isProprietary":false}],"created":"2018-07-31T11:59:09.196Z","createdReverseMs":-1533038349196,"isTest":false}",
    shortContentId: "intel-prime-2681021"
  },
  from: "750107557867",
  notification: {
    body: "PREPA, FOMB reach restructuring support agreement with bondholders",
    title: "Debtwire"
  },
  priority: "normal"
}

```
> _(there might be some subtle syntax/styling errors as I had to retype it)._

**Comment by tclarke-scottlogic** [comment] 2018-07-31 15:53
Oh, also, updated to firebase 4.3.1 and thus FirebaseSDK:

```
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Performance', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
```

**Comment by Salakar** [comment] 2018-07-31 15:57
@tclarke-scottlogic given the stack trace is internal to the Firebase SDK and that the error is on receiving a remote message I'm fairly confident it's unrelated to React Native Firebase's implementation of this.

Not sure why but it looks like `data.notification` in the message data payload is getting picked up at the root of the message as `notification` - which expects a dictionary, potential conflict on using a key called `notification` inside `data` when parsing on the iOS SDK?

**Comment by Salakar** [comment] 2018-07-31 16:03
Looks like it's these lines specifically on the iOS SDK: https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/FIRMessagingDataMessageManager.m#L173-L176

Does seem to appear based on a quick glance of the code above you can also send a notification inside the data payload, whether that's intentional though I'm not sure.

**Comment by tclarke-scottlogic** [comment] 2018-07-31 16:12
What's really weird is that I'm not getting these crashes on the phone itself, merely the simulator.

**Comment by tclarke-scottlogic** [comment] 2018-07-31 16:13
And it apparently hasn't changed in a while. The main change on the client side specific to the simulator is an update to High Sierra 10.13.6 OS.

Could this have changed how notifications are processed?

**Comment by tclarke-scottlogic** [comment] 2018-08-01 09:44
@Salakar A thought occurs. I assume the simulator itself isn't getting these notifications, it's getting them via the Mac?
So is this the Mac pre-processing incoming notifications differently?

**Comment by tclarke-scottlogic** [comment] 2018-08-01 09:45
Because that might *also* explain why I'm still getting the crash (with the same stack) when my app in the simulator has notifications disabled, which has not helped with diagnosing the root cause of this issue.

**Comment by tclarke-scottlogic** [comment] 2018-08-02 10:43
I'm trying to find out how FCM notifications get into the simulator, because despite having updated to a different name (as per @Salakar's suggestion), we're still getting this error.

**Comment by chliangGoogle** [comment] 2018-08-06 18:58
can you print out the dataMessage.appDataArray before the crash point?

Also it would be great to share with us both when running on app or simulator.

Because the server data payload is not corrected parsed it's hard for us to debug. It would be great to know which server API you use to send and what the exact payload you sent.

**Comment by tclarke-scottlogic** [comment] 2018-08-07 14:06
I'm afraid we fixed the issue a few days ago (using the suggestion of @Salakar), and so we can no longer replicate.

We had to erase content on the simulator before this would stop happening though.

**Comment by tclarke-scottlogic** [comment] 2018-08-07 14:07
Not sure what this means, btw. How is the server data payload not correctly parsed?

>Because the server data payload is not corrected parsed it's hard for us to debug.

**Comment by chliangGoogle** [comment] 2018-08-07 18:07
I'm referring to the payloads you provided:

This is the payload:

{
  data: {
    matchId: "Yjk4ZTc3ZjU5NDI5ZjE5M2YzYmZjMzRiZTgxYzkxZTI=",
    matchType: "immediate",
    notification: "{"id":"Yjk4ZTc3ZjU5NDI5ZjE5M2YzYmZjMzRiZTgxYzkxZTI=","profile":{"profileId":"5ac35e6057fc7d00193b712a","profileName":"Munis All","matchType":"immediate","product":"debtwire","acurisUserId":200801055,"email":"test.mobile.registration@acuris.com","productDisplayName":"Debtwire","deliveryMethods":["desktop","email","feed","mobile"]},"contents":[{"shortContentId":"intel-prime-2681021","mmgid":"prime-2681021","headline":"PREPA, FOMB reach restructuring support agreement with bondholders","publishDate":"2018-07-31T11:59:00.000Z","productEditions":[{"edition":"North America","editionDisplayName":"Municipals","id":"512_2","product":"Debtwire"}],"dominantSector":{"mmgid":"prime-government","name":"Government"},"dominantCountry":{"mmgid":"prime-PRI","name":"Puerto Rico"},"reportType":{},"contentCategories":["headline"],"contentSubCategories":[],"isProprietary":false}],"created":"2018-07-31T11:59:09.196Z","createdReverseMs":-1533038349196,"isTest":false}",
    shortContentId: "intel-prime-2681021"
  },
  from: "750107557867",
  notification: {
    body: "PREPA, FOMB reach restructuring support agreement with bondholders",
    title: "Debtwire"
  },
  priority: "normal"
}

(there might be some subtle syntax/styling errors as I had to retype it).


If you think this issue has resolved, please close the issue or we can help resolve why the data was corrupted at the first place.

**Comment by tclarke-scottlogic** [comment] 2018-08-13 11:01
Closing issue. If we get a change to re-replicate, will raise a new card.

**Closed** 2018-08-13 11:01 UTC
Labels: Messaging

**Comment by tringuyen1121** [comment] 2019-06-06 13:30
Hi, @tclarke-scottlogic 

I'm getting exact the same issue as you. What is your fix for this? This is the message object from my server: 
```
collapseKey: undefined
data: {
     body: "Diane "Diane" Yellow posted to CHANNEL with Tri."
     eventType: "SHARE_ACTIVITY_IN_CHANNEL"
     notification: "{"id":"38174765","reference":{"channel_name":"CHANNEL with Tri","snippet":{"snippet":"jhfvih"},"entity_id":"72293187"},"referenceUser":{"id":"13","thumbnailPhotoUrl":"https://www.google.com/s2/photos/public/AIbEiAIAAABECPXU9Ojs5JeMuQEiC3ZjYXJkX3Bob3RvKihmZDZkYzk2YzBhMjg0MGIyZTI2MzdlYzM5NjkxZDhkZjk3NjNmZTI2MAGYHUIZNESK9p_08CKWd9WoeytLjQ?etag=GPUJN6YVAOElesyqxtgGs7jrFWY/Qrre1T0aEZyy0P6sNokgo8ITG9M","name":"Diane \"Diane\" Yellow"},"subscriber":{"id":"21659648","thumbnailPhotoUrl":"https://storage.googleapis.com/spacegapps_uploads/1328de30-2ade-4ace-8cbe-1d2272413fa7","name":"Tri Lesuthas"},"timestamp":{"millis":"1559827646138","isoString":"2019-06-06T13:27:26.138Z"},"eventType":"SHARE_ACTIVITY_IN_CHANNEL","url":"/workspace/12451840/discussion/72293187"}"
     title: "New post"
}
from: "779721836595"
messageId: "0:1559827646955863%70afb65af9fd7ecd"
messageType: undefined
sentTime: 1559827646953
ttl: 3600
```

**Comment by kumbhar-ketan** [comment] 2019-09-19 05:07
I'm also getting the same issue. Please help me ASAP. Thanks.

**Comment by tclarke-scottlogic** [comment] 2019-09-19 07:58
@tringuyen1121 @kumbhar-ketan 
Renaming the field from `notification` to something else was the workaround. Not sure if there's a fix.
https://github.com/firebase/firebase-ios-sdk/issues/1602#issuecomment-409273118

**Comment by chliangGoogle** [comment] 2019-09-19 18:18
I can't reproduce when putting a notification inside the data payload (@tclarke-scottlogic is that what you meant for the fix?)

@tringuyen1121 @kumbhar-ketan Are you trying to send a hidden data message or a display notification?

**Comment by kumbhar-ketan** [comment] 2019-09-20 05:31
Hey i got it solved. My issue was with the Pod file. It was giving me the same error as given above.
Solution - https://github.com/invertase/react-native-firebase/issues/2600
Thanks.
