### ISSUE TITLE
Memory leak at [FSTSerializerBeta decodeFieldvalue]

### ISSUE THREAD

**Issue by businessengine** [firebase/firebase-ios-sdk#2189] opened 2018-12-14 08:54 UTC
.### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.14.0
  * Firebase Component: Firestore
  * Component version: 0.16.1

### [REQUIRED] Step 3: Describe the problem
We found memory leaks from Firestore the Instruments tool while tracing leaks from other SDK.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
![image](https://user-images.githubusercontent.com/578995/49993015-2be08580-ffb8-11e8-8737-60eba37ba441.png)

**Comment by wilhuff** [comment] 2018-12-17 19:12
I can't reproduce a leak in FSTSerializerBeta, either using our tests or a sample application. Looking at the code I can't see an unbalanced retain/release there either. I did find some other leaks related to SCNetworkReachability and a gRPC leak in FillMetadataArray that I'll look at now.

Can you give some more detail about what you might have been doing to trigger this? Things that might be interesting are the shape of your data or the way you access it.

Also could you get a full copy of that stack trace? It's possible that the leak is not local the the serializer. You can get the stack in text form In Instruments by selecting all stack frames, copying, and pasting into a text editor.

**Comment by wilhuff** [comment] 2018-12-19 17:01
Absent more data there's not much I can do about this because I can't find any leak resembling this. Those I did find were fixed in the PR above.

If you are still able to see the leak in FSTSerializerBeta and can provide the additional information requested above we can reopen this and address it.

**Closed by wilhuff** 2018-12-19 17:01 UTC
Labels: Firestore
