### ISSUE TITLE
Firestore crash <firebase::firestore::util::AsyncQueue>

### ISSUE THREAD

**Issue by yusuftor** [firebase/firebase-ios-sdk#5485] opened 2020-04-28 15:16 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.21.0
  * Firebase Component: Firestore
  * Component version: 6.21.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
I've receive the following crash report that has come from a user of my app:

```
Crashed: com.google.firebase.firestore
0  libsystem_kernel.dylib         0x191959ec4 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1918751d8 pthread_kill$VARIANT$mp + 136
2  libsystem_c.dylib              0x1917c9844 abort + 100
3  libsystem_malloc.dylib         0x191862b80 _malloc_put + 558
4  libsystem_malloc.dylib         0x191862d38 malloc_report + 60
5  libsystem_malloc.dylib         0x191858124 free + 532
6  QJAM                           0x104f05dd0 std::__1::shared_ptr<firebase::firestore::util::AsyncQueue>::~shared_ptr() + 4301692368
7  QJAM                           0x104f8540c firebase::firestore::immutable::SortedMap<firebase::firestore::model::DocumentKey, absl::lts_2019_08_08::optional<firebase::firestore::model::MaybeDocument>, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey> >::~SortedMap() + 4302214156
8  QJAM                           0x104f96ab8 std::__1::__function::__func<std::__1::enable_if<!(std::is_same<void, decltype(fp0())>::value), decltype(fp0())>::type firebase::firestore::local::Persistence::Run<firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7>(absl::lts_2019_08_08::string_view, firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7)::'lambda'(), std::__1::allocator<std::__1::enable_if<!(std::is_same<void, decltype(fp0())>::value), decltype(fp0())>::type firebase::firestore::local::Persistence::Run<firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7>(absl::lts_2019_08_08::string_view, firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&)::$_7)::'lambda'()>, void ()>::operator()() + 4302285496
9  QJAM                           0x104f822e8 firebase::firestore::local::LevelDbPersistence::RunInternal(absl::lts_2019_08_08::string_view, std::__1::function<void ()>) + 4302201576
10 QJAM                           0x104f9312c firebase::firestore::local::LocalStore::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&) + 4302270764
11 QJAM                           0x104fdb494 firebase::firestore::core::SyncEngine::ApplyRemoteEvent(firebase::firestore::remote::RemoteEvent const&) + 4302566548
12 QJAM                           0x104fc736c firebase::firestore::remote::RemoteStore::RaiseWatchSnapshot(firebase::firestore::model::SnapshotVersion const&) + 4302484332
13 QJAM                           0x104ff7dc0 firebase::firestore::remote::WatchStream::NotifyStreamResponse(grpc::ByteBuffer const&) + 2148 (memory:2148)
14 QJAM                           0x104fd4ed0 firebase::firestore::remote::Stream::OnStreamRead(grpc::ByteBuffer const&) + 2637 (memory:2637)
15 QJAM                           0x104f688d8 std::__1::__function::__func<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0, std::__1::allocator<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0>, void ()>::operator()() + 1651 (functional:1651)
16 QJAM                           0x104f06a10 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 4301695504
17 QJAM                           0x104f26bb4 firebase::firestore::util::internal::DispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&)::$_0::__invoke(void*) + 4301826996
18 libdispatch.dylib              0x19182f184 _dispatch_client_callout + 16
19 libdispatch.dylib              0x1917db404 _dispatch_lane_serial_drain$VARIANT$mp + 608
20 libdispatch.dylib              0x1917dbdf8 _dispatch_lane_invoke$VARIANT$mp + 420
21 libdispatch.dylib              0x1917e5314 _dispatch_workloop_worker_thread + 588
22 libsystem_pthread.dylib        0x19187eb88 _pthread_wqthread + 276
23 libsystem_pthread.dylib        0x191881760 start_wqthread + 8
```

#### Steps to reproduce:

Unfortunately I can't reproduce it, it happened on a random persons device, and I don't have any more info than the above.

I'd be grateful if you could look into this crash.

**Comment by schmidt-sebastian** [comment] 2020-04-28 17:11
@yusuftor Thank you for this report. 

Unfortunately, the stacktrace in the Crash Report is rather broad and as such makes it a bit hard to pinpoint the issue. While I understand that this is a one off issue for you, it would help us a lot if you are able to reproduce this in a small sample app. Alternatively, would it be possible to share the code from your app that you think might be responsible?

Can you also let us know if you see this crash again?

**Comment by schmidt-sebastian** [comment] 2020-04-28 18:49
This might be related to https://github.com/firebase/firebase-ios-sdk/issues/5238.

If the above steps are not feasible for you, the steps in https://github.com/firebase/firebase-ios-sdk/issues/5238#issuecomment-607372681 might also let us determine the cause.

**Comment by yusuftor** [comment] 2020-04-29 16:49
@schmidt-sebastian thanks for the reply. Unfortunately it won't be possible to reproduce the crash because it happened on a random user's device and I don't know any more about it. I can't share code from my app either due to privacy reasons but firebase doesn't say that it's from heap corruption. Sorry I can't help any further!

**Comment by morganchen12** [comment] 2020-05-14 17:50
Closing this since it's not currently actionable by the Firestore team and the stack trace indicates the crash may not be caused by Firestore. Please let us know if you have more information and we'll reopen the issue.

**Closed by morganchen12** 2020-05-14 17:50 UTC
Labels: api: firestore
