### ISSUE TITLE
firebase sdk 7.0.0 update not working 

### ISSUE THREAD

**Issue by colondeethpark** [firebase/firebase-ios-sdk#7020] opened 2020-11-24 07:48 UTC
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

I am currently using firebase using cocoapods.
The current version is 6.34.0
I want to update to the latest version

But I raised it to project ios sdk 10.0
I also uploaded the pod file to 10.0
Firebase is not updated to the latest version.
How do I use version 7.0.0 or higher?

=-=------
Podfile.lock file
PODS:
  - ALSystemUtilities (1.3.4):
    - ALSystemUtilities/no-arc (= 1.3.4)
  - ALSystemUtilities/no-arc (1.3.4)
  - AppsFlyerFramework (5.4.4)
  - FBSDKCoreKit (8.2.0):
    - FBSDKCoreKit/Basics (= 8.2.0)
    - FBSDKCoreKit/Core (= 8.2.0)
  - FBSDKCoreKit/Basics (8.2.0)
  - FBSDKCoreKit/Core (8.2.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (8.2.0):
    - FBSDKLoginKit/Login (= 8.2.0)
  - FBSDKLoginKit/Login (8.2.0):
    - FBSDKCoreKit (~> 8.2.0)
  - Firebase/Analytics (6.34.0):
    - Firebase/Core
  - Firebase/Core (6.34.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.9.0)
  - Firebase/CoreOnly (6.34.0):
    - FirebaseCore (= 6.10.4)
  - Firebase/Crashlytics (6.34.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 4.6.2)
  - Firebase/MLVision (6.34.0):
    - Firebase/CoreOnly
    - FirebaseMLVision (~> 0.21.0)
  - Firebase/MLVisionFaceModel (6.34.0):
    - Firebase/CoreOnly
    - FirebaseMLVisionFaceModel (~> 0.21.0)
  - Firebase/Performance (6.34.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.3.1)
  - FirebaseABTesting (4.2.0):
    - FirebaseCore (~> 6.10)
  - FirebaseAnalytics (6.9.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.7)
    - GoogleAppMeasurement (= 6.9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseCore (6.10.4):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseCrashlytics (4.6.2):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleDataTransport (~> 7.2)
    - nanopb (~> 1.30906.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseMLCommon (0.21.0):
    - FirebaseCore (~> 6.9)
    - FirebaseInstallations (~> 1.5)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - GoogleUtilities/UserDefaults (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
  - FirebaseMLVision (0.21.0):
    - FirebaseCore (~> 6.9)
    - FirebaseMLCommon (~> 0.21)
    - GoogleAPIClientForREST/Core (~> 1.3)
    - GoogleAPIClientForREST/Vision (~> 1.3)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
  - FirebaseMLVisionFaceModel (0.21.0):
    - FirebaseMLVision (~> 0.21)
  - FirebasePerformance (3.3.2):
    - FirebaseCore (~> 6.9)
    - FirebaseInstallations (~> 1.5)
    - FirebaseRemoteConfig (~> 4.7)
    - GoogleDataTransport (~> 7.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (4.9.1):
    - FirebaseABTesting (~> 4.2)
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
  - GoogleAPIClientForREST/Core (1.5.1):
    - GTMSessionFetcher (>= 1.1.7)
  - GoogleAPIClientForREST/Vision (1.5.1):
    - GoogleAPIClientForREST/Core
    - GTMSessionFetcher (>= 1.1.7)
  - GoogleAppMeasurement (6.9.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - GoogleDataTransport (7.5.1):
    - nanopb (~> 1.30906.0)
  - GoogleToolboxForMac/DebugUtils (2.3.0):
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - GoogleToolboxForMac/Defines (2.3.0)
  - GoogleToolboxForMac/Logger (2.3.0):
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - "GoogleToolboxForMac/NSData+zlib (2.3.0)":
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.3.0)":
    - GoogleToolboxForMac/DebugUtils (= 2.3.0)
    - GoogleToolboxForMac/Defines (= 2.3.0)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.3.0)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.3.0)"
  - GoogleUtilities/AppDelegateSwizzler (6.7.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/ISASwizzler (6.7.2)
  - GoogleUtilities/Logger (6.7.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.7.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.2)"
  - GoogleUtilities/Reachability (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.7.2):
    - GoogleUtilities/Logger
  - GTMSessionFetcher (1.5.0):
    - GTMSessionFetcher/Full (= 1.5.0)
  - GTMSessionFetcher/Core (1.5.0)
  - GTMSessionFetcher/Full (1.5.0):
    - GTMSessionFetcher/Core (= 1.5.0)
  - HCSStarRatingView (1.5)
  - IQKeyboardManager (6.5.6)
  - lottie-ios (2.5.3)
  - Mantle (2.1.6):
    - Mantle/extobjc (= 2.1.6)
  - Mantle/extobjc (2.1.6)
  - nanopb (1.30906.0):
    - nanopb/decode (= 1.30906.0)
    - nanopb/encode (= 1.30906.0)
  - nanopb/decode (1.30906.0)
  - nanopb/encode (1.30906.0)
  - pop (1.0.12)
  - PromisesObjC (1.2.11)
  - Protobuf (3.13.0)
  - SDWebImage (5.10.0):
    - SDWebImage/Core (= 5.10.0)
  - SDWebImage/Core (5.10.0)
  - SpinKit (1.2.0)
  - TOCropViewController (2.5.5)
  - TTTAttributedLabel (2.0.0)
  - "UINavigationItem+Margin (2.1.1)"
  - YLProgressBar (3.10.2)

Podfile
 pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionFaceModel'

**Comment by ZComwiz** [comment] 2020-11-24 09:43
You can try using this format in your cocoapod and see the errors of cross dependencies:

pod 'Firebase/Core', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '7.1.0'

**Comment by paulb777** [comment] 2020-11-24 15:19
Likely, the problem is `pod 'Firebase/MLVisionFaceModel'`.  `MLVisionFaceModel` was deprecated in Firebase 6.x and removed in Firebase 7.x.

See https://developers.google.com/ml-kit/migration/ios for information about migrating it to the new `MLKit` replacement.

I'll close this issue, but feel free to continue the conversation here if you have more questions.

**Closed by paulb777** 2020-11-24 15:19 UTC
Labels: needs-triage, type: feature request
