### ISSUE TITLE
Error "Undefined symbols for architecture x86_64: "___isOSVersionAtLeast"" after adding Firebase (Xcode/Swift)

### ISSUE THREAD

**Issue by EvanMurphy17** [firebase/firebase-ios-sdk#5219] opened 2020-03-29 00:09 UTC
Contacted Firebase support and they told me to post here:

New project, installed Firebase 6.21.0 using cocoapods, tried to build and run into this error.

Xcode: Version 11.3.1 (11C504)
Toolchain: Swift 5.1.3 Release 2019-12-13 (a)

Full error:

Undefined symbols for architecture x86_64: "___isOSVersionAtLeast", referenced from: ___54+[GULSceneDelegateSwizzler proxyOriginalSceneDelegate]_block_invoke in GULSceneDelegateSwizzler.o +[GULSceneDelegateSwizzler handleSceneWillConnectToNotification:] in GULSceneDelegateSwizzler.o -[GULSceneDelegateSwizzler scene:openURLContexts:] in GULSceneDelegateSwizzler.o +[GULSecureCoding unarchivedObjectOfClasses:fromData:error:] in GULSecureCoding.o +[GULSecureCoding archivedDataWithRootObject:error:] in GULSecureCoding.o ld: symbol(s) not found for architecture x86_64 clang-7: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by paulb777** [comment] 2020-03-29 14:22
Are you able to reproduce with a [quickstart project](https://github.com/firebase/quickstart-ios)?

We'll likely need a reproducible example to help since this is likely an configuration or environment issue.

**Comment by EvanMurphy17** [comment] 2020-03-29 14:48
[Test.zip](https://github.com/firebase/firebase-ios-sdk/files/4399087/Test.zip)
I have created this Test file that is reproducing the error.

**Comment by paulb777** [comment] 2020-03-29 15:02
Hmm. Works fine for me with Xcode 11.3.1.  Please check the version you're using by selecting `About Xcode`:

![Screen Shot 2020-03-29 at 8 01 06 AM](https://user-images.githubusercontent.com/73870/77852437-8ee93200-7193-11ea-9461-f693f11a3f60.png)

**Comment by EvanMurphy17** [comment] 2020-03-29 15:04
<img width="569" alt="Screen Shot 2020-03-29 at 10 04 09 AM" src="https://user-images.githubusercontent.com/47575224/77852512-b0064e80-71a4-11ea-8dd6-cc83d4876b33.png">

**Comment by EvanMurphy17** [comment] 2020-03-29 15:12
@paulb777 switched the toolchain to fit what you sent over and it works now. Any reason it works on the Xcode toolchain but not the Swift toolchain? I am new to this

**Comment by paulb777** [comment] 2020-03-29 17:46
@EvanMurphy17 Some relevant discussion about the Swift toolchain issue here - https://forums.swift.org/t/undefined-symbol-isosversionatleast/29782.

In general, Firebase is validated with Xcode releases and toolchains included with those Xcode versions.

I'll close the issue since it looks like you're resolved.

**Closed by paulb777** 2020-03-29 17:46 UTC
Labels: needs-attention
