### ISSUE TITLE
Catalyst still cannot compile:  building for Mac Catalyst, but linking in object file built for iOS Simulator

### ISSUE THREAD

**Issue by imWildCat** [firebase/firebase-ios-sdk#5206] opened 2020-03-26 15:05 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version latest
  * Firebase Component: Analytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: latest
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Note: I've created a demo project: https://github.com/imWildCat/DemoFirebaseCatalyst

1. Create a demo project
2. Add these dependencies into `Podfile`:

```rb
pod 'Firebase/Analytics'
```

What happened? How can we make the problem occur?

Cannot build:

`Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector(FIRAnalyticsConnector_c162b9f6e9dd193ef13757b8d7ebe6f7.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '.../Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector' for architecture x86_64`

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment] 2020-03-26 15:25
Duplicate of #4563.  FirebaseAnalytics does not support Catalyst.

See https://github.com/firebase/firebase-ios-sdk#community-supported-efforts for a summary of what is available.

**Closed by paulb777** 2020-03-26 15:25 UTC
Labels: needs-triage

**Comment by imWildCat** [comment] 2020-03-28 09:32
Thanks. I can finally manage to exclude Firebase for the Catalyst target: https://stackoverflow.com/a/60612984/2949840
