### ISSUE TITLE
GoogleUtilities swizzling causing crashes: Fatal Exception: NSRangeException Cannot remove an observer NSTouchBarFinderObservation

### ISSUE THREAD

**Issue by arielelkin** [firebase/firebase-ios-sdk#9371] opened 2022-02-21 13:15 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.10.0
  * Installation method: Swift Package Manager
  * Firebase Component: Firebase Core
  * Target platform(s): macOS

#### Steps to reproduce:

Our app was regularly reporting crashes in `AppKit -[NSApplication run]` with these stack traces :

```
Fatal Exception: NSRangeException
Cannot remove an observer <_NSTouchBarFinderObservation 0x600000afd180> for the key path "nextResponder" from <GUL_SwiftUI.AppDelegate-55E6245C-CD16-4A21-B1A8-CE75DC32F6DA 0x600002eb8300> because it is not registered as an observer.

Fatal Exception: NSRangeException
0  CoreFoundation                 0xfa61b (Missing UUID afcc752e074d340f890c263efd2da77f)
1  libobjc.A.dylib                0x18dce (Missing UUID 6b22efe418cc355190bad18236104790)
2  Foundation                     0x54bbf (Missing UUID d7fd02144bbb3d8488f7820b25a6e16c)
3  Foundation                     0x548bf (Missing UUID d7fd02144bbb3d8488f7820b25a6e16c)
4  Foundation                     0x54577 (Missing UUID d7fd02144bbb3d8488f7820b25a6e16c)
5  AppKit                         0x6aff88 (Missing UUID dd0028a378e33a8aa51bddd68123adef)
6  AppKit                         0x6b042e (Missing UUID dd0028a378e33a8aa51bddd68123adef)
7  AppKit                         0x43ff9 (Missing UUID dd0028a378e33a8aa51bddd68123adef)
8  AppKit                         0x43e1d (Missing UUID dd0028a378e33a8aa51bddd68123adef)
9  Foundation                     0x34cfa (Missing UUID d7fd02144bbb3d8488f7820b25a6e16c)
10 Foundation                     0xf8c15 (Missing UUID d7fd02144bbb3d8488f7820b25a6e16c)
11 Foundation                     0x1a14be (Missing UUID d7fd02144bbb3d8488f7820b25a6e16c)
12 AppKit                         0x8f108c (Missing UUID dd0028a378e33a8aa51bddd68123adef)
13 AppKit                         0x8f13ff (Missing UUID dd0028a378e33a8aa51bddd68123adef)
14 CoreFoundation                 0x7f6ee (Missing UUID afcc752e074d340f890c263efd2da77f)
15 CoreFoundation                 0x7f5a2 (Missing UUID afcc752e074d340f890c263efd2da77f)
16 CoreFoundation                 0x7e251 (Missing UUID afcc752e074d340f890c263efd2da77f)
17 CoreFoundation                 0x7d809 (Missing UUID afcc752e074d340f890c263efd2da77f)
18 HIToolbox                      0x2f3e1 (Missing UUID 4163a93fbf71321980ed6f65e9266b81)
19 HIToolbox                      0x2f137 (Missing UUID 4163a93fbf71321980ed6f65e9266b81)
20 HIToolbox                      0x2eed5 (Missing UUID 4163a93fbf71321980ed6f65e9266b81)
21 AppKit                         0x3e8f0 (Missing UUID dd0028a378e33a8aa51bddd68123adef)
22 AppKit                         0x3cf5c (Missing UUID dd0028a378e33a8aa51bddd68123adef)
23 AppKit                         0x2f359 (Missing UUID dd0028a378e33a8aa51bddd68123adef)
24 AppKit                         0x31f8 (Missing UUID dd0028a378e33a8aa51bddd68123adef)
25 SwiftUI                        0x7b14f (Missing UUID 5863fd3b7aa7368c82792bc03e136cbb)
26 SwiftUI                        0xa90134 (Missing UUID 5863fd3b7aa7368c82792bc03e136cbb)
27 SwiftUI                        0x59b5af (Missing UUID 5863fd3b7aa7368c82792bc03e136cbb)
28 MyAppName                        0x78a6 (Missing UUID 81545a865b4537a29547217b97510876)
29 ???                            0x2051af4fe (Missing)
30 ???                            0x2051aa000 (Missing)
31 MyAppName                        0x0 (Missing UUID 81545a865b4537a29547217b97510876)



Crashed: com.google.firebase.crashlytics.mac.exception
EXC_BAD_INSTRUCTION EXC_I386_INVOP 0x0000000000000000

Crashed: com.google.firebase.crashlytics.mac.exception
0  MyAppName                        0x74f62 (Missing UUID 81545a865b4537a29547217b97510876)
1  MyAppName                        0x75353 (Missing UUID 81545a865b4537a29547217b97510876)
2  MyAppName                        0x6e36a (Missing UUID 81545a865b4537a29547217b97510876)
3  MyAppName                        0x6870f (Missing UUID 81545a865b4537a29547217b97510876)
4  libdispatch.dylib              0x2cc9 _dispatch_client_callout + 8
5  libdispatch.dylib              0x1013f _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  MyAppName                        0x67d89 (Missing UUID 81545a865b4537a29547217b97510876)
7  MyAppName                        0x6810b (Missing UUID 81545a865b4537a29547217b97510876)
8  MyAppName                        0x67ada (Missing UUID 81545a865b4537a29547217b97510876)
9  AppKit                         0x2f40c -[NSApplication run] + 765
10 AppKit                         0x31f8 NSApplicationMain + 816
11 SwiftUI                        0x7b14f $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5 + 161
12 SwiftUI                        0xa90134 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 164
13 SwiftUI                        0x59b5af $s7SwiftUI3AppPAAE4mainyyFZ + 63
14 MyAppName                        0x78a6 (Missing UUID 81545a865b4537a29547217b97510876)
15 ???                            0x2051af4fe (Missing)
16 ???                            0x2051aa000 (Missing)
17 MyAppName                        0x0 (Missing UUID 81545a865b4537a29547217b97510876)
```

Nowhere in our app code (nor in our third-party code) were we manipulating the TouchBar or adding or removing observers related to it.

The "Missing UUID" messages are puzzling, as we've uploaded that app's DSYMs and indeed other crashes reported by the same app version were being symbolicated without issues.

As an experiment, we pushed out a build where the only change was adding `FirebaseAppDelegateProxyEnabled` to the info plist and set it to `NO`. The crash was no longer reported. 

This [StackOverflow post ](https://stackoverflow.com/questions/71091412/is-there-a-way-to-understand-what-is-causing-a-crash-involving-nstouchbarfinde) would seem to corroborate this.

**Comment by paulb777** [comment] 2022-02-21 14:55
Thanks for sharing the issue. Given the workaround, the issue is likely related to the AppDelegate swizzler.

**Comment by ptrkstr** [comment] 2022-02-23 19:29
Thanks for reporting this @arielelkin, I forgot that I should probably raise it as a bug as well 😋

**Comment by chliangGoogle** [comment] 2022-02-23 19:34
@arielelkin To help me reproduce the bug, can you list all the firebase products you use? From the stackoverflow, it seems like analytics is used. Can you provide me a full list?

**Comment by arielelkin** [comment] 2022-02-24 11:31
@chliangGoogle In our app we're just using Crashlytics and Analytics.

**Comment by chliangGoogle** [comment] 2022-03-10 22:47
@arielelkin If you only use Crashlytics and Analytics+SwiftUI, you should be fine to turn off the swizzling.

I'm not able to reproduce with mac app. Also the crash log doesn't really specify Firebase anywhere but I guess it could be maybe the swizzling is not working properly with UIKit. Would you able to send me a small sample code on how you initialize firebase and calling analytics code in your app? Also I would like to know you are building a swiftUI lifecycle or regular appDelegate lifecycle mac app.

**Comment by ptrkstr** [comment] 2022-03-11 03:57
> @arielelkin If you only use Crashlytics and Analytics+SwiftUI, you should be fine to turn off the swizzling.
> 
> 
> 
> I'm not able to reproduce with mac app. Also the crash log doesn't really specify Firebase anywhere but I guess it could be maybe the swizzling is not working properly with UIKit. Would you able to send me a small sample code on how you initialize firebase and calling analytics code in your app? Also I would like to know you are building a swiftUI lifecycle or regular appDelegate lifecycle mac app.

@chliangGoogle you mentioned UIKit but this is a Mac app and therefore doesn't use it. Did you mean AppKit?

**Comment by arielelkin** [comment] 2022-03-14 10:52
> the crash log doesn't really specify Firebase anywhere but I guess it could be maybe the swizzling is not working properly with UIKit.

How do you mean? The second part of the crash log indicates that the thread that crashed is `com.google.firebase.crashlytics.mac.exception`

Also, there is no UIKit in my app, it's purely macOS.

> Would you able to send me a small sample code on how you initialize firebase and calling analytics code in your app? 

This is how I initialise Firebase: 
```swift
UserDefaults.standard.register(defaults: ["NSApplicationCrashOnExceptions" : true])
FirebaseApp.configure()
```

This is how I record events:

```swift
// record analytic event: 
Crashlytics.crashlytics().setCustomKeysAndValues(properties) // properties is [String: String]
FirebaseAnalytics.Analytics.logEvent(event.rawValue, parameters: properties) // event.rawValue is a String

// record error event: 
Crashlytics.crashlytics().setCustomKeysAndValues(properties)
let errorDomain = String(reflecting: error).components(separatedBy: ".").dropFirst().joined(separator: ".")
Crashlytics.crashlytics().record(error: NSError(domain: errorDomain, code: 0, userInfo: nil))
```

> Also I would like to know you are building a swiftUI lifecycle or regular appDelegate lifecycle mac app.

I have a SwiftUI `App` instance that instantiates my `AppDelegate` instance via `@NSApplicationDelegateAdaptor`

**Comment by morganchen12** [comment] 2022-03-14 20:21
Crashlytics will sometimes incorrectly blame the crash recorder thread when crashes occur. This cause is most likely not caused by Crashlytics.

Given the exception message, it's most likely caused by the GoogleUtilities swizzling behavior.
```
Cannot remove an observer <_NSTouchBarFinderObservation 0x600000afd180> for the key path "nextResponder" from <GUL_SwiftUI.AppDelegate-55E6245C-CD16-4A21-B1A8-CE75DC32F6DA 0x600002eb8300> because it is not registered as an observer.
```
If you can symbolicate the stack trace or reproduce the crash with an exception breakpoint, that would be helpful as well.

**Comment by ptrkstr** [comment] 2022-03-15 03:09
@morganchen12 see here for an example stack trace 

https://stackoverflow.com/questions/71091412/is-there-a-way-to-understand-what-is-causing-a-crash-involving-nstouchbarfinde

**Comment by arielelkin** [comment] 2022-04-04 09:14
@chliangGoogle @morganchen12 any updates?

**Comment by paulb777** [comment] 2024-06-05 04:10
Closing for staleness. If this is still an issue, please comment here or open another issue referencing this one.

**Closed by paulb777** 2024-06-05 04:10 UTC
Labels: GoogleUtilities, macOS
