### ISSUE TITLE
Crashed: com.google.fira.worker

### ISSUE THREAD

**Issue by itsMeSyedPS** [firebase/firebase-ios-sdk#10485] opened 2022-11-11 14:57 UTC
### Description

Attached is the stack trace logs from crashlytics
```
Crashed: com.google.fira.worker
0  libsystem_platform.dylib       0x404c _os_unfair_lock_unowned_abort + 36
1  libsystem_platform.dylib       0x54f4 _os_unfair_lock_unlock_slow + 144
2  libsqlite3.dylib               0x795ac sqlite3_randomness + 4204
3  libsqlite3.dylib               0x58ba4 sqlite3_value_text + 26348
4  libsqlite3.dylib               0x58580 sqlite3_value_text + 24776
5  libsqlite3.dylib               0x23e30 sqlite3_finalize + 3696
6  libsqlite3.dylib               0x50404 sqlite3_step + 64128
7  libsqlite3.dylib               0x40b40 sqlite3_step + 444
8  libsqlite3.dylib               0x95f8 sqlite3_exec + 324
9  Polestar Systems               0x34daec -[APMSqliteStore endTransaction] + 44
10 Polestar Systems               0x34d950 -[APMSqliteStore performTransactionWithError:block:] + 224
11 Polestar Systems               0x2ba760 -[APMDatabase performTransaction:] + 48
12 Polestar Systems               0x2fb450 -[APMMeasurement(Event) writeFilteredEventOnWorkerQueue:] + 264
13 Polestar Systems               0x2fb098 -[APMMeasurement(Event) writeEventOnWorkerQueue:] + 1444
14 Polestar Systems               0x2fa984 -[APMMeasurement(Event) handleEventOnWorkerQueue:] + 540
15 Polestar Systems               0x2eea84 -[APMMeasurement logEventOnWorkerQueue:notifyEventListeners:] + 76
16 Polestar Systems               0x2eea34 -[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 708
17 Polestar Systems               0x2ee6c8 __151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 68
18 Polestar Systems               0x343088 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 44
19 libdispatch.dylib              0x5fa38 _dispatch_call_block_and_release + 24
20 libdispatch.dylib              0x607d4 _dispatch_client_callout + 16
21 libdispatch.dylib              0x9324 _dispatch_lane_serial_drain$VARIANT$mp + 592
22 libdispatch.dylib              0x9e40 _dispatch_lane_invoke$VARIANT$mp + 428
23 libdispatch.dylib              0x124ac _dispatch_workloop_worker_thread + 596
24 libsystem_pthread.dylib        0xc114 _pthread_wqthread + 304
25 libsystem_pthread.dylib        0xecd4 start_wqthread + 4
```

### Reproducing the issue

There are no specific steps to reproduce this issue but the app crashes when switching between the views at the same time I am performing some transactions into the SQL database but somehow firebase is making the app crash.

I am using firebase crashlytics, firebase analytics, and firebase auth.

### Firebase SDK Version

9.6.0

### Xcode Version

14.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "pins" : [
    {
      "identity" : "abseil-cpp-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/abseil-cpp-SwiftPM.git",
      "state" : {
        "revision" : "583de9bd60f66b40e78d08599cc92036c2e7e4e1",
        "version" : "0.20220203.2"
      }
    },
    {
      "identity" : "boringssl-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/boringssl-SwiftPM.git",
      "state" : {
        "revision" : "dd3eda2b05a3f459fc3073695ad1b28659066eab",
        "version" : "0.9.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "7e80c25b51c2ffa238879b07fbfc5baa54bb3050",
        "version" : "9.6.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "c1cfde8067668027b23a42c29d11c246152fe046",
        "version" : "9.6.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "5056b15c5acbb90cd214fe4d6138bdf5a740e5a8",
        "version" : "9.2.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "68ea347bdb1a69e2d2ae2e25cd085b6ef92f64cb",
        "version" : "7.9.0"
      }
    },
    {
      "identity" : "grpc-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/grpc/grpc-ios.git",
      "state" : {
        "revision" : "8440b914756e0d26d4f4d054a1c1581daedfc5b6",
        "version" : "1.44.3-grpc"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "5ccda3981422a84186387dbb763ba739178b529c",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "3e4e743631e86c8c70dbc6efdc7beaa6e90fd3bb",
        "version" : "2.1.1"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "ab3a58b7209a17d781c0d1dbb3e1ff3da306bae8",
        "version" : "1.20.3"
      }
    }
  ],
  "version" : 2
}


```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by morganchen12** [comment] 2022-11-15 23:11
Duplicate of #5503.

We've never been able to repro this crash, but had something similar happen with a partner who was using a custom version of sqlite3.

**Closed** 2022-11-15 23:11 UTC
Labels: api: analytics
