### ISSUE TITLE
Project cannot build in XCode 15 beta 3

### ISSUE THREAD

**Issue by dpyy** [firebase/firebase-ios-sdk#11516] opened 2023-07-07 18:50 UTC
### Description

Project is using swift package manager set to Master. I think the version installed is 10.11.0

`null objc class data for '_OBJC_METACLASS_$_APMPrivateSetMembershipClient' in '/Users/X/Library/Developer/Xcode/DerivedData/X-himgkzgxmepuzhbmyfqwrsqoymyi/Build/Products/Debug-iphoneos/GoogleAppMeasurementOnDeviceConversion.framework/GoogleAppMeasurementOnDeviceConversion[arm64][2](arm64_merged.o)`

### Firebase SDK Version

10.11.0

### Xcode Version

15 beta 3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-07-07 19:19
Looks like the problem is with Analytics, not Auth.

**Comment by htcgh** [comment] 2023-07-10 18:52
@dpyy @morpholio Thanks for the report. Looks like Xcode 15 beta 3 introduced a new [linker](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking). While we investigate this issue, the workaround for now would be to use the classic linker by including `-ld64` in the 'Other Linker Flags' build setting.

**Comment by mushao1990** [comment] 2023-07-11 09:15
> @dpyy @morpholio Thanks for the report. Looks like Xcode 15 beta 3 introduced a new [linker](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking). While we investigate this issue, the workaround for now would be to use the classic linker by including `-ld64` in the 'Other Linker Flags' build setting.

oh,thanks~ it works

**Comment by via-guy** [comment] 2023-07-12 14:10
Problem is that then we can't compile in Xcode 14. Any suggestions?

**Comment by dpyy** [comment] 2023-07-12 15:26
Same, we need to compile in 14 and 15, please fix

**Comment by morpholio** [comment] 2023-07-12 19:04
The workaround is also helping us out, thank you for that @htcgh. We're toggling the flag from machine to machine to deal with the Xcode 14 vs 15 issue. It's not ideal but we can at least continue our iOS 17 and Vision Pro work while we wait for a more permanent fix.

**Comment by dpyy** [comment] 2023-07-12 19:53
but why cant they fix it? It's been broken since beta1, what are they doing?

**Comment by EggsBlue** [comment] 2023-07-22 14:21
> 

cool, it solved my issue

**Comment by htcgh** [comment] 2023-08-09 19:33
This issue appears to be fixed in Xcode 15 beta 6.

**Closed by htcgh** 2023-08-09 19:33 UTC
Labels: api: analytics, Xcode 15 - iOS 17
