### ISSUE TITLE
ASWebAuthenticationSession error when using GIDSignIn 

### ISSUE THREAD

**Issue by ajkolean** [firebase/firebase-ios-sdk#3791] opened 2019-09-06 17:15 UTC
### [READ] Step 1: Are you in the right place?

YES

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0 beta 7
  * Firebase SDK version: 6.7.0
  * Firebase Component:  Auth
  * Component version: 6.7.0

My Podfile.lock is

```
  - Firebase/Analytics (6.7.0):
    - Firebase/Core
  - Firebase/Auth (6.7.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.2.3)
  - Firebase/Core (6.7.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.1)
  - Firebase/CoreOnly (6.7.0):
    - FirebaseCore (= 6.2.1)
  - Firebase/DynamicLinks (6.7.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 4.0.3)
  - Firebase/Firestore (6.7.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.4.4)
  - Firebase/Functions (6.7.0):
    - Firebase/CoreOnly
    - FirebaseFunctions (~> 2.5.1)
  - Firebase/Messaging (6.7.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.1.3)
  - Firebase/Performance (6.7.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.2)
  - Firebase/RemoteConfig (6.7.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.3.0)
  - Firebase/Storage (6.7.0):
    - Firebase/CoreOnly
    - FirebaseStorage (~> 3.4.0)
  - FirebaseABTesting (3.1.0):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (~> 3.8)
  - FirebaseAnalytics (6.1.1):
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.4.0)
  - FirebaseAuth (6.2.3):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.2.1):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnostics (1.0.1):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnosticsInterop (1.0.0)
  - FirebaseDynamicLinks (4.0.3):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
  - FirebaseFirestore (1.4.5):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - FirebaseFirestore/abseil-cpp (= 1.4.5)
    - "gRPC-C++ (= 0.0.9)"
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (1.4.5):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - "gRPC-C++ (= 0.0.9)"
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.901)
    - Protobuf (~> 3.1)
  - FirebaseFunctions (2.5.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseInstanceID (4.2.3):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebaseMessaging (4.1.3):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Reachability (~> 6.2)
    - GoogleUtilities/UserDefaults (~> 6.2)
    - Protobuf (~> 3.1)
  - FirebasePerformance (3.1.2):
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - FirebaseRemoteConfig (~> 4.2)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/ISASwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseRemoteConfig (4.3.0):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - Protobuf (~> 3.5)
  - FirebaseStorage (3.4.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)```
```

### [REQUIRED] Step 3: Describe the problem

Trying to sign in with Google causes crash.

```
 NSError    domain: "com.google.GIDSignIn" - code: 18446744073709551615    0x0000000283cd0390
Error Domain=com.google.GIDSignIn Code=-1 "The operation couldn’t be completed. (org.openid.appauth.general error -3.)" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (org.openid.appauth.general error -3.)}
```

**Comment by morganchen12** [comment] 2019-09-06 23:27
Can you share the stack trace of the crash? The error log at the bottom is a non-fatal error.

**Comment by jlaws** [comment] 2019-09-10 10:30
@morganchen12 it does not crash for us, it just fails with the error posted above.

**Comment by ajkolean** [comment] 2019-09-11 04:38
Yes my mistake the error is being called in `func sign( _ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!)` with the above set as the error.

More on the error:
`
Error Domain=org.openid.appauth.general Code=-3 "(null)" UserInfo={NSUnderlyingError=0x6000007cf240 {Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}}}
/*! @abstract Provides context to target where in an application's UI the authorization view should be shown. A provider
must be set prior to calling -start, otherwise the authorization view cannot be displayed. If deploying to iOS prior to
13.0, the desired window is inferred by the application's key window.
*/
@property (nonatomic, weak) id <ASWebAuthenticationPresentationContextProviding> presentationContextProvider API_AVAILABLE(ios(13.0), macos(10.15));
`
line 90 of OIDExternalUserAgentIOS.m
`
Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}
`
Investigating OIDExternalUserAgentIOS.m more it looks like something must have changed in apple's framework and `_presentingViewController.view.window` is now returning nil. UIWindow from a view is returning nil even when the VC is on the screen. Updating the return statement on line to return the sharedWindow resolves the issue.

`
- (ASPresentationAnchor)presentationAnchorForWebAuthenticationSession:(ASWebAuthenticationSession *)session API_AVAILABLE(ios(13.0)){
  return _presentingViewController.view.window;
}
`
However, this code isn't ideal.  **OIDExternalUserAgentIOS** should ask for a window rather then trying to derive it from the ViewController that is provided.

**Comment by morganchen12** [comment] 2019-09-11 10:48
@renkelvin based on the error posted above it looks like we're misusing AuthenticationServices. Can you investigate?

**Comment by renkelvin** [comment] 2019-09-11 18:32
@morganchen12 Firebase Auth doesn't depend on AuthenticationServices. It seems an issue with GSI.

**Comment by renkelvin** [comment] 2019-09-17 23:05
There is a compatibility issue with AppAuth 1.1.0 https://github.com/openid/AppAuth-iOS/commit/d16caab0115fca52f7deb0e93866ab6b657574a2
GoogleSignIn gonna release a new version with AppAuth 1.2.0 which will fix this issue.

**Comment by nndb05123** [comment] 2019-10-02 03:14
how to fixed ???? :(

**Comment by renkelvin** [comment] 2019-10-02 17:46
You'll get AppAuth 1.2.0 now if using CocoaPods, which should fixed this issue.

**Comment by tkrajacic** [comment] 2019-10-02 17:54
Why is this issue closed? There is still no new binary release which fixes the issue.
Using Cocoapods is not a viable solution for many users, so this is still broken in the latest binary release here: https://developers.google.com/identity/sign-in/ios/sdk/

**Comment by paulb777** [comment] 2019-10-02 18:04
@tkrajacic Good point. Thanks! 

This issue was missing a milestone.  I've updated the issue to include the 6.10.0 milestone which is stabilizing now and should publish next week for CocoaPods, Carthage, and the [Firebase binary release](https://github.com/firebase/firebase-ios-sdk/releases). I can't speak for the GoogleSignIn releases.

Our policy in this repo is to close issues when they're fixed in source and do release tracking based on the associated milestone.

**Comment by vetrovosk** [comment] 2019-10-09 12:31
Even after release of 6_10_0 we still do observe the same behaiour on devices running iOS 13.

After invoking `[[GIDSignIn sharedInstance] signIn]` with GoogleSignIn framework from Firebase binary distribution we see `"The app" Want to use google.com to signin" modal dialog that appears briefly and then hides itself and that's it.

**Comment by paulb777** [comment] 2019-10-09 13:21
@vetrovosk Please confirm that you updated the AppAuth.framework to the version 1.2.0 from the zip download, did a clean rebuild, and removed DerivedData(`rm -rf ~/Library/Developer/Xcode/DerivedData/`)

**Comment by vetrovosk** [comment] 2019-10-09 13:47
Yes, I confirm that I've just made a clone of [google signin sample app](https://github.com/googlesamples/google-services/tree/master/ios/signin), opened it in Xcode 11, changed client id in app delegate, changed `CFBundleURLTypes` in `Info.plist` accordingly, added `-ObjC` linked flag, and dragged and dropped all the frameworks from `Firebase/GoogleSignIn` and `GoogleSignIn/Resources/GoogleSignIn.bundle` into the project (with "Copy items if needed" checkbox checked).

**Comment by vetrovosk** [comment] 2019-10-09 14:50
Yes, I even think that I've mentioned that their fix uses compile time checks that don't get applied when built against older versions of ios sdk in the support Case 00011522 submitted to firebase-support@google.com :-)

Thanks!

**Comment by paulb777** [comment] 2019-10-10 02:29
According to the GoogleSignIn team, the 5.0.1 zip file downloadable from https://developers.google.com/identity/sign-in/ios/sdk has the fix.

I'll leave this issue open until we have a resolution for the Firebase zip and Carthage distribution.

**Comment by NathanWalker** [comment] 2019-10-15 17:33
Is anyone still running into this issue with latest Firebase 6.10.0? Seems still occurs - perhaps that's what you're referring to @paulb777 that everyone still waiting on full resolution in Firebase ditro? Perhaps in a 6.11.0 upcoming release?

**Comment by paulb777** [comment] 2019-10-15 17:39
@NathanWalker We don't have a mechanism in Firebase to support different binaries for both Xcode 10 and Xcode 11, so we're planning to drop distribution of the GoogleSignIn binary and instead reference the GoogleSignIn team's official distribution channel at https://developers.google.com/identity/sign-in/ios/sdk

**Comment by vetrovosk** [comment] 2019-10-15 19:19
@paulb777 when we try to use[ GoogleSignIn SDK](https://developers.google.com/identity/sign-in/ios/sdk) instead of `Firebase/GoogleSignIn/` together with the rest of Firebase SDK `v6.10.0` (we use `Firebase/Analytics`, `Firebase/Performance` and Crashlytics) our Xcode build failes with a lot of the errors like these:

```
duplicate symbol '_OBJC_IVAR_$_GTMSessionFetcherService._userAgent' in:
    ..//../delightex-statistics-moe/build/SDK/Firebase/Performance/GTMSessionFetcher.framework/GTMSessionFetcher(GTMSessionFetcherService.o)
    ..//../delightex-statistics-moe/build/SDK/GoogleSignIn/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMSessionFetcherService_2e227824097119dae0a3dbbaed733920.o)
duplicate symbol '_OBJC_IVAR_$_GTMSessionFetcherService._allowInvalidServerCertificates' in:
    ..//../delightex-statistics-moe/build/SDK/Firebase/Performance/GTMSessionFetcher.framework/GTMSessionFetcher(GTMSessionFetcherService.o)
    ..//../delightex-statistics-moe/build/SDK/GoogleSignIn/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMSessionFetcherService_2e227824097119dae0a3dbbaed733920.o)
duplicate symbol '_OBJC_IVAR_$_GTMSessionFetcherService._allowedInsecureSchemes' in:
    ..//../delightex-statistics-moe/build/SDK/Firebase/Performance/GTMSessionFetcher.framework/GTMSessionFetcher(GTMSessionFetcherService.o)
    ..//../delightex-statistics-moe/build/SDK/GoogleSignIn/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMSessionFetcherService_2e227824097119dae0a3dbbaed733920.o)
duplicate symbol '_OBJC_IVAR_$_GTMSessionFetcherService._properties' in:
    ..//../delightex-statistics-moe/build/SDK/Firebase/Performance/GTMSessionFetcher.framework/GTMSessionFetcher(GTMSessionFetcherService.o)
    ..//../delightex-statistics-moe/build/SDK/GoogleSignIn/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMSessionFetcherService_2e227824097119dae0a3dbbaed733920.o)
duplicate symbol '_OBJC_IVAR_$_GTMSessionFetcherService._stoppedFetchersToWaitFor' in:
    ..//../delightex-statistics-moe/build/SDK/Firebase/Performance/GTMSessionFetcher.framework/GTMSessionFetcher(GTMSessionFetcherService.o)
    ..//../delightex-statistics-moe/build/SDK/GoogleSignIn/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMSessionFetcherService_2e227824097119dae0a3dbbaed733920.o)
duplicate symbol '_OBJC_IVAR_$_GTMSessionFetcherService._authorizer' in:
    ..//../delightex-statistics-moe/build/SDK/Firebase/Performance/GTMSessionFetcher.framework/GTMSessionFetcher(GTMSessionFetcherService.o)
    ..//../delightex-statistics-moe/build/SDK/GoogleSignIn/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMSessionFetcherService_2e227824097119dae0a3dbbaed733920.o)
duplicate symbol '_OBJC_IVAR_$_GTMSessionFetcherSessionDelegateDispatcher._discardTimer' in:
    ..//../delightex-statistics-moe/build/SDK/Firebase/Performance/GTMSessionFetcher.framework/GTMSessionFetcher(GTMSessionFetcherService.o)
    ..//../delightex-statistics-moe/build/SDK/GoogleSignIn/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMSessionFetcherService_2e227824097119dae0a3dbbaed733920.o)
```

**Comment by paulb777** [comment] 2019-10-15 19:23
Thanks for the report @vetrovosk 

A likely workaround would be to stop linking the GTMSessionFetcher.framework from Firebase.

**Comment by peteyblah** [comment] 2019-10-17 21:49
I'm still having this issue, any timeframe for when this might be fixed? Thanks.

**Comment by paulb777** [comment] 2019-10-17 21:53
@peteyblah To summarize, the issue is fixed for CocoaPods users. For binary distro users, you need to use one of the workarounds discussed above. We're targeting a binary distribution solution for the M59 release, which is roughly three weeks from now.

**Comment by peteyblah** [comment] 2019-10-17 22:03
I've read through the thread, I've tried using the package from the GoogleSignIn team with the 5.0.1 zip, but end up having the same error as mentioned above (even after a clean build and clearing derived data), that I get with the complete Firebase package.

**Comment by paulb777** [comment] 2019-11-06 01:48
This should be fixed in today's Firebase 6.12.0 in which the zip and Carthage distros are built with Xcode 11 instead of Xcode 10.

cc: @maksymmalyhin

**Comment by olejnjak** [comment] 2019-11-06 07:05
I'm afraid that I'm experiencing the same issue even with 6.12.0 release. Calling `GIDSignIn.shared.signIn()` almost immediately fails with error `The operation couldn’t be completed. (org.openid.appauth.general error -3.)`

**Comment by paulb777** [comment] 2019-11-06 19:21
@olejnjak Thanks for the report and sorry about that. 

It turns out we had a problem with the release scripting and that the Carthage distribution was still built with Xcode 10. We plan to fix in the next release.

In the meantime, a workaround for Carthage users is to use `GoogleSignIn.framework` from the [zip distribution](https://github.com/firebase/firebase-ios-sdk/releases/tag/6.12.0).

**Comment by ryanwilson** [comment] 2019-11-15 15:34
Firebase 6.13.0 was published to Carthage moments ago and was packaged with Xcode 11. This should be resolved now, please re-open if you still run into issues.

**Closed by ryanwilson** 2019-11-15 15:34 UTC
Labels: Carthage, api: auth, iOS 13, zip-builder
