### ISSUE TITLE
Missing InAppMessagingDisplayResources.bundle with Carthage installation

### ISSUE THREAD

**Issue by matickunaver** [firebase/firebase-ios-sdk#2603] opened 2019-03-21 14:20 UTC
* Xcode version: 10.1
  * Firebase SDK version: 5.19
  * Firebase Component: InAppMessaging
  * Component version: 5.19

Using **Carthage** to include Firebase with my app. 
App crashes when trying to present InApp display message with:

```
 5.19.0 - [Firebase/InAppMessaging][] Fetch is done. Start message rendering flow.
 App[] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
```

I cannot find the  _InAppMessagingDisplayResources.bundle_ included with the Framework.

**Comment by paulb777** [comment] 2019-03-21 14:35
Confirmed. Thanks for the report @matickunaver.

Workarounds are specifying version 5.18.0 for InAppMessagingDisplay in the Cartfile or applying the Resource bundle from the 5.18.0 install to the 5.19.0 install.

**Comment by paulb777** [comment] 2019-03-29 17:13
Fixed in 5.20.0

**Closed by paulb777** 2019-03-29 17:13 UTC
Labels: Carthage, Infrastructure, api: inappmessaging

**Comment by thebugcode** [comment] 2019-05-02 10:37
Still crashes, in 5.20.0 for me

**Comment by thebugcode** [comment] 2019-05-02 12:25
@paulb777  The reason of the crash is the use of [NSBundle mainbundle] in FIRIAMDefaultDisplayImpl getViewResourceBundle. 

The InAppMessagingDisplayResources.bundle is not always to be found in the main bundle.

**Comment by paulb777** [comment] 2019-05-02 15:40
@thebugcode InAppMessagingDisplay is a static framework that is linked at build time, so its resources should be part of the main bundle.

**Comment by kostapappas** [comment] 2019-05-10 10:14
same with pod install
my app crash when receives in-app message
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
<img width="288" alt="Screenshot 2019-05-10 at 13 13 35" src="https://user-images.githubusercontent.com/3284228/57520093-80005380-7325-11e9-967a-6307f40a5c87.png">

**Comment by nikhildange** [comment] 2019-05-27 10:55
facing the same issue with pod install.

**Comment by nikhildange** [comment] 2019-05-28 10:23
> same with pod install
> my app crash when receives in-app message
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
> <img alt="Screenshot 2019-05-10 at 13 13 35" width="288" src="https://user-images.githubusercontent.com/3284228/57520093-80005380-7325-11e9-967a-6307f40a5c87.png">

Did you get any solution? https://github.com/firebase/firebase-ios-sdk/issues/3090

**Comment by AlexisQapa** [comment] 2019-06-21 12:18
I have the same issue with 6.0.0, the issue is closed is there any solution ?

**Comment by Nicholmon** [comment] 2019-06-27 12:52
Same issue hereSame here with 6.3.0. I have embedded both `FirebaseInAppMessaging` and `FirebaseInAppMessagingDisplay.framework`. Looking into the built frameworks, it seems the `InAppMessagingDisplayResources.bundle` lies inside `FirebaseInAppMessaging.framework` but it crashes with the same error mentioned above:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'

**Comment by AlexisQapa** [comment] 2019-06-27 15:01
@Nicholmon quick fix run a script at the end of the build copying the bundle to your app bundle. As Firease is statically linked it uses the app bundle.

**Comment by Anastassi** [comment] 2019-07-23 11:46
6.5.0 - same issue - keeps crashing.
@AlexisQapa did you succeeded in running script? Can you share it, please?

**Comment by Tripwire999** [comment] 2019-10-14 14:33
Having the same issue Firebase core 6.2 with FirebaseInAppMessagingDisplay 0.15.5
