### ISSUE TITLE
Crash on GDTCORStorage.m line

### ISSUE THREAD

**Issue by vnavarro** [firebase/firebase-ios-sdk#4691] opened 2020-01-16 12:34 UTC
* Device: iPhone XR
* OS: 13.3.0

```
PODS:
  - Alamofire (4.9.1)
  - Branch (0.30.1):
    - Branch/Core (= 0.30.1)
  - Branch/Core (0.30.1)
  - Charts (3.4.0):
    - Charts/Core (= 3.4.0)
  - Charts/Core (3.4.0)
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - Eureka (5.1.0)
  - Fabric (1.10.2)
  - Firebase/Analytics (6.14.0):
    - Firebase/Core
  - Firebase/Core (6.14.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.7)
  - Firebase/CoreOnly (6.14.0):
    - FirebaseCore (= 6.5.0)
  - FirebaseAnalytics (6.1.7):
    - FirebaseCore (~> 6.5)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.7)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseCore (6.5.0):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.4)
    - GoogleUtilities/Logger (~> 6.4)
  - FirebaseCoreDiagnostics (1.1.2):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.1.0)
  - FirebaseInstanceID (4.2.7):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FLAnimatedImage (1.0.12)
  - Fuzi (3.1.1)
  - GoogleAppMeasurement (6.1.7):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - GoogleDataTransport (3.2.0)
  - GoogleDataTransportCCTSupport (1.2.3):
    - GoogleDataTransport (~> 3.2)
    - nanopb (~> 0.3.901)
  - GoogleUtilities/AppDelegateSwizzler (6.4.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.4.0)
  - GoogleUtilities/Logger (6.4.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.4.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.4.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.4.0)"
  - GoogleUtilities/Reachability (6.4.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.4.0):
    - GoogleUtilities/Logger
  - InputBarAccessoryView (4.2.2)
  - Instabug (9.0.1)
  - Intercom (6.0.0)
  - MessageKit (3.0.0):
    - InputBarAccessoryView (~> 4.2.2)
  - Moya/Core (13.0.1):
    - Alamofire (~> 4.1)
    - Result (~> 4.1)
  - Moya/RxSwift (13.0.1):
    - Moya/Core
    - RxSwift (~> 4.0)
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - Plaid (1.1.25)
  - ReachabilitySwift (5.0.0)
  - Result (4.1.0)
  - RxSwift (4.5.0)
  - SDWebImage (4.4.7):
    - SDWebImage/Core (= 4.4.7)
  - SDWebImage/Core (4.4.7)
  - SDWebImage/GIF (4.4.7):
    - FLAnimatedImage (~> 1.0)
    - SDWebImage/Core
  - SwiftLint (0.38.0)
  - SwiftyJSON (5.0.0)
  - TouchVisualizer (3.1.0)
  - XLPagerTabStrip (9.0.0)

DEPENDENCIES:
  - Branch
  - Charts
  - Crashlytics
  - Eureka
  - Fabric
  - Firebase/Analytics
  - Fuzi
  - Instabug
  - Intercom
  - MessageKit (~> 3.0)
  - Moya/RxSwift
  - Plaid (~> 1.1.24)
  - ReachabilitySwift
  - SDWebImage
  - SDWebImage/GIF
  - SwiftLint
  - SwiftyJSON
  - TouchVisualizer
  - XLPagerTabStrip (~> 9.0)

SPEC REPOS:
  trunk:
    - Alamofire
    - Branch
    - Charts
    - Crashlytics
    - Eureka
    - Fabric
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseInstanceID
    - FLAnimatedImage
    - Fuzi
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleUtilities
    - InputBarAccessoryView
    - Instabug
    - Intercom
    - MessageKit
    - Moya
    - nanopb
    - Plaid
    - ReachabilitySwift
    - Result
    - RxSwift
    - SDWebImage
    - SwiftLint
    - SwiftyJSON
    - TouchVisualizer
    - XLPagerTabStrip

SPEC CHECKSUMS:
  Alamofire: 85e8a02c69d6020a0d734f6054870d7ecb75cf18
  Branch: 80c583d989d3d46a7ada15b6cc1881142c1720a1
  Charts: 74c9f256eaf0460c0c416522d1cf8c634ea6b286
  Crashlytics: 540b7e5f5da5a042647227a5e3ac51d85eed06df
  Eureka: 18a5076dcf0c41f9cd9748aa1c42f4d11434bdae
  Fabric: 706c8b8098fff96c33c0db69cbf81f9c551d0d74
  Firebase: 0219bb4782eb1406f1b9b0628a2e625484ce910d
  FirebaseAnalytics: f68b9f3f1241385129ae0a83b63627fc420c05e5
  FirebaseCore: 632e05cc5e1199d9147122c16d92305eb04c34bd
  FirebaseCoreDiagnostics: 511f4f3ed7d440bb69127e8b97c2bc8befae639e
  FirebaseCoreDiagnosticsInterop: e9b1b023157e3a2fc6418b5cb601e79b9af7b3a0
  FirebaseInstanceID: ebd2ea79ee38db0cb5f5167b17a0d387e1cc7b6e
  FLAnimatedImage: 4a0b56255d9b05f18b6dd7ee06871be5d3b89e31
  Fuzi: bcc5694488dd6e672e126cbf3c5471d7a79506d1
  GoogleAppMeasurement: db118eb61a97dd8c4f7014e368d3c335cbbcf80a
  GoogleDataTransport: 8e9b210c97d55fbff306cc5468ff91b9cb32dcf5
  GoogleDataTransportCCTSupport: 202d7cdf9c4a7d81a2bb7f7e7e1ba6faa421b1f2
  GoogleUtilities: 29bd0d8f850efbd28cff6d99e8b7da1f8d236bcf
  InputBarAccessoryView: 2b937602598e2fab3149f37f51dd7ad795653812
  Instabug: 4a4a01935b26022b485bcb2b7c0b7baebbf99303
  Intercom: 04aa591f0bd35f0405a7d9d5dac39ba91affee27
  MessageKit: e892a9ca49ebe6d82684d3a93ad84021fa23e2c6
  Moya: f4a4b80ff2f8a4ffc208dfb31cd91636622fee6e
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  Plaid: 9273f4d1539a3af29b2b7b4a5aef17c293e32896
  ReachabilitySwift: 985039c6f7b23a1da463388634119492ff86c825
  Result: bd966fac789cc6c1563440b348ab2598cc24d5c7
  RxSwift: f172070dfd1a93d70a9ab97a5a01166206e1c575
  SDWebImage: c10d14a8883ebd89664f02a422006f66a85c0c5d
  SwiftLint: 4105f061f9812b214568b736dab580ab2c73a582
  SwiftyJSON: 36413e04c44ee145039d332b4f4e2d3e8d6c4db7
  TouchVisualizer: b97b1efb0f25d1408bb4557e6f493eae454425e7
  XLPagerTabStrip: 61c57fd61f611ee5f01ff1495ad6fbee8bf496c5

PODFILE CHECKSUM: 1d0f7322d43044ef6e6223dea15f49cdb54625a0

COCOAPODS: 1.8.4
```
Crash reported by Crashlytics:

Crashed: com.apple.main-thread
SIGSEGV 0x00000000004e0c4c

```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1bdab8fc0 objc_msgSend + 32
1  Foundation                     0x1be15e64c _encodeObject + 212
2  Foundation                     0x1be0ddaec -[NSOrderedSet(NSOrderedSet) encodeWithCoder:] + 268
3  Foundation                     0x1be15ea34 _encodeObject + 1212
4  Olivia                         0x101212e30 -[GDTCORStorage encodeWithCoder:] + 313 (GDTCORStorage.m:313)
5  Foundation                     0x1be15ea34 _encodeObject + 1212
6  Foundation                     0x1be071e8c +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 116
7  Olivia                         0x101212a14 -[GDTCORStorage appWillTerminate:] + 262 (GDTCORStorage.m:262)
8  Olivia                         0x10120fe38 -[GDTCORLifecycle applicationWillTerminate:] + 109 (GDTCORLifecycle.m:109)
9  Foundation                     0x1be16f06c __57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2 + 28
10 CoreFoundation                 0x1bdcfc99c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
11 CoreFoundation                 0x1bdcfc9ec ___CFXRegistrationPost1_block_invoke + 68
12 CoreFoundation                 0x1bdcfbce4 _CFXRegistrationPost1 + 396
13 CoreFoundation                 0x1bdcfb97c ___CFXNotificationPost_block_invoke + 108
14 CoreFoundation                 0x1bdc74910 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1424
15 CoreFoundation                 0x1bdcfb2ac _CFXNotificationPost + 1268
16 Foundation                     0x1be05dbfc -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
17 Olivia                         0x101210434 -[GDTCORApplication iOSApplicationWillTerminate:] + 190 (GDTCORPlatform.m:190)
18 Foundation                     0x1be16f06c __57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2 + 28
19 CoreFoundation                 0x1bdcfc99c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
20 CoreFoundation                 0x1bdcfc9ec ___CFXRegistrationPost1_block_invoke + 68
21 CoreFoundation                 0x1bdcfbce4 _CFXRegistrationPost1 + 396
22 CoreFoundation                 0x1bdcfb97c ___CFXNotificationPost_block_invoke + 108
23 CoreFoundation                 0x1bdc74910 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1424
24 CoreFoundation                 0x1bdcfb2ac _CFXNotificationPost + 1268
25 Foundation                     0x1be05dbfc -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
26 UIKitCore                      0x1c1e980d8 -[UIApplication _terminateWithStatus:] + 304
27 UIKitCore                      0x1c162983c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
28 UIKitCore                      0x1c1629498 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220
29 UIKitCore                      0x1c1e8e2b4 -[UIApplication workspaceShouldExit:withTransitionContext:] + 216
30 FrontBoardServices             0x1c2f7f98c -[FBSUIApplicationWorkspaceShim workspaceShouldExit:withTransitionContext:] + 88
31 FrontBoardServices             0x1c2fad264 __83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_invoke_2 + 80
32 FrontBoardServices             0x1c2f91ef4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
33 FrontBoardServices             0x1c2fad1f0 __83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_invoke + 140
34 libdispatch.dylib              0x1bda49fd8 _dispatch_client_callout + 20
35 libdispatch.dylib              0x1bda4cd1c _dispatch_block_invoke_direct + 264
36 FrontBoardServices             0x1c2fd4254 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
37 FrontBoardServices             0x1c2fd3f00 -[FBSSerialQueue _queue_performNextIfPossible] + 432
38 FrontBoardServices             0x1c2fd446c -[FBSSerialQueue _performNextFromRunLoopSource] + 32
39 CoreFoundation                 0x1bdd20108 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
40 CoreFoundation                 0x1bdd2005c __CFRunLoopDoSource0 + 84
41 CoreFoundation                 0x1bdd1f7c8 __CFRunLoopDoSources0 + 184
42 CoreFoundation                 0x1bdd1a694 __CFRunLoopRun + 1068
43 CoreFoundation                 0x1bdd19f40 CFRunLoopRunSpecific + 480
44 GraphicsServices               0x1c7f97534 GSEventRunModal + 108
45 UIKitCore                      0x1c1e92a60 UIApplicationMain + 1940
46 Olivia                         0x100ef867c main + 20 (AppDelegate.swift:20)
47 libdyld.dylib                  0x1bdb98e18 start + 4
```

**Comment by rizafran** [comment] 2020-01-16 13:13
Seems related to this issue #4546.

**Comment by mikehaney24** [comment] 2020-01-16 19:37
Duplicate of #4546

**Closed by mikehaney24** 2020-01-16 19:37 UTC
Labels: GoogleDataTransport
