### ISSUE TITLE
“FirebaseAnalytics.framework” couldn’t be copied to “debug-iphoneos” 

### ISSUE THREAD

**Issue by geeklingo** [firebase/firebase-ios-sdk#9031] opened 2021-11-30 12:12 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: 8.9.1
  * Installation method:  Swift Package Manager
  * Firebase Component: Analytics, Crashlytics, Performance
  * Target platform(s): iOS 

### [REQUIRED] Step 2: Describe the problem
When building in pipeline via CLI, I am getting errors with the Firebase components only.

```
▸ Compiling GULNSData+zlib.m
❌  error: “FirebaseAnalytics.framework” couldn’t be copied to “debug-iphoneos” because an item with the same name already exists.
[16:36:52]: Exit status: 65
[16:36:52]: 
[16:36:52]: Maybe the error shown is caused by using the wrong version of Xcode
[16:36:52]: Found multiple versions of Xcode in '/Applications/'
[16:36:52]: Make sure you selected the right version for your project
[16:36:52]: This build process was executed using '/Applications/Xcode-13.1.app'
[16:36:52]: If you want to update your Xcode path, either
```

and

```
▸ Compiling GULNSData+zlib.m
❌  error: “GoogleAppMeasurement.framework” couldn’t be copied to “release-iphoneos” because an item with the same name already exists.
ERROR [2021-11-30 21:58:33.49]: Exit status: 65
```

#### Steps to reproduce:
Run it in a code pipeline via CLI (e.g. Fastlane)

**Comment by paulb777** [comment] 2021-11-30 15:34
This problem looks like a corrupt Xcode state. Does clearing Derived Data or resetting the Swift package cache help?

Another option is to search Apple forums for similar issues with other binary Swift packages.

Otherwise, please share a reproducible example.

**Comment by geeklingo** [comment] 2021-12-01 10:48
Yeah derived data is cleared after each pipeline is run and the package is downloaded fresh each time as well.

**Comment by geeklingo** [comment] 2021-12-10 02:10
Hi, what additional information can i provide to assist?

**Comment by paulb777** [comment] 2021-12-10 15:36
Hi. We would need instructions for how to reproduce outside of Fastlane to help investigate.

**Comment by geeklingo** [comment] 2021-12-13 01:46
Yeah, that's part of the problem. I can't replicate this issue outside of Fastlane...ever.

But when it's compiled in CI pipeline, it's failing more often than not.

<img width="335" alt="CleanShot 2021-12-13 at 11 44 38@2x" src="https://user-images.githubusercontent.com/36504208/145739919-603b9c92-8e40-47a1-a287-5e52d9017561.png">

<img width="1161" alt="CleanShot 2021-12-13 at 11 45 44@2x" src="https://user-images.githubusercontent.com/36504208/145739989-d8f05e80-104c-4bb2-83c3-3e4cc549e811.png">

**Comment by paulb777** [comment] 2021-12-13 15:56
This is old, but maybe some ideas at https://stackoverflow.com/questions/20301434/an-item-with-the-same-name-already-exists-in-xcode

**Comment by geeklingo** [comment] 2021-12-15 11:54
Unfortunately not. I just created a fresh project using XCode 13.2, copied my source code over, pushed to GitLab and same result.

The only SPM installed is the Firebase one.

**Comment by a-25** [comment] 2022-01-06 15:36
Hello, @geeklingo. Could you post your Fastfile or a lane that builds at least? It could answer the question why is this issue not reproducible outside fastlane.

**Comment by geeklingo** [comment] 2022-01-07 02:35
> Hello, @geeklingo. Could you post your Fastfile or a lane that builds at least? It could answer the question why is this issue not reproducible outside fastlane.

Hi, i have a issue logged over at Fastlane as well as not sure which side of the fence the resolution falls. https://github.com/fastlane/fastlane/issues/19645 has all the fastlane config info.

**Comment by morganchen12** [comment] 2022-03-10 22:14
Based on discussion in the other issue, looks like it's been resolved (though the root cause was never found). I'll close this issue as well, but if new information comes up feel free to file a new issue.

**Closed by morganchen12** 2022-03-10 22:14 UTC
Labels: api: analytics, Swift Package Manager
