### ISSUE TITLE
Could not reach Cloud Firestore backend. 

### ISSUE THREAD

**Issue by ZhaoTianze** [firebase/firebase-ios-sdk#4455] opened 2019-12-07 07:41 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: Auth&Firestore
  * Component version: 1.8.0

### [REQUIRED] Step 3: Describe the problem

Hello, I use the Firebase Auth & Firestore in my game to save user`s data.  Everything is working well on Android. But I  have some problems with iOS SDK:

After I login successfully, I would like to get a doc on Firestore. The path is `/tapcolor-users/{uid}`. If the doc does not exist, I will create a new doc. It is working fine on Android. But when I try to get same doc on iOS, I get error. The log is:

```
6.13.0 - [Firebase/Firestore][I-FST000001] Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

2019-12-07 11:30:16.973176+0800 number[17020:7536320] getDoc failed! error = Failed to get document because the client is offline.
```
or

`
Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: failed to connect to all addresses
`

I have checked my Internet connection, it is fine. Because I can login successfully.

Any advise for this situation? Thanks.

#### Relevant Code:

Test Code on iOS:
```
- (void)DoTest:(GIDGoogleUser *)googleUser
{
    GIDAuthentication * authentication = googleUser.authentication;
    FIRAuthCredential * credential = [FIRGoogleAuthProvider credentialWithIDToken:authentication.idToken
                                     accessToken:authentication.accessToken];
    [[FIRAuth auth] signInWithCredential:credential completion:^(FIRAuthDataResult * authResult, NSError * firError) {
        if(firError == nil)
        {
            id<FIRUserInfo> firUserInfo = authResult.user.providerData[0];
            NSString * userID = firUserInfo.uid;
            NSString * userName = firUserInfo.displayName;
            
            NSLog(@"Google Login Success! userID = %@, userName = %@", userID, userName);
            
            [self GetDoc:userID];
        }
        else
        {
            NSLog(@"Google Login Failed! (firebase) firError = %@", firError.localizedDescription);
        }
    }];
}

- (void)GetDoc:(NSString *)docName
{
    NSString * collectionName = @"tapcolor-users";
    
    FIRDocumentReference * docRef = [[[FIRFirestore firestore] collectionWithPath:collectionName] documentWithPath:docName];
    [docRef getDocumentWithCompletion:^(FIRDocumentSnapshot * snapshot, NSError * error) {
        if(error != nil)
        {
            NSLog(@"getDoc failed! error = %@", error.localizedDescription);
        }
        else
        {
            NSLog(@"getDoc success!");
        }
    }];
}
```

**Comment by rizafran** [comment] 2019-12-09 13:59
Hi @ZhaoTianze , thanks for reporting this. The error message you encountered usually appears when there is no connection from your device to your database, possibly due to network issues on your end. It also means that there is something that is not allowing the client application to reach the Firestore backend. With this, could you try the following:
1. Try to execute the app under different networks and using different devices, just to see if you are able to determine a pattern.
2. Are you under a proxy network? where are you located? Some carriers could block the connection with Firebase.
3. Try to disable antivirus in your device (if any). We had some reports where this kind of software affects the connectivity with Firebase.
4. Check if the [API key restriction is enabled](https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions) in your Cloud Console (similar to this [issue](https://github.com/firebase/firebase-ios-sdk/issues/3763#issuecomment-530963526)).

**Comment by thebrianchen** [comment] 2019-12-09 18:16
@ZhaoTianze  Thanks for your report! If you still have the logs from the time the error was reproducible, could you please post them here? That would greatly help us in debugging your issue.

**Comment by ZhaoTianze** [comment] 2019-12-10 07:08
@thebrianchen 
```
2019-12-10 10:34:36.618203+0800 number[19316:7924731] 6.13.0 - [Firebase/Firestore][I-FST000001] Initializing. Current user: n6tPWsAwDIPj3bTeXxNGeXaEilk1
2019-12-10 10:34:36.648698+0800 number[19316:7924731] 6.13.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Start LevelDB: 0 changes (0 bytes):>
2019-12-10 10:34:36.652089+0800 number[19316:7923729] 6.13.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Start MutationQueue: 0 changes (0 bytes):>
2019-12-10 10:34:36.652140+0800 number[19316:7923729] 6.13.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction NextMutationBatchAfterBatchID: 0 changes (0 bytes):>
2019-12-10 10:34:36.652248+0800 number[19316:7923729] 6.13.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Allocate query: 0 changes (0 bytes):>
2019-12-10 10:34:36.652340+0800 number[19316:7923729] 6.13.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction ExecuteQuery: 0 changes (0 bytes):>
0 number[19316:7923729] 6.13.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction RemoteDocumentKeysForTarget: 0 changes (0 bytes):>
2019-12-10 10:34:36.652526+0800 number[19316:7923729] 6.13.0 - [Firebase/Firestore][I-FST000001] WatchStream (10a867d58) start
2019-12-10 10:34:36.652801+0800 number[19316:7923729] 6.13.0 - [Firebase/Firestore][I-FST000001] Creating Firestore stub.
2019-12-10 10:34:36.859737+0800 number[19316:7923606] 6.13.0 - [Firebase/Firestore][I-FST000001] roots.pem found in bundle org.cocoapods.gRPCCertificates-Cpp (in parent com.pixel.art.coloring.by.number)
2019-12-10 10:34:36.864613+0800 number[19316:7923606] 6.13.0 - [Firebase/Firestore][I-FST000001] WatchStream (10a867d58) watch: <ListenRequest 0x16ff665f8>: {
2019-12-10 10:34:36.972037+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] GrpcStream('122a284b0'): operation of type 2 failed
2019-12-10 10:34:36.972543+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] GrpcStream('122a284b0'): finishing the underlying call
2019-12-10 10:34:36.972575+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] GrpcStream('122a284b0'): fast finishing 1 completion(s)
2019-12-10 10:34:36.972606+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] GrpcStream('122a284b0'): finishing and notifying observers
2019-12-10 10:34:36.972667+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] GrpcStream('122a284b0'): shutting down; completions: 0, is finished: true
00 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] GrpcStream('122a284b0'): fast finishing 0 completion(s)
2019-12-10 10:34:36.972808+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] WatchStream (10a867d58) Stream error: 'Unavailable: failed to connect to all addresses'
2019-12-10 10:34:36.972848+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] GrpcStream('122a284b0'): destroying stream
 - [Firebase/Firestore][I-FST000001] Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: failed to connect to all addresses
2019-12-10 10:34:36.973034+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] WatchStream (10a867d58) backoff
3138+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] WatchStream (10a867d58) start
2019-12-10 10:34:36.973174+0800 number[19316:7923921] 6.13.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Release query: 2 changes (110 bytes):
```

**Comment by ZhaoTianze** [comment] 2019-12-10 11:13
@rizafran 
Thanks for reply.

1. We tested the app on different networks(wifi,4G) and different device (iPhone X, iPhone 8).Now we try to test in different location office, hope it will be working.
2.Yes, we under a proxy nextwork. Because we are in China, if we want to conncet to google, we need proxy. But it is working well on Android device, and it doesn`t work on iOS. The insteresting thing is that we can success at login, but failed to firestore.
3.No antivirus in my device.
4.I have checked, no restriction is enabled.

**Comment by wilhuff** [comment] 2019-12-10 21:10
@ZhaoTianze Based on your logs this appears to be a duplicate of #1060.

Note that Auth and Firestore use different mechanisms for making network connections. Auth makes comparatively simple REST-based calls and this ends up honoring the system proxy configuration. Firestore uses a more complicated streaming RPC transport built with gRPC and this does not honor the system proxy settings. The advice given in https://github.com/firebase/firebase-ios-sdk/issues/1060#issuecomment-380319526 should hel p you resolve this.

**Closed by wilhuff** 2019-12-10 21:10 UTC
Labels: api: firestore, needs-attention

**Comment by ZhaoTianze** [comment] 2019-12-11 03:42
@wilhuff Thanks, we tested on different proxy. Finally, one of them is working!
