### ISSUE TITLE
Firestore Assertion Failed in void firebase::firestore::core, etc (signal8: SIGABRT)

### ISSUE THREAD

**Issue by MathewGarcia** [firebase/firebase-ios-sdk#4865] opened 2020-02-08 23:16 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __11___
  * Firebase SDK version: __6.16___
  * Firebase Component: Auth, core, database, Firebase/Firestore,storeage(Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: Most latest on all (just updated)
  * Installation method: `[CocoaPods] | Carthage | Zip file` (select one)

#### Steps to reproduce:
I have documents in the following order - collection("users")document(currentusersid)- with the info of email and name. 
I made a function called get name that is supposed to search firestore for the sessionid that was saved and retrieve the name. To then paste (hello, "mat/john/etc") Sometimes it works. Sometimes it doesnt and I get this error:
 *** Assertion failure in void firebase::firestore::core::FirestoreClient::Initialize(const firebase::firestore::auth::User &, const firebase::firestore::api::Settings &)(), *FILE NAME* 

Theres more errors too but I read online to try and debug and to create and exception break point because xcode is throwing an error at the crash rather than whats causing the crash. Tried that and it stops there. Which sounds like theres an initializations problem with firestore?

#### Relevant Code:

```
 func getName(){
       
        let userid = session.session?.uid ?? ""
        
              let docRef = db.collection("users").document(userid)
              
              
              docRef.getDocument{ (document, err) in
                if let document = document, document.exists{
                      let displayname = document.get("name")
                    
                    self.displayName = displayname as? String
                      
                                  }
                  else {
                      print("document does not exist\(String(describing: err))")
                  }
                  
              }
        
    }
   

                Text("Hello \(self.displayName ?? "")").foregroundColor(Color.black).onAppear(perform:self.getName).position(x:108,y:10)
```
edit: the program works completely fine once i delete that function, also, the preview works sometimes too. Sometimes doesnt,.

**Comment by wilhuff** [comment] 2020-02-08 23:25
Please include the complete error message, including the stack trace, and any other messages nearby. Without them we can't really help.

**Comment by MathewGarcia** [comment] 2020-02-08 23:42
`*** Assertion failure in void firebase::firestore::core::FirestoreClient::Initialize(const firebase::firestore::auth::User &, const firebase::firestore::api::Settings &)(), /Users/mathewgarcia/Library/Autosave Information/Beats/Beats/BeatsCloud/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/core/firestore_client.cc:168
2020-02-08 18:41:26.020783-0500 BeatsCloud[57831:1513028] [General] An uncaught exception was raised
2020-02-08 18:41:26.020861-0500 BeatsCloud[57831:1513028] [General] FIRESTORE INTERNAL ASSERTION FAILED: Failed to open DB: Internal: Failed to open LevelDB database at /Users/mathewgarcia/Library/Application Support/firestore/__FIRAPP_DEFAULT/beatswave-2c93c/main: LevelDB error: IO error: lock /Users/mathewgarcia/Library/Application Support/firestore/__FIRAPP_DEFAULT/beatswave-2c93c/main/LOCK: Resource temporarily unavailable (expected created.ok())
2020-02-08 18:41:26.020970-0500 BeatsCloud[57831:1513028] [General] (
	0   CoreFoundation                      0x00007fff2c5b38ab __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6286d805 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2c5dcd10 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff2ed13af7 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   BeatsCloud                          0x00000001001dcf84 _ZN8firebase9firestore4util16ObjcThrowHandlerENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 356
	5   BeatsCloud                          0x00000001001dc5a3 _ZN8firebase9firestore4util5ThrowENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 67
	6   BeatsCloud                          0x000000010033874d _ZN8firebase9firestore4util8internal13FailAssertionEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 45
	7   BeatsCloud                          0x000000010033880a _ZN8firebase9firestore4util8internal13FailAssertionEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEES4_ + 186
	8   BeatsCloud                          0x000000010026411c _ZN8firebase9firestore4core15FirestoreClient10InitializeERKNS0_4auth4UserERKNS0_3api8SettingsE + 556
	9   BeatsCloud                          0x000000010027143c _ZZZN8firebase9firestore4core15FirestoreClient6CreateERKNS1_12DatabaseInfoERKNS0_3api8SettingsENSt3__110shared_ptrINS0_4auth19CredentialsProviderEEENSB_INS0_4util8ExecutorEEENSB_INSF_10AsyncQueueEEEEN3$_2clENSC_4UserEENKUlvE_clEv + 60
	10  BeatsCloud                          0x00000001002713dd _ZNSt3__1L8__invokeIRZZN8firebase9firestore4core15FirestoreClient6CreateERKNS3_12DatabaseInfoERKNS2_3api8SettingsENS_10shared_ptrINS2_4auth19CredentialsProviderEEENSC_INS2_4util8ExecutorEEENSC_INSG_10AsyncQueueEEEEN3$_2clENSD_4UserEEUlvE_JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSP_DpOSQ_ + 29
	11  BeatsCloud                          0x000000010027138d _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZZN8firebase9firestore4core15FirestoreClient6CreateERKNS5_12DatabaseInfoERKNS4_3api8SettingsENS_10shared_ptrINS4_4auth19CredentialsProviderEEENSE_INS4_4util8ExecutorEEENSE_INSI_10AsyncQueueEEEEN3$_2clENSF_4UserEEUlvE_EEEvDpOT_ + 29
	12  BeatsCloud                          0x000000010027135d _ZNSt3__110__function12__alloc_funcIZZN8firebase9firestore4core15FirestoreClient6CreateERKNS4_12DatabaseInfoERKNS3_3api8SettingsENS_10shared_ptrINS3_4auth19CredentialsProviderEEENSD_INS3_4util8ExecutorEEENSD_INSH_10AsyncQueueEEEEN3$_2clENSE_4UserEEUlvE_NS_9allocatorISO_EEFvvEEclEv + 29
	13  BeatsCloud                          0x000000010026ff29 _ZNSt3__110__function6__funcIZZN8firebase9firestore4core15FirestoreClient6CreateERKNS4_12DatabaseInfoERKNS3_3api8SettingsENS_10shared_ptrINS3_4auth19CredentialsProviderEEENSD_INS3_4util8ExecutorEEENSD_INSH_10AsyncQueueEEEEN3$_2clENSE_4UserEEUlvE_NS_9allocatorISO_EEFvvEEclEv + 25
	14  BeatsCloud                          0x0000000100268975 _ZNKSt3__110__function12__value_funcIFvvEEclEv + 53
	15  BeatsCloud                          0x00000001002688e5 _ZNKSt3__18functionIFvvEEclEv + 21
	16  BeatsCloud                          0x0000000100157dac _ZN8firebase9firestore4util10AsyncQueue15ExecuteBlockingERKNSt3__18functionIFvvEEE + 188
	17  BeatsCloud                          0x000000010015d451 _ZZN8firebase9firestore4util10AsyncQueue4WrapERKNSt3__18functionIFvvEEEENK3$_0clEv + 49
	18  BeatsCloud                          0x000000010015d3fd _ZNSt3__1L8__invokeIRZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSC_DpOSD_ + 29
	19  BeatsCloud                          0x000000010015d3ad _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0EEEvDpOT_ + 29
	20  BeatsCloud                          0x000000010015d37d _ZNSt3__110__function12__alloc_funcIZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0NS_9allocatorISB_EES7_EclEv + 29
	21  BeatsCloud                          0x000000010015bfc9 _ZNSt3__110__function6__funcIZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0NS_9allocatorISB_EES7_EclEv + 25
	22  BeatsCloud                          0x0000000100268975 _ZNKSt3__110__function12__value_funcIFvvEEclEv + 53
	23  BeatsCloud                          0x00000001002688e5 _ZNKSt3__18functionIFvvEEclEv + 21
	24  BeatsCloud                          0x00000001001df041 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEENK3$_0clEPv + 33
	25  BeatsCloud                          0x00000001001df015 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEEN3$_08__invokeEPv + 21
	26  libdispatch.dylib                   0x000000010382878f _dispatch_client_callout + 8
	27  libdispatch.dylib                   0x000000010382fd31 _dispatch_lane_serial_drain + 777
	28  libdispatch.dylib                   0x0000000103830ae8 _dispatch_lane_invoke + 438
	29  libdispatch.dylib                   0x000000010383df2e _dispatch_workloop_worker_thread + 681
	30  libsystem_pthread.dylib             0x00000001038b402c _pthread_wqthread + 290
	31  libsystem_pthread.dylib             0x00000001038b3157 start_wqthread + 15
)
2020-02-08 18:41:26.022255-0500 BeatsCloud[57831:1513028] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Failed to open DB: Internal: Failed to open LevelDB database at /Users/mathewgarcia/Library/Application Support/firestore/__FIRAPP_DEFAULT/beatswave-2c93c/main: LevelDB error: IO error: lock /Users/mathewgarcia/Library/Application Support/firestore/__FIRAPP_DEFAULT/beatswave-2c93c/main/LOCK: Resource temporarily unavailable (expected created.ok())'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2c5b38ab __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6286d805 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2c5dcd10 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff2ed13af7 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   BeatsCloud                          0x00000001001dcf84 _ZN8firebase9firestore4util16ObjcThrowHandlerENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 356
	5   BeatsCloud                          0x00000001001dc5a3 _ZN8firebase9firestore4util5ThrowENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 67
	6   BeatsCloud                          0x000000010033874d _ZN8firebase9firestore4util8internal13FailAssertionEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 45
	7   BeatsCloud                          0x000000010033880a _ZN8firebase9firestore4util8internal13FailAssertionEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEES4_ + 186
	8   BeatsCloud                          0x000000010026411c _ZN8firebase9firestore4core15FirestoreClient10InitializeERKNS0_4auth4UserERKNS0_3api8SettingsE + 556
	9   BeatsCloud                          0x000000010027143c _ZZZN8firebase9firestore4core15FirestoreClient6CreateERKNS1_12DatabaseInfoERKNS0_3api8SettingsENSt3__110shared_ptrINS0_4auth19CredentialsProviderEEENSB_INS0_4util8ExecutorEEENSB_INSF_10AsyncQueueEEEEN3$_2clENSC_4UserEENKUlvE_clEv + 60
	10  BeatsCloud                          0x00000001002713dd _ZNSt3__1L8__invokeIRZZN8firebase9firestore4core15FirestoreClient6CreateERKNS3_12DatabaseInfoERKNS2_3api8SettingsENS_10shared_ptrINS2_4auth19CredentialsProviderEEENSC_INS2_4util8ExecutorEEENSC_INSG_10AsyncQueueEEEEN3$_2clENSD_4UserEEUlvE_JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSP_DpOSQ_ + 29
	11  BeatsCloud                          0x000000010027138d _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZZN8firebase9firestore4core15FirestoreClient6CreateERKNS5_12DatabaseInfoERKNS4_3api8SettingsENS_10shared_ptrINS4_4auth19CredentialsProviderEEENSE_INS4_4util8ExecutorEEENSE_INSI_10AsyncQueueEEEEN3$_2clENSF_4UserEEUlvE_EEEvDpOT_ + 29
	12  BeatsCloud                          0x000000010027135d _ZNSt3__110__function12__alloc_funcIZZN8firebase9firestore4core15FirestoreClient6CreateERKNS4_12DatabaseInfoERKNS3_3api8SettingsENS_10shared_ptrINS3_4auth19CredentialsProviderEEENSD_INS3_4util8ExecutorEEENSD_INSH_10AsyncQueueEEEEN3$_2clENSE_4UserEEUlvE_NS_9allocatorISO_EEFvvEEclEv + 29
	13  BeatsCloud                          0x000000010026ff29 _ZNSt3__110__function6__funcIZZN8firebase9firestore4core15FirestoreClient6CreateERKNS4_12DatabaseInfoERKNS3_3api8SettingsENS_10shared_ptrINS3_4auth19CredentialsProviderEEENSD_INS3_4util8ExecutorEEENSD_INSH_10AsyncQueueEEEEN3$_2clENSE_4UserEEUlvE_NS_9allocatorISO_EEFvvEEclEv + 25
	14  BeatsCloud                          0x0000000100268975 _ZNKSt3__110__function12__value_funcIFvvEEclEv + 53
	15  BeatsCloud                          0x00000001002688e5 _ZNKSt3__18functionIFvvEEclEv + 21
	16  BeatsCloud                          0x0000000100157dac _ZN8firebase9firestore4util10AsyncQueue15ExecuteBlockingERKNSt3__18functionIFvvEEE + 188
	17  BeatsCloud                          0x000000010015d451 _ZZN8firebase9firestore4util10AsyncQueue4WrapERKNSt3__18functionIFvvEEEENK3$_0clEv + 49
	18  BeatsCloud                          0x000000010015d3fd _ZNSt3__1L8__invokeIRZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSC_DpOSD_ + 29
	19  BeatsCloud                          0x000000010015d3ad _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0EEEvDpOT_ + 29
	20  BeatsCloud                          0x000000010015d37d _ZNSt3__110__function12__alloc_funcIZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0NS_9allocatorISB_EES7_EclEv + 29
	21  BeatsCloud                          0x000000010015bfc9 _ZNSt3__110__function6__funcIZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0NS_9allocatorISB_EES7_EclEv + 25
	22  BeatsCloud                          0x0000000100268975 _ZNKSt3__110__function12__value_funcIFvvEEclEv + 53
	23  BeatsCloud                          0x00000001002688e5 _ZNKSt3__18functionIFvvEEclEv + 21
	24  BeatsCloud                          0x00000001001df041 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEENK3$_0clEPv + 33
	25  BeatsCloud                          0x00000001001df015 _ZZN8firebase9firestore4util8internal13DispatchAsyncEPU28objcproto17OS_dispatch_queue8NSObjectONSt3__18functionIFvvEEEEN3$_08__invokeEPv + 21
	26  libdispatch.dylib                   0x000000010382878f _dispatch_client_callout + 8
	27  libdispatch.dylib                   0x000000010382fd31 _dispatch_lane_serial_drain + 777
	28  libdispatch.dylib                   0x0000000103830ae8 _dispatch_lane_invoke + 438
	29  libdispatch.dylib                   0x000000010383df2e _dispatch_workloop_worker_thread + 681
	30  libsystem_pthread.dylib             0x00000001038b402c _pthread_wqthread + 290
	31  libsystem_pthread.dylib             0x00000001038b3157 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

sure thing @wilhuff !

**Comment by wilhuff** [comment] 2020-02-09 00:47
The interesting part of that error is this:

> `Failed to open DB: Internal: Failed to open LevelDB database at <directory>: LevelDB error: IO error: lock <directory>/LOCK: Resource temporarily unavailable (expected created.ok())'`

"Resource temporarily unavailable" corresponds to `EDEADLK` (errno 11) and that indicates that somehow you've got multiple locks held. This really shouldn't happen.

The code you've listed isn't really doing anything that could cause that. There must be some interaction with something else in your system that's causing this to fail. 

Questions:
  * Are you using more than one Firebase App and using Firestore with them?
  * Does this happen reliably?
  * Could you share your project (privately) so that I could reproduce it? (For example, if you're not open source, you could zip up your checked-out project state and share it via Google Drive or similar).

**Comment by MathewGarcia** [comment] 2020-02-09 00:57
@wilhuff sure thing! i just uploaded it to google drive, anyway you'd like for me to send it to you?

**Comment by wilhuff** [comment] 2020-02-09 01:05
I'm definitely interested in understanding how this is happening, even if you're now fixed. This really shouldn't be happening.

You can share with mcg@google.com. Please describe what steps you take to see the problem--even if the failure only happened occasionally.

**Comment by MathewGarcia** [comment] 2020-02-09 01:14
@wilhuff i just sent it! and there are no exact steps, i pretty much just put that code in 'getName()' and it basically works when it wants to lol. Hopefully it'll do the same for you. I thought it was because the name is coming back as nil but its not. So I tried using other steps. btw, this is on Mac OS

**Comment by wilhuff** [comment] 2020-02-09 01:29
You sent over just the `contents.xcworkspacedata` file. I meant zip up your entire project directory, including the source code and whatever it takes to build it.

**Comment by MathewGarcia** [comment] 2020-02-09 19:45
@wilhuff sorry i had left my computer! but let me zip and send it over! 
-the problem still persists though. Makes no sense lol.

**Comment by MathewGarcia** [comment] 2020-02-09 19:49
@wilhuff sent!

**Comment by wilhuff** [comment] 2020-02-10 16:41
Update: I managed to get the project to build but can't run it yet because I don't have a machine running macOS 10.15 yet. Next steps are to locate one :-).

**Comment by morganchen12** [comment] 2020-02-10 17:42
@wilhuff I have a laptop running Catalina if you need help debugging. I am worried about this, though:

> edit 2: now it works fine after i deleted those files in firestore too lol... at a loss

Seems like this may not be reproducible without the right disk cache contents.

**Comment by MathewGarcia** [comment] 2020-02-10 18:54
@morganchen12 Hey, im confused though i thought my function would read the document directly through firestore? am i using the wrong function call?

**Comment by morganchen12** [comment] 2020-02-10 18:58
You're not using the wrong function call, but `getDocument` will still check the cache. The crash is happening because Firestore is unexpectedly not allowed to access the cache when it should be (I think). @wilhuff can explain in more detail.

**Comment by MathewGarcia** [comment] 2020-02-10 19:01
@morganchen12 okay i see, well thats at least a breather. Is there a way i can force it to be allowed or maybe skip getDocument from checking the cache?

**Comment by morganchen12** [comment] 2020-02-10 19:21
The preview crashing is likely an Apple bug (see #4772). It shouldn't affect your app at runtime.

You can force a fetch from the server using [`getDocument(source:completion:)`](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/DocumentReference#/c:objc(cs)FIRDocumentReference(im)getDocumentWithSource:completion:).

**Comment by MathewGarcia** [comment] 2020-02-10 20:15
@morganchen12 okay so i added a source:.cache and so far it worked so im seeing if it stays consistent. I only tried once so lets hope for the best or an answer eventually ! lol

**Comment by morganchen12** [comment] 2020-02-11 21:45
I ran the app you shared with @wilhuff a couple times and wasn't able to reproduce the crash. Here's what I tried:

- Run the app
- Sign up with a test account (test@example.com, password: password)
- Log out and log in repeatedly

Do you have more detailed crash repro steps?

**Comment by MathewGarcia** [comment] 2020-02-11 23:31
@wilhuff dang, well thats unfortunate for me. Well i know it normally crashes when I login, then leave the account logged in, exit the program, the start the program up again. Itll try to gain the info in the docs and then crash. Would you like a video?

**Comment by morganchen12** [comment] 2020-02-12 03:12
I'll leave this issue open for a while in case it starts crashing again.

**Comment by MathewGarcia** [comment] 2020-02-12 16:20
@morganchen12 whoops, tagged your friend instead! Sorry haha, question though, would internet connection matter whether or not I connect to the document? I ask because when I got home on my network, I had no problem with the function, but when I was at work and using a hotspot I have from work, it had crashed. (not tested yet, but the question just crossed my mind)

**Comment by wilhuff** [comment] 2020-02-12 16:22
Firestore opens its local database before attempting to use the network so it's highly unlikely that differences in the network have anything to do with this particular failure.

**Comment by MathewGarcia** [comment] 2020-02-12 16:43
hmm, odd. Well, it crashed again and it only managed to crash on while  I was on my hotspot. Ill send you the video. Should I do that privately or ?

**Comment by morganchen12** [comment] 2020-02-12 19:49
I was able to repro this with the exact same stack trace by running two instances of the app at the same time. Network and other factors don't affect the crash.

What's happening in my setup is one instance of the app locks the db cache while the other instance tries to access it. Normally this isn't an issue on iOS because you can't run two instances of the same app, but on Mac you can do whatever you want.

Steps to repro:
- Run the app in Xcode.
- Under the Debug menu, click "Detach from BeatsCloud".
- Run the app again after detaching the debugger from the first instance.

@MathewGarcia can you check when you're troubleshooting this that only one instance of your app is running at a time?

**Comment by MathewGarcia** [comment] 2020-02-12 23:40
@morganchen12 ah i just checked my Activity monitor... Theres like at least 8 of them running in the background. I wonder why? I stopped the program already! Also sorry for the late reply. Work got a little hectic

**Comment by morganchen12** [comment] 2020-02-12 23:50
No problem. This behavior by Firestore is working as intended. Note that the default behavior of macOS is to not run multiple copies of the same process when a user clicks on your app twice, so this should generally not cause any issues. If you want to allow for multiple instances of Firestore running in multiple instances of your app at the same time, you need to use multiple Firebase apps so each Firestore instance references a different app.

I'll close this issue now, but please let us know if you have any other questions.

**Closed by morganchen12** 2020-02-12 23:50 UTC
Labels: Catalyst, api: firestore, needs-attention

**Comment by MathewGarcia** [comment] 2020-02-13 01:50
@morganchen12 okay perfect, as long as this doesnt happen during final product! Thank you. Glad we figured it out!

**Comment by anushkmittal** [comment] 2020-02-14 01:36
had exact same issue. killing the duplicate processes worked!
thanks :)
