### ISSUE TITLE
Combine Integration

### ISSUE THREAD

**Issue by Wildchild9** [firebase/firebase-ios-sdk#7130] opened 2020-12-08 20:30 UTC
### Feature Proposal

* Firebase Component: All

### Combine Integration Proposal
Currently, many functions associated with Firebase are asynchronous. Because of this, users are forced to make use of completion handlers for their asynchronous callbacks. Currently, Swift is under the process of introducing an entirely new way for users to interact with asynchronous code with the new keywords like `async` and `await`, but while [Swift's concurrency roadmap](https://forums.swift.org/t/swift-concurrency-roadmap/41611) is still underway, many users of asynchronous code make use asynchronous completion handlers by way of closures. This is extremely common throughout Firebase's iOS framework. This can result in hard-to-read code though when multiple operations have to happen concurrently, forming what is commonly referred to as the pyramid of death. One common way to get around this when writing asynchronous code is using frameworks like Combine. During WWDC 2019, Apple introduced a new framework called [Combine](https://developer.apple.com/documentation/combine). This framework simplifies asynchronous code like networking, key value observing, notifications and callbacks. 

Extensions to Firebase's iOS that work with Combine have the potential to clean up a lot of common Firebase code. For example, one such operation that integration with Combine can streamline is adding an observer to a key in a Firebase database. 

<details open>
<summary>Consider the following Combine extension to Firebase for this specific operation.</summary>
</br>

Firstly, a custom publisher and subscription are created for observing events in the database. 

```swift 
extension Firebase.Database {
    struct Publisher: Combine.Publisher {
        typealias Output = DataSnapshot
        typealias Failure = Never
        
        private var reference: DatabaseReference
        private var event: DataEventType
        
        init(for reference: DatabaseReference, on event: DataEventType) {
            self.reference = reference
            self.event = event
        }
        
        func receive<S>(subscriber: S) where S: Subscriber, Publisher.Failure == S.Failure, Publisher.Output == S.Input {
            let subcription = Subscription(subscriber: subscriber, reference: reference, event: event)
            subscriber.receive(subscription: subcription)
        }
    }
    
    final class Subscription<SubscriberType: Subscriber>: Combine.Subscription where SubscriberType.Input == DataSnapshot {
        
        private var reference: Firebase.DatabaseReference?
        private var handle: UInt?
        
        init(subscriber: SubscriberType, reference: Firebase.DatabaseReference, event: DataEventType) {
            self.reference = reference
            handle = reference.observe(event) { snapshot in
                _ = subscriber.receive(snapshot)
            }
        }
        
        func request(_ demand: Subscribers.Demand) {
            // We do nothing here as we only want to send events when they occur.
            // See, for more info: https://developer.apple.com/documentation/combine/subscribers/demand
        }
        
        func cancel() {
            if let handle = handle {
                reference?.removeObserver(withHandle: handle)
            }
            handle = nil
            reference = nil
        }
    }
}
```
As well, two extensions on `DatabaseReference` are created to make observing single events (replacing 
1. A function that returns `Future` instance containing the `DataSnapshot` for the observation of a single event. This extension aims to replace calls to the existing `observeSingleEvent(of:with:)` method.
2. A function that returns our new publisher type (`Database.Publisher`) for the continual observation of a given event. This extension aims to replace calls to the existing `observe(_:with:)` method.
```swift
extension DatabaseReference {
    func observer(for event: DataEventType) -> Database.Publisher {
        return Database.Publisher(for: self, on: event)
    }
    
    func observeSingleEvent(of event: DataEventType) -> Future<DataSnapshot, Never> {
        Future { promise in
            self.observeSingleEvent(of: event) { snapshot in
                promise(.success(snapshot))
            }
        }
    }
}
```

Using this publisher and the corresponding extensions, one can update values when they change in a database in a more streamlined fashion. For example, if one wanted to keep `firstName` and `lastName` properties up-to-date with the value of a key 'full_name', they would currently have to do something along the lines of the following:
```swift
let observerHandle = Database.database().reference().child("full_name").observe(.childAdded) { snapshot in
    guard let fullName = snapshot.value as? String else {
        return
    }
    let components = fullName.split(separator: " ")
    guard components.count == 2 else {
        return
    }
    let capitalizedComponents = components.map { $0.capitalized }
    let (firstName, lastName) = (capitalizedComponents[0], capitalizedComponents[1])
    self.firstName = firstName
    self.lastName = lastName
}
self.observerCancellers.append(observerHandle)
```

But with the addition of the Combine extension above, that code can be cleaned up to:
```swift
Database.database().reference().child("full_name").observer(for: .value)
    .compactMap { $0.value as? String }
    .map { $0.split(separator: " ") }
    .filter { $0.count == 2 }
    .map { $0.map { $0.capitalized } }
    .map { (firstName: $0[0], lastName: $0[1]) }
    .sink {
        self.firstName = $0.firstName
        self.lastName = $0.lastName
    }
    .store(in: &self.observerCancellers)
```

This is just a sample of what can be done when integrating Combine with Firebase. The example above can be cleaned up even further by throwing custom errors if the value of the 'full_name' key in the database does not exist, is not separated by a space, or contains more than one space. As well, while the non-Combine version of the code is not yet very unruly, in an instance where one has to initially read multiple values in order to create a structure with them, the non-Combine version requires the nesting of multiple completion handlers. The Combine code can solve this issue through the use of operations like `zip(_:_:)` to combine the results of multiple publishers.
</details>

Many more operations have the potential to be cleaned up by Combine integration. Some of these operations include evaluating cloud functions, user creation, reading data from Firebase storage, etc.

Combine integration can be implemented in compiler directives to ensure that the end user can indeed import Combine.
```swift
#if canImport(Combine)
    // Firebase Combine integration            
#endif
```
The majority of this integration can most likely be done through extensions to existing Firebase types. As well, the implementation of some custom Combine operations might also be useful to streamline common operations.

Combine integration has the potential to make Firebase more user-friendly by allowing for the introduction of more modern asynchronous program practices, streamlining common operations, and improving overall code readability. For all of these reasons, I think integration with Combine should be strongly considered as a new feature for Firebase.

**Comment by paulb777** [comment] 2020-12-09 16:14
@Wildchild9 Thanks for the request. We're making active progress on Combine and Firebase. See #6976, #7003, and #6397 

cc: @ryanwilson @peterfriese

**Comment by peterfriese** [comment] 2021-02-17 09:40
Thanks for filing this feature request, @Wildchild9! 

We're actively working on this - see the [project board](https://github.com/firebase/firebase-ios-sdk/projects/3).

If you'd like to contribute, check out the notes on the [tracking bug](https://github.com/firebase/firebase-ios-sdk/issues/7295#issue-785171675). We're working on Auth, Firestore, and Functions - but if you'd like to contribute by writing publishers (and tests) for any of the other Firebase products, we'd be thrilled!

Closing this as a duplicate of #7295

**Closed by peterfriese** 2021-02-17 09:40 UTC
Labels: duplicate, type: feature request
