### ISSUE TITLE
-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x281829f50'

### ISSUE THREAD

**Issue by kapilkiwi** [firebase/firebase-ios-sdk#8743] opened 2021-10-06 04:25 UTC
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x280772f40'
*** First throw call stack:
(0x19d81186c 0x1b282ac50 0x19d71895c 0x19d814438 0x19d816740 0x10a352ab0 0x10a351f78 0x10a3875a4 0x10a386e30 0x10c97bbcc 0x10c97d6c0 0x10c985588 0x10c9860c0 0x10c992644 0x1e92bd814 0x1e92c476c)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x280772f40'
terminating with uncaught exception of type NSException

**Comment by paulb777** [comment] 2021-10-06 13:45
This may be a duplicate of #7939. See the discussion there.

**Closed** 2021-10-19 01:03 UTC
Labels: needs-info, no-recent-activity, GoogleDataTransport
