### ISSUE TITLE
Apple Silicon M1 : GoogleUtilities/AppDelegateSwizzler App Delegate does not conform to UIApplicationDelegate protocol.

### ISSUE THREAD

**Issue by alelordelo** [firebase/firebase-ios-sdk#8051] opened 2021-05-07 15:44 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.5 (12E262)
  * Firebase SDK version: 7.9.1
  * Installation method: Swift Package Manager
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage

### [REQUIRED] Step 2: Describe the problem

App crashes when build on macOS M1 apple silicon:
GoogleUtilities/AppDelegateSwizzler App Delegate does not conform to UIApplicationDelegate protocol.

#### Steps to reproduce:

What happened? How can we make the problem occur?

When I build on:

A- iMac Pro 2017Big Sur 11.3 (20E232) Intel  targeting MacOS and Catalyst-> builds fine
B- MacBook Air 2020 Big Sur 11.3 (20E232) Apple Silicon M1 targeting MacOS and Catalyst--> crashes

2021-05-07 16:03:04.006884+0200 tStudio[10689:135171] 7.9.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001014] App Delegate does not conform to UIApplicationDelegate protocol.

2021-05-07 16:03:04.375423+0200 tStudio[10689:135177] -[__NSSingleEntryDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x600001cff720
2021-05-07 16:03:04.380104+0200 tStudio[10689:135177] [General] An uncaught exception was raised
2021-05-07 16:03:04.380171+0200 tStudio[10689:135177] [General] -[__NSSingleEntryDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x600001cff720
2021-05-07 16:03:04.380214+0200 tStudio[10689:135177] [General] (
	0   CoreFoundation                      0x0000000192f4bdb8 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000192c750a8 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000192fdcba0 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x0000000192ead1e4 ___forwarding___ + 1444
	4   CoreFoundation                      0x0000000192eacb80 _CF_forwarding_prep_0 + 96
	5   tStudio                             0x000000010119cb98 __50-[GULHeartbeatDateStorage setHearbeatDate:forTag:]_block_invoke + 152
	6   Foundation                          0x0000000193d09bf0 -[NSFileCoordinator _invokeAccessor:thenCompletionHandler:] + 100
	7   Foundation                          0x0000000193d0bdf0 __98-[NSFileCoordinator coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:]_block_invoke + 132
	8   Foundation                          0x0000000193eaca1c __110-[NSFileCoordinator(NSPrivate) _coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:]_block_invoke.381 + 300
	9   Foundation                          0x0000000193c6ecd0 -[NSFileCoordinator(NSPrivate) _withAccessArbiter:invokeAccessor:orDont:andRelinquishAccessClaim:] + 620
	10  Foundation                          0x0000000193d0a4a8 -[NSFileCoordinator(NSPrivate) _coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:] + 1184
	11  Foundation                          0x0000000193d09fe0 -[NSFileCoordinator coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:] + 120
	12                              0x000000010119ca28 -[GULHeartbeatDateStorage setHearbeatDate:forTag:] + 436
	13                              0x00000001011b2920 -[FIRCoreDiagnostics setHeartbeatFlagIfNeededToConfig:] + 228
	14                              0x00000001011b2654 __42-[FIRCoreDiagnostics sendDiagnosticsData:]_block_invoke + 252
	15  libdispatch.dylib                   0x0000000106ca4020 _dispatch_call_block_and_release + 32
	16  libdispatch.dylib                   0x0000000106ca5da0 _dispatch_client_callout + 20
	17  libdispatch.dylib                   0x0000000106caf1c8 _dispatch_lane_serial_drain + 804
	18  libdispatch.dylib                   0x0000000106cb0318 _dispatch_lane_invoke + 452
	19  libdispatch.dylib                   0x0000000106cbfc68 _dispatch_workloop_worker_thread + 1924
	20  libsystem_pthread.dylib             0x00000001067ab4a0 _pthread_wqthread + 276
	21  libsystem_pthread.dylib             0x00000001067aa1d8 start_wqthread + 8
)
(lldb) 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

This is my Apple delegate, using SwiftUi for whole app:

```
import SwiftUI
import Firebase

@main
struct myApp: App {
    

    func applicationDidFinishLaunching(_ aNotification: Notification) {
        Database.database().reference()
    }
    
    init() {
      FirebaseApp.configure()
        Database.database().isPersistenceEnabled = true
    }

    var body: some Scene {

        WindowGroup {            
            Initial()
            .environmentObject(SessionStore())
        }
        
    }
}

```

**Comment by maksymmalyhin** [comment] 2021-05-07 16:00
It looks like a duplicate of #8047. Closing it so far. Feel free to reopen it with more details if you think it is a separate issue.

**Closed by maksymmalyhin** 2021-05-07 16:00 UTC
Labels: api: auth

**Comment by alelordelo** [comment] 2021-05-07 16:34
@maksymmalyhin , are you sure it’s a duplicate? It’s doesn’t mention apple M1 or app delegate

**Comment by paulb777** [comment] 2021-05-07 17:33
@alelordelo The crash backtrace matches.
