### ISSUE TITLE
[Firebase Crashlytics] ignoring duplicate libraries: '-lc++'

### ISSUE THREAD

**Issue by hoangquangbao** [firebase/firebase-ios-sdk#11980] opened 2023-10-23 04:43 UTC
### Description

**Describe the issue**
I got a warning when build my iOS project with Xcode 15. Xcode 14 didn't get them.

`ignoring duplicate libraries: '-lc++'`

I think Xcode 15 automatically add libc++, you don't need to add it as well.

```
FirebaseCrashlytics.podspec (Line: 66)
s.libraries = 'c++', 'z'  // consider remove this line
```

**Expected**
Removes a warning in the app compilation step.

### Firebase SDK Version

10.16.0

### Xcode Version

15.0

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2023-10-23 10:12
Hi @hoangquangbao, this issue seems related to #11818.

**Comment by paulb777** [comment] 2023-10-23 13:54
Yes. Closing as a duplicate of #11818. See the discussion and workarounds there.

**Closed by paulb777** 2023-10-23 13:54 UTC
Labels: Xcode 15 - iOS 17

**Comment by hoangquangbao** [comment] 2023-10-24 01:34
Thank you.
