### ISSUE TITLE
Memory Leaks issue using .whereField(_, isEqualTo:)

### ISSUE THREAD

**Issue by holmeso983** [firebase/firebase-ios-sdk#12732] opened 2024-04-09 13:39 UTC
### The Issue
I'm currently receiving mutiple memory leaks when using the .whereField(_, isEqualTo:) in one of my functions. The happens no where else in my code other than here, which is quite confusing. When I remove just the .whereField(_, isEqualTo:) line, I have no issues. 

### The Code:
```
static func getManyFromProject(_ project: Project, topLevelCategoryID: String?, sortByDateAdded: Bool = false, limit: Int = 10) async -> Result<[InventoryItem], Error> {
        do {
            // 1. Base query setup for project items
            var baseQuery: Query = FirebaseService.shared.database
                .collection("companies")
                .document("123456")
                .collection(Collections.inventory.rawValue)
            // Apply project filter
                .whereField("projectID", isEqualTo: project.objectID)   // MARK: MEMORY LEAK HERE
            
            // Execute the base query
            let allProjectItems: [InventoryItem] = try await FirebaseService.shared.getMany(with: baseQuery).get()
 
            return .success(allProjectItems)
        } catch let error {
            return .failure(error)
        }
    }
```

### Logs
![Screenshot 2024-04-09 at 3 13 43 PM](https://github.com/firebase/firebase-ios-sdk/assets/134079813/b734ca7e-09f9-4f81-9ba1-d13166e6ef62)

![Screenshot 2024-04-09 at 3 14 29 PM](https://github.com/firebase/firebase-ios-sdk/assets/134079813/f4e36210-0091-4ecd-971e-f5880fdd3a2e)

### Firebase SDK Version

10.23.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Database, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by jesus-mg-ios** [comment] 2024-04-09 15:25
Yas, Same error here, workaround trying to not use whereField ...

**Comment by MarkDuckworth** [comment] 2024-04-09 15:53
Thanks for the report and the sample code. I'm going to close this as a duplicate of https://github.com/firebase/firebase-ios-sdk/issues/12613. The team is working on a fix, but I will also share this report.

**Closed as not planned by MarkDuckworth** 2024-04-09 15:53 UTC
Labels: needs-triage, api: firestore
