### ISSUE TITLE
 Firebase's Deletegate didReceiveRegistrationToken is not called and token is nil

### ISSUE THREAD

**Issue by OkumuraShintarou** [firebase/firebase-ios-sdk#1339] opened 2018-05-28 05:46 UTC
## Envroment
- Xcode Version: 9.3.1
- FirebaseSDK version: 4.9.0
- Firebase Component: Messaging
- Component Version: 2.1.0

## problem
In-house I am implementing Firebase's fcmToken and sending a push notification. 
But firebase 's  fcmToken can not be acquired at all, and delegate has never been called.
I investigated it with the same verison as this is a firebase bug or my own project is wrong.
The project created by me can get fcmToken and delegate called.

I'm Very Warried...

If you like, please let me know where the cause for this is involved.

## What I tried
- Checked GoogleService-Info.plist (There are three for debug, inhouse, and production)
- Reneual APNs
- Reneual APNsKey
- Reneual Certificate
- Called observerMethod 
- Use Swift standard observer and call delegate method of didReceiveRegistrationToken
- Reneual GoogleService-info.plist 
- Create SampleProject (Successful acquisition of fcmToken)

**Comment by morganchen12** [comment] 2018-05-29 16:50
Can you share the project that's unable to fetch the fcmToken?

**Comment by TuanFram** [comment] 2018-05-31 08:43
I don't know why but some days before, firebase was working normal in my project but today it's not working =((((

**Comment by OkumuraShintarou** [comment] 2018-06-04 04:57
@morganchen12 We can not be shared because of the company's products.

**Comment by OkumuraShintarou** [comment] 2018-06-04 04:59
@TuanFram I see. Can you share that project?

**Comment by morganchen12** [comment] 2018-06-04 16:58
Can you share your implementation of `FIRMessagingDelegate`?

**Comment by ccynn** [comment] 2018-06-17 00:05
i am having the same issue where the didReceiveRegistrationToken delegate function all of a sudden isn't firing anymore...it was just working the other day where i'd see the fcmToken

**Comment by omatty198** [comment] 2018-06-17 00:08
@ccynn Can it be reproduced by creating a new project?

**Comment by ccynn** [comment] 2018-06-17 01:10
i just reproduced it and weird...with the new project the didReceiveRegistrationToken does get triggered.

what's the best mode of action here?

**Comment by morganchen12** [comment] 2018-06-18 19:03
Closing this issue since there's not enough information for me to debug. Please feel free to continue commenting here, and if someone shares a reproducible example, I'll re-open the issue.

**Closed by morganchen12** 2018-06-18 19:03 UTC
Labels: Messaging

**Comment by pwlkania** [comment] 2018-06-25 10:22
I was struggling with this issue too. Steps to reproduce from my app:

1. In UIViewController_1 call `FirebaseApp.configure()`
2. Push UIViewController_2 and set the messaging delegate, i.e. `Messaging.messaging().delegate = self`
3. In UIViewController_2 call `UIApplication.shared.registerForRemoteNotifications()` - system alert view should appear; tap accept
4. In UIViewController_2 listen for device token - send it via Notification from appdelegate to controller
5. In UIViewController_2 in method which receives device token call `Messaging.messaging().apnsToken = data`

Result: `InstanceID.instanceID().token()` is nil and nothing from `MessagingDelegate` is called

However, there is simple workaround for this - looks like you have to set the messaging delegate (`Messaging.messaging().delegate = ...`) before `FirebaseApp.configure()`

**Comment by gerchicov-bp** [comment] 2018-07-27 12:23
@morganchen12 
As I understand `didReceiveRegistrationToken` method simply doesn't exist at all.

So it seems everything is correct except of the documentation:
https://firebase.google.com/docs/cloud-messaging/ios/client

Fix the documentation please

**Comment by kilirushi** [comment] 2018-11-28 15:40
I fixed it. I think I was wrong when I put in the end
FirebaseApp.configure()
Messaging.messaging().delegate = self
 And I fixed it as screenshoot below:
![screen shot 2018-11-28 at 22 37 50](https://user-images.githubusercontent.com/17327812/49162820-4d0d6900-f35e-11e8-9b4a-eeb6f4168cf6.png)

**Comment by shoaibnomani** [comment] 2018-12-21 07:00
> I fixed it. I think I was wrong when I put in the end
> FirebaseApp.configure()
> Messaging.messaging().delegate = self
> And I fixed it as screenshoot below:
> ![screen shot 2018-11-28 at 22 37 50](https://user-images.githubusercontent.com/17327812/49162820-4d0d6900-f35e-11e8-9b4a-eeb6f4168cf6.png)

This solved the issue for me. But I can't figure out why this started happening. It was working fine previously.

**Comment by aparandiy** [comment] 2019-01-04 12:40
shoaibnomani, thank you man - you saved my day

**Comment by shoaibnomani** [comment] 2019-01-04 13:09
> shoaibnomani, thank you man - you saved my day

It was in fact the solution by @kilirushi if you look above in the thread. It saved me a lot of time as well.

**Comment by engasix** [comment] 2019-02-17 09:29
> > I fixed it. I think I was wrong when I put in the end
> > FirebaseApp.configure()
> > Messaging.messaging().delegate = self
> > And I fixed it as screenshoot below:
> > ![screen shot 2018-11-28 at 22 37 50](https://user-images.githubusercontent.com/17327812/49162820-4d0d6900-f35e-11e8-9b4a-eeb6f4168cf6.png)
> 
> This solved the issue for me. But I can't figure out why this started happening. It was working fine previously.

I think this makes sense you are trying to set up the delegate while firebase engine is not yet ready.

**Comment by harshad1242** [comment] 2019-10-03 15:38
Firebase need to take some second to connect with server. so i gave 5 second delay. 
```
DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(5000)) {
            InstanceID.instanceID().instanceID { (result, error) in
            // Get called
            if let error = error {
                print("Error fetching remote instance ID: \(error)")
            } else if let result = result {
             
                print("Remote instance ID token: \(result.token)")
                //self.instanceIDTokenMessage.text  = "Remote InstanceID token: \(result.token)"
            }}
        }
```
