### ISSUE TITLE
[FR]: Apple privacy manifest file

### ISSUE THREAD

**Issue by sborovikov-belkacar** [firebase/firebase-ios-sdk#12389] opened 2024-02-14 07:31 UTC
### Description

1. Having this manifest will be a requirement from Apple starting in spring 2024. 
https://developer.apple.com/support/third-party-SDK-requirements/

### Firebase Product(s)

AB Testing, Analytics, Authentication, Crashlytics, DynamicLinks, Firestore, Installations, Messaging, Remote Config

**Comment by peterfriese** [comment] 2024-02-14 08:04
Duplicate of #11490

**Closed by peterfriese** 2024-02-14 08:04 UTC
Labels: needs-triage, type: feature request
