### ISSUE TITLE
Crash at iOS 13.3 (Cannot convert value of type 'UnsafeRawPointer')

### ISSUE THREAD

**Issue by Denok137** [firebase/firebase-ios-sdk#11333] opened 2023-05-26 11:44 UTC
### Description

Hello!
Some users faced with crash at iOS 13.3-13.6 version

I compile project at Mac OS 13.3.1 and xCode 14.3. No compilation problem. Last available iOS simulator is iOS 13.7 no problem too
I took an old macbook 2014 with Xcode 12.5 mac os 11.7 try compile project and faced with error

> Pods/FirebaseSessions/FirebaseSessions/Sources/SessionStartEvent.swift:217:56: Cannot convert value of type 'UnsafeRawPointer' to expected argument type 'UnsafePointer<pb_byte_t>?' (aka 'Optional<UnsafePointer<UInt8>>')

at this place 
```
let bytes = (transportBytes as NSData).bytes
var istream: pb_istream_t = pb_istream_from_buffer(bytes, transportBytes.count)

```

i see same ticket - https://github.com/firebase/flutterfire/issues/10711

found workaround, replace 
`let bytes = (transportBytes as NSData).bytes`
with
`let bytes = (transportBytes as NSData).bytes.bindMemory(to: pb_byte_t.self, capacity: transportBytes.count)`

but what about fix it at master?

waiting for an response

### Firebase SDK Version

10.10

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Pods/FirebaseSessions/FirebaseSessions/Sources/SessionStartEvent.swift:217:56: Cannot convert value of type 'UnsafeRawPointer' to expected argument type 'UnsafePointer<pb_byte_t>?' (aka 'Optional<UnsafePointer<UInt8>>')
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - Alamofire (4.9.1)
  - Eureka (5.3.5)
  - Firebase/Analytics (10.10.0):
    - Firebase/Core
  - Firebase/Core (10.10.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.10.0)
  - Firebase/CoreOnly (10.10.0):
    - FirebaseCore (= 10.10.0)
  - Firebase/Crashlytics (10.10.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.10.0)
  - Firebase/Messaging (10.10.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.10.0)
  - FirebaseAnalytics (10.10.0):
    - FirebaseAnalytics/AdIdSupport (= 10.10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.10.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.10.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreExtension (10.10.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.10.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.10.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInstallations (10.10.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.10.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseSessions (10.10.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - GoogleAppMeasurement (10.10.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.10.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.10.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.3):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleMaps (5.2.0):
    - GoogleMaps/Maps (= 5.2.0)
  - GoogleMaps/Base (5.2.0)
  - GoogleMaps/Maps (5.2.0):
    - GoogleMaps/Base
  - GoogleUtilities/AppDelegateSwizzler (7.11.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.1):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.11.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.11.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.1)"
  - GoogleUtilities/Reachability (7.11.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.1):
    - GoogleUtilities/Logger
  - ImageRow (4.1.0):
    - Eureka (~> 5.3.5)
  - InputBarAccessoryView (4.2.2)
  - IQKeyboardManagerSwift (6.5.10)
  - Kingfisher (6.3.1)
  - MarqueeLabel (4.0.5)
  - MessageKit (3.0.0):
    - InputBarAccessoryView (~> 4.2.2)
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - NotificationBannerSwift (3.0.6):
    - MarqueeLabel (~> 4.0.5)
    - SnapKit (~> 5.0.1)
  - Parchment (3.2.0)
  - PromisesObjC (2.2.0)
  - PromisesSwift (2.2.0):
    - PromisesObjC (= 2.2.0)
  - RichTextRow (1.0.4):
    - Eureka (~> 5.3)
  - SnapKit (5.0.1)
  - SwiftLint (0.52.2)
  - SwiftyJSON (5.0.1)
  - YandexMobileMetrica/Dynamic/Core (4.5.2)

DEPENDENCIES:
  - Alamofire (= 4.9.1)
  - Eureka (= 5.3.5)
  - Firebase/Analytics (~> 10.10.0)
  - Firebase/Crashlytics (~> 10.10.0)
  - Firebase/Messaging (~> 10.10.0)
  - GoogleMaps
  - ImageRow (= 4.1.0)
  - IQKeyboardManagerSwift (= 6.5.10)
  - Kingfisher
  - MessageKit (= 3.0.0)
  - NotificationBannerSwift (= 3.0.6)
  - Parchment (= 3.2.0)
  - RichTextRow (from `https://github.com/EurekaCommunity/RichTextRow.git`, commit `029e0450f205845b1a62ec2b6141f63da6d9e523`)
  - SwiftLint
  - SwiftyJSON
  - YandexMobileMetrica/Dynamic/Core (~> 4.5.0)

SPEC REPOS:
  trunk:
    - Alamofire
    - Eureka
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseSessions
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMaps
    - GoogleUtilities
    - ImageRow
    - InputBarAccessoryView
    - IQKeyboardManagerSwift
    - Kingfisher
    - MarqueeLabel
    - MessageKit
    - nanopb
    - NotificationBannerSwift
    - Parchment
    - PromisesObjC
    - PromisesSwift
    - SnapKit
    - SwiftLint
    - SwiftyJSON
    - YandexMobileMetrica

EXTERNAL SOURCES:
  RichTextRow:
    :commit: 029e0450f205845b1a62ec2b6141f63da6d9e523
    :git: https://github.com/EurekaCommunity/RichTextRow.git

CHECKOUT OPTIONS:
  RichTextRow:
    :commit: 029e0450f205845b1a62ec2b6141f63da6d9e523
    :git: https://github.com/EurekaCommunity/RichTextRow.git

SPEC CHECKSUMS:
  Alamofire: 85e8a02c69d6020a0d734f6054870d7ecb75cf18
  Eureka: 7b39a479d074620d43028a0e2bfc3e0d667724df
  Firebase: facd334e557a979bd03a0b58d90fd56b52b8aba0
  FirebaseAnalytics: 7bc7de519111dae802f5bc0c9c083918f8b8870d
  FirebaseCore: d027ff503d37edb78db98429b11f580a24a7df2a
  FirebaseCoreExtension: 8d93ebbf6838a874b4ed82a564c9d6705f8365dd
  FirebaseCoreInternal: 971029061d326000d65bfdc21f5502c75c8b0893
  FirebaseCrashlytics: bc8f3bed7f4d04be79d87391455efb4c9b163131
  FirebaseInstallations: 52153982b057d3afcb4e1fbb3eb0b6d00611e681
  FirebaseMessaging: 8a3b9a8b98ce72a42d22e69865cf662e38d2d6f5
  FirebaseSessions: 5f9e62cd4096e24d2011cbd845b0efceffaee1ec
  GoogleAppMeasurement: bbbfd4bcb2b40ae9b772c3b0823a58c1e3d618f9
  GoogleDataTransport: f0308f5905a745f94fb91fea9c6cbaf3831cb1bd
  GoogleMaps: 025272d5876d3b32604e5c080dc25eaf68764693
  GoogleUtilities: 9aa0ad5a7bc171f8bae016300bfcfa3fb8425749
  ImageRow: 880c0f052c5a89c80521b485c86ccf723a124e99
  InputBarAccessoryView: 2b937602598e2fab3149f37f51dd7ad795653812
  IQKeyboardManagerSwift: 52962c76ab33532f15ad9f3ff4e5715eda5335bb
  Kingfisher: 016c8b653a35add51dd34a3aba36b580041acc74
  MarqueeLabel: 00cc0bcd087111dca575878b3531af980559707d
  MessageKit: e892a9ca49ebe6d82684d3a93ad84021fa23e2c6
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  NotificationBannerSwift: 7021be2338f8f29cf424b0aca43da462bf9e2a1a
  Parchment: a43c440b22c8a60f7e0196b74339446d4d1d18ea
  PromisesObjC: 09985d6d70fbe7878040aa746d78236e6946d2ef
  PromisesSwift: cf9eb58666a43bbe007302226e510b16c1e10959
  RichTextRow: 105917e1ac39a50f18a4b17de8fa656203bf7516
  SnapKit: 97b92857e3df3a0c71833cce143274bf6ef8e5eb
  SwiftLint: 1ac76dac888ca05cb0cf24d0c85887ec1209961d
  SwiftyJSON: 2f33a42c6fbc52764d96f13368585094bfd8aa5e
  YandexMobileMetrica: f5368ee93f286c793d73b58da00929babfc897c1

PODFILE CHECKSUM: adfa2b854711871d78046dc87db14d6c21ac941c

COCOAPODS: 1.12.1


```

</details>

**Comment by paulb777** [comment] 2023-05-26 14:15
Duplicate of #10966. And now with Firebase 10.10.0, at least Xcode 14.1 is required.

**Closed by paulb777** 2023-05-26 14:15 UTC
Labels: sessions
