### ISSUE TITLE
Firestore new crashes - 10.14.0

### ISSUE THREAD

**Issue by mgrms** [firebase/firebase-ios-sdk#11794] opened 2023-09-11 20:54 UTC
### Description

Hello,

After updating from 10.9.0 to 10.14.0 we observe new Firestore crashes in Crashlytics. At the moment it happened only for iOS 12 users.

Here is stack:
```
Crashed: com.google.firebase.firestore
0  grpcpp                         0x4a10 grpc_core::ExecCtx::ExecCtx() + 156 (time.h:156)
1  grpcpp                         0x2bf5c grpc::SecureChannelCredentials::~SecureChannelCredentials() + 54 (secure_credentials.h:54)
2  grpcpp                         0x2c160 std::__1::__shared_ptr_pointer<grpc::SecureChannelCredentials*, std::__1::shared_ptr<grpc::ChannelCredentials>::__shared_ptr_default_delete<grpc::ChannelCredentials, grpc::SecureChannelCredentials>, std::__1::allocator<grpc::SecureChannelCredentials>>::__on_zero_shared() + 57 (unique_ptr.h:57)
3  FirebaseFirestore              0x94a04 firebase::firestore::remote::GrpcConnection::CreateChannel() const + 220 (shared_ptr.h:220)
4  FirebaseFirestore              0x94734 firebase::firestore::remote::GrpcConnection::EnsureActiveStub() + 869 (shared_ptr.h:869)
5  FirebaseFirestore              0x94f24 firebase::firestore::remote::GrpcConnection::CreateStream(absl::lts_20220623::string_view, firebase::firestore::credentials::AuthToken const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, firebase::firestore::remote::GrpcStreamObserver*) + 343 (grpc_connection.cc:343)
6  FirebaseFirestore              0x1438cc firebase::firestore::remote::Stream::ResumeStartWithCredentials(firebase::firestore::util::StatusOr<firebase::firestore::credentials::AuthToken> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 308 (unique_ptr.h:308)
7  FirebaseFirestore              0x144dfc std::__1::__function::__func<firebase::firestore::remote::Stream::RequestCredentials()::$_0::operator()(absl::lts_20220623::optional<firebase::firestore::util::StatusOr<firebase::firestore::credentials::AuthToken>> const&, absl::lts_20220623::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>> const&) const::'lambda'(), std::__1::allocator<firebase::firestore::remote::Stream::RequestCredentials()::$_0::operator()(absl::lts_20220623::optional<firebase::firestore::util::StatusOr<firebase::firestore::credentials::AuthToken>> const&, absl::lts_20220623::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>> const&) const::'lambda'()>, void ()>::operator()() + 176 (shared_ptr.h:176)
8  FirebaseFirestore              0xb180 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 997 (atomic:997)
9  FirebaseFirestore              0x15656c firebase::firestore::util::Task::ExecuteAndRelease() + 491 (function.h:491)
10 libdispatch.dylib              0x61484 _dispatch_client_callout + 16
11 libdispatch.dylib              0x8bd0 _dispatch_lane_serial_drain$VARIANT$mp + 592
12 libdispatch.dylib              0x9718 _dispatch_lane_invoke$VARIANT$mp + 432
13 libdispatch.dylib              0x11eb8 _dispatch_workloop_worker_thread + 600
14 libsystem_pthread.dylib        0xc0dc _pthread_wqthread + 312
15 libsystem_pthread.dylib        0xecec start_wqthread + 4
```

Hope for the fix soon.

### Firebase SDK Version

10.14.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

**Comment by mgrms** [comment] 2023-09-12 10:07
As for now, we see this crash for iOS 12 users, and iPadOS 14 users. It has "Early crashes" and"Repetitive crashes" Crashlytics badges on it. I guess it makes app unusable for these users.

**Comment by dconeybe** [comment] 2023-09-12 11:37
Drive-by comment: This looks like a duplicate of https://github.com/firebase/firebase-ios-sdk/issues/11509.

**Comment by mgrms** [comment] 2023-09-12 13:11
Hi @dconeybe ,

Thank you for your comment.

These two look similar. We see a huge number of such crashes for our users on production. Should we downgrade back to 10.9.0 asap?

**Comment by paulb777** [comment] 2023-09-12 19:58
Closing in favor of the duplicate #11509. Please see the discussion there.

**Closed by paulb777** 2023-09-12 19:58 UTC
Labels: api: firestore
