### ISSUE TITLE
Crashed: com.google.iid-token-operations (QOS: UTILITY)

### ISSUE THREAD

**Issue by Swarnima-shuttl** [firebase/firebase-ios-sdk#1179] opened 2018-04-25 07:51 UTC
Xcode version: 9.2
Firebase SDK version: 4.13.0

Podfile:
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'

Podfile lock: 
- Firebase/Analytics (4.13.0):
    - Firebase/Core
  - Firebase/Core (4.13.0):
    - FirebaseAnalytics (= 4.2.0)
    - FirebaseCore (= 4.0.20)
  - Firebase/Messaging (4.13.0):
    - Firebase/Core
    - FirebaseMessaging (= 2.2.0)
  - Firebase/RemoteConfig (4.13.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 2.1.3)
  - FirebaseABTesting (1.0.0):
    - FirebaseCore (~> 4.0)
    - Protobuf (~> 3.1)
  - FirebaseAnalytics (4.2.0):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.20):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.10):
    - FirebaseCore (~> 4.0)
  - FirebaseMessaging (2.2.0):
    - FirebaseAnalytics (~> 4.1)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.5)
  - FirebaseRemoteConfig (2.1.3):
    - FirebaseABTesting (~> 1.0)
    - FirebaseAnalytics (~> 4.1)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - Protobuf (~> 3.5)
 
Problem: 
It is occurring to few of our users. We are not able to reproduce.

Crashlytics indicate :
The stack trace indicates that heap corruption may have caused your app to crash. Memory corruption can occur pretty easily from freeing a dangling pointer, a thread race, or bad pointer arithmetic. The important thing to keep in mind is that the resulting crash may happen long after the initial corruption. As a result, the stack trace for this crash might not provide any clues to the location of the bug in your code. However, you can still fix memory issues with tools from Apple. For speedy resolution of memory corruption issues, we recommend regularly auditing your app with Xcode’s memory debugging facilities: Visual Memory Debugger, Zombies Instrument, Address Sanitizer, Thread Sanitizer and malloc diagnostics.

Crash logs:

#3
Crashed: com.google.iid-token-operations (QOS: UTILITY)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000b26cfbec8

Crashed: com.google.iid-token-operations (QOS: UTILITY)
0  libobjc.A.dylib                0x1825201a0 objc_retain + 16
1  Shuttl                         0x1006add44 +[FIRLoggerWrapper logWithLevel:withService:withCode:withMessage:withArgs:] + 4311391556
2  CoreFoundation                 0x1832bd670 __invoking___ + 144
3  CoreFoundation                 0x18319c6cc -[NSInvocation invoke] + 292
4  Shuttl                         0x1006ce020 +[FIRInstanceIDLogger logWithLevel:withService:withCode:withMessage:withArgs:] + 4311523360
5  Shuttl                         0x1006ce1d4 -[FIRInstanceIDLogger logFuncDebug:messageCode:msg:] + 4311523796
6  Shuttl                         0x1006d0964 -[FIRInstanceIDTokenFetchOperation performTokenOperation] + 4311533924
7  Foundation                     0x183c83004 __NSOQSchedule_f + 404
8  libdispatch.dylib              0x182c39048 _dispatch_client_callout + 16
9  libdispatch.dylib              0x182c413d4 _dispatch_continuation_pop$VARIANT$mp + 428
10 libdispatch.dylib              0x182c3fcd4 _dispatch_async_redirect_invoke$VARIANT$mp + 604
11 libdispatch.dylib              0x182c461c8 _dispatch_root_queue_drain + 596
12 libdispatch.dylib              0x182c45f10 _dispatch_worker_thread3 + 120
13 libsystem_pthread.dylib        0x182edf120 _pthread_wqthread + 1268
14 libsystem_pthread.dylib        0x182edec20 start_wqthread + 4

Relevant code:
- We have lazy initialized the class fetching remoteConfig. And the remoteConfig data is fetched from the main thread (viewDidLoad() of a viewController). 
- Analytics user property is set everytime user data is fetched/ updated.

**Comment by paulb777** [comment] 2018-04-25 13:40
This is a duplicate of #402 which was fixed in Firebase 4.8.0.   The FIRLoggerWrapper call in the backtrace was eliminated from the code in that release.

It looks like these are crash reports from an un-updated release of the app.

**Closed by paulb777** 2018-04-25 13:40 UTC
