### ISSUE TITLE
Missing dSYM upload commands if Crashlytics installed with Carthage

### ISSUE THREAD

**Issue by olejnjak** [firebase/firebase-ios-sdk#4720] opened 2020-01-22 02:19 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.15
  * Firebase Component: Crashlytics
  * Component version: 6.15

### [REQUIRED] Step 3: Describe the problem

When Crashlytics is installed using Carthage, dSYM upload scripts are missing.

 The issue would be that before making Crashlytics open source and using `https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json` as source for Carthage, the _run_ and _upload-symbols_ were located under _Crashlytics.framework_ folder in the targeted zip file, now they are outside and Carthage does not copy them to projects _Carthage/Build_ directory.

Is this expected behavior and we are expected to get those commands from somewhere else or is it a bug? Thanks in advance.

#### Steps to reproduce:

Run in terminal:
```
echo 'binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" ~> 6.15' > Cartfile
carthage update
ls -r Carthage/Build/iOS/FirebaseCrashlytics.framework
```
The _run_ and _upload-symbols_ commands are missing.

#### Relevant Code:

See above ⬆️

**Comment by ryanwilson** [comment] 2020-01-22 02:53
Thanks for the report - this is working as expected and instructions can be found [at the bottom of this section of Carthage.md](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage) (search for "For Crashlytics").

I was under the impression that Carthage expected a very specific format and including the binaries inside the `.framework` was causing issues but I could be wrong. 

@jasonhu-g or @paulb777 do you remember the reason for excluding it?

I'll close this as working as intended but we can re-open if something should be done to address this.

**Closed** 2020-01-22 02:53 UTC
Labels: api: crashlytics

**Comment by jasonhu-g** [comment] 2020-01-22 14:45
The change was made for a few reasons:
1. Transparency - Developers can more easily see what is included without embedding executables into the framework.
2. Size  - The framework included in apps will take up less space. 
3. Maintainability - We implemented parts of upload-symbols to Swift at one point. Even though upload-symbols will only run on macOS, Objective-C only apps fail to build because XCode runs scans on files inside the framework and detected Swift code. Moving upload-symbols outside of the framework will give us better maintainability and flexibility.

**Comment by olejnjak** [comment] 2020-01-22 14:50
Thanks for clearing it up 🙂 and is there a way to use Carthage distribution and fetch its corresponding _upload-symbols_ executable? Or it would be safe to always use the version from `master` branch regardless of Crashlytics version?

**Comment by jasonhu-g** [comment] 2020-01-22 15:00
We currently do not know of any Carthage capabilities which allows us to distribute the upload symbols executable alongside with the framework. We will update this thread if things change. 

We haven't experienced any changes to upload-symbols where it is tied to a specific version of the SDK. But if you really want to be safe, download the Crashlytics Carthage JSON, follow the link in the JSON file to download the zip file which contains the upload symbols executables for the specific version.
