### ISSUE TITLE
Firestore: Delayed listener updates and delayed persistence after heavy batch writes

### ISSUE THREAD

**Issue by KabukiAdam** [firebase/firebase-ios-sdk#5911] opened 2020-06-25 14:40 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.27
  * Firebase Component: Firestore
  * Component version: 6.27
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

I’m not sure if this is one problem or a couple different problems.  Let me know if you’d like me to create a new separate issue for any of this.

We’re using Firestore with persistence enabled, unlimited cache size.

At certain times, our app may perform several batch adds and deletes within a short period of time.  The total documents being added or deleted may be a few thousand (but we still split it up into bacthes that are less than the max size of 500).

* After a few sets of these batch adds and deletes, there seems to be a delay in when these changes come through on our listener.  It can be quite a while sometimes, 10 seconds, 30 seconds, maybe even a minute.  It is my understanding based on the docs that “Local writes in your app will invoke snapshot listeners immediately” (latency comnpensation).  While this seems to be the case normally, it does not seem to be the case after doing heavy batch operations.  Can heavy batch operation calls cause some sort of bottleneck? 
* A more serious problem seems to be that not only is there a delay in the listener in these cases, but that there seems to be a delay in persisting these writes to the cache.  I was under the impression that the writes to cache happened synchronously, so that by the time batch.commit() returns, the data has been persisted in the cache.  But this seems not to be the case.  If the our app is closed during these bottleneck periods (prior to all the changes coming through on the listener), and then launched fresh, our listener sees only some of the changes made by the previous batch operations…as if some of them never were persisted before the app closed.

Are the bottlenecks/delays we’re experiencing in regard to local writes coming through on the listener considered normal (for heavy batch updates)?  If so, is there anything we can do to make this work better?

Is it indeed the case that SDK calls to the write functions (such as batch.commit()) aren’t persisting the data syncronously?

For what its worth, our app handles the delayed listener updates fairly well (although certainly sometimes it becomes a bit of an issue).  The real problem that’s biting us is the delayed persistence. We make some batch updates, then if the user closes the app soon after, then next time they launch the app they see that they have missing/wrong data.  Our app isn’t well suited to having any sort of “make the user wait while saving changes” type of UI…we pretty much need it to be the case that at the time the user “sees” the changes in their doc, that the changes have actually been persisted.

#### Steps to reproduce:
I’m able to reproduce the issue with batch writes not being synchronously persisted with a very simple sample app that does the following:
1. Sets up listener for collection of documents
2. Adds 1350 new documents (3 x 450 batch writes).
3. After final batch.commit() returns, wait 0.25 seconds, then abort the app.
4. Upon re-launch, only some (or none) of the documents are returned by the listener (not all 1350).  I've attached the sample app for this.

[FirestoreWriteTest Sample.zip](https://github.com/firebase/firebase-ios-sdk/files/4832000/FirestoreWriteTest.Sample.zip)

**Comment by thebrianchen** [comment] 2020-06-26 18:07
@KabukiAdam Thanks for writing in with a detailed report and reproduction app! I was able to observe what you were describing.

> Can heavy batch operation calls cause some sort of bottleneck?

In order to maintain its strong consistency guarantees, all Firestore operations are queued locally. Your series of batch writes is expensive to handle due its size. Breaking the large batches down into smaller batches of 30 to 50 would speed up the write times. Since batches are committed atomically, smaller batches also allow Firestore to locally persist the data more frequently.

> Is it indeed the case that SDK calls to the write functions (such as batch.commit()) aren’t persisting the data synchronously?

Terminating Firestore before it can locally persist the writes will cause them to be lost. One way to know if all writes have been durably persisted is to perform perform a get from the [cache](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Enums/FirestoreSource#cache) after making your writes. Since operations are queued and executed serially, obtaining a snapshot from the cache implies your previous writes have been persisted.

**Closed** 2020-07-06 17:55 UTC
Labels: api: firestore
