### ISSUE TITLE
Missing dsyms in firebase

### ISSUE THREAD

**Issue by AbhishekBB** [firebase/firebase-ios-sdk#8464] opened 2021-07-30 08:56 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 6.24.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

Manual upload script gives result as "**Successfully uploaded Crashlytics symbols**" But when I got Crashlytics it says "**This app has 37 unprocessed crashes. Upload 2 dSYM files to process them**".

#### Steps to reproduce:

<img width="1317" alt="Screenshot 2021-07-30 at 2 11 01 PM" src="https://user-images.githubusercontent.com/15157308/127628275-14427fec-be72-4bcf-a4ac-52f78fc7393a.png">

<img width="1019" alt="Screenshot 2021-07-30 at 2 11 18 PM" src="https://user-images.githubusercontent.com/15157308/127628307-89cca414-59c1-4509-ad5f-5ac8bfd1007c.png">

<img width="1444" alt="Screenshot 2021-07-30 at 2 11 32 PM" src="https://user-images.githubusercontent.com/15157308/127628337-843499f2-6fd4-4852-a68d-2b7c784a8b2c.png">

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by rizafran** [comment] 2021-07-30 10:20
Hi @AbhishekBB, it seems like you're using an outdated version of Firebase SDK. With this, could you try using the latest version to see if the issue is reproducible?

**Comment by AbhishekBB** [comment] 2021-07-31 06:45
Ok, We will upgrade to the latest version. But as of now our build is already in production and we are facing some crashes which are not symbolicating because of missing dsym. Is there any way to get it corrected for now?

We are using firebase/performance and crashlytics. How about the change log updating to 8.4.0. Is it a minor change or it has major changes?

**Comment by Shresht-Gatla** [comment] 2021-07-31 12:57
Hello @AbhishekBB, regarding your first question, I have one simple solution, which may help you in identifying crashes in your app, which is already in production, in Firebase Crashlytics.

Please open terminal and paste this following code:
`/path/to/pods/directory/FirebaseCrashlytics/upload-symbols -gsp /path/to/GoogleService-Info.plist -p ios /path/to/dSYMs`

This code consists of paths to three directories:
1. Path to your **upload-symbols**. (If you're using cocoaPods, it is located in Pods > FirebaseCrashlytics folder)
2. Path to your **GoogleService-Info.plist** file.
3. Path to your **dSYM's folder**. (If you don't know your dSYM's location. Just go to **AppStoreConnect**, go to your app and in the **TestFlight** tab, select your latest build and inside your build go to **Build Metadata** tab, in the **Include Symbols** section you will find a button **download dSYM**, download it).

For more information, please refer to this [document](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios).

Thanks!

**Comment by AbhishekBB** [comment] 2021-07-31 16:18
@Shresht-Gatla I already tried upload-symbols command, As mentioned in the above screenshot which is getting uploaded successfully. But still 2 of the UUID shows missing dsyms.

**Comment by duyquang91** [comment] 2021-08-02 02:56
I'm facing this issue also, seems like Apple Connect is returning wrong UUID not by Firebase

**Comment by rizafran** [comment] 2021-08-03 18:11
Hi @AbhishekBB, based on the [troubleshooting docs](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=ios#ios-locate-dsyms) for missing dSYMs, make sure that you're using the latest Crashlytics version as this contains bug fixes and new features. If you're still getting the issue, could you file a ticket to [Firebase support](https://firebase.google.com/support) in order to get your app and project details and do some investigation in the backend? Thanks.

**Comment by Shadester** [comment] 2021-08-09 19:15
We have the same issue. I wonder if there's an issue on Apple Connect side?

**Comment by daveluong** [comment] 2021-08-10 03:56
We suspect issue on Apple's side as well
https://developer.apple.com/forums/thread/686310

**Comment by daveluong** [comment] 2021-08-10 05:00
> I'm facing this issue also, seems like Apple Connect is returning wrong UUID at this moment. To workaround this, you have to identify the missing Binary to find the missing dSYM file then rename the UUID to match the missing UUID. I just wrote an article to solve this: https://medium.com/geekculture/how-to-fix-the-missing-dsyms-on-firebase-crashlytics-5f36d9db51d9

Thanks man, this workaround works for us 👍

**Comment by schmittsfn** [comment] 2021-08-13 12:58
For missing dsyms firebase should revisit previously uploaded dsyms for the same build version, temporarily substituting the dsym's UUID with the missing ones and trying it on unsymbolicated stack traces to see if it produces what appears as code. It should then present the Firebase user with the option to review the results produced by the substitution and have the human validate it.
For Google, it would be a neat way to train the code recognition algorithm that determines if UUID replacement produced gibberish or not.
For us Firebase users it would automate an otherwise laborious process. Thanks @duyquang91, your solution works perfectly!

**Comment by kevinmun** [comment] 2021-08-16 04:38
@duyquang91 is there any way to determine which binary image file to rename? currently only have firebase crashlytics - so it only showsd what missing uuid, therefore, am not sure which dsym is actually named incorrectly

**Comment by duyquang91** [comment] 2021-08-16 07:07
> @duyquang91 @schmittsfn is there any way to determine which binary image file to rename? currently only have firebase crashlytics - so it only showsd what missing uuid, therefore, am not sure which dsym is actually named incorrectly

Hi @kevinmun 
Unfortunately, there are no way to determine the missing binary on Firebase Crashlytics. For my experience at this moment, the missing binary is the main Application binary.

**Comment by kevinmun** [comment] 2021-08-16 08:15
> > @duyquang91 @schmittsfn is there any way to determine which binary image file to rename? currently only have firebase crashlytics - so it only showsd what missing uuid, therefore, am not sure which dsym is actually named incorrectly
> 
> Hi @kevinmun
> Unfortunately, there are no way to determine the missing binary on Firebase Crashlytics. For my experience at this moment, the missing binary is the main Application binary.

I see, that's very unfortunate, but thank you for the reply

**Comment by schmittsfn** [comment] 2021-08-17 07:55
@kevinmun You can:
Step A) In Crashlytics:
1. Note down the version of the build for which a dsym is missing
2. Note down the UUID of the missing dsym

Step B) Find an unsymbolicated line in one of your crash files for that version:
1. Open Xcode -> Window -> Organiser
2. In the left-hand pane, select `Crashes`
3. Use the drop-down menu in the top left-hand corner to select the version you are interested in
4. Once all the crashes for that version are downloaded, locate the crash you are interested in
5. Find the line in the crash report you are interested in and which is not symbolicated
6. Note down the Library

Step C) Locate the dsym with the incorrect UUID:
1. Open Xcode -> Window -> Organiser
2. In the left-hand pane, select Archives
3. Select the archive that corresponds to the version you noted down in Step A)
4. In the right hand pane, select `Download Debug Symbols`
5. Once finished downloading, in the Organiser right click the archive -> Show in Finder
6. In Finder, right click the archive -> Show Package Contents
7. Go to the `dSYMs` directory
8. Optional: Sort the finder list by `Size`
9. Starting from the top, right click the first dsym file -> `Show Package Contents`
10. Navigate to Contents -> Resources -> Dwarf
11. Compare the name of the file inside the Dwarf directory with the Library name you noted down in Step B) 6.
12.1. If it matches, follow the steps outlined in @duyquang91 excellent writeup to replace the UUID
12.2. If it doesn't match, repeat step 9 - 12, going through all dsym files until you found the right one

**Comment by schmittsfn** [comment] 2021-08-17 14:14
I wrote a tool for it that automates overwriting the UUID.
You can find it here: https://github.com/schmittsfn/dsymrename/blob/main/README.md

**Comment by kevinmun** [comment] 2021-08-19 01:52
@schmittsfn Appreciate the help! though i guess it'll only be applicable to those who do submit crash reports, but at least there is way, none the less

**Comment by duyquang91** [comment] 2021-08-19 05:47
> I wrote a tool that automates finding the UUID for a libName and overwrites its internal UUID.
> You can find it here: https://github.com/schmittsfn/dsymrename

@schmittsfn I've been looking for this tool before, will add it to my article also. 
Thank you!

**Comment by AlexanderPan** [comment] 2021-08-19 10:33
@schmittsfn Thanks! That works for me!

**Comment by samedson** [comment] 2021-08-19 17:49
For folks that have been renaming their dSYM UUID, are you finding that the resulting stacktraces are correct?

My worry is that the dSYM is actually for the app before it's been recompiled via bitcode, which would mean even though the UUID matches up, the stacktrace could be incorrect.

You may find in Crashlytics, if you page back to your less frequent issues, there are some incorrect looking ones, but I'm curious what folks are finding.

**Comment by schmittsfn** [comment] 2021-08-19 18:08
@samedson on our side they are. We have bitcode enabled and only rename those dsyms which correspond to the build crashlytics is receiving crashes for. For most people those builds are most likely builds built on Apple's servers if you have bitcode enabled.

One has to be very careful on which dsyms one applies the renaming. e.g. your app's binary image will have dsyms in each local archive and/or .zip file downloaded via apstoreconnect.

I haven't dared to try this out personally but I can imagine that should you rename a dsym from a build that doesn't match the one Crashlytics is requesting it will most likely silence the warning, but result in gibberish stack traces.

**Comment by schmittsfn** [comment] 2021-08-19 18:22
@samedson 
> Also, Crashlytics is aware of this issue and actively working to solve it. We're finding that this impacts crashes symbolicated via Xcode Organizer as well.
That's very interesting. Would you be ok to share your source? That way we have a reference to it in this thread for future answer seeking devs.

**Comment by samedson** [comment] 2021-08-19 19:20
Yeah we're following a thread here on Apple's forums: [Thread Message](https://developer.apple.com/forums/thread/686310?answerId=684235022#684235022)

**Comment by mathaeus** [comment] 2021-08-30 05:15
> I was wondering: for folks who have rewritten their UUIDs, have you inspected your stacktraces? Do they look correct for the most part?

@samedson from what I can see, yes they look correct.

**Comment by iPhoneNoobDeveloper** [comment] 2021-08-31 07:32
> We're still working with the involved parties to resolve the issue.
> 
> I was wondering: for folks who have rewritten their UUIDs, have you inspected your stacktraces? Do they look correct for the most part?

I have cooked the new dSYM file with steps mentioned by @duyquang91 but it shows crashes in different view controller. It just shows random controller for the fatal crashes. Also, My Project dSYM file contains two different UUIDs for armv7 and arm64 hence it's baffling me to cook new dSYM based on the given solution above.

**Comment by schmittsfn** [comment] 2021-08-31 07:40
> > We're still working with the involved parties to resolve the issue.
> 
> > 
> 
> > I was wondering: for folks who have rewritten their UUIDs, have you inspected your stacktraces? Do they look correct for the most part?
> 
> 
> 
> I have cooked the new dSYM file with steps mentioned by @duyquang91 but it shows crashes in different view controller. It just shows random controller for the fatal crashes. Also, My Project dSYM file contains two different UUIDs for armv7 and arm64 hence it's baffling me to cook new dSYM based on the given solution above.

Do you have Bitcode enabled?
What platforms are you supporting?
And what is your supported version range? 
I'm wondering why you have several architectures.

**Comment by iPhoneNoobDeveloper** [comment] 2021-09-01 07:40
> > > We're still working with the involved parties to resolve the issue.
> > 
> > 
> > > 
> > 
> > 
> > > I was wondering: for folks who have rewritten their UUIDs, have you inspected your stacktraces? Do they look correct for the most part?
> > 
> > 
> > I have cooked the new dSYM file with steps mentioned by @duyquang91 but it shows crashes in different view controller. It just shows random controller for the fatal crashes. Also, My Project dSYM file contains two different UUIDs for armv7 and arm64 hence it's baffling me to cook new dSYM based on the given solution above.
> 
> @iPhoneNoobDeveloper
> Do you have Bitcode enabled? - Yes, Bitcode is enabled
> What platforms are you supporting? - iOS 
> And what is your supported version range? iOS 10 and later 
> I'm wondering why you have several architectures. This is to handle older devices and other third party SDKs who supports these standard architectures(arm64 & armv7)

**Comment by duyquang91** [comment] 2021-09-06 07:15
Seems like the problem has been fixed by Apple. It works well on my side now.

**Comment by elenadoty** [comment] 2021-09-08 14:31
Glad to hear this seems to have been resolved, but feel free to reopen if you're still affected.

**Closed by elenadoty** 2021-09-08 14:31 UTC
Labels: api: crashlytics
