### ISSUE TITLE
messaging(_ messaging, didReceiveRegistrationToken) not called at first app start if Surfshark VPN is enabled

### ISSUE THREAD

**Issue by artembolotov** [firebase/firebase-ios-sdk#9910] opened 2022-06-15 05:22 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 9.1.0
  * Installation method: Swift Package Manager
  * Firebase Component: Messaging
  * Target platform(s): iOS

#### Steps to reproduce:

Connect to Surfshark VPN (may be not only this), remove the app and install it again. Messaging(_ messaging, didReceiveRegistrationToken) will not be called. If you try to get token manually via Messaging.messaging().token(completion: ) you will get error "Could not connect to server". You can close app, open it again — didReceiveRegistrationToken still not be called. After disconnect VPN, all be fine even you connect them again.
#### Relevant Code:

```
func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
    guard Auth.auth().currentUser != nil, let fcmToken = fcmToken else { return }      
    FCMToken.updateCloud(newFCMToken: fcmToken)
}
```

**Comment by rizafran** [comment] 2022-06-15 14:41
Hi @artembolotov, I'm unable to reproduce the issue without VPN. It looks like you're running into network issues with VPN services. You need to configure it to allow mobile devices to connect with FCM in order for them to receive messages. FCM usually uses ports 5228, 5229, and 5230. You may check this [page](https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall) for more details regarding FCM ports.

**Comment by artembolotov** [comment] 2022-06-16 06:18
You can reproduce the issue if enable CleanWeb feature in SurfShark VPN (which block ads and trackers)

**Comment by artembolotov** [comment] 2022-06-16 14:59
![image](https://user-images.githubusercontent.com/13273821/174099367-edac8b7c-7039-46e3-a942-2988ab31a548.png)
Success, not blocked

**Comment by ryanwilson** [comment] 2022-06-16 15:09
@artembolotov in particular, can you try the register endpoint? If that still succeeds, we'd need more information from the error (ideally we can see the underlying NSURLSession error).

**Comment by artembolotov** [comment] 2022-06-16 16:12
I set this breakpoint and this functions wasn't called when VPN is enabled.
![image](https://user-images.githubusercontent.com/13273821/174116938-97e76946-40b9-4801-9f9f-2eab7d1ccb5c.png)

**Comment by artembolotov** [comment] 2022-06-17 04:54
This URL is blocked https://device-provisioning.googleapis.com/checkin

**Comment by ryanwilson** [comment] 2022-06-17 12:27
Thanks for finding that. Communicating with this endpoint is required for Messaging to function correctly (cc @leojaygoogle to correct me if I'm wrong). Since it works correctly without a VPN, I'm going to close this issue but we can continue discussing as needed. 

I'd recommend reaching out to the VPN provider and mentioning the specific endpoint causes issues with push notifications using Firebase Messaging.

**Closed by ryanwilson** 2022-06-17 12:27 UTC
Labels: api: messaging
