### ISSUE TITLE
upload-symbols doesn't give usage information when run with no arguments

### ISSUE THREAD

**Issue by crspybits** [firebase/firebase-ios-sdk#7764] opened 2021-03-20 17:55 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Installation method: `CocoaPods | Carthage | Zip file | Swift Package Manager` (select one)
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

From: https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md this indicates:
"Another option is to use the upload-symbols script. Place it in the directory where your .xcodeproj file lives, eg. scripts/upload-symbols, and make sure that the file is executable: chmod +x scripts/upload-symbols. This script can be used to manually upload dSYM files (for usage notes and additional instructions, run without any parameters)."

When I run `upload-symbols`, it says:

```
MacBook-Pro-4:Neebla chris$ ./upload-symbols 
error: No Google App ID or Google Services file provided
```

**Comment by rizafran** [comment] 2021-03-22 11:12
Hi @crspybits, have you tried to explicitly pass the GoogleService file? If not, you could try:
`/path/to/upload-symbols -gsp /path/to/GoogleService-Info.plist -p ios /path/to/dSYMs
`

You may also check this [link](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports#upload-dsyms) for reference.

**Comment by paulb777** [comment] 2021-03-23 19:12
I can reproduce, so there is at least a documentation bug here, since running without options doesn't provide the usage notes.

**Comment by samedson** [comment] 2021-04-06 15:36
Thanks for calling this out @crspybits - documentation should be fixed now!

**Closed** 2021-04-06 15:35 UTC
Labels: api: crashlytics
