### ISSUE TITLE
Cannot contact reCAPTCHA, Check your connection and try again

### ISSUE THREAD

**Issue by ControlAndC** [firebase/firebase-ios-sdk#9013] opened 2021-11-25 16:55 UTC
I have implemented firebase auth in my project, and it is getting rejected on iTunes.
  
  They provided me attached screenshot, Can you please let me know what is the reason behind it.
  
  At my side it is working fine but iTunes testing continuously failing, Please help  

![image](https://user-images.githubusercontent.com/5564601/143479385-96929a15-2a75-4c9a-b240-4e8ca0cb5589.png)

**Comment by rizafran** [comment] 2021-11-25 20:25
Thanks for reporting, @ControlAndC. I tried reproducing the issue, but my reCAPTCHA is working fine. Could you provide the following details so we could investigate it:
- Firebase SDK version used
- Confirmation if you have tried the solution [here](https://stackoverflow.com/questions/69909351/firebase-ios-15-cannot-contact-recaptcha-check-your-connection-and-try-again) 
- Confirmation if the issue is reproducible using other network or browser
- Stack trace of the error you're receiving (if there's any)

**Comment by ControlAndC** [comment] 2021-11-26 04:48
I am using React-native -firebase version -     "@react-native-firebase/app": "^8.4.7".

I have no place to change above help link code as my AppDelegate.M is different from what i saw in above help link.

Here is my AppDelegate.M file, Please look at it and provide any solution.

`/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"
#import <RNShareMenu/ShareMenuManager.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#if RCT_DEV
#import <React/RCTDevLoadingView.h>
#endif
#import <Firebase.h>
#import "RNFirebaseMessaging.h"
#import "RNFirebaseNotifications.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  [FIRApp configure];
  [RNFirebaseNotifications configure];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
#if RCT_DEV
  [bridge moduleForClass:[RCTDevLoadingView class]];
#endif
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"gyfthint"
                                            initialProperties:nil];
//  if (@available(iOS 13.0, *)) {
//         rootView.overrideUserInterfaceStyle = UIUserInterfaceStyleLight;
//     }
  if (@available(iOS 14, *)) {
      UIDatePicker *picker = [UIDatePicker appearance];
      picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
   }
  // rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:0.18 green:0.14 blue:0.23 alpha:1];


  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  return YES;
}


    - (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
    {
      return [ShareMenuManager application:app openURL:url options:options];
    }


- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[RNFirebaseNotifications instance] didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}



- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

@end
`

**Comment by rizafran** [comment] 2021-11-26 15:26
Thanks for sharing the details, @ControlAndC. This seems like a react-native integration issue and might be better if addressed to [React Native repo](https://github.com/invertase/react-native-firebase/issues). I also noticed that you have filed an [issue](https://github.com/invertase/react-native-firebase/issues/5882) in the said repo. As mentioned there by the engineer, you can try upgrading your SDK to the latest version and see if you'll still encounter the issue. With this, I'm going to close the issue for now.

**Closed by rizafran** 2021-11-26 15:26 UTC
Labels: api: auth, needs-attention, react-native
