### ISSUE TITLE
Archive fails in FirebaseCoreDiagnostics with "Could not build module GoogleUtilities" Xcode 10.3 Firebase 6.8.1

### ISSUE THREAD

**Issue by roma86** [firebase/firebase-ios-sdk#3886] opened 2019-09-19 11:46 UTC
**[REQUIRED] Step 2: Describe your environment**

  * Xcode version: 10.3
  * Firebase SDK version: 6.8.1
  * Podifle:
```
    pod 'Firebase/Performance'
    pod 'Firebase'
```

  * pod update output:
```
...
Using Crashlytics (3.14.0)
Using Fabric (1.10.2)
Installing Firebase 6.8.1
Installing FirebaseABTesting (3.1.1)
Using FirebaseAnalytics (6.1.1)
Installing FirebaseAnalyticsInterop (1.4.0)
Using FirebaseCore (6.2.3)
Using FirebaseCoreDiagnostics (1.0.1)
Using FirebaseCoreDiagnosticsInterop (1.0.0)
Using FirebaseInstanceID (4.2.5)
Installing FirebasePerformance (3.1.4)
Installing FirebaseRemoteConfig (4.4.0)
Installing GTMSessionFetcher (1.2.2)
Using GoogleAppMeasurement (6.1.1)
Using GoogleDataTransport (1.2.0)
Using GoogleDataTransportCCTSupport (1.0.4)
Using GoogleMaps (3.4.0)
Using GooglePlaces (3.4.0)
Installing GoogleToolboxForMac (2.2.1)
Installing GoogleUtilities 6.3.0
Using ObjcExceptionBridging (1.0.1)
Installing Protobuf (3.9.0)
...

```

**[REQUIRED] Step 3: Describe the problem**

## Application builds and runs on device and simulator, but failed on Archiving.

![archiving output](https://d1ro8r1rbfn3jf.cloudfront.net/ms_7588/aJBBuxlSDqqtJUYYcQInBlk6qHiOOv/Podfile%2B2019-09-19%2B14-16-06.png?Expires=1568892600&Signature=oiS5AzLT9ZB3ZBJEBZOCIvKg5HABNcKsxG1pOvOnQJhx5B7gMfN5HFWlMj14pOsYRVDqyVNEsYHH3YBjCiEGU8UDfG5MrOEaJSKt3ZzEXvSuHXxY6ymxwDwULyttXWzUo2QqQqYUxxFfJW4b4hSG2-f-VwNn7YSbXQWl-RhqdhYnm3Ku1uofmvXocheNY3YsE9GLbcQkD73oGW8TlaIEvgxdN1Aj99gsGr~20XTdPir0PF2bQA1tkbfcDMGxG9L8qpD1MSH-QIEbhlwXzhmHB4Cn4GJFQhaZgRmcgzq4G1PCA5PUXQ03mBAEZ9xFUECL6e6HIr4pyqHbVlHPlMyD7A__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA)

**Steps to reproduce:**  

1. Podfile:
```
Podfile:

    pod 'Firebase/Performance'
    pod 'Firebase'
    pod 'Fabric'
    pod 'Crashlytics'

```

2. Product / Archive

**What i tried:**  
1. Remove `Pods` and `Podfile.lock` and `pod update`
2. Remove `DerivedData` folder and repeat step 1
3. Cried
4. Laughed
5. Remove pods Firebase, 'Firebase/Performance, Fabric and Crashlytics, `pod update`. In this case Archiving works.

**Comment by paulb777** [comment] 2019-09-20 17:15
How does it fail?  The output attachment gives a 403 error. Perhaps a duplicate of #3884?

**Comment by paulb777** [comment] 2019-09-21 13:01
Looks like a problem with the Swift compiler or the SwiftSoup pod. See #3884.

**Closed by paulb777** 2019-09-21 13:01 UTC
Labels: Infrastructure, needs-info
