### ISSUE TITLE
SPM can't find firebase dependencies

### ISSUE THREAD

**Issue by StarLard** [firebase/firebase-ios-sdk#6357] opened 2020-08-28 04:56 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 12.0 beta 6 (12A8189n)
  * Firebase SDK version: 6.31-spm-beta
  * Firebase Component: Auth, Core, Analytics, Firestore
  * Component version: 6.31-spm-beta
  * Installation method: Swift Package Manager

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

When attempting to include Firebase SDK as dependency through SPM...

Expected:
Xcode finds and includes the products.

Actual:
Xcode will generate error: "produce dependency 'FirebaseProductNameXYZ' in package 'firebase-ios-sdk' not found" for each product listed in dependencies.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
let package = Package(
    name: "SomePackage",
    platforms: [ .iOS(.v14), .macOS(.v11), .tvOS(.v14) ],
    products: [
        .library(
            name: "SomePackage",
            targets: ["SomePackage"]),
    ],
    dependencies: [
        .package(url: "https://github.com/firebase/firebase-ios-sdk.git", .branch("6.31-spm-beta"))
    ],
    targets: [
        .target(
            name: "SomePackage",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk", condition: .when(platforms: [.iOS])),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseCore", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFirestore", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFirestoreSwift", package: "firebase-ios-sdk"),
            ],
        )
        .testTarget(
            name: "SomePackageTests",
            dependencies: ["SomePackage"]),
    ]
)

```

**Comment by ryanwilson** [comment] 2020-08-28 14:09
Thanks for the report @StarLard - there were a few issues with the copy/pasted code (like a missing `)` to close the `.target(` but after I cleaned it up I was able to reproduce the issue. I'm not sure exactly why that's the case though, it looks like that should be the correct default name: https://github.com/apple/swift-package-manager/blob/96b0ff907fdd4d91fcd207f4c49aae4fce1d9ec5/Sources/PackageModel/Package.swift#L140-L161

Regardless, a workaround for now is to add `name: "Firebase"` to the `.package` in the `dependencies` argument before the `url`, then change to `package: "Firebase"` for each `product` in the target itself.

Funnily enough, even explicitly adding `name: "firebase-ios-sdk"` instead of `name: "Firebase"` also fails for me so I'll have to see if I can figure out what's going on there.

**Comment by ryanwilson** [comment] 2020-08-28 14:36
Follow up:

It looks like this is working as intended based on this package resolution code:
https://github.com/apple/swift-package-manager/blob/6f469cf0c7c03591ac0723baa134b5d42855e3c1/Sources/PackageGraph/PackageGraphLoader.swift#L327-L338

(shout out to Swift Package Manager for being open source).

I'm going to post on the forums asking about this because it's unclear to me what this means if you have two different dependencies that offer the same package name. Need to do a bit more reading on [SE-0226](https://forums.swift.org/t/se-0226-package-manager-target-based-dependency-resolution/15404/12), then after I get that posted, I'll close this issue since we have the right method.

**Comment by StarLard** [comment] 2020-08-28 16:02
Thanks for the quick reply Ryan! I'll give that a try.

**Comment by ryanwilson** [comment] 2020-09-18 14:53
Finally added a note to the Swift forums with a repro, showing that it's impossible to have two dependencies with the same package name. https://forums.swift.org/t/cant-consume-two-swift-packages-with-the-same-name/40408. I'll update the instructions for us then close this bug, thanks!

**Closed** 2020-09-18 16:11 UTC
Labels: Swift Package Manager, beta-software
