### ISSUE TITLE
addStateDidChangeListener not called after login

### ISSUE THREAD

**Issue by revolter** [firebase/firebase-ios-sdk#689] opened 2018-01-21 01:05 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: `9.2 (9C40b)`
  * Firebase SDK version: `4.8.1`
  * Firebase Component: `Auth` (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: `4.8.1`

### [REQUIRED] Step 3: Describe the problem

I am registering an `addStateDidChangeListener` in my `AppDelegate`, but it's only called once.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

- Fresh install the app
- Listener called with `nil` user
- Log in
- Listener is not called

#### Relevant Code:

`AppDelegate.swift`:
```swift
Auth.auth().addStateDidChangeListener() { (auth, firebaseUser) in
	if let firebaseUser = firebaseUser {
		print("logged in")
	} else {
		print("not logged int")
	}
}
```

`AccountViewController.swift`:
```swift
var firebaseUIAuth: FUIAuth?

override func viewDidLoad() {
	if let facebookAccessToken = FBSDKAccessToken.current()?.tokenString, let firebaseUser = Auth.auth().currentUser {
		print("already logged in")
	} else {
		self.firebaseUIAuth = FUIAuth.defaultAuthUI()

		self.firebaseUIAuth?.delegate = self

		self.firebaseUIAuth?.providers = [FUIFacebookAuth()]

		if let authViewController = self.firebaseUIAuth?.authViewController() {
			self.present(authViewController, animated: false, completion: nil)
		}
	}
}
```

**Comment by revolter** [comment] 2018-01-21 17:35
@paulb777, Any idea on this one?

**Comment by revolter** [comment] 2018-01-21 21:37
It worked correctly in Firebase/Auth version `3.10.0` and stopped working when I updated to `4.8.1`.

**Comment by paulb777** [comment] 2018-01-21 22:20
@morganchen12 or @protocol86 PTAL

**Comment by revolter** [comment] 2018-01-22 20:27
Actually, updating `FirebaseUI/Facebook` (and implicitly `FirebaseUI/Auth`) from version `1.0.0` to `2.0.0` breaks it.

**Comment by revolter** [comment] 2018-01-22 20:31
Sadly, the repo didn't have a `Podfile.lock` at [that time](https://github.com/firebase/FirebaseUI-iOS/tree/b889eef20f7c1eb600d67a6d1be208c55ff5b1ff), so I don't know which `Firebase/Auth` version broke it.

**Comment by revolter** [comment] 2018-01-25 21:37
@protocol86, Any updates for this one?

**Comment by protocol86** [comment] 2018-01-26 07:04
Happy to take a look. I am actually not able to reproduce this issue, can you verify that sign-in is successful?

**Comment by revolter** [comment] 2018-01-26 18:10
Having:

```swift
func authUI(_ authUI: FUIAuth, didSignInWith user: User?, error: Error?) {
	print(user ?? "no user")
	print(error ?? "no error")
}
```
in `AccountViewController.swift` prints:

> <FIRUser: 0x6000000d3f60>
> no error

**Comment by revolter** [comment] 2018-01-27 19:36
It looks like maybe

> Changes auth state change listener to only be triggered when the user changes.

from [version 4.0.0](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Auth/CHANGELOG.md#2017-05-17----v400) might cause this.

**Comment by paulb777** [comment] 2018-05-04 13:50
Closing for staleness. Reopen with new information.

**Closed by paulb777** 2018-05-04 13:50 UTC
Labels: Auth

**Comment by QuantumThom** [comment] 2019-10-15 04:19
Im having this same problem did anyone figure it out?

**Comment by QuantumThom** [comment] 2019-10-15 04:20
with the auth().addStateChangeListener
