### ISSUE TITLE
Expect to get the same installationID after reinstalling the application

### ISSUE THREAD

**Issue by LightHouse2013** [firebase/firebase-ios-sdk#10421] opened 2022-10-31 08:46 UTC
### Description

installation id was changed after reinstall the app.
lead to firebase MAU/DAU more than the actual device/user number.

### Reproducing the issue

Step:
- build and run Xcode project, install app
- xcode console log: "fid":"xxxx"
- uninstall app from iPhone
- rebuild Xcode project, console log: "fid":"xxxx2"

Result: 
- fid was changed after reinstall.

Code:
- Module:  FirebaseInstallations
- File: FIRInstallationsStore
- Line: 61

- installation flag saved at user default, installation id saved at keychain；
- installation flag was removed when uninstall app，so not to read keychain installation id，but createAndSaveFID another one.

Expect:
- direct get keychain`s installation id.
- If creating a new id after reinstallation is a feature, can I modify the code to use the installation id in the keychain?

``` 
- (FBLPromise<FIRInstallationsItem *> *)installationForAppID:(NSString *)appID
                                                     appName:(NSString *)appName {
  NSString *itemID = [FIRInstallationsItem identifierWithAppID:appID appName:appName];
  return [self installationExistsForAppID:appID appName:appName]
      .then(^id(id result) {
        return [self.secureStorage getObjectForKey:itemID
                                       objectClass:[FIRInstallationsStoredItem class]
                                       accessGroup:self.accessGroup];
      })
      .then(^id(FIRInstallationsStoredItem *_Nullable storedItem) {
        if (storedItem == nil) {
          return [FIRInstallationsErrorUtil installationItemNotFoundForAppID:appID appName:appName];
        }
        FIRInstallationsItem *item = [[FIRInstallationsItem alloc] initWithAppID:appID
                                                                 firebaseAppName:appName];
        [item updateWithStoredItem:storedItem];
        return item;
      });
}
```

### Firebase SDK Version

10.1.0

### Xcode Version

13.4.1

### Installation Method

CocoaPods

### Firebase Product(s)

Installations

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[FirebaseInstallations][I-FIS001001] Sending request body:{"appId":"xxx","fid":"fO5FnH2Z7U6xxxx"
```

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

  pod 'Firebase', '~> 10.1'
  pod 'FirebaseCrashlytics', '~> 10.1'
  pod 'FirebaseAnalytics', '~> 10.1'
  pod 'FirebaseInstallations', '~> 10.1'
  pod 'FirebasePerformance', '~> 10.1'

```

</details>

**Comment by morganchen12** [comment] 2022-10-31 20:28
hey @LightHouse2013, Firebase Installations is designed to anonymously identify installations, not users. If a user installs your app multiple times then Installations will count multiple installations. Installations cannot change this behavior without privacy implications (this effectively becomes a device ID on the level of the advertising ID). Also, even with that behavior, a user could install your app on multiple devices, meaning your user count would still be inaccurate.

Have you considered [setting a user ID](https://firebase.google.com/docs/analytics/userid) instead?

**Comment by ncooke3** [comment] 2022-10-31 20:33
Closing as this is intended behavior.

**Closed by ncooke3** 2022-10-31 20:33 UTC
Labels: wontfix, api: installations
