### ISSUE TITLE
Error installing Firebase

### ISSUE THREAD

**Issue by hectorsvill** [firebase/firebase-ios-sdk#4604] opened 2020-01-07 05:25 UTC
* Xcode version: 11.3
  * Firebase SDK version: 6.14.0
  * Firebase Component:  Core, Firestore, 
  * CocoaPods Version 1.8.4

- pod install produces this error
- pod update produces this error 
- tried to uninstall and reinstall cocoapods
- tried to change version of pods all the way down to 6.3.1

```
[!] Error installing Firebase
[!] /usr/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/r8/xnt547491w910gvc98t14c_h0000gn/T/d20200106-47847-9yvu5c --template= --single-branch --depth 1 --branch 6.14.0
Cloning into '/var/folders/r8/xnt547491w910gvc98t14c_h0000gn/T/d20200106-47847-9yvu5c'...
Note: checking out '20ab31fe130e9a1d22a75b35ba7046cfba0e5a47'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
fatal: No url found for submodule path 'Firestore/Example/App/Testing' in .gitmodules
```

**Comment by morganchen12** [comment] 2020-01-07 08:23
What version of CocoaPods are you using?

**Comment by hectorsvill** [comment] 2020-01-07 16:34
> What version of CocoaPods are you using?

version 1.8.4

**Comment by paulb777** [comment] 2020-01-07 16:40
Most likely is something about the particular machine's environment.  Please share the Podfile and if created the Podfile.lock.  Also, make sure you do a `pod update` or `pod install --repo-update`

**Comment by hectorsvill** [comment] 2020-01-07 16:46
> Most likely is something about the particular machine's environment. Please share the Podfile and if created the Podfile.lock. Also, make sure you do a `pod update` or `pod install --repo-update`

Podfile.lock
```
PODFILE CHECKSUM: a856d6c8f2fb5aae0b2852a1b992da135652d9c6

COCOAPODS: 1.8.4
```

Podfile
```
target 'TestFirebase' do

  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end

```
I created another user account on my machine and Cocoapods work just fine. So you must be right.

**Comment by paulb777** [comment] 2020-01-07 17:24
Sounds good.  I'm going to close the issue now, but feel free to follow up if you have additional questions and/or want to share the root cause.

**Closed by paulb777** 2020-01-07 17:24 UTC
Labels: needs-attention, type: question
