### ISSUE TITLE
MemoryLeaks on GULObjectSwizzler

### ISSUE THREAD

**Issue by hsPark1** [firebase/firebase-ios-sdk#2421] opened 2019-02-22 06:59 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _10.1_
  * Firebase SDK version: _5.16.0_
  * Firebase Component: _Core, DynamicLinks, RemoteConfig, Performance_
  * Component version: _5.16.0_

### [REQUIRED] Step 3: Describe the problem
Memory leaks on GULObjectSwizzler
#### Relevant Code:
<img width="1040" alt="2019-02-22 3 58 10" src="https://user-images.githubusercontent.com/47730829/53225229-add8e300-36ba-11e9-9db9-3c7619ac8b9e.png">

**Comment by maksymmalyhin** [comment] 2019-02-28 19:14
@hsPark1 Thank you for reporting the issue. Would you be able to share a simple test project or at least a code snippet to reproduce the issue?

The ivar `_generatedClass` is deallocated by on `-[GULObjectSwizzler dealloc]` using `objc_disposeClassPair(_generatedClass);`. I could not find a case when `_generatedClass` was leaking after `GULObjectSwizzler` deallocation.

It looks like `GULObjectSwizzler` instances are involved into a retain cycle their-self.

**Comment by paulb777** [comment] 2019-03-11 14:19
Closing for now. Will reopen with a reproducible example.

**Closed by paulb777** 2019-03-11 14:19 UTC
Labels: GoogleUtilities

**Comment by kyleturner** [comment] 2019-05-03 14:52
Following up and confirming, @maksymmalyhin @paulb777 we too are seeing this exact same memory leak with the same specs @hsPark1 reported. 

![Screen Shot 2019-05-03 at 8 38 26 AM](https://user-images.githubusercontent.com/283362/57144696-d813e480-6d7e-11e9-9dbd-d93168560ad6.png)

**Comment by maksymmalyhin** [comment] 2019-05-03 15:02
@kyleturner Thank you for the update. Would you be able to share a test project please?

**Comment by pk123hk2003** [comment] 2019-07-01 18:45
Any update in regard of this issue? We too are getting a memory leak from GULObjectSwizzler class.

Our app make use of a URLSession object and at the end, we ensure the we called invalidateAndCancel for the session. 

![image](https://user-images.githubusercontent.com/6550263/60459245-7b556e80-9bf5-11e9-8f5a-feab3f959363.png)

It shows that session is being retain by GULObjectSwizzler.m (-[GULObjectSwizzler initWithObject:])

![Screen Shot 2019-07-01 at 11 36 43 AM](https://user-images.githubusercontent.com/6550263/60459066-041fda80-9bf5-11e9-848b-98150b3871e1.png)

Firebase analytics version: 

  - FirebaseAnalytics (6.0.1):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.1)
    - GoogleAppMeasurement (= 6.0.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
