### ISSUE TITLE
App crashes when it goes offline

### ISSUE THREAD

**Issue by Nathan1258** [firebase/firebase-ios-sdk#3533] opened 2019-08-08 12:45 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.6.0
  * Firebase Component: GoogleDataTransportCCTSupport
  * Component version: 1.0.0

### [REQUIRED] Step 3: Describe the problem
I have an app that requires the user to leave the app to connect to another device's wifi network. However, when I change to that wifi network and come back to the app (go offline), it seems as if Firebase or 'Google Data transport support' crashes the app saying 'there's no internet connection' when I already know there's no connection.

#### Steps to reproduce:
Open the app connected to wifi, come off app, switch off wifi and go back to the app. The app will crash

#### Relevant Code:

Crash Log:

`Assertion failure in -[GDTCCTUploader uploadPackage:], /Users/nathan/OneDrive/Memories/app_project/Memories/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m:97

There should be no errors uploading events: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x281cddfe0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://firebaselogging.googleapis.com/v0cc/log/batch, NSErrorFailingURLKey=https://firebaselogging.googleapis.com/v0cc/log/batch, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}
(null)`

Code where it occurs:

`(void)uploadPackage:(GDTUploadPackage *)package {

  dispatch_async(_uploaderQueue, ^{

    NSAssert(!self->_currentTask, @"An upload shouldn't be initiated with another in progress.");

    NSAssert(!self->_currentUploadPackage, @"An upload shouldn't be initiated with a new package.");

    NSURL *serverURL = self.serverURL ? self.serverURL : [self defaultServerURL];

    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:serverURL];

    request.HTTPMethod = @"POST";

 

    id completionHandler =

        ^(NSData *_Nullable data, NSURLResponse *_Nullable response, NSError *_Nullable error) {

          NSAssert(!error, @"There should be no errors uploading events: %@", error);

          NSError *decodingError;

          gdt_cct_LogResponse logResponse = GDTCCTDecodeLogResponse(data, &decodingError);

          if (!decodingError && logResponse.has_next_request_wait_millis) {

            self->_nextUploadTime =

                [GDTClock clockSnapshotInTheFuture:logResponse.next_request_wait_millis];

          } else {

            // 15 minutes from now.

            self->_nextUploadTime = [GDTClock clockSnapshotInTheFuture:15 * 60 * 1000];

          }

          pb_release(gdt_cct_LogResponse_fields, &logResponse);

          [package completeDelivery];

          if (self->_backgroundID != GDTBackgroundIdentifierInvalid) {

            [[GDTApplication sharedApplication] endBackgroundTask:self->_backgroundID];

            self->_backgroundID = GDTBackgroundIdentifierInvalid;

          }

          self.currentTask = nil;`

**Comment by Nathan1258** [comment] 2019-08-08 12:51
It's a stupid issue, I can't proceed with my app because this keeps on happening and I can't control it in any way. Is there a work around??

**Comment by Nathan1258** [comment] 2019-08-08 12:53
Go here for more context with someone with more knowledge with me explaining why it's horrible code.

**Comment by paulb777** [comment] 2019-08-08 14:09
Duplicate of #3530. Please continue discussion there.

**Closed by paulb777** 2019-08-08 14:09 UTC
Labels: needs-triage
