### ISSUE TITLE
SwiftUI preview in Xcode 13.4 crashes due to uncaught exception in Firebase

### ISSUE THREAD

**Issue by LukasCZ** [firebase/firebase-ios-sdk#9916] opened 2022-06-17 09:51 UTC
### Step 1: Describe your environment

  * Xcode version: 13.4
  * Firebase SDK version: 9.1.0
  * Installation method: CocoaPods
  * Firebase Component: Crashlytics
  * Target platform(s): `iOS | watchOS`

### Step 2: Describe the problem

I recently wanted to start using SwiftUI in my Xcode app, but I'm unable to because Firebase keeps crashing the SwiftUI previews every time I make a change. It'd be great if this could be resolved and/or fixed soon because it is pretty much preventing me from using SwiftUI in my iOS app.

I don't think that my setup is unusual in any way. I'm using CocoaPods to integrate 'Firebase/Crashlytics'. Most of my codebase is Objective-C, but I'm also using a fair amount of Swift, and SwiftUI for the watch app. My project builds correctly when building for a simulator or a real device, so this is really specific to SwiftUI previews.

#### Crash stack trace:

CrashReportError: Timelines crashed due to an uncaught exception

Timelines crashed due to an uncaught exception `NSInvalidArgumentException`. Reason: -[FBLPromise HTTPBody]: unrecognized selector sent to instance 0x600003a33420.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 82E5BE04-AB2A-49CE-99DC-029F92697858
CrashReporter Key:   C817B438-FEC3-DFB8-3E5A-9B3C3BA96008
Hardware Model:      MacBookPro16,1
Process:             Timelines [17952]
Path:                /Users/USER/Library/Developer/Xcode/UserData/Previews/Simulator Devices/17B644D6-84B5-4731-87D0-4AEFA055FDD9/data/Containers/Bundle/Application/40FD9DBD-718B-4FEE-AB47-155D847439F9/Timelines.app/Timelines
Identifier:          com.glimsoft.Timelines
Version:             3.0 (3.0.0.8)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [13963]
Coalition:           com.apple.CoreSimulator.SimDevice.17B644D6-84B5-4731-87D0-4AEFA055FDD9 [1594]
Responsible Process: SimulatorTrampoline [731]

Date/Time:           2022-06-17 11:40:22.6332 +0200
Launch Time:         2022-06-17 11:40:21.6484 +0200
OS Version:          macOS 12.4 (21F79)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  3

Thread 0::  Dispatch queue: com.google.firebase.crashlytics.ios.exception
0   libsystem_kernel.dylib        	    0x7fff7016d3a2 close + 10
1   Timelines                     	       0x10c628bca FIRCLSFileCloseWithOffset + 154
2   Timelines                     	       0x10c628b19 FIRCLSFileClose + 25
3   Timelines                     	       0x10c62293a __FIRCLSExceptionRecord_block_invoke + 154
4   libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
5   libdispatch.dylib             	    0x7fff20123cfd _dispatch_lane_barrier_sync_invoke_and_complete + 94
6   Timelines                     	       0x10c620650 FIRCLSExceptionRecord + 336
7   Timelines                     	       0x10c621f00 FIRCLSExceptionRecordNSException + 1088
8   Timelines                     	       0x10c622ba8 FIRCLSCatchAndRecordActiveException(std::type_info*) + 184
9   Timelines                     	       0x10c620174 FIRCLSTerminateHandler() + 244
10  libc++abi.dylib               	    0x7fff202599c7 std::__terminate(void (*)()) + 8
11  libc++abi.dylib               	    0x7fff20259978 std::terminate() + 56
12  libdispatch.dylib             	    0x7fff20115b39 _dispatch_client_callout + 28
13  libdispatch.dylib             	    0x7fff201230a4 _dispatch_main_queue_drain + 1147
14  libdispatch.dylib             	    0x7fff20122c1b _dispatch_main_queue_callback_4CF + 31
15  CoreFoundation                	    0x7fff20371ed5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
16  CoreFoundation                	    0x7fff2036c6ca __CFRunLoopRun + 2761
17  CoreFoundation                	    0x7fff2036b704 CFRunLoopRunSpecific + 562
18  GraphicsServices              	    0x7fff2cba9c8e GSEventRunModal + 139
19  UIKitCore                     	    0x7fff2509e65a -[UIApplication _run] + 928
20  UIKitCore                     	    0x7fff250a32b5 UIApplicationMain + 101
21  Timelines                     	       0x10c3785b0 main + 96 (main.m:14)
22  dyld_sim                      	       0x10d014f21 start_sim + 10
23  dyld                          	       0x1168f351e start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 2::  Dispatch queue: com.google.firebase.crashlytics.ios.binary-images
0   dyld_sim                      	       0x10d0366c3 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 91
1   dyld_sim                      	       0x10d036f3a dyld3::MachOFile::forEachSegment(void (dyld3::MachOFile::SegmentInfo const&, bool&) block_pointer) const + 154
2   dyld_sim                      	       0x10d0241d3 dyld4::JustInTimeLoader::contains(dyld4::RuntimeState&, void const*, void const**, unsigned long long*, unsigned char*) const + 177
3   dyld_sim                      	       0x10d02c995 invocation function for block in dyld4::APIs::findImageMappedAt(void const*, dyld3::MachOLoaded const**, bool*, char const**, void const**, unsigned long long*, unsigned char*) + 120
4   dyld_sim                      	       0x10d018515 dyld4::RuntimeState::withLoadersReadLock(void () block_pointer) + 41
5   dyld_sim                      	       0x10d02c8be dyld4::APIs::findImageMappedAt(void const*, dyld3::MachOLoaded const**, bool*, char const**, void const**, unsigned long long*, unsigned char*) + 596
6   dyld_sim                      	       0x10d02cd64 dyld4::APIs::dladdr(void const*, dl_info*) + 168
7   Timelines                     	       0x10c630f9a FIRCLSMachOSliceGetExecutablePath + 58
8   Timelines                     	       0x10c61339e FIRCLSBinaryImageRecordSlice + 158
9   Timelines                     	       0x10c6130d5 __FIRCLSBinaryImageChanged_block_invoke + 213
10  libdispatch.dylib             	    0x7fff201148e4 _dispatch_call_block_and_release + 12
11  libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
12  libdispatch.dylib             	    0x7fff2011c0df _dispatch_lane_serial_drain + 753
13  libdispatch.dylib             	    0x7fff2011ccc1 _dispatch_lane_invoke + 400
14  libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
15  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
16  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 3 Crashed::  Dispatch queue: com.google.GDTCCTUploader
0   libsystem_kernel.dylib        	    0x7fff7017300e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7fff701cb1ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7fff2010b751 __abort + 139
3   libsystem_c.dylib             	    0x7fff2010b6c6 abort + 145
4   Timelines                     	       0x10c620152 FIRCLSTerminateHandler() + 210
5   libc++abi.dylib               	    0x7fff202599c7 std::__terminate(void (*)()) + 8
6   libc++abi.dylib               	    0x7fff20259978 std::terminate() + 56
7   libdispatch.dylib             	    0x7fff20115b39 _dispatch_client_callout + 28
8   libdispatch.dylib             	    0x7fff2011c203 _dispatch_lane_serial_drain + 1045
9   libdispatch.dylib             	    0x7fff2011ccc1 _dispatch_lane_invoke + 400
10  libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
11  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
12  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 4::  Dispatch queue: com.google.GDTCORUploadCoordinator
0   TimelinesThreeView.1.preview-thunk.dylib	       0x10fb44b7c __36+[GDTCORReachability sharedInstance]_block_invoke + 12
1   libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
2   libdispatch.dylib             	    0x7fff20116cdd _dispatch_once_callout + 20
3   TimelinesThreeView.1.preview-thunk.dylib	       0x10fb44b3e +[GDTCORReachability sharedInstance] + 78
4   TimelinesThreeView.1.preview-thunk.dylib	       0x10fb44ae1 +[GDTCORReachability initialize] + 33
5   libobjc.A.dylib               	    0x7fff2018a175 CALLING_SOME_+initialize_METHOD + 17
6   libobjc.A.dylib               	    0x7fff2018b094 initializeNonMetaClass + 700
7   libobjc.A.dylib               	    0x7fff2018c2e7 initializeAndMaybeRelock(objc_class*, objc_object*, mutex_tt<false>&, bool) + 172
8   libobjc.A.dylib               	    0x7fff2019893d lookUpImpOrForward + 672
9   libobjc.A.dylib               	    0x7fff20185f1b _objc_msgSend_uncached + 75
10  TimelinesThreeView.1.preview-thunk.dylib	       0x10fb496a4 -[GDTCORUploadCoordinator uploadConditions] + 36
11  TimelinesThreeView.1.preview-thunk.dylib	       0x10fb48db8 __37-[GDTCORUploadCoordinator startTimer]_block_invoke_2 + 120
12  libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7fff20118656 _dispatch_continuation_pop + 475
14  libdispatch.dylib             	    0x7fff2012ad00 _dispatch_source_invoke + 2028
15  libdispatch.dylib             	    0x7fff2011bf65 _dispatch_lane_serial_drain + 375
16  libdispatch.dylib             	    0x7fff2011ccc1 _dispatch_lane_invoke + 400
17  libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
18  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
19  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 8::  Dispatch queue: com.apple.CFNetwork.Connection
0   libsystem_c.dylib             	    0x7fff200d126a __vfprintf + 429
1   libsystem_c.dylib             	    0x7fff200dedb5 _vsnprintf + 316
2   libsystem_c.dylib             	    0x7fff200dee75 vsnprintf + 95
3   libsystem_trace.dylib         	    0x7fff20047136 os_trace_blob_vaddf + 216
4   libsystem_trace.dylib         	    0x7fff20047210 os_trace_blob_addf + 132
5   libsystem_trace.dylib         	    0x7fff2004a7ea _os_log_fmt_compose_data + 386
6   libsystem_trace.dylib         	    0x7fff200497c3 os_log_fmt_compose + 1711
7   libsystem_trace.dylib         	    0x7fff200507b6 _os_log_impl_compose + 117
8   libsystem_trace.dylib         	    0x7fff2004ffd3 _os_log_impl_stream + 82
9   libsystem_trace.dylib         	    0x7fff2004fc3c _os_log_impl_flatten_and_send + 8741
10  libsystem_trace.dylib         	    0x7fff20050f3f os_log_pack_send + 53
11  libnetwork.dylib              	    0x7fff22cc1a0a nw_connection_report_state_with_handler_on_nw_queue + 1226
12  libnetwork.dylib              	    0x7fff22cc144a __nw_connection_cancel_inner_block_invoke.200 + 42
13  libnetwork.dylib              	    0x7fff22cbac3f __nw_connection_cancel_inner_block_invoke + 1631
14  libnetwork.dylib              	    0x7fff22cba2d9 nw_connection_cancel + 249
15  CFNetwork                     	    0x7fff23ee5492 0x7fff23e41000 + 672914
16  CFNetwork                     	    0x7fff23eb209b 0x7fff23e41000 + 463003
17  CFNetwork                     	    0x7fff23eb4603 0x7fff23e41000 + 472579
18  libdispatch.dylib             	    0x7fff201148e4 _dispatch_call_block_and_release + 12
19  libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
20  libdispatch.dylib             	    0x7fff2011c0df _dispatch_lane_serial_drain + 753
21  libdispatch.dylib             	    0x7fff2011ccf8 _dispatch_lane_invoke + 455
22  libdispatch.dylib             	    0x7fff2011e0ae _dispatch_workloop_invoke + 2065
23  libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
24  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
25  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 9:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 10::  Dispatch queue: com.google.firebase.crashlytics.startup
0   libsystem_kernel.dylib        	    0x7fff7016e0ea __ulock_wait + 10
1   libsystem_platform.dylib      	    0x7fff701bc27e _os_unfair_lock_lock_slow + 155
2   dyld_sim                      	       0x10d01850e dyld4::RuntimeState::withLoadersReadLock(void () block_pointer) + 34
3   dyld_sim                      	       0x10d02ac7b dyld4::APIs::_dyld_get_image_header(unsigned int) + 109
4   Timelines                     	       0x10c612940 FIRCLSBinaryImageFindImageForUUID + 160
5   Timelines                     	       0x10c648f0b -[FIRCLSSymbolResolver fillInImageDetails:forUUID:] + 123
6   Timelines                     	       0x10c6490ee -[FIRCLSSymbolResolver updateStackFrame:] + 270
7   Timelines                     	       0x10c648432 __36-[FIRCLSSymbolicationOperation main]_block_invoke + 98
8   Timelines                     	       0x10c6496e4 -[FIRCLSThreadArrayOperation enumerateFramesWithBlock:] + 596
9   Timelines                     	       0x10c6483b6 -[FIRCLSSymbolicationOperation main] + 118
10  Foundation                    	    0x7fff207f09cb __NSOPERATION_IS_INVOKING_MAIN__ + 17
11  Foundation                    	    0x7fff207ecc0f -[NSOperation start] + 785
12  Timelines                     	       0x10c63dd60 -[FIRCLSProcessReportOperation symbolicateFile:withResolver:] + 352
13  Timelines                     	       0x10c63df96 __36-[FIRCLSProcessReportOperation main]_block_invoke + 118
14  Timelines                     	       0x10c62e7dd -[FIRCLSInternalReport enumerateSymbolicatableFilesInContent:] + 397
15  Timelines                     	       0x10c63def7 -[FIRCLSProcessReportOperation main] + 263
16  Foundation                    	    0x7fff207f09cb __NSOPERATION_IS_INVOKING_MAIN__ + 17
17  Foundation                    	    0x7fff207ecc0f -[NSOperation start] + 785
18  Timelines                     	       0x10c64357d __91-[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:]_block_invoke + 781
19  Timelines                     	       0x10c610f89 FIRCLSApplicationActivity + 89
20  Timelines                     	       0x10c643213 -[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:] + 323
21  Timelines                     	       0x10c625379 __92-[FIRCLSExistingReportManager processExistingActiveReportPath:dataCollectionToken:asUrgent:]_block_invoke_2 + 89
22  Foundation                    	    0x7fff207edab1 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
23  Foundation                    	    0x7fff207ed9a9 -[NSBlockOperation main] + 98
24  Foundation                    	    0x7fff207f09cb __NSOPERATION_IS_INVOKING_MAIN__ + 17
25  Foundation                    	    0x7fff207ecc0f -[NSOperation start] + 785
26  Foundation                    	    0x7fff207f131d __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
27  Foundation                    	    0x7fff207f0e64 __NSOQSchedule_f + 182
28  libdispatch.dylib             	    0x7fff201237f4 _dispatch_block_async_invoke2 + 83
29  libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
30  libdispatch.dylib             	    0x7fff2011c0df _dispatch_lane_serial_drain + 753
31  libdispatch.dylib             	    0x7fff2011ccc1 _dispatch_lane_invoke + 400
32  libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
33  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
34  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 11:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 14::  Dispatch queue: com.yahoo.flurry.indexMapQueue
0   libsystem_kernel.dylib        	    0x7fff701700ca __fchmod + 10
1   libsystem_kernel.dylib        	    0x7fff70170002 fchmod + 25
2   Foundation                    	    0x7fff207fd05e _NSWriteDataToFileWithExtendedAttributes + 2272
3   Timelines                     	       0x10c5510b1 +[FlurryUtil _archiveObject:toPath:] + 164
4   Timelines                     	       0x10c5512b6 +[FlurryUtil archiveObject:toFile:] + 123
5   Timelines                     	       0x10c5121c9 -[FlurryDataSenderIndex saveState] + 166
6   Timelines                     	       0x10c512847 __66-[FlurryDataSenderIndex removeBlockInfoWithIdentifier:forDataKey:]_block_invoke + 933
7   libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
8   libdispatch.dylib             	    0x7fff20123cfd _dispatch_lane_barrier_sync_invoke_and_complete + 94
9   Timelines                     	       0x10c512465 -[FlurryDataSenderIndex removeBlockInfoWithIdentifier:forDataKey:] + 179
10  Timelines                     	       0x10c5657a9 -[FlurryDataSender removeStoredDataWithIdentifier:] + 103
11  Timelines                     	       0x10c56684e -[FlurryDataSender requestSuccessComplete:withResponse:] + 362
12  Timelines                     	       0x10c56654e __60-[FlurryDataSender flurryUrlRequestDidSucceed:withResponse:]_block_invoke + 168
13  libdispatch.dylib             	    0x7fff201148e4 _dispatch_call_block_and_release + 12
14  libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
15  libdispatch.dylib             	    0x7fff2011c0df _dispatch_lane_serial_drain + 753
16  libdispatch.dylib             	    0x7fff2011ccc1 _dispatch_lane_invoke + 400
17  libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
18  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
19  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 15:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 17::  Dispatch queue: com.apple.CFNetwork.CacheDB-write
0   CoreFoundation                	    0x7fff20399e23 __CFStringCreateImmutableFunnel3 + 2024
1   CoreFoundation                	    0x7fff203994b2 _CFNonObjCStringCreateCopy + 381
2   CoreFoundation                	    0x7fff2039f06f _CFStringCreateWithFormatAndArgumentsReturningMetadata + 180
3   CoreFoundation                	    0x7fff2039ef93 CFStringCreateWithFormatAndArguments + 122
4   CoreFoundation                	    0x7fff2039f16c CFStringCreateWithFormat + 126
5   CFNetwork                     	    0x7fff23f15ac9 0x7fff23e41000 + 871113
6   CFNetwork                     	    0x7fff23efde72 0x7fff23e41000 + 773746
7   CFNetwork                     	    0x7fff23efe5fd 0x7fff23e41000 + 775677
8   CFNetwork                     	    0x7fff23ea98ac 0x7fff23e41000 + 428204
9   libdispatch.dylib             	    0x7fff201237f4 _dispatch_block_async_invoke2 + 83
10  libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
11  libdispatch.dylib             	    0x7fff2011c0df _dispatch_lane_serial_drain + 753
12  libdispatch.dylib             	    0x7fff2011ccf8 _dispatch_lane_invoke + 455
13  libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
14  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
15  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 18:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	    0x7fff701c6f48 start_wqthread + 0

Thread 20::  Dispatch queue: com.apple.UIKit.UIScenePersistenceQueue
0   Foundation                    	    0x7fff207fa62d -[NSSearchPathEnumerator initWithDirectory:domains:] + 81
1   Foundation                    	    0x7fff207fa78d NSSearchPathForDirectoriesInDomains + 110
2   UIKitCore                     	    0x7fff250cb1a2 _restorationDirectory + 47
3   UIKitCore                     	    0x7fff24f77bb8 ___queue_scheduleUpdateAndSaveForPersistedSceneSessions_block_invoke_3 + 301
4   libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
5   libdispatch.dylib             	    0x7fff20118656 _dispatch_continuation_pop + 475
6   libdispatch.dylib             	    0x7fff2012ad00 _dispatch_source_invoke + 2028
7   libdispatch.dylib             	    0x7fff2011bf65 _dispatch_lane_serial_drain + 375
8   libdispatch.dylib             	    0x7fff2011ccc1 _dispatch_lane_invoke + 400
9   libdispatch.dylib             	    0x7fff2012797b _dispatch_workloop_worker_thread + 779
10  libsystem_pthread.dylib       	    0x7fff701c7fd0 _pthread_wqthread + 326
11  libsystem_pthread.dylib       	    0x7fff701c6f57 start_wqthread + 15

Thread 21:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	    0x7fff7016c97a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7fff7016cce8 mach_msg + 56
2   CoreFoundation                	    0x7fff20371acc __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7fff2036c0e2 __CFRunLoopRun + 1249
4   CoreFoundation                	    0x7fff2036b704 CFRunLoopRunSpecific + 562
5   Foundation                    	    0x7fff20828049 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 213
6   Foundation                    	    0x7fff208282c2 -[NSRunLoop(NSRunLoop) runUntilDate:] + 72
7   UIKitCore                     	    0x7fff25161bda -[UIEventFetcher threadMain] + 491
8   Foundation                    	    0x7fff208511a1 __NSThread__start__ + 1009
9   libsystem_pthread.dylib       	    0x7fff701cb4e1 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7fff701c6f6b thread_start + 15

Thread 22:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	    0x7fff7016c97a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7fff7016cce8 mach_msg + 56
2   CoreFoundation                	    0x7fff20371acc __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7fff2036c0e2 __CFRunLoopRun + 1249
4   CoreFoundation                	    0x7fff2036b704 CFRunLoopRunSpecific + 562
5   CFNetwork                     	    0x7fff240753e0 0x7fff23e41000 + 2311136
6   Foundation                    	    0x7fff208511a1 __NSThread__start__ + 1009
7   libsystem_pthread.dylib       	    0x7fff701cb4e1 _pthread_start + 125
8   libsystem_pthread.dylib       	    0x7fff701c6f6b thread_start + 15

Thread 23:: com.google.firebase.crashlytics.MachExceptionServer
0   libsystem_kernel.dylib        	    0x7fff7016c97a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7fff7016cce8 mach_msg + 56
2   Timelines                     	       0x10c63071e FIRCLSMachExceptionReadMessage + 78
3   Timelines                     	       0x10c630660 FIRCLSMachExceptionServer + 48
4   libsystem_pthread.dylib       	    0x7fff701cb4e1 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7fff701c6f6b thread_start + 15

Thread 3 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000070000fe6c000  rcx: 0x000070000fe6b7a8  rdx: 0x0000000000000000
  rdi: 0x0000000000001907  rsi: 0x0000000000000006  rbp: 0x000070000fe6b7d0  rsp: 0x000070000fe6b7a8
   r8: 0x0000000000000000   r9: 0x0000000000989680  r10: 0x000070000fe6c000  r11: 0x0000000000000246
  r12: 0x0000000000001907  r13: 0x0000600003005b00  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff7017300e  rfl: 0x0000000000000246  cr2: 0x000000c000473000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

**Comment by paulb777** [comment] 2022-06-17 14:17
Sorry about the trouble. This is a duplicate of #8005. Please follow the issue there and at https://github.com/google/promises/issues/189

**Closed by paulb777** 2022-06-17 14:17 UTC
Labels: GoogleDataTransport, SwiftUI
