### ISSUE TITLE
Firebase Crashlytics integration

### ISSUE THREAD

**Issue by high5Fly** [firebase/firebase-ios-sdk#6464] opened 2020-09-15 10:14 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12 beta 6
  * Firebase SDK version: 6.32.0
  * Firebase Component: Crashlytics
  * Component version: [Firebase/Crashlytics] Version 6.32.0
  * Installation method: `Swift Package Manager`

### [REQUIRED] Step 2: Describe the problem
I am having issue running Crashlytics and connecting it to the console.

#### Steps to reproduce:
Crashlytics was added by following the instructions [here](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md#installation). Then we build/run/crash the app but nothing seems to be popping in the console.
Afterwards we aded the run and upload-symbols scripts as part of the directory. Still wasn't able to connect the the firebase console.

Please provide us with documentation/steps how to integrate Crashlytics with SPM?

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by cvaghela** [comment] 2020-09-15 16:54
Can you also make sure that your `Debug Information Format` is set to `DWARF with dSYMs`?

Also, can you turn on Firebase debug more, build and run the app, disconnect from xcode debugger, open the app, make a test crash, run from the xcode again and attach the debug logs here?

Make sure that your Firebase Crashlytics dashboard is open and looking for the integration.

**Comment by stherold** [comment] 2020-09-15 19:20
We have the same issue, this is logged in the console (after doing what you wrote):
```
2020-09-15 21:17:27.248416+0200 Barnim[22185:5045128] [Firebase/Crashlytics] Version 4.6.0
2020-09-15 21:17:27.249896+0200 Barnim[22185:5045174] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics] Running on iPhone11,2, 13.7.0 (17H35)
2020-09-15 21:17:27.350644+0200 Barnim[22185:5045174] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports:Event] Registered Firebase Analytics event listener
2020-09-15 21:17:27.350779+0200 Barnim[22185:5045174] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] Automatic data collection is enabled.
2020-09-15 21:17:27.351277+0200 Barnim[22185:5045174] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] Unsent reports will be uploaded at startup
```

After crashed, attached the debugger again I get this:
```
2020-09-15 21:18:53.561119+0200 Barnim[22206:5046233] [Firebase/Crashlytics] Version 4.6.0
2020-09-15 21:18:53.562831+0200 Barnim[22206:5046277] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics] Running on iPhone11,2, 13.7.0 (17H35)
2020-09-15 21:18:53.595730+0200 Barnim[22206:5046306] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports:Event] Registered Firebase Analytics event listener
2020-09-15 21:18:53.595855+0200 Barnim[22206:5046306] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] Automatic data collection is enabled.
2020-09-15 21:18:53.596158+0200 Barnim[22206:5046306] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] Unsent reports will be uploaded at startup
2020-09-15 21:18:53.625554+0200 Barnim[22206:5046305] [Firebase/Crashlytics] Packaged report with id '984a106fb1094be686e1788500171393' for submission
2020-09-15 21:18:53.626027+0200 Barnim[22206:5046309] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] Preparing the report for the new endpoint: 1
2020-09-15 21:18:53.626390+0200 Barnim[22206:5046309] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports] Submitting report
[22206:5046308] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports:Event] Sending event.
```

But always seeing this screen:

![Screen Shot 2020-09-15 at 20 09 31](https://user-images.githubusercontent.com/64915710/93254800-3afdf400-f799-11ea-8cc6-02753f30465b.png)

**Comment by ericjjj** [comment] 2020-09-16 05:34
some error

**Comment by high5Fly** [comment] 2020-09-16 11:15
1. Dwarf with dSYMs is enabled
![Screenshot 2020-09-15 at 20 55 17](https://user-images.githubusercontent.com/11722811/93330099-ee60fa00-f826-11ea-9e1f-05f520ed0324.png)

2. Log after crash:
2020-09-16 14:12:14.507845+0300 DeviceMate[17958:7949502] [Firebase/Crashlytics] Version 6.32.0
2020-09-16 14:12:14.615378+0300 DeviceMate[17958:7949659] [Firebase/Crashlytics] Packaged report with id 'ba802e35cd184f6e8b8fd30ad9405282' for submission

Nothing else, even in the Console/system.log
And the Crashlytics Dashboard is still in wait, same as the screenshot above.

**Comment by high5Fly** [comment] 2020-09-17 07:03
This is from today with Xcode 12 GM seed.
2020-09-17 10:00:46.420287+0300 DeviceMate[22778:8190307] [Firebase/Crashlytics] Version 6.32.0
2020-09-17 10:00:49.089238+0300 DeviceMate[22778:8192477] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-6 "(null)" UserInfo={retryLimit=1, NSErrorFailingURLStringKey=https://firebase-settings.crashlytics.com/spi/v2/platforms/ios/gmp/1:212738175965:ios:36958d3c2a9b748e183c34/settings?build_version=1&display_version=1.0&instance=97b953e361d40f9a3f7d28a9f015763112fc5845&source=1}

**Comment by high5Fly** [comment] 2020-09-17 07:15
@stherold It worked for me with Xcode 12 GM seed.

**Comment by stherold** [comment] 2020-09-17 08:13
WOW really?! I also had problems with one of my command line tools and it was resolved in Swift 5.3

**Comment by kevinkokomani** [comment] 2020-09-23 18:27
Are people still seeing the same issues on this thread?

**Comment by chanuuuu** [comment] 2020-09-24 00:31
I am facing the same issue with Xcode 12 and Firebase 6.33-spm-beta.

**Comment by stherold** [comment] 2020-09-24 10:04
I tested right now and I can confirm it with the `Carthage` integration, `Xcode 12.0 (12A7209)` and Firebase 6.33.0. 

What exactly makes the website recognize the app? Is it the run script that runs at compile time or is it something at runtime?

**Comment by tkrajacic** [comment] 2020-09-24 13:24
Maybe a stupid question, but how did you run the build phase that previously ran the script `${PODS_ROOT}/FirebaseCrashlytics/run`?

**Comment by kevinrefermat** [comment] 2020-09-24 16:37
@tkrajacic in the build phase, try replacing `${PODS_ROOT}/FirebaseCrashlytics/run` with `${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run`

**Comment by tkrajacic** [comment] 2020-09-24 16:40
@kevinrefermat oh I wasn't asking for me. I was asking if that might be the user's problem here.

**Comment by stherold** [comment] 2020-09-24 17:10
@tkrajacic okay for Carthage integration I downloaded the framework from https://firebase.google.com/download/ios since the `run` is not included at all in the Carthage download. I extracted the 2 scripts `run` and `upload-symbols` into a sub-directory of my project and call it as the last build phase via:

`${PROJECT_DIR}/dependencies/firebase-crashlytics-dsym-upload/run`

Does this make sense?

**Comment by ericjjj** [comment] 2020-09-26 03:20
@stherold  sorry, what about swift package manager?

**Comment by stherold** [comment] 2020-09-26 23:12
> @stherold sorry, what about swift package manager?

We're not on coe 12 yet. Also we can easily cche Carthage dependencies on Bitrise but not SPM ones. So Carthage is the better option.

**Comment by samedson** [comment] 2020-09-30 16:26
Hey folks, want to dig in further. We saw a case where GDTCORFlatFileStorage isn't loading with binary frameworks. Can you try the following to confirm it's the same issue:

1. Run your app
1. Go to the Debug Navigator in Xcode (the spray paint icon)
1. Click "Memory" and then the tiny vertical lines and choose "View Memory Graph Hierarchy"

![Screen Shot 2020-09-30 at 12 22 47 PM](https://user-images.githubusercontent.com/555046/94712857-0ac96000-0318-11eb-9de9-7eadcaa3e5aa.png)

4. Then, add "GDT" to the filter at the bottom, and confirm whether GDTCORFlatFileStorage has loaded into the app?

![Screen Shot 2020-09-30 at 12 23 00 PM](https://user-images.githubusercontent.com/555046/94712877-1026aa80-0318-11eb-86ee-d178e8cd815d.png)

**Comment by kazi05** [comment] 2020-10-05 09:10
I have the same issue, but also i have `Failed to download settings Error Domain=FIRCLSNetworkError Code=-5` error.
![Снимок экрана 2020-10-05 в 12 10 29](https://user-images.githubusercontent.com/26439900/95061053-c36e1580-0703-11eb-8e0c-cc9f98b6ec37.png)

My Run Script is like:
![Снимок экрана 2020-10-05 в 12 08 44](https://user-images.githubusercontent.com/26439900/95060905-915cb380-0703-11eb-8a68-913ed88272c7.png)

Crashlytics added into project. Any ideas for this ?

**Comment by balazserdeszlogmein** [comment] 2020-10-05 14:56
I might be the only one, but I do not understand the context switch from SPM to carthage. Is that the same issue?

**Comment by kevinrefermat** [comment] 2020-10-05 18:03
@kazi05 looking at your screenshot, you must at least remove the quotes from`${PROJECT_DIR}/dependencies/firebase-crashlytics-dsym-upload/run`. We are passing the actual `Crashlytics/run` script to `/bin/sh` to be executed, not a string of the path to it.

I had the same error recently when I integrated Crashlytics into my project using SPM. After some searching around I had to do the following to get it to work.
1) follow the directions in this comment https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-694449182
2) add FirebaseAnalytics to your project in addition to FirebaseCrashlytics; some Crashlytics docs say adding FirebaseAnalytics makes Crashlytics work better, but Crashlytics didn't work at all unless I added it.

<img width="707" alt="Screenshot" src="https://user-images.githubusercontent.com/3867343/95115443-54d88a00-06fa-11eb-864e-c88bbd930a4e.png">

**Comment by stherold** [comment] 2020-10-12 09:38
I tried to remove all Firebase related keys from our info.plist that we use to prevent analytics/data collecion from the app start so we can give the user the possibility to opt-in to any kind of data collection. But that gave no results :-( The website doesn't react to the start of the app. In detail I tried the following steps:

    - [x] Disable backend influence on Crashlytics (analytics always enabled)
    - [x] Make isReleaseBuild always return true
    - [x] Remove FIREBASE_ANALYTICS_COLLECTION_ENABLED from plist
    - [x] Upgrade Firebase to 6.34.0
    - [x] Remove FirebaseScreenReportingEnabled and GOOGLE_ANALYTICS_IDFV_COLLECTION_ENABLED from info.plist
    - [x] Remove cache builds from carthage command call
    - [x] reset all simulators
    - [x] Remove firebase_performance_collection_deactivated

**Comment by das-palash-appsbee** [comment] 2020-10-13 03:21
Facing same issue while using Carthage.

Xcode Version 12.0.1 (12A7300)
Firebase SDK Version 6.34.0

**Comment by stherold** [comment] 2020-10-13 09:51
Okay we solved the problem for us 🎉

The issue was (as @samedson depicted) that some frameworks where not linked to the main app target 🤭  Why can that happen?! Wenn quite easy, we integrated Firebase via Carthage for a long time now, upgraded it in that time a lot and we think that Google added some frameworks that where suddenly there after the upgrade but we forgot to link them to the target. The app was just building fine and also didn't crash nor log anything regarding the missing frameworks. In detail the missing frameworks where:

![Screen Shot 2020-10-13 at 11 45 27](https://user-images.githubusercontent.com/64915710/95844781-9942d600-0d49-11eb-84c8-004ac7460914.png)

There are different solutions we came up to check what frameworks could be missing:
- Create an example project, add the same frameworks to the Cartfile as you do in your main project, run carthage to build the frameworks and add all frameworks from `Carthage/Build/iOS` to your project and compare them to your project.
- Create an example project, integrate the framework via CocoaPods (since this seems to be the main method Google supports and maintains), run `pod install` and compare the frameworks CocoaPods links to your main app target.

To prevent such issues to happen in future, Google could (additionally to handling it gracefully) execute some runtime checks on app start in the Firebase framework and at least print some logs when required frameworks are missing - wdyt?

Hope that helps some of you guys ✌️

**Comment by Blackjacx** [comment] 2020-10-13 09:53
Okay we solved the problem for us 🎉

The issue was (as @samedson depicted) that some frameworks where not linked to the main app target 🤭  Why can that happen?! Wenn quite easy, we integrated Firebase via Carthage for a long time now, upgraded it in that time a lot and we think that Google added some frameworks that where suddenly there after the upgrade but we forgot to link them to the target. The app was just building fine and also didn't crash nor log anything regarding the missing frameworks. In detail the missing frameworks where (it was the missing GoogleDataTransport framework that prevented the crash report to get submitted to the server):

![Screen Shot 2020-10-13 at 11 45 27](https://user-images.githubusercontent.com/64915710/95844781-9942d600-0d49-11eb-84c8-004ac7460914.png)

There are different solutions we came up to check what frameworks could be missing:
- Create an example project, add the same frameworks to the Cartfile as you do in your main project, run carthage to build the frameworks and add all frameworks from `Carthage/Build/iOS` to your project and compare them to your project.
- Create an example project, integrate the framework via CocoaPods (since this seems to be the main method Google supports and maintains), run `pod install` and compare the frameworks CocoaPods links to your main app target.

To prevent such issues to happen in future, Google could (additionally to handling it gracefully) execute some runtime checks on app start in the Firebase framework and at least print some logs when required frameworks are missing - wdyt?

Hope that helps some of you guys ✌️

**Comment by puneet-egym** [comment] 2020-10-13 11:56
@Blackjacx Thanks a lot for your comment. Adding the GoogleDataTransport.framework fixed it for us as well. 
I wonder where we missed it in the documentation of how to integrate the firebase crashlytics.

**Comment by stherold** [comment] 2020-10-13 15:29
Maybe @puneet-egym integrates Firebase via Carthage too. The original question from @high5Fly regarding SPM was already answered by https://github.com/firebase/firebase-ios-sdk/issues/6464#issuecomment-693338988

**Comment by puneet-egym** [comment] 2020-10-13 15:46
@paulb777 Yes, @stherold  is correct, I was also using Carthage to integrate Firebase

**Comment by paulb777** [comment] 2020-10-13 16:42
Thanks for clearing up. It sounds like everything is resolved here. Thanks all!

**Closed by paulb777** 2020-10-13 16:42 UTC
Labels: Swift Package Manager, api: crashlytics, needs-info
