### ISSUE TITLE
Crash in CCTLogWriter

### ISSUE THREAD

**Issue by DarkoDamjanovic** [firebase/firebase-ios-sdk#618] opened 2018-01-05 09:24 UTC
I experience a crash in CCTLogWriter and according to this page this can be related to Firebase:

https://github.com/google/protobuf/issues/3267

Here the crash: http://crashes.to/s/62acdb4b872

Version from podfile.lock:  - Firebase (4.8.0):

Thanks.

**Comment by paulb777** [comment] 2018-01-05 15:48
@DarkoDamjanovic Please share the full contents of Podfile.lock - or at least all of the Firebase pods that you're using with their versions.

**Comment by morganchen12** [comment] 2018-01-05 17:40
The crash listed in Crashlytics and the one in the original issue you linked are two different crashes; the former was fixed earlier in 2017. Crashlytics also lists the issue as "resolved".

There's not enough information here to debug the issue, please list your whole Podfile.lock as @paulb777 mentioned and re-open.

**Comment by DarkoDamjanovic** [comment] 2018-01-05 19:08
Sorry, that was me. I mark bugs related to Cocoapods as resolved as soon as I report them (e.g. here). Because I can't do more than that. 

Here the unresolved link:
http://crashes.to/s/62acdb4b872

The whole content of my Podfile.lock:

```
$ cat Podfile.lock 
PODS:
  - Adjust (4.12.1):
    - Adjust/Core (= 4.12.1)
  - Adjust/Core (4.12.1)
  - AppAuth (0.91.0)
  - Bolts (1.8.4):
    - Bolts/AppLinks (= 1.8.4)
    - Bolts/Tasks (= 1.8.4)
  - Bolts/AppLinks (1.8.4):
    - Bolts/Tasks
  - Bolts/Tasks (1.8.4)
  - Crashlytics (3.9.3):
    - Fabric (~> 1.7.2)
  - Fabric (1.7.2)
  - FBSDKCoreKit (4.29.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.29.0):
    - FBSDKCoreKit
  - FBSDKShareKit (4.29.0):
    - FBSDKCoreKit
  - Firebase (4.8.0):
    - Firebase/Core (= 4.8.0)
  - Firebase/Core (4.8.0):
    - FirebaseAnalytics (= 4.0.5)
    - FirebaseCore (= 4.0.13)
  - Firebase/Performance (4.8.0):
    - Firebase/Core
    - FirebasePerformance (= 1.1.0)
  - Firebase/RemoteConfig (4.8.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 2.1.0)
  - FirebaseABTesting (1.0.0):
    - FirebaseCore (~> 4.0)
    - Protobuf (~> 3.1)
  - FirebaseAnalytics (4.0.5):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.13):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.8):
    - FirebaseCore (~> 4.0)
  - FirebasePerformance (1.1.0):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - FirebaseSwizzlingUtilities (~> 1.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.1)
  - FirebaseRemoteConfig (2.1.0):
    - FirebaseABTesting (~> 1.0)
    - FirebaseAnalytics (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - Protobuf (~> 3.1)
  - FirebaseSwizzlingUtilities (1.0.0)
  - FLEX (2.4.0)
  - GoogleAnalytics (3.17.0)
  - GoogleIDFASupport (3.14.0)
  - GoogleSignIn (4.1.1):
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GoogleToolboxForMac/NSString+URLArguments (~> 2.1)
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/Defines (2.1.3)
  - GoogleToolboxForMac/Logger (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/NSData+zlib (2.1.3):
    - GoogleToolboxForMac/Defines (= 2.1.3)
  - GoogleToolboxForMac/NSDictionary+URLArguments (2.1.3):
    - GoogleToolboxForMac/DebugUtils (= 2.1.3)
    - GoogleToolboxForMac/Defines (= 2.1.3)
    - GoogleToolboxForMac/NSString+URLArguments (= 2.1.3)
  - GoogleToolboxForMac/NSString+URLArguments (2.1.3)
  - GTMOAuth2 (1.1.6):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.1.12):
    - GTMSessionFetcher/Full (= 1.1.12)
  - GTMSessionFetcher/Core (1.1.12)
  - GTMSessionFetcher/Full (1.1.12):
    - GTMSessionFetcher/Core (= 1.1.12)
  - libwebp (0.6.0):
    - libwebp/core (= 0.6.0)
    - libwebp/dec (= 0.6.0)
    - libwebp/demux (= 0.6.0)
    - libwebp/dsp (= 0.6.0)
    - libwebp/enc (= 0.6.0)
    - libwebp/mux (= 0.6.0)
    - libwebp/utils (= 0.6.0)
    - libwebp/webp (= 0.6.0)
  - libwebp/core (0.6.0):
    - libwebp/webp
  - libwebp/dec (0.6.0):
    - libwebp/core
  - libwebp/demux (0.6.0):
    - libwebp/core
  - libwebp/dsp (0.6.0):
    - libwebp/core
  - libwebp/enc (0.6.0):
    - libwebp/core
  - libwebp/mux (0.6.0):
    - libwebp/core
  - libwebp/utils (0.6.0):
    - libwebp/core
  - libwebp/webp (0.6.0)
  - Mixpanel-swift (2.3.1):
    - Mixpanel-swift/Complete (= 2.3.1)
  - Mixpanel-swift/Complete (2.3.1)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.5.0)
  - SDWebImage/Core (4.2.2)
  - SDWebImage/WebP (4.2.2):
    - libwebp
    - SDWebImage/Core
  - SwiftyBeaver (1.5.0)
```

Thanks.

**Comment by morganchen12** [comment] 2018-01-05 19:54
The crash was caused by an EXC_BAD_ACCESS in `strlen`, which means either your app memory at that point was corrupted or there's something wrong in the CCTFarmHash code.

**Comment by morganchen12** [comment] 2018-01-22 19:40
@DarkoDamjanovic in the absence of other reports or additional debugging information, we're going to close this issue.

**Closed by morganchen12** 2018-01-22 19:40 UTC
Labels: Performance
