### ISSUE TITLE
FIRStorageUploadTask putFile: callBack never called if no connection

### ISSUE THREAD

**Issue by mjlee250** [firebase/firebase-ios-sdk#8724] opened 2021-09-29 20:35 UTC
Step 1: Describe your environment

  * Xcode version:  12.4
  * Firebase SDK version: 8.8.0
  * Installation method: CocoaPods
  * Firebase Component: Storage

Step 2: Describe the problem
When calling  FIRStorageUploadTask putFile, if there is a connection failure (in my case I have turned off WIFI and cell), the callBack is never called, whether or not an observer is being used. If using an observer, that is never called either. This occurs in both the simulator and a real iPhone. If I turn on WIFI, then the callBack is called and everything works fine.

#### Relevant Code:

```
+ (void) upload:(NSURL *)url filename:(NSString *)filename completion:(void (^)(NSURL *))completion {
       
    FIRStorage *storage = [FIRStorage storage];
    FIRStorageReference *storageRef = [storage reference];
    FIRStorageReference *destFileRef = [storageRef child:filename];

    FIRStorageUploadTask *uploadTask = [destFileRef putFile:url metadata:nil completion:^(FIRStorageMetadata *metadata, NSError *error) {
        
      if (error != nil) {   // WE NEVER GET HERE
          NSLog(@"Error FIRStorageUploadTask: %@", error);
          completion(nil);
      } else {
        [destFileRef downloadURLWithCompletion:^(NSURL * _Nullable URL, NSError * _Nullable error) {
            if (error != nil) {
                NSLog(@"Error Firebase downloadURLWithCompletion: %@", error);
                completion(nil);
            } else {
                completion(URL);
            }
        }];
      }
    }];
    
    FIRStorageHandle observer = [uploadTask observeStatus:FIRStorageTaskStatusProgress handler:^(FIRStorageTaskSnapshot *snapshot) {
        // WE NEVER GET HERE
    }];
    
}
```

**Comment by morganchen12** [comment] 2021-09-30 01:40
Duplicate of #5295

**Closed by morganchen12** 2021-09-30 01:40 UTC
Labels: api: storage
