### ISSUE TITLE
Crashed: FirebaseWorker

### ISSUE THREAD

**Issue by JienLee** [firebase/firebase-ios-sdk#888] opened 2018-03-08 04:57 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: maybe 4.4.0
  * Firebase Component: Core, Database, Messaging, DynamicLinks, RemoteConfig, Performance
  * Component version: Sorry I don't even know the detailed version.

#### Steps to reproduce:

I got crash message from my old app versions. (by Crashlytics)
Latest app's Firebase version is 4.8.2.

please some advice to me..

#### Relevant Code:

```
Crashed: FirebaseWorker
0  libobjc.A.dylib                0x180880430 objc_msgSend + 16
1  CoreFoundation                 0x181530984 -[NSDictionary isEqualToDictionary:] + 380
2  CoreFoundation                 0x18152e8b4 -[__NSCFDictionary isEqual:] + 124
3  CoreFoundation                 0x181530984 -[NSDictionary isEqualToDictionary:] + 380
4  CoreFoundation                 0x18152e8b4 -[__NSCFDictionary isEqual:] + 124
5  Foundation                     0x181fd3f50 __98-[NSObject(NSKeyValueObservingPrivate) _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:]_block_invoke.158 + 84
6  CoreFoundation                 0x18167a284 ____NSDictionaryEnumerate_block_invoke.13 + 40
7  CoreFoundation                 0x1814e31f8 CFBasicHashApply + 132
8  CoreFoundation                 0x181679dc4 __NSDictionaryEnumerate + 212
9  Foundation                     0x181fd3cec -[NSObject(NSKeyValueObservingPrivate) _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 508
10 CoreFoundation                 0x18165624c forEachObserver + 224
11 CoreFoundation                 0x181656494 -[CFPrefsSource _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 72
12 CoreFoundation                 0x1815ba938 __78-[CFPrefsSearchListSource deferredNotifyOfChangesFromDictionary:toDictionary:]_block_invoke + 36
13 CoreFoundation                 0x18165d394 _CFPrefsDeliverPendingKVONotifications + 104
14 CoreFoundation                 0x1815bbfbc __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 284
15 CoreFoundation                 0x1815bb7c8 normalizeQuintuplet + 356
16 CoreFoundation                 0x1815bbe94 -[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 108
17 CoreFoundation                 0x18166008c -[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:] + 92
18 CoreFoundation                 0x18166370c _CFPreferencesSetAppValueWithContainer + 128
19 Foundation                     0x181f1bf80 -[NSUserDefaults(NSUserDefaults) setObject:forKey:] + 68
20 {MyAppName}                     0x10274e2c0 -[FRepoInfo setInternalHost:] + 4310704832
21 {MyAppName}                     0x1027825bc -[FConnection onReset:] + 4310918588
22 {MyAppName}                     0x1027821b8 -[FConnection onControl:] + 4310917560
23 {MyAppName}                     0x102781f40 -[FConnection onMessage:withMessage:] + 4310916928
24 {MyAppName}                     0x102783554 -[FWebSocketConnection appendFrame:] + 4310922580
25 {MyAppName}                     0x102783614 -[FWebSocketConnection handleIncomingFrame:] + 4310922772
26 {MyAppName}                    0x10279c174 __31-[FSRWebSocket _handleMessage:]_block_invoke + 4311023988
27 libdispatch.dylib              0x180fa1088 _dispatch_call_block_and_release + 24
28 libdispatch.dylib              0x180fa1048 _dispatch_client_callout + 16
29 libdispatch.dylib              0x180faae48 _dispatch_queue_serial_drain$VARIANT$mp + 528
30 libdispatch.dylib              0x180fab7d8 _dispatch_queue_invoke$VARIANT$mp + 340
31 libdispatch.dylib              0x180fac200 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 400
32 libdispatch.dylib              0x180fb44a0 _dispatch_workloop_worker_thread$VARIANT$mp + 644
33 libsystem_pthread.dylib        0x181246fd0 _pthread_wqthread + 932
34 libsystem_pthread.dylib        0x181246c20 start_wqthread + 4
```

**Comment by paulb777** [comment] 2018-03-08 14:48
This looks like #496. We'll likely need a reproducible test case to make progress on it.

**Comment by morganchen12** [comment] 2018-05-15 18:12
Closing since this has staled and has no new reports.

**Closed by morganchen12** 2018-05-15 18:12 UTC
Labels: Database
