### ISSUE TITLE
Firebase SDK with Version 9.2.0 is giving build time error with older versions of Swift

### ISSUE THREAD

**Issue by RupaliPatil28910** [firebase/firebase-ios-sdk#9960] opened 2022-06-28 14:09 UTC
I have added Firebase SDK through cocoa-pods with the help of below lines:

  pod 'Firebase', '~> 9.2.0'

  pod 'Firebase/Crashlytics', '~> 9.2.0'

  pod 'Firebase/Analytics', '~> 9.2.0'

After successful addition of firebase SDK's, It is giving compile-time error:
Pods/FirebaseCoreInternal/FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift:110:14: Value of optional type 'HeartbeatsBundle?' must be unwrapped to refer to member 'makeHeartbeatsPayload' of wrapped base type 'HeartbeatsBundle'

Please find attached a screenshot for the same. 
<img width="955" alt="Screenshot 2022-06-28 at 7 34 03 PM" src="https://user-images.githubusercontent.com/51600664/176199267-efa5fed1-2a30-48fe-a841-a0405a7aa875.png">

**Comment by paulb777** [comment] 2022-06-28 14:43
Please share the version of Xcode used.

**Comment by RupaliPatil28910** [comment] 2022-06-29 06:34
@paulb777 I used xcode 13.3.1.

**Comment by paulb777** [comment] 2022-06-29 16:56
@RupaliPatil28910 I'm not able to reproduce. Are you able to share a reproducible example. Perhaps with one of the examples in https://github.com/firebase/quickstart-ios?

**Comment by tel-kho** [comment] 2022-07-04 13:15
Hello,

I'm facing the same issue, today I tried to build my Flutter project after updating Firebase SDK to 9.2.O on Xcode and the build failed.

Xcode version: Version 13.4.1 (13F100)

**Comment by tel-kho** [comment] 2022-07-05 06:57
For now, I downgraded versions directly in my Podfile. I checked them on my colleague's Mac, this is what I added:
`$FirebaseSDKVersion = '8.15.0'
  pod 'Firebase/Core', '8.15.0'
  pod 'FirebaseCoreDiagnostics', '8.15.0'
  pod 'FirebaseInstallations', '8.15.0'`
It's running fine for now.

**Comment by tel-kho** [comment] 2022-07-05 11:53
I added '!' like suggested by Xcode for now like that:

`return heartbeatsBundle!.makeHeartbeatsPayload()`

and it compiles and runs now. The thing is that it is inside the package so I'll need to do it several times if removed after downloading it again.

**Comment by ryanwilson** [comment] 2022-07-05 15:50
It seems like the compiler is getting confused somehow:

https://github.com/firebase/firebase-ios-sdk/blob/3862a56dd3735c84d746892648781f36984ff2ed/FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift#L109-L111

Line 109 uses `if let` which should mean that `heartbeatsBundle` is non-optional on line 110. I thought it maybe could have been getting confused with the similarly named variable on line 94 but it's not in the same scope. 

@RupaliPatil28910 are you also using Flutter? If so, maybe it's worth filing an issue there. 

We're still hoping for a repro project, otherwise we likely won't be able to make progress on this.

**Comment by RupaliPatil28910** [comment] 2022-07-08 13:37
@ryanwilson I am facing this issue in Native iOS project.

**Comment by RupaliPatil28910** [comment] 2022-07-08 13:40
@paulb777 In xcode 13.3.1, I just updated firebase to version 9.2.0 through cocoa-pods. After that build gets failed by giving attached error.

But through Swift Package Manager, same firebase version worked.

**Comment by JEuler** [comment] 2022-07-11 15:33
Same problem here

**Comment by JEuler** [comment] 2022-07-12 15:29
> I added '!' like suggested by Xcode for now like that:
> 
> `return heartbeatsBundle!.makeHeartbeatsPayload()`
> 
> and it compiles and runs now. The thing is that it is inside the package so I'll need to do it several times if removed after downloading it again.

Yeah, that hack works. :)

**Comment by kennethj** [comment] 2022-07-12 20:55
As a Flutter developer, it is super frustrating how often firebase breaks stuff. 😕

**Comment by ryanwilson** [comment] 2022-07-12 21:00
I'm sorry for the frustration @kennethj - we still don't have a project that reproduces this. If you have one, that will enable us to move forward and get to the root issue.

It's quite confusing because the code as written should work, it sounds like the compiler is in a bad state or is getting confused. In the workaround of adding a `!` to `heartbeatsBundle`, that won't actually compile when building the SDK alone or in our quickstart projects, so it's not like we can do that and ship it. 

cc @JEuler in case you also have a sample project that reproduces this.

**Comment by ncooke3** [comment] 2022-07-12 21:04
Adding on to Ryan's post: @RupaliPatil28910, you mentioned that you saw this issue in a native iOS project, are you able to share a repro by chance?

**Comment by kennethj** [comment] 2022-07-12 21:20
Does this help?

https://github.com/kennethj/firebase_ios_flutter_bug

It is a base `flutter create` project with firebase dependencies added and `await Firebase.initializeApp();` added to `main.dart`

This produces the same errors I am getting in other projects.

**Comment by kennethj** [comment] 2022-07-12 22:16
Setting Firebase SDK version to `8.15.0` in the `Podfile` seems to work for me

```ruby
# Override Firebase SDK Version
$FirebaseSDKVersion = '8.15.0'
```

**Comment by morganchen12** [comment] 2022-07-12 22:46
For people running into this issue, can you share your project's Swift version as well?

**Comment by kennethj** [comment] 2022-07-13 01:38
https://github.com/kennethj/firebase_ios_flutter_bug - updated to match the configuration of projects to reproduce the `HeartbeatsBundle?` error.

 ```sh 
Swift Compiler Error (Xcode): Value of optional type 'HeartbeatsBundle?' must be unwrapped to refer to member
'makeHeartbeatsPayload' of wrapped base type 'HeartbeatsBundle'
```

**Comment by ncooke3** [comment] 2022-07-13 15:03
Thanks a bunch @kennethj, I took a look at your project. Could you bump your Swift version to 5.x? Could you try 5.3 for example? I see that your project is using the previous major version which could be contributing to the problem here.

**Comment by kennethj** [comment] 2022-07-13 15:31
Updating the `SWIFT_VERSION` to `'5.3'` in the Podfile appears to work for the repo posted above.

Changes to Podfile:
https://github.com/kennethj/firebase_ios_flutter_bug/commit/5a442144054a656d4d73b313ab24c613b3df57ea

**Comment by ncooke3** [comment] 2022-07-13 16:03
Thanks @kennethj for confirming it worked. I recommend to stay on the latest major Swift version as that is the version we develop Firebase with.

Could others in this thread confirm that bumping their Swift version to a 5.x version addresses the build error?
@JEuler  @RupaliPatil28910  @tel-kho

**Comment by JEuler** [comment] 2022-07-13 16:16
It worked for me also. Sorry for dumbness error report :D Thanks!

**Comment by ncooke3** [comment] 2022-07-13 19:07
No worries at all @JEuler, and thank you for confirming. 

At this point, the recommended solution is to bump the Swift version to major version 5. I'm going to close this issue for now but can re-open if anyone runs into more issues. 

Sorry again for the trouble and thanks everyone for the helpful info. I'm going to look into how we can keep this version in sync with the Swift version that Flutter uses.

**Closed by ncooke3** 2022-07-13 19:07 UTC
Labels: api: core

**Comment by tel-kho** [comment] 2022-07-14 07:49
> Could others in this thread confirm that bumping their Swift version to a 5.x version addresses the build error? @JEuler @RupaliPatil28910 @tel-kho

I updated my Podfile too:
`      config.build_settings['SWIFT_VERSION'] = '5.3'`
I cleaned my dependancies and installed them again, I can now run my project without modifying the line, thank you!

I'll let you know if I face the error again with further app build on Xcode
