### ISSUE TITLE
Long Delay On Every Read When Offline

### ISSUE THREAD

**Issue by barrysohl** [firebase/firebase-ios-sdk#5926] opened 2020-06-26 00:26 UTC
### [REQUIRED] Step 1: Describe your environment

* Using Firestore SDK on Xamarin via Plugin.CloudFirestore (which wraps Xamarin.Firebase.iOS.CloudFirestore)

Same issue occurs on Android, so does not seem to be platform specific.

### [REQUIRED] Step 2: Describe the problem

When offline, Firestore appears to try the network first (and wait for a lengthy timeout) for **every** read before attempting to read from persisted cache. In our case, our app performs 20-30 trivial queries at launch. These queries take 2-3 seconds when online, but were taking **5 minutes** when offline. By forcing the 'source' param on GetDocument() to be Cache when offline, the launch drops from 5 minutes to below 1 second. 

#### Steps to reproduce:

100% reproducible. It is possible the issue is related to the Xamarin library, but that seems unlikely given that it is strictly wrapping the native APIs.

**Comment by wu-hui** [comment] 2020-06-30 15:21
Hi @barrysohl,

Thanks for the report.

I failed to reproduce what you described, with a vanilla iOS App and latest Firebase/Firestore SDK. When device is offline, the app is still able to get the initial snapshots from cache with default listen option, instantly. There is no noticeable delay.

I don't have much experience with Xamarin, I could try to reproduce it as well if you could provide a more detailed guide on the setup and code snippets. Also please include the versions of all related components.

Thanks

**Comment by barrysohl** [comment] 2020-06-30 16:06
In this case, we're not using listen/snapshots. It occurs using just direct GetDocumentAsync reads. It occurs on Android as well. This snippet is C#/Xamarin specific, but maps pretty directly to the native API:

```
			var query = GetCollection( collectionKey ).WhereEqualsTo( field, UniqueId );

			// Optional sorting (ascending)
			if ( !string.IsNullOrEmpty( orderBy ) )
			{
				query = query.OrderBy( orderBy, false );
			}

			// Blocking read
			var results = await query.GetDocumentsAsync( GetSource() ).ConfigureAwait( false );

			return results.ToObjects<T>().ToList();

```

**Comment by wu-hui** [comment] 2020-06-30 16:25
I see.

So when the device is offline (or having network issues), Firestore is unfortunately not aware immediately, it would take it some time to figure out, that is the delay you see with `GetDocumentAsync`, it is basically waiting for the backend to send a signal that the local storage has a consistent view of the data. As you noted above, using `Source: Cache` will make this go away. 

I think a better way is to listen to the query snapshots instead though, since it will give you whatever the local storage has first, then play catch up if backend responds.

OTOH, 5 minutes delay is a bit too long though, I will look into that. But the delay most likely will not go away.

Thanks.

**Comment by barrysohl** [comment] 2020-06-30 16:31
If you could "batch" the delay, that would be fine. For our case, a one-time hit of 10 seconds at startup would be no problem. But right now, it appears to be for every single GetDocumentAsync(), and we have maybe 20 of those calls at startup. And a several minute delay would I think be a showstopper for anyone. If we switched to listening, we would still have to listen on many collections, and presumably still have the same problem.

**Comment by wu-hui** [comment] 2020-06-30 16:54
Switching to listening should lead to no delay for the initial snapshots (from cache), `GetDocumentAsync` with default listen options is actually implemented through listening, with a setting to turn on backend signalling (I explained above), because the intention was to provide a consistent view since user only read the result once.

The only downside for switching to listens is you have to manually unsubscribe, if you don't want to keep them around. You could do the unsub in the first snapshot raising, which means you might be seeing inconsistent view, or when backend comes around, which means you only unsub when your view of data is consistent (note you need `includeMetadataChanges: true` because second snapshots might not have actual document change).

**Comment by wu-hui** [comment] 2020-06-30 19:27
Also, I just tried reproducing with `GetDocument`, and the documents load pretty quick to me. 

At this point, I'd need a reproduce instruction to proceed.

**Comment by barrysohl** [comment] 2020-06-30 20:22
In retrospect, I wish we would have implemented everything with listeners/snapshots, but that would be a pretty significant re-architecture for us at this point. As mentioned, it is possible it's something related to the Xamarin library we're using. Since forcing GetDocument() to read from cache solves the issue, I think it's a viable workaround for us. We can close this ticket and revisit later if it becomes an issue. Thanks!

**Comment by ryanwilson** [comment] 2020-07-08 14:17
Thanks, closing the issue as per your recommendation. Like you mentioned, if you need to revisit it please re-open as necessary!

**Closed by ryanwilson** 2020-07-08 14:17 UTC
Labels: api: firestore, needs-attention
