### ISSUE TITLE
GoogleDataTransport not compile in Xcode 12

### ISSUE THREAD

**Issue by gilrodar** [firebase/firebase-ios-sdk#6488] opened 2020-09-17 18:28 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12
  * Firebase SDK version: 6.32.2
  * Firebase Component: GoogleDataTransport
  * Component version: 7.3.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Parse issue

`Could not build module 'nanopb'`

<img width="696" alt="Captura de Pantalla 2020-09-17 a la(s) 13 25 46" src="https://user-images.githubusercontent.com/13817108/93512026-4e1fd980-f8e9-11ea-9097-60b0ddfd1b87.png">

Lexical or Preprocessor Issue

<img width="941" alt="Captura de Pantalla 2020-09-17 a la(s) 13 27 57" src="https://user-images.githubusercontent.com/13817108/93512222-9b9c4680-f8e9-11ea-8ee2-8c6589bda49b.png">

**Comment by paulb777** [comment] 2020-09-17 18:39
Duplicate of #6484. tldr Update to CocoaPods 1.10

**Closed by paulb777** 2020-09-17 18:39 UTC
Labels: needs-triage
