### ISSUE TITLE
Firebase Apple 10.21.0 has no privacy manifest in FirebaseCore and Firebase Messaging  framework

### ISSUE THREAD

**Issue by wangyunico** [firebase/firebase-ios-sdk#12367] opened 2024-02-07 03:48 UTC
### Description

When I install Firebase Messaging of version 10.21.0.  I can not find my app has privacy manifest as expected.

### Firebase SDK Version

10.21.0

### Xcode Version

15.1

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2024-02-07 13:37
Hi @wangyunico, this is a duplicate of #11490. Please refer to the aforementioned ticket for the progress. Thanks.

**Closed by rizafran** 2024-02-07 13:37 UTC
