### ISSUE TITLE
gRPC-Core Apple Mach O-Linker Errors after Xcode 9/Swift 4 Update

### ISSUE THREAD

**Issue by adornoventura** [firebase/firebase-ios-sdk#426] opened 2017-11-03 19:44 UTC
* Xcode version: 9.1
  * Firebase SDK version: 4.5.0
  * Firebase Component: Core (gRPC-Core)
  * Component version: 4.0.10 (Firebase Core)
  * CocoaPods version: 1.3.1

### Describe the problem

After updating from Xcode 8.3.3 to 9.1 I am receiving a multitude of gRPC-Core errors when building. These errors were not prevalent before updating Xcode and I tried the usual steps to resolve them (remove pods, reinstall, pod update, delete Xcode derived data, clean, rebuild, etc). Running CocoaPods version 1.3.1

: "_gpr_ltoa", referenced from:
: "_grpc_static_slice_table", referenced from:
: "_grpc_mdelem_from_slices", referenced from:
: "_gpr_cpu_current_cpu", referenced from:
: "_grpc_channel_stack_element", referenced from:
: "_grpc_error_create", referenced from:
: "_grpc_api_trace", referenced from:
: "_grpc_channel_get_channel_stack", referenced from:
: "_grpc_exec_ctx_finish", referenced from:
: "_gpr_log", referenced from:
: "_grpc_channel_create", referenced from:
: "_grpc_call_stack_ignore_set_pollset_or_pollset_set", referenced from:
: "_grpc_slice_from_copied_string", referenced from:
: "_grpc_closure_sched", referenced from:
: "_grpc_slice_from_static_string", referenced from:
: "_grpc_error_unref", referenced from:
: "_grpc_transport_stream_op_batch_finish_with_failure", referenced from:
: Linker command failed with exit code 1 (use -v to see invocation)

#### Steps to reproduce:

Update from Xcode 8.3.3 to 9.1

Pod File:

```
platform :ios, '9.3'

target 'Alexandria' do
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI/Firestore', '~> 4.0'
  pod 'FirebaseUI/Storage', '~> 4.0'
  pod 'FirebaseUI/Auth', '~> 4.0'
  pod 'FirebaseUI/Facebook', '~> 4.0'
  pod 'FirebaseUI/Google', '~> 4.0'
  pod 'UITextField+Shake', '~> 1.1'
  pod 'SJFluidSegmentedControl', :git => 'https://github.com/adornoventura/SJFluidSegmentedControl.git'
  pod 'GoogleBooksApiClient'
  pod 'Kingfisher', '~> 4.0'
  pod 'BarcodeScanner'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Stripe'
  pod 'Lightbox'
  pod 'SwipeCellKit'
```

**Comment by paulb777** [comment] 2017-11-03 20:17
Duplicate of #423. I'll retitle that one to match this issue since this is a better title.

**Closed by paulb777** 2017-11-03 20:17 UTC
Labels: needs-triage
