### ISSUE TITLE
Unable to read the license file `LICENSE` for the spec `Firebase (7.9.0)`

### ISSUE THREAD

**Issue by Algashev** [firebase/firebase-ios-sdk#7803] opened 2021-03-30 06:01 UTC
### Environment

  * Xcode version: 12.4 (12D4e)
  * Firebase SDK version: 7.9.0
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics, Crashlytics, RemoteConfig

### Steps to reproduce: 
```
pod update
``` 
or
```
pod install
``` 
`pod update` log:
```
Downloading dependencies
...
Installing Firebase 3.6.0 (was 6.34.0)
Installing Firebase 7.9.0 (was 6.34.0)
...
Installing GoogleUtilities 7.3.1 (was 6.7.2)
Installing GoogleUtilities 1.3.2 (was 6.7.2)
...
```
Console warning:
```
[!] Unable to read the license file `LICENSE` for the spec `Firebase (7.9.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.3.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (7.9.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.3.1)`

[!] [Xcodeproj] Generated duplicate UUIDs:

...
```

**Comment by Algashev** [comment] 2021-03-30 10:17
Deleting `pod 'Firebase/RemoteConfig'` from the Podfile fixes the issue.

**Comment by paulb777** [comment] 2021-03-30 14:19
This looks like a duplicate of #7782.

Please see the resolution and discussion there and let us know if you have any additional questions.

**Comment by oleg-moseyko** [comment] 2021-04-08 15:58
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


target 'ImageLockerMobile' do

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  # Pods for ImageLockerMobile
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'SDWebImagePhotosPlugin'


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'


  target 'ImageLockerMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!

  use_frameworks!

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
        def pod.build_type;
          # Uncomment one line depending on your CocoaPods version
           Pod::BuildType.static_library # >= 1.9
          # Pod::Target::BuildType.static_library # < 1.9
        end
      end
    end
  end

end

post_install do |installer|
    framework = installer.pods_project.frameworks_group["iOS"]["MobileCoreServices.framework"]
    framework.referrers.each do |ref|
        if ref.isa == "PBXBuildFile"
            ref.remove_from_project
        end
    end
    framework.remove_from_project
end


$ pod install
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `ImageLockerMobile`: RNCAsyncStorage, RNDeviceInfo, RNFBApp, RNFastImage, RNGestureHandler, RNImageCropPicker, RNPermissions, RNReanimated, RNSVG, RNScreens, RNTransferLibrary, react-native-config, react-native-image-picker, and react-native-netinfo
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.4)
Installing FBReactNativeSpec (0.63.4)
Installing Firebase (3.6.0)
Installing Firebase (7.9.0)
Installing FirebaseAnalytics (3.4.2)
Installing FirebaseCore (7.9.0)
Installing FirebaseCoreDiagnostics (7.10.0)
Installing FirebaseInstanceID (1.0.9)
Installing Folly (2020.01.13.00)
Installing GoogleDataTransport (8.4.0)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleUtilities (1.3.2)
Installing GoogleUtilities (7.3.1)
Installing Permission-Camera (2.2.2)
Installing Permission-PhotoLibrary (2.2.2)
Installing PromisesObjC (1.2.12)
Installing QBImagePickerController (3.4.0)
Installing RCTRequired (0.63.4)
Installing RCTTypeSafety (0.63.4)
Installing RNCAsyncStorage (1.12.0)
Installing RNDateTimePicker (3.0.9)
Installing RNDeviceInfo (5.6.5)
Installing RNFBApp (11.2.0)
Installing RNFastImage (7.0.2)
Installing RNGestureHandler (1.8.0)
Installing RNImageCropPicker (0.26.2)
Installing RNPermissions (2.2.2)
Installing RNReanimated (1.13.2)
Installing RNSVG (9.13.6)
Installing RNScreens (2.11.0)
Installing RNTransferLibrary (1.0.67)
Installing RNVectorIcons (7.0.0)
Installing RSKImageCropper (3.0.1)
Installing React (0.63.4)
Installing React-Core (0.63.4)
Installing React-CoreModules (0.63.4)
Installing React-RCTActionSheet (0.63.4)
Installing React-RCTAnimation (0.63.4)
Installing React-RCTBlob (0.63.4)
Installing React-RCTImage (0.63.4)
Installing React-RCTLinking (0.63.4)
Installing React-RCTNetwork (0.63.4)
Installing React-RCTSettings (0.63.4)
Installing React-RCTText (0.63.4)
Installing React-RCTVibration (0.63.4)
Installing React-callinvoker (0.63.4)
Installing React-cxxreact (0.63.4)
Installing React-jsi (0.63.4)
Installing React-jsiexecutor (0.63.4)
Installing React-jsinspector (0.63.4)
Installing ReactCommon (0.63.4)
Installing SDWebImage (5.10.0)
Installing SDWebImagePhotosPlugin (1.1.0)
Installing SDWebImageWebPCoder (0.2.5)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing libwebp (1.1.0)
Installing nanopb (2.30908.0)
Installing react-native-cameraroll (4.0.2)
Installing react-native-config (0.12.0)
Installing react-native-image-picker (2.3.4)
Installing react-native-netinfo (5.9.7)
Installing rn-fetch-blob (0.12.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 50 dependencies from the Podfile and 66 total pods installed.

[!] Unable to read the license file `LICENSE` for the spec `Firebase (7.9.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.3.1)`

[!] Unable to read the license file `LICENSE` for the spec `Firebase (7.9.0)`

[!] Unable to read the license file `LICENSE` for the spec `GoogleUtilities (7.3.1)`

[!] [Xcodeproj] Generated duplicate UUIDs:

.......
[!] [Xcodeproj] Generated duplicate UUIDs:

PBXAggregateTarget -- 072CEA044D2EF26F03496D5996BBF59F
PBXAggregateTarget -- 8D7F5D5DD528D21A72DC87ADA5B12E2D

[!] react-native-config has added 1 script phase. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.

**Comment by paulb777** [comment] 2021-04-08 16:04
Please examine the `Podfile.lock` to determine why Firebase 3.x components are being installed in addition to the expected 7.x ones.

**Comment by louicoder** [comment] 2021-04-10 09:36
This helped alot, I had some components for version 3.x.x being installed alongside those with version 7.x.x Causing the Duplication.

**Closed** 2021-04-10 14:17 UTC
Labels: GoogleUtilities, needs-info

**Comment by rmindo** [comment] 2021-04-16 18:26
In my case pod 'Firebase/Analytics' caused the issue, anything that has Firebase/ will duplicate.

**Comment by anabeatrizzz** [comment] 2021-05-09 20:30
@louicoder delete Pods folder or delete Podfile file?

**Comment by louicoder** [comment] 2021-05-10 04:04
@anabeatrizzz , never delete the Podfile. But you can always delete Podfile.lock and Pods folders. In your case delete both the Pods folder and Podfile.lock

**Comment by anabeatrizzz** [comment] 2021-05-10 23:05
@louicoder Ok, but didn't work for me :/
