### ISSUE TITLE
Error with Firestore

### ISSUE THREAD

**Issue by devLoop1** [firebase/firebase-ios-sdk#2909] opened 2019-04-29 01:45 UTC
When installing the service Firestore through cocoapods and start the application through the .xcworkspace file, I get several errors that can be seen in the screenshots I attached.
I hope you can help me.

  * Xcode version: 10.2.1
  * Firebase Component:  Firestore
  * Component version: 5.20.2

<img width="799" alt="Captura de Pantalla 2019-04-28 a la(s) 21 38 18" src="https://user-images.githubusercontent.com/48538624/56873222-dc4aa580-69fe-11e9-834f-479cee7dc5eb.png">
<img width="794" alt="Captura de Pantalla 2019-04-28 a la(s) 21 38 25" src="https://user-images.githubusercontent.com/48538624/56873223-dc4aa580-69fe-11e9-82bb-545e18f0c062.png">
<img width="792" alt="Captura de Pantalla 2019-04-28 a la(s) 21 38 31" src="https://user-images.githubusercontent.com/48538624/56873224-dce33c00-69fe-11e9-864c-7be4819ee988.png">
<img width="791" alt="Captura de Pantalla 2019-04-28 a la(s) 21 38 37" src="https://user-images.githubusercontent.com/48538624/56873225-dce33c00-69fe-11e9-894d-0da01516c971.png">

**Comment by morganchen12** [comment] 2019-04-29 06:22
Duplicate of #1419. You can ignore those warnings for the time being.

**Closed** 2019-04-29 18:07 UTC
Labels: api: firestore
