### ISSUE TITLE
LICENSE in this repo is not following APACHE's guideline

### ISSUE THREAD

**Issue by superarts** [firebase/firebase-ios-sdk#9175] opened 2022-01-06 23:48 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: ALL
  * Firebase SDK version: latest
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Core, Firestore
  * Target platform(s): `All`

#### Steps to reproduce:

Go to this file: https://github.com/firebase/firebase-ios-sdk/blob/master/LICENSE

APACHE license requires `Copyright [yyyy] [name of copyright owner]` to be inserted, but it's not properly done in this repo.

#### Relevant Code: 

```
   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0
```

**Comment by paulb777** [comment] 2022-01-06 23:52
Duplicate of #7340. See explanation at #7105

**Closed by paulb777** 2022-01-06 23:52 UTC
Labels: api: core

**Comment by superarts** [comment] 2022-01-06 23:56
Thank you @paulb777 ! I'll inform our legal team about this info.
