### ISSUE TITLE
FirebasePerformance 3.0.0 conflicts with Google TagManager 7.1.2

### ISSUE THREAD

**Issue by thorstenstark** [firebase/firebase-ios-sdk#2962] opened 2019-05-08 10:35 UTC
There seems to be a conflict when using Google TagManager 7.1.2 and FirebasePerformance in the same project. This issue also occurs with TagManager 7.1.1 and FirebasePerfromance >= 2.1. When using FirebasePerformance 2.0.x the app crashes during initialization when trying to call `-[FIRApp isAutomaticDataCollectionEnabled]`. 

  * Xcode version: 10..2.1
  * Firebase SDK version: 6.0
  * Firebase Component: Performance 
  * Component version: 3.0.0

#### Steps to reproduce:

* Install GoogleTagManager 7.1.2 and FirebasePerformance via CocoaPods
* Archive App

Produces following error:
```
Multiple commands produce '<redacted>/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework':
1) Target 'GoogleUtilities-00567490' has create directory command with output '<redacted>/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
2) Target 'GoogleUtilities-ac14cd06' has create directory command with output '<redacted>/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
```
Relevant lines from podfile.lock:

```
 - FirebaseABTesting (3.0.0):
    - FirebaseCore (~> 6.0)
    - Protobuf (~> 3.5)
  - FirebaseAnalytics (6.0.0):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.0)
    - GoogleAppMeasurement (= 6.0.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseCore (6.0.0):
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/Logger (~> 6.0)
  - FirebaseInstanceID (4.0.0):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebasePerformance (3.0.0):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.0)
    - FirebaseRemoteConfig (~> 4.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/ISASwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseRemoteConfig (4.0.0):
    - FirebaseABTesting (~> 3.0)
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.0)
    - GoogleUtilities/Environment (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - Protobuf (~> 3.5)
  - google-cast-sdk (4.3.3):
    - google-cast-sdk/Core (= 4.3.3)
    - Protobuf (~> 3.0)
  - google-cast-sdk/Core (4.3.3):
    - Protobuf (~> 3.0)
  - Google-Mobile-Ads-SDK (7.26.0)
  - GoogleAnalytics (3.17.0)
  - GoogleAppMeasurement (6.0.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - GoogleIDFASupport (3.14.0)
  - GoogleMobileAdsMediationMoPub (5.3.0.1):
    - Google-Mobile-Ads-SDK (>= 7.14.0)
    - mopub-ios-sdk/Core (= 5.3.0)
  - GoogleSymbolUtilities (1.1.2)
  - GoogleTagManager (7.1.2):
    - FirebaseAnalytics (~> 6.0)
    - GoogleAnalytics (~> 3.17)
    - GoogleUtilitiesLegacy (~> 1.3)
  - GoogleToolboxForMac/Defines (2.2.0)
  - GoogleToolboxForMac/Logger (2.2.0):
    - GoogleToolboxForMac/Defines (= 2.2.0)
  - "GoogleToolboxForMac/NSData+zlib (2.2.0)":
    - GoogleToolboxForMac/Defines (= 2.2.0)
  - GoogleUtilities/AppDelegateSwizzler (6.0.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.0.0)
  - GoogleUtilities/ISASwizzler (6.0.0)
  - GoogleUtilities/Logger (6.0.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.0.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.0.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.0.0)"
  - GoogleUtilities/Reachability (6.0.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.0.0):
    - GoogleUtilities/Logger
  - GoogleUtilitiesLegacy (1.3.2):
    - GoogleSymbolUtilities (~> 1.1)
  - GTMSessionFetcher/Core (1.2.1)
```

**Comment by paulb777** [comment] 2019-05-08 14:28
This might be a CocoaPods issue related to #2166

**Comment by paulb777** [comment] 2019-05-08 17:16
I'm not able to reproduce in a Podfile with only `FirebasePerfomance` and `GoogleTagManager`. It's possible that some of the other pods you're including are necessary to reproduce.

Either way, this is likely a duplicate of #2166 with a repro of explicitly requesting the superset of GoogleUtilities subspec's required for all dependencies.

**Comment by paulb777** [comment] 2019-05-14 15:29
Closing for now. Will reopen on new information showing this is different from #2166.

**Closed by paulb777** 2019-05-14 15:29 UTC
Labels: GoogleUtilities, api: performance, api: tagmanager
