### ISSUE TITLE
Coverage differences without change

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#7491] opened 2021-02-09 19:10 UTC
Please investigate why #7490 and #7488 show coverage changes for DynamicLinks and Database even though there were no changes in those libraries.

**Comment by granluo** [comment] 2021-02-09 21:52
The reason for that is probably caused by changes happening between the base commit and the head commit.

On solution could be update the base commit to the head of the merged branch, master in this case.

**Comment by paulb777** [comment] 2021-02-09 22:38
Hmm, neither of those libraries have had any recent changes?

**Comment by granluo** [comment] 2021-02-23 01:19
Have tried `scripts/build.sh` and unit tests via podspec in #7585, they have the same result.

I tried locally on the base commit, and the result is the same as the one in the pull requests. 
Based on the `xcresult`s, the difference of code coverages is from [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m#L1501-L1596), where the coverage in a pull request is 83.9% while the one in the base commit is 59.1%.
Has rerun the [workflow runs](https://github.com/firebase/firebase-ios-sdk/actions/runs/590239350) to upload new code coverages to see if the data is updated. Will also investigate why the tests for code coverage are not consistent between the merge and pull requests.

**Comment by granluo** [comment] 2021-02-24 02:52
Looks like the eventCode is not consistent  [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m#L1501-L1596). Unit tests do not have a consistent coverage on the switch cases. I suspect that is due to the stream?

**Comment by paulb777** [comment] 2021-02-24 03:31
Oh good find.  Do you know if there is best practice for measuring coverage on unit tests that exercise networking code that is not consistent? I wonder if there should be more mocking?

cc: @schmidt-sebastian @maksymmalyhin @ryanwilson

**Comment by maksymmalyhin** [comment] 2021-02-24 15:29
Looks like currently we use both unit and integration tests for measuring coverage. We may consider excluding less stable integration tests from the measurement. Also I'd be curious what exactly conditions lead to different coverage for the tests. Maybe we can just make it more stable. I'll take a look and let you know if I find something.

**Comment by granluo** [comment] 2021-02-25 00:06
[Unit tests ](https://github.com/firebase/firebase-ios-sdk/blob/master/scripts/code_coverage_report/pod_test_code_coverage_report.sh#L37)should be the one measured in the coverage workflow. Except for Firestore and Peformance, tests are running unit in podspecs, e.g. [database](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDatabase.podspec#L44-L57). I ran locally and it turned out the [safeHandleEvent](https://github.com/firebase/firebase-ios-sdk/blob/feb5ce95174d5bfa2b43019c1898266b14782faa/FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m#L1501) did not have a consistent number of calls as well. If the internet is disconnected, the coverage will be consistent since only [NSStreamEventErrorOccurred](https://github.com/firebase/firebase-ios-sdk/blob/feb5ce95174d5bfa2b43019c1898266b14782faa/FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m#L1521) will be called.
If unit tests are using network, we probably need to mock the return code.

**Closed** 2023-05-23 19:01 UTC
Labels: Infrastructure
