### ISSUE TITLE
Crash: `[FIRCoreDiagnostics sendDiagnosticsData:]` leads to an "unrecognized selector sent to instance"

### ISSUE THREAD

**Issue by elincoln** [firebase/firebase-ios-sdk#8047] opened 2021-05-07 00:17 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5 (12E262)
  * Firebase SDK version: 7.11.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Crashlytics, Core

#### Steps to reproduce:

Launch app in iOS 14.5 simulator
`[FIRCoreDiagnostics sendDiagnosticsData:]` leads to a crash: 
```
2021-05-06 16:47:31.477146-0700 Unearth[73286:3123244] -[__NSSingleEntryDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7b08002d52c0
2021-05-06 16:47:31.796546-0700 Unearth[73286:3123244] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSSingleEntryDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7b08002d52c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20431d2f +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff204274cf ___forwarding___ + 1455
	4   CoreFoundation                      0x00007fff204297a8 _CF_forwarding_prep_0 + 120
	5   Unearth                             0x0000000110dd36ee __50-[GULHeartbeatDateStorage setHearbeatDate:forTag:]_block_invoke + 398
	6   Foundation                          0x00007fff208dd108 -[NSFileCoordinator _invokeAccessor:thenCompletionHandler:] + 74
	7   Foundation                          0x00007fff208dd475 __98-[NSFileCoordinator coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:]_block_invoke + 106
	8   Foundation                          0x00007fff208e0398 __110-[NSFileCoordinator(NSPrivate) _coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:]_block_invoke.347 + 248
	9   Foundation                          0x00007fff208dec6e -[NSFileCoordinator(NSPrivate) _withAccessArbiter:invokeAccessor:orDont:andRelinquishAccessClaim:] + 601
	10  Foundation                          0x00007fff208e00ab -[NSFileCoordinator(NSPrivate) _coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:] + 1106
	11  Foundation                          0x00007fff208dd3ec -[NSFileCoordinator coordinateReadingItemAtURL:options:writingItemAtURL:options:error:byAccessor:] + 99
	12  Unearth                             0x0000000110dd33da -[GULHeartbeatDateStorage setHearbeatDate:forTag:] + 874
	13  Unearth                             0x0000000110e0662d -[FIRCoreDiagnostics setHeartbeatFlagIfNeededToConfig:] + 669
	14  Unearth                             0x0000000110e05eda __42-[FIRCoreDiagnostics sendDiagnosticsData:]_block_invoke + 730
	15  libclang_rt.tsan_iossim_dynamic.dyl 0x00000001139fb76c _ZN6__tsanL24invoke_and_release_blockEPv + 12
	16  libclang_rt.tsan_iossim_dynamic.dyl 0x00000001139fb4c2 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
	17  libdispatch.dylib                   0x00000001190ca74e _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00000001190d0f9a _dispatch_lane_serial_drain + 796
	19  libdispatch.dylib                   0x00000001190d1c67 _dispatch_lane_invoke + 436
	20  libdispatch.dylib                   0x00000001190dda7a _dispatch_workloop_worker_thread + 872
	21  libsystem_pthread.dylib             0x00007fff603404c0 _pthread_wqthread + 314
	22  libsystem_pthread.dylib             0x00007fff6033f493 start_wqthread + 15
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSSingleEntryDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7b08002d52c0'
terminating with uncaught exception of type NSException
CoreSimulator 757.5 - Device: iPhone 11 Pro Max (8354ABC3-297B-4640-8814-0101E5EFD7D6) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 11 Pro Max
```
#### Relevant Code:

https://github.com/google/GoogleUtilities/blob/2124e8645fa00ff4e8c219f29e5a11aa7c5e6667/GoogleUtilities/Environment/GULHeartbeatDateStorage.m#L136 
assumes that 
https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities/Environment/GULSecureCoding.m#L21
returns something that can be cast to a `NSMutableDictionary`, but it's not, in my particular case it is instead returning a `__NSSingleEntryDictionaryI`

**Comment by paulb777** [comment] 2021-05-07 00:47
@elincoln Sorry about the trouble and thanks for the detailed report and analysis.  We'll investigate.

**Comment by maksymmalyhin** [comment] 2021-05-07 14:26
Here are our finding so far:
- in GoogleUtilities version 7.4.0 a mutable copy of the stored dictionary is made before modifying it (see [here](https://github.com/google/GoogleUtilities/blob/66f5945ac3a4c4ac268bf94c31f226116b14e327/GoogleUtilities/Environment/GULHeartbeatDateStorage.m#L118))
- GoogleUtilities version 7.4.0 stores `NSDictionary` to the file in contrast to previous versions storing `NSMutableDictionary`. Previous versions don't do mutable copy before using unarchived dictionary (see [here](https://github.com/google/GoogleUtilities/blob/1c47ea135322768023ecdcc9db79bf3df821209f/GoogleUtilities/Environment/GULHeartbeatDateStorage.m#L151))
- Based on above, it looks like the crash may be caused by installing an app version with older GoogleUtilities version on top of the app version with GoogleUtilities version 7.4.0. In this case the older GoogleUtilities version will try to read and modify immutable dictionary stored by the newer version.

@elincoln, @kevinLaRosa could you please confirm if it could be that the crash happens only when an older version of the app is installed on top of the newer version of the app?

**Comment by maksymmalyhin** [comment] 2021-05-07 15:07
I could reproduce the crash on my end with the described steps.

**Comment by ncooke3** [comment] 2021-05-07 17:39
We are working on a patch fix and will update this thread accordingly.

**Comment by KevinLaRosa** [comment] 2021-05-07 18:15
> Here are our finding so far:
> 
> * in GoogleUtilities version 7.4.0 a mutable copy of the stored dictionary is made before modifying it (see [here](https://github.com/google/GoogleUtilities/blob/66f5945ac3a4c4ac268bf94c31f226116b14e327/GoogleUtilities/Environment/GULHeartbeatDateStorage.m#L118))
> * GoogleUtilities version 7.4.0 stores `NSDictionary` to the file in contrast to previous versions storing `NSMutableDictionary`. Previous versions don't do mutable copy before using unarchived dictionary (see [here](https://github.com/google/GoogleUtilities/blob/1c47ea135322768023ecdcc9db79bf3df821209f/GoogleUtilities/Environment/GULHeartbeatDateStorage.m#L151))
> * Based on above, it looks like the crash may be caused by installing an app version with older GoogleUtilities version on top of the app version with GoogleUtilities version 7.4.0. In this case the older GoogleUtilities version will try to read and modify immutable dictionary stored by the newer version.
> 
> @elincoln, @KevinLaRosa could you please confirm if it could be that the crash happens only when an older version of the app is installed on top of the newer version of the app?

First of all, thanks for your investigation, you’ve helped me a lot to get a hint to my issue, It seems we have wrongly updated our SPM version of firebase when we fixed the exact version to `7.4.0` after a previous release in `up to next major 7.4.0` in the last release of our APP, I'm investigating to reproduce the issue.

**Comment by elincoln** [comment] 2021-05-07 18:50
@maksymmalyhin Xcode SPM did indeed have GoogleUtilities version 7.3.0, and deleting and reinstalling clean did resolve the issue.
Then I did a right-click "Update package" in Xcode and it pulled down 7.4.0.

I do toggle between two clones of the same repo, so I guess this is caused from a stale SPM cache for one of the repos? 

I have no idea why SPM didn't automatically update to 7.4.0... Firebase is currently my only SPM: 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/1448144/117495223-33f34400-af2a-11eb-8d46-9bd8c7487635.png">

Does SPM get influenced by which Github tags are "published releases"?? https://github.com/google/GoogleUtilities/releases shows 7.3.0 as the "latest release"

**Comment by maksymmalyhin** [comment] 2021-05-07 19:23
@elincoln A couple notes that may be helpful:
- once dependencies have been resolved SPM doesn't update package versions unless explicitly asked (in command line, "Update package" action or "File" ->"Swift Packages->Update to Latest Package Versions " menu, etc.)
- The installed package versions are specified in `Package.resolved` file
- SPM should be able pick up any version tag even if it is not marked as a release on GitHub, so 7.4.0 from https://github.com/google/GoogleUtilities/tags should be available for install.

**Comment by leechoohyoung** [comment] 2021-05-10 04:09
same here.
@ncooke3 could you tell me when the new version will be released?

**Comment by paulb777** [comment] 2021-05-10 16:04
@leechoohyoung We're working to make a release in the next few days.

In the meantime, rebuilding with GoogleUtilities 7.4.0 should resolve the crash. We also expect that uninstalling before installing an app built with an older version of GoogleUtilities would prevent the crash.

**Closed** 2021-05-11 00:48 UTC
Labels: GoogleUtilities, Swift Package Manager, api: crashlytics
