### ISSUE TITLE
[NSProcessInfo isiOSAppOnMac] crash 

### ISSUE THREAD

**Issue by wangjunhua1** [firebase/firebase-ios-sdk#7978] opened 2021-04-27 04:41 UTC
ios 14.0.0 crash 

![image](https://user-images.githubusercontent.com/11474284/116186245-d440b000-a755-11eb-840c-d8fe27f23f63.png)

    sdk version  
    #firebase
    pod 'Firebase/Crashlytics', '7.11.0'
    pod 'Firebase/Analytics', '7.11.0'
    pod 'Firebase/RemoteConfig', '7.11.0'

    pod 'Firebase', '7.11.0'
    pod 'FirebaseAnalytics', '7.11.0'
    pod 'FirebaseCore' ,'7.11.0'
    pod 'FirebaseCoreDiagnostics' ,'7.11.0'
    pod 'FirebaseCrashlytics', '7.11.0'
    pod 'FirebaseInstallations' ,'7.11.0'
    pod 'GoogleAppMeasurement', '7.11.0'
    pod 'GoogleUtilities', '7.3.1'
    pod 'GoogleDataTransport', '8.4.0'

**Comment by paulb777** [comment] 2021-04-27 14:35
This is a duplicate off #7413. See the resolution there.

**Closed by paulb777** 2021-04-27 14:35 UTC
Labels: api: ads
