### ISSUE TITLE
Xcode beta 6 iOS code won't compile with Firebase SDK

### ISSUE THREAD

**Issue by ravichandra-ayla** [firebase/firebase-ios-sdk#11688] opened 2023-08-17 10:11 UTC
### Description

Xcode beta 6 with Firebase compile failure with Firebase SDK.

I have removed all firebase linked libs and code and then code compile was success.

Issue is while compiling it throws an error, reported here too for your ref.

https://github.com/CocoaPods/CocoaPods/issues/12012
https://github.com/CocoaPods/CocoaPods/pull/12009#issuecomment-1674566539

Error:-
<img width="538" alt="Screenshot 2023-08-17 at 3 36 09 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/63033150/148b0edb-a5d1-4ac1-b77f-ece459419021">

### Reproducing the issue

- Create iOS project
- Include Firebase products 
              pod 'Firebase/DynamicLinks'
- Do pod install
`Installing Firebase (10.10.0)
Installing FirebaseCore (10.10.0)
Installing FirebaseCoreInternal (10.10.0)
Installing FirebaseDynamicLinks (10.10.0)`
- Compile and see build error shows as described 

### Firebase SDK Version

10.10.0

### Xcode Version

Version 15.0 beta 6 (15A5219j)

### Installation Method

CocoaPods

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### Relevant Log Output

```shell
More info can be found here 

https://github.com/CocoaPods/CocoaPods/issues/12012
https://github.com/CocoaPods/CocoaPods/pull/12009#issuecomment-1674566539
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment] 2023-08-17 14:40
Hi @ravichandra-ayla, I'm closing this as it is a duplicate of https://github.com/firebase/firebase-ios-sdk/issues/11608. Please see the conversation there.

**Closed by ncooke3** 2023-08-17 14:40 UTC
Labels: api: core
