### ISSUE TITLE
157239855: When app is not installed - Firebase Dynamic Link Preview not displayed on click the link in iPad6 Device - iPadOS 13.1

### ISSUE THREAD

**Issue by pbtouchtier** [firebase/firebase-ios-sdk#3938] opened 2019-09-27 11:56 UTC
**Test environment**
> Xcode version: 11.0
> Firebase SDK version: 5.20.2
> Firebase Component: FirebaseDynamicLinks
> Component version: 3.4.3
> Device: iPad 6, iPad OS 13.1

What is the problem?
Dynamic Link Preview enabled 
    If the app was not installed, when clicking the link in notes - the dynamic link preview not displayed in device its directly open safari browser and redirect to web URL page link.

**Comment by dmandar** [comment] 2019-09-27 23:20
Does the app preview page open on other devices? Can you check the dynamic link does not have any warnings when you add the query param "?d=1"

**Comment by re-ckart** [comment] 2019-10-01 11:35
We have the same issue. I commented this in the following issue but seems like this is the correct one to post it.
https://github.com/firebase/firebase-ios-sdk/issues/3918#issuecomment-535912331

Here is an example link: https://rex.codes/v1/63cdf012-ccb4-4c8d-b8a5-39ee6d18def2  (no errors, warnings etc with `d=1`)
Works fine on devices prior iOS13

**Comment by dmandar** [comment] 2019-10-02 01:19
Hi..we are not seeing any reproable issues on iOS 13 at the moment. @pbtouchtier is this only repro on iPadOS for you?

**Comment by re-ckart** [comment] 2019-10-02 12:20
> Hi..we are not seeing any reproable issues on iOS 13 at the moment. 

So you are saying that you **get** redirected to the AppStore when you click on the link I provided in my comment above with an iPad with iOS 13? Because this does **not** work on our iPad (iOS 13.1.2) but does on the ones with prior version (iOS 12.2)

Also I am not sure if this is really an SDK issue. It seems more like an issue on the Firebase servers as the redirect should happen there. @dmandar am I right?

**Comment by pbtouchtier** [comment] 2019-10-03 07:35
> Hi..we are not seeing any reproable issues on iOS 13 at the moment. @pbtouchtier is this only repro on iPadOS for you?

Case - On App not installed in the device and click on link 
Expectation - Redirect to Dynamic link preview page

Case Result in iPhone 11 Pro Max- iOS 13.1 simulator - its display dynamic link preview page
Case Result in iPad6 Device (iPad OS 13.1) - 
On click link - Redirect to the browser and open the link parameter URL(happens same as the dynamic link on web)
On long press the dynamic link displayed the preview page and on resized popup view preview page displayed.

**Comment by jffmrk** [comment] 2019-10-25 02:04
Safari on iPad with iPadOS 13 and above has "Request Desktop Site" turned on be default in the Settings app. The user agent reported by Safari in this case is the same user agent as Safari on a Mac. Firebase would need to use some other detection mechanism to determine if the user is on an iPad or a Mac. I've modified some of my sites to use javascript to check navigator.maxTouchPoints to see if it is a "touch-enabled Mac" which would indicate it is an iPad.

Here's an example - load this on your iPad with iOS 13 to see:
https://output.jsbin.com/haroriw/

**Comment by dmandar** [comment] 2020-01-31 08:19
Thanks for reporting. Internal bug b/148649490 opened for tracking. Will update as we have more info.

**Comment by paul-bonnel-fr** [comment] 2020-02-18 11:32
Do you guys have any updates on this ? 
In the mean time @jffmrk's workaround is great :)

**Comment by vthommeret** [comment] 2020-08-09 04:38
I'm not sure if this is exactly the same issue but I'm seeing that dynamic links generated for passwordless auth (https://firebase.google.com/docs/auth/ios/email-link-auth) simply don't open the app on iPadOS 13. The exact same link opened (with the same app installed) on my iOS 13 on my iPhone opens the app.

Intuitively it seems like the issue is because the Firebase site isn't detecting the device as a mobile device due iPad OS 13's desktop browsing changes although requesting the mobile website doesn't seem to address the issue.

**Comment by eldhosembabu** [comment] 2021-10-11 17:48
This issue should be fixed by now (Tracking internal Bug : b/141873818). Closing this github issue.

**Closed by eldhosembabu** 2021-10-11 17:48 UTC
Labels: api: dynamiclinks, iOS 13
