### ISSUE TITLE
Cannot do xcodebuild clean

### ISSUE THREAD

**Issue by Ralle** [firebase/firebase-ios-sdk#12140] opened 2023-11-24 20:33 UTC
### Description

When I run the following command:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project App.xcodeproj clean
```

On my project, that has `firebase-ios-sdk` added as a Swift Package Manager dependency, I get an error.
Here's a sample project.
[Test1.zip](https://github.com/firebase/firebase-ios-sdk/files/13462032/Test1.zip)

It works without this project as dependency, so it's clearly something going wrong in here.

### Reproducing the issue

- Open the attached project above.
- Run the `xcodebuild -project <project> clean` command and see it fail

### Firebase SDK Version

10.11

### Xcode Version

15.0.1, 14.3, etc.

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
rasmus@Pirkefnirt Test1 % /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project Test1.xcodeproj clean
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project Test1.xcodeproj clean

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph


Resolved source packages:
  GTMSessionFetcher: https://github.com/google/gtm-session-fetcher.git @ 3.1.1
  gRPC: https://github.com/google/grpc-binary.git @ 1.49.1
  leveldb: https://github.com/firebase/leveldb.git @ 1.22.3
  nanopb: https://github.com/firebase/nanopb.git @ 2.30909.0
  InteropForGoogle: https://github.com/google/interop-ios-for-google-sdks.git @ 100.0.0
  Firebase: https://github.com/firebase/firebase-ios-sdk.git @ 10.18.0
  Promises: https://github.com/google/promises.git @ 2.3.1
  SwiftProtobuf: https://github.com/apple/swift-protobuf.git @ 1.25.1
  GoogleUtilities: https://github.com/google/GoogleUtilities.git @ 7.12.1
  GoogleDataTransport: https://github.com/google/GoogleDataTransport.git @ 9.2.5
  AppCheck: https://github.com/google/app-check.git @ 10.18.0
  GoogleAppMeasurement: https://github.com/google/GoogleAppMeasurement.git @ 10.17.0
  abseil: https://github.com/google/abseil-cpp-binary.git @ 1.2022062300.0

error: Could not delete `/Users/rasmus/Library/Developer/Xcode/DerivedData/Test1-ebqxjjcrukatqiefcubratdkjdrk/SourcePackages/checkouts/nanopb/build` because it was not created by the build system.
    note: To mark this directory as deletable by the build system, run `xattr -w com.apple.xcode.CreatedByBuildSystem true /Users/rasmus/Library/Developer/Xcode/DerivedData/Test1-ebqxjjcrukatqiefcubratdkjdrk/SourcePackages/checkouts/nanopb/build` when it is created.
error: Could not delete `/Users/rasmus/Library/Developer/Xcode/DerivedData/Test1-ebqxjjcrukatqiefcubratdkjdrk/SourcePackages/checkouts/nanopb/build` because it was not created by the build system.
    note: To mark this directory as deletable by the build system, run `xattr -w com.apple.xcode.CreatedByBuildSystem true /Users/rasmus/Library/Developer/Xcode/DerivedData/Test1-ebqxjjcrukatqiefcubratdkjdrk/SourcePackages/checkouts/nanopb/build` when it is created.

** CLEAN FAILED **
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json
{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
        "version" : "1.2022062300.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "5746b2d35c91c50581590ed97abe4c06b5037274",
        "version" : "10.18.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "5de0369ee79ad096c164eb3afeb7921d92a43b58",
        "version" : "10.18.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "6b332152355c372ace9966d8ee76ed191f97025e",
        "version" : "10.17.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "aae45a320fd0d11811820335b1eabc8753902a40",
        "version" : "9.2.5"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "bc27fad73504f3d4af235de451f02ee22586ebd3",
        "version" : "7.12.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "a673bc2937fbe886dd1f99c401b01b6d977a9c98",
        "version" : "1.49.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "d415594121c9e8a4f9d79cecee0965cf35e74dbd",
        "version" : "3.1.1"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "9d108e9112aa1d65ce508facf804674546116d9c",
        "version" : "1.22.3"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "e70e889c0196c76d22759eb50d6a0270ca9f1d9e",
        "version" : "2.3.1"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "07f7f26ded8df9645c072f220378879c4642e063",
        "version" : "1.25.1"
      }
    }
  ],
  "version" : 2
}

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-11-25 16:07
Looks like a duplicate of an Xcode issue described at #11426.

The workaround is `xcodebuild -scheme Test1 clean`

**Comment by Ralle** [comment] 2023-11-28 09:07
Not a good workaround for me. I'm using Capacitor CLI and it invokes the other command. This problem only occurs with `firebase-ios-sdk`. None of my other Swift Package Manager dependencies have this problem.

**Comment by qeireal** [comment] 2024-01-14 06:33
@Ralle Did you manage to solve this problem? I am facing the same problem right now.

**Comment by kuquert** [comment] 2024-01-17 17:12
Adding `-scheme` option fixed it for me. This error started happening after we migrated Firebase from cocoapods to SPM

**Comment by PeimanHaghighat** [comment] 2024-02-15 19:36
@Ralle Did you fix this issue? Thanks.

**Comment by lmalagon21** [comment] 2024-02-21 23:07
in Xcode Remove firebase-ios-sdk from package dependencies App, and Add firebase-ios-sdk pakage dependiencies into Pods Project, use cap sync ios again from terminal project

**Comment by paulb777** [comment] 2024-05-21 21:33
Closing since this is an Xcode issue and not much we can do.

**Closed by paulb777** 2024-05-21 21:33 UTC
Labels: Swift Package Manager
