### ISSUE TITLE
Issue causing crash app in iOS 17.4

### ISSUE THREAD

**Issue by Aslanyan99n** [firebase/firebase-ios-sdk#12526] opened 2024-03-12 10:58 UTC
### Description
App is crashing when launching

![Uploading Screenshot 2024-03-12 at 11.40.51.png…]()

### Firebase SDK Version

10.22.1

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2024-03-12 11:44
Thanks for reporting, @Aslanyan99n. Unfortunately, I'm unable to open the screenshot you shared. Could you try to re-upload the screenshot of the full error?

**Comment by Aslanyan99n** [comment] 2024-03-12 13:59
<img width="1679" alt="Screenshot 2024-03-12 at 11 40 51" src="https://github.com/firebase/firebase-ios-sdk/assets/68569879/14135895-6f5b-4306-a416-0e0407f7bc83">

**Comment by mattiacantalu** [comment] 2024-03-12 14:32
Following the 3d.. same on us. Xcode 15.3, iOS 17.4 and latest firebase update.

**Comment by paulb777** [comment] 2024-03-12 14:38
This is a duplicate of #12485. Please see the discussion there.

**Closed as completed by paulb777** 2024-03-12 14:38 UTC
Labels: api: dynamiclinks

**Comment by alflix** [comment] 2024-04-08 12:08
same on us. Xcode 15.3, iOS 17.4 and latest firebase update. also I remove the FirebaseDynamicLinks
