### ISSUE TITLE
Actual app auth UIDs appearing in my XCTest unit tests

### ISSUE THREAD

**Issue by datureezy** [firebase/firebase-ios-sdk#6811] opened 2020-10-23 04:22 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____12.0.1
  * Firebase SDK version: _____6.34.0
  * Firebase Component: _____ Auth
  * Component version: _____ 6.34.0
  * Installation method: CocoaPods

#### Steps to reproduce:

What happened? How can we make the problem occur?
I have built out extensive testing for my app. Also, because of my app's architecture, I had to run the `FirebaseApp.configure()` call in the AppDelegate's `init()` function.

But I'm facing a problem in my testing suite, where out of ALL my tests, I always have one test fail on my when the test suite is run. There must be something happening with the FirebaseApp.configure() call that's hijacking the testing suite, and actually pushing a real, live `auth.uid` string out, such as: `kD1SncZ8lXSJgN8Ze8NNZ5QYDms2`.

When I run the testing suite as a whole, the real production uid like `kD1SncZ8lXSJgN8Ze8NNZ5QYDms2` pops out on a test 80% of the time; 20% of the time, it doesn't.
When I run the failing test by itself, it always passes and pushes out my mock uids.

After attempting to debug this issue, my best guess is that the testing suite runs, but the launching of the simulator and the running of the AppDelegate initializing code does also happen in parallel. The very initial code of the real app runs, the auth gets populated with real live data (and in turn affecting my app state), and my unit tests gets affected in that split second. , 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by morganchen12** [comment] 2020-10-23 16:49
Hey @datureezy, in order to debug this issue we'll need to know how your tests are being set up to replace the live uid with a fake test value. If you can provide a sample test project, that would be ideal, but otherwise sharing code snippets and a description of your test setup will be helpful as well.

**Comment by datureezy** [comment] 2020-10-26 17:24
```AppDelegate``` Setting up Firebase

```    
override init() {
        guard
            let googleServiceInfoPlist = Bundle.main.object(forInfoDictionaryKey: "GoogleServiceInfoPlist") as? String,
            let filePath = Bundle.main.path(forResource: googleServiceInfoPlist, ofType: "plist"),
            let fileOptions = FirebaseOptions(contentsOfFile: filePath)
        else {
            assert(false, "Firebase File Options do not exist.")
            return
        }
        
        FirebaseApp.configure(options: fileOptions)
    }
```


```AuthComponentProtocol``` Real and mock auth components adhere to this protocol

```
protocol AuthComponentProtocol {
    var uid: String? { get }
    var user: User? { get set }
    
    func checkAuthState(completion: @escaping AuthStateCompletion)
    func stopAuthStateCheck()
    
    func convertAnonymousAccountToPatron(withEmail email: String, password: String, completion: @escaping StringResultCompletion)
    func createAnonymousAccount(completion: @escaping StringResultCompletion)
    
    func logIn(withEmail email: String, password: String, completion: @escaping StringResultCompletion)
    
    func signOut(completion: @escaping OptionalErrorCompletion)
}
```

```Real Auth Component```

```
class AuthComponent: AuthComponentProtocol {
    
    static let shared = AuthComponent()
    
    private let auth = Auth.auth()
    
    private var authStateHandle: AuthStateDidChangeListenerHandle?
    
    var user: User?
    var uid: String? {
        return user?.uid
    }
}
```

```Mock Auth Component```

```
class MockAuthComponent: AuthComponentProtocol {
    
    let authState: AuthState
    let isAuthWorking: Bool
    
    init(authState: AuthState, isAuthWorking: Bool) {
        self.authState = authState
        self.isAuthWorking = isAuthWorking
        
        if case let AuthState.hasAccount(uid: uid) = authState, isAuthWorking {
            self.uid = uid
        } else if case AuthState.noAccount = authState, isAuthWorking {
            self.uid = mockNewAnonymousUserUID
        } else {
            self.user = nil 
            self.uid = nil
        }
    }
    
    var user: User?
    var uid: String?
}
```

```This is the test that fails for me; but this test is creating a view model that is creating a *MOCK* auth component, yet it occasionally pushes out a real live uid from my development server.```

```
func testAdminAccountInitializationWith_FailingAuth_WorkingDB_ApprovedLocation_ApprovedNotification() {
        appStateFor_InitialLaunch_INVALID()
        
        let analytics = analytics_
        let notification = notification_approved

        let viewModel = LoadingViewModel(
            analytics: analytics,
            auth: auth_hasAccountWMockUID_failing,
            db: db_admin_working,
            location: location_working_approved,
            notification: notification,
            remoteConfig: remoteConfig_DishesRequireApproval
        )
        
        let exp = expectation(description: "")
        var appPermissions: [AppPermission]?
        
        viewModel.initializeApp { appPerms in
            appPermissions = appPerms
            exp.fulfill()
        }
        
        waitForExpectations(timeout: 5, handler: nil)
        
        XCTAssertFalse(mainStore.state.isAuthenticated)
        XCTAssertEqual(mainStore.state.uid, nil)
        XCTAssertEqual(mainStore.state.userType, .anonymous)
        XCTAssertEqual(analytics.hasLogAnonymousAccountCreated, 0)
        XCTAssertEqual(analytics.hasLogAppInitialized, 1)
        XCTAssertEqual(analytics.hasLogAuthError, 1)
        XCTAssertEqual(analytics.hasLogDBReadError, 0)
        XCTAssertEqual(analytics.hasLogDBWriteError, 0)
        XCTAssertEqual(notification.hasRegisterUserTags, 0)
        XCTAssertEqual([AppPermission](), appPermissions)
    }
```

```
let auth_hasAccountWMockUID_failing = MockAuthComponent(
    authState: .hasAccount(uid: mockExistingUserUID),
    isAuthWorking: false
)
```

And with that mock auth component above, the uid should always be nil...

```
    init(authState: AuthState, isAuthWorking: Bool) {
        self.authState = authState
        self.isAuthWorking = isAuthWorking
        
        if case let AuthState.hasAccount(uid: uid) = authState, isAuthWorking {
            self.uid = uid
        } else if case AuthState.noAccount = authState, isAuthWorking {
            self.uid = mockNewAnonymousUserUID
        } else {
            self.user = nil 
            self.uid = nil <<< This is the case that should be hit for the mock auth component initialization, but the production uid hijacks my component and pushes out: kD1SncZ8lXSJgN8Ze8NNZ5QYDms2, instead of nil.
        }
    }
```

**Comment by datureezy** [comment] 2020-10-26 17:27
Just ran a test and it failed for me.

Although I'm using mock components, on this one test, it's pulling out the uid value of the logged in user on my simulator device.

<img width="1784" alt="Screen Shot 2020-10-26 at 12 26 08 PM" src="https://user-images.githubusercontent.com/9462299/97206305-889d5180-1786-11eb-9775-bd6fa6bf4c9c.png">

I could reset my simulator, but because my app creates an anonymous user account if there is no logged in user on the device, then in that scenario, the unit test will push out the uid of that user created on start up.

**Comment by morganchen12** [comment] 2020-10-26 17:47
From this code it's not clear to me how the real Auth object is replacing the mock Auth you've assigned in your test. Even if the real Auth instance is creating an anonymous user, the way you've set up your viewmodel should prevent that user's uid from being accessed unless the viewmodel is referencing the default Auth instance directly.

The inconsistency may be a result of the Auth instance's anonymous user creation racing with your unit test.

**Comment by datureezy** [comment] 2020-10-26 17:51
Thank you for your responses, Morgan.

```The inconsistency may be a result of the Auth instance's anonymous user creation racing with your unit test.```

I completely agree. It's some sort of race condition, that's my guess too.

I just run the tests over again and they all pass.

I only brought it up to point out this instance, and maybe you guys would have the solution at hand to prevent the race condition from happening? If not, no sweat. 

I love Firebase, nonetheless, and look forward to the event tomorrow!

You can close this ticket if there is no way to prevent the racing to your knowledge.

**Comment by morganchen12** [comment] 2020-10-26 18:26
In your unit tests the race can be prevented by avoiding initializing the default Auth instance altogether, but this is dependent on your app's architecture. I'll close this issue since it seems to be usage-related and not a bug in Firebase, but if you need help preventing Auth initialization in tests or have any other questions feel free to continue commenting here.

**Closed by morganchen12** 2020-10-26 18:26 UTC
Labels: api: auth, type: question
