### ISSUE TITLE
Firebase SDK for iOS - Zombie Object crash

### ISSUE THREAD

**Issue by sehdich** [firebase/firebase-ios-sdk#8573] opened 2021-08-25 09:58 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1 (12E507)
  * Firebase SDK version: 8.6.0
  * Installation method: Swift Package Manager
  * Firebase Component: Remote Config, Messaging, In-app messaging, Crashlytics, Analytics

#### Steps to reproduce:

When "Zombie Objects" detection is turned on within the Scheme configuration an `EXC_BAD_ACCESS` crash on the `FBLPromise` object happens. (`Thread 9: EXC_BAD_ACCESS (code=1, address=0x555555555552)`)

![Screenshot 2021-08-25 at 11 49 59](https://user-images.githubusercontent.com/6875817/130769086-113dc99b-a635-464f-a53b-32f2462ffd84.png)

#### Relevant Code:

In General it's just creating a new empty Project within Xcode, add Firebase and enabled `Zombie Objects` within the configuration of the Scheme:

1.) Create a new empty Project within Xcode
2.) Integrate Firebase via Swift Package Manager
3.) Setup as described (call `FirebaseApp.configure()` an add a `GoogleService-Info.plist`
**4.) Enable Zombie Objects and malloc guards within the configuration of the scheme:**
![Zombie_configuration](https://user-images.githubusercontent.com/6875817/130769843-be37edbc-a155-4394-9cef-8e1fad22f50e.png)

5.) Start the App and wait about 1-2 seconds -> App will crash with the `EXC_BAD_ACCESS` described above

NOTICE: In some cases it does not crash when the App is already installed, but it will crash everytime the App is freshly installed.

**Comment by maksymmalyhin** [comment] 2021-08-25 14:55
@sehdich Sorry for the trouble. The bug looks like a duplicate of #8321. We are still working on a fix for it. In the meanwhile you may try the workaround described in the https://github.com/firebase/firebase-ios-sdk/issues/8321#issuecomment-900321941

I am closing this ticket, but if you see evidences that this is a separate issue unrelated to #8321 feel free to reopen it with additional details.

**Closed by maksymmalyhin** 2021-08-25 14:55 UTC
Labels: GoogleDataTransport
