### ISSUE TITLE
XCode 15, Firebase SPM - Fatal error "An attribute list cannot appear here"

### ISSUE THREAD

**Issue by alexrybachev** [firebase/firebase-ios-sdk#11880] opened 2023-10-01 16:53 UTC
### Description

XCode 15, Firebase SPM - Fatal error "An attribute list cannot appear here"

### Firebase SDK Version

9.6.0

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
XCode 15, Firebase SPM - Fatal error "An attribute list cannot appear here"
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by alexrybachev** [comment] 2023-10-01 17:34
<img width="814" alt="Screenshot 2023-10-01 at 21 34 19" src="https://github.com/firebase/firebase-ios-sdk/assets/75905972/ba07df48-0dcd-4d2a-88fb-7617cc8e292b">

**Comment by paulb777** [comment] 2023-10-01 22:38
Duplicate of #11840. See the resolution and discussion there.

**Closed by paulb777** 2023-10-01 22:38 UTC
Labels: needs-triage
