### ISSUE TITLE
Import Firebase (No Longer Work)

### ISSUE THREAD

**Issue by nicholaschong95** [firebase/firebase-ios-sdk#6079] opened 2020-07-20 09:56 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.28.1
  * Firebase Component: Firebase/Crashlytics, Firebase/Analytics
  * Component version: FirebaseCrashlytics (4.3.0), FirebaseAnalytics (6.6.2)
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
After install the latest Crashlytics and Analytics, FirebaseApp.configure() no longer works

#### Steps to reproduce:
1) clean remove the whole dependency of Firebase/Crashlytics, Firebase/Analytics 
2) reinstall the dependency Firebase/Crashlytics, Firebase/Analytics 
3) FirebaseApp.configure() [unresolved identifier 'FirebaseApp']

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
import Firebase

```
// TODO(you): code here to reproduce the problem
```

**Comment by Marcin951** [comment] 2020-07-20 11:24
Hey, I also met with that issue, but i have a solution for that https://github.com/firebase/firebase-ios-sdk/issues/6066
You have to import each module to solve it, like if you want firestore then import FirebaseFirestore, if Crashlytics then import FirebaseCrashlytics

**Comment by paulb777** [comment] 2020-07-20 14:23
Closing as duplicate of #6066. Let's investigate there.

**Closed by paulb777** 2020-07-20 14:23 UTC
Labels: needs-triage
