### ISSUE TITLE
unlink provider doesn't remove the email of the provider

### ISSUE THREAD

**Issue by Usman4Github** [firebase/firebase-ios-sdk#4246] opened 2019-11-06 05:01 UTC
**[READ] Step 1: Are you in the right place?**

yes

**[REQUIRED] Step 2: Describe your environment**

Xcode version: 11.1
Firebase SDK version: 6.9.0
Firebase Component: Auth, AuthUI
Component version: 6.2.3

**[REQUIRED] Step 3: Describe the problem**

When trying to remove a provider using unlink method the firebase removes it from the list but it does not remove the email id of the provider from user id.

**Steps to reproduce:** 

Auth.auth().currentUser?.unlink(fromProvider: "google.com") { (user, error) in
  // ...
}
So for example I have phone number and gmail email from Google. Both linked to same account. Now if I unlink the Google provider, now the identifier should be set to phone number only.
But problem is that the provider is removed but email is still set to the removed identifier's email.

Is there any solution?

**Comment by rizafran** [comment] 2019-11-06 09:53
Hi @Usman4Github , thanks for reporting. I was able to replicate the same issue on my end. I'll confirm internally to see if this is an intended behavior or bug, and I'll let you know once I have an update.

**Comment by rizafran** [comment] 2019-11-07 07:11
Hello @Usman4Github this is an intended behavior. What happened here was that, the top-level email was populated when you signed up with Facebook/Google provider. In your case, the top-level email (which is the Google provider) remains in the list after unlinking it to the phone number.

**Comment by Usman4Github** [comment] 2019-11-07 07:18
Hello @rizafran, thanks for quick response and findings. 

ok thats understood that it keeps the email as top level even after unlinking. so after that when ever that user will try to login with gmail using that email. it wont allow to login with an error of email already used or attached. is there any solution for it?

**Comment by rizafran** [comment] 2019-11-08 07:27
No worries, @Usman4Github.

When you sign in again with Google after unlinking, if it's already existing with the same email, the Google credential will automatically merge with that account.

Currently, you can only change your email and unable delete it.

**Comment by rizafran** [comment] 2019-11-11 14:02
Closing this issue for now since this is an intended behavior.

**Closed by rizafran** 2019-11-11 14:02 UTC
Labels: api: auth
