### ISSUE TITLE
Program Crash after Dynatrace SDK installed

### ISSUE THREAD

**Issue by TonyWatsons** [firebase/firebase-ios-sdk#8438] opened 2021-07-27 09:40 UTC
**Environment**
Xcode version: 12
Firebase SDK version: 7.5.0
Installation method: CocoaPods

**The problem**
App crash with dynatrace and firebase installed 
Crash free rate dropped from 2-8% from our apps, some weeks higher and some weeks are lowers, the issue happens randomly

We include Dynatrace SDK from our app from 4.10.7 version, with suggested from Dynatrace, we had upgrade their SDK to latest one 8.217 in 4.12.0 and problem still resist, after that, we remove the dynatrace from our app and the crash gone.

However, with investigate by dynatrace team, they found the issue is triggered by Firebase SDK, 
https://one.dynatrace.com/hc/en-us/requests/6344

Here are the dump from firebase for your reference.
![image](https://user-images.githubusercontent.com/81208574/127132455-7a3498ff-8bdc-49b1-87d9-2c0bde7852c8.png)

Our program did have crash with 
-Firebase SDK 7.5.0 
-Dynatrace SDK 8.217

**Steps to reproduce:**
no step to reproduce, it happens randomly

```
Crashed: com.apple.root.background-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000002c88dd3a0
objc_release

Crashed: com.apple.root.background-qos
0  libobjc.A.dylib                0x19d536dd0 objc_release + 16
1  libobjc.A.dylib                0x19d53857c AutoreleasePoolPage::releaseUntil(objc_object**) + 204
2  libobjc.A.dylib                0x19d53841c objc_autoreleasePoolPop + 212
3  libdispatch.dylib              0x18865f7f8 _dispatch_last_resort_autorelease_pool_pop + 44
4  libdispatch.dylib              0x1886712c0 _dispatch_root_queue_drain + 1124
5  libdispatch.dylib              0x1886717d8 _dispatch_worker_thread2 + 112
6  libsystem_pthread.dylib        0x1d45d6768 _pthread_wqthread + 216
7  libsystem_pthread.dylib        0x1d45dd74c start_wqthread + 8

TagManagerContainerQueue
semaphore_timedwait_trap
TagManagerContainerQueue
0  libsystem_kernel.dylib         0x1b6b64550 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x18865fe00 _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x188660410 _dispatch_semaphore_wait_slow + 76
3  Watsons SG App Store           0x10583ef3c -[TAGJSExportedInstructions userPropertyNamed:defaultValue:] + 65864
4  CoreFoundation                 0x188a77774 __invoking___ + 148
5  CoreFoundation                 0x18894ad44 -[NSInvocation invoke] + 380
6  JavaScriptCore                 0x192147620 JSC::ObjCCallbackFunctionImpl::call(JSContext*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 412
7  JavaScriptCore                 0x19214701c JSC::objCCallbackFunctionCallAsFunction(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 228
8  JavaScriptCore                 0x19214a3fc long long JSC::APICallbackFunction::callImpl<JSC::ObjCCallbackFunction>(JSC::JSGlobalObject*, JSC::CallFrame*) + 420
9  JavaScriptCore                 0x1920c47dc llint_function_for_construct_arity_checkTagGateAfter + 145756
10 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
11 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
12 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
13 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
14 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
15 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
16 JavaScriptCore                 0x1920c1844 llint_function_for_construct_arity_checkTagGateAfter + 133572
17 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
18 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
19 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
20 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
21 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
22 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
23 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
24 JavaScriptCore                 0x1920c1844 llint_function_for_construct_arity_checkTagGateAfter + 133572
25 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
26 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
27 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
28 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
29 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
30 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
31 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
32 JavaScriptCore                 0x1920c30a0 llint_function_for_construct_arity_checkTagGateAfter + 139808
33 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
34 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
35 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
36 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
37 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
38 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
39 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
40 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
41 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
42 JavaScriptCore                 0x1920c177c llint_function_for_construct_arity_checkTagGateAfter + 133372
43 JavaScriptCore                 0x1920c1844 llint_function_for_construct_arity_checkTagGateAfter + 133572
44 JavaScriptCore                 0x1920c1844 llint_function_for_construct_arity_checkTagGateAfter + 133572
45 JavaScriptCore                 0x19209ab58 vmEntryToJavaScriptTrampoline + 8
46 JavaScriptCore                 0x19272b400 JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 488
47 JavaScriptCore                 0x19296c0a4 JSC::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 164
48 JavaScriptCore                 0x19216595c JSObjectCallAsFunction + 656
49 JavaScriptCore                 0x191e75ad0 -[JSValue invokeMethod:withArguments:] + 592
50 Watsons SG App Store           0x105840df8 -[TAGRuntime evaluateEvent:] + 73732
51 Watsons SG App Store           0x105837e84 __42-[TAGContainer handleLoadOfPendingEvents:]_block_invoke + 37008
52 libdispatch.dylib              0x18865da84 _dispatch_call_block_and_release + 32
53 libdispatch.dylib              0x18865f81c _dispatch_client_callout + 20
54 libdispatch.dylib              0x188667004 _dispatch_lane_serial_drain + 620
55 libdispatch.dylib              0x188667c00 _dispatch_lane_invoke + 404
56 libdispatch.dylib              0x1886724bc _dispatch_workloop_worker_thread + 764
57 libsystem_pthread.dylib        0x1d45d67a4 _pthread_wqthread + 276
58 libsystem_pthread.dylib        0x1d45dd74c start_wqthread + 8


com.google.fira.worker
__CFStringAppendFormatCore
com.google.fira.worker
0  CoreFoundation                 0x188a129e8 __CFStringAppendFormatCore + 13804
1  CoreFoundation                 0x188a259fc _CFStringAppendFormatAndArgumentsAux2 + 68
2  Foundation                     0x189cf67e0 -[NSPlaceholderMutableString initWithFormat:locale:arguments:] + 96
3  Foundation                     0x189cdb780 -[NSString initWithFormat:] + 60
4  Watsons SG App Store           0x10547a01c -[APMSqliteStore rowCountForTableWithName:columnName:columnValue:error:] + 4350238748
5  Watsons SG App Store           0x1054194d8 -[APMDatabase updateDataType:inTableWithName:columnName:columnValue:error:] + 4349842648
6  Watsons SG App Store           0x10540e3d8 -[APMDatabase updateDailyCounts:error:] + 4349797336
7  Watsons SG App Store           0x10543d850 __49-[APMMeasurement(Event) writeEventOnWorkerQueue:]_block_invoke + 4349990992
8  Watsons SG App Store           0x10547b8f4 -[APMSqliteStore performTransactionWithError:block:] + 4350245108
9  Watsons SG App Store           0x10540d46c -[APMDatabase performTransaction:] + 4349793388
10 Watsons SG App Store           0x10543d640 -[APMMeasurement(Event) writeEventOnWorkerQueue:] + 4349990464
11 Watsons SG App Store           0x10543d19c -[APMMeasurement(Event) handleEventOnWorkerQueue:] + 4349989276
12 Watsons SG App Store           0x10544b588 -[APMMeasurement logEventOnWorkerQueue:notifyEventListeners:] + 4350047624
13 Watsons SG App Store           0x10544b538 -[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 4350047544
14 Watsons SG App Store           0x10544b268 __151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 4350046824
15 Watsons SG App Store           0x1054704b0 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4350198960
16 libdispatch.dylib              0x18865da84 _dispatch_call_block_and_release + 32
17 libdispatch.dylib              0x18865f81c _dispatch_client_callout + 20
18 libdispatch.dylib              0x188667004 _dispatch_lane_serial_drain + 620
19 libdispatch.dylib              0x188667c00 _dispatch_lane_invoke + 404
20 libdispatch.dylib              0x1886724bc _dispatch_workloop_worker_thread + 764
21 libsystem_pthread.dylib        0x1d45d67a4 _pthread_wqthread + 276
22 libsystem_pthread.dylib        0x1d45dd74c start_wqthread + 8
```

**Comment by rizafran** [comment] 2021-07-27 13:20
Thanks for reporting, @TonyWatsons. Is the issue also reproducible when using the latest Firebase SDK version?

**Comment by TonyWatsons** [comment] 2021-07-27 13:41
Hi Riza,

We didn’t try in latest sdk, because the app is a ecom app, we would like to minimal impact to our customers. And thats why we remove the dynatrace sdk before issue is resolved. Could you check if this issue can be fixed or have any workaround



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paulb777** [comment] 2021-07-27 14:03
This looks similar to #6039. Dynatrace may be using a version of sqlite3 that is incompatible with the system version.

**Comment by TonyWatsons** [comment] 2021-07-28 02:47
I had check the thread #6039 , is that means the issues is not resolved even latest version?
Any suggested version of sqlite?

**Comment by harp79** [comment] 2021-07-28 05:54
Dynatrace is using the iOS provided sqlite version - nothing external

**Comment by TonyWatsons** [comment] 2021-07-28 07:07
@paulb777 

@harp79 is the represent from dynatrace, 

do you have a sqlite version that is compatible to system or as @harp79 said, they are using the sqlite version comes with standard package, is that align on the expected version from your side?

**Comment by paulb777** [comment] 2021-07-28 14:03
Firebase Analytics uses the system version of sqlite. We've seen issues linking with other libraries that embed other versions of sqlite. If Dynatrace is also using the system version, a reproducible version of the crash would be helpful to investigate.

**Comment by TonyWatsons** [comment] 2021-07-30 01:29
@paulb777 as mentioned this issues happens randomly, we don't have a way to reproduce the issue, however, we can provide the exception logs from bigquery on the related issue (around 4000 of records). While do you have a private channel allow us to share the logs?

**Comment by morganchen12** [comment] 2021-07-30 23:57
@TonyWatsons can you try running your app with some memory diagnostics enabled? The crashing stack trace

```
Crashed: com.apple.root.background-qos
0  libobjc.A.dylib                0x19d536dd0 objc_release + 16
1  libobjc.A.dylib                0x19d53857c AutoreleasePoolPage::releaseUntil(objc_object**) + 204
2  libobjc.A.dylib                0x19d53841c objc_autoreleasePoolPop + 212
3  libdispatch.dylib              0x18865f7f8 _dispatch_last_resort_autorelease_pool_pop + 44
4  libdispatch.dylib              0x1886712c0 _dispatch_root_queue_drain + 1124
5  libdispatch.dylib              0x1886717d8 _dispatch_worker_thread2 + 112
6  libsystem_pthread.dylib        0x1d45d6768 _pthread_wqthread + 216
7  libsystem_pthread.dylib        0x1d45dd74c start_wqthread + 8
```

isn't a strong indicator that this bug is caused by Analytics (or even Dynatrace).

**Comment by TonyWatsons** [comment] 2021-08-02 03:54
@morganchen12 
as it happens randomly, any tricks/steps for us to reproduce the issue? by the way, can someone from google analytics helps to watch on this issue?

**Comment by morganchen12** [comment] 2021-08-02 18:54
> any tricks/steps for us to reproduce the issue?

Have you tried using the memory diagnostic tools in Xcode? They'll increase the likelihood of you reproducing the crash and also generally generate a more useful stack trace.

**Comment by TonyWatsons** [comment] 2021-08-03 01:48
Hi Ben,

Please help to check if we can reproduce the issue and using memory diagnostic tools. Related JIRA: APPWAT-7215
https://github.com/firebase/firebase-ios-sdk/issues/8438#issuecomment-891254406


Best Regards,

Tony Lam
Digital Innovation Lead
eLab Asia
A.S. Watson Group
Tel: +852 3521 3522
***@***.******@***.***>

A member of CK Hutchison Holdings
***@***.***

寄件者: Morgan Chen ***@***.***>
寄件日期: Tuesday, August 3, 2021 2:54 AM
收件者: firebase/firebase-ios-sdk ***@***.***>
副本: Tony Lam (ASW - Digital Innovation Lead, eLab Asia) ***@***.***>; Mention ***@***.***>
主旨: Re: [firebase/firebase-ios-sdk] Program Crash after Dynatrace SDK installed (#8438)

WARNING: This email was sent from an external network. Do not click links or open attachments unless you recognise the source and know the content is safe.

any tricks/steps for us to reproduce the issue?

Have you tried using the memory diagnostic tools in Xcode? They'll increase the likelihood of you reproducing the crash and also generally generate a more useful stack trace.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffirebase%2Ffirebase-ios-sdk%2Fissues%2F8438%23issuecomment-891254406&data=04%7C01%7Ctony.lam%40hk.elab.aswatson.com%7C33f9b22c231d492601ee08d955e6eeef%7C08ec9b3099ef4d1f8c8461d8fe9bde75%7C0%7C0%7C637635272645373269%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jzw76dBa9rLbjgOmpB5ctYL9j8wkSOpqAiX2StNCj6Y%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATLSJ7QYLBRFXEZCAYJBQ6LT23SVRANCNFSM5BB3LU2Q&data=04%7C01%7Ctony.lam%40hk.elab.aswatson.com%7C33f9b22c231d492601ee08d955e6eeef%7C08ec9b3099ef4d1f8c8461d8fe9bde75%7C0%7C0%7C637635272645383262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PhXkWPLqOTVEkeKqvt86Is3sOUtXHAR1hVS5dS40Cr4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctony.lam%40hk.elab.aswatson.com%7C33f9b22c231d492601ee08d955e6eeef%7C08ec9b3099ef4d1f8c8461d8fe9bde75%7C0%7C0%7C637635272645383262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g9j8usqLcCkh%2Bge7GgEw2XCHpYsSnkNvsQt9p1MoBOc%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ctony.lam%40hk.elab.aswatson.com%7C33f9b22c231d492601ee08d955e6eeef%7C08ec9b3099ef4d1f8c8461d8fe9bde75%7C0%7C0%7C637635272645393260%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wZdKD3OpCIDb1fW9gJc6G0rVNKvzEdisuDxin1h3Tuo%3D&reserved=0>.
CONFIDENTIALITY NOTE
The message represents the personal views and opinion of the individual sender and under no circumstances represents those of ASW or its Group Companies.  The shareholders, directors and management of ASW and any of its Group Companies accept no responsibility and accordingly shall have no liability to any party whatsoever with respect to the contents of this message.
This message (including any attachments) is intended only for the use of the addressee(s) named above. It may contain information that is PRIVILEGED and CONFIDENTIAL and should not be read, copied or otherwise used by any other person.
If you are not the intended recipient, you are hereby notified that any use, retention, disclosure, copying, printing, forwarding or dissemination of this communication is strictly prohibited. If you have received this communication in error, please erase all copies of the message and its attachments and notify us immediately.

**Comment by TonyWatsons** [comment] 2021-08-03 01:58
Dear Andy,
Please help to check.

在 2021年8月3日週二 09:48，Tony Lam (ASW - Digital Innovation Lead, eLab Asia) <
***@***.***> 寫道：

**Comment by TonyWatsons** [comment] 2021-08-10 02:17
@morganchen12 as mentioned, this issue we don't have step to reproduce, do you have a guide on how we can help to track on the issue so that we can help on obtain something like log or other stuff to help resolving issue. Please also write here if help from dynatrace is needed.

**Comment by morganchen12** [comment] 2021-08-10 18:41
Unfortunately we won't be able to make progress on resolving this issue without a way to reproduce it or otherwise diagnose where the memory corruption is coming from. If the memory corruption is coming from your app code, removing Dynatrace or Firebase is not a guarantee that the code will not crash in the future.

Since this is not conclusively a Firebase issue, I'll set it to auto-close in a week. In the meantime, you may find this [debugging guide](https://developer.apple.com/documentation/xcode/investigating-memory-access-crashes) from Apple to be helpful.

**Comment by TonyWatsons** [comment] 2021-08-18 03:23
@morganchen12 

any update from your side base on feedback from dynatrace?

**Comment by morganchen12** [comment] 2021-08-18 17:46
Without a clear set of instructions for reproducing the issue, we haven't been able to make any progress diagnosing its cause.

**Closed** 2021-08-31 01:03 UTC
Labels: api: analytics, needs-info, no-recent-activity

**Comment by TonyWatsons** [comment] 2021-09-01 08:41
It is not closed by resolved, is closed since no one take action to got issue to resolved.

**Comment by csepukar** [comment] 2021-09-06 12:32
I am getting the same issue when both Dynatrace, as well as firebase, are used at the same time for analytics. Any help would be greatly appreciated.

**Comment by TonyWatsons** [comment] 2021-09-07 07:23
@harp79 would you please check with firebase team on the compatibility, although I prefer on using of dynatrace, if this issue is not able to resolved, we have no choice to pick another platform

**Comment by harp79** [comment] 2021-09-07 12:56
@TonyWatsons both stacktraces mentioned in this ticket show that it is a memory corruption problem as it crashes on release of an object. So as mentioned in  https://github.com/firebase/firebase-ios-sdk/issues/8438#issuecomment-890257940 it is pretty unlikely that this is caused by Dynatrace or Firebase. But adding one or both frameworks can indeed have an impact on the frequency this problem surfaces caused by shifted internal timings introduced by execution of Dynatrace/Firebase code. So they just lead to the crash surfacing more often, but are not the reason for the crash itself.

**Comment by TonyWatsons** [comment] 2021-09-08 01:44
@harp79 But after we remove Dynatrace from the package for testing for more than a month, it did not have even 1 hit of related crash, is it related to the problem on Dynatrace SDK itself?

**Comment by TonyWatsons** [comment] 2021-09-08 01:54
@harp79 
For more information, our app updated since 21 Jul 2021, and til 7 Sept 2021, there have no more related crashes after dynatrace sdk is removed from the package. Could you help in your side to deeply check on the SDK compatibility as it not a single case?

**Comment by harp79** [comment] 2021-09-08 10:16
A crash because of memory corruption is not a compatibility issue - Dynatrace and Firebase work well together. I can't rule out that there is a memory problem in our SDK, but as we did not get any other reports from customers of a similar crash we do not have hints at such a problem. If you think this really is a Dynatrace SDK problem then this should be continued as a Dynatrace support ticket - but without a way to reproduce such a crash we also don't have a way of telling if it is caused by Dynatrace SDK or not or even find out what the root cause is and fix it.
Same is also valid the other way - does it happen with Dynatrace only with no Firebase added?

**Comment by TonyWatsons** [comment] 2021-09-08 10:32
@harp79 that's why I open both tickets in dynatrace and firebase,  please refer https://one.dynatrace.com/hc/en-us/requests/6344. and according to the thread consult, your side agreed to follow in the ticket here.

For what I proven is it's not crash by our app while happens when firebase and dynatrace is co-existing. 

And I don't agree I am a single case as you can see @csepukar  is facing similar issue, since proven it should not related to our code for the memory corruption, or why issue is not happen if dynatrace sdk is not included? could dynatrace team work with firebase team to resolve on the problem? as so far from the thread, I can not see any action was taken. 

@morganchen12 suggested a memory dump, did you try in your side yet? if this is not causing by our app, we don't have the uncompiled set of code from sdk to diagnose. All we can given is the stack trace log when it's happens. 

I suggest if someone is facing same issue, please drop a line in this thread instead of just reading.

**Comment by harp79** [comment] 2021-09-08 11:22
well - the issue that was reported with https://one.dynatrace.com/hc/en-us/requests/6344
had the same crash as reported with https://github.com/firebase/firebase-ios-sdk/issues/6318 and https://github.com/firebase/firebase-ios-sdk/issues/7935 - no Dynatrace involved, also no outcome...
Without a way to reproduce this will be a tough nut to crack. A memory dump at time of crash might be of some help, but how would we get hold of this when it can't be reproduced on demand?
As https://one.dynatrace.com/hc/en-us/requests/6344 was already closed I suggest that you create a follow up ticket from it and provide some more crash reports on the new ticket (full report with all threads in text format) - we can then check them for similarities in the other running threads to see if there is a pattern...

To get back to my question:
> does it happen with Dynatrace only with no Firebase added?
Did you try that? What was the outcome there?

**Comment by TonyWatsons** [comment] 2021-09-09 07:51
@harp79 the crash report already embed in https://one.dynatrace.com/hc/en-us/requests/6344 initial thread. please make it as reference for study. Those are dump from crashlytics.

And we have no chance to remove firebase from our package since we are ecomm app and our business rely on it for analytics for business analysis.

**Comment by kkevin** [comment] 2021-09-16 07:28
I am running into the same issue.
Anyone found the fix?

Dynatrace: 6.2.7.1063 Firebase SDK: 8.4.0

**Comment by harp79** [comment] 2021-09-16 08:28
the only update I can provide is that we had another customer inquiry about that problem, but for them it worked fine again with only Dynatrace and no Firebase... so sadly not closer to a solution, but this hints more at it being either a Firebase problem triggered by Dynatrace or an unknown incompatibility...
@kkevin a 6.x version of Dynatrace (with that version number presumably AppMon) is out of support for several years - you should think of updating
