### ISSUE TITLE
Performance: Crash in `InstrumentDownloadTaskWithRequest`

### ISSUE THREAD

**Issue by atulJha17** [firebase/firebase-ios-sdk#9736] opened 2022-05-02 07:05 UTC
iOS 15.3.1 and some version over above this.
Devices: iPhone XS, iPhone 11, iPhone 12 min and multiple version which supports iOS 15.3.1 and above.
SDK installed using cocoa pods and version 8.4.0.

FirebasePerformance
FPRNSURLSessionInstrument.m - Line 561
__InstrumentDownloadTaskWithRequest_block_invoke + 561

https://console.firebase.google.com/project/tata-one/crashlytics/app/ios:com.tatadigital.tcp/issues/cc01768e3473ede3a1f5728a7353fee5?time=1649289600000:1650412799000&sessionEventKey=39c88f42b34748c2bbb91b3fe20a60b1_1664927412966934128

**Comment by rizafran** [comment] 2022-05-02 10:58
Thanks for reporting, @atulJha17. I tried opening the link you shared, but I'm unable to access it. To have a clearer view of the issue, could you provide the complete stack trace as well as the steps to reproduce it?

**Comment by atulJha17** [comment] 2022-05-02 12:18
[INC0075417 | Incident | ServiceNow (service-now.com)](https://tdlprod.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Ddaa4d854db8fc5507f55ef5dd3961989%26sysparm_stack%3D%26sysparm_view%3D)

Crash Item	:	<compiler-generated> line 2147483647Issue Details	:	Crashed: com.apple.main-thread0  libobjc.A.dylib                0x1f6c objc_msgSend + 1721  libobjc.A.dylib                0x8e20 -[NSObject respondsToSelector:] + 362  CFNetwork                      0x72adc _CFURLStorageSessionCopyCache + 145843  CFNetwork                      0x72b3c _CFURLStorageSessionCopyCache + 146804  CFNetwork                      0x3db10 CFURLRequestSetShouldStartSynchronously + 158685  CFNetwork                      0x6c4c0 CFURLResponseGetTextEncodingName + 11086  CFNetwork                      0x44b14 CFURLRequestSetHTTPRequestBodyParts + 32367  FirebasePerformance            0x1c7b4 __InstrumentDownloadTaskWithRequest_block_invoke + 561 (FPRNSURLSessionInstrument.m:561)8  FirebasePerformance            0x1c7b4 __InstrumentDownloadTaskWithRequest_block_invoke + 561 (FPRNSURLSessionInstrument.m:561)9  TCPApp                         0x12a9f4 closure #1 in MoreView.downloadTransactionStatement() + 283 (MoreView.swift:283)10 TCPApp                         0x11174 thunk for @escaping @callee_guaranteed () -> () + 4306440564 (<compiler-generated>:4306440564)11 libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 3212 libdispatch.dylib              0x3a2c _dispatch_client_callout + 2013 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 92814 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 4415 CoreFoundation                 0x522f0 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 1616 CoreFoundation                 0xc1f4 __CFRunLoopRun + 253217 CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 60018 GraphicsServices               0x1374 GSEventRunModal + 16419 UIKitCore                      0x513e88 -[UIApplication _run] + 110020 UIKitCore                      0x2955ec UIApplicationMain + 36421 TCPApp                         0xa2d2f0 main + 39 (AppDelegate.swift:39)22 ???                            0x108981ce4 (Missing)

Crash Events	:	 350 crash events affecting 267 usersDevice For Max count	: 	iPhone 12OS for Max count	:	15.4.1Crash Link	:	https://console.firebase.google.com/project/tata-one/crashlytics/app/ios:com.tatadigital.tcp/issues/cc01768e3473ede3a1f5728a7353fee5?time=1649289600000:1650412799000&sessionEventKey=39c88f42b34748c2bbb91b3fe20a60b1_1664927412966934128

**Comment by morganchen12** [comment] 2022-05-02 22:48
This may have been fixed in https://github.com/firebase/firebase-ios-sdk/issues/8495. Can you try updating to the latest version of Firebase?

**Comment by raymondlam** [comment] 2022-05-02 23:33
Thanks @atulJha17 for reporting the issue.

#8495 might be an unrelated issue. From the stack trace, the issue looks to be related to our swizzling for [NSURLSessionDownloadTask within FPRNSURLSessionInstrument.m](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m#L564). Our swizzling logic adds a small piece of logic to track the request but should keep the original method the same.

Looking at your crash, there maybe a few reasons for the crash

1) There could be another library that is interfering with the way we are swizzling the network request
2) The underlying download task could be failing due to _CFURLStorageSessionCopyCache regardless of whether Fireperf is enabled

To check for 1), can you provide the following
1) A list of libraries you are using?
2) Can you provide the stack traces for other threads as well?
3) Can you also give the percentage of users impacted by this?

**Comment by atulJha17** [comment] 2022-05-04 04:02
@raymondlam please find the stack trace for other thread below:

Crash Item	:FPRNSURLSessionInstrument.m line 564Issue Details   :Crashed: com.apple.main-thread0  libobjc.A.dylib                0x5ac0 objc_opt_class + 441  libobjc.A.dylib                0x8a98 -[NSObject respondsToSelector:] + 362  CFNetwork                      0x73490 _CFURLStorageSessionCopyCache + 147963  CFNetwork                      0x734d4 _CFURLStorageSessionCopyCache + 148644  CFNetwork                      0x3dd20 CFURLRequestSetShouldStartSynchronously + 160405  CFNetwork                      0x6cd68 CFURLResponseGetTextEncodingName + 11086  CFNetwork                      0x44e00 CFURLRequestSetHTTPRequestBodyParts + 33287  FirebasePerformance            0x1c7b4 __InstrumentDownloadTaskWithRequest_block_invoke + 564 (FPRNSURLSessionInstrument.m:564)8  FirebasePerformance            0x1c7b4 __InstrumentDownloadTaskWithRequest_block_invoke + 564 (FPRNSURLSessionInstrument.m:564)9  TCPApp                         0x12a9f4 closure #1 in MoreView.downloadTransactionStatement() + 283 (MoreView.swift:283)10 TCPApp                         0x11174 thunk for @escaping @callee_guaranteed () -> () + 4333982068 (<compiler-generated>:4333982068)11 libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 3212 libdispatch.dylib              0x4670 _dispatch_client_callout + 2013 libdispatch.dylib              0x12b70 _dispatch_main_queue_callback_4CF + 94414 CoreFoundation                 0x51d84 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 1615 CoreFoundation                 0xbf5c __CFRunLoopRun + 254016 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 60017 GraphicsServices               0x138c GSEventRunModal + 16418 UIKitCore                      0x5195d0 -[UIApplication _run] + 110019 UIKitCore                      0x297f74 UIApplicationMain + 36420 TCPApp                         0xa2d2f0 main + 39 (AppDelegate.swift:39)21 ???                            0x108d1daa4 (Missing)

Crash Events	:	107 crash events affecting 80 usersDevice For Max count	: iPhone 11OS for Max count	:15.3.1

**Comment by raymondlam** [comment] 2022-05-05 17:04
Thanks for the additional stack trace, could you also provide a list of libraries you use?

**Comment by atulJha17** [comment] 2022-05-06 06:34
@raymondlam I won't be able to share the list of libraries.

**Comment by raymondlam** [comment] 2022-05-09 16:49
Do you have a small sample app to reproduce the issue? That would be useful to debug the issue further to see if the issue is related to our SDK.

**Closed** 2022-05-23 01:03 UTC
Labels: api: performance, needs-info, no-recent-activity
