### ISSUE TITLE
FirebaseInAppMessaging iOS SDK throwing "'FirebaseCore/FIRLogger.h' file not found" error on installation through Cocoapods

### ISSUE THREAD

**Issue by prapa1190** [firebase/firebase-ios-sdk#10218] opened 2022-09-15 07:23 UTC
### Description

On installing FirebaseInAppMessaging SDK for iOS through Cocoapods (v1.11.3) , the project fails to compile and shows an error 'FirebaseCore/FIRLogger.h' file not found.

### Reproducing the issue

1. Add `FirebaseInAppMessaging` to a project using Cocoapods
2. Install the pod and attempt to build the project. The compile will fail.

### Firebase SDK Version

0.13.0

### Xcode Version

14.0

### Installation Method

CocoaPods

### Firebase Product(s)

In-App Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
/Users/xxxx/Desktop/xxxx/Pods/FirebaseInAppMessaging/Firebase/InAppMessaging/Flows/FIRIAMServerMsgFetchStorage.m:17:9: fatal error: 'FirebaseCore/FIRLogger.h' file not found
#import <FirebaseCore/FIRLogger.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/xxxx/Desktop/xxxx/Pods/FirebaseInAppMessaging/Firebase/InAppMessaging/Flows/FIRIAMServerMsgFetchStorage.m:17:9: note: did not find header 'FIRLogger.h' in framework 'FirebaseCore' (loaded from '/Users/xxxx/Library/Developer/Xcode/DerivedData/xxxx-gxkovryukbkxroehfyciloodvcpj/Build/Products/Debug-iphonesimulator/FirebaseCore')
1 error generated.
```

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

PODS:
  - ABGaugeViewKit (1.0.1)
  - Alamofire (5.6.2)
  - CalendarDateRangePickerViewController (0.1.0)
  - CryptoSwift (1.5.1)
  - DropDown (2.3.13)
  - FirebaseAnalytics (9.6.0):
    - FirebaseAnalytics/AdIdSupport (= 9.6.0)
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (9.6.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleAppMeasurement (= 9.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalyticsInterop (1.5.0)
  - FirebaseCore (9.6.0):
    - FirebaseCoreDiagnostics (~> 9.0)
    - FirebaseCoreInternal (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (9.6.0):
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCoreInternal (9.6.0):
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
  - FirebaseCrashlytics (9.6.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInAppMessaging (0.13.0):
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseCore
    - FirebaseInstanceID
  - FirebaseInstallations (9.6.0):
    - FirebaseCore (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (~> 2.1)
  - FirebaseInstanceID (2.0.7)
  - FirebaseMessaging (9.6.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Reachability (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FSPagerView (0.8.3)
  - GoogleAppMeasurement (9.6.0):
    - GoogleAppMeasurement/AdIdSupport (= 9.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (9.6.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 9.6.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (9.6.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.0):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.8.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.8.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.8.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.8.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.8.0)"
  - GoogleUtilities/Reachability (7.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.8.0):
    - GoogleUtilities/Logger
  - IQKeyboardManagerSwift (6.5.10)
  - KeychainSwift (20.0.0)
  - lottie-ios (3.4.3)
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - PromisesObjC (2.1.1)
  - RangeSeekSlider (1.8.0)
  - RATreeView (2.1.2)
  - Realm (10.29.0):
    - Realm/Headers (= 10.29.0)
  - Realm/Headers (10.29.0)
  - RealmSwift (10.29.0):
    - Realm (= 10.29.0)
  - Segmentio (4.1)
  - SkyFloatingLabelTextField (4.0.0)
  - SVProgressHUD (2.2.5)
  - Swift_PageMenu (1.4.2)
  - SwiftyJSON (5.0.1)
  - Tags (0.3.2)

DEPENDENCIES:
  - ABGaugeViewKit
  - Alamofire
  - CalendarDateRangePickerViewController
  - CryptoSwift
  - DropDown
  - FirebaseAnalytics
  - FirebaseCrashlytics
  - FirebaseInAppMessaging
  - FirebaseMessaging
  - FSPagerView
  - IQKeyboardManagerSwift
  - KeychainSwift
  - lottie-ios
  - RangeSeekSlider
  - RATreeView
  - RealmSwift
  - Segmentio
  - SkyFloatingLabelTextField
  - SVProgressHUD
  - Swift_PageMenu
  - SwiftyJSON
  - Tags

SPEC REPOS:
  trunk:
    - ABGaugeViewKit
    - Alamofire
    - CalendarDateRangePickerViewController
    - CryptoSwift
    - DropDown
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInAppMessaging
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FSPagerView
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - IQKeyboardManagerSwift
    - KeychainSwift
    - lottie-ios
    - nanopb
    - PromisesObjC
    - RangeSeekSlider
    - RATreeView
    - Realm
    - RealmSwift
    - Segmentio
    - SkyFloatingLabelTextField
    - SVProgressHUD
    - Swift_PageMenu
    - SwiftyJSON
    - Tags

SPEC CHECKSUMS:
  ABGaugeViewKit: b69c855c2878e5ba49605b0662d409c1577ed198
  Alamofire: d368e1ff8a298e6dde360e35a3e68e6c610e7204
  CalendarDateRangePickerViewController: 9e82a36a21ad7338f4e21a314469bfabe1f738fb
  CryptoSwift: c4f2debceb38bf44c80659afe009f71e23e4a082
  DropDown: 8a2116376c1981888557f72ec2ffc9a5e0e456ec
  FirebaseAnalytics: 89ad762c6c3852a685794174757e2c60a36b6a82
  FirebaseAnalyticsInterop: 3f86269c38ae41f47afeb43ebf32a001f58fcdae
  FirebaseCore: 2082fffcd855f95f883c0a1641133eb9bbe76d40
  FirebaseCoreDiagnostics: 99a495094b10a57eeb3ae8efa1665700ad0bdaa6
  FirebaseCoreInternal: bca76517fe1ed381e989f5e7d8abb0da8d85bed3
  FirebaseCrashlytics: 3210572ddb77801e5a0bd9d7bc890769f2066a0c
  FirebaseInAppMessaging: 25e8c4408829928b6727fb461e0aef6a43111467
  FirebaseInstallations: 0a115432c4e223c5ab20b0dbbe4cbefa793a0e8e
  FirebaseInstanceID: 148c25c986c8699e67304b114e365713dce467f2
  FirebaseMessaging: a4d7910e4af663c9cbfc1071c5bef34651690949
  FSPagerView: 670405b2f18e2a87fa37f20b00de783e562c25a8
  GoogleAppMeasurement: 6de2b1a69e4326eb82ee05d138f6a5cb7311bcb1
  GoogleDataTransport: 1c8145da7117bd68bbbed00cf304edb6a24de00f
  GoogleUtilities: 1d20a6ad97ef46f67bbdec158ce00563a671ebb7
  IQKeyboardManagerSwift: 52962c76ab33532f15ad9f3ff4e5715eda5335bb
  KeychainSwift: 0ce6a4d13f7228054d1a71bb1b500448fb2ab837
  lottie-ios: 9ae750cdc7820fecbd3c2f0cfc493038208fcdc4
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  PromisesObjC: ab77feca74fa2823e7af4249b8326368e61014cb
  RangeSeekSlider: 650b11fa1edcb92e1e0ede797669d98622570fb5
  RATreeView: 380cde0090cfde21dc6ac29137f49d3b768fdd28
  Realm: 5596770daeff1ad76c8eb10d5947dc10472da779
  RealmSwift: 35d8d318b7e5a8dbc7096c2a243184e4d19abcc0
  Segmentio: ab29def64e1bff6e6e9b97671788a99bed3f1d9f
  SkyFloatingLabelTextField: 79ddc40e4ad59707fedbb48d605417aee48bb78a
  SVProgressHUD: 1428aafac632c1f86f62aa4243ec12008d7a51d6
  Swift_PageMenu: 6cc3e92540729606bd66c9b35a0886ed6c8ed899
  SwiftyJSON: 2f33a42c6fbc52764d96f13368585094bfd8aa5e
  Tags: e1d330baa83b7c855ef1eb47b04532771e32b5f5

PODFILE CHECKSUM: 2b5a7cf7565455831f263bbfcca8a5161e404cba

COCOAPODS: 1.11.3

```

</details>

**Comment by rizafran** [comment] 2022-09-15 12:44
Hi @prapa1190, I'm unable to reproduce the issue. Based on your `Podfile.lock`, it seems that the FIAM picked up the old version. Have you tried indicating `9.6.0-beta` version in FIAM pod in your `Podfile`?

**Comment by prapa1190** [comment] 2022-09-21 05:40
Hi @rizafran, sorry for the delay in replying.

I tried the `9.6.0-beta` FIAM pod as you mentioned and that does seem to work as the project at least compiles successfully.

**Comment by rizafran** [comment] 2022-09-21 09:11
Thanks for the update, @prapa1190. I'm glad that it works. I'll be closing the issue for now, but feel free to reopen if the issue arises.

**Closed by rizafran** 2022-09-21 09:11 UTC
Labels: api: inappmessaging, needs-attention
