### ISSUE TITLE
FirebaseDatabase uses SHA1 hash

### ISSUE THREAD

**Issue by sathishgodbtech** [firebase/firebase-ios-sdk#906] opened 2018-03-12 06:44 UTC
Environment
  * Xcode version: 9.2
  * Firebase SDK version: 4.5
  * Firebase Component: FirebaseInstanceId

Problem
	We are using the firebase for push notification in our cordova application.
	Our penetration testing team have found out that Weak HASH API(s) are being used in the application(CC_SHA1)
	Further to out testing we found out that CC_SHA1 was used in the following files
	1. FSRWebSocket.m
	2. FStringUtilities.m
	We have update the code, recompiled the files and updated the same in our application.
	
	Then we found out that library file called "FirebaseInstanceId" contains _strlen and _memcpy.
	Source code for the same is not available. We refered the following likns for the reference.
	https://github.com/firebase/firebase-ios-sdk/issues/186
	
	Can you please tell me when these issues will be fixed or will the source code for the same will be available for us to edit.

**Comment by wilhuff** [comment] 2018-03-12 15:26
You can't change the hashing function in `FStringUtilities.m`: that's used as a part of the tree hashing protocol with the Real-Time Database backend. If you change the hash function in the client without changing the backend the data in the client will always look out of date and will retransmit all data each time you start a query (rather than just transmitting what's new). This won't appear like you've obviously broken anything but it will cost you significantly more money.

I can't find any usage of the [hash in `FSRWebSocket.m`](https://github.com/firebase/firebase-ios-sdk/search?utf8=%E2%9C%93&q=stringBySHA1ThenBase64Encoding&type=). That may be dead code to us, though that's in a fork of SocketRocket. @schmidt-sebastian are we merging with upstream SocketRocket at all?

The memcpy comment I think doesn't apply here.

**Comment by paulb777** [comment] 2018-03-12 16:59
@sathishgodbtech Please narrow down the bug description.   You're claiming to use FirebaseMessaging, yet pointing out issues in FirebaseDatabase sources and raising the FirebaseInstanceID issue that is a duplicate of #905

**Comment by morganchen12** [comment] 2018-03-12 18:16
FSRWebSocket's hash is used [here](https://github.com/firebase/firebase-ios-sdk/blob/b6613bdba73eaf542373ea11a9afeb04cf3b4743/Firebase/Database/third_party/SocketRocket/FSRWebSocket.m#L465).

**Comment by wilhuff** [comment] 2018-03-12 18:21
In that case it's not possible to remove either of those and this is non-actionable.

**Closed by wilhuff** 2018-03-12 18:21 UTC
Labels: Database

**Comment by vikrum** [comment] 2018-03-12 19:01
From [RFC6455](https://tools.ietf.org/html/rfc6455#section-10.8):

> The WebSocket handshake described in this document doesn't depend on any security properties of SHA-1, such as collision resistance or resistance to the second pre-image attack

**Comment by schmidt-sebastian** [comment] 2018-03-13 00:06
So far, we have not merged the SocketRocket changes back to upstream. It's certainly something we can look at.
