### ISSUE TITLE
Can't receive message on foreground after turnoff notification setting for app

### ISSUE THREAD

**Issue by letrungtrung** [firebase/firebase-ios-sdk#4888] opened 2020-02-12 12:07 UTC
on iOS 13, when we turnoff notification setting of app, fcm not trigger message on foreground

**Comment by rizafran** [comment] 2020-02-12 12:16
Hi @letrungtrung, please provide more information on this issue by filing up the issue template,

**Comment by letrungtrung** [comment] 2020-02-12 12:25
Hi @rizafra ,  
Client: latest firebase-ios sdk,  
Server: latest firebase-admin sdk,
Device: iphone 11 , iOS 13.3.1

Go settings, turn off 'Allow Notifications' for my app
Open app to be ready receive notification , using firebase-admin send a notify to my device.
My app can't receive this notification

Go setting, turn on 'Allow Notifications' for my App
Testing again, received notification normally

**Comment by letrungtrung** [comment] 2020-02-12 12:26
> Hi @letrungtrung, please provide more information on this issue by filing up the issue template,

**Comment by rizafran** [comment] 2020-02-12 15:04
Hi @letrungtrung, as far as I know, turning off "Allow notifications" in settings won't display notifications in foreground or background.

**Comment by letrungtrung** [comment] 2020-02-12 15:40
> Hi @letrungtrung, as far as I know, turning off "Allow notifications" in settings won't display notifications in foreground or background.

It’s not display, but it still delegate to app to handle?

**Comment by letrungtrung** [comment] 2020-02-12 15:49
> Hi @letrungtrung, as far as I know, turning off "Allow notifications" in settings won't display notifications in foreground or background.

Follow yours, on foreground fcm still use apns to send notification to app? Do you explain for me , thanks so much

**Comment by morganchen12** [comment] 2020-02-12 18:00
We're deprecating the direct channel messages soon, but afaik this change hasn't been released yet.

**Comment by chliangGoogle** [comment] 2020-02-12 18:02
can you share with us a sample payload you try to send using admin sdk?

**Comment by letrungtrung** [comment] 2020-02-13 02:16
> can you share with us a sample payload you try to send using admin sdk?

Message.Builder messageBuilder = Message.builder();
        messageBuilder.putData("key1", "data to test");
        messageBuilder.setNotification(
                Notification.builder()
                        .setBody("Hello notification")
                        .build()
        );
        messageBuilder.setApnsConfig(ApnsConfig.builder().setAps(Aps.builder().setBadge(1).build()).build());
        messageBuilder.setToken("Token FCM");
        Message msg = messageBuilder.build();
        FirebaseMessaging.getInstance().sendAsync(msg);

**Comment by letrungtrung** [comment] 2020-02-13 02:18
> We're deprecating the direct channel messages soon, but afaik this change hasn't been released yet.

What it means, bro?

**Comment by chliangGoogle** [comment] 2020-02-18 20:30
@letrungtrung 
Did you implement userNotificationCenter:willPresentNotification:withCompletionHandler: method? 
If yes, does it get triggered when you try to send it?

**Comment by letrungtrung** [comment] 2020-02-25 03:57
> @letrungtrung
> Did you implement userNotificationCenter:willPresentNotification:withCompletionHandler: method?
> If yes, does it get triggered when you try to send it?

I did it. It still not triggered.

**Comment by chliangGoogle** [comment] 2020-02-25 18:38
The notification you sent has "notification " in the payload, meaning it's a display notification.And it will not be delivered once permission is off.
This is expected behavior.

If you want to send foreground silent notification that is not affected by notification permission, you should only set data payload.

**Comment by morganchen12** [comment] 2020-03-09 18:40
Closing since this is intended (iOS platform) behavior. @letrungtrung please let us know if you have any more questions.

**Closed by morganchen12** 2020-03-09 18:40 UTC
Labels: api: messaging
