### ISSUE TITLE
Firestore Fatal Exception: [FSTImmutableSortedDictionary documentDictionary]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by mpaulsonco** [firebase/firebase-ios-sdk#1341] opened 2018-05-28 08:53 UTC
#### Enviornment
  * Xcode version: 9.3
  * Firebase SDK version: 5.0.1 (Carthage)
  * Firebase Component: Firestore
  * Component version: 5.0.1

#### Steps to reproduce:

1. Try a basic query of a collection (see Relevant Code):

After calling `getDocuments`, the app will experience a fatal exception. 

#### Console Output:

```
2018-05-28 03:44:39.558364-0500 AppName[99307:5274217] 5.0.0 - [Firebase/Core][I-COR000022] Firebase Analytics is not available.
2018-05-28 03:44:39.559563-0500 AppName[99307:5274217] 5.0.0 - [Firebase/Core][I-COR000025] FIRAuth getUID implementation wasn't set.
got here!
firebaseDatabase: <FIRFirestore: 0x6040000da6a0>
collection: characteristics
2018-05-28 03:44:39.596419-0500 AppName[99307:5274217] +[FSTImmutableSortedDictionary documentDictionary]: unrecognized selector sent to class 0x104663d00
2018-05-28 03:44:39.600865-0500 AppName[99307:5274217] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FSTImmutableSortedDictionary documentDictionary]: unrecognized selector sent to class 0x104663d00'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001063be1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000105a53031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010643f6c4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000106340898 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000106340278 _CF_forwarding_prep_0 + 120
	5   AppName              0x00000001043c30db -[FSTLevelDBRemoteDocumentCache documentsMatchingQuery:] + 56
	6   AppName              0x00000001043c6740 -[FSTLocalDocumentsView documentsMatchingCollectionQuery:] + 167
	7   AppName              0x00000001043c64cd -[FSTLocalDocumentsView documentsMatchingQuery:] + 115
	8   AppName              0x00000001043cd96f -[FSTLocalStore executeQuery:] + 184
	9   AppName              0x00000001043fdd4d -[FSTSyncEngine listenToQuery:] + 280
	10  AppName              0x00000001043aa427 -[FSTEventManager addListener:] + 486
	11  AppName              0x00000001043b2104 __64-[FSTFirestoreClient listenToQuery:options:viewSnapshotHandler:]_block_invoke + 62
	12  AppName              0x00000001043a3e49 -[FSTDispatchQueue enterCheckedOperation:] + 79
	13  libdispatch.dylib                   0x000000010b204807 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x000000010b205848 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010b20dc41 _dispatch_queue_serial_drain + 1305
	16  libdispatch.dylib                   0x000000010b20e556 _dispatch_queue_invoke + 328
	17  libdispatch.dylib                   0x000000010b20a3a0 _dispatch_queue_override_invoke + 726
	18  libdispatch.dylib                   0x000000010b2113c8 _dispatch_root_queue_drain + 664
	19  libdispatch.dylib                   0x000000010b2110d2 _dispatch_worker_thread3 + 132
	20  libsystem_pthread.dylib             0x000000010b72b169 _pthread_wqthread + 1387
	21  libsystem_pthread.dylib             0x000000010b72abe9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

#### Relevant Code:
```
        FirebaseApp.configure()

        let firestore = Firestore.firestore()
        let settings = firestore.settings
        settings.areTimestampsInSnapshotsEnabled = true
        firestore.settings = settings

        firestore.collection("cities").getDocuments { (querySnapshot, error) in 
            // crash happens before this line 
            print("querySnapshot: \(querySnapshot) error: \(error)")
        }
```

**Comment by morganchen12** [comment] 2018-05-31 19:58
Looks like that's crashing on [this line](https://github.com/firebase/firebase-ios-sdk/blob/8037a4bf79b8ae49162c2b6f099d62ec17a7f283/Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm#L86), which shouldn't ever crash.

@wilhuff was this code changed recently?

**Comment by wilhuff** [comment] 2018-05-31 20:42
Nearly everything has had some minor modifications lately, but overall this code is not moving fast.

**Comment by morganchen12** [comment] 2018-05-31 21:43
@mpaulsonco, can you share a project that's causing this crash? Is it consistently reproducible, or does it only happen sporadically?

**Comment by SujaySundaram** [comment] 2018-06-17 23:08
I had the same issue and for some reason adding $(inherited) to the other linker flags of my target seems to fix the issue. What is weird is that there are no flags in my project settings.

**Comment by morganchen12** [comment] 2018-06-18 18:47
@mpaulsonco, I'm closing this issue as it hasn't seen any activity lately and we don't have a solid repro case. Please open this if you have an example to share.

**Comment by var-const** [comment] 2018-07-16 20:20
The issue can be reproduced consistently using [this test app](https://github.com/var-const/FirestoreCrashRepro). The thing that triggers this seems to be the fact that `Podfile` is configured to fetch Firestore _and_ FirebaseCore from Git (just using the default pod for `FirebaseCore` "fixes" it). I have found this out accidentally while trying out my branch, which is the branch I'm using. It looks like `FSTDocumentDictionary` is somehow not linked properly.

The original post mentioned using Carthage, so perhaps the Carthage configuration file is (or was) somehow broken.

**Comment by paulb777** [comment] 2018-07-16 23:52
`-ObjC` is not getting added to the `OTHER_LDFLAGS` setting. Adding it manually is a workaround.  I suspect something about one of the pods is messing with the typical CocoaPods install behavior.

**Comment by paulb777** [comment] 2018-07-23 14:04
@var-const Thanks for finding the root cause. The CocoaPods bug fix is now merged into master and will be part of the CocoaPods 1.6.0 release.  In the meantime, the workaround is to add `-ObjC` to `OTHER_LDFLAGS`.

**Closed by paulb777** 2018-07-23 14:04 UTC
Labels: Firestore
