### ISSUE TITLE
Several linking errors from 10.8.0 and up when installing via SPM

### ISSUE THREAD

**Issue by freetradeUmair** [firebase/firebase-ios-sdk#11575] opened 2023-07-20 13:51 UTC
### Description

Hi, raising this bug on behalf of Freetrade. 

We're attempting to migrate from the Firebase SDKs version 8.6.0 using Cocoapods over to SPM (currently attempting the newest version - 10.12.0).

We've hit several blockers on the way. Attempting to migrate to 10.7.0 resulted in an open ssl binary name error in which Xcode didn't like the use of an underscore in a dependant package within Firebase. 

Upgrading to 10.8.0 and above fixes that issue (as I believe you now package that dependency as an XCFramework internally). However, we're hit with the same issues from 10.8.0 and up... 

For simplicities sake, we have 1 dynamic SPM package we've created named `Core`. This only depends on `FirebaseDatabase` and `FirebaseFirestore`. This package builds successfully independently of any other package/target. 
We then have our main app module/target - `Freetrade`. This depends on `Core` as well as the following Firebase products:
- Analytics
- Database
- Firestore
- Crashlytics
- Installations
- Messaging

However, on building we're hit with the error log I've pasted below. The classes referenced are our files that live in the `Freetrade` module. 

We've tried to add `-ObjC` as a linker flag to no avail. We've also tried to remove the Analytics product (as this seems to be the only one using ObjC according to the docs.)

Using the Swift suffixed Firebase products instead results in linker errors surrounding grpc within an internal Firebase product. 

Is there anything we're missing here? 

### Firebase SDK Version

10.12.0

### Xcode Version

14.3.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication, Crashlytics, Database, Firestore, Installations, Messaging, Performance, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Undefined symbols for architecture arm64:
  "_FIRFirestoreErrorDomain", referenced from:
      _$sSo20FIRDocumentReferenceC9FreetradeE11getDocument6source7RxSwift10ObservableCySo0A8SnapshotCGSo18FIRFirestoreSourceV_tFAF10Disposable_pAF11AnyObserverVyAJGcfU_yAJSg_s5Error_pSgtcfU_ in DocumentReference+Rx.o
  "_OBJC_CLASS_$_FIRCollectionReference", referenced from:
      objc-class-ref in FirestoreProtocol.o
  "_OBJC_CLASS_$_FIRDocumentReference", referenced from:
      objc-class-ref in AccountService.o
      objc-class-ref in FirestoreProtocol.o
  "_OBJC_CLASS_$_FIRDocumentSnapshot", referenced from:
      objc-class-ref in FreeshareService.o
      objc-class-ref in DocumentReference+Rx.o
      objc-class-ref in ExchangeRateService.o
      objc-class-ref in OneDayChartService.o
      objc-class-ref in ClientService.o
      objc-class-ref in OnboardingService.o
      objc-class-ref in FeatureService.o
      ...
  "_OBJC_CLASS_$_FIRFirestore", referenced from:
      objc-class-ref in MarketService.o
      objc-class-ref in AccountService.o
      objc-class-ref in OrderService.o
      objc-class-ref in FreeshareService.o
      objc-class-ref in ExchangeRateService.o
      objc-class-ref in DepositInfoService.o
      objc-class-ref in CampaignService.o
      ...
  "_OBJC_CLASS_$_FIRQuery", referenced from:
      objc-class-ref in FirestoreProtocol.o
  "_OBJC_CLASS_$_FIRQueryDocumentSnapshot", referenced from:
      objc-class-ref in FreeshareService.o
      objc-class-ref in ActivityService.o
      objc-class-ref in Query+Rx.o
      objc-class-ref in AnnualCostsService.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
        "version" : "1.2022062300.0"
      }
    },
    {
      "identity" : "alamofire",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Alamofire/Alamofire",
      "state" : {
        "revision" : "78424be314842833c04bc3bef5b72e85fff99204",
        "version" : "5.6.4"
      }
    },
    {
      "identity" : "alamofireimage",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Alamofire/AlamofireImage",
      "state" : {
        "revision" : "98cbb00ce0ec5fc8e52a5b50a6bfc08d3e5aee10",
        "version" : "4.2.0"
      }
    },
    {
      "identity" : "algoliasearch-client-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/algolia/algoliasearch-client-swift",
      "state" : {
        "revision" : "b0082c5afc902e32157726e4926b063eb4052e6c",
        "version" : "8.14.0"
      }
    },
    {
      "identity" : "charts",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/danielgindi/Charts",
      "state" : {
        "revision" : "07b23476ad52b926be772f317d8f1d4511ee8d02",
        "version" : "4.1.0"
      }
    },
    {
      "identity" : "checkout-event-logger-ios-framework",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/checkout/checkout-event-logger-ios-framework.git",
      "state" : {
        "revision" : "a914d754b4ffb1843730e8e1f8e7e60c4bf81cf9",
        "version" : "1.2.4"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "a580250a9ff49ec38da5430cef20f88ddc831db2",
        "version" : "10.12.0"
      }
    },
    {
      "identity" : "forked-airship-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/freetrade-io/forked-airship-ios.git",
      "state" : {
        "revision" : "ded2164cbf98d81565fc98f5c419aee82e61607b"
      }
    },
    {
      "identity" : "frames-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/checkout/frames-ios",
      "state" : {
        "revision" : "7bad77a7bfa3132269b1b1258217e209593101f1",
        "version" : "4.0.4"
      }
    },
    {
      "identity" : "ft-fork-panmodal",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/freetrade-io/ft-fork-PanModal",
      "state" : {
        "branch" : "master",
        "revision" : "fcffa6f697a71bbd8ef70c3c902e00e7384e37b3"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "0a226a8c50494c4cb877fbde27ab6374520a3354",
        "version" : "10.12.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "98a00258d4518b7521253a70b7f70bb76d2120fe",
        "version" : "9.2.4"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "58d03d22beae762eaddbd30cb5a61af90d4b309f",
        "version" : "7.11.3"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "f1b366129d1125be7db83247e003fc333104b569",
        "version" : "1.50.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "5ccda3981422a84186387dbb763ba739178b529c",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "highlighterswift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/alfianlosari/HighlighterSwift",
      "state" : {
        "branch" : "main",
        "revision" : "c15eea4e5e8f18b0a2d2173830fcaa250f742bc0"
      }
    },
    {
      "identity" : "intercom-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/intercom/intercom-ios",
      "state" : {
        "revision" : "28c6d17951ed01cb7004cf37581684451a151fc1",
        "version" : "10.4.0"
      }
    },
    {
      "identity" : "ios-branch-deep-linking-attribution",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/BranchMetrics/ios-branch-deep-linking-attribution",
      "state" : {
        "revision" : "ac9422150d33839b19952111592085ea67b7a412",
        "version" : "1.41.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "lokalise-ios-framework",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/lokalise/lokalise-ios-framework.git",
      "state" : {
        "revision" : "5bbc9ce346575266f96df271e4702c4a6fa57819",
        "version" : "0.10.2"
      }
    },
    {
      "identity" : "lottie-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/airbnb/lottie-ios.git",
      "state" : {
        "revision" : "4a6058cbbdfe4f74aeae92c8bd51ad3b0de2a1ee",
        "version" : "3.3.0"
      }
    },
    {
      "identity" : "mixpanel-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/mixpanel/mixpanel-swift",
      "state" : {
        "revision" : "8ecce4c2ce14f130fe1c5e043bb0f7f23b34051d",
        "version" : "3.1.7"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "ohhttpstubs",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/AliSoftware/OHHTTPStubs",
      "state" : {
        "revision" : "12f19662426d0434d6c330c6974d53e2eb10ecd9",
        "version" : "9.1.0"
      }
    },
    {
      "identity" : "onfido-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/onfido/onfido-ios-sdk",
      "state" : {
        "revision" : "9f684a8fe561f8be11637f1e5a166d8e567fbf92",
        "version" : "27.0.0"
      }
    },
    {
      "identity" : "phonenumberkit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/marmelroy/PhoneNumberKit.git",
      "state" : {
        "revision" : "6edd6e38a30aec087cb97f7377edf876c29a427e",
        "version" : "3.5.9"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "ec957ccddbcc710ccc64c9dcbd4c7006fcf8b73a",
        "version" : "2.2.0"
      }
    },
    {
      "identity" : "rxalamofire",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RxSwiftCommunity/RxAlamofire",
      "state" : {
        "revision" : "9535b58695b91fb67f56d58d6fd0c76462d7743a",
        "version" : "6.1.2"
      }
    },
    {
      "identity" : "rxdatasources",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RxSwiftCommunity/RxDataSources",
      "state" : {
        "revision" : "90c29b48b628479097fe775ed1966d75ac374518",
        "version" : "5.0.2"
      }
    },
    {
      "identity" : "rxswift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ReactiveX/RxSwift",
      "state" : {
        "revision" : "9dcaa4b333db437b0fbfaf453fad29069044a8b4",
        "version" : "6.6.0"
      }
    },
    {
      "identity" : "rxswiftext",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RxSwiftCommunity/RxSwiftExt",
      "state" : {
        "revision" : "a42af9caeab63f2dbde318f1f3dc424f05871a37",
        "version" : "6.1.0"
      }
    },
    {
      "identity" : "simplekeychain",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/auth0/SimpleKeychain",
      "state" : {
        "revision" : "b355c569efcd409e252ccbb500d9fc2713b4d64d",
        "version" : "0.12.5"
      }
    },
    {
      "identity" : "snapkit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SnapKit/SnapKit",
      "state" : {
        "revision" : "892722a93361e6c7ac67feab1b0e79b9070deef9"
      }
    },
    {
      "identity" : "swift-algorithms",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-algorithms.git",
      "state" : {
        "revision" : "b14b7f4c528c942f121c8b860b9410b2bf57825e",
        "version" : "1.0.0"
      }
    },
    {
      "identity" : "swift-cmark",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-cmark.git",
      "state" : {
        "revision" : "29d9c97e6310b87c4799268eaa2fc76164b2dbd8",
        "version" : "0.2.0"
      }
    },
    {
      "identity" : "swift-log",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-log.git",
      "state" : {
        "revision" : "32e8d724467f8fe623624570367e3d50c5638e46",
        "version" : "1.5.2"
      }
    },
    {
      "identity" : "swift-markdown",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-markdown",
      "state" : {
        "revision" : "68b2fed9fb12fb71ac81e537f08bed430b189e35",
        "version" : "0.2.0"
      }
    },
    {
      "identity" : "swift-numerics",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-numerics",
      "state" : {
        "revision" : "0a5bc04095a675662cf24757cc0640aa2204253b",
        "version" : "1.0.2"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "f25867a208f459d3c5a06935dceb9083b11cd539",
        "version" : "1.22.0"
      }
    }
  ],
  "version" : 2
}

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-07-20 14:50
Does integrating via source make a difference? See the [10.12.0 release notes](https://firebase.google.com/support/release-notes/ios) for visionOS support.

Now that SPM is integrating Firestore via a static binary, there may be issues depending on it into a dynamic framework.

**Comment by freetradeUmair** [comment] 2023-07-20 16:38
Hey @paulb777, appreciate your promptness. 

Just tried that but was now hit with `error: Could not get GOOGLE_APP_ID in Google Services file from build environment`. I vaguely remember having this issue before but updating to a newer Firebase version fixed this. 

Also, we don't currently have visionOS support... is this still a recommended change?  

> Now that SPM is integrating Firestore via a static binary, there may be issues depending on it into a dynamic framework.
The dynamic framework does build fine - I assume our issue isn't in `Core` but rather in our main app module.

**Comment by paulb777** [comment] 2023-07-20 16:48
Understood, I suspect the same workaround of doing a source build also would address building a dependency for a dynamic library.

The other issue sounds related to finding GoogleServices-Info.plist

**Comment by abegehr** [comment] 2023-07-22 18:05
In case you're using Xcode 15 beta, regarding the Crashlytics run script error (`error: Could not get GOOGLE_APP_ID in Google Services file from build environment`), I found the solution here: https://github.com/firebase/firebase-ios-sdk/pull/11463#issue-1767693978

**Comment by freetradeUmair** [comment] 2023-07-25 09:59
Out of curiosity, what's the recommended approach for implementing Firebase SDKs when a project has multiple SPM packages/dynamic frameworks that also require Firebase SDKs? 

I'm assuming a lot of these issues stem from the SDKs only being available as static binaries?

**Comment by paulb777** [comment] 2023-07-25 14:36
It's recommended to link any Firebase static library to the main app instead of to any dynamic libraries. We're considering improving dynamic library support in the next major version #8945

In the meantime, a source build as described above is a workaround for Firestore.

**Comment by freetradeUmair** [comment] 2023-07-25 15:06
That drastically breaks away from our app architecture at the moment. Firebase is also the last dependency preventing us from deprecating our use of Cocoapods in favour of SPM. 

A source build doesn't seem to be the solution given it's replaced the initial error with the error of not finding the plist - the solutions aimed at Xcode 15 don't work here either. Although, I'll download the beta and report back if that changes anything. 

After some internal discussion and it looking like we have in fact got a single successfully building dynamic swift package with a Firebase dependency... we'll experiment with the following over the next couple of weeks:
1. Remove all Firebase dependencies from the main app module
2. Move removed dependencies from (1) to our Core swift package via SPM 
3. Create protocols/wrappers to expose desired interactions with Firebase within Core
4. Any other module and/or the main app target must import Core and use the appropriately exposed interface for communicating with Firebase. 

This should allow us to remove the Firebase dependency from every target apart from Core. Firebase only being imported into one package should hopefully remove the root of why these linking errors happen. 

Does this sound like a feasible approach to this problem? or are there any findings to report back from similar patterns? 

Appreciate your insight

**Comment by paulb777** [comment] 2023-07-25 15:16
A few clarifications:

- Xcode 15 shouldn't make a difference. The same source build solution can be used to solve two different problems: to build for vision OS in Xcode 15 and to build a dynamic library for FirebaseFirestore with any Xcode version.
- The plist setting can be set programmatically for everything in Firebase except Analytics #230 

As long as Firebase is only linked in one place, the build should work

**Comment by paulb777** [comment] 2023-08-08 21:06
Marking this for Firebase 11 to make sure we consider it then, if not before.

**Comment by omz1990** [comment] 2024-05-01 09:59
We've been experiencing the same issue for a couple of months now keenly waiting for Firebase 11. We only use SPM and have abstracted away all Firebase dependencies in an external library, it works fine when building and running the app on the simulator, but we run into similar issues when running unit tests.

We do understand the workarounds (including the ones highlighted in this thread), but all are either tedious or break from our architecture pattern and don't pull their weight as interim solutions if its eventually going to get fixed via the SDK itself.

@paulb777 do we have any estimated release timeframe for Firebase 11?

Any update will be appreciated. Thanks

**Comment by paulb777** [comment] 2024-05-01 13:40
@omz1990 The goal for Firebase 11 is mid-summer, but the plans are far from firm.

**Comment by omz1990** [comment] 2024-05-01 23:59
Thanks for the update @paulb777. Appreciate it.

**Comment by paulb777** [comment] 2024-05-29 00:11
May be the same solution as #8945

**Comment by ncooke3** [comment] 2024-07-26 21:43
Hi everyone, we unfortunately had to pull plans to release dynamic libraries in Firebase 11 due to a lack of support in SwiftPM for Firebase's use case. Could a minimal, sample project be provided that reproduces the issue?

**Comment by omz1990** [comment] 2024-08-06 00:49
Thanks for the update @ncooke3 . This is noted. Can't speak for others but my team has already settled on an alternate approach which doesn't rely on Firebase SDKs during test automation.

**Closed** 2024-08-19 01:04 UTC
Labels: api: firestore, needs-info, no-recent-activity, closed-by-bot, Swift Package Manager, dynamic-linking
