### ISSUE TITLE
pod package error in FIRCore and Firebase version

### ISSUE THREAD

**Issue by raulrom13** [firebase/firebase-ios-sdk#1429] opened 2018-06-20 13:45 UTC
* Xcode version:  9.4.1
  * Firebase SDK version:  5.2.0
  * Firebase Component: Core
  * Component version: 5.0.3

I have an error when execute this plugin for cocoapods:

pod package #MY_SPEC#.podspec --force --no-mangle --exclude-deps --verbose

The error is:

#error "Firebase_VERSION is not defined: add -DFirebase_VERSION=... to the build invocation"
#error "FIRCore_VERSION is not defined: add -DFIRCore_VERSION=... to the build invocation"

Where I have to add this version? Is it not automatic?

Thank you!

**Comment by paulb777** [comment] 2018-06-20 13:50
Thanks for the report. This is a duplicate of #1369. 

See the fix in #1378 that will be available in the next Firebase update.

**Closed by paulb777** 2018-06-20 13:50 UTC
