### ISSUE TITLE
Heap corruption crashes after migrating to Firebase Crashlytics

### ISSUE THREAD

**Issue by philfi** [firebase/firebase-ios-sdk#6788] opened 2020-10-20 16:37 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0
  * Firebase SDK version: 6.33.0
  * Firebase Component: Crashlytics
  * Component version: 6.33.0
  * Installation method: `CocoaPods`

#### Steps to reproduce:

What happened? How can we make the problem occur?

Have yet to reproduce but have seen a variety of heap corruption related crash reports show up in Firebase Crashlytics since releasing a build that introduced the migration from Fabric Crashlytics -> Firebase Crashlytics. This was the only code change that was made between releases. 

So far have been unable to tie the crashes to any specific user action, it just seems to randomly happen after awhile for some percentage of user sessions (at least 5% from the numbers I'm seeing in the past day). Tried poking in the memory debugger for clues but didn't find much there either. I've provided the specific code and Podfile changes in the following section. 

Also fwiw here are a couple example crash reports:
Example 1
```
Crashed: NSOperationQueue 0x103590ae0 (QOS: UNSPECIFIED)
0  CoreFoundation                 0x1b83b8fbc CFDictionaryGetValue + 80
1  Foundation                     0x1b882a114 _NSSetLongLongValueAndNotify + 88
2  CFNetwork                      0x1bb86ce00 _CFNetworkHTTPConnectionCacheSetLimit + 205712
3  Foundation                     0x1b88463f0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
4  Foundation                     0x1b8751710 -[NSBlockOperation main] + 84
5  Foundation                     0x1b884864c __NSOPERATION_IS_INVOKING_MAIN__ + 20
6  Foundation                     0x1b8751414 -[NSOperation start] + 740
7  Foundation                     0x1b8849044 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
8  Foundation                     0x1b8848b10 __NSOQSchedule_f + 180
9  libdispatch.dylib              0x1b811add0 _dispatch_block_async_invoke2 + 104
10 libdispatch.dylib              0x1b8137524 _dispatch_client_callout + 16
11 libdispatch.dylib              0x1b8111274 _dispatch_continuation_pop$VARIANT$armv81 + 404
12 libdispatch.dylib              0x1b81109e8 _dispatch_async_redirect_invoke + 584
13 libdispatch.dylib              0x1b811d534 _dispatch_root_queue_drain + 344
14 libdispatch.dylib              0x1b811dcd0 _dispatch_worker_thread2 + 112
15 libsystem_pthread.dylib        0x1b8188b38 _pthread_wqthread + 212
16 libsystem_pthread.dylib        0x1b818b740 start_wqthread + 8
```

Example 2:
```
Crashed: com.apple.NSURLSession-work
0  libobjc.A.dylib                0x1b6f62160 objc_release + 16
1  Foundation                     0x1a41bed18 NSKeyValuePopPendingNotificationLocal + 152
2  Foundation                     0x1a41bec38 NSKeyValueDidChange + 360
3  Foundation                     0x1a41be690 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 648
4  Foundation                     0x1a40fb11c -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 72
5  Foundation                     0x1a41b973c _NSSetLongLongValueAndNotify + 312
6  CFNetwork                      0x1a34c1d40 CFNetServiceBrowserSearchForServices + 1356
7  CFNetwork                      0x1a3710964 __CFTubeSetTubeTypeNotifier + 58572
8  libdispatch.dylib              0x1a2ac6fd0 _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x1a2ac8ac8 _dispatch_client_callout + 20
10 libdispatch.dylib              0x1a2acfc08 _dispatch_lane_serial_drain + 580
11 libdispatch.dylib              0x1a2ad0768 _dispatch_lane_invoke + 460
12 libdispatch.dylib              0x1a2ada528 _dispatch_workloop_worker_thread + 708
13 libsystem_pthread.dylib        0x1ea424908 _pthread_wqthread + 276
14 libsystem_pthread.dylib        0x1ea42b77c start_wqthread + 8
```

#### Relevant Code:

Only code changes made were per the migration doc suggestions on converting the few crashlytics callsites we had, I've provided a couple (redacted) examples as well as the podfile updates below.

```
Crashlytics.sharedInstance().setObjectValue(booleanValue, forKey: someKey)
->
Crashlytics.crashlytics().setCustomValue(booleanValue, forKey: someKey)

Crashlytics.sharedInstance().setUserIdentifier(userId)
->
Crashlytics.crashlytics().setUserID(userId)
```

Podfile changes:
Before migration:
```
pod 'Fabric', '~> 1.10.2'
pod 'Crashlytics', '~> 3.14.0'
pod 'Firebase/Performance', '6.13.0'
pod 'Firebase/Analytics', '6.13.0'
```

After migration:
```
pod 'Firebase/Performance', '6.33.0'
pod 'Firebase/Analytics', '6.33.0'
pod 'Firebase/Crashlytics', '6.33.0'
```

```

**Comment by philfi** [comment] 2020-10-20 16:39
I should also note that this is happening on both iOS 13 & 14 and it occurs in foreground and background.

**Comment by philfi** [comment] 2020-10-20 16:43
searching for similar issues on performance/analytics, looks like this might be on the path of the actual issue: https://github.com/firebase/firebase-ios-sdk/issues/6734

**Comment by paulb777** [comment] 2020-10-20 16:43
@philfi Thanks for the report. This looks like a duplicate of #6768 or #6734 and a Performance issue. See the discussion there.

**Closed** 2020-10-20 18:00 UTC
Labels: api: performance
