### ISSUE TITLE
displayName not saved on first Apple login

### ISSUE THREAD

**Issue by lorenzofiamingo** [firebase/firebase-ios-sdk#5939] opened 2020-06-28 12:07 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0 beta
  * Firebase SDK version: Firebase 6.27.0
  * Firebase Component: Auth
  * Component version: FirebaseAuth 6.6.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When I use Apple Login the `appleIDCredential.fullName` is not converted to `user.displayname`.
I know that Apple gives fullName only on the first login, but it is not saved there anyway.
I tried to remove the account on firebase console and to remove the app from "App that uses ID Apple" in settings and redo the login but it doesn't work, despite `print(appleIDCredential.fullName)` prints out the correct value.

**Comment by ryanwilson** [comment] 2020-06-29 13:20
Thanks for the report! Is this specific to Xcode 12 and iOS 14 or does this also happen on iOS 13?

**Comment by morganchen12** [comment] 2020-06-29 16:35
Similar to #4393

**Comment by scottcrossen** [comment] 2020-06-29 20:27
Internal tracking: b/156546247

**Comment by lorenzofiamingo** [comment] 2020-07-01 22:13
> Thanks for the report! Is this specific to Xcode 12 and iOS 14 or does this also happen on iOS 13?

I’m sorry but I just tried on iOS14

**Comment by IldarMurzenkov** [comment] 2020-07-07 22:24
I am facing same issue on iOS 13: user.displayname is equal to nil

**Comment by rosalyntan** [comment] 2020-07-07 22:46
Thanks for reporting this issue! As mentioned by Morgan, this looks to be the same issue as #4393.

For now, try the workaround in https://peterfriese.dev/replicating-reminder-swiftui-firebase-part3/ under the "Retrieving the user’s display name" heading.

**Comment by yuchenshi** [comment] 2020-11-23 21:15
Duplicate of #4393

**Closed by yuchenshi** 2020-11-23 21:15 UTC
Labels: api: auth, internal-bug-filed
