### ISSUE TITLE
[Firebase/RemoteConfig] Remote Config ensureInitialized return unknown error

### ISSUE THREAD

**Issue by dangthaison91** [firebase/firebase-ios-sdk#6874] opened 2020-10-30 11:04 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 6.28.2
  * Installation method: `Zip file` (select one)
  * Firebase Component: RemoteConfig

#### Steps to reproduce:

We cannot reproduce this bug in the development environment but have thousands of logs:

![Screen Shot 2020-10-30 at 17 41 44](https://user-images.githubusercontent.com/6436310/97697254-54ed5f00-1ad9-11eb-98dd-5402579d89b1.png)

![Screen Shot 2020-10-30 at 17 58 18](https://user-images.githubusercontent.com/6436310/97697413-8c5c0b80-1ad9-11eb-8463-d939c9e0df73.png)

#### Relevant Code:
Recorded non-fatal error relates to line `remoteConfig.ensureInitialized`

```swift
public class FBRemoteConfig {
    public static let `default`: FBRemoteConfig = FBRemoteConfig()

    public let remoteConfig: RemoteConfig

    public init() {
        if FirebaseApp.app() == nil {
            guard let filePath = Bundle.main.path(forResource: appFirebasePlistPath, ofType: "plist"),
                let options = FirebaseOptions(contentsOfFile: filePath) else {
                fatalError("Cannot configure Firebase with plist file")
            }

            if FirebaseApp.app() == nil {
                FirebaseApp.configure(options: options)
            }
        }

        guard let app = FirebaseApp.app() else {
            fatalError("Cannot init FirebaseApp")
        }

        remoteConfig = RemoteConfig.remoteConfig(app: app)
        let settings = RemoteConfigSettings()
        settings.minimumFetchInterval = developerModeEnabled ? 15 : 15 * 60
        remoteConfig.configSettings = settings
        remoteConfig.setDefaults(fromPlist: "DefaultRemoteConfigValues")

        remoteConfig.ensureInitialized { [weak self] error in
            if let error = error {
                CrashlyticsLogger.recordError(error)
                #if DEBUG
                print("🤯🤯🤯 \(error.localizedDescription)")
                #endif
            }
            self?.fetchData()
        }
    }
}
```

Should we wait to RemoteConfig **Initialized successfully** then fetchConfig or can we just ignore it?

**Comment by dangthaison91** [comment] 2020-11-03 02:10
> Can you share the error message?

The error message is in the second picture. We just found that our logging code is not working properly, please wait while we update better error message.

**Comment by dangthaison91** [comment] 2020-11-11 04:11
Hi again, with the new app version, we get a better error message:

```
Domain: com.google.remoteconfig.ErrorDomain Code: 8003 NSLocalizedDescription: Timed out waiting for database load.
```

**Comment by morganchen12** [comment] 2020-11-11 06:23
That error indicates the local device's database could not be loaded within the timeout interval (defined [here](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:FirebaseRemoteConfig/Sources/RCNConfigContent.m;l=367?q=RCNConfigContent). @karenyz, can you take a look at this issue?

**Comment by MichaelVerdon** [comment] 2024-11-18 17:08
I have been unable to reproduce this error and this ticket is quite old so I will close it. Please feel free to reopen it if you are still experiencing this issue on the latest SDK version and we will investigate it.

**Closed by MichaelVerdon** 2024-11-18 17:08 UTC
Labels: api: remoteconfig
