### ISSUE TITLE
[Firebase/Crashlytics][I-CLS000000] Failed to download settings

### ISSUE THREAD

**Issue by zhouheAragon** [firebase/firebase-ios-sdk#5743] opened 2020-06-04 01:49 UTC
Describe your use case and/or feature request here.

Xcode version: 11.5
Firebase SDK version: 6.25.0
Firebase Component: [Firebase/Crashlytics]
Component version:=Version 4.1.0
Describe the problem

Crashlytics[1000:23616] 6.25.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-6 "(null)" UserInfo={retryLimit=1, NSErrorFailingURLStringKey=https://firebase-settings.crashlytics.com/spi/v2/platforms/ios/gmp/1:547164324192:ios:151513cc73f9c161fc1e05/settings?build_version=1&display_version=1.0&instance=bdccd8e07acf9a27f8248f69fa8fd9b7d499e84b&source=1}

The firebase project is not correctly initialized. I'm not seeing the Crashlytics console

Steps to reproduce:

Run the app on iOS and [FIRApp configure] which produces the error.

**Comment by ryanwilson** [comment] 2020-06-04 14:21
Hi, I see this is a duplicate of #5732. 

The same questions apply - is this an issue with Catalyst?

Also please check if there's a VPN / Adblocker / Pi-Hole that's refusing the connection. You can follow up on this issue and we can track it accordingly.

**Comment by zhouheAragon** [comment] 2020-06-05 01:40
> Hi, I see this is a duplicate of #5732.
> 
> The same questions apply - is this an issue with Catalyst?
> 
> Also please check if there's a VPN / Adblocker / Pi-Hole that's refusing the connection. You can follow up on this issue and we can track it accordingly.

This is an issue with iOS App

**Comment by ryanwilson** [comment] 2020-06-05 13:54
Okay, please open a Support request here: https://firebase.google.com/support since they'll have access to your project configuration and help further.

Thanks, I'll close this now since it's likely a project configuration issue and they should be able to help.

**Closed by ryanwilson** 2020-06-05 13:54 UTC
Labels: api: crashlytics, needs-attention
