### ISSUE TITLE
Authentication is replacing providers instead of merging them 

### ISSUE THREAD

**Issue by skaldic** [firebase/firebase-ios-sdk#8658] opened 2021-09-15 13:33 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.70
  * Installation method: `CocoaPods` 
  * Firebase Component: Auth 

#### Steps to reproduce:

What happened? How can we make the problem occur?

A user creates an account using the regular (email+password) provider, logs out and then uses a social provider (that has the same email) to log back in (e.g. Apple or Google). Before we would end up with and account that had 2 or 3 providers (Regular email/password + the social Apple and Google for example)

![Screenshot 2021-08-16 at 09 57 34](https://user-images.githubusercontent.com/10638409/133441815-0afea2ff-c925-4c19-9c4d-7bce4191a953.png)

Today I've noticed that with the above steps the providers are not merged, but replaced. So instead of having 2 providers we end up with the latest one. (Google overrides regular or Apple overrides regular). 

![image](https://user-images.githubusercontent.com/10638409/133442787-03c7243b-04d0-4f3e-89f3-36ea3e2c371c.png)

Account email address setting is "Prevent creation of multiple accounts with the same email address"
   
![Screenshot 2021-09-15 at 15 25 37](https://user-images.githubusercontent.com/10638409/133441984-f0042e91-edda-42cc-8b5e-8e7ef4fa167f.png)

If this a bug or a new strategy of provider handling for the Auth? User can't login in this case with the regular (email + password) provider if they later use Google or Apple.

**Comment by rizafran** [comment] 2021-09-15 18:00
Hi @skaldic, it seems that the issue you're encountering is an intended behavior. For security reasons, if a user signs up with unverified email/password, and then the user signs in with Apple or Google using the same email, the email/password provider will be removed as we can't verify that the original user owns that email. You may check this [page](https://firebase.google.com/docs/auth/users#verified_email_addresses) for more details. Thanks.

**Comment by skaldic** [comment] 2021-09-16 06:46
> Hi @skaldic, it seems that the issue you're encountering is an intended behavior. For security reasons, if a user signs up with unverified email/password, and then the user signs in with Apple or Google using the same email, the email/password provider will be removed as we can't verify that the original user owns that email. You may check this [page](https://firebase.google.com/docs/auth/users#verified_email_addresses) for more details. Thanks.

Fair enough, but why did it behave differently a week ago ?

**Comment by rizafran** [comment] 2021-09-17 18:15
@skaldic, based on the [docs](https://firebase.google.com/docs/auth/users#verified_email_addresses):

> In some situations, Firebase will automatically link accounts when a user signs in with different providers using the same email address.

In your case, if the email/password account is verified, then signing in with Apple/Google account will keep both providers on the account.

**Comment by skaldic** [comment] 2021-09-21 07:23
@rizafran you mean: verified by the user (by clicking the verify email CTA) or the email provider is verified (as described in the doc link). One account is a gmail account (thus verified) and the second one is part of a G Suite email.

This is behaviour is new and It causes us some concern and it also reproduces on Android and Web. I guess a change in how Firebase Auth backend merges accounts ?

**Comment by rizafran** [comment] 2021-09-21 17:14
@skaldic, yes, if email/password account is verified (e.g. by sending verification email), then the Gmail account will be linked to it:
<img width="784" alt="Screen Shot 2021-09-22 at 12 51 48 AM" src="https://user-images.githubusercontent.com/56452638/134213916-6f8d24c1-89e3-442d-8eb1-2b60b156a3e0.png">


Also, per checking, it seems that the behavior you're encountering does exist, and it is also working on Android and Web. Currently, I see that there are no updates regarding this behavior based on the [release notes](https://firebase.google.com/support/release-notes/ios).

**Comment by rizafran** [comment] 2021-09-30 17:53
I'll be closing this issue for now, but feel free to reopen if you have additional questions or details to share.

**Closed by rizafran** 2021-09-30 17:53 UTC
Labels: type: question, api: auth

**Comment by skaldic** [comment] 2021-10-01 06:44
Thank you Riza !
