### ISSUE TITLE
FirebaseAnalytics not found in FirebaseAnalyticsSwift

### ISSUE THREAD

**Issue by lorenzofiamingo** [firebase/firebase-ios-sdk#7891] opened 2021-04-13 14:57 UTC
### Environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.10.0
  * Installation method: Swift Package Manager
  * Firebase Component: Analytics Swift

### Problem
When I build the project there is no problem, but when I archive it for a release this appears:

<img width="1281" alt="Schermata 2021-04-13 alle 16 49 56" src="https://user-images.githubusercontent.com/40797951/114573949-20c9bd00-9c79-11eb-93d8-d26f97636c53.png">

**Comment by paulb777** [comment] 2021-04-13 15:30
@lorenzofiamingo Sorry about the trouble. This is looks to be a duplicate of #7785.

**Closed by paulb777** 2021-04-13 15:30 UTC
Labels: Swift Package Manager, api: analytics
