### ISSUE TITLE
Fatal Exception: std::__1::system_error recursive_mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by sspogra** [firebase/firebase-ios-sdk#10691] opened 2023-01-17 07:56 UTC
### Description

Fatal Exception: std::__1::system_error recursive_mutex lock failed: Invalid argument
Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x1eea8 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0x1f288 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0x164d4 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x111a8 __FIRCLSExceptionRecord_block_invoke + 232 (FIRCLSException.mm:232)
4  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
5  libdispatch.dylib              0x13574 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  FirebaseCrashlytics            0x101b4 FIRCLSExceptionRecord + 234 (FIRCLSException.mm:234)
7  FirebaseCrashlytics            0xfec4 FIRCLSTerminateHandler() + 404 (FIRCLSException.mm:404)
8  libc++abi.dylib                0x10f28 std::__terminate(void (*)()) + 20
9  libc++abi.dylib                0x10ec4 std::terminate() + 56
10 libobjc.A.dylib                0x33bec objc_terminate + 16
11 libdispatch.dylib              0x3ff0 _dispatch_client_callout + 40
12 libdispatch.dylib              0x15b8c _dispatch_root_queue_drain + 684
13 libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
14 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
15 libsystem_pthread.dylib        0xb98 start_wqthread + 8

### Reproducing the issue

Don't know exactly when this crash happened but as per logs the last entry is adding an array of data to a document. See below code.
 {
"notes" = "<FSTArrayUnionFieldValue: 0x28089b120>";
}

let noteMap = {} // Json of list of notes 
let mapToCache = ["notes": FieldValue.arrayUnion([noteMap!])]

firestore
            .collection("user")
            .document("123")
            .setData(mapToCache, merge: true)

### Firebase SDK Version

10.1.0

### Xcode Version

14.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, App Distribution, Crashlytics, Database, Firestore, Messaging, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by dconeybe** [comment] 2023-01-17 14:24
Drive-by comment: The _only_ place in Firestore where we use `std::recursive_mutex` is in EventListener: https://github.com/firebase/firebase-ios-sdk/blob/43b6e276bf89d899bb3fadcafabd42b81f1ef759/Firestore/core/src/core/event_listener.h#L97. This is almost certainly related to another issue reported by @sspogra: https://github.com/firebase/firebase-ios-sdk/issues/10611. Something is going wrong with listener callbacks, and this issue appears to be another symptom.

**Comment by dconeybe** [comment] 2023-01-18 15:59
After further investigation, this crash almost certainly has the same root cause as the other listener-related crashes that you've reported. I'm going to close this one and use https://github.com/firebase/firebase-ios-sdk/issues/10611 as the canonical issue to track progress. At this time, there is nothing more I can do without a reproducible scenario. Were you ever able to run your app with Address Sanitizer enabled? Can you try reproducing when your app is compiled in Release mode?

**Closed by dconeybe** 2023-01-18 15:59 UTC
Labels: api: firestore
