### ISSUE TITLE
Crash when calling appWillForeground in GDTCORStorage class

### ISSUE THREAD

**Issue by jeffvstudio** [firebase/firebase-ios-sdk#4044] opened 2019-10-10 17:01 UTC
* Firebase/Core (6.10.0)
  * Firebase/RemoteConfig (6.10.0)
  * FirebaseABTesting (3.1.2)
  * Xcode version: Version 11.1 (11A1027)
  * iOS decices version: 12.3.1 and 13.1

If you run the tests in Xcode it crashes after starting, it happens no matter the device you choose to run them. It crashes because there's Null pointer passed as an argument and the function doesn't expect Null values. Image with file, class, function, call, error and debug data attached

![crash](https://user-images.githubusercontent.com/34173141/66589856-1646d880-eb55-11e9-9fc5-08771d1bac11.png)

**Comment by morganchen12** [comment] 2019-10-10 17:08
Duplicate of #4039

**Closed by morganchen12** 2019-10-10 17:08 UTC
Labels: GoogleDataTransport
