### ISSUE TITLE
In App Messaging display glitch

### ISSUE THREAD

**Issue by GZaccaroni** [firebase/firebase-ios-sdk#7022] opened 2020-11-24 13:26 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.1.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: InAppMessaging

### [REQUIRED] Step 2: Describe the problem
The in app message ( Card template ) is shown cut at the top of the screen.
![IMG_0003](https://user-images.githubusercontent.com/17646575/100100361-fc537c80-2e60-11eb-8287-40e969b48cea.PNG)

#### Steps to reproduce:
Open the app after an in app message is sent, we haven't found a pattern.

**Comment by christibbs** [comment] 2020-11-30 16:40
Thanks for reporting! Closing this as a duplicate of #6803. You can track progress there.

**Closed** 2020-11-30 16:40 UTC
Labels: api: inappmessaging
