### ISSUE TITLE
Change configuration in run time

### ISSUE THREAD

**Issue by dbeleza** [firebase/firebase-ios-sdk#8537] opened 2021-08-17 06:48 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 8.5.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytics

#### Steps to reproduce:

When my app starts I'm initializing Firebase this way: `FirebaseApp.configure()` on `didFinishLaunchingWithOptions` method.

But at some point, **in run time**, I will need to reinitialize Firebase with a different config file. For that, I'm doing this:
```
guard let filePath = Bundle.main.path(forResource: "GoogleService-US-Strict-Info", ofType: "plist"),
           let fileOptions = FirebaseOptions(contentsOfFile: filePath) else {
               return
}

FirebaseApp.app()?.delete({ _ in
      FirebaseApp.configure(options: fileOptions)
})
```

Note: Using _breakpoint_, I'm sure this line `FirebaseApp.configure(options: fileOptions)` is being called.

However this is not working. Instead, I continue to receive events on the default configuration.
Can someone please give me some help?

**Comment by paulb777** [comment] 2021-08-17 14:26
This looks like a duplicate of #230. Analytics does not support multiple configurations. See the discussion there.

**Comment by dbeleza** [comment] 2021-08-18 10:02
> This looks like a duplicate of #230. Analytics does not support multiple configurations. See the discussion there.

Ok. Thanks for the answer @paulb777

**Closed** 2021-08-18 11:38 UTC
Labels: api: analytics
