### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by RohithKilaparthi** [firebase/firebase-ios-sdk#4117] opened 2019-10-18 15:23 UTC
* Xcode version: 10.3
  * Firebase SDK version: 6 and above
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage, Crashlytics, Performance, Analytics, Google Maps
  * Component version: Given Below

### Describe the problem
When I submitted my app to AppStore, I got a mail from . them saying 
```ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.```

#### Steps to reproduce:
  firebase_database: ^3.0.7
  cloud_firestore: ^0.12.9+4
  firebase_analytics: ^5.0.2
  firebase_storage: ^3.0.5
  firebase_messaging: ^5.1.6
  firebase_auth: ^0.14.0+5
  firebase_performance: ^0.3.0+5
  google_maps_flutter: ^0.5.21+7

What happened? How can we make the problem occur?
```ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.```

**Comment by morganchen12** [comment] 2019-10-18 17:06
This issue should be resolved in the latest version of Firebase (6.10.0). Please upgrade and see if the issue is still reproducible.

See #3780

**Closed by morganchen12** 2019-10-18 17:06 UTC
Labels: api: auth
