### ISSUE TITLE
Frameworks/grpc.framework” is not a proper framework bundle

### ISSUE THREAD

**Issue by CristianMoisei** [firebase/firebase-ios-sdk#12568] opened 2024-03-15 21:45 UTC
### Description

My apps that use Firebase have been stuck in review for a long time and finally Apple sent me the following email.
It is not clear to me what the issue is, but it seems related to Firebase. Is this a known issue?

Hello Cristian,
 
My name is Annie, and I’m a senior Advisor with Apple Developer Program Support.

We're reaching out regarding your app, “Evo - The Everything App”, Apple ID: 6475402655.

Specifically, “Evo.app/Contents/Frameworks/grpc.framework” is not a proper framework bundle. 

Frameworks that are not proper:

Frameworks/FirebaseAnalytics.framework
Frameworks/FirebaseFirestoreInternal.framework
Frameworks/GoogleAppMeasurement.framework
Frameworks/GoogleAppMeasurementIdentitySupport.framework
Frameworks/absl.framework
Frameworks/grpc.framework
Frameworks/grpcpp.framework
Frameworks/openssl_grpc.framework

The following builds of App ID: 6475402655 are marked invalid binary: 

macOS 1.15 (44)
macOS beta build 1.16 (47)
macOS store version 1.15

You can resolve this issue by following the link below for more information and update their binary.

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html

If you have additional questions related to this issue, please respond to this email and reference case number 102247584876.

For code-level assistance with Apple frameworks, APIs, and tools, you can submit a request to [Developer Technical Support](https://developer.apple.com/support/technical/).

If you have additional questions related to this request, please reference case number 102247584876.

Best regards,

Annie
Apple Inc.

### Firebase SDK Version

10.22.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Firestore

### Targeted Platforms

macCatalyst

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment] 2024-03-15 22:35
Hi @CristianMoisei, thanks for reporting. I'll work on reproducing this. In the meantime, you may be able to unblock submission by using Firestore from source ([release notes](https://firebase.google.com/support/release-notes/ios#cloud-firestore_7)). That should workaround the XCFramework validation issues as you would be building these libraries from source.

**Comment by ncooke3** [comment] 2024-03-15 22:38
Actually, looking at it again, I believe this is a dupe of #12505. See this comment https://github.com/firebase/firebase-ios-sdk/issues/12505#issuecomment-1989630753

**Comment by ncooke3** [comment] 2024-03-15 22:39
I'm marking this as closed as we will have a fix out early next week.

**Closed by ncooke3** 2024-03-15 22:39 UTC
Labels: needs-triage

**Comment by CristianMoisei** [comment] 2024-03-16 05:50
Thank you @ncooke3 , this is a pretty urgent bug fix for me, so when you say build it from source, what exactly are you referring to? What do I need to do?

**Comment by paulb777** [comment] 2024-03-16 14:30
See https://github.com/firebase/firebase-ios-sdk?tab=readme-ov-file#visionos
