### ISSUE TITLE
AppCheck support for watchOS

### ISSUE THREAD

**Issue by Semty** [firebase/firebase-ios-sdk#9191] opened 2022-01-10 19:03 UTC
### Feature proposal

* Firebase Component: AppCheck

We've implemented support for AppCheck in our app ecosystem (iOS, Android, Web) and thinking about enforcing App Check verification. 

The main obstacle is that we have watchOS as well and it seems that AppCheck doesn't support it (well, of course, DeviceCheck and AppAttest just not available on watchOS). 

What is the expected behaviour in this situation? Should we just abandon the idea of using AppCheck in a foreseeable future or there is some workaround we could do?

**Comment by paulb777** [comment] 2022-01-10 19:34
@Semty Thanks for the request. AppCheck should be community supported where possible for watchOS.

We just merged a PR fix today - #9187 that fixes a Firebase podspec issue for watchOS that will be available with the next release - 8.11.0. In the meantime - a CocoaPods workaround might be changing the Podfile from `Firebase/AppCheck` to `FirebaseAppCheck`

**Comment by paulb777** [comment] 2022-01-11 00:34
I'll close since there is a staged fix and workaround, but please comment if you have another issue and we can reopen.

**Comment by Semty** [comment] 2022-01-18 17:59
@paulb777 hey! it seems that the desired effect is seen only with using Cocoapods, but with SPM I get this after adding AppCheck for watchOS target:
DeviceCheck is not available when building for watchOS.

**Comment by paulb777** [comment] 2022-01-18 18:33
Hi @Semty AppCheck should be available for watchOS for both CocoaPods and SPM.  Device Check is not available for watchOS.  See https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckAvailability.h and https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRDeviceCheckProvider.h#L33

**Comment by Semty** [comment] 2022-01-19 11:29
@paulb777 hello! Thank you for the quick response!

Of course, DeviceCheck is not available for watchOS, but the truth is that I don't use it in a watchOS target, I get this error just by adding ```FirebaseAppCheck``` package to the watchOS target

**Comment by paulb777** [comment] 2022-01-19 15:32
@Semty Thanks for clarifying! I can reproduce and it looks like a problem in the Package.swift specification. I'll reopen and see if I can come up with a fix.

**Closed** 2022-01-19 17:25 UTC
Labels: type: feature request, watchOS, Swift Package Manager, api: appcheck
