### ISSUE TITLE
Firebase Analytics Debug View not working on iOS 18.1 (but works on iPadOS 18.1) (Release configuration for TestFlight)

### ISSUE THREAD

**Issue by zhocker** [firebase/firebase-ios-sdk#14139] opened 2024-11-18 11:38 UTC
### Description

Firebase Analytics Debug View not working on iOS 18.1 (but works on iPadOS 18.1) (Release configuration for TestFlight) 

Description
Firebase Analytics Debug View is not showing up on iOS 18.1 devices when building Release configuration for TestFlight, despite being properly configured. However, the same build works correctly on iPadOS 18.1.
Environment

iOS Version: 18.1
Device: iPhone (model: specify if possible)
Firebase SDK Version: (specify your version)
Distribution: TestFlight (Release build)
Xcode Version: (specify your version)

Steps to Reproduce

Configured launch arguments in scheme:

-FIRDebugEnabled
-FIRAnalyticsDebugEnabled

Added the following code in app initialization:

swiftCopyFirebaseConfiguration.shared.setLoggerLevel(.debug)
Performance.sharedInstance().isInstrumentationEnabled = true
Performance.sharedInstance().isDataCollectionEnabled = true

Archived with Release configuration
Uploaded to TestFlight
Installed via TestFlight on iOS 18.1 device
Tried to access Debug View (via device shake)

Expected Behavior
Debug View should appear when triggering it on the device.
Actual Behavior

Debug View does not appear on iOS 18.1 devices when using Release build on TestFlight
Debug View works fine when running Debug build directly from Xcode

Additional Information

The same Release build works correctly on iPadOS 18.1 devices
Debug View is accessible when running directly from Xcode
All proper Firebase initialization and setup has been confirmed

Workarounds Attempted

Verified launch arguments are properly set
Confirmed Firebase initialization
Tested on multiple iOS 18.1 devices
Clean build and reinstall

Would appreciate any insights or confirmation if this is a known issue with iOS 18.1 specifically when using Release configuration.

### Firebase SDK Version

11.4

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2024-11-19 15:06
Thanks for reaching out, @zhocker. The issue you're encountering seems to be an intended behavior. DebugView requires to run the app in a development environment with the `-FIRDebugEnabled` flag enabled in Xcode. With this, you won't be able to pass the parameter when launching a TestFlight build in your device.

I'll be closing this ticket for now, but feel free to comment if you have other questions.

**Closed by rizafran** 2024-11-19 15:06 UTC
Labels: api: analytics
