### ISSUE TITLE
Memory leak when using Firebase and Crashlytics together.

### ISSUE THREAD

**Issue by janremes** [firebase/firebase-ios-sdk#571] opened 2017-12-15 16:48 UTC
* Xcode version:  9.2
  * Firebase SDK version: 4.7
  * Firebase Component:  Firebase Core and Crashlytics 
  * Component version: Crashlytics 3.93, Firebase 4.7.0

If you link both Firebase and Crashlytics, Xcode memory debugger and Allocations instruments is reporting a memory leak. It's reproducible always. I attached empty project without firebase plist as an example.

<img width="1041" alt="screen shot 2017-12-15 at 17 40 58" src="https://user-images.githubusercontent.com/1276036/34051702-e7cb0f94-e1bf-11e7-9d5d-9e7b5a9ed10a.png">

Xcode example project:
[firebase-leak.zip](https://github.com/firebase/firebase-ios-sdk/files/1563359/firebase-leak.zip)

**Comment by TKBurner** [comment] 2018-01-06 00:41
Thanks for reaching out! Can you confirm if you have previously used Fabric Crashlytics? I want to determine if the firebase dependency is necessary to reproduce this. I'll be reporting this to the Crashlytics eng team on your reply.

Thanks!

**Comment by janremes** [comment] 2018-01-08 12:37
@TKBurner I tested it with the latest Firebase 4.8.0 and it seems more like a Firebase issue. If you install just Crashlytics, Memory Analyzer in Xcode is reporting 0 issues. It can be false positive, but still it's weird.

**Comment by TKBurner** [comment] 2018-01-08 16:36
@janremes Thanks so much! Did you have firebase set up in your Xcode project prior to this, or you added it just for Crashlytics? Really want to get to the bottom of this!

**Comment by janremes** [comment] 2018-01-08 16:43
@TKBurner I have installed Crashlytics first and then I added Firebase/Database for realtime data observing. Then we had some memory issues with our app and I was able to fix almost all of them. Just this issue persisted and I was able to see it also in empty project with Crashlytics and Firebase installed.

**Comment by TKBurner** [comment] 2018-01-12 14:32
Thanks! I'm working on reproducing this, but wasn't able to so far. Can you give me exact reproduction steps? Did you get this before you installed Firebase/Database? The team here is really curious to get to the bottom of this 👍

**Comment by 10686142** [comment] 2018-01-15 15:54
I am having the same issue here, when I try to backtrace the error it references the GADMobileAds.configure

But I am using an older version of firebase messaging since the older version wasn't working anymore 2 motnhs ago, so that's version 2.0

**Comment by TKBurner** [comment] 2018-01-15 15:59
Thanks, are you also using Crashlytics? Definitely want to get to the
bottom of this!

**Comment by 10686142** [comment] 2018-01-15 16:38
Yes I just turned it on, what can I do now?

**Comment by TKBurner** [comment] 2018-01-16 15:23
Sorry for the confusion. Did you run into the issue before or after you
turned on the Crashlytics SDK? I'm trying to isolate the cause of this
problem and if it is related to the relationship between Firebase and
Crashlytics or just Firebase core.

Thanks!

**Comment by morganchen12** [comment] 2018-01-26 20:03
Closing as this issue has staled. Please re-open if you have any new information.

**Closed by morganchen12** 2018-01-26 20:03 UTC
Labels: Crashlytics
