### ISSUE TITLE
The following build commands failed: 

### ISSUE THREAD

**Issue by MMavrisPaleBlue** [firebase/firebase-ios-sdk#11426] opened 2023-06-12 10:45 UTC
### Description

When I run the project from Xcode it builds fine. 
As soon as I use xcodebuild I get this error:

```
Build description path: /Users/user/Software/macos-project/build/XCBuildData/1de1a3320b63060eeac8ee6054441eab.xcbuilddata

warning: Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning
ClangStatCache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk /var/folders/3y/wxqdg41958n7cl4xdf9qzxxh0000gn/C/com.apple.DeveloperTools/14.3-14E222b/Xcode/SDKStatCaches.noindex/macosx13.3-22E245-.sdkstatcache
    cd /Users/user/Software/macos-project/project.xcodeproj
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -o /var/folders/3y/wxqdg41958n7cl4xdf9qzxxh0000gn/C/com.apple.DeveloperTools/14.3-14E222b/Xcode/SDKStatCaches.noindex/macosx13.3-22E245-.sdkstatcache

CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/Release
    cd /Users/user/Software/macos-project/project.xcodeproj
    builtin-create-build-directory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/Release
error: File exists but is not a directory: /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build

CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs/Release
    cd /Users/user/Software/macos-project/project.xcodeproj
    builtin-create-build-directory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs/Release
error: File exists but is not a directory: /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs

warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'project' from project 'project')
warning: Run script build phase 'Swiftlint' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'project' from project 'project')
warning: Run script build phase 'Firebase' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'project' from project 'project')
** BUILD FAILED **


The following build commands failed:
	CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/Release
	CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs/Release
```

This is a fresh installation of Firebase (SPM). 

### Firebase SDK Version

10.10.0

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

macOS

### Relevant Log Output

```shell
✘ user@Michaels-MacBook-Pro  ~/Software/macos-project   feature/76-crashlytics  xcodebuild
2023-06-12 13:38:45.806 xcodebuild[32413:8575837] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph


Resolved source packages:
  nanopb: https://github.com/firebase/nanopb.git @ 2.30909.0
  GTMSessionFetcher: https://github.com/google/gtm-session-fetcher.git @ 3.1.1
  GoogleAppMeasurement: https://github.com/google/GoogleAppMeasurement.git @ 10.10.0
  SwiftProtobuf: https://github.com/apple/swift-protobuf.git @ 1.22.0
  gRPC: https://github.com/google/grpc-binary.git @ 1.50.2
  Promises: https://github.com/google/promises.git @ 2.2.0
  GoogleUtilities: https://github.com/google/GoogleUtilities.git @ 7.11.1
  Firebase: https://github.com/firebase/firebase-ios-sdk @ 10.10.0
  leveldb: https://github.com/firebase/leveldb.git @ 1.22.2
  abseil: https://github.com/google/abseil-cpp-binary.git @ 1.2022062300.0
  GoogleDataTransport: https://github.com/google/GoogleDataTransport.git @ 9.2.3

2023-06-12 13:38:47.787 xcodebuild[32413:8575837] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x6000031f0400: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/swift-protobuf/Sources/protoc-gen-swift/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}
Computing target dependency graph and provisioning inputs
2023-06-12 13:38:50.464 xcodebuild[32413:8575863]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x60000151abc0; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2023-06-12 13:38:50.467 xcodebuild[32413:8575863]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired. Please log in." UserInfo={payload={
    creationTimestamp = "2023-06-12T10:38:50Z";
    httpCode = 200;
    protocolVersion = QH65B2;
    requestUrl = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action";
    responseId = "39f40334-b3ff-418e-b9b6-dc4b09e55585";
    resultCode = 1100;
    resultString = "Your session has expired. Please log in.";
    userLocale = "en_US";
    userString = "Your session has expired. Please log in.";
}, NSLocalizedDescription=Your session has expired. Please log in.}

Create build description
Build description signature: 1de1a3320b63060eeac8ee6054441eab
Build description path: /Users/user/Software/macos-project/build/XCBuildData/1de1a3320b63060eeac8ee6054441eab.xcbuilddata

warning: Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning
ClangStatCache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk /var/folders/3y/wxqdg41958n7cl4xdf9qzxxh0000gn/C/com.apple.DeveloperTools/14.3-14E222b/Xcode/SDKStatCaches.noindex/macosx13.3-22E245-.sdkstatcache
    cd /Users/user/Software/macos-project/project.xcodeproj
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -o /var/folders/3y/wxqdg41958n7cl4xdf9qzxxh0000gn/C/com.apple.DeveloperTools/14.3-14E222b/Xcode/SDKStatCaches.noindex/macosx13.3-22E245-.sdkstatcache

CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/Release
    cd /Users/user/Software/macos-project/project.xcodeproj
    builtin-create-build-directory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/Release
error: File exists but is not a directory: /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build

CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs/Release
    cd /Users/user/Software/macos-project/project.xcodeproj
    builtin-create-build-directory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs/Release
error: File exists but is not a directory: /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs

warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'project' from project 'project')
warning: Run script build phase 'Swiftlint' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'project' from project 'project')
warning: Run script build phase 'Firebase' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'project' from project 'project')
** BUILD FAILED **


The following build commands failed:
	CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/Release
	CreateBuildDirectory /Users/user/Library/Developer/Xcode/DerivedData/project-enqmgygeiagmohbnywjtetshcnrr/SourcePackages/checkouts/nanopb/build/EagerLinkingTBDs/Release
```

### If using Swift Package Manager, the project's Package.resolved

{
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
        "version" : "1.2022062300.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "5034479ca0c4f32f299677fb0ba1fe4d3e3e20b4",
        "version" : "10.10.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "69f5b8425dd473d2f2475bba7f88f82cd9da0e36",
        "version" : "10.10.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "7874c1b48cbffd086ce8a052c4be873a78613775",
        "version" : "9.2.3"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "871d43135925cde39ef7421d8723ce47edfdcc39",
        "version" : "7.11.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "f1b366129d1125be7db83247e003fc333104b569",
        "version" : "1.50.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "d415594121c9e8a4f9d79cecee0965cf35e74dbd",
        "version" : "3.1.1"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "ec957ccddbcc710ccc64c9dcbd4c7006fcf8b73a",
        "version" : "2.2.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "f25867a208f459d3c5a06935dceb9083b11cd539",
        "version" : "1.22.0"
      }
    }
  ],
  "version" : 2
}

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-06-12 17:42
Are you able to share a reproducible example?

**Comment by MMavrisPaleBlue** [comment] 2023-06-13 05:40
Yes, you can checkout the project here: https://github.com/wakatime/macos-wakatime/tree/feature/76-crashlytics

(very simple project)

**Comment by paulb777** [comment] 2023-06-14 15:32
There is no XCode project at that link:

```
$ xcodebuild
Command line invocation:
    /Applications/Xcode14.2.app/Contents/Developer/usr/bin/xcodebuild

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2023-06-14 08:31:38.729 xcodebuild[9800:18057232] Writing error result bundle to /var/folders/f8/780yxvcx2x91wmlsmvyv0bdr00bzqz/T/ResultBundle_2023-14-06_08-31-0038.xcresult
xcodebuild: error: The directory /Users/paul/bugs/11426/macos-wakatime does not contain an Xcode project.
```

**Comment by paulb777** [comment] 2023-06-14 15:55
Oh, I see that the project expects Xcodegen to be run. Perhaps, there's an issue with the Xcodegen project generation.

**Comment by paulb777** [comment] 2023-06-14 17:49
I see the same issue in a new macos project that adds a Crashlytics dependency.

It looks likes there may be a strange interaction between contents of the nanopb repo and the SwiftPM build process.

**Comment by paulb777** [comment] 2023-06-14 18:32
The build get further after `rm /Users/paul/Library/Developer/Xcode/DerivedData/WakaTime-ajddjvloqqdypzgpcnvixhudzlox/SourcePackages/checkouts/nanopb/build` but then runs into other issues:
```
fatal error: module map file
      '/Users/paul/Library/Developer/Xcode/DerivedData/WakaTime-ajddjvloqqdypzgpcnvixhudzlox/SourcePackages/checkouts/GoogleDataTransport/build/GeneratedModuleMaps/nanopb.modulemap'
      not found
```

**Comment by ncooke3** [comment] 2023-06-14 21:17
Hi @MMavrisPaleBlue, this seems like it might be related to the `xcodebuild` invocation.

Try passing a scheme to your `xcodebuild` invocation using the `-scheme` argument. To get a list of valid schemes names, run `xcodebuild -list` in your project's directory. 

It might perhaps be: `xcodebuild -scheme WakaTime`

The difference seems to be that, with a scheme passed, artifacts go into a different folder (`DerivedData/WakaTime-ajddjvloqqdypzgpcnvixhudzlox/Build/Intermediates.noindex/nanopb.build/Debug/nanopb.build/Objects-normal/x86_64/`) rather than the package repo checkouts. Even so, it seems weird that not passing a scheme leads to such a misleading error. Ideally, the xcodebuild error message should be a little clearer here.

**Comment by MMavrisPaleBlue** [comment] 2023-06-15 08:49
Solved! Thank you

**Comment by paulinon** [comment] 2023-06-15 10:13
Good to hear about this, @MMavrisPaleBlue. I'll be closing this for now.

**Closed by paulinon** 2023-06-15 10:13 UTC
Labels: Swift Package Manager

**Comment by MMavrisPaleBlue** [comment] 2023-06-20 09:48
Still having this issue with a different project that uses Firebase. I am passing ` xcodebuild -scheme `Paid - Staging``
Do you plan on fixing this?

**Comment by paulb777** [comment] 2023-06-20 13:41
@MMavrisPaleBlue From what we've seen, this is an issue with `xcodebuild`, not Firebase, so a feedback should be filed with Apple to get a fix. We'll need a reproducible example to investigate why the `-scheme` workaround doesn't always work.
