### ISSUE TITLE
[MacOS] Firebase causes large packet drops on non-Apple routers

### ISSUE THREAD

**Issue by dsanghan** [firebase/firebase-ios-sdk#313] opened 2017-09-26 06:24 UTC
* Xcode version: 8.3.2
  * Firebase Community: 0.1.2 via cocoapods
  * Firebase Product: Auth, Core, Database

Problem:

Firebase, on initializing, causes large packet drops. 

Here you can see how the ping times spike as soon as firebase initializes:
<img width="425" alt="screen shot 2017-09-26 at 11 50 21 am" src="https://user-images.githubusercontent.com/6698354/30845475-445ffea2-a2b1-11e7-816b-54dd27da3fae.png">

#### Steps to reproduce:

1. Integrate firebase into your project via cocoapods
2. Initialize firebase with
```
    [FIRApp configure];
    [[FIRDatabase database] setPersistenceEnabled:YES];
    self.ref = [[FIRDatabase database] reference];
```
3. Notice massive packet drops and latency on router

We've tested this on several different routers from Netgear, TP-Link and Asus.

The issue does not occur on an Airport Extreme and stops occurring as soon as we remove the above three lines.

**Comment by neerajcse** [comment] 2017-12-18 05:24
I suspect that this happens on Android SDK too.
After using "keepSynced" and "setPersistenceEnabled", I've seen much longer load times on my app.

**Comment by morganchen12** [comment] 2018-10-12 22:48
Closing since this issue has staled. FirebaseCommunity has been deprecated; if this issue continues to reproduce, please comment here and I'll reopen it.

**Closed by morganchen12** 2018-10-12 22:48 UTC
Labels: help wanted
