### ISSUE TITLE
Firebase 6.7.0 crash hard_assert_apple.mm line 34

### ISSUE THREAD

**Issue by Banck** [firebase/firebase-ios-sdk#3678] opened 2019-08-24 14:09 UTC
* Xcode version: 10.3.
  * Firebase SDK version: 6.7.0
  * Firebase Component: Firestore, Messaging
  * Component version: 
Core-6.2.1 
Firestore-1.4.4

I've updated to firebase 6.7.0 from 6.6.0 due another crash, which was fixed in #3623  .
But in 6.7.0 there is a new crash from fabric reporting:
```
Fatal Exception: NSInternalInconsistencyException
FIRESTORE INTERNAL ASSERTION FAILED: Expected to be called by the executor associated with this queue (expected executor: 'com.google.firebase.firestore', actual executor: 'com.apple.main-thread') (expected executor_->IsCurrentExecutor())
```
![image](https://user-images.githubusercontent.com/6259254/63638520-7374f080-c6b3-11e9-8903-0582a2bf546b.png)

**Comment by paulb777** [comment] 2019-08-24 14:27
@Banck Thanks for the report. This looks like a duplicate of #3661 that was fixed in a Firestore patch update yesterday. Please run `pod update` to get the FirebaseFirestore 1.4.5 pod.

**Closed** 2019-08-24 14:27 UTC
Labels: api: firestore
