### ISSUE TITLE
Storage directory directly visible to/accessible for the user on iOS

### ISSUE THREAD

**Issue by hm122** [firebase/firebase-ios-sdk#10036] opened 2022-07-22 09:41 UTC
### Feature proposal

* Firebase Component: Firebase iOS SDK

Currently it looks like for FirebaseDatabase, when persistence is enabled, `getApplicationDocumentsDirectory` is used to set the path for the cached data.
On iOS, this folder is fully accessible in the "Files" app for the user. It would be better to either use `getApplicationSupportDirectory` for iOS or make the path of the cache directory dynamic.

### Steps to reproduce
Steps to reproduce the behaviour (also works in the iOS Simulator):

- FirebaseDatabase.instance.setPersistenceEnabled(true);
- Sync some data
- Check "Files" app on iOS

### Expected behaviour
The folder is not visible for the user and can not be accessed by the user. Either by using `getApplicationSupportDirectory` for iOS or by making the path of the persistence cache directory dynamic.

**Comment by paulb777** [comment] 2022-07-22 13:28
@hm122 Sorry about the trouble and thanks for the report. This is a duplicate of #2984.  As described there, migration makes this a challenge to implement. Please thumbs-up that issue to help us increase the priority.

**Closed by paulb777** 2022-07-22 13:28 UTC
Labels: api: database, type: feature request

**Comment by hm122** [comment] 2022-07-31 20:03
@paulb777 I understand the migration challenge. But it still would be good to add the path as an option, as this gives new apps the possibility to use to correct path. 

I see three options:
a) New apps: Should use the new path which isn't visible in Files
b) Existing apps #1: Don't migrate and start fresh with the new path
c) Existing apps #2: Migrate current files to new path

a) and b) should be straight forward, c) might be a more complicated (not sure about the detailed issues, probably copying files to the new location is not enough?). 

Since  #2984 is open for over 3 years, I think it would already help to implement at least a) and b)?
