### ISSUE TITLE
After upgrading to 10.25.0, this crash occurred: -[FIRCLSRolloutsPersistenceManager updateRolloutsStateToPersistenceWithRollouts:reportID:] + 356

### ISSUE THREAD

**Issue by ilyon** [firebase/firebase-ios-sdk#13126] opened 2024-06-13 12:52 UTC
### Description

In the last version, we upgraded the firebase sdk from 8.14.0 to 10.25.0. After the upgrade, we collected this crash in xcode. The screenshot shows the detailed stack information. Is there a fixed version available for upgrade?
![7831718283009_ pic](https://github.com/firebase/firebase-ios-sdk/assets/2276323/01e6bbb0-9466-44de-a392-d2dc195efa25)

### Firebase SDK Version

10.25.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing, Analytics, Authentication, Crashlytics, Remote Config, Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2024-06-13 13:21
Thanks for reporting, @ilyon. This seems to be a duplicate of #12913. Please refer to the original issue for updates.

**Closed by rizafran** 2024-06-13 13:21 UTC
Labels: api: crashlytics
