### ISSUE TITLE
Crashed: com.google.firebase.firestore

### ISSUE THREAD

**Issue by sspogra** [firebase/firebase-ios-sdk#10697] opened 2023-01-17 14:16 UTC
### Description

Crashed: com.google.firebase.firestore
0  libsystem_kernel.dylib         0xb160 __pthread_kill + 8
1  libsystem_pthread.dylib        0x71ac pthread_kill + 268
2  libsystem_c.dylib              0x20c8c abort + 180
3  libsystem_malloc.dylib         0x1de2c malloc_vreport + 908
4  libsystem_malloc.dylib         0x1e0d0 malloc_zone_error + 100
5  libsystem_malloc.dylib         0x185ac nanov2_guard_corruption_detected + 44
6  libsystem_malloc.dylib         0x16758 nanov2_free_definite_size + 402
7  libc++abi.dylib                0x138b0 operator new(unsigned long) + 32
8  FirebaseFirestore              0x9721c firebase::firestore::remote::(anonymous namespace)::AppendToGrpcBuffer(pb_ostream_s*, unsigned char const*, unsigned long) + 235 (new:235)
9  nanopb                         0x6f2c pb_write + 117 (pb_encode.c:117)
10 nanopb                         0x7584 pb_encode_varint + 627 (pb_encode.c:627)
11 nanopb                         0x7a3c pb_enc_bytes + 711 (pb_encode.c:711)
12 nanopb                         0x71f8 encode_field + 411 (pb_encode.c:411)
13 nanopb                         0x7010 pb_encode + 544 (pb_encode.c:544)
14 FirebaseFirestore              0x16a998 firebase::firestore::nanopb::Writer::Write(pb_field_s const*, void const*) + 43 (writer.cc:43)
15 FirebaseFirestore              0x1660b0 grpc::ByteBuffer firebase::firestore::remote::MakeByteBuffer<firebase::firestore::_google_firestore_v1_ListenRequest>(firebase::firestore::nanopb::Message<firebase::firestore::_google_firestore_v1_ListenRequest> const&) + 71 (grpc_nanopb.h:71)
16 FirebaseFirestore              0x165f94 firebase::firestore::remote::WatchStream::WatchQuery(firebase::firestore::local::TargetData const&) + 67 (watch_stream.cc:67)
17 FirebaseFirestore              0x129f60 firebase::firestore::remote::RemoteStore::Listen(firebase::firestore::local::TargetData) + 196 (remote_store.cc:196)
18 FirebaseFirestore              0x13f0d0 firebase::firestore::core::SyncEngine::Listen(firebase::firestore::core::Query) + 54 (target_data.h:54)
19 FirebaseFirestore              0x44740 firebase::firestore::core::EventManager::AddQueryListener(std::__1::shared_ptr<firebase::firestore::core::QueryListener>) + 60 (event_manager.cc:60)
20 FirebaseFirestore              0x6ebdc std::__1::__function::__func<firebase::firestore::core::FirestoreClient::ListenToQuery(firebase::firestore::core::Query, firebase::firestore::core::ListenOptions, std::__1::shared_ptr<firebase::firestore::core::EventListener<firebase::firestore::core::ViewSnapshot>>&&)::$_13, std::__1::allocator<firebase::firestore::core::FirestoreClient::ListenToQuery(firebase::firestore::core::Query, firebase::firestore::core::ListenOptions, std::__1::shared_ptr<firebase::firestore::core::EventListener<firebase::firestore::core::ViewSnapshot>>&&)::$_13>, void ()>::operator()() + 958 (shared_ptr.h:958)
21 FirebaseFirestore              0x67b8 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 997 (atomic:997)
22 FirebaseFirestore              0x14e3e4 firebase::firestore::util::Task::ExecuteAndRelease() + 491 (function.h:491)
23 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
24 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
25 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
26 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
27 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
28 libsystem_pthread.dylib        0xb98 start_wqthread + 8

### Reproducing the issue

Don't know exactly why this crash happened but as per log app crashed on get data and added a Listener on a document.

### Firebase SDK Version

10.1.0

### Xcode Version

14.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, Database, Firestore, Messaging, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by dconeybe** [comment] 2023-01-18 16:01
This crash too almost certainly has the same root cause as the other listener-related crashes that you've reported. I'm going to close this one and use https://github.com/firebase/firebase-ios-sdk/issues/10611 as the canonical issue to track progress.

**Closed** 2023-01-18 16:09 UTC
Labels: api: firestore

**Comment by sspogra** [comment] 2023-01-18 16:35
@dconeybe Thanks.
