### ISSUE TITLE
Update GoogleAppMeasurement version to avoid macOS version error.

### ISSUE THREAD

**Issue by AdieOlami** [firebase/firebase-ios-sdk#8339] opened 2021-07-05 16:44 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 10.25
  * Firebase SDK version: 8.2.0
  * Installation method: `Swift Package Manager` (select one)
  * Firebase Component: Messaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
When you run swift `swift build` you get an error

`error: the library 'GoogleAppMeasurementTarget' requires macos 10.10, but depends on the product 'GULAppDelegateSwizzler' which requires macos 10.12; consider changing the library 'GoogleAppMeasurementTarget' to require macos 10.12 or later, or the product 'GULAppDelegateSwizzler' to require macos 10.10 or earlier.`

After investigating the problem, I discovered that the problem is using an app measurement .package(
      name: "GoogleAppMeasurement",
      url: "https://github.com/google/GoogleAppMeasurement.git",
      .exact("8.3.0")
    )

using the exact version means macOS version would be 10.10. If you could bump this version up all would be fine.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ryanwilson** [comment] 2021-07-05 19:36
Thanks for the report and sorry for the troubles. 

It looks like there was an attempt at a fix here: https://github.com/google/GoogleAppMeasurement/pull/12 which is included in the 8.3.0 release: https://github.com/google/GoogleAppMeasurement/blob/06e74ef7ee7326e1af724d462091eed1e5c6fb4a/Package.swift#L22

Are the reproduction steps the same for you as the issue linked above, or did you follow a different set of steps?

**Comment by AdieOlami** [comment] 2021-07-05 19:42
Yes, it works changing the branch to master. but then this error pops up.

`error: artifact 'GoogleAppMeasurement' does not support the target platform and architecture ('Triple(tripleString: "arm64-apple-macosx", arch: TSCUtility.Triple.Arch.arm64, vendor: TSCUtility.Triple.Vendor.apple, os: TSCUtility.Triple.OS.macOS, abi: TSCUtility.Triple.ABI.unknown)')`

`swift build -Xswiftc "-sdk" -Xswiftc "xcrun --sdk iphonesimulator --show-sdk-path" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios11.0-simulator"`

**Comment by paulb777** [comment] 2021-07-06 00:07
GoogleAppMeasurement (a FirebaseAnalytics dependency) does not currently support macOS.  See #1732.  You may need to use `xcodebuild` instead of `swift build` to build from the command line.

**Comment by paulb777** [comment] 2021-07-07 21:43
Going to close since the version error is addressed in 8.3.0.  We can continue the discussion here though.

**Closed by paulb777** 2021-07-07 21:43 UTC
Labels: Swift Package Manager, api: analytics, macOS

**Comment by Kaspik** [comment] 2021-07-09 11:40
<img width="1140" alt="Screenshot 2021-07-09 at 13 40 06" src="https://user-images.githubusercontent.com/7204168/125072692-2dfd1900-e0bb-11eb-9572-e8961d37d459.png">

Probably related, but after upgrading to Firebase 8.3.0 via SPM, I'm not able to run the project anymore. Should I create new issue?

**Comment by ryanwilson** [comment] 2021-07-09 13:47
@Kaspik I've seen that happen even outside of the upgrade cycle, it seems to be an Xcode flake that happens occasionally. Typically going to `File -> Swift Packages -> Reset Package Cache` works for me.
