### ISSUE TITLE
When I use NSProxy to hook NSURLSession, I get a crash in +[GULSwizzler ivarObjectsForObject].

### ISSUE THREAD

**Issue by ritchie7** [firebase/firebase-ios-sdk#9951] opened 2022-06-27 09:33 UTC
```
+ (NSArray<id> *)ivarObjectsForObject:(id)object {
  NSMutableArray *array = [NSMutableArray array];
  unsigned int count;
  Ivar *vars = class_copyIvarList([object class], &count);
  for (NSUInteger i = 0; i < count; i++) {
    const char *typeEncoding = ivar_getTypeEncoding(vars[i]);
    // Check to see if the ivar is an object.
    if (strncmp(typeEncoding, "@", 1) == 0) {
      id ivarObject = object_getIvar(object, vars[i]);
      [array addObject:ivarObject];
    }
  }
  free(vars);
  return array;
}
```

In my project, object is a real obj for NSURLSession's NSProxy, and `class_copyIvarList([object class], &count)` is the function that gets the real object (NSURLSession instance). When the code reaches `object_getIvar()`, an EXC_BAD_ACCESS crash will occur.

thanks.

**Comment by rizafran** [comment] 2022-06-27 11:31
Thanks for reporting, @ritchie7. Please fill out the needed information from the template so we could try to reproduce the issue.

**Comment by ritchie7** [comment] 2022-06-28 02:17
Sorry, here is the information I added:
---------------------------------------------------
  * Xcode version: 13.2.1 (13C100)
  * Firebase SDK version: 8.14.0
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics, Core, Database, Firestore, Messaging, Storage, Performance, RemoteConfig, FirebaseAnalytics, FirebaseABTesting
  * Target platform(s): `iOS`
---------------------------------------------------
![CleanShot 2022-06-28 at 10 15 57@2x](https://user-images.githubusercontent.com/22406308/176077094-3810c0ed-b55a-441e-ae9d-0b5010e87ad5.png)

In my project, object is a real obj for NSURLSession's NSProxy, and class_copyIvarList([object class], &count) is the function that gets the real object (NSURLSession instance). When the code reaches object_getIvar(), an EXC_BAD_ACCESS crash will occur.


---------------------------------------------------


Here is my code for hooking NSURLSession.
---------------------------------------------------
```
// The implementation of `NSProxy1`/`NSProxy2` and GULProxy is the same.
+ (NSURLSession *)swizzling_sharedSession {
    NSURLSession *session = [NSProxy1 proxyWithTarget:[self swizzling_sharedSession]];
    return session;
}

+ (NSURLSession *)swizzling_sessionWithConfiguration:(NSURLSessionConfiguration *)configuration
                                    delegate:(id<NSURLSessionDelegate>)delegate
                               delegateQueue:(NSOperationQueue *)queue {
    
    id delegateProxy = [NSProxy2  proxyWithTarget:delegate];
    
    NSURLSession *session = [self swizzling_sessionWithConfiguration:configuration
                                                    delegate:delegateProxy
                                               delegateQueue:queue];
    return (id<NSObject>)[NSProxy1 proxyWithTarget:session];
}
```

Thanks

**Comment by paulb777** [comment] 2022-06-28 22:43
Does removing FirebasePerformance make a difference?

**Comment by ritchie7** [comment] 2022-06-29 02:13
> 
Thank you for your reply.
If firebasePerformance is removed, the crash will not occur, because `-[FPRNSURLSessionInstrument registerProxyObject:]` is not executed.

**Comment by paulb777** [comment] 2022-06-29 19:19
Thanks. I'll assign to the Performance team for investigation.

**Comment by exaby73** [comment] 2024-11-12 13:48
Since this issue hasn't had any updates recently and I am not able to reproduce it, I am closing this issue. If this issue occurs again, please file a new issue with information about your current environment. Thank you

**Closed by exaby73** 2024-11-12 13:48 UTC
Labels: api: performance, GoogleUtilities, needs-attention
