### ISSUE TITLE
10Mb limit problem with WriteBatches

### ISSUE THREAD

**Issue by macoapps** [firebase/firebase-ios-sdk#933] opened 2018-03-16 09:25 UTC
### Environment :
  * Xcode version: 9.2
  * Firebase SDK version: 4.10.1
  * Firebase Component: Firestore
  * Component version: latest

### Describe the problem
I need to create a large amount of documents (created from big JSON files).
I extract JSON data to create custom objects, then loop through those objects. Each time I reach 500 objects, I create a Write batch, set objects (500 or less), then commit the batch.
As I understand, the SDK puts each batch in his own queue, and the "real" commit is done when the function ends. But if the queue size exceeds 10Mb (approx.), it does nothing (no network activity)
Is there any way to "force" the queue to be commited ?
Regards

PS : sorry for my english, i'm french, and jsu discovered that it's not that simple to explain my pb :)

**Comment by morganchen12** [comment] 2018-03-16 16:46
Even if this is an intentional limitation, our communication around it could be more clear. @wilhuff wdyt?

**Comment by macoapps** [comment] 2018-03-19 13:01
actually, i found a kind of workaround : i use transaction instead of writebatch, and it seems to work like a charm. I was able to write ~500Mb in one function call (and approx. 20k transactions)

**Comment by mikelehen** [comment] 2018-03-26 15:23
@macoapps Thanks for bringing this up.  There are a few things going on it looks like:

- There is a 10mb limit to the size of a write batch or transaction. This should be documented [here](https://firebase.google.com/docs/firestore/quotas#writes_and_transactions) but it is not currently. We'll get that fixed.
- It looks like when using a Write Batch you'll actually hit a limit of 3MB per batch. I don't think this is intentional and we'll look into fixing this so that you can send up to 10MB..
- If you send several Write Batches in a row that together exceed ~10-20MB total I am seeing that our backend stream can end up "stuck." It gets an UNAVAILABLE error from the backend and retries the writes, over and over.  I'm guessing this is what you saw. This is a bug too and we'll look into it.

For now, your workaround seems like a good idea.  You could also probably use write batches < 3MB and perhaps wait for each one to complete before starting the next one, but if the transaction is working for you, you can go ahead and stick to that.

Thanks again for reporting this.

**Comment by morganchen12** [comment] 2018-05-31 20:09
@mikelehen were these bugs fixed? I see the docs were changed a while ago to reflect the batched write size limits.

**Comment by mikelehen** [comment] 2018-06-01 15:46
Not entirely.  The write size limit was documented which is good, but the second 2 issues are still active. I guess I'll close this though since they are backend issues rather than issues in the iOS SDK and so this issue isn't tracking anything actionable.

If folks run into this, feel free to comment here or contact Firebase Support. For reference, the internal issue tracking the issues is b/76411277.

**Closed by mikelehen** 2018-06-01 15:46 UTC
Labels: Firestore

**Comment by KabukiAdam** [comment] 2019-02-07 18:15
@mikelehen Hi, I was wondering if you had any info about whether the third issue in your above comment has been fixed yet?  (server getting stuck after ~10MB of writes).

We're experiencing something very similar to this in our own app, except it is actually a bit worse:
- If we write (add) multiple documents consecutively, once we hit ~10MB in total data written, the subsequent writes don't make it to the server.  In the developer console, we see the first ~10MB of documents only.  Additionally, the iOS client setData() completion calls only get called for the first ~10MB of document writes.  For subsequent calls, the completion handler is never called at all (not even with an error).
- The problem happens regardless of the size of the individual documents.
- The problem happens regardless any time delays in between the writes (we've tried delays up to 10s between each document write and the problem still occurs).
- The problem happens regardless of whether the writes are batched or not (your description of the issue above only mentioned batch writes).

I've created a [simple test app](https://github.com/KabukiAdam/FirestoreLargeWriteTest) that demonstrates the problem.

Do you have any advice or guidance on this?  We haven't been able to find any workarounds, and it severely impacting our ability to ship our app.  If this sounds like a different issue to this one, let me know and I can create a new one.  Thanks.

**Comment by mikelehen** [comment] 2019-02-07 18:45
@KabukiAdam To be honest, I'm not 100% sure the latest state of the backend's flow control behavior which is what we were running into before (if you sent too many big writes too fast, it would behave poorly). I'll see if I can get an update from the backend team.

But the workaround for the prior issue was basically just to throttle yourself.  I.e. if you are writing large amounts of data, try to write it in chunks less than 5-10MB, and wait for each chunk to complete before sending the next one.

**Comment by KabukiAdam** [comment] 2019-02-07 18:53
@mikelehen Thanks for your reply.  It would be great to get an update on this from the backend team.

Regarding the workaround, unfortunately this isn't working for us, and we've tried all sorts of throttling and timing to no avail.  

For example, if we write one single 100kB document, wait for it to complete, then wait a full several seconds before writing the next 100kB document, etc, then as soon as the total written hits ~10MB (about 115 documents), the problem occurs.  We haven't been able to find any combination of doc size + throttling speed that works around the issue.   🙁

**Comment by mikelehen** [comment] 2019-02-07 18:54
That sounds really bizarre. I'll try to dig into this.

**Comment by KabukiAdam** [comment] 2019-02-07 18:57
Thanks. If it helps, the [test app](https://github.com/KabukiAdam/FirestoreLargeWriteTest) I created makes it really easy to reproduce the issue.

**Comment by mikelehen** [comment] 2019-02-07 19:14
Yep, I'll give that a try.

And if you're really in a bind for a workaround, try calling [disableNetwork()](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Firestore#/c:objc(cs)FIRFirestore(im)disableNetworkWithCompletion:) followed by enableNetwork() periodically. That will restart our network streams, which I suspect will work around the issue.

**Comment by mikelehen** [comment] 2019-02-07 20:25
I've reproduced the problem and can confirm this isn't expected behavior. I've opened an internal tracking bug (b/76411277) and am working with the backend team.  We have a hunch what the problem is but even if correct, it could unfortunately be a couple weeks before we can roll out a fix to production.

**Comment by KabukiAdam** [comment] 2019-02-25 22:37
It appears that this issue might be solved? @mikelehen can you confirm?  When I run my test app now, everything seems to work as expected.  We can now write lots of batches in a row, and as long as each batch is under the 500-document/10Mb limit, the server never seems to get "stuck" as it previously did.

**Comment by mikelehen** [comment] 2019-02-26 22:15
@KabukiAdam Yes! It looks like the fix did indeed roll out to production, so you should no longer see this going forward.  Thanks very much for your help in tracking it down!
