### ISSUE TITLE
Analytics.setUserProperty nil doesn't remove it

### ISSUE THREAD

**Issue by victor-sarda** [firebase/firebase-ios-sdk#3230] opened 2019-06-20 13:04 UTC
###  Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.3.0
  * Firebase Component: Analytics
  * Component version: 6.3.0

### Describe the problem

When setting a user property value to `nil` with `Analytics.setUserProperty` I'm expecting it to be removed on Firebase as the documentation says:

> The value of the user property. Values can be up to 36 characters long. Setting the value to nil removes the user property.

#### Steps to reproduce:

1. Send a user property on firebase analytics like this
`Analytics.setUserProperty(<property>, forName: <name>)`.
2. Go to the debug view in the firebase console and check that property is set
3. Call `Analytics.setUserProperty(nil, forName: <name>)`
4. Go back to the debug view

The property is still here in the debug view but I'm expecting it to be gone. This is quite annoying since we can only set 25 properties but we can't remove any.

**Comment by morganchen12** [comment] 2019-06-20 16:48
@htcgh can you confirm this is a bug?

**Comment by allenktv** [comment] 2019-06-24 17:30
Thanks @victor-sarda. I just reproduced this and believe that it may just be a UI issue since the bundle uploaded does not have the user property anymore after setting it to nil. 

Tracked internally at b/135926151

**Comment by victor-sarda** [comment] 2019-06-25 09:07
Thanks @allenktv 😊 
Just to clarify, if we set `nil` right now, property is actually removed and we can set a new one instead? I guess UI should be working fine in BigQuery?

**Comment by allenktv** [comment] 2019-06-25 16:58
@victor-sarda 
Yes I believe so. 
The debug view is still an issue and we will get that fixed. Thank you for reporting this and please let us know if you encounter any more issues!

**Comment by victor-sarda** [comment] 2019-06-25 17:11
Thanks :)

**Comment by allenktv** [comment] 2019-08-07 17:48
Closing this issue

**Closed by allenktv** 2019-08-07 17:48 UTC
Labels: api: analytics
