### ISSUE TITLE
GDTEvent class conflict

### ISSUE THREAD

**Issue by arthurchenjs** [firebase/firebase-ios-sdk#3800] opened 2019-09-09 03:06 UTC
GDTEvent class conflict

duplicate symbol _OBJC_CLASS_$_GDTEvent in:
.........SDK/Frameworks/GDT/libGDTMobSDK.a(GDTEvent.o)
.........Build/Products/Debug-iphoneos/GoogleDataTransport/libGoogleDataTransport.a(GDTEvent.o)

**Comment by morganchen12** [comment] 2019-09-09 03:43
Duplicate of #3729

**Closed by morganchen12** 2019-09-09 03:43 UTC
Labels: GoogleDataTransport
