### ISSUE TITLE
Error 'Cannot find 'Messaging' in scope' after installing with Swift Package Manager

### ISSUE THREAD

**Issue by ilosqut** [firebase/firebase-ios-sdk#6654] opened 2020-10-03 07:48 UTC
* Xcode version: 12.0.1
  * Firebase SDK version: 6.31-spm-beta
  * Firebase Component: Messaging
  * Component version: 6.31-spm-beta
  * Installation method: Swift Package Manager

Installed all Firebase components with Swift package manager 6.31-spm-beta branch.
All manuals describe steps to setup Firebase messaging:

```
import Firebase
....
FirebaseApp.configure()
Messaging.messaging().delegate = self

...

func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
    }
```
Xcode failed with error:
 'Cannot find 'Messaging' in scope'

**Comment by paulb777** [comment] 2020-10-03 13:59
As documented at https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md, SwiftPM support for Messaging has not yet been released.  It has been implemented in the upcoming Firebase 7 milestone and will be released in the next month or two.

**Closed by paulb777** 2020-10-03 13:59 UTC
Labels: needs-triage

**Comment by rrozenv** [comment] 2020-10-05 15:42
@paulb777 what would recommend doing if we needed Messaging as a dependency but are using the spm beta branch for all other Firebase dependencies? 

Would it possible to add only Messaging as a binary target to an SPM package which depends on the spm beta branch? And if not, would it be possible to add only the Messaging .xcframeworks at the project level?

**Comment by paulb777** [comment] 2020-10-05 15:47
@rrozenv It's a bit ugly but probably workable to add the Messaging .xcframework (and its dependencies not part of SwiftPM) from the [Firebase binary](https://github.com/firebase/firebase-ios-sdk/releases/tag/CocoaPods-6.33.0) or Carthage distributions.

**Comment by rrozenv** [comment] 2020-10-06 02:26
@paulb777 Thank you for the quick reply. Do you know if there is any way to get around having some dependencies be pulled from the spm branch, but then also linking Messaging as a binary target? 

The problem is that some of the lower level dependencies like FirebaseCore and FirebaseInstallations are required for both Messaging and by those pulled from the spm branch. Below I have included my Package.manifest file which illustrates what I am attempting to do. This package actual compiles perfectly fine, but when I add it to an Xcode project I get the following errors:
 
   -ld: warning: Could not find or use auto-linked framework 'FirebaseCore'
  - ld: warning: Could not find or use auto-linked framework 'FirebaseInstallations'

And if I attempt to add 'FirebaseCore' and 'FirebaseInstallations' as binary targets then the package does not compile any longer and I get the following error: "multiple targets named Firebase Core"

I feel like mixing and matching dependencies in this manner won't work, but just wanted to see if you had any ideas. If it doesn't work then would the next approach be to actually add every single Firebase dependency as a binary target and not depend on the spm branch at all? That would defeat the purpose of having a swift package at all, but do you believe it would work in theory? 

```
let package = Package(
	name: "QuarkFirebase",
	platforms: [
		.iOS(.v13),
		.macOS(.v10_15),
		.tvOS(.v13)
	],
	products: [
		.library(
			name: "QuarkFirebase",
			targets: ["QuarkFirebase"]
		)
	],
	dependencies: [
		.package(
			name: "Firebase",
			url: "git@github.com:firebase/firebase-ios-sdk.git",
			.branch("6.32-spm-beta")
		)
	],
	targets: [
		.target(
			name: "QuarkFirebase",
			dependencies: [
				.target(name: "FirebaseMessaging"),
				.target(name: "FirebaseInstanceID"),
				.target(name: "Protobuf"),
				.product(name: "FirebaseAuth", package: "Firebase"),
				.product(name: "FirebaseStorage", package: "Firebase"),
				.product(name: "FirebaseDatabase", package: "Firebase"),
				.product(name: "FirebaseFirestore", package: "Firebase"),
				.product(name: "FirebaseFirestoreSwift", package: "Firebase"),
				.product(name: "FirebaseDynamicLinks", package: "Firebase")
			]
		),
		.binaryTarget(
			name: "FirebaseMessaging",
			path: "BinaryFrameworks/FirebaseMessaging.xcframework"
		),
		 .binaryTarget(
			 name: "FirebaseInstanceID",
			 path: "BinaryFrameworks/FirebaseInstanceID.xcframework"
		 ),
		 .binaryTarget(
			 name: "Protobuf",
			 path: "BinaryFrameworks/Protobuf.xcframework"
		 )
	]
)
```

**Comment by paulb777** [comment] 2020-10-06 18:20
Are the `Could not find or use auto-linked framework` warnings actually causing something to fail?

Your approach seems reasonable to me, but I don't have too much time to dive too deep in the near future.
