### ISSUE TITLE
Cocoapod invalid spec 

### ISSUE THREAD

**Issue by EdmundLeex** [firebase/firebase-ios-sdk#5257] opened 2020-04-02 04:29 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _11.3.1____
  * Firebase SDK version: _latest____
  * Firebase Component: _Auth__ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: __latest___
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem
Added `pod 'Firebase/Auth'` to Podfile, and `pod install` fails with error log below. Pointing version to `6.4.0` would not see this error.

#### Steps to reproduce:
Add `pod 'Firebase/Auth'` to Podfile, and run `pod install`

What happened? How can we make the problem occur?
```
### Error

\```
JSON::ParserError - 765: unexpected token at ''
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `map'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/edmund/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/edmund/.rbenv/versions/2.5.1/bin/pod:23:in `load'
/Users/edmund/.rbenv/versions/2.5.1/bin/pod:23:in `<main>'
\```
```
If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulb777** [comment] 2020-04-02 14:33
This looks like a problem in the `Podfile`. There should not be a `v` in the version string.  Please share the `Podfile` if you're still stuck.

**Comment by EdmundLeex** [comment] 2020-04-03 04:43
Oops sorry, I pasted the wrong log. UPdated it.

**Comment by paulb777** [comment] 2020-04-03 14:38
This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/9672. A reproducible test case is needed. Please continue the conversation in that CocoaPods issue.

**Closed by paulb777** 2020-04-03 14:38 UTC
Labels: needs-attention, type: question

**Comment by EdmundLeex** [comment] 2020-04-05 01:05
interestingly, if I specify the FirabaseAuth version to 6.4, I won't run into this error.
