### ISSUE TITLE
Malformed Framework response from App Store Connect

### ISSUE THREAD

**Issue by federicoramos77** [firebase/firebase-ios-sdk#12587] opened 2024-03-19 17:58 UTC
### Description

I got this email from App Store Connect after submitting a macOS app with Firebase 10.23.0 and Xcode 14.3. M1 MacBook with Sonoma 14.3.1
My project only has Firebase as dependency.

I tried:
Removing all dependencies, clearing build folder and derived data. Xcode submission went through but then you receive an email from Connect.
<img width="685" alt="Screenshot 2024-03-19 at 18 54 12" src="https://github.com/firebase/firebase-ios-sdk/assets/75210447/cec81385-7a9c-4c25-bd54-8eb508b16fd3">

### Firebase SDK Version

10.23.0

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

All

### Targeted Platforms

macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "originHash" : "c63c63846d9c539229e96de38d6af51417e28c0ee9a0bc48bd0f0f19d923c329",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "7ce7be095bc3ed3c98b009532fe2d7698c132614",
        "version" : "1.2024011601.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "3e464dad87dad2d29bb29a97836789bf0f8f67d2",
        "version" : "10.18.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "fcf5ced6dae2d43fced2581e673cc3b59bdb8ffa",
        "version" : "10.23.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "6ec4ca62b00a665fa09b594fab897753a8c635fa",
        "version" : "10.23.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "26c898aed8bed13b8a63057ee26500abbbcb8d55",
        "version" : "7.13.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "67043f6389d0e28b38fa02d1c6952afeb04d807f",
        "version" : "1.62.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "76135c9f4e1ac85459d5fec61b6f76ac47ab3a4c",
        "version" : "3.3.1"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "43aaef65e0c665daadf848761d560e446d350d3d",
        "version" : "1.22.4"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "65e8f29b2d63c4e38e736b25c27b83e012159be8",
        "version" : "1.25.2"
      }
    }
  ],
  "version" : 3
}


```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by federicoramos77** [comment] 2024-03-19 18:23
Done. Sorry.

**Comment by paulb777** [comment] 2024-03-19 18:34
Thanks! We've reproduced. It looks like Apple silently added new requirements today or within the last few days since we last tested. 

We'll investigate.

**Comment by paulb777** [comment] 2024-03-19 18:47
If you're using Firestore, but not Analytics, the source SwiftPM build should be a workaround. See https://github.com/firebase/firebase-ios-sdk?tab=readme-ov-file#visionos

**Comment by yakovmanshin** [comment] 2024-03-19 19:58
Same issue here:
* Xcode 15.3 on macOS 14.4 RC (Xcode Cloud) → ASC errors ITMS-90291 and ITMS-90292
* Xcode 15.2 on macOS 14.3.1 (Xcode Cloud) → all good

**Comment by jtaby** [comment] 2024-03-19 20:27
Just wanted to confirm that this issue occurs on 10.23.0 (I was waiting for this update to fix our issue). Seems like @paulb777 you've gotten the repro you need?

**Comment by jtaby** [comment] 2024-03-19 20:39
Thanks all. Appreciate the response. Should we expect a hotfix this week or should we expect this to be part of the normal release cycle? just need to manage expectations with the team.

**Comment by emperinter** [comment] 2024-03-19 23:03
Tested the latest Firebase 10.23.0 , feedback reported the following error, still not working. So the latest version still conflicts with Xcode 15.3? A similar error is mentioned in https://github.com/firebase/firebase-ios-sdk/issues/12505#issuecomment-1989630753


<img width="712" alt="图片" src="https://github.com/firebase/firebase-ios-sdk/assets/20177836/d5c4a3cf-6ba0-4f75-b573-88ebc0784ece">

**Comment by paulb777** [comment] 2024-03-19 23:09
@emperinter The issue in #12505 was addressed. Apple introduced new checks today that we're now working on.

**Comment by emperinter** [comment] 2024-03-19 23:31
🤣 One problem solved, and found a new problem, it is not clear when it can be fixed? The last half month can not be used really quite affect the business monitoring, related work can not be carried out, the team is considering downgrading the relevant program version to solve this problem or migrate to other platforms.

**Comment by paulb777** [comment] 2024-03-20 00:03
One option could be to stay on Xcode 15.2 while the Xcode 15.3/App Store issues get sorted.

**Comment by Lguanghui** [comment] 2024-03-20 02:43
Same issue. Waiting for a new fixed version.

**Comment by jtaby** [comment] 2024-03-20 02:59
> One option could be to stay on Xcode 15.2 while the Xcode 15.3/App Store issues get sorted.

Thanks for this tip, I can confirm it works in the meantime

**Comment by jesus-mg-ios** [comment] 2024-03-20 15:03
Same here, please fix it. Any ETA @ncooke3 ?

**Comment by CristianMoisei** [comment] 2024-03-20 15:10
You can download Xcode 15.2 from [here](https://developer.apple.com/download/all/?q=xcode%2015.2) and use Firebase 10.21. I was able to get my binaries approved for Catalyst this way.

**Comment by jesus-mg-ios** [comment] 2024-03-20 15:11
I know but I have more dependencies that work with Xcode 15.3 and its features are only available on new versions so ...  nothing to do with it.

**Comment by ncooke3** [comment] 2024-03-22 18:35
Hi everyone, we are still working on this. The macOS and macCatalyst framework structure is changing quite a bit, so this is taking some time to work through. The fix is scheduled to be released in 10.24.0 during the week of April 9. For now, the workaround is to use Xcode 15.2. 

Additionally:
> If you're using Firestore, but not Analytics, the source SwiftPM build should be a workaround. See https://github.com/firebase/firebase-ios-sdk?tab=readme-ov-file#visionos

**Comment by pmacro** [comment] 2024-03-31 03:52
You can workaround using something like this, but easier to downgrade of course:

```
# resolve packages as a separate step
xcodebuild -resolvePackageDependencies -workspace My.xcworkspace -scheme MyScheme -derivedDataPath build -destination generic/platform\=macOS,variant\=Mac\ Catalyst

cd build/SourcePackages/artifacts

# Fixes the "Current" symlink. This makes the archive succeed.
find -P . -regex ".*\.framework/\Versions/\Current" -execdir rm -rf {} \; -execdir ln -s A {} \;
# Find the top-level symlinks and fix those too. The archive succeeds without this, but is rejected by Apple.
# I haven't scripted this yet, but `ln -s ` all top-level entries to the matching Versions/Current/blah entry.

# Create the archive as normal, but avoid touching the packages.
xcodebuild -skipPackageUpdates -workspace My.xcworkspace -scheme MyScheme -derivedDataPath build -destination generic/platform\=macOS,variant\=Mac\ Catalyst archive
```

It's surprising this hasn't been an issue before now because this has been [Apple's guidance](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for > 10 years

**Comment by jtaby** [comment] 2024-04-02 14:20
Yeah I think Apple just started enforcing it

**Comment by wojciech-kulik** [comment] 2024-04-08 12:28
@ncooke3 do we have any specific release date? I see in the milestone that everything is already done, isn't it?

**Comment by YoavGro** [comment] 2024-04-09 11:12
This is still reproducing in 10.23.1

**Comment by wojciech-kulik** [comment] 2024-04-09 12:00
@YoavGro the fix is planned in 10.24.0

**Comment by ncooke3** [comment] 2024-04-09 15:39
@wojciech-kulik, 10.24.0 is being released today. It is already released for SPM and the `Firebase.zip` (https://github.com/firebase/firebase-ios-sdk/releases/download/10.24.0/Firebase.zip). 

CocoaPods and Carthage publishing are still in progress.

**Comment by ncooke3** [comment] 2024-04-09 15:41
I'm going to close this issue as the 10.24.0 release should fix this.

**Closed by ncooke3** 2024-04-09 15:41 UTC
Labels: macOS, needs-attention, Catalyst, zip

**Comment by wojciech-kulik** [comment] 2024-04-10 14:07
I can confirm that it works as expected now :). Yesterday I released the app with the latest Firebase package from SPM. 🎊 Thanks for resolving this issue  @ncooke3 🍻
