### ISSUE TITLE
Application crashes after building in XCodeCloud with Xcode 15.3 RC

### ISSUE THREAD

**Issue by Ausianovich** [firebase/firebase-ios-sdk#12463] opened 2024-03-04 16:16 UTC
### Description

When building our app for Archive using Xcode 15.3 RC the app crashes when open it.

### Reproducing the issue

Build an app using Xcode 15.3 RC that uses the Google Firebase Cocoapods

### Firebase SDK Version

10.21

### Xcode Version

15.3 RC

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Thread 0 name:
 Thread 0 Crashed:
 0   MyApp                             0x00000001051380d8 safe_read_bool + 0 (pb_encode.c:140)
 1   MyApp                             0x00000001051380d8 pb_enc_bool + 0 (pb_encode.c:771)
 2   MyApp                             0x0000000105137b00 encode_basic_field + 256 (pb_encode.c:0)
 3   MyApp                             0x0000000105137b00 encode_field + 436 (pb_encode.c:457)
 4   MyApp                             0x0000000105137920 pb_encode + 172 (pb_encode.c:544)
 5   MyApp                             0x000000010467fbfc FIRSESEncodeProto + 64 (FIRSESNanoPBHelpers.m:60)
 6   MyApp                             0x000000010468a2f8 SessionStartEvent.transportBytes() + 232 (SessionStartEvent.swift:155)
 7   MyApp                             0x000000010468a580 @objc SessionStartEvent.transportBytes() + 28 (<compiler-generated>:0)
 8   MyApp                             0x00000001047762f4 -[GDTCOREvent setDataObject:] + 68 (GDTCOREvent.m:101)
 9   MyApp                             0x0000000104776184 -[GDTCOREvent copy] + 72 (GDTCOREvent.m:68)
 10  MyApp                             0x0000000104782cd4 -[GDTCORTransport sendEvent:onComplete:] + 44 (GDTCORTransport.m:89)
 11  MyApp                             0x0000000104685d90 GDTCORTransport.logGDTEvent(event:completion:) + 24 (GoogleDataTransport+GoogleDataTransportProtocol.swift:31)
 12  MyApp                             0x0000000104685d90 protocol witness for GoogleDataTransportProtocol.logGDTEvent(event:completion:) in conformance GDTCORTransport + 176 (<compiler-generated>:30)
 13  MyApp                             0x000000010468168c EventGDTLogger.logEvent(event:completion:) + 224 (EventGDTLogger.swift:52)
 14  MyApp                             0x0000000104681710 protocol witness for EventGDTLoggerProtocol.logEvent(event:completion:) in conformance EventGDTLogger + 20 (<compiler-generated>:0)
 15  MyApp                             0x00000001046884b0 closure #1 in SessionCoordinator.attemptLoggingSessionStart(event:callback:) + 176 (SessionCoordinator.swift:47)
 16  MyApp                             0x00000001046886b0 closure #1 in SessionCoordinator.fillInFIID(event:callback:) + 180 (SessionCoordinator.swift:0)
 17  MyApp                             0x000000010468613c closure #1 in FIRInstallations.installationID(completion:) + 32 (Installations+InstallationsProtocol.swift:0)
 18  MyApp                             0x000000010468613c partial apply for closure #1 in FIRInstallations.installationID(completion:) + 48 (<compiler-generated>:0)
 19  MyApp                             0x0000000104686000 thunk for @escaping @callee_guaranteed (@guaranteed String?, @guaranteed Error?) -> () + 96 (<compiler-generated>:0)
 20  MyApp                             0x000000010465d6dc __49-[FIRInstallations installationIDWithCompletion:]_block_invoke + 56 (FIRInstallations.m:201)
 21  MyApp                             0x0000000104613a70 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.18 + 52 (FBLPromise.m:273)
 22  libdispatch.dylib                 0x00000001a83986a8 _dispatch_call_block_and_release + 32 (init.c:1530)
 23  libdispatch.dylib                 0x00000001a839a300 _dispatch_client_callout + 20 (object.m:561)
 24  libdispatch.dylib                 0x00000001a83a89e0 _dispatch_main_queue_drain + 1056 (queue.c:7813)
 25  libdispatch.dylib                 0x00000001a83a85b0 _dispatch_main_queue_callback_4CF + 44 (queue.c:7973)
 26  CoreFoundation                    0x00000001a03d0f9c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1780)
 27  CoreFoundation                    0x00000001a03cdca8 __CFRunLoopRun + 1996 (CFRunLoop.c:3149)
 28  CoreFoundation                    0x00000001a03cd3f8 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
 29  GraphicsServices                  0x00000001e39834f8 GSEventRunModal + 164 (GSEvent.c:2196)
 30  UIKitCore                         0x00000001a27f38a0 -[UIApplication _run] + 888 (UIApplication.m:3685)
 31  UIKitCore                         0x00000001a27f2edc UIApplicationMain + 340 (UIApplication.m:5270)
 32  MyApp                             0x000000010413105c main + 64 (AppDelegate.swift:19)
 33  dyld                              0x0000000105f11dcc start + 2240 (dyldMain.cpp:1269)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment] 2024-03-04 16:20
Hi @Ausianovich, thanks for reporting. This is a duplicate of #12457. The fix is planned to be released today.

**Closed by ncooke3** 2024-03-04 16:20 UTC
Labels: needs-triage
