### ISSUE TITLE
Crash in FIRTrace sessions (Firebase SDK version 6.17.0)

### ISSUE THREAD

**Issue by Goodman333** [firebase/firebase-ios-sdk#5324] opened 2020-04-09 04:21 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: __11.3.1___
  * Firebase SDK version: __6.17.0___
  * Firebase Component: __Firebase/Analytics (6.17.0), Firebase/Core (6.17.0), Firebase/DynamicLinks (6.17.0), Firebase/Performance (6.17.0), FirebaseABTesting (3.1.2), FirebaseAnalytics (6.2.2), FirebaseAnalyticsInterop (1.5.0), FirebaseCore (6.6.2), FirebaseCoreDiagnostics (1.2.0), FirebaseCoreDiagnosticsInterop (1.2.0), FirebaseDynamicLinks (4.0.7), FirebaseInstallations (1.1.0), FirebaseInstanceID (4.3.1), FirebasePerformance (3.1.10), FirebaseRemoteConfig (4.4.7)___ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem
We encountered the same problem as https://github.com/firebase/firebase-ios-sdk/issues/4299 . iOS Version: 13.3.1, iPhone 11 Pro Max
```
Crashed: com.google.perf.sessionIds.trace
0  libobjc.A.dylib                0x1840c3230 objc_retain + 16
1  CoreFoundation                 0x184262c9c -[NSArray initWithArray:range:copyItems:] + 416
2  rohan                          0x100da0e40 __20-[FIRTrace sessions]_block_invoke + 4374498880
3  libdispatch.dylib              0x184035fd8 _dispatch_client_callout + 20
4  libdispatch.dylib              0x1840427f4 _dispatch_lane_barrier_sync_invoke_and_complete + 60
5  rohan                          0x100da0d90 -[FIRTrace sessions] + 4374498704
6  rohan                          0x100d8fc20 FPRGetTraceMetric + 4374428704
7  rohan                          0x100d8d6d0 __22-[FPRClient logTrace:]_block_invoke + 4374419152
8  libdispatch.dylib              0x184034b7c _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x184035fd8 _dispatch_client_callout + 20
10 libdispatch.dylib              0x18403c59c _dispatch_lane_serial_drain + 900
11 libdispatch.dylib              0x18403ce7c _dispatch_lane_invoke + 368
12 libdispatch.dylib              0x184045f20 _dispatch_workloop_worker_thread + 580
13 libsystem_pthread.dylib        0x18409b6d0 _pthread_wqthread + 280
14 libsystem_pthread.dylib        0x1840a19e8 start_wqthread + 8
```
[Crash.txt](https://github.com/firebase/firebase-ios-sdk/files/4454006/Crash.txt)

**Comment by ryanwilson** [comment] 2020-04-09 12:41
Hi @Goodman333 thanks for the report.

Have you been able to reproduce this at all? It's also worth noting there's a newer version of FirebasePerformance available (3.1.11) and it'd be helpful to know if this issue still happens there.

**Comment by paulb777** [comment] 2020-04-09 13:41
This looks like #4299 which we believe to be resolved by a February release.

**Comment by recurs1v0** [comment] 2020-04-09 15:18
I think I'm having the same issue here, my app is live, wasn't having any issues.

Buy wednesday shows up as Zero DAU and Zero events registered.

I can see the users on Streamview, but when I go into the detail view of a random user, it shows as if, they never triggered any event inside the app.

Which makes no sense because, A) User is showing up on Streamview and B) I have many events triggering since the app loaded.

**Comment by morganchen12** [comment] 2020-04-09 17:26
@recurs1v0, you seem to be describing a different issue than the parent. This issue is for a crash in Firebase Performance, not an Analytics issue.

You should file a support ticket at [Firebase Support](http://firebase.google.com/support). They'll be able to look at your project to see what's wrong with your data.

**Comment by recurs1v0** [comment] 2020-04-09 21:27
Sorry about that.

Thanks

**Comment by Goodman333** [comment] 2020-04-10 01:25
> Hi @Goodman333 thanks for the report.
> 
> Have you been able to reproduce this at all? It's also worth noting there's a newer version of FirebasePerformance available (3.1.11) and it'd be helpful to know if this issue still happens there.



> Hi @Goodman333 thanks for the report.
> 
> Have you been able to reproduce this at all? It's also worth noting there's a newer version of FirebasePerformance available (3.1.11) and it'd be helpful to know if this issue still happens there.

Thanks for your reply, we can not reproduce this crash, currently we are using Firebase version 6.21.0, did not encounter this crash

**Comment by Goodman333** [comment] 2020-04-10 01:27
> Hi @Goodman333 thanks for the report.
> 
> Have you been able to reproduce this at all? It's also worth noting there's a newer version of FirebasePerformance available (3.1.11) and it'd be helpful to know if this issue still happens there.

Thanks for your reply, we can not reproduce this crash, currently we are using Firebase version 6.21.0, did not encounter this crash

**Comment by Goodman333** [comment] 2020-04-10 01:30
> This looks like #4299 which we believe to be resolved by a February release.

I still encountered on 6.17.0, but we have upgraded to 6.21.0

**Closed** 2020-04-10 01:32 UTC
Labels: api: performance, needs-attention

**Comment by Goodman333** [comment] 2020-04-10 01:44
> This looks like #4299 which we believe to be resolved by a February release.

Can you tell me the specific version number, thank you

**Comment by paulb777** [comment] 2020-04-10 22:38
Firebase 6.17.0 and FirebasePerformance 3.1.10

**Comment by paulb777** [comment] 2020-04-10 22:39
FirebasePerformance is now at version 3.1.11
