### ISSUE TITLE
I have problems with connect Firebase to iOS project (iOS 17 version) / Xcode 15 beta 4

### ISSUE THREAD

**Issue by voffkal** [firebase/firebase-ios-sdk#11602] opened 2023-07-25 17:37 UTC
### Description

Got this error messages:

Null objc class data for '_OBJC_METACLASS_$_APMPrivateSetMembershipClient' in '/Users/user/Library/Developer/Xcode/DerivedData/FirebaseWork-cvikgamvhwsmfkcsfsmmlxgoksbz/Build/Products/Debug-iphonesimulator/GoogleAppMeasurementOnDeviceConversion.framework/GoogleAppMeasurementOnDeviceConversion[arm64][2](arm64_merged.o)'

Linker command failed with exit code 1 (use -v to see invocation)

### Reproducing the issue

In @main into struct _:App i place

 init() {
        FirebaseApp.configure()
        print("start")
    }

also i'm import Firebase

### Firebase SDK Version

10.12.0

### Xcode Version

15 beta 4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-07-25 17:43
This is a duplicate of #11516. See the discussion there.

**Closed by paulb777** 2023-07-25 17:43 UTC
Labels: needs-triage
