### ISSUE TITLE
The value during batch processing can not be taken.

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebase-ios-sdk#364] opened 2017-10-11 05:02 UTC
Hi. 
Thank you for a wonderful product. I found a problem with Firestore.

  * Xcode version: Xcode9
  * Firebase SDK version: 0.1.3
  * Firebase Component: Firestore
  * Component version: 0.8.0

```
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
```

```
Using BoringSSL (9.0)
Using Firebase (4.3.0)
Using FirebaseAnalytics (4.0.4)
Using FirebaseAuth (4.2.1)
Using FirebaseCore (4.0.8)
Using FirebaseFirestore (0.8.0)
Using FirebaseInstanceID (2.0.4)
Using FirebaseStorage (2.0.2)
Using GTMSessionFetcher (1.1.12)
Using GoogleToolboxForMac (2.1.3)
Using Protobuf (3.4.0)
Using gRPC (1.6.5)
Using gRPC-Core (1.6.5)
Using gRPC-ProtoRPC (1.6.5)
Using gRPC-RxLibrary (1.6.5)
Using leveldb-library (1.18.3)
Using nanopb (0.3.8)
```

#### Steps to reproduce:

The value during batch processing can not be taken.

``` swift
        do {
            let db = Firestore.firestore().collection("test1").document("id")
            db.setData(["test": FieldValue.serverTimestamp(), "key": "hoge"]) { (error) in
                db.getDocument(completion: { (snapshot, error) in
                    print("TEST 0", snapshot?.data()["test"])
                    (0..<5).forEach({ index in
                        let batch = db.firestore.batch()
                        batch.updateData(["test": FieldValue.serverTimestamp(), "key": "\(index)"], forDocument: db)
                        batch.commit(completion: { _ in
                        })
                    })
                    db.getDocument(completion: { (snapshot, error) in
                        print("TEST 1", snapshot?.data()["test"])
                    })
                    DispatchQueue.main.asyncAfter(deadline: .now() + 4, execute: {
                        db.getDocument(completion: { (snapshot, error) in
                            print("TEST 2", snapshot?.data()["test"])
                        })
                    })
                })
            }
        }
```

## RESULT
``` 
TEST 0 Optional(2017-10-11 05:01:03 +0000)
TEST 1 Optional(<null>)
TEST 2 Optional(2017-10-11 05:01:05 +0000)
```

**Comment by wilhuff** [comment] 2017-10-11 15:52
Thanks for this submission, I've been able to reproduce your output and I'm digging into the root cause.

**Comment by wilhuff** [comment] 2017-10-11 17:50
I'm sorry to report that this is working as designed, though our design didn't account for this case particularly well and we're considering how to adjust for it.

The root of the issue is our notion of "latency compensation". When you perform a write locally we show the result of what we believe the result of that write will be before the server has committed it and confirmed what the value actually will be.

For example, if you had also included the key in the output (`snapshot?.data()["key"]`) the output would look like this:

```
TEST 0 Optional(hoge) Optional(2017-10-11 17:47:32 +0000)
TEST 1 Optional(4) Optional(<null>)
TEST 2 Optional(4) Optional(2017-10-11 17:47:43 +0000)
```

Server timestamps are special: unlike writes of fields like `"key": "4"` we don't actually know what time the server will give us until the server actually gives us the result back. The client doesn't actually estimate this value; internally we keep a counter so that if you wrote a collection and sorted by time they would sort correctly but when you actually ask for the value it substitutes a `nil`.

The trouble in this case is that you're waiting for the value to fixate by waiting for the completion of `setData` and then immediately turning around and writing a new value and not waiting for it to fixate.

This means that at the point where `TEST 1` happens you're getting the latency compensated view which for server timestamps is always `nil` even though there was a previous value we could be showing.

The take-away here is that until the clients know the value of a server timestamp they will show `nil`. Other values within the snapshot will be populated. For now a work-around is to display the current local time if the timestamp is `nil`.

It's possible that a straight-forward change to this is possible but it will miss the release window so you'll have to work around this for at least the next few weeks.

**Comment by 1amageek** [comment] 2017-10-12 02:53
Does Server timestamps issue also occur among multiple devices?

For example, when DeviceA is updating Server timestamps, will DeviceB also get `nil`?
Or will it only occur locally?

**Comment by wilhuff** [comment] 2017-10-12 15:54
No, only the client writing the server timestamp will see a `nil` value. 

The `nil` value only happens while the value of the server timestamp is unknown. The process of sharing the value with another client goes like this:

  * Device A writes a `FieldValue.serverTimestamp`; if it observes it the value will be `nil`
  * Device A commits to the server
  * The server populates the timestamp
  * The server replicates to any listening devices including Device B
  * Device B observes the actual server timestamp, not `nil`

**Comment by 1amageek** [comment] 2017-10-12 15:55
Thanks!

**Comment by morganchen12** [comment] 2018-01-26 20:18
This behavior is improved with the latest version of Firestore (0.10.0), which allows clients to specifically ask for server timestamp estimates from the client before they can be synced from the server.

Take a look at the sample [here](https://github.com/firebase/snippets-ios/commit/6fb2d2e8713914cdae7b3719d468cfb2d9992bd3#diff-ac81ab115caf45e3d791eff7331d00bfR399) for example usage and more details.

**Closed by morganchen12** 2018-01-26 20:18 UTC
Labels: Firestore

**Comment by 1amageek** [comment] 2018-01-27 00:07
Thank you very much
I am grateful for your work.
🎉
