### ISSUE TITLE
Dynamic Links don't survive app install on iOS 16.1

### ISSUE THREAD

**Issue by MEHTAMAYUR** [firebase/firebase-ios-sdk#10416] opened 2022-10-28 07:10 UTC
### Description

Firebase SDK version: 8.10.0
Firebase Component: Dynamic Links

One of user is using iOS 16.1 after fresh install 
App Link is not surviving, 

TIme : 
2022-10-25 06:31:28 +0000 
64ED186D-50BF-45A4-AB06-AA9E6FA87995

URL:com.fab.PersonalBanking://google/link/?request_ip_version=IP%5FV6&match_message=No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E

Device iOS 16.1
Model Iphone 12 pro Max

### Reproducing the issue

-User is tapping long dynamic Link,

-Click on Firebase Long Dynamic Links
-Browser redirect to app store
-Install from app store
-Open the app
-Dynamic link received : No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E

This issue also we have reproduced in user's phone  by downloading Test flight build.

For another user we have reproduced issue by changing safari browser language.

### Firebase SDK Version

8.10

### Xcode Version

13.1

Code snippet after fresh installation : 

       func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool { 
       
         //After downloading app from App store deeplink check
          if let dynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url){
            
            
            
            guard let deepLinkURL = dynamicLink.url  else {
                            return false
                        }

.......

### Installation Method

CocoaPods

### Firebase Product(s)

DynamicLinks

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2022-11-02 18:06
Thanks for reporting, @MEHTAMAYUR. Is the issue only happening on iOS 16.1 devices? Is it also reproducible using the latest SDK version?

**Comment by DellaBitta** [comment] 2022-11-09 21:08
This seems to be a similar issue to one reported in the [Firebase Unity SDK running on iOS](https://github.com/firebase/firebase-unity-sdk/issues/495). The user reported that this occurs on iOS 16.

The Firebase Unity SDK wraps the Firebase iOS SDK for its implementation so that information should be relevant here.

**Comment by MEHTAMAYUR** [comment] 2022-11-10 18:11
This issue has occurred on Firebase SDK Version
8.10

**Comment by MEHTAMAYUR** [comment] 2022-11-11 20:32
@rizafran  It is working fine 0n latest firebase SDK 10.0.0 , Could you give any info why it was not working in 8.10.0 and now it is working on 10.0.0

**Comment by rizafran** [comment] 2022-11-14 13:26
Thanks for the update, @MEHTAMAYUR. It's possible that there are changes including bug fixes and new features to the latest SDK version since [8.10.0](https://firebase.google.com/support/release-notes/ios#version_8100_-_december_1_2021) was released almost a year ago. With this, we always suggest developers to update SDK versions to the latest one. 

I'll be closing this issue for now, but feel free to comment if the issue persists.

**Closed by rizafran** 2022-11-14 13:26 UTC
Labels: api: dynamiclinks, needs-attention
