### ISSUE TITLE
cant archive firebase/Analytics  on xcode 12 

### ISSUE THREAD

**Issue by mennyAlterscu** [firebase/firebase-ios-sdk#7218] opened 2020-12-27 16:07 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _12.3____
  * Firebase SDK version: _7.3.0____
  * Installation method: `CocoaPods'
  * Firebase Component: Analytics

#### Steps to reproduce:
cant archive the app when Analytics installed
it was issue sine xcode 12 update
i try to update pod
remove pods
archive with xcode 11.3
and same error happen

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
![WhatsApp Image 2020-12-27 at 16 13 53](https://user-images.githubusercontent.com/47102988/103174846-1b816780-486e-11eb-885c-fb8a0024751d.jpeg)

**Comment by mennyAlterscu** [comment] 2020-12-27 16:19
cant archive the app when Analytics installed
it was issue sine xcode 12 update
i try to update pod
remove pods
archive with xcode 11.3
and same error happen

**Comment by paulb777** [comment] 2020-12-27 22:23
This looks like a duplicate of #6339. Please see the discussion there.

**Comment by mennyAlterscu** [comment] 2020-12-28 09:44
Hi
I try to add this to my podfile

def google_utilites
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/Environment'
  pod 'GoogleUtilities/ISASwizzler'
  pod 'GoogleUtilities/Logger'
  pod 'GoogleUtilities/MethodSwizzler'
  pod 'GoogleUtilities/NSData+zlib'
  pod 'GoogleUtilities/Network'
  pod 'GoogleUtilities/Reachability'
  pod 'GoogleUtilities/UserDefaults'
end


and the error remain when archive the project
 I can’t find any solution that work for me and its delaying my deployment because the analtics
when I removed analytics the error disappear


Here the pod ifle now :


platform :ios, '11.0'
ENV['SWIFT_VERSION'] = '5.0'
use_frameworks!

#target 'Telenet Mobile Security' do
#    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#    use_frameworks!
#    pod 'Fabric'
#    pod 'Crashlytics'
#
#end
workspace 'Telenet Mobile Security'

# https://github.com/firebase/firebase-ios-sdk/issues/6339
# Should be referenced for anything below that transitively uses GoogleUtilities
def google_utilites
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/Environment'
  pod 'GoogleUtilities/ISASwizzler'
  pod 'GoogleUtilities/Logger'
  pod 'GoogleUtilities/MethodSwizzler'
  pod 'GoogleUtilities/NSData+zlib'
  pod 'GoogleUtilities/Network'
  pod 'GoogleUtilities/Reachability'
  pod 'GoogleUtilities/UserDefaults'
end


def analitics_pod
  google_utilites
  pod 'Firebase/Crashlytics'
  # Recommended: Add the Firebase pod for Google Analytics
 pod 'Firebase/Analytics'
end

target 'EP sam' do
  use_frameworks!
  pod 'Reusable'
  analitics_pod
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Messaging'

end

target 'VPN sam' do
  use_frameworks!
end

target 'KidSDK_Vpn' do
  use_frameworks!
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Crashlytics'
end

target 'Telenet_KID_VPN' do
  use_frameworks!
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Crashlytics'
end



target 'Safespot guard' do
  use_frameworks!
  pod 'Reusable'
  analitics_pod
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Messaging'

end

target 'Safespot guard VPN' do
  use_frameworks!
end


target 'SamEPSDK' do
  project 'Sam-EPSDK-iOS/SamEPSDK.xcodeproj'
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
             config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end



and here the pod file before



platform :ios, '11.0'
ENV['SWIFT_VERSION'] = '5.0'
use_frameworks!

#target 'Telenet Mobile Security' do
#    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#    use_frameworks!
#    pod 'Fabric'
#    pod 'Crashlytics'
#
#end
workspace 'Telenet Mobile Security'

def analitics_pod
  pod 'Firebase/Crashlytics'
  # Recommended: Add the Firebase pod for Google Analytics
 pod 'Firebase/Analytics'
end

target 'EP sam' do
  use_frameworks!
  pod 'Reusable'
  analitics_pod
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Messaging'

end

target 'VPN sam' do
  use_frameworks!
end

target 'KidSDK_Vpn' do
  use_frameworks!
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Crashlytics'
end

target 'Telenet_KID_VPN' do
  use_frameworks!
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Crashlytics'
end



target 'Safespot guard' do
  use_frameworks!
  pod 'Reusable'
  analitics_pod
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'Firebase/Messaging'

end

target 'Safespot guard VPN' do
  use_frameworks!
end


target 'SamEPSDK' do
  project 'Sam-EPSDK-iOS/SamEPSDK.xcodeproj'
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
             config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end

**Comment by paulb777** [comment] 2020-12-28 15:42
The GoogleUtilities subspecs need to be added to all the targets include Firebase. 

The problem is exposed by requiring different subspec subsets in different targets.

**Closed** 2021-01-11 02:03 UTC
Labels: needs-info, no-recent-activity, type: question
