### ISSUE TITLE
Firestore moving document offline (by creating new document and removal the old one in completion block)

### ISSUE THREAD

**Issue by DJ-Glock** [firebase/firebase-ios-sdk#4571] opened 2020-01-02 11:07 UTC
I have the following documents and collections structure of my firestore database for iOS application:

```
-ActiveSession (Application allows user to have only one active session in the collection):
--Session
-ArchivedSessions (collection that contains archived (closed) sessions):
--Session 1
--Session 2
--...
--Session N
```
When session is being closed, application sets `CloseTime` parameter, copies document to `ArhivedSessions` collection and removes original document from `ActiveSession` collection.

I implemented this structure to avoid potential issues with performance - it always easier to get the only one document from a collection instead of looking for one document with `CloseTime` is null in the collection with tons of documents.

When my application is online - described logic works with no issues. But when I'm trying to do the same in offline mode (it's enabled explicitly in my code), it does not work properly.

Expected result:
In offline mode application moves active session document to archive (copy and remove). After removal from `ActiveSessions` collection, it becomes unavailable and accessible only in `ArchivedSessions` collection. UI is being updated respectively and application allows user to add another new active session.
After enabling online mode - all changes are pushed to the Firestore Cloud and it gets all documents in incremental order: old session becomes closed in `ArchivedSessions`, new active session - in `ActiveSession`.

Actual result:
In offline mode application 'moves' active session document. But actually it's still available in `ActiveSession` collection so UI is not able to show changes and hence not able to allow user to add new session (because old one is displayed as active).

Please note than I use `addSnapshotListener` to get the data from Cloud and watch for updates.
I checked StackOverflow, Firebase documents and found nothing about documents removal in a local cache in offline mode. The only thing I found is a one mention somewhere on the github that `addSnapshotListeners`'s callback is being called only when sync is finished (id est only in online mode).

**Update:**
It looks like the issue is somewhere in `setData(<#T##documentData: [String : Any]##[String : Any]#>, completion: <#T##((Error?) -> Void)?##((Error?) -> Void)?##(Error?) -> Void#>)` method. It's completion code is not getting called while application is offline (disableNetwork). It is only getting called after network is restored (enableNetwork).

I did not create any new sample project, but I believe that the following bad and good examples can easily reproduce a problem.

Good example:
```
class func goodExample () {
        let documentReference = Firestore.firestore()
            .collection("SomeCollection")
            .document("SomeDocumentID")
        
        documentReference.getDocument { (document, error) in
            if let document = document {
                let data = document.data()
                let newDocument = userData
                    .collection("AnotherCollection")
                    .document()
                
                newDocument.setData(data!)
                // Call of the function that removes the initial document. Is being called after setData execution is finished.
                // removeOldDocument()
            }
        }
    }
```

Bad example:
```
class func badExample () {
        let documentReference = Firestore.firestore()
            .collection("SomeCollection")
            .document("SomeDocumentID")
        
        documentReference.getDocument { (document, error) in
            if let document = document {
                let data = document.data()
                let newDocument = userData
                    .collection("AnotherCollection")
                    .document()
                
                newDocument.setData(data!) { error in
                    // This block of code is NOT being called while application is offline.
                    // Once you enableNetwork - it will be called. So here is the issue.
                    if let error = error {
                        print("Failed to create new document due to \(error)")
                        return
                    } else {
                        // Call of the function that removes the initial document
                        // removeOldDocument()
                    }
                }
            }
        }
    }
```

**Comment by Warfalamei** [comment] 2020-01-02 18:24
Thanks! I have two iPhone! I love honest Fox very much ! But the connections, they didn't happen from me! At this point, I am in Russia

2 янв. 2020 г., в 14:07, Google Open Source Bot <notifications@github.com> написал(а):

I found a few problems with this issue:

I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
This issue does not seem to follow the issue template. Make sure you provide all the required information.

**Comment by wu-hui** [comment] 2020-01-08 20:22
Hi DJ-Glock,

From your description, it seems like you are saying when offline (`disableNetwork`), your snapshot listener does not get notified when your document is removed?

I just tried myself, and the snapshot listener does get notified. Note that your snapshot listener should give you an array of `FIRDocumentChange` via `FIRQuerySnapshot.getDocumentChanges`. The way to know that a document is removed is by checking if `FIRDocumentChange.type` is `FIRDocumentChangeTypeRemoved`.

Can you please tell me if you don't see any notification to your snapshot listener, or you see some notification, but it does not indicate the document is removed?

If so, I'd be interested to see a minimum reproduction, my reproduction simply does not work.

Thanks

**Comment by DJ-Glock** [comment] 2020-01-09 21:25
Hello @wu-hui 
Thanks a lot for your attention! I have created a separate simple sample project based on mine application. I put it to the following repo: https://github.com/DJ-Glock/firebase-sample

Please use the following credentials to log into the app (e-mail auth):
e-mail: test@example.com
password: test123
Please note that my app is still under development and provided project has a bug: once you logged in first time, application will crash. So you'll have to re-launch it and it will run fine.
It's better to launch this sample app on a clean simulator to avoid any potential issues with authentication.

And by the way I have found that you are right - simple document removal works as expected in the online and offline modes. But my issue can be reproduced when moving a document by creating a new document in another collection and removing the old one from the initial collection. If I am not mistaken - snapshot listener does not get notified about document removal. I suspect that it could be related to callbacks chain (completion closures).

When you run the app and log in, you will see three labels and several buttons.
Please do the following to reproduce the issue:
1. Click the `Create session` button - it will create a document in the collection `/UserData/
pTk5xGrvg8bUmzFeQsu1qShOYFB3/Tables/cDrSF0fJJlXVP5QWY3RF/ActiveSession/`
2. Click the `Move session to archive` button - it will create a document in the collection `/UserData/pTk5xGrvg8bUmzFeQsu1qShOYFB3/Tables/cDrSF0fJJlXVP5QWY3RF/ArchivedSessions/` and will remove active session document created on the first step.
3. Click `Disable network` button - it will call firestore.disableNetwork function.
4. Repeat steps 1-2 and you will see that UI is not being updated after moving document.
5. Click `Enable network` button - it will call firestore.enableNetwork function. Once network is enabled, you will see that document will be removed and UI will be updated.

If you need an access to firebase console - please ping me, I'll grant an access to your email.
If you face any issues with this sample project - I'll be happy to help.

**Comment by wu-hui** [comment] 2020-01-10 16:16
Hi DJ-Glock,

I played with your sample a bit, UI does not change no matter how I try it, with network enabled or disabled.

Moreover, if the simple document removal shows up in your snapshot listener in simple cases, it should show up in other cases too. A good way to find out what is wrong is to start from the simple case, and program towards your current implementation in steps, and verify in each step that things worked. 

It is nice of you to provide a sample, however, I'd appreciate a minimal reproduction. The sample in its current form is hardly minimal and cannot reproduce the issue. If you take my suggestion and start from simple, and yet you still stuck at some steps where you believe it's an issue with the SDK, I am happy to look into it again!

Thanks.

**Comment by DJ-Glock** [comment] 2020-01-11 13:04
@wu-hui I'm sad that my sample was not usefu. But I followed your advice and got some results :)

It looks like the issue is somewhere in `setData(<#T##documentData: [String : Any]##[String : Any]#>, completion: <#T##((Error?) -> Void)?##((Error?) -> Void)?##(Error?) -> Void#>)` method. It's completion code is not getting called while application is offline (disableNetwork). It is only getting called after network is restored (enableNetwork).

I did not create any new sample project, but I believe that the following bad and good examples can easily reproduce a problem.

Good example:
```
class func goodExample () {
        let documentReference = Firestore.firestore()
            .collection("SomeCollection")
            .document("SomeDocumentID")
        
        documentReference.getDocument { (document, error) in
            if let document = document {
                let data = document.data()
                let newDocument = userData
                    .collection("AnotherCollection")
                    .document()
                
                newDocument.setData(data!)
                // Call of the function that removes the initial document. Is being called after setData execution is finished.
                // removeOldDocument()
            }
        }
    }
```

Bad example:
```
class func badExample () {
        let documentReference = Firestore.firestore()
            .collection("SomeCollection")
            .document("SomeDocumentID")
        
        documentReference.getDocument { (document, error) in
            if let document = document {
                let data = document.data()
                let newDocument = userData
                    .collection("AnotherCollection")
                    .document()
                
                newDocument.setData(data!) { error in
                    // This block of code is NOT being called while application is offline.
                    // Once you enableNetwork - it will be called. So here is the issue.
                    if let error = error {
                        print("Failed to create new document due to \(error)")
                        return
                    } else {
                        // Call of the function that removes the initial document
                        // removeOldDocument()
                    }
                }
            }
        }
    }
```

I've updated my initial message accordingly.

**Comment by wu-hui** [comment] 2020-01-13 15:20
Hi @DJ-Glock,

I see what happened now. Yes, the completion on `setData` is only called when the data is written to *the backend*, and if network is disabled, it will not get called at all. See the documentation: https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/DocumentReference#/c:objc(cs)FIRDocumentReference(im)setData:completion:

The fact that `setData` returned without exception tells you that you data is written locally, in your case, simple remove the old doc after that will do the trick, as you already did in your good example.

I am closing the issue for now, let me know if you have further questions.

**Closed by wu-hui** 2020-01-13 15:20 UTC
Labels: api: firestore, needs-attention
