### ISSUE TITLE
Cannot `getStoredUser` from keychain in watchOS

### ISSUE THREAD

**Issue by ivopintodasilva** [firebase/firebase-ios-sdk#9525] opened 2022-03-28 13:44 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.15.0 (commit b4dd98da69fca029123788e69e14d612ef44e0d1)
  * Installation method: `Swift Package Manager`
  * Firebase Component: Auth
  * Target platform(s): `iOS | watchOS`

### [REQUIRED] Step 2: Describe the problem

I'm having trouble sharing an authenticated user between an iOS and a watchOS app.

By creating a watchOS app for an iOS app, I expect to be able to share authentication between both - so, to sign a user in through the iOS app and be able to use it in the watchOS app.

I've tried two approaches:

**1.** Using the same `GoogleService-Info.plist` for both iOS and watchOS. This causes a warning because the bundle ID of the watch app doesn't match the one of the iOS app. 
In this example, the bundle ID for my watch app was `*app-bundle-id*.watchkitapp` and `*app-bundle-id*.watchkitapp.watchkitextension` for the watch extension.
I thought this approach would work, since it's the same one I've successfully used previously with widgets, but no luck...

**2.** Using a separate `GoogleService-Info.plist` for the watchOS app. The bundle ID warning now disappears and the setup is successful.
However, when trying to call `getStoredUser` in the watch app (after logging in on the iOS app), the user returned is always `nil`.

Additionally, on both configurations I've setup Keychain sharing capabilities for both apps and am calling `Auth.auth().useUserAccessGroup(...)` after `FirebaseApp.configure()`. 

Here's a link to a sample project configured as described in [approach #2](https://github.com/ivopintodasilva/firebase-apple-watch-shared-auth-test).

Am I doing something wrong in terms of configuration?

Cheers!

**Comment by paulb777** [comment] 2022-04-30 14:52
This may be related to #7854

**Comment by charlotteliang** [comment] 2022-11-30 19:49
This is a duplicate of #7854. 

[App group doesn't support data sharing between watch and phone right now](https://developer.apple.com/forums/thread/3927?page=2). It would be great for @ivopintodasilva to file a feature request or upvote one already exists which helps us prioritize.

**Closed by charlotteliang** 2022-11-30 19:49 UTC
Labels: api: auth, watchOS
