### ISSUE TITLE
ld: framework not found GRPCClient

### ISSUE THREAD

**Issue by petard** [firebase/firebase-ios-sdk#3937] opened 2019-09-27 10:47 UTC
* Xcode version: 11.0
  * Firebase SDK version: 6.9.0
  * Firebase Component: Core, Messaging, Analytics
  * Component version: 6.3.0, 4.1.5, 6.1.2

### [REQUIRED] Step 3: Describe the problem

My project fails to build after adding Firebase. I've updated to Cocoapods 1.8.0, cleaned XCode's derived folder, cleaned Cocoapods cache and reinstalled Pod from scratch via `pod deintegrate, pod install` without luck.

#### Steps to reproduce:

1. Add Firebase dependencies to Podfile:

```
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
```

2. Build project in XCode, get `ld: framework not found GRPCClient` error. Build fails.
3. Remove Firebase dependencies from Podfile
4. Build in XCode, build compiles without error.

#### Relevant Code:

My `Podfile`

```Podfile
pod 'SnapKit'
pod 'SquareMosaicLayout'
pod 'SDWebImage'


pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

#fix SnapKit in NotificationBanner
pod 'NotificationBannerSwift', :git => 'https://github.com/Arcovv/NotificationBanner.git', :branch => 'master'

pod 'Hero'
pod 'UIImageColors'
```

**Comment by ryanwilson** [comment] 2019-09-27 15:07
Hi @petard - thanks for the report. I'm not able to reproduce this issue. 

I created a new Xcode project using Xcode 11, ran `pod init` and copied the contents of your `Podfile`, imported each framework for good measure, but still built successfully.

Can you run `pod update` instead of `pod install` to see if you're on the latest version of frameworks? Your `Podfile.lock` would be helpful as well to see if it's somehow getting incorrect versions (I saw you posted the component versions though, and those seem correct).

Thanks, hopefully we can get this resolved for you shortly.

**Comment by paulb777** [comment] 2019-09-27 15:14
Would be interesting to track down where the GRPCClient dependency is coming from in the Xcode workspace. Only Firestore in Firebase needs it and it doesn't look like that is in the Podfile.

**Comment by petard** [comment] 2019-09-27 15:37
Thanks so much for your help, @paulb777  and @ryanwilson. I've deleted the lock file and ran `pod update`:

```
pdating local specs repositories
Analyzing dependencies
Pre-downloading: `NotificationBannerSwift` from `https://github.com/Arcovv/NotificationBanner.git`, branch `master`
Downloading dependencies
Installing Firebase (6.9.0)
Installing FirebaseAnalytics (6.1.2)
Installing FirebaseAnalyticsInterop (1.4.0)
Installing FirebaseCore (6.3.0)
Installing FirebaseCoreDiagnostics (1.1.0)
Installing FirebaseCoreDiagnosticsInterop (1.0.0)
Installing FirebaseInstanceID (4.2.5)
Installing FirebaseMessaging (4.1.5)
Installing GoogleAppMeasurement (6.1.2)
Installing GoogleDataTransport (2.0.0)
Installing GoogleDataTransportCCTSupport (1.1.0)
Installing GoogleUtilities (6.3.0)
Installing NotificationBannerSwift 1.8.1
Installing Protobuf (3.9.2)
Installing SDWebImage 5.2.0 (was 5.1.1 and source changed to `https://cdn.cocoapods.org/` from `https://github.com/CocoaPods/Specs.git`)
Installing nanopb (0.3.901)
Generating Pods project
Integrating client project
Pod installation complete! There are 8 dependencies from the Podfile and 21 total pods installed.
```

I wasn't aware that there isn't a dependency to GRPCClient from Firebase. I had installed previously the swift client for Google Cloud Voice which depends on it. I need to dig deeper to find the place where this is might be referenced. I thought resetting all pods, clearing caches and deleting the `Podfile`, `Podfile.lock` and the Pods folder in my project would be enough.

**Comment by paulb777** [comment] 2019-09-27 20:55
Closing since this is almost certainly not a Firebase issue. We can continue the conversation here though if you like.

**Closed by paulb777** 2019-09-27 20:55 UTC
Labels: api: core
