### ISSUE TITLE
"Framework 'CrashReporter' not found" in app extension when trying to export localizations in Xcode 15

### ISSUE THREAD

**Issue by xinatanil** [firebase/firebase-ios-sdk#11896] opened 2023-10-05 07:42 UTC
### Description

I converted my project to use new Xcode Strings Catalog, and when I'm trying to use export localizations, it fails with an error "Framework 'CrashReporter' not found" in my app extension target. Any idea why does that happen and how can I fix it?
Note, that the app itself builds and runs just fine.

### Reproducing the issue

1. Use Xcode 15 Strings Catalog.
2. Press Product -> Export Localizations -> YOUR_TARGET

### Firebase SDK Version

9.3.0

### Xcode Version

15.0

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Firebase/Analytics (9.3.0):
    - Firebase/Core
  - Firebase/Core (9.3.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 9.3.0)
  - Firebase/CoreOnly (9.3.0):
    - FirebaseCore (= 9.3.0)
  - Firebase/Crashlytics (9.3.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 9.3.0)
  - FirebaseABTesting (9.6.0):
    - FirebaseCore (~> 9.0)
  - FirebaseAnalytics (9.3.0):
    - FirebaseAnalytics/AdIdSupport (= 9.3.0)
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (9.3.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleAppMeasurement (= 9.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (9.3.0):
    - FirebaseCoreDiagnostics (~> 9.0)
    - FirebaseCoreInternal (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (9.3.0):
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCoreInternal (9.3.0):
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
  - FirebaseCrashlytics (9.3.0):
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleDataTransport (< 10.0.0, >= 9.1.4)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInAppMessaging (9.6.0-beta):
    - FirebaseABTesting (~> 9.0)
    - FirebaseCore (~> 9.0)
    - FirebaseInstallations (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseInstallations (9.6.0):
    - FirebaseCore (~> 9.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (~> 2.1)
  - FloatingPanel (2.5.4)
  - Flurry-iOS-SDK/CrashReporter (12.1.1)
  - Flurry-iOS-SDK/FlurrySDK (12.1.1):
    - Flurry-iOS-SDK/CrashReporter
  - GoogleAppMeasurement (9.3.0):
    - GoogleAppMeasurement/AdIdSupport (= 9.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (9.3.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 9.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (9.3.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/MethodSwizzler (~> 7.7)
    - GoogleUtilities/Network (~> 7.7)
    - "GoogleUtilities/NSData+zlib (~> 7.7)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleDataTransport (9.2.0):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.7.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.7.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.7.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.7.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.7.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.7.0)"
  - GoogleUtilities/Reachability (7.7.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.7.0):
    - GoogleUtilities/Logger
  - Hero (1.6.1)
  - KTCenterFlowLayout (1.3.1)
  - LGSideMenuController (3.1.2)
  - Localize-Swift (3.2.0):
    - Localize-Swift/LocalizeSwiftCore (= 3.2.0)
    - Localize-Swift/UIKit (= 3.2.0)
  - Localize-Swift/LocalizeSwiftCore (3.2.0)
  - Localize-Swift/UIKit (3.2.0):
    - Localize-Swift/LocalizeSwiftCore
  - Mantis (2.14.1)
  - MerchantKit (0.14.0)
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - Pageboy (3.6.2)
  - PromisesObjC (2.1.1)
  - TinyConstraints (4.0.1)
  - TTTAttributedLabel (2.0.0)
  - UICircularProgressRing (6.5.0)

DEPENDENCIES:
  - Firebase/Analytics
  - Firebase/Crashlytics
  - FirebaseInAppMessaging (= 9.6.0-beta)
  - FloatingPanel (= 2.5.4)
  - Flurry-iOS-SDK/FlurrySDK
  - Hero (= 1.6.1)
  - KTCenterFlowLayout (= 1.3.1)
  - LGSideMenuController (= 3.1.2)
  - Localize-Swift (= 3.2.0)
  - Mantis (from `https://github.com/xinatanil/Mantis.git`)
  - MerchantKit (= 0.14.0)
  - Pageboy (= 3.6.2)
  - TinyConstraints (= 4.0.1)
  - TTTAttributedLabel (= 2.0.0)
  - UICircularProgressRing (= 6.5.0)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInAppMessaging
    - FirebaseInstallations
    - FloatingPanel
    - Flurry-iOS-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - Hero
    - KTCenterFlowLayout
    - LGSideMenuController
    - Localize-Swift
    - MerchantKit
    - nanopb
    - Pageboy
    - PromisesObjC
    - TinyConstraints
    - TTTAttributedLabel
    - UICircularProgressRing

EXTERNAL SOURCES:
  Mantis:
    :git: https://github.com/xinatanil/Mantis.git

CHECKOUT OPTIONS:
  Mantis:
    :commit: 175f01bc66beef806670971360fb7880dc100914
    :git: https://github.com/xinatanil/Mantis.git

SPEC CHECKSUMS:
  Firebase: ef75abb1cdbc746d5a38f4e26c422c807b189b8c
  FirebaseABTesting: 61826730ce9eee8781ba99a2b3420e9bce148dc9
  FirebaseAnalytics: bf46f5163f44097ce2c789de0b3e6f87f1da834a
  FirebaseCore: c088995ece701a021a48a1348ea0174877de2a6a
  FirebaseCoreDiagnostics: 060eb57cc56dfaf40b1b1b5874a5c17c41ce79f8
  FirebaseCoreInternal: 635d1c9a612a6502b6377a0c92af83758076ffff
  FirebaseCrashlytics: 65a5b349e664e986e6c7486b0a9b5ed8c11d0491
  FirebaseInAppMessaging: 64f19fde7c3010c170af2c8c629bdb484a4ba642
  FirebaseInstallations: 0a115432c4e223c5ab20b0dbbe4cbefa793a0e8e
  FloatingPanel: 387377aa46a9b088e5f8f5f2a8d2c00c61e67298
  Flurry-iOS-SDK: 2ae2391515ae3248a63e95a397c1b393ae52b3a9
  GoogleAppMeasurement: b907bdad775b6975a8108762345b2cfbf1a93c37
  GoogleDataTransport: 1c8145da7117bd68bbbed00cf304edb6a24de00f
  GoogleUtilities: e0913149f6b0625b553d70dae12b49fc62914fd1
  Hero: 215865ba3ae41dd9bb08cd6c60a645529c6fc94b
  KTCenterFlowLayout: 6e02b50ab2bd865025ae82fe266ed13b6d9eaf97
  LGSideMenuController: 0c7b155b0dbdf14bf8b88d5ac363c5fe1584bb23
  Localize-Swift: 6f4475136bdb0d7b2882ea3d4ea919d70142b232
  Mantis: b91a7fb2b16c180c77a76bc83bb126abba105cd5
  MerchantKit: 6dfed9a012cada65744494192867d4fc2edb0e43
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  Pageboy: cf121b9dd48c63f3f281b2a9ec93d02e0f23879b
  PromisesObjC: ab77feca74fa2823e7af4249b8326368e61014cb
  TinyConstraints: 8dd91295e56797648c7bc335dd20e1d91ec4c192
  TTTAttributedLabel: 8cffe8e127e4e82ff3af1e5386d4cd0ad000b656
  UICircularProgressRing: e6852e8f88e296cbbbe2720cccb55241acda6708

PODFILE CHECKSUM: 99a9e1cead965f113c7808ec15eadad2d48181b1

COCOAPODS: 1.13.0

**Comment by paulb777** [comment] 2023-10-05 14:02
`CrashReporter` is not a Firebase symbol. 

A Google search shows https://github.com/bitstadium/HockeySDK-iOS/issues/177. 

I'll close this issue and feel free to reopen if you isolate the cause to Firebase.

**Closed by paulb777** 2023-10-05 14:02 UTC
Labels: type: question, Xcode 15 - iOS 17
