### ISSUE TITLE
'com.firebase.installations', reason: 'FirebaseInstallations will not work correctly with current version of Firebase Instance ID

### ISSUE THREAD

**Issue by Saranjithpk** [firebase/firebase-ios-sdk#5261] opened 2020-04-02 14:21 UTC
Source code was working perfectly, Suddently below issue comes for some of collaborates of project in XCode 11.2.1

'com.firebase.installations', reason: 'FirebaseInstallations will not work correctly with current version of Firebase Instance ID. Please update your Firebase Instance ID version.'

**Comment by paulb777** [comment] 2020-04-02 14:27
This looks like a duplicate of #5213.  See the discussion there.

**Comment by JasonSa1993** [comment] 2020-04-14 19:24
Steps to fix:

1- pod deintegrate

2- pod cache clean --all

3- in Podfile put pod 'Firebase' without specifying any version, and for you to install the latest 6.22.0

4- pod install

5- When compiling the application, a FirebaseInstanceID error will appear

6- Open Podfile and specify pod 'FirebaseInstallations', '1.1.0'

7- pod install

8- re compile and run the project

Hope it helps

**Comment by paulb777** [comment] 2020-04-14 20:22
Going to close in favor of #5213. Please continue conversation there.

**Closed by paulb777** 2020-04-14 20:22 UTC
Labels: api: installations, needs-info
