### ISSUE TITLE
Xcode 13 Beta 5 warning about NSKeyedUnarchiver validateAllowedClass

### ISSUE THREAD

**Issue by jorydekort** [firebase/firebase-ios-sdk#8636] opened 2021-09-09 07:53 UTC
### My environment

  * Xcode version: Xcode 13 beta 5
  * Firebase SDK version: 8.7.0
  * Installation method: CocoaPods
  * Firebase Component: Core, CoreDiagnostics, Crashlytics,

### The problem

Run a project with FirebaseCrashlytics embedded. Warning will show on launch:

```
    "'NSDictionary' (0x7ff84b43fa60) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.
2021-09-09 09:45:03.052203+0200 ******[7997:216371] [general] *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x7ff84b469a00) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.keys', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x7ff84b43fa60) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.
2021-09-09 09:45:03.052291+0200 ******[7997:216371] [general] *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x7ff84b469a00) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.keys', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x7ff84b43fa60) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.
2021-09-09 09:45:03.052426+0200 ******[7997:216371] [general] *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x7ff84b469a00) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.objects', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x7ff84b43fa60) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.
2021-09-09 09:45:03.052539+0200 ******[7997:216371] [general] *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x7ff84b469a00) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.keys', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x7ff84b43fa60) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.
2021-09-09 09:45:03.052658+0200 ******[7997:216371] [general] *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x7ff84b469a00) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.keys', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x7ff84b43fa60) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.

```

**Comment by mplorentz** [comment] 2021-09-16 20:25
This is still happening with Xcode 13 RC.

**Comment by ncooke3** [comment] 2021-09-16 21:35
Hi there, sorry for the trouble. I wasn't able to reproduce Xcode 13 (both beta 5 and RC) in a project using Crashlytics. A few follow-up questions to help debug the issue:
- Is there anymore context in the logs as to where this warning is originating from?
- Could you share the `Podfile.lock`?

- Alternatively, if you're able to create a mini project that reproduces the issue, please share as it will be very helpful

**Comment by cwagdev** [comment] 2021-09-21 19:21
I'm also seeing this in a project that includes Firebase.

**Comment by natalia-osa** [comment] 2021-09-21 19:57
I am also receiving this warning since I upgraded to Xcode 13.0 (13A233) (& I never saw it before). The class which is causing the problem is `NSKeyedUnarchiver`, which in my project is available only in Firebase-related dependencies:

<img src="https://user-images.githubusercontent.com/1477880/134237033-a4849d76-0b3b-4cbc-abdd-11175182a399.png" width="400" />

Atm Firebase is installed via cocoapods:
`pod 'Firebase/Core', "~> 6.33.0"`

and in the Podfile.lock I can confirm to have (meaningful version of the modules from the screenshot)
- `Firebase/Core (6.33.0)`
- `FirebaseCoreDiagnostics (1.7.0)`
- `FirebaseInstallations (1.7.0)`
- `GoogleDataTransport (7.4.0)`
- `GoogleUtilities/Environment (6.7.2)`

Essentially, it's this warning duplicated 3 times in Xcode console:
```
[general] *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] 
allowed unarchiving safe plist type ''NSString' (0x10c45f7f0) [/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework]'
for key 'NS.keys', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x10ed8ea30) [/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework]",
    "'NSDate' (0x10ed8e828) [/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.
```

---
**The issue is only reproducible in Xcode 13.**. 
PS. Clearing derived data does not help.

**Comment by ncooke3** [comment] 2021-09-22 16:18
Hi everyone,

Thanks for all the info, and sorry again for the trouble! After further investigation, I believe this runtime warning has been fixed in a [7.x version of GoogleUtilities (dependency of Firebase)](https://github.com/google/GoogleUtilities/pull/42/files). Based on some of the older versions of Firebase mentioned in this thread, it's likely this dependency needs updating in your project. 

To fix this warning, **I'd recommend upgrading to the latest version of Firebase**.

With that, I'm going to close this issue. Please don't hesitate to comment here if the issue persists after updating Firebase.

**Closed** 2021-09-22 16:18 UTC
Labels: api: crashlytics

**Comment by bdrelling** [comment] 2021-09-26 19:42
@ncooke3 Thanks for the update. Do you know when this will be properly reflected within the core Firebase project? Right now, it looks like the dependency should be pulled in, but I'm using the latest 8.7.0 version of Firebase and it's only grabbing 7.4.1. The change you linked to is on 7.4.2, if I read the PR correctly. At this point, 7.5.2 is deployed, and Firebase is still not pulling that version in by default.

This is the dependency line in the `Package.swift` file: https://github.com/firebase/firebase-ios-sdk/blob/f243335a256264a5190830406208c524b1bdd527/Package.swift#L162

With all the dependency spaghetti Firebase has, it's hard to understand exactly when we'll get a downstream update from one of the other Google dependencies this Package is dependent on.

**Comment by ncooke3** [comment] 2021-09-26 20:46
Sorry for the trouble @bdrelling!

This does not seem like expected behavior. Just to clarify the issue: you are on **Firebase 8.7.0** via **Swift Package Manager** and are seeing only **GoogleUtilities 7.4.1** being pulled in to your project, correct?

**Comment by bdrelling** [comment] 2021-09-26 23:10
@ncooke3 No apologies necessary!

That is correct, yep. I went from **Firebase 8.6.0** to **Firebase 8.7.0**, and my version of **Google Utilities** did bump up from **7.4.1**. I then basically tried every combo of SPM tools available here:

![image](https://user-images.githubusercontent.com/3022693/134827265-b6b4577c-4df3-48a9-a2c9-0be4d977c6d0.png)

I had to manually add the following dependency:

```swift
.package(name: "GoogleUtilities", url: "https://github.com/google/GoogleUtilities", .upToNextMajor(from: "7.5.2")),
```

Then, it refreshed my packages, and now I removed the dependency and I can reset package cache / resolve package versions no problem, and it's pulling in **GoogleUtilities 7.5.2** properly.

Any idea why this didn't happen automatically? I would assume that `"7.4.0" ..< "8.0.0"` would have, as expected, pulled in any versions between `7.4.0` up to, but not including, `8.0.0`.

For additional context, I am running Xcode 13.

**Comment by ncooke3** [comment] 2021-09-27 14:01
@bdrelling 

> **re:** Any idea why this didn't happen automatically? I would assume that "7.4.0" ..< "8.0.0" would have, as expected, pulled in any versions between 7.4.0 up to, but not including, 8.0.0.

I expected the same behavior so I'm not too sure. I was unable to reproduce this issue and am unsure why the SPM tools did not work in this instance. 🤔

Now that your project has the latest dependency, are you still seeing the `NSKeyedUnarchiver` runtime warnings logged in your app?

**Comment by bdrelling** [comment] 2021-09-27 15:30
@ncooke3 No worries, I totally get it. And yeah, it's definitely an SPM thing. But I suppose the Firebase Package.swift _could_ be manually updated to `"7.5.2 ..< "8.0.0"`, right? Would that cause any issues? Because at the very least, it would have fixed whatever happened to me (which I hope was a weird off-case and not a common thing, but still...)

Nope, no more warnings! 🎉 

Thanks, @ncooke3! Sorry I couldn't provide more repro details. I'll keep an eye out and file a radar in the future if I see it again.

**Comment by paulb777** [comment] 2021-09-30 23:59
@bdrelling Good suggestion! We're working on it in #8728.

**Comment by kamrankhan07** [comment] 2021-10-01 06:41
Have same issue with Pods
GoogleUtilities is pointing to (~> 7.4), should change the version there as well.
