### ISSUE TITLE
RemoteConfigErrorDomain mismatch with "com.firebase.config"

### ISSUE THREAD

**Issue by ghowen** [firebase/firebase-ios-sdk#3279] opened 2019-06-28 09:59 UTC
* Xcode version:  10.2.1
  * Firebase SDK version: 6.3.0
  * Firebase Component: RemoteConfig
  * Component version: 4.1.0

### [REQUIRED] Step 3: Describe the problem

I am currently experiencing a FirebaseRemoteConfig error 8003. I used to catch it, but this time my switch statement failed. While investigating I noticed that the constant `RemoteConfigErrorDomain` resolves to `com.google.remoteconfig.ErrorDomain` but the error had the domain `com.firebase.config` with the error code 8003. 

So either the error is reporting the wrong domain or the constant has not been updated.

#### Steps to reproduce:

Difficult as we need to trigger the error 8003 which is not described in the docs in detail

**Comment by ryanwilson** [comment] 2019-06-28 11:50
Thanks for the report @ghowen - looks like there's a combination of both domains being used in different locations and it should be resolved. Which API were you using that caused this error?

**Comment by ghowen** [comment] 2019-06-28 11:55
@ryanwilson not sure what you mean by "which API". It's an iOS project in Swift with a deployment target of iOS 11.4. The error was triggered when I was attempting to activate a fetched configuration on a real device. In the simulator the error was not triggered for some reason. HTH

**Comment by ryanwilson** [comment] 2019-06-28 12:20
Apologies, essentially I was looking for a code sample of the method call you used. Were you using `fetch` along with `activatedFetched` in that case?

**Comment by ghowen** [comment] 2019-06-28 14:04
Got it. Here's the sample that failed with 8003 on device and worked on simulator. I am not looking to solving the 8003 though but just wanted to report the error domain mismatch.

            let remoteConfig = RemoteConfig.remoteConfig()
            remoteConfig.setDefaults(fromPlist: "RemoteConfigDefaults")
            
            remoteConfig.fetch(withExpirationDuration: 3600) { status, error in
                
                if status == .success {
                    
                    remoteConfig.activate { error in
                        
                        if error != nil {
                            return seal.reject(error!)

                        }

The error was thrown in the `remoteConfig.activate` completion handler.

**Comment by ghowen** [comment] 2019-06-28 14:07
I have rewritten this to 
`remoteConfig.fetchAndActivate { status, error in` 
in the meantime, and now there is no error but a status of `.successUsingPreFetchedData` on device. 

So my guess is that the prefetched data has triggered the 8003. The code is about a year old and started to fail only recently, probably with the latest update of the SDK.

**Comment by ryanwilson** [comment] 2019-06-28 14:16
Got it, thanks. Were you on a version of Firebase before 6.0? I'm trying to determine if the behaviour of the `activate` API changed or not during a non-major version change.

Also, it looks like some logs should be printed, and the error has an associated user description. Having the `userInfo` from the error would be helpful as well, thanks!

**Comment by ghowen** [comment] 2019-06-28 14:29
I am pretty sure I was on Firebase 6.2 or 6.1 before updating pods today. I am actively developing at the moment and I update the libs quite frequently. 

When reverting back to the old code there is a user description for the error and it looks like it's the same status, but this time presented as an error:

```
(lldb) po RemoteConfigErrorDomain
"com.google.remoteconfig.ErrorDomain"

(lldb) po error
▿ Optional<Error>
  - some : Error Domain=com.firebase.config Code=8003 "(null)" UserInfo={ActivationFailureReason=Most recently fetched config is already activated}
```

**Comment by paulb777** [comment] 2019-06-28 14:59
RemoteConfig had more substantial changes from 6.2.0 to 6.3.0 than from 5.x to 6.0.0 so if it's a regression, 6.3.0 is a good bet.

**Comment by ryanwilson** [comment] 2019-06-28 15:04
Got it, thanks!

The `activate` with completion handler was added recently, and it looks like the domain didn't change but is indeed different from the constant given. I'm guessing the device vs simulator has to do with the persistence of the values being returned from cache vs being fetched successfully.

**Comment by ghowen** [comment] 2019-06-28 15:13
Actually `activate` must have been around for some time as I did not touch this code for a while before it stopped working today. The docs at https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig are a bit out of sync on this as they do not mention the method `fetchAndActivate` yet. They do mention `activateFetched` though which might have been added recently (or was `activate` renamed?). But maybe updating the reference should be another issue?

**Comment by morganchen12** [comment] 2019-06-28 16:57
`activateFetched` was recently deprecated in favor of `activate`. We'll track updating the docs separately.

**Comment by dmandar** [comment] 2019-07-02 04:15
Thanks for reporting @ghowen . A fix is in the works.

**Closed by dmandar** 2019-07-02 04:15 UTC
Labels: api: remoteconfig

**Comment by paulb777** [comment] 2019-07-02 14:23
Targeting for M52 (the release after 6.4.0)
