### ISSUE TITLE
DynamicLink url is nil when first install 

### ISSUE THREAD

**Issue by chenkuanhuaian** [firebase/firebase-ios-sdk#2666] opened 2019-03-28 10:45 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.4.1 (tried 5.19.0)
  * Firebase Component:  DynamicLinks
  * Component version: 3.0.1 (tried 3.4.2)

### [REQUIRED] Step 3: Describe the problem

I tried to create dynamicLink at Firebase console to navigate user to download my app at appStore,
and when they launch app for the first time I keep getting DynamicLink object with nil url.

```
 func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {

      if let dynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
            //  dynamicLink url is nil 
      }
}
```

```
<FIRDynamicLink: 0x281ad2a40, url [(null)], match type: none, minimumAppVersion: N/A, match message: (null)>
```

and the url is 
```
MyAppSchema://google/link/?dismiss=1&is_weak_match=1
```

when I perform diagnostic i got this 
```
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 3.0.1
System information: OS iOS, OS version 12.1.4, model iPhone
Current date 2019-03-28 10:10:21 +0000
Device locale en-US (raw en_US), timezone Asia/Taipei
	Specified custom URL scheme is tw.tyche.voicetube and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: {AppID Prefix:}, Team ID: {Team ID}, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----
```

has tried / confirmed :

1. not using safari private mode
2. short link / long link 
3. app not installed
4. switch preferredLanguages / region / locale 
5. preview page enabled
6. wifi and Cellular 

but none of above helps 

I went through pretty much any information I could reach but still have no idea what went wrong.

#### Steps to reproduce:

1. app not installed
2. click on a dynamicLink
3. preview page 
4. appStore page 
5. build to device from Xcode 
6. get DynamicLink object but url is nil

#### Relevant Code:

**Comment by maksymmalyhin** [comment] 2019-03-28 13:48
@chenkuanhuaian It looks like there might be an issue with the dynamic link itself or with Dynamic Links setting in your Firebase application, e.g. iOS bundle ID is not configured correctly, etc. Have you tried to open the link in the debug mode? (https://firebase.google.com/docs/dynamic-links/debug) If you could see any warnings there?

**Comment by chenkuanhuaian** [comment] 2019-03-28 15:16
it says 
```
There is no configuration to prevent phishing on this domain https://v4kwt.app.goo.gl. Setup URL patterns to whitelist in the Firebase Dynamic Links console. 
```
So the whitelist has to be set to make valid FDL ?
thanks for replying

**Comment by maksymmalyhin** [comment] 2019-03-28 15:26
@chenkuanhuaian This warning doesn't look like a reason of your issue. 

Another thing you can check - `apple-app-site-association` for your link:
<img width="358" alt="Screen Shot 2019-03-28 at 11 21 09 AM" src="https://user-images.githubusercontent.com/1841926/55169910-fd904b80-514b-11e9-81d1-36e13f3b39f0.png">

The `details` array should contain the bundle ID of your application (where you perform the code). Sometimes the developer variant of a Team ID + Bundle ID is missing.

**Comment by chenkuanhuaian** [comment] 2019-03-28 15:31
```
{"applinks":{"apps":[],"details":[{"appID":"S5EYV54P8X.com.voicetube.dictionary","paths":["NOT /_/*","/*"]},{"appID":"S5EYV54P8X.tw.tyche.voicetube","paths":["NOT /_/*","/*"]},{"appID":"S5EYV54P8X.com.voicetube.mainApp","paths":["NOT /_/*","/*"]},{"appID":"S5EYV54P8X.com.voicetube.dictionaryBeta","paths":["NOT /_/*","/*"]}]}}
```
here's what I got !

**Comment by maksymmalyhin** [comment] 2019-03-28 16:23
@chenkuanhuaian Looks correct to me.
Just looked at the code more attentively - if you receive your custom scheme URL in `func application(_:, open url:, options:) ` then following code should not be affected by this.

Another reason in may fail: it looks like you need to specify your `deepLinkURLScheme` before configuring the `FirebaseApp` to make `dynamicLink(fromCustomSchemeURL:` being able to process your link:

```
FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "<MyAppScheme>"
FirebaseApp.configure()
```

I wonder, if you do it?

**Comment by chenkuanhuaian** [comment] 2019-03-28 17:03
Yes, 

In my appDelegate method :

```
FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "tw.tyche.voicetube"
FirebaseApp.configure()

```

and Here's my dynamic link
```
https://v4kwt.app.goo.gl/?link=http://tw.voicetube.com/?appPage%3Dpayment?ius%3Dtw.tyche.voicetube&apn=org.redidea.voicetube&isi=641446200&ibi=tw.tyche.voicetube
```

according to the documentation, 
as long as `ius` parameter  match deepLinkURLScheme, it should works fine.
https://firebase.google.com/docs/dynamic-links/ios/create
please correct me if i am wrong

**Comment by maksymmalyhin** [comment] 2019-03-28 17:38
Everything looks correct to me.

@dmandar Could you help here?

**Comment by dmandar** [comment] 2019-03-29 17:51
can you make sure your ibi parameter in your DL is the same as the target app you are opening?

**Comment by chenkuanhuaian** [comment] 2019-03-30 02:55
@dmandar 
yes.
When app is already installed, DynamicLinks works like a charm.
If ibi parameter doesn't match, I wouldn't even open my app with FDL right ?

**Comment by chenkuanhuaian** [comment] 2019-04-02 02:12
Hi, I tried to set up a new clean project with dynamicLink / deeplink,
It works like a charm and I got the deep link url that I need. 

But I still have no clue why it doesn't work on my current project. 
If is not the code, then it must be the Xcode or Firebase Console configuration ?

**Comment by joerivett** [comment] 2019-04-05 17:46
@chenkuanhuaian Did you get anywhere with working out why it wasn't working in your existing project? I am seeing exactly the same issue - when the app is installed the dynamic links work fine but on first run after install I see the `<<scheme>>://google/link/?dismiss=1&is_weak_match=1` URL

**Comment by chenkuanhuaian** [comment] 2019-04-05 18:18
@joerivett unfortunately no.
still struggling, almost give up.
I tried everything that could possibly cause the issue and still have no clue.
I called out firebase support team for help and waiting for reply. 
Glad I am not the only one having this issue.

**Comment by chenkuanhuaian** [comment] 2019-04-10 01:46
@joerivett 
I think you're right!
My FDL deep links works now!
The weird thing is, I mentioned that I opened a clean project just for testing,
I didn't enabled FDL for the project at the console you posted and still works.
Anyway, good thing we both worked it out! 

----

I called for Firebase support team' help and here's their reply just in case someone struggles like I did

```
Thanks for patiently waiting and for bringing this to our attention. It seems that you're able to make it work by creating a new clean project.

From what I understand, in your current project the deeplink does not survive after install from the App Store. I've checked your issue in the provided link, and see that some information are hidden such as {bundleId}. So that we are on the same page, kindly follow some troubleshooting steps that usually solves this issue:
Check the app's bundle ID against the "ibi" parameter of the dynamic link and confirm that they match.
Make sure that you call the handleUniversalLink: and dynamicLinkFromCustomSchemeURL: methods when your app loads to get the data passed in the Dynamic Link. You can refer to this guide.
In the Capabilities tab of your app's Xcode project, make sure that "Associated Domains" is enabled and add the following to the Associated Domains list: applinks:your_subdomain.page.link. You may visit our guide here for more information.
Verify if your_subdomain.page.link/apple-app-site-association contains an entry for your app. Make sure that the values are correct for your app.
If you're encountering this issue during simulated app install and redirected to an interstitial(app preview) page. Click 'Open' first before side-loading the app using Xcode. The app will receive null when the app is side-loaded without clicking 'Open' in the interstitial page.
If you're still encountering this issue after following the guide above, kindly provide the following information to dig deeper into the issue:
Minimal repro that I can run locally (i.e. MCVE) 
AppDelegate file
Short FDL / Long FDL
Error logs or stack trace when downloading the app for the first time from App Store.
```

**Comment by asn111** [comment] 2019-05-10 20:54
Hellow every one
Thank you for this awesome library, but I am stuck at a point when dealing with deep linking, it has been enabled before and was working fine, then God knows how did I got ShortUrl nil, after some RND, I did managed to update pods and then all happens that when instancing DynamicLinkComponents with its initialiser,
`let components = DynamicLinkComponents(link: urlLink, domainURIPrefix: AppConstants.kDynamicLink_Domain)!`
both `urlLink` and `AppConstants.kDynamicLink_Domain` have valid values in them but still getting app crashed, with Fatal error that nil found while unwrapping.
I have no idea why its happening, I have opened another issue but now one is answering me there.

Xcode version: 10.1
Firebase SDK version: 6.0.0
Firebase Component: Firebase/DynamicLinks
Component version: 4.0.0

**Comment by maksymmalyhin** [comment] 2019-05-10 21:18
@asn111 The initialize `DynamicLinkComponents(link:, domainURIPrefix:)` is marked as an optional, so it may return `nil` as a result, so you should not force unwrap its result if you don't want you app crashing. 

You can get more information on the Swift Optionals [here](https://developer.apple.com/documentation/swift/optional)

You may use `if let components = ...` or `guard let components  = ... else ...` instead.

I would ask you to create a separate issue (ideally with a test project/code to reproduce the issue) if you think that `DynamicLinkComponents(link:, domainURIPrefix:)` should not return `nil` in your case. Please consider verifying correctness of the parameters you pass to the initializer.

**Comment by asn111** [comment] 2019-05-10 21:29
Hi, @maksymmalyhin thank you for your response, yes i figured out that, but main thing is i do not want it to be nil.
[https://github.com/firebase/firebase-ios-sdk/issues/2961](url) here I have created a new issue two days ago, but no one responded, if you may kindly have a look and guide me it will be very helpful for me. thanks

**Closed** 2019-05-21 01:06 UTC
Labels: api: dynamiclinks
