### ISSUE TITLE
Crashed: com.google.firebase.firestore

### ISSUE THREAD

**Issue by ChristianVinterly** [firebase/firebase-ios-sdk#3875] opened 2019-09-18 08:24 UTC
This issue might be related to #3851, since it has the same stack trace in Protobuf.

We only see this crash on iOS 10 and iPad 4, but this is from TestFlight, so the user group only consists of a few thousand users.

```
Using Firebase (6.7.0)
Using FirebaseABTesting (3.1.0)
Using FirebaseAnalytics (6.1.1)
Using FirebaseAnalyticsInterop (1.4.0)
Using FirebaseAuth (6.2.3)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.2.1)
Using FirebaseCoreDiagnostics (1.0.1)
Using FirebaseCoreDiagnosticsInterop (1.0.0)
Using FirebaseFirestore (1.4.5)
Using FirebaseInstanceID (4.2.3)
Using FirebasePerformance (3.1.2)
Using FirebaseRemoteConfig (4.3.0)
Using FirebaseStorage (3.4.0)
```

![65023361-f1cf5600-d932-11e9-98ee-6f83d7e0d067](https://user-images.githubusercontent.com/12391750/65130839-83f06080-d9fe-11e9-9898-1d5ef559f47c.png)

**Comment by ryanwilson** [comment] 2019-09-18 14:04
Thanks for the report @ChristianVinterly! You're right, this is definitely a dupe of #3851. We're making good progress on it and will update that bug with more information.

Thanks again 😄

**Closed by ryanwilson** 2019-09-18 14:04 UTC
Labels: api: firestore

**Comment by morganchen12** [comment] 2019-09-18 14:29
I had originally suspected this to be a different issue because it originated from a different framework, but looks like the root cause is the same. Sorry @ChristianVinterly!
