### ISSUE TITLE
Firebase/Perofrmance issue

### ISSUE THREAD

**Issue by babuiglesiaskhan** [firebase/firebase-ios-sdk#2155] opened 2018-12-06 07:28 UTC
Describe your environment
  * Xcode version: 9.2
  * Firebase SDK version: 4.9.0
  * Firebase Component: _____ (FirebaseAnalytics (4.0.9), FirebaseAuth (4.4.3), FirebaseCore (4.0.15), FirebaseDatabase (4.1.4), FirebaseInstanceID (2.0.9), FirebaseMessaging (2.1.0), etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
I just installed FirebasePerformance but with automatically installed FirebaseSwizzlingUtilities.

Installing FirebasePerformance (1.1.1)
Installing FirebaseSwizzlingUtilities (1.0.1)

but after installed when I tried to run my app so I got this error 

![screen shot 2018-12-06 at 12 57 03 pm](https://user-images.githubusercontent.com/45651995/49568276-8e050f00-f956-11e8-8605-e7706883003d.png)

**Comment by ryanwilson** [comment] 2018-12-06 14:18
Hi @babuiglesiaskhan - Firebase 4.9.0 was release about 10 months ago and there have been several iterations (including a major version update, 5.0) and we're currently on version `5.14.0`. The functionality of the `FirebaseSwizzlingUtilities` framework is now integrated with `GoogleUtiltiies` pod.

There are many bug-fixes (and features) included since then, it's recommended that you update to the recent version for best compatibility. At the very least, if you don't want to go through a breaking change, you can update to `4.13.0`.

**Comment by paulb777** [comment] 2018-12-06 15:53
This is a duplicate of #1197. A workaround is posted there at https://github.com/firebase/firebase-ios-sdk/issues/1197#issuecomment-385554442

**Closed by paulb777** 2018-12-06 15:53 UTC
