### ISSUE TITLE
FR: Swift codable with arrays

### ISSUE THREAD

**Issue by EddieLukeAtmey** [firebase/firebase-ios-sdk#5438] opened 2020-04-22 16:09 UTC
### Feature proposal

* Firebase Component: FirestoreSwift

I'm implementing swift codable as guided in doc using `data.as(DecodableType.self)`.
There's a case where I have an array of doc references (referenced to another collection)

```
final class TodoModel: DocumentReference {
    var name: String?
    var createdAt: Date?
    var deadLine: Date?
    var startTime: Date?
    var endTime: Date?
    var spendTime: Date?

    // MARK: - Realtionship
    // @ObjectID var tasks: [TodoTaskModel]? // @ObjectID Not working on this.
    // @ObjectID var tasks: [DocumentReference]? // This is not working also.
}

final class TodoTaskModel: DocumentReference {
   var name: String?
   @ObjectID var todo: TodoModel?
}
```

This yields `decodingIsNotSupported : "DocumentReference values can only be decoded with Firestore.Decoder"` even after comment all the tasks. 

After digging the fireStoreSwift for a bit, it seems the decoding for array reference is not yet implemented. Any helps to implement this is appreciated. Thanks.

**Comment by EddieLukeAtmey** [comment] 2020-04-22 16:21
Digging for more, it seems this part is somehow incorrect in the logic:

```
FireStoreDecoder.h
Line 1039: 
func unbox<T: Decodable>(_ value: Any, as _: T.Type) throws -> T? {
....
    if let v = value as? T { // T is TodoModel, but value is [String: Any] 
      if isFirestorePassthroughType(v) {
        // All the native Firestore types that should not be encoded
        return (value as! T)
      }
    }
...
```
The debugger passed the check and go to this:
```
storage.push(container: value)
let decoded = try T(from: self)
```

Here it jumps again to `CodableDocumentReference` and `throw FirestoreDecodingError.decodingIsNotSupported(
      "DocumentReference values can only be decoded with Firestore.Decoder"
    )`

**Comment by schmidt-sebastian** [comment] 2020-04-22 19:13
@EddieLukeAtmey Thanks for filing this. I will look at this today and report back with an estimate on how long it might take to fix.

**Comment by schmidt-sebastian** [comment] 2020-04-24 22:18
@EddieLukeAtmey Sorry for the slow response time here. I had to check back with the team.

It turns out that we explicitly decided to not provide a general purpose encoding of `DocumentReference`s. While they work within Firestore, we don't provide a JSON mapping that allows them to be used outside of Firestore.Encoder/Firestore.Decoder. The reason for this is that there is no appropriate general purpose way to serialize the inherent properties of a DocumentReference (e.g. the path, project and database and the properties of the Firestore instance from which it was created). 

While we could theoretically provide a JSON mapping that conveys this data, doing so would lock us into a format and prevent us from making internal SDK changes that could affect the representation (such as adding new private fields).

I am able to serialize arrays of DocumentReferences using the Firestore.Encoder and Firestore.Decoder. If that doesn't work for you either, do you mind providing a reproduction so we can continue our investigation? I will close this feature request for now, but we can re-open if there are issues in this code path.

**Closed by schmidt-sebastian** 2020-04-24 22:18 UTC
Labels: api: firestore, type: feature request
