### ISSUE TITLE
Stable EXC_BAD_ACCESS crash in FIRInstallations after updating to iOS 17.4 / Xcode 15.3

### ISSUE THREAD

**Issue by bn-dev-1** [firebase/firebase-ios-sdk#12604] opened 2024-03-21 12:41 UTC
### Description

Dear Firebase Team,

After updating development environment to latest versions (iOS 17.4 / Xcode 15.3) we've started receiving excessive crash reports from TestFlight builds. We don't have exact steps to reproduce the problem, but it is reported that once the installed build faces this issue, it is reproduced on every app launch and it immediately crashes. The Firebase lib version is 10.21.0. Kindly see the attached crash log. Thank you for your time and consideration.

### Firebase SDK Version

10.21.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000170f14fcc
Exception Codes: 0x0000000000000001, 0x0000000170f14fcc
VM Region Info: 0x170f14fcc is not in any region.  Bytes after previous region: 21860301  Bytes before following region: 589934644
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                    16f9b4000-16fa3c000 [  544K] rw-/rwx SM=PRV  thread 21
--->  GAP OF 0x24774000 BYTES
      unused __TEXT            1941b0000-194224000 [  464K] r-x/r-x SM=COW  unused  unknown system shared lib __TEXT
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [1861]

Triggered by Thread:  0


Thread 0 name:
Thread 0 Crashed:
0   nanopb                        	0x00000001051da904 safe_read_bool + 0 (pb_encode.c:140)
1   nanopb                        	0x00000001051da904 pb_enc_bool + 0 (pb_encode.c:771)
2   nanopb                        	0x00000001051da254 encode_basic_field + 256 (pb_encode.c:0)
3   nanopb                        	0x00000001051da254 encode_field + 436 (pb_encode.c:457)
4   nanopb                        	0x00000001051da074 pb_encode + 172 (pb_encode.c:544)
5   FirebaseSessions              	0x0000000102fe813c FIRSESEncodeProto + 64 (FIRSESNanoPBHelpers.m:60)
6   FirebaseSessions              	0x0000000102ff304c SessionStartEvent.transportBytes() + 232 (SessionStartEvent.swift:155)
7   FirebaseSessions              	0x0000000102ff32d4 @objc SessionStartEvent.transportBytes() + 28 (<compiler-generated>:0)
8   GoogleDataTransport           	0x0000000103179fac -[GDTCOREvent setDataObject:] + 68 (GDTCOREvent.m:101)
9   GoogleDataTransport           	0x0000000103179e3c -[GDTCOREvent copy] + 72 (GDTCOREvent.m:68)
10  GoogleDataTransport           	0x0000000103187000 -[GDTCORTransport sendEvent:onComplete:] + 44 (GDTCORTransport.m:89)
11  FirebaseSessions              	0x0000000102fee834 GDTCORTransport.logGDTEvent(event:completion:) + 24 (GoogleDataTransport+GoogleDataTransportProtocol.swift:31)
12  FirebaseSessions              	0x0000000102fee834 protocol witness for GoogleDataTransportProtocol.logGDTEvent(event:completion:) in conformance GDTCORTransport + 176 (<compiler-generated>:30)
13  FirebaseSessions              	0x0000000102fe9ec0 EventGDTLogger.logEvent(event:completion:) + 224 (EventGDTLogger.swift:52)
14  FirebaseSessions              	0x0000000102fe9f44 protocol witness for EventGDTLoggerProtocol.logEvent(event:completion:) in conformance EventGDTLogger + 20 (<compiler-generated>:0)
15  FirebaseSessions              	0x0000000102ff11c4 closure #1 in SessionCoordinator.attemptLoggingSessionStart(event:callback:) + 176 (SessionCoordinator.swift:47)
16  FirebaseSessions              	0x0000000102ff13c4 closure #1 in SessionCoordinator.fillInFIID(event:callback:) + 180 (SessionCoordinator.swift:0)
17  FirebaseSessions              	0x0000000102feebe4 closure #1 in FIRInstallations.installationID(completion:) + 32 (Installations+InstallationsProtocol.swift:0)
18  FirebaseSessions              	0x0000000102feebe4 partial apply for closure #1 in FIRInstallations.installationID(completion:) + 48 (<compiler-generated>:0)
19  FirebaseSessions              	0x0000000102feeaa8 thunk for @escaping @callee_guaranteed (@guaranteed String?, @guaranteed Error?) -> () + 96 (<compiler-generated>:0)
20  FirebaseInstallations         	0x0000000102eb49bc __49-[FIRInstallations installationIDWithCompletion:]_block_invoke + 56 (FIRInstallations.m:201)
21  FBLPromises                   	0x00000001029b9130 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.18 + 52 (FBLPromise.m:273)
22  libdispatch.dylib             	0x00000001a425d13c _dispatch_call_block_and_release + 32 (init.c:1530)
23  libdispatch.dylib             	0x00000001a425edd4 _dispatch_client_callout + 20 (object.m:576)
24  libdispatch.dylib             	0x00000001a426d5ec _dispatch_main_queue_drain + 1060 (queue.c:7898)
25  libdispatch.dylib             	0x00000001a426d1b8 _dispatch_main_queue_callback_4CF + 44 (queue.c:8058)
26  CoreFoundation                	0x000000019c39951c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1780)
27  CoreFoundation                	0x000000019c396218 __CFRunLoopRun + 1996 (CFRunLoop.c:3149)
28  CoreFoundation                	0x000000019c395968 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
29  GraphicsServices              	0x00000001e06934e0 GSEventRunModal + 164 (GSEvent.c:2196)
30  UIKitCore                     	0x000000019e808edc -[UIApplication _run] + 888 (UIApplication.m:3692)
31  UIKitCore                     	0x000000019e808518 UIApplicationMain + 340 (UIApplication.m:5282)
32  ApplicationN       	                0x000000010104fb20 main + 80 (main.m:24)
33  dyld                          	0x00000001bf8b6d84 start + 2240 (dyldMain.cpp:1298)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

- Firebase/Analytics (10.21.0):
    - Firebase/Core
  - Firebase/Core (10.21.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.21.0)
  - Firebase/CoreOnly (10.21.0):
    - FirebaseCore (= 10.21.0)
  - Firebase/Crashlytics (10.21.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.21.0)
  - Firebase/DynamicLinks (10.21.0):
    - Firebase/CoreOnly
    - FirebaseDynamicLinks (~> 10.21.0)
  - Firebase/Performance (10.21.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 10.21.0)
  - FirebaseABTesting (10.21.0):
    - FirebaseCore (~> 10.0)
  - FirebaseAnalytics (10.21.0):
    - FirebaseAnalytics/AdIdSupport (= 10.21.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.21.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.21.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.21.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.21.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.21.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.21.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseDynamicLinks (10.21.0):
    - FirebaseCore (~> 10.0)
  - FirebaseInstallations (10.21.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebasePerformance (10.21.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfig (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/ISASwizzler (~> 7.8)
    - GoogleUtilities/MethodSwizzler (~> 7.8)
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.21.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSharedSwift (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseSessions (10.21.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (10.21.0)

```

</details>

**Comment by paulb777** [comment] 2024-03-21 13:41
This is a duplicate of #11403. Please update to 10.22.0 or newer.

**Closed by paulb777** 2024-03-21 13:41 UTC
Labels: api: installations
