### ISSUE TITLE
fetchSignInMethodsForEmail wrong response for EmailLink providerId

### ISSUE THREAD

**Issue by radvansky-tomas** [firebase/firebase-ios-sdk#3412] opened 2019-07-22 23:50 UTC
* Xcode version: 10.2.1
  * Firebase SDK version: firebase_auth: ^0.11.1+12 -> auth version 6.0
  * Firebase Component: Auth(Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 6.0

#### Steps to reproduce:

Register user with firebase auth using emailLink. Check providerId using
fetchSignInMethodsForEmail

Response is: ["password"] but it should be ["emailLink"]

Which is correct on JS client.

#### Relevant Code:
Code from flutter plugin
```
if ([@"fetchSignInMethodsForEmail" isEqualToString:call.method]) {
    NSString *email = call.arguments[@"email"];
    [[self getAuth:call.arguments]
        fetchProvidersForEmail:email
                    completion:^(NSArray<NSString *> *providers, NSError *error) {
                      [self sendResult:result forObject:providers error:error];
                    }];
  }
```

**Comment by radvansky-tomas** [comment] 2019-07-23 01:06
Temp workaround - create cloud function to expose fetchProvidersForEmail via HTTP endpoint

Make sure that you have client env setup on cloud functions
```
exports.getProviders = functions.https.onCall((data, context) => {
  return new Promise((resolve, reject) => {
    return firebase.auth().fetchSignInMethodsForEmail(data.email).then((providers:any) => {
      resolve(providers);
    }).catch((err:any) => {
      reject(err);
    })
  });
});
```

**Comment by renkelvin** [comment] 2019-07-30 23:40
Hi @radvansky-tomas, are you using the flutter SDK?

**Comment by epicquestgames** [comment] 2019-07-30 23:42
@renkelvin yes, but issue is in Native libs, not in flutter plugin. I've checked their source and iOS library is returning wrong results

**Comment by renkelvin** [comment] 2019-07-31 00:03
I'm not able to reproduce the issue yet so I'm not sure what the root cause is.
Do you know how to reproduce on native platform?

**Comment by epicquestgames** [comment] 2019-07-31 00:07
It should be completely the same thing. Create user with 
password less account -> then fetch providers
and check what method will return to you

Additionally you can add password provider to same account and check if you will get both providers in fetch methods.

**Comment by renkelvin** [comment] 2019-07-31 00:20
Still not able to reproduce.
`fetchProvidersForEmail` returns "password" and `fetchSignInMethodsForEmail` returns `emaillink`.
Would you mind sharing a public repo that can reproduce this issue?

**Comment by epicquestgames** [comment] 2019-07-31 00:23
I will test it then again, will try to update versions and is if was some temporary issue then.

Code for plugin is very simple:

```
if ([@"fetchSignInMethodsForEmail" isEqualToString:call.method]) {
    NSString *email = call.arguments[@"email"];
    [[self getAuth:call.arguments]
        fetchProvidersForEmail:email
                    completion:^(NSArray<NSString *> *providers, NSError *error) {
                      [self sendResult:result forObject:providers error:error];
                    }];
  }
```

**Comment by siburb** [comment] 2019-08-09 03:52
I'm seeing similar behaviour, but both `fetchSignInMethods` and `fetchProviders` are returning the same incorrect results. I have an account that is authenticated using Facebook, and I'm getting "password, google.com" back. Testing an email that was authenticated using google.com, and I'm getting the correct result back. I can't see whether these incorrect results are just cached from a previous user, or are a direct result of checking for the current user.

**Comment by renkelvin** [comment] 2019-08-13 17:51
@siburb It seems a different issue. Could you create a new issue with the steps to reproduce? Thanks!

**Comment by morganchen12** [comment] 2019-09-20 20:58
Closing this since we haven't had a solid repro case. Please comment here if you're able to share a sample project that reproduces the issue.

**Closed by morganchen12** 2019-09-20 20:58 UTC
Labels: api: auth
