### ISSUE TITLE
Crash on FIRAnalytics, FIRAScheduler, FIRAIdentity and FIRASqliteStore classes

### ISSUE THREAD

**Issue by kaannesinn** [firebase/firebase-ios-sdk#1288] opened 2018-05-17 11:01 UTC
Hi,
In our ios [application](https://itunes.apple.com/us/app/translate-assistant/id1348751689?mt=8), we use Firebase for event logging and show native and interstitial ad banners with Google-Mobile-Ads-SDK. After adding Firebase and GAD libraries and updating our app on AppStore, these crashes are occured;
http://crashes.to/s/5fc50f389c7 -> FIRAnalytics
http://crashes.to/s/47b922a704a -> FIRAScheduler
http://crashes.to/s/71867fc9083 -> FIRAIdentity
http://crashes.to/s/3777fae0a3b -> FIRASqliteStore

I cant experience or reproduce these issues with simulator or test devices but on the production platform (appstore version)

The crash might be when the application is on background or when sending an event on purchasing step. Don't know the exact step.

Pod I am using on Xcode version: 9.3 (ObjC);
Using AFNetworking (3.2.0)
Using CNPPopupController (0.3.3)
Using Crashlytics (3.10.1)
Using EAIntroView (2.12.0)
Using EARestrictedScrollView (1.1.0)
Using FLAnimatedImage (1.0.12)
Using Fabric (1.7.6)
Using Firebase (4.13.0)
Using FirebaseAnalytics (4.2.0)
Using FirebaseCore (4.0.20)
Using FirebaseInstanceID (2.0.10)
Using Google-Mobile-Ads-SDK (7.30.0)
Using GoogleAnalytics (3.17.0)
Using GoogleToolboxForMac (2.1.4)
Using HCSStarRatingView (1.5)
Using IQKeyboardManager (5.0.8)
Using SDWebImage (4.3.3)
Using SMPageControl (1.2)
Using UICKeyChainStore (2.1.1)
Using nanopb (0.3.8)

Thanks

**Comment by baolocdo** [comment] 2018-05-17 15:12
Would you mind updating to the latest SDK at 5.0.0 and let us know whether you still see similar crashes?

**Comment by baolocdo** [comment] 2018-05-17 15:17
tracked internally at b/79920348

**Comment by kaannesinn** [comment] 2018-05-17 22:34
Yes of course, because of we were using previous versions on AppStore version of our app, we have updated all sdks and updated our app also. I have sent to Apple this evening, waiting the review process. After that and distributing some days, I will look for them and turn to you the cases. 

Are these bugs known ones on your previous sdks or new issues that you dont know or experience?

Thanks


Alex Do <notifications@github.com> şunları yazdı (17 May 2018 18:12):

**Comment by baolocdo** [comment] 2018-06-12 20:28
Some of these are rare and they are not easy to reproduce. We are still trying to see whether we can reproduce those crashes. If you have any sample projects with similar crashes, please share them. Thanks.

**Comment by morganchen12** [comment] 2018-06-29 21:35
Closing since this has had no new activity or repro steps. Please update to the latest version of Firebase and comment on this issue if it still exists.

**Closed by morganchen12** 2018-06-29 21:35 UTC
Labels: Analytics

**Comment by kaannesinn** [comment] 2018-07-02 14:19
Hi @baolocdo 

Could you find a fix for that case? We are updating with the new versions of the SDK whenever Firebase updates them. But we cant find a related description for fixes on each release notes of them. 

Btw the previous crashes doesnt like to be appeared again but sometimes some other crashes occurs. We see them on fabric but we cant reproduce them.

I am going to open a new issue for them and we cant reproduce them again on our app :/

Thanks

**Comment by baolocdo** [comment] 2018-07-05 22:05
@kaannesinn: I'm not aware of the fixes that fixed your crashes. It might be a coincidence that some bug fixes also alleviate your crashes too or newer iOS might influence the crash rate. If you find any new one, please let us know. Thanks

**Comment by kaannesinn** [comment] 2018-07-06 00:08
@baolocdo ok, yes we are updating Firebase sdk whenever there is a new update without knowing that it solves our crashes or not. And some of the crashes on this issue are like to be gone. Yes it could be a coincidence maybe. But some crashes still exist with a low amount. 

You can see them on https://github.com/firebase/firebase-ios-sdk/issues/1487

Thank
