### ISSUE TITLE
InAppMessaging - After updating to 5.20.2, InAppMessaging no longer appears

### ISSUE THREAD

**Issue by nirazo** [firebase/firebase-ios-sdk#2981] opened 2019-05-10 08:17 UTC
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.20.2
  * Firebase Component: InAppMessaging + InAppMessagingDisplay
  * Component version: 5.20.2

### [REQUIRED] Step 3: Describe the problem

After updating to 5.20.2, InAppMessaging no longer appears.
I used a custom event for the trigger and specified "1 time per device for this campaign" as the display frequency.
Event transmission is successful (confirmed with DebugView), but InAppMessaging is not displayed.
If you change the display frequency, it will not be displayed as well.

InAppMessaging is displayed correctly if it is not a custom event but a default event (for example, on_foreground event).

It used to use Firebase SDK 5.13.0 before updating it, and was able to display correctly in that version with the same settings.

Thanks in advance!

**Comment by michalbencur** [comment] 2019-05-14 13:28
We integrated InAppMessaging only yesterday, with new 6.0.0 release and experience the same bug as describe above.

Campaign triggered on_foreground gets delivered, but campaign triggered by our own event never shows up.

**Comment by christibbs** [comment] 2019-05-14 17:49
I'm seeing this as well, investigating.

**Comment by ryanwilson** [comment] 2019-05-15 19:54
We've tracked down the cause and are working on a fix.

**Comment by jonameson** [comment] 2019-05-21 15:14
@ryanwilson any workarounds available while using the latest Firebase libs? We are also having the same issue.

**Comment by ryanwilson** [comment] 2019-05-21 15:15
Unfortunately not, but we should have a new release out shortly that fixes the issue. Hang tight!

**Comment by christibbs** [comment] 2019-05-21 20:04
This is fixed in the latest SDK update. Run `pod update`, it should install `FirebaseInAppMessaging 0.14.1` where this is fixed.

**Closed by christibbs** 2019-05-21 20:04 UTC
Labels: api: inappmessaging

**Comment by jonameson** [comment] 2019-05-21 20:32
Confirmed works! Thank you guys!

**Comment by nirazo** [comment] 2019-05-22 01:51
Confirmed works too! Thank you guys!!!
