### ISSUE TITLE
Memory leak in GULNetworkURLSession

### ISSUE THREAD

**Issue by KleMiX** [firebase/firebase-ios-sdk#1917] opened 2018-10-08 05:25 UTC
* Xcode version: 10.1 beta (10O23u)
  * Firebase SDK version: 5.9.0
  * Firebase Component: GoogleUtilities/Network
  * Component version: 5.2

#### Steps to reproduce:

Configure Firebase and run app in Instruments, it will show many leaks related to `NSURLSession`. These sessions need to be invalidated to free all resources they are holding to, placing calls to `[session finishTasksAndInvalidate];`  before returning from functions that create `NSURLSession`, seems to fix the issue.

#### Relevant Code:

```[FIRApp configure];```

**Comment by hcn1519** [comment] 2018-10-09 11:21
I also have same issue.

<img width="1396" alt="2018-10-09 8 20 19" src="https://user-images.githubusercontent.com/13018877/46666142-d925ce80-cc00-11e8-90f1-bfd224cef14d.png">

<img width="1396" alt="2018-10-09 8 20 12" src="https://user-images.githubusercontent.com/13018877/46666145-dc20bf00-cc00-11e8-8945-da18a402f571.png">

**Comment by paulb777** [comment] 2018-10-11 01:49
The initial fix failed some tests. Reopening to continue the investigation.

**Comment by morganchen12** [comment] 2018-10-31 16:42
@RamblinWreck77 can you share your project? I haven't been able to repro.

**Comment by morganchen12** [comment] 2018-10-31 16:53
Looks like this fix has not been released yet.

**Comment by AndriyGo** [comment] 2018-11-06 21:00
@morganchen12 I have the same issue with lots of memory leaks generated by Firebase. I am attaching the screenshot.

<img width="1396" alt="screenshot 2018-11-06 at 22 58 04" src="https://user-images.githubusercontent.com/7107815/48093311-b4c90c00-e217-11e8-93e6-f53808a6f754.png">


Here is my setup:

```
Using Firebase (5.11.0)
Using FirebaseAnalytics (5.3.0)
Using FirebaseAnalyticsInterop (1.1.0)
Using FirebaseAuth (5.0.4)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.6)
Using FirebaseDynamicLinks (3.1.1)
Using FirebaseFunctions (2.1.1)
Using FirebaseInstanceID (3.3.0)
Using FirebaseUI (5.2.2)
Using GTMSessionFetcher (1.2.0)
Using GoogleAppMeasurement (5.3.0)
Using GoogleUtilities (5.3.4)
```

I would be happy to share my project with you as long as there is some secure way of doing this.

**Comment by morganchen12** [comment] 2018-11-06 21:46
Thanks @AndriyGo, I'll take a look.

**Comment by AndriyGo** [comment] 2018-11-08 16:15
@morganchen12 in case it may be helpful here are the results after updating to latest pods:

<img width="1396" alt="screenshot 2018-11-08 at 18 12 29" src="https://user-images.githubusercontent.com/7107815/48211326-f4ac0280-e381-11e8-91b4-07c830088fb6.png">

Setup:

```
Using Firebase (5.12.0)
Using FirebaseAnalytics (5.3.0)
Using FirebaseAnalyticsInterop (1.1.0)
Using FirebaseAuth (5.0.5)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.7)
Using FirebaseDynamicLinks (3.1.1)
Using FirebaseFunctions (2.1.1)
Using FirebaseInstanceID (3.3.0)
Using FirebaseUI (5.2.2)
Using GTMSessionFetcher (1.2.0)
Using GoogleAppMeasurement (5.3.0)
Using GoogleUtilities (5.3.4)
```

**Comment by AndriyGo** [comment] 2018-11-19 16:09
@morganchen12 the leaks are still there after latest releases (and #2061 fix)

<img width="1396" alt="screenshot 2018-11-19 at 18 07 29" src="https://user-images.githubusercontent.com/7107815/48719432-29437800-ec26-11e8-964f-4a9f182fffa6.png">

Setup:

```
Using Firebase (5.12.0)
Using FirebaseAnalytics (5.3.0)
Using FirebaseAnalyticsInterop (1.1.0)
Using FirebaseAuth (5.0.5)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.1.7)
Using FirebaseDynamicLinks (3.1.1)
Using FirebaseFunctions (2.1.1)
Using FirebaseInstanceID (3.3.0)
Using FirebaseUI (5.2.2)
Using GTMSessionFetcher (1.2.0)
Using GoogleAppMeasurement (5.3.0)
Using GoogleUtilities (5.3.6)
```

**Comment by RamblinWreck77** [comment] 2018-11-19 18:54
@AndriyGo can confirm, I'm seeing these as well

**Comment by morganchen12** [comment] 2018-11-20 03:16
I was previously able to reproduce this by just logging a bunch of Analytics events, but the last patch made those go away. How are you two reproducing this issue?

**Comment by AndriyGo** [comment] 2018-12-10 18:05
@morganchen12 

I can't reproduce it now. Don't know what has changed. If it resurfaces I will let you know how it can be reproduced.

**Comment by morganchen12** [comment] 2018-12-10 18:18
Thanks @AndriyGo. I'll close this issue for now, but please comment if it resurfaces again.

**Closed by morganchen12** 2018-12-10 18:18 UTC
Labels: GoogleUtilities

**Comment by Manidevlop** [comment] 2019-10-07 12:55
Hi, Even I'm also getting the same leak in firebase config

import Firebase & FIRApp.configure() in didFinishLaunchingWithOptions in app delegate.



![Screenshot 2019-10-07 at 6 23 07 PM](https://user-images.githubusercontent.com/32291332/66313263-b6bbb380-e92f-11e9-82c7-536dbe8ef50b.png)
![Screenshot 2019-10-07 at 6 23 43 PM](https://user-images.githubusercontent.com/32291332/66313265-b7544a00-e92f-11e9-982d-79e617d19a46.png)

If I remove the import FIRApp.configure(), it's fine.

 I'm using firebase version:
Using Firebase (5.10.0)
Using FirebaseAnalytics (5.2.0)
Using FirebaseAnalyticsInterop (1.1.0)
Using FirebaseCore (5.1.5)
Using FirebaseDynamicLinks (3.1.0)
Using FirebaseInstanceID (3.2.2)
Using FirebaseMessaging (3.2.0)
Using GoogleUtilities (5.3.4)

**Comment by paulb777** [comment] 2019-10-07 13:23
@Manidevlop Please upgrade to Firebase 6.x

**Comment by Manidevlop** [comment] 2019-10-10 09:46
Okay, I will upgrade and check it. 

Thank you
