### ISSUE TITLE
[Crashlytics] Xcode16 beta build with debug mode missing dSYM

### ISSUE THREAD

**Issue by flexund** [firebase/firebase-ios-sdk#13543] opened 2024-08-26 10:00 UTC
### Description

When building application with `Debug` mode on Xcode16, dSYM fails to upload to Crashlytics. 

This is related to https://github.com/firebase/firebase-ios-sdk/issues/13202

Workaround is to disable `Debug Dylib Support` in target Build settings. But this causes SwiftUI previews to not work.

### Reproducing the issue

- Set ENABLE_DEBUG_DYLIB=YES for build options
- Build application for debug mode in Xcode 16

### Firebase SDK Version

11.1.0

### Xcode Version

16.0 Beta 6

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Osein** [comment] 2024-09-03 13:26
I solved this by setting ENABLE_DEBUG_DYLIB to false. Crashlytics upload dsym successfully but it makes preview go kaput

<img width="497" alt="image" src="https://github.com/user-attachments/assets/95f9213d-3d10-4bc1-adaf-777492d0bfca">

**Comment by themiswang** [comment] 2024-09-05 18:24
Seems like Apple changed their dSYM content a bit again, will work on a fix. Meanwhile another work around is uploading the dSYM through web uploader.

**Comment by 4eleven7** [comment] 2024-09-23 20:11
Is there any update on this?

**Comment by jerald-dexcom** [comment] 2024-09-25 02:33
I would like to know if there is any update to this as well. ENABLE_DEBUG_DYLIB to false is the only solution for me for Crashlytics to work.

**Comment by benfrearson** [comment] 2024-09-25 05:44
As above, `ENABLE_DEBUG_DYLIB` is the only solution for me too. Manually uploading dylibs is not particularly feasible when rapid prototyping and using CI/CD. 

Would be good to know if there's a fix on the way!

**Comment by themiswang** [comment] 2024-09-25 18:56
Hey folks,

Thank you for reaching out, I am working on the fix now. This fix need a refactor work in script so we need to do a thoroughly regression test which might take more time. Tl;dr the fix need to make `upload-symbols` to support upload multiple DWARF contents within the same dSYM bundle which currently `upload-symbols` does not support. We likely gonna miss the code freeze for the upcoming release version. But as soon as we finished testing and I'll post the artifact in the issue as a workaround before we having official release.

**Comment by vhartikainen** [comment] 2024-09-26 07:43
> * Set ENABLE_DEBUG_DYLIB=YES for build options
> * Build application for debug mode in Xcode 16

This seems to do the trick for me too. 
* Xcode Version 16.0 (16A242d)

Processing of new dSYMs seem to take rather long on Google's side - after upload complete, it takes 5-10minutes before the events start to appear. Is this normal? 

This makes fast iteration and testing really hard and prone to make wrong conclusions what works and what not.

**Comment by jerald-dexcom** [comment] 2024-09-26 19:09
Thank you @themiswang ,
Do you have any ETA for the release that will have this fix?

**Comment by murad1981** [comment] 2024-10-01 18:04
I'm still facing the issue after updating to `11.3.0`

**Comment by themiswang** [comment] 2024-10-02 19:53
Hey folks,

I have merged the change for upload-symbols in this PR(https://github.com/firebase/firebase-ios-sdk/pull/13760), we are expected this change will be in the next Firebase release for version `11.4.0` and release date will be on Oct 21, 2024. We would love to get your early feedback, so we're sharing the pre-release artifact [upload-symbols.zip](https://github.com/user-attachments/files/17235176/upload-symbols.zip) early for anyone who would like to try it out.

If you are using CocoaPods, you can override the upload-symbols executable to the new one under `$PODS_ROOT/FirebaseCrashlytics/upload-symbols`

For SPM, you can put `upload-symbols` and `run.sh` in a convenient place and then change the path to the new place for your upload symbols build phase.

**Comment by benfrearson** [comment] 2024-10-03 04:52
Thanks @themiswang for fixing and keeping us updated 👍🏻

**Comment by NigamAnkit** [comment] 2024-10-03 05:44
<img width="719" alt="Screenshot 2024-10-03 at 11 13 16 AM" src="https://github.com/user-attachments/assets/8fcb3505-7701-4a76-a220-3dd53911a29d">

I get it while validating the release build from Xcode 16.
How to get rid of these warnings ?

**Comment by themiswang** [comment] 2024-10-03 14:11
Hey @NigamAnkit, @lirbar,  

The warning actually related to #13551, it is a different issue which relate to how package is getting build. I would suggest follow up with that issue, thank you!

**Comment by kimliss** [comment] 2024-10-08 07:11
> <img alt="Screenshot 2024-10-03 at 11 13 16 AM" width="719" src="https://private-user-images.githubusercontent.com/32325505/373131425-8fcb3505-7701-4a76-a220-3dd53911a29d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTQ4MDEsIm5iZiI6MTcyODM1NDUwMSwicGF0aCI6Ii8zMjMyNTUwNS8zNzMxMzE0MjUtOGZjYjM1MDUtNzcwMS00YTc2LWEyMjAtM2RkNTM5MTFhMjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMjgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYjE0ZjY4OGY0MDlmMzBhNjE4Nzc5ZDNjZDcxZWYyYzJiMGNiZDEzYzI1YTU5Y2M2NGRmNTBkYjU0NDQzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kewrKBdWFodfG3wclbGTXxQQqpCoSvmElHoumBPwgvM">
> I get it while validating the release build from Xcode 16. How to get rid of these warnings ?

Does your Firebase Analytics dashboard contain user data?

**Comment by yigiteryelkovan** [comment] 2024-10-08 08:12
Hello everyone,

I encountered the same issue and needed to urgently release an update to the App Store due to a change in my application's API endpoint. To address this temporarily, I found the following solution:

I downgraded Xcode to version 15.4, which allowed my project to successfully build without validation errors, and I was able to release my update.
[How can I run older Xcode version on new macOS version?](https://stackoverflow.com/questions/69994916/how-can-i-run-older-xcode-version-on-new-macos-version/69995053#69995053) for more details. 

This may not be a permanent solution, but it could be helpful if you need to quickly push an update.

**Comment by SuryakantRapido** [comment] 2024-10-15 10:17
Any ETA for fix ??

**Closed** 2024-10-15 14:18 UTC
Labels: api: crashlytics, Xcode 16 - iOS 18

**Comment by JaskiratSinghGFG** [comment] 2024-10-22 06:22
Is someone else still facing the issue after 11.4.0 too?

**Comment by VValiente** [comment] 2024-10-23 10:09
@paulb777, @themiswang, I've updated to 11.4.0 but dSYM still fails to upload to Crashlytics. And I still see this warning in Xcode's console:
<img width="594" alt="Screenshot 2024-10-23 at 16 52 18" src="https://github.com/user-attachments/assets/cf4326b2-e34c-42b9-8172-edfc86330201">

I'm still using the recommended configurations as per your Crashlytics documentation. Does 11.4.0 require changes? If yes, which ones?

Also, ever since I integrated Firebase SDK to use Analytics and Crashlytics, all previews stopped working due to AppLaunchTimeoutError. I'm on Xcode 16. I will try to remove Firebase SDK to verify.

**Comment by sebastienL** [comment] 2024-10-23 15:02
Hey,

I updated to 11.4.0 and I have this error which: `/Users/....xcodeproj Missing package product 'FirebaseRemoteConfigSwift'`

Any idea?

thx

**Comment by paulb777** [comment] 2024-10-23 15:07
FirebaseRemoteConfigSwift should be removed. It was merged into FirebaseRemoteConfig.

**Comment by lluisgerard** [comment] 2024-10-24 08:51
I updated to 11.4.0, I have ENABLE_DEBUG_DYLIB set to true and every time I run the app on the simulator my team gets an email warning them. I had to disable the script on development as someone else suggested.

**Comment by porsalud-source** [comment] 2024-10-24 21:22
> <img alt="Screenshot 2024-10-03 at 11 13 16 AM" width="719" src="https://private-user-images.githubusercontent.com/32325505/373131425-8fcb3505-7701-4a76-a220-3dd53911a29d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDQ1MTksIm5iZiI6MTcyOTgwNDIxOSwicGF0aCI6Ii8zMjMyNTUwNS8zNzMxMzE0MjUtOGZjYjM1MDUtNzcwMS00YTc2LWEyMjAtM2RkNTM5MTFhMjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDIxMTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYjNjYjE2NjE5Y2E4OTAyOTI4ZTdjMzg1MmFlODYzYmVhZDI2NmVkZjA4Y2M4N2M4YWE3ZDE0ZmZlMzkzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ajUlxVB6zNsAy5vaJjD0vvKdDpmZksHTgVlWB2qi1o4">
> I get it while validating the release build from Xcode 16. How to get rid of these warnings ?

Any ETA on this that may help!? I'm having the same issue right now.

**Comment by jfrazzle123** [comment] 2024-10-25 19:00
Any update on this?  I am still having this issue.

**Comment by rawmean** [comment] 2024-10-25 22:26
Is this going to cause an App Review rejection? What happens if we ignore this warning?
The issue still exists in 11.4 as others pointed out.

**Comment by porsalud-source** [comment] 2024-10-25 22:33
> Is this going to cause an App Review rejection? What happens if we ignore this warning? The issue still exists in 11.4 as others pointed out.

If it helps to you, I already Validated and Distributed my app to Appstore. So far they haven't say anything about it. I don't think that warnings may cause your app to be rejected. (Warnings, not Errors)

**Comment by kennywyland** [comment] 2024-10-25 22:54
> Is this going to cause an App Review rejection? What happens if we ignore this warning? The issue still exists in 11.4 as others pointed out.

I was able to submit an app that had the warning and my submission was approved, FYI.

**Comment by JaskiratSinghGFG** [comment] 2024-10-28 05:42
The submission is getting approved but the warnings are still coming even after updating to 11.4.0.
@paulb777 Any update/ETA on this?

**Comment by rbmstudios** [comment] 2024-10-28 13:21
I submitted a version of our app with these warnings and now Google Analytics is showing no data. All of our users who updated to the new version are now not showing. Does the workaround fix this issue??
