### ISSUE TITLE
Swift Package depdendecies

### ISSUE THREAD

**Issue by jayakrishnan-Span** [firebase/firebase-ios-sdk#4929] opened 2020-02-19 14:03 UTC
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.1_____
  * Firebase SDK version: 6.17.0_____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____
  * Installation method: Swift Package Dependencies

### [REQUIRED] Step 2: Describe the problem
 https://github.com/firebase/firebase-ios-sdk.git has no Package.swift manifest for version 6.17.0
#### Steps to reproduce:
Add the swift package dependencies from file -> swift Package -> Add Package Dependency -> Select Project and paste the git url ->  **https://github.com/firebase/firebase-ios-sdk.git** 

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
![Screenshot 2020-02-19 at 7 32 56 PM](https://user-images.githubusercontent.com/46318390/74841431-b2c48700-534e-11ea-89e7-a8ff760260c7.png)
![Screenshot 2020-02-19 at 7 32 56 PM](https://user-images.githubusercontent.com/46318390/74841473-c07a0c80-534e-11ea-9c8a-1a7fee20e2f9.png)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rizafran** [comment] 2020-02-19 14:17
Hi @jayakrishnan-Span, Swift Package is currently unsupported. You may refer to this issue #3136.

**Comment by paulb777** [comment] 2020-02-19 15:15
Closing as duplicate of #3136

**Closed by paulb777** 2020-02-19 15:15 UTC
Labels: Infrastructure
