### ISSUE TITLE
Mac APPS upgraded from Fabric to FirebaseCashkit, but a problem accessing a private folder in keychain was found in the new Mac system (10.15.5)! Cannot receive report when user is denied access!! This was not the case at Fabric before!

### ISSUE THREAD

**Issue by dingmriesgui** [firebase/firebase-ios-sdk#6289] opened 2020-08-18 07:58 UTC
[REQUIRED] Step 1: Describe your environment

Xcode version: 11.6
Firebase SDK version: See below. Podfile just specifies unversioned Firebase/Crashlytics and Firebase/Analytics
Component version: See above
Installation method: CocoaPods
`
    pod 'FirebaseCore'
    pod 'Firebase/Crashlytics'
    pod 'FirebaseInstallations'
`
[REQUIRED] Step 2: Describe the problem

Steps to reproduce:

This is for a macOS application, running on macOS 10.15.5.
In applicationDidFinishLaunching, I have simply:
`[FIRApp configure]     
`
Upon launch I then see this:
<img width="427" alt="截屏2020-08-18 3 36 12 PM" src="https://user-images.githubusercontent.com/42464856/90486265-4b578a80-e16b-11ea-8375-cf6965a73303.png">
Click OK and an access permission prompt will pop up!
<img width="431" alt="截屏2020-08-18 3 36 31 PM" src="https://user-images.githubusercontent.com/42464856/90486277-4e527b00-e16b-11ea-87ac-2143f542d052.png">

In my opinion, when The Fabric framework was used in the past, this kind of prompt did not pop up. In my opinion, it is unreasonable to pop up this kind of prompt inexplicably, which will not be allowed for many operation users! Same problem with #[5540](https://github.com/firebase/firebase-ios-sdk/issues/5540) feedback！

**Comment by ryanwilson** [comment] 2020-08-18 12:33
Thanks for the report - you're right it does look like #5540 but based on the comments in the thread it could have been fixed by an update (unless I'm reading it incorrectly, I wasn't involved too closely with the original issue). 

Can you please share your `Podfile.lock` so we can see which versions are being installed? Also, can you answer the questions from [this comment[(https://github.com/firebase/firebase-ios-sdk/issues/5540#issuecomment-625279873) here so we have further context?

**Comment by morganchen12** [comment] 2020-08-18 16:18
Duplicate of #6141

**Closed by morganchen12** 2020-08-18 16:18 UTC
Labels: api: crashlytics, api: installations, macOS, needs-info

**Comment by dingmriesgui** [comment] 2020-08-19 07:26
> Thanks for the report - you're right it does look like #5540 but based on the comments in the thread it could have been fixed by an update (unless I'm reading it incorrectly, I wasn't involved too closely with the original issue).
> 
> Can you please share your `Podfile.lock` so we can see which versions are being installed? Also, can you answer the questions from [this comment](https://github.com/firebase/firebase-ios-sdk/issues/5540#issuecomment-625279873) here so we have further context?



> Thanks for the report - you're right it does look like #5540 but based on the comments in the thread it could have been fixed by an update (unless I'm reading it incorrectly, I wasn't involved too closely with the original issue).
> 
> Can you please share your `Podfile.lock` so we can see which versions are being installed? Also, can you answer the questions from [this comment](https://github.com/firebase/firebase-ios-sdk/issues/5540#issuecomment-625279873) here so we have further context?

So there is no way to deal with it?
