### ISSUE TITLE
[BackgroundTask] Background Task 1001 ("GDTStorage"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

### ISSUE THREAD

**Issue by xabodog** [firebase/firebase-ios-sdk#8908] opened 2021-11-02 06:36 UTC
[BackgroundTask] Background Task 1001 ("GDTStorage"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by paulb777** [comment] 2021-11-02 14:21
This looks like a duplicate of #6937.  Please make sure you on are on a recent version and fill out the issue template including the Firebase versions used.

**Closed** 2021-11-15 02:03 UTC
Labels: needs-info, no-recent-activity, GoogleDataTransport
