### ISSUE TITLE
GoogleDataTransportCCTSupport Group Lexical or Preprocessor Issue

### ISSUE THREAD

**Issue by sir-argupta** [firebase/firebase-ios-sdk#6763] opened 2020-10-18 18:38 UTC
### Step 0: Are you in the right place?
Yes
  

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: FBSDKCoreKit (7.0.1)  
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage)
  * Component version: _____
  * Installation method: CocoaPods 

### [REQUIRED] Step 2: Describe the problem
I have a simple Xcode project with some Pods (related to Google Firebase) already installed. Everything with these is working perfectly fine. **However, any attempts to install any additional Pods is resulting in the Xcode project failing to compile.**
I'm providing examples of this below. Please note that  pod below are failing with the same error:-

GoogleDataTransportCCTSupport Group
Lexical or Preprocessor Issue Group
/Pods/Target Support Files/nanopb/nanopb-umbrella.h:13:9: Double-quoted include "pb.h" in framework header, expected angle-bracketed instead

/Pods/Target Support Files/nanopb/nanopb-umbrella.h:14:9: Double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead#### Steps to reproduce:

What happened? How can we make the problem occur?
Any attempt to install new pod causing build to fail due to GoogleDataTransportCCTSupport Group Lexical or Preprocessor Issue.
Please Help..

![Screenshot 2020-10-19 at 12 05 00 AM](https://user-images.githubusercontent.com/21137415/96376815-c1de2c00-119e-11eb-8ee0-8f03feba3d78.png)
![Screenshot 2020-10-19 at 12 07 12 AM](https://user-images.githubusercontent.com/21137415/96376869-0e296c00-119f-11eb-8be8-3feb6c2ed29e.png)

#### Relevant Code:
my pod.lock file
```
PODS:
  - Alamofire (5.2.1)
  - ContentLoader (1.1.1)
  - DSGradientProgressView (1.0.1)
  - FBSDKCoreKit (7.0.1):
    - FBSDKCoreKit/Basics (= 7.0.1)
    - FBSDKCoreKit/Core (= 7.0.1)
  - FBSDKCoreKit/Basics (7.0.1)
  - FBSDKCoreKit/Core (7.0.1):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (7.0.1):
    - FBSDKLoginKit/Login (= 7.0.1)
  - FBSDKLoginKit/Login (7.0.1):
    - FBSDKCoreKit (~> 7.0.1)
  - FirebaseAuth (6.6.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (6.8.0):
    - FirebaseCoreDiagnostics (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.4.0):
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseDatabase (6.3.0):
    - FirebaseCore (~> 6.8)
    - leveldb-library (~> 1.22)
  - FirebaseInstallations (1.4.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.4.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
  - FirebaseMessaging (4.5.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Reachability (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseStorage (3.7.0):
    - FirebaseCore (~> 6.8)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleDataTransport (6.2.1)
  - GoogleDataTransportCCTSupport (3.2.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.4.0)
  - GTProgressBar (0.3.3)
  - IQKeyboardManagerSwift (6.5.5)
  - JJFloatingActionButton (2.5.0)
  - JSQMessagesViewController (7.3.5):
    - JSQSystemSoundPlayer (~> 2.0.1)
  - JSQSystemSoundPlayer (2.0.1)
  - Kingfisher (5.14.0):
    - Kingfisher/Core (= 5.14.0)
  - Kingfisher/Core (5.14.0)
  - leveldb-library (1.22)
  - MarqueeLabel (4.0.2)
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - NextLevel (0.16.3)
  - PromisesObjC (1.2.9)
  - Protobuf (3.12.0)
  - PryntTrimmerView (4.0.0)
  - Regift (1.5.0)
  - SDWebImage (5.8.1):
    - SDWebImage/Core (= 5.8.1)
  - SDWebImage/Core (5.8.1)
  - SteviaLayout (4.7.3)
  - YPImagePicker (4.2.1):
    - PryntTrimmerView (~> 4.0.0)
    - SteviaLayout (~> 4.7.3)

DEPENDENCIES:
  - Alamofire
  - ContentLoader
  - DSGradientProgressView
  - FBSDKLoginKit
  - FirebaseAuth
  - FirebaseCore
  - FirebaseDatabase
  - FirebaseMessaging
  - FirebaseStorage
  - GTProgressBar
  - IQKeyboardManagerSwift
  - JJFloatingActionButton
  - JSQMessagesViewController
  - Kingfisher
  - MarqueeLabel
  - NextLevel
  - Regift
  - SDWebImage
  - YPImagePicker

SPEC REPOS:
  trunk:
    - Alamofire
    - ContentLoader
    - DSGradientProgressView
    - FBSDKCoreKit
    - FBSDKLoginKit
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseDatabase
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebaseStorage
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleUtilities
    - GTMSessionFetcher
    - GTProgressBar
    - IQKeyboardManagerSwift
    - JJFloatingActionButton
    - JSQMessagesViewController
    - JSQSystemSoundPlayer
    - Kingfisher
    - leveldb-library
    - MarqueeLabel
    - nanopb
    - NextLevel
    - PromisesObjC
    - Protobuf
    - PryntTrimmerView
    - Regift
    - SDWebImage
    - SteviaLayout
    - YPImagePicker

SPEC CHECKSUMS:
  Alamofire: e911732990610fe89af59ac0077f923d72dc3dfd
  ContentLoader: b14db4449065be0fd2b8c77b65ff5e4a0a8c7f86
  DSGradientProgressView: 256d85dc3a92b429ace38617ceb459faec42bb41
  FBSDKCoreKit: 9cc05bec0568a5955c82eb59ae95da0fe125b88d
  FBSDKLoginKit: ecc6fd43c81b60f5b5e9388d58f137aff4a5d00b
  FirebaseAuth: b85c064e0ac60f82486728d50a4803f235687302
  FirebaseCore: feda061cb1ee6d8ad4824f4a4a8ffbcfe284f595
  FirebaseCoreDiagnostics: 4505e4d4009b1d93f605088ee7d7764d5f0d1c84
  FirebaseDatabase: 3d02ffa794ec174853c086cf87cf2dc79bd6da49
  FirebaseInstallations: 293f567159b6d66d1c990f13bb868066096c94ec
  FirebaseInstanceID: 3b119bfe90e904851218159c9a4ecb847cc51d18
  FirebaseMessaging: ad9e1a80ea64905e01a0ce1b3eb76a2944544151
  FirebaseStorage: af7bdbd12177cf567df00904e3e3a93704f25b15
  GoogleDataTransport: 9a8a16f79feffc7f42096743de2a7c4815e84020
  GoogleDataTransportCCTSupport: 489c1265d2c85b68187a83a911913d190012158d
  GoogleUtilities: 39530bc0ad980530298e9c4af8549e991fd033b1
  GTMSessionFetcher: 6f5c8abbab8a9bce4bb3f057e317728ec6182b10
  GTProgressBar: a480283ecb0ada50de16c71e634892826928f640
  IQKeyboardManagerSwift: 0fb93310284665245591f50f7a5e38de615960b7
  JJFloatingActionButton: fdc3aefb0f28f04d0f988fa25d5fac97028a9ea7
  JSQMessagesViewController: 6587f56aedbcb150a8ba1d968e1ef58b1bc758b7
  JSQSystemSoundPlayer: c5850e77a4363ffd374cd851154b9af93264ed8d
  Kingfisher: 7b64389a43139c903ec434788344c288217c792d
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  MarqueeLabel: f762aa681ae201f66c1d511858b171f75d83013a
  nanopb: c43f40fadfe79e8b8db116583945847910cbabc9
  NextLevel: 76dab336f758e6a98ef6b4917de1481324cffe04
  PromisesObjC: b48e0338dbbac2207e611750777895f7a5811b75
  Protobuf: 2793fcd0622a00b546c60e7cbbcc493e043e9bb9
  PryntTrimmerView: 67e67573ffd4c073f1308effa66aefd0cfa667a0
  Regift: d097afd401021f4f42b102ee125ceeb125a38caf
  SDWebImage: e3eae2eda88578db0685a0c88597fdadd9433f05
  SteviaLayout: c2ecdcff57d44e38fd2f65e54ad52aeae28ca0c4
  YPImagePicker: 3b88ca0c50134af2856c48c481572c98a8b8b65b

PODFILE CHECKSUM: f84298497f338c540cb40682b8baeafe55c98d10

COCOAPODS: 1.9.3
```

my pod file
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TIK TIK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TIK TIK
  pod "NextLevel"
  pod 'JJFloatingActionButton'
  pod 'SDWebImage'
  pod 'DSGradientProgressView'
  pod 'IQKeyboardManagerSwift'
  pod "Regift"
  pod 'YPImagePicker'
  pod 'FirebaseCore'
  pod 'FirebaseStorage'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseMessaging'
  pod 'MarqueeLabel'
  pod 'FBSDKLoginKit'
  pod 'Alamofire'
  pod 'ContentLoader'
  pod 'JSQMessagesViewController'
  pod 'Kingfisher'
  pod "GTProgressBar"
  
  target 'TIK TIKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end```

**Comment by paulb777** [comment] 2020-10-18 18:42
This is a duplicate of #5987 and #6484. See the resolutions there and https://stackoverflow.com/questions/63646607/xcode-12-using-firebase-pods-lexical-or-preprocessor-issue-pb-h-file-not-fou/63648164#63648164

**Closed by paulb777** 2020-10-18 18:42 UTC
Labels: api: auth

**Comment by sir-argupta** [comment] 2020-10-18 18:50
thanks @paulb777 for help
