### ISSUE TITLE
Auth Facebook API tests failing on travis

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#2543] opened 2019-03-13 14:29 UTC
The following tests started failing on travis yesterday.

Since they started failing after a changelog commit, I suspect a server issue, but it should be investigated.

	-[FacebookAuthTests testLinkAnonymousAccountToFacebookAccount]
	-[FacebookAuthTests testLinkAnonymousAccountToFacebookAccount]
	-[FacebookAuthTests testLinkAnonymousAccountToFacebookAccount]
	-[FacebookAuthTests testSignInWithFaceboook]
	-[FacebookAuthTests testSignInWithFaceboook]
	-[FacebookAuthTests testSignInWithFaceboook]

from https://travis-ci.org/firebase/firebase-ios-sdk/jobs/505770480

**Comment by renkelvin** [comment] 2019-03-13 18:41
Facebook related tests failed due to (highly possibly) https://developers.facebook.com/status/issues/559896447845433/
Temporarily disable the tests.

https://github.com/firebase/firebase-ios-sdk/pull/2547

**Comment by ryanwilson** [comment] 2019-03-14 12:44
i imagine this has to do with the [global Facebook outage](https://twitter.com/facebook/status/1105888649676111877).

**Comment by ryanwilson** [comment] 2019-03-15 17:46
This was resolved. Can we roll back #2547?

**Comment by renkelvin** [comment] 2019-03-15 18:01
Yeah, thanks for reminding! https://github.com/firebase/firebase-ios-sdk/pull/2566

**Comment by paulb777** [comment] 2019-03-20 14:07
Reopened since the rollback was reverted.

**Comment by renkelvin** [comment] 2019-03-20 17:47
Yeah, according to my investigation, there is still issue on Facebook side. Will reenable the tests when the issue is fixed.

**Comment by ryanwilson** [comment] 2019-03-22 03:43
Sorry about that, thought it was resolved!

**Comment by renkelvin** [comment] 2019-03-25 17:51
Issue fixed on Facebook side. Revert again https://github.com/firebase/firebase-ios-sdk/pull/2628

**Closed** 2019-03-26 20:19 UTC
Labels: api: auth
