### ISSUE TITLE
upload-symbols script stalls indefinitely

### ISSUE THREAD

**Issue by matkavt** [firebase/firebase-ios-sdk#11159] opened 2023-04-21 14:24 UTC
### Description

We have been receiving emails where Crashlytics detects a missing Dsym
![telegram-cloud-photo-size-2-5339062455860578432-y](https://user-images.githubusercontent.com/18314027/233660855-25d36d92-3657-4893-9e43-3dab840b9d69.jpg)

Some investigation lead to the Crashlytics/run and upload-symbols scripts
Specifically the upload-symbols appears to stall for some reason.
We tried to obtain some logs by passing the --debug flag, however nothing relevant came by because the Crashlytics/run script works correctly and the upload-symbols script is silenced even with the --debug parameter
We also tried to run the upload-symbols script synchronously and get some output out of it. It appears to be working correctly (I mean no signs of malfunction in the output), however it may stall and block th whole building stage (since we tried to run it synchronously)
Additionally I managed to notice that the upload-symbols script can pile up in the process list confirming that it stalls in the background
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/18314027/233658330-b885561e-85c6-4441-bb98-1c3c656b6dea.png">

### Reproducing the issue

We noticed that this issue appears from time to time.

Most of the time it appears after changing the git branch or cleaning the project, howewer we are not entirely sure how to reproduce it.
It appears on every of three macbooks our team has.
Personally I am now using Xcode Version 14.3 (14E222b) and Firbase 10.8.1 via SPM

### Firebase SDK Version

10.8.1

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Showing Recent Messages
upload-symbols 3.14 build 33

Running upload-symbols in Build Phase mode

Validating build environment for Crashlytics...



Arguments:

Debug mode enabled

Google App ID: 1:46191884389:ios:e9474eda94335a797f2e8c

Platform: ios

DSYM Paths: ["/Users/matveykavtorov/Library/Developer/Xcode/DerivedData/HSEAppX-fshwmsuctpgxjnevrkvlbqyvvpuu/Build/Products/Debug-iphonesimulator/HSE App X.app.dSYM"]



Validation succeeded. Symbol uploading will proceed in the background.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "object": {
    "pins": [
      {
        "package": "abseil",
        "repositoryURL": "https://github.com/google/abseil-cpp-binary.git",
        "state": {
          "branch": null,
          "revision": "a5f16ba68913840ee5df91b8dc06f5cc063579de",
          "version": "1.2021110200.0"
        }
      },
      {
        "package": "Alamofire",
        "repositoryURL": "https://github.com/Alamofire/Alamofire.git",
        "state": {
          "branch": null,
          "revision": "78424be314842833c04bc3bef5b72e85fff99204",
          "version": "5.6.4"
        }
      },
      {
        "package": "CodableWrappers",
        "repositoryURL": "https://github.com/GottaGetSwifty/CodableWrappers.git",
        "state": {
          "branch": null,
          "revision": "4eb46a4c656333e8514db8aad204445741de7d40",
          "version": "2.0.7"
        }
      },
      {
        "package": "Firebase",
        "repositoryURL": "https://github.com/firebase/firebase-ios-sdk.git",
        "state": {
          "branch": null,
          "revision": "ee016a6774edca5ffc50c39855783d1add6ca0fc",
          "version": "10.8.1"
        }
      },
      {
        "package": "GoogleAppMeasurement",
        "repositoryURL": "https://github.com/google/GoogleAppMeasurement.git",
        "state": {
          "branch": null,
          "revision": "274428b83e063cd518b998555be0ec18abcbe9de",
          "version": "10.8.0"
        }
      },
      {
        "package": "GoogleDataTransport",
        "repositoryURL": "https://github.com/google/GoogleDataTransport.git",
        "state": {
          "branch": null,
          "revision": "cc7265b8e3906304e6e81f32c1662a94bbae2357",
          "version": "9.2.2"
        }
      },
      {
        "package": "GoogleUtilities",
        "repositoryURL": "https://github.com/google/GoogleUtilities.git",
        "state": {
          "branch": null,
          "revision": "871d43135925cde39ef7421d8723ce47edfdcc39",
          "version": "7.11.1"
        }
      },
      {
        "package": "gRPC",
        "repositoryURL": "https://github.com/google/grpc-binary.git",
        "state": {
          "branch": null,
          "revision": "df37f6af8a273bc687e3166843ed86007de57d78",
          "version": "1.44.0"
        }
      },
      {
        "package": "GTMSessionFetcher",
        "repositoryURL": "https://github.com/google/gtm-session-fetcher.git",
        "state": {
          "branch": null,
          "revision": "96d7cc73a71ce950723aa3c50ce4fb275ae180b8",
          "version": "3.1.0"
        }
      },
      {
        "package": "HSEDatePicker",
        "repositoryURL": "https://github.com/hseapp/HSEDatePicker",
        "state": {
          "branch": null,
          "revision": "52cbf626db13943e79c8d9bd0ffe4e531f9f7597",
          "version": "1.0.2"
        }
      },
      {
        "package": "Ink",
        "repositoryURL": "https://github.com/johnsundell/ink.git",
        "state": {
          "branch": null,
          "revision": "bcc9f219900a62c4210e6db726035d7f03ae757b",
          "version": "0.6.0"
        }
      },
      {
        "package": "JWTDecode",
        "repositoryURL": "https://github.com/auth0/JWTDecode.swift.git",
        "state": {
          "branch": null,
          "revision": "7918a343e674c7707e0be120bb4e21d679be014c",
          "version": "3.0.1"
        }
      },
      {
        "package": "leveldb",
        "repositoryURL": "https://github.com/firebase/leveldb.git",
        "state": {
          "branch": null,
          "revision": "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
          "version": "1.22.2"
        }
      },
      {
        "package": "nanopb",
        "repositoryURL": "https://github.com/firebase/nanopb.git",
        "state": {
          "branch": null,
          "revision": "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
          "version": "2.30909.0"
        }
      },
      {
        "package": "PhoneNumberKit",
        "repositoryURL": "https://github.com/marmelroy/PhoneNumberKit.git",
        "state": {
          "branch": null,
          "revision": "9b051490589ae4f2fa861287407a43a87be7226c",
          "version": "3.5.8"
        }
      },
      {
        "package": "Promises",
        "repositoryURL": "https://github.com/google/promises.git",
        "state": {
          "branch": null,
          "revision": "ec957ccddbcc710ccc64c9dcbd4c7006fcf8b73a",
          "version": "2.2.0"
        }
      },
      {
        "package": "SwiftProtobuf",
        "repositoryURL": "https://github.com/apple/swift-protobuf.git",
        "state": {
          "branch": null,
          "revision": "0af9125c4eae12a4973fb66574c53a54962a9e1e",
          "version": "1.21.0"
        }
      },
      {
        "package": "SwiftKeychainWrapper",
        "repositoryURL": "https://github.com/jrendel/SwiftKeychainWrapper",
        "state": {
          "branch": null,
          "revision": "185a3165346a03767101c4f62e9a545a0fe0530f",
          "version": "4.0.1"
        }
      }
    ]
  },
  "version": 1
}


```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ls-bertrand-landry-hetu** [comment] 2023-04-26 16:14
I'm having the same issue. I'm not sure if it's intermittent as we have had the issue in our last 2 releases. I believe it started once we updated to FB `10.7.0`. Maybe a regression caused by https://github.com/firebase/firebase-ios-sdk/pull/10936 ?

**Comment by samedson** [comment] 2023-04-27 18:14
I'm wondering if this still happens on upload-symbols associated with Firebase 10.0.0? Would you try using the upload-symbols at this version and see if you still get stalls? 

https://github.com/firebase/firebase-ios-sdk/tree/release-10.0/Crashlytics

**Comment by immi-sipgate** [comment] 2023-05-10 11:22
any updates regarding this issue??
Since we are using 10.8.0 the dsym files are not appearing in crashlytics.

**Comment by matkavt** [comment] 2023-05-15 11:20
> I'm wondering if this still happens on upload-symbols associated with Firebase 10.0.0? Would you try using the upload-symbols at this version and see if you still get stalls?
> 
> https://github.com/firebase/firebase-ios-sdk/tree/release-10.0/Crashlytics

We have been using 10.0 for a week now and I think it helped. We can use it for a while but I hope that this issue would be resolved in upcoming releases

**Comment by immi-sipgate** [comment] 2023-05-17 07:54
@matkavt for us 10.0 is not a possibility because we depend on a fix regarding firestore (symbol collision) which was introduced in version 10.8

see: https://github.com/firebase/firebase-ios-sdk/issues/6869

**Comment by thecael** [comment] 2023-05-19 07:10
Can I help you with additional information to resolve the issue?
It seems that the latest Firebase SDK makes the dSYM symbol unusable for firebase, I also tried to upload them via web interface. Unfortunately, there is no debug feedback in the UI indicating what went wrong with Firebase's processing of the dSYMs 😞 

CLI and Webinterface don't complain but it's still indicating as "Required" / missing

**Comment by thecael** [comment] 2023-06-05 07:47
Is there any update on this issue? Unfortunately we still can not use Crashlytics :-/

**Comment by immi-sipgate** [comment] 2023-06-12 08:09
Please update on this issue. We don't have any dsyms on crashlytics!

**Comment by themiswang** [comment] 2023-06-13 19:40
Hey folks,

Wonder if you are sandboxing the application or set `user script sandboxing = true` for you build option. 
<img width="615" alt="Screenshot 2023-06-13 at 3 28 00 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/16548721/c0dad541-e615-41da-898a-307cc12926e9">

I have run into this issue when I turn this build option on XCode 14.1 and the sample the process gives me this:
<img width="1297" alt="Screenshot 2023-06-13 at 3 30 00 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/16548721/df793339-308c-42dd-9052-9bcd27874eb2">

I am assuming this is the behind logic, when running the application in sandbox and it need to access to some OS-mediated permissions, those need to be done through this `LaunchServices` instead of running in shell. By setting `user script sandboxing` back to False I have no problem to run the upload symbols in build phase. Can folks give a try? Thanks!

**Comment by matkavt** [comment] 2023-06-13 19:57
> 

I have just check and we don't use this flag 
<img width="520" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/18314027/f5e196f6-cc44-4caa-8ef8-f29ebf03053b">

But this explanation makes sense, could be somehow related...

**Comment by themiswang** [comment] 2023-06-13 20:13
@matkavt then next step I would suggest that:

- When you build your app, can you quickly go to activity monitor to see if can get an sample for upload-symbol process? So far this is the only scenario that I can reproduce the issue and I am able to get a snapshot call graph there. 
- It might related to your file permissions on your mac, can you double check you give correct read, write access to `~/Library/Caches`, temporary directory as well as the directory which store your dsym files?

**Comment by matkavt** [comment] 2023-06-13 20:36
> @matkavt then next step I would suggest that:
> 
> 
> 
> - When you build your app, can you quickly go to activity monitor to see if can get an sample for upload-symbol process? So far this is the only scenario that I can reproduce the issue and I am able to get a snapshot call graph there. 
> 
> - It might related to your file permissions on your mac, can you double check you give correct read, write access to `~/Library/Caches`, temporary directory as well as the directory which store your dsym files?

Ok I'll give it a try

**Comment by matkavt** [comment] 2023-06-13 20:42
Yes there are lots of processes in the list like in the original issue description

**Comment by themiswang** [comment] 2023-06-13 20:50
@ls-bertrand-landry-hetu, @matkavt,

Yeah most of time I am getting that as well, but luckily I have once captured the thread for `LS database changed notification queue`. When it unwind there is no difference compare with the call graph you had.

**Comment by themiswang** [comment] 2023-06-14 23:25
This is probably related to file permissions. There is one more thing folks can try.

- Open Console.app and filter `upload-symbols`, start streaming
- Run app and check the logs for `upload-symbols`, in my case for hanging upload-symbol script I do violate kernel policy for my dsym file read
![image](https://github.com/firebase/firebase-ios-sdk/assets/16548721/d7858854-0889-4633-bdff-bf253d080046)

If you run into the same dsym read violation, in your run script for `upload-symbol`, for input file, instead of `${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}` try `${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}`. It works for me then even in sandbox mode.

**Comment by kientux** [comment] 2023-06-20 03:07
I have the same problem, and after some investigations, I figured out that `${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}` is not always the right path.

My project has custom `PRODUCT_NAME` for each scheme so I have to use `${PRODUCT_NAME}` instead of `${TARGET_NAME}`, because that's the name of DWARF symbol file to be generated.

Also if I use just `${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}`, it messes up the order of build phase scripts. Crashlytics script will run immediately when input file is available, eventhough when the dSYM dir is created, DWARF file is not yet generated, and the script will throw out "File no longer exists at (null)" error.

**Comment by themiswang** [comment] 2023-06-21 22:20
Xcode sometimes run build scripts async and Upload-symbol might be run before dSYM getting generated, we do have a check in script to wait until dSYM gets generated but it will timeout if dSYM takes too long to generate. If there is async issue for build phase script, can you try adding the script to [post actions](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow/customizing_the_xcode_archive_process?language=objc)

**Comment by matkavt** [comment] 2023-06-22 00:09
> Xcode sometimes run build scripts async and Upload-symbol might be run before dSYM getting generated, we do have a check in script to wait until dSYM gets generated but it will timeout if dSYM takes too long to generate. If there is async issue for build phase script, can you try adding the script to [post actions](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow/customizing_the_xcode_archive_process?language=objc)

Wow, sounds reasonable. I wonder if there is any downsides to this. If not, may be we should do it anyway, just in case

**Comment by themiswang** [comment] 2023-06-23 19:29
@matkavt, I don't see there is any downside, it really depends which way suits the best for your development process and you might want to try our different strategies to figure out. 

Adding upload-symbol to build phase you get benefit most from automatically upload symbol during development, by doing such every time when you make a new build locally you don't need to manually upload-symbols. Some people actually don't do it because they don't want their console pollutes with development versions. Adding the scripts to post action from Xcode is another way. Other strategies I have seen folks using is make upload-symbol as another action after build action in their CI/CD pipeline, you can use [Fastlane](https://docs.fastlane.tools/actions/upload_symbols_to_crashlytics/) integration or adding [the command](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#upload-dsyms) list here to make that action. Again there are many solutions and I think you might want to evaluate each and see which one you are going to approach. 

Feel like we know the root cause for stalls and there a few alternatives have been provided. Do you mind to try out see if any of them helps for your issue then we can close it :).  Thank you!

**Closed** 2023-07-06 01:05 UTC
Labels: api: crashlytics, needs-info, no-recent-activity

**Comment by immi-sipgate** [comment] 2023-07-06 10:33
@matkavt is the problem solved for you? Unfortunately we still have the problem.

**Comment by matkavt** [comment] 2023-07-06 11:16
> @matkavt is the problem solved for you? Unfortunately we still have the problem.

Sorry I am currently on vacation so I am not sure. I think that we also kept getting these errors last time I checked
