### ISSUE TITLE
Crash: libobjc.A.dylib objc_exception_throw

### ISSUE THREAD

**Issue by siddew201** [firebase/firebase-ios-sdk#10159] opened 2022-09-01 07:24 UTC
### Description

The app is getting crash. It should not be crash.

### Reproducing the issue

There is not any reproducible step. App is getting crash at client side.

### Firebase SDK Version

9.1

### Xcode Version

13.2.1

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics, DynamicLinks, Messaging, Performance, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Fatal Exception: NSInvalidArgumentException
-[_UIRemoteInputViewController _alignsToContentViewController]: unrecognized selector sent to instance 0x118c1ca00

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0xa248 (Missing UUID 1b67e644593a3401b48d084b8d879212)
1  libobjc.A.dylib                0x17a68 objc_exception_throw
2  CoreFoundation                 0x17e3f0 (Missing UUID 1b67e644593a3401b48d084b8d879212)
3  UIKitCore                      0xd40450 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
4  CoreFoundation                 0x20360 (Missing UUID 1b67e644593a3401b48d084b8d879212)
5  CoreFoundation                 0x88660 (Missing UUID 1b67e644593a3401b48d084b8d879212)
6  UIKitCore                      0x26cd8c (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
7  UIKitCore                      0x2f3fa4 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
8  UIKitCore                      0x2f2d14 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
9  UIKitCore                      0x372d40 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
10 UIKitCore                      0x373028 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
11 UIKit                          0x48394 (Missing UUID 3be0a23e8f7338219321aae05a8aa0d2)
12 UIKitCore                      0x5346cc (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
13 UIKitCore                      0x56dbbc (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
14 UIKitCore                      0x2060e4 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
15 UIKitCore                      0x571cd0 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
16 UIKitCore                      0x3be0c4 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
17 UIKitCore                      0x3be0c4 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
18 UIKitCore                      0x3be0c4 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
19 UIKitCore                      0x3be0c4 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
20 UIKitCore                      0x11610 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
21 UIKitCore                      0x49cb70 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
22 UIKitCore                      0x4bf7d0 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
23 UIKitCore                      0xba4bbc (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
24 UIKitCore                      0xb930c0 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
25 UIKitCore                      0xb92a14 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
26 UIKitCore                      0x3d383c (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
27 UIKitCore                      0x3d3720 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
28 Foundation                     0x3b000 (Missing UUID d9be846e2d4a34ca8dd114eb6f8c938e)
29 CoreFoundation                 0xd622c (Missing UUID 1b67e644593a3401b48d084b8d879212)
30 CoreFoundation                 0xe2614 (Missing UUID 1b67e644593a3401b48d084b8d879212)
31 CoreFoundation                 0x6657c (Missing UUID 1b67e644593a3401b48d084b8d879212)
32 CoreFoundation                 0x7beb8 (Missing UUID 1b67e644593a3401b48d084b8d879212)
33 CoreFoundation                 0x811e4 (Missing UUID 1b67e644593a3401b48d084b8d879212)
34 GraphicsServices               0x1368 GSEventRunModal
35 UIKitCore                      0x3a2c48 (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
36 UIKitCore                      0x3a28ac (Missing UUID ac8cbdf008843177b89b40e5a83a5f96)
37 TCPApp                         0xbad894 main + 39 (AppDelegate.swift:39)
38 ???                            0x1da34b948 (Missing)

Crashed: com.google.firebase.crashlytics.ios.exception
SIGABRT ABORT 0x00000001f856b200
Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x2228c FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0x2266c FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0x185c0 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x127e0 __FIRCLSExceptionRecord_block_invoke + 232 (FIRCLSException.mm:232)
4  libdispatch.dylib              0x3fdc <redacted> + 20
5  libdispatch.dylib              0x13574 <redacted> + 56
6  FirebaseCrashlytics            0x115c0 FIRCLSExceptionRecord + 234 (FIRCLSException.mm:234)
7  FirebaseCrashlytics            0x12288 FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126)
8  FirebaseCrashlytics            0x111c0 FIRCLSTerminateHandler + 398 (FIRCLSException.mm:398)
9  libc++abi.dylib                0x10f28 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x13ecc __cxa_rethrow + 148
11 libobjc.A.dylib                0x19854 objc_exception_rethrow + 44
12 CoreFoundation                 0x812a8 CFRunLoopRunSpecific + 808
13 GraphicsServices               0x1368 GSEventRunModal + 164
14 UIKitCore                      0x3a2c48 <redacted> + 888
15 UIKitCore                      0x3a28ac UIApplicationMain + 340
16 TCPApp                         0xbad894 main + 39 (AppDelegate.swift:39)
17 ???                            0x1da34b948 (Missing)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment] 2022-09-01 12:34
Hi @siddew201, based on your stack trace, it seems like it didn't mention what part of Firebase is causing the crash. Also, most of the traces have missing UUIDs. Could you provide your complete stack trace? Thanks.

**Comment by morganchen12** [comment] 2022-09-06 20:43
The exception message

```
-[_UIRemoteInputViewController _alignsToContentViewController]: unrecognized selector sent to instance 0x118c1ca00
```

indicates some UIKit misuse is causing your crash. Closing this issue since there's no indication it's caused by Firebase, but if you have more information feel free to continue commenting.

**Closed by morganchen12** 2022-09-06 20:43 UTC
Labels: needs-info
