### ISSUE TITLE
Crash: [FSnapshotHolder updateSnapshot:withNewSnapshot:]

### ISSUE THREAD

**Issue by saldous** [firebase/firebase-ios-sdk#480] opened 2017-11-21 17:18 UTC
* Xcode version: _9.1
  * Firebase SDK version: _4.6.0

Crashlytics is reporting a number of crashes in my app since updating to Firebase 4.6.0.

[FSnapshotHolder updateSnapshot:withNewSnapshot:]

Fatal Exception: NSInvalidArgumentException
-[FListenProvider updateChild:withNewChild:]: unrecognized selector sent to instance 0x1c042da40

![image](https://user-images.githubusercontent.com/3334306/33086515-c9ee01ba-ceb5-11e7-8592-448bb23d687f.png)

**Comment by paulb777** [comment] 2017-11-21 17:42
Duplicate of #281

**Closed by paulb777** 2017-11-21 17:42 UTC
Labels: Database, duplicate
