### ISSUE TITLE
Problem warning Protobuf

### ISSUE THREAD

**Issue by devLoop1** [firebase/firebase-ios-sdk#3243] opened 2019-06-24 14:52 UTC
Hello, when installing the services of firebase (Auth, Firestore, Database) they show me errors about Protobuf (Images of attached files). Apparently, the error is that the path you are looking for files is / Protobuf with the P in upper case, but the path is with the P minuscula.
Try changing the import "#import <Protobuf / Timestamp.pbobjc.h>" to "#import <protobuf / Timestamp.pbobjc.h>" and the error disappears, but I do not know if this can cause problems later.

Attached capture of the file Podfile
As you can solve this problem, I hope you can help me.

- xcode 10.2.1
- Swift 5
<img width="1269" alt="Captura de Pantalla 2019-06-23 a la(s) 18 47 47" src="https://user-images.githubusercontent.com/48538624/60028829-0bcc0600-966e-11e9-941c-fb6f12665f1a.png">
<img width="1253" alt="Captura de Pantalla 2019-06-23 a la(s) 18 48 12" src="https://user-images.githubusercontent.com/48538624/60028830-0bcc0600-966e-11e9-82e0-2c81c94dff5d.png">
<img width="573" alt="Captura de Pantalla 2019-06-24 a la(s) 10 52 07" src="https://user-images.githubusercontent.com/48538624/60028922-2ef6b580-966e-11e9-912e-952252778b03.png">

**Comment by paulb777** [comment] 2019-06-24 14:54
Duplicate of #2665

**Closed by paulb777** 2019-06-24 14:54 UTC
Labels: needs-triage
