### ISSUE TITLE
App Launch time excessive requests

### ISSUE THREAD

**Issue by jserrafindster** [firebase/firebase-ios-sdk#6403] opened 2020-09-04 12:30 UTC
### Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.21.0
  * Installation method: CocoaPods

### Describe the problem
The issue doesn't seem to happen always. 
Sometimes when launching the app the app can take more than 10 seconds to reach the home screen.

While this issue was happening I was able to pause the code and do some debug. 
Seems firebase is delaying the app start.
I've notice at a point that we had 180 pending blocks

#### Steps to reproduce:

Create a new app add firebase support 
add the configureFirebase() to the didFinishLaunchingWithOptions on AppDelegate

Sorry but i didn't grab the text version of the stack

![Screenshot 2020-09-03 at 16 59 38](https://user-images.githubusercontent.com/52421199/92239062-48220580-eeb2-11ea-865a-5afaea3cd58d.png)

![Screenshot 2020-09-03 at 16 57 24](https://user-images.githubusercontent.com/52421199/92238916-0beea500-eeb2-11ea-8425-4e44813fcb6c.png)

also just for note I've stumble on issue [#5956 ](https://github.com/firebase/firebase-ios-sdk/issues/5956)and then I was forward to check issue [#6232](https://github.com/firebase/firebase-ios-sdk/pull/6232) but I was told to create a new issue.

**Comment by maksymmalyhin** [comment] 2020-09-08 14:09
@jserrafindster Thank you for creating the issue. To check if it is the same issue as the one fixed in #6232 could you please enable [debug mode](https://firebase.google.com/docs/analytics/debugview#enabling_debug_mode) and post the app logs you see when the issue is reproducible. Feel free to filter non-Firebase logs.

**Closed** 2020-09-22 01:03 UTC
Labels: api: installations, needs-info, no-recent-activity
