### ISSUE TITLE
Crash happening on sdk remote config db manager [RCNConfigDBManager insertMainTableWithValues:fromSource:]

### ISSUE THREAD

**Issue by sbalani92** [firebase/firebase-ios-sdk#9155] opened 2022-01-03 08:54 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: xcode 13.0
  * Firebase SDK version: 8.6.0
  * Installation method:  CocoaPods 
  * Firebase Component: Database
  * Target platform(s):  iOS 

#### Steps to reproduce:

What happened? How can we make the problem occur?
Crash happened just after the app launch when firebase doing some configuration.

Below are the crash details:
Crashed: com.google.GoogleConfigService.database
0  libsystem_platform.dylib       0x60e8 _os_unfair_lock_unowned_abort + 36
1  libsystem_platform.dylib       0x1168 _os_unfair_lock_unlock_slow + 96
2  libsqlite3.dylib               0x7358 sqlite3_snprintf + 4300
3  libsqlite3.dylib               0x6f68 sqlite3_snprintf + 3292
4  libsqlite3.dylib               0x69008 sqlite3_free_table + 44116
5  libsqlite3.dylib               0x6c590 sqlite3_free_table + 57820
6  libsqlite3.dylib               0x6bd50 sqlite3_free_table + 55708
7  libsqlite3.dylib               0x4af74 sqlite3_step + 34744
8  libsqlite3.dylib               0x428f0 sqlite3_step + 308
9  FirebaseRemoteConfig           0xd938 -[RCNConfigDBManager insertMainTableWithValues:fromSource:] + 440
10 FirebaseRemoteConfig           0xd6f0 __77-[RCNConfigDBManager insertMainTableWithValues:fromSource:completionHandler:]_block_invoke + 56
11 libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x3950 _dispatch_client_callout + 20
13 libdispatch.dylib              0xb0ac _dispatch_lane_serial_drain + 664
14 libdispatch.dylib              0xbc10 _dispatch_lane_invoke + 392
15 libdispatch.dylib              0x16318 _dispatch_workloop_worker_thread + 656
16 libsystem_pthread.dylib        0x11b0 _pthread_wqthread + 288
17 libsystem_pthread.dylib        0xf50 start_wqthread + 8

**Comment by rizafran** [comment] 2022-01-03 11:26
Thanks for reporting, @sbalani92. Do you have any other sqlite code in your codebase?

**Comment by paulb777** [comment] 2022-01-04 15:24
Yes, looks like a duplicate of #8147

**Comment by Zhenghuawei-iOS** [comment] 2022-01-08 03:39
```
Crashed: com.google.GoogleConfigService.database
0  libsystem_platform.dylib       0x404c _os_unfair_lock_unowned_abort + 36
1  libsystem_platform.dylib       0x54f4 _os_unfair_lock_unlock_slow + 144
2  libsqlite3.dylib               0x6f18 sqlite3_snprintf + 3188
3  libsqlite3.dylib               0x6b18 sqlite3_snprintf + 2164
4  libsqlite3.dylib               0x69c0c sqlite3_free_table + 49564
5  libsqlite3.dylib               0x6d47c sqlite3_free_table + 64012
6  libsqlite3.dylib               0x6cc30 sqlite3_free_table + 61888
7  libsqlite3.dylib               0x47d00 sqlite3_step + 29564
8  libsqlite3.dylib               0x40b40 sqlite3_step + 444
9  FirebaseRemoteConfig           0xd99c -[RCNConfigDBManager insertMainTableWithValues:fromSource:] + 440
10 FirebaseRemoteConfig           0xd754 __77-[RCNConfigDBManager insertMainTableWithValues:fromSource:completionHandler:]_block_invoke + 56
11 libdispatch.dylib              0x5fa38 _dispatch_call_block_and_release + 24
12 libdispatch.dylib              0x607d4 _dispatch_client_callout + 16
13 libdispatch.dylib              0x9324 _dispatch_lane_serial_drain$VARIANT$mp + 592
14 libdispatch.dylib              0x9e40 _dispatch_lane_invoke$VARIANT$mp + 428
15 libdispatch.dylib              0x124ac _dispatch_workloop_worker_thread + 596
16 libsystem_pthread.dylib        0xc114 _pthread_wqthread + 304
17 libsystem_pthread.dylib        0xecd4 start_wqthread + 4
```

- Firebase/RemoteConfig (7.10.0):

i have the same problem.

**Comment by argzdev** [comment] 2022-01-14 09:34
Thanks for the response, @sbalani92. With that said, I'll close this issue for now. Feel free to ask any questions after investigating or open a new issue if needed. Thanks!

**Closed by argzdev** 2022-01-14 09:34 UTC
Labels: api: remoteconfig, needs-attention

**Comment by sbalani92** [comment] 2022-01-14 09:46
Just a question here, Is there anyway i can get the sql version used in Firebase SDK version: 8.6.0?

**Comment by paulb777** [comment] 2022-01-14 14:35
Firebase uses the default iOS system version of sqlite3
