### ISSUE TITLE
[FR]: Include Firebase XCFrameworks through SPM

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#10524] opened 2022-11-25 11:18 UTC
### Description

I want to reduce frictions with my internal tools to build faster xcframeworks from SPM to use it in my projects.

### API Proposal

For that purpose already exists a repo that make it possible https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks 
I want to know if it's possible that firebase use this approach directly.

Thanks in advance 

### Firebase Product(s)

AB Testing, Analytics, App Check, App Distribution, Authentication, Crashlytics, Database, DynamicLinks, Firestore, Functions, In-App Messaging, Installations, ML Model Downloader, Messaging, Performance, Remote Config, Storage

**Comment by paulb777** [comment] 2022-11-25 14:43
This is a duplicate of #6564. Please follow the feature request there.

**Closed by paulb777** 2022-11-25 14:43 UTC
Labels: type: feature request, Swift Package Manager
