### ISSUE TITLE
Crash in Firebase Crashlytics SDK

### ISSUE THREAD

**Issue by atulJha17** [firebase/firebase-ios-sdk#9737] opened 2022-05-02 07:09 UTC
iOS 15.3.1 and some version over above this.
Devices: iPhone XS, iPhone 11, iPhone 12 min and multiple version which supports iOS 15.3.1 and above.
SDK installed using cocoa pods and version 8.4.0.

FirebasePerformance
FPRNSURLSessionInstrument.m - Line 564
__InstrumentDownloadTaskWithRequest_block_invoke + 564

https://console.firebase.google.com/project/tata-one/crashlytics/app/ios:com.tatadigital.tcp/issues/5ed6ac4e0f861660066a2f99181a0405?time=1649289600000:1650412799000&sessionEventKey=ca5e0601db004a358cbbed734042db17_1662682800563319436

**Comment by rizafran** [comment] 2022-05-02 09:18
Duplicate of #9736.

**Closed by rizafran** 2022-05-02 09:18 UTC
Labels: needs-triage
