### ISSUE TITLE
FirebaseInAppMessaging Storyboard Layout Failed

### ISSUE THREAD

**Issue by CentrumGuy** [firebase/firebase-ios-sdk#3883] opened 2019-09-18 22:32 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0
  * Firebase SDK version: 6.8.1
  * Firebase Component: InAppMessaging (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: (FirebaseInAppMessaging 0.15.4), (FirebaseInAppMessagingDisplay 0.15.4)

### [REQUIRED] Step 3: Describe the problem
I get this error:

file:///Users/.../Alerts.storyboard: error: IB Designables: Failed to render and update auto layout status for CustomNotification (Pg5-Wi-G39): dlopen(FirebaseInAppMessagingDisplay.framework, 1): no suitable image found.  Did find:
	FirebaseInAppMessagingDisplay.framework: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A

I now can't see updates to my storyboards after I add views, move views, or do anything else. The storyboards don't update. This happens on every storyboards and .xib file in my project.

#### Steps to reproduce:
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

This problems started occurring after installation of FirebaseInAppMessaging in my project. I installed FirebaseInAppMessaging with cocoapods.

[edit]: I just noticed that this problem only affects storyboards that have custom IBDesignable classes. My storyboard updated until I changed the class of one of my views to an IBDesignable class.
#### Relevant Code:
No code involved

**Comment by paulb777** [comment] 2019-09-18 23:45
Probably a duplicate of #3748 

I still suspect a build state issue.

**Comment by CentrumGuy** [comment] 2019-09-19 00:06
> Probably a duplicate of #3748
> 
> I still suspect a build state issue.

Were there any @IBDesignable classes in the project you created for issue #3748?

**Comment by christibbs** [comment] 2019-10-29 20:02
This was fixed in the 15.5 version of In App Messaging. Please run `pod update`.

**Closed by christibbs** 2019-10-29 20:02 UTC
Labels: api: inappmessaging
