### ISSUE TITLE
Firebase Dynamic Links not working iOS 15.1 Facebook Swift

### ISSUE THREAD

**Issue by dhimansham** [firebase/firebase-ios-sdk#9382] opened 2022-02-23 07:52 UTC
Firebase Dynamic Links not working iOS 15.1 for Facebook but working perfectly iOS 14.1. I have tried lot of changes with Dynamic Link parameters. I have checked all parameter configured correctly in the Firebase account and Dynamic link like **App BundleId**, **AppStoreID**, **AppID** and all others parameters.

**For iOS 14.1** 

User post a dynamic link on facebook as a post. When user click on then facebook post redirect to automatically in the app.

**For iOS 15.1** 

User post a dynamic link on facebook as post. When user click on facebook post, the user redirect default Website which i set in the dynamic link url. 

User post a dynamic link on facebook as post. When user click on facebook post, the user redirect default Website which i set in the dynamic link url. 

**Code:-**

    func createLinkShare1(dynamicLinksDomainURIPrefix:String,link:URL) {
    let appBundleID = AppInformation.AppBundleId
    if let linkBuilder = DynamicLinkComponents(link: link, domainURIPrefix: dynamicLinksDomainURIPrefix) {
        linkBuilder.navigationInfoParameters = DynamicLinkNavigationInfoParameters()
        linkBuilder.navigationInfoParameters?.isForcedRedirectEnabled = true
        linkBuilder.iOSParameters = DynamicLinkIOSParameters(bundleID: appBundleID)
        linkBuilder.iOSParameters?.appStoreID = AppInformation.AppStoreId
        linkBuilder.iOSParameters?.minimumAppVersion = AppInformation.AppMinimumVersion
        linkBuilder.androidParameters = DynamicLinkAndroidParameters(packageName: appBundleID)
        linkBuilder.androidParameters?.minimumVersion = 0
        linkBuilder.socialMetaTagParameters = DynamicLinkSocialMetaTagParameters()
        linkBuilder.socialMetaTagParameters!.title = "Testing "
        linkBuilder.socialMetaTagParameters!.descriptionText = "Invite You"
        guard let longDynamicLink = linkBuilder.url else {
            print("ERROR in linkBuilder")
            return
        }
        DynamicLinkComponents.shortenURL(longDynamicLink, options: nil) { url, warnings, error in
            if let error = error {
                print("error shortening link: \(error.localizedDescription)")
                return
            }
            if let url = url {
                print("Share Url = ",url)
                return
               }
           }
       }
    }

[**Firebase Dynamic Links not working Every Time Open Custom WebView (Redirection issue) Swift**][1]

Please check above code and let me know if i'm doing wrong anything, please correct me. 

Can someone please explain to me how to show popup or deep working as expected in the Facebook case in the iOS 15., I've tried to with above code but no results yet.

Any help would be greatly appreciated.

Thanks in advance.

  [1]: https://stackoverflow.com/q/70114069/17395036

**Comment by rizafran** [comment] 2022-02-23 16:08
Hi @dhimansham, per checking, there are known issues with FDL involving Facebook. It's up to Facebook to determine how URLs are being handled by [App Links](https://developers.facebook.com/docs/applinks) inside the app. 

Also, this seems to be a duplicate of #9375. I'm going to close this issue so you can continue discussing with the Firebase support team. Thanks.

**Closed by rizafran** 2022-02-23 16:08 UTC
Labels: api: dynamiclinks
