### ISSUE TITLE
Got "Invalid Signature" after submitted to App Store Connect

### ISSUE THREAD

**Issue by Lguanghui** [firebase/firebase-ios-sdk#12572] opened 2024-03-18 03:34 UTC
### Description

I integrate Google Firebase using Swift Package Manager and can receive events in the Analytics's real-time dashboard. Everything will go fine until it is submitted to App Store Connect.

When I submitted my app to App Store Connect for testing, I got an email that there was an error in my app: 

ITMS-90238: Invalid Signature - The main app bundle MyApp at path MyApp.app has following signing error(s): code has no resources but signature indicates they must be present In subcomponent: MyApp.app/Contents/Frameworks/GoogleAppMeasurementIdentitySupport.framework. Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

### Firebase SDK Version

10.22.1

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "originHash" : "4a1aa4eb68817b174536f72e4695ea3d073b35d2cc8a18369c6cd9cebf11763a",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "df308b8b46607675f2b9ec8e569109008f9155ce",
        "version" : "1.2022062300.1"
      }
    },
    {
      "identity" : "alamofire",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Alamofire/Alamofire",
      "state" : {
        "revision" : "723fa5a6c65812aec4a0d7cc432ee198883b6e00",
        "version" : "5.9.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "3e464dad87dad2d29bb29a97836789bf0f8f67d2",
        "version" : "10.18.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "be49849dcba96f2b5ee550d4eceb2c0fa27dade4",
        "version" : "10.22.1"
      }
    },
    {
      "identity" : "foundationx",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Lguanghui/FoundationX",
      "state" : {
        "branch" : "master",
        "revision" : "4b0f23962292f53d8748bd9ccea9e5c36fdfac4b"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "482cfa4e5880f0a29f66ecfd60c5a62af28bd1f0",
        "version" : "10.22.1"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a637d318ae7ae246b02d7305121275bc75ed5565",
        "version" : "9.4.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "26c898aed8bed13b8a63057ee26500abbbcb8d55",
        "version" : "7.13.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "ea4cb5cc0c39c732b85386263116d2e2fdbbdc61",
        "version" : "1.49.2"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "76135c9f4e1ac85459d5fec61b6f76ac47ab3a4c",
        "version" : "3.3.1"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "43aaef65e0c665daadf848761d560e446d350d3d",
        "version" : "1.22.4"
      }
    },
    {
      "identity" : "menubarextraaccess",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/orchetect/MenuBarExtraAccess",
      "state" : {
        "revision" : "f5896b47e15e114975897354c7e1082c51a2bffd",
        "version" : "1.0.5"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "networkingx",
      "kind" : "remoteSourceControl",
      "location" : "https://Lguanghui@github.com/Lguanghui/NetworkingX.git",
      "state" : {
        "branch" : "main",
        "revision" : "a3b807811bc43caa47c0a0f638d7aa16e08fa120"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "swift-algorithms",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-algorithms.git",
      "state" : {
        "revision" : "f6919dfc309e7f1b56224378b11e28bab5bccc42",
        "version" : "1.2.0"
      }
    },
    {
      "identity" : "swift-numerics",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-numerics.git",
      "state" : {
        "revision" : "0a5bc04095a675662cf24757cc0640aa2204253b",
        "version" : "1.0.2"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "65e8f29b2d63c4e38e736b25c27b83e012159be8",
        "version" : "1.25.2"
      }
    },
    {
      "identity" : "swiftuiessentials",
      "kind" : "remoteSourceControl",
      "location" : "https://Lguanghui@github.com/Lguanghui/SwiftUIEssentials.git",
      "state" : {
        "branch" : "main",
        "revision" : "22c69d42df0a87579df6ba9fc3ffa13cd5c8c88e"
      }
    },
    {
      "identity" : "swiftuifoundation",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Lguanghui/SwiftUIFoundation",
      "state" : {
        "branch" : "master",
        "revision" : "c5c303f57dcf3a0e0ece47ee57d17289c5c4f906"
      }
    }
  ],
  "version" : 3
}

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by jesus-mg-ios** [comment] 2024-03-18 13:50
Same here!

**Comment by ncooke3** [comment] 2024-03-18 14:00
Hi eveeyone, I'm closing this as it is a dupe of #12505. The issue came down to a faulty plist for macOS slices and a subtle change in framework validation in Xcode 15.3. The fix for this should be released this week (https://github.com/firebase/firebase-ios-sdk/issues/12505#issuecomment-1989630753).

**Closed by ncooke3** 2024-03-18 14:00 UTC
Labels: needs-triage
