### ISSUE TITLE
iOS 15 Crash [apmidentity appinstanceid]

### ISSUE THREAD

**Issue by ilyon** [firebase/firebase-ios-sdk#8726] opened 2021-09-30 06:58 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5.1
  * Firebase SDK version: 7.4.0
  * Installation method: CocoaPods
  * Firebase Component: Auth, Core, Analytics, Crashlytics, Storage, RemoteConfig

### [REQUIRED] Step 2: Describe the proble

After iOS 15 was released, we saw an increase in the number of crashes in the appstore. But there is no corresponding increase in firebase. We have received some new crash reports in the organizer of xcode, which mainly occurred in iOS 15. The crash information is as follows:

![2371632984759_ pic_hd](https://user-images.githubusercontent.com/2276323/135402132-cbcc4047-b1f1-4a4d-923e-053dcb843984.jpg)

The increase in crashes was sudden. We did not release a new version, but only appeared after the official release of iOS 15. Hope to get help, thanks!

**Comment by paulb777** [comment] 2021-09-30 16:20
This may be a duplicate of #6392 internally tracked at b/152743115

**Comment by jrustonapps** [comment] 2021-10-09 14:53
I am also seeing these crashes on iOS 15.

**Comment by tsunghung** [comment] 2021-10-21 17:53
The main thread was waiting for the worker thread, which was blocked in ASIdentifierManager.advertisingIdentifier. We asked the threading assumption/requirement of ASIdentifierManager in the apple developer forum but have not received any clarification.

We created a workaround in Firebase Analytics 8.7.0+ for testing, but we need help from app developers to verify.
1. The apps must integrate with Firebase Analytics 8.7.0+.
2. Please provide the bundle IDs of your apps. We will enable the workaround for your apps. It may take a few days to adopt the new configurations.
3. Please help to monitor the issue count with time and let us know whether the workaround helps.

**Comment by xidipeng** [comment] 2021-11-01 00:45
I also crash in iOS 15 sdk ver 8.8.0

**Comment by AlexTatarinchik** [comment] 2021-11-01 10:41
Sent request via email

**Comment by ilyon** [comment] 2021-11-12 08:59
> @AlexTatarinchik Just leave the app bundle IDs here. We will enable the workaround and let you know. After the workaround is enabled, please help to monitor the crash count and crash report and let us know how it goes, thanks. If you prefer to email me, my email is [tsunghung@google.com](mailto:tsunghung@google.com).

Hello, is there any result of this experiment, can it solve this problem?

**Comment by tsunghung** [comment] 2021-12-01 20:27
Unfortunately, the experiment result is not positive. The bug may happen before the new configurations are adopted. We will need a different approach to test the workaround.

**Comment by paulb777** [comment] 2021-12-01 23:47
@tsunghung Could this be the result of iOS 15 introducing pre-warming? Could a keychain operation have timed out? See https://twitter.com/steipete/status/1466013492180312068, #8695 and #9026.

**Comment by thisisjeffwong** [comment] 2021-12-03 06:00
Hi, my app is using GoogleMobileAdsSDK and not Firebase and we are seeing this same exact "App Hang" crash. The stackframes are the same except our version number stackframe name is `GAD_GADSignals_arm64_8_9_0`.

This is happening on iOS 15 and iOS 14. So may not be the prewarming issue in iOS 15 described by @paulb777.

**Comment by tsunghung** [comment] 2021-12-20 18:26
In early 2022, we will provide an Early Access Program (EAP) build, which would enable the workaround by default. This will require app developers to rebuild apps with the EAP, publish apps to the App Store, and monitor crashes of new apps. Once we have the EAP build, I will update the related info here.

**Comment by tsunghung** [comment] 2022-01-11 19:16
This issue is the same as #6392. Please follow the updates in #6392.

**Closed by tsunghung** 2022-01-11 19:16 UTC
Labels: api: analytics, internal-bug-filed, Xcode 13 - iOS 15, iOS 15
