### ISSUE TITLE
WatchOS support implementation

### ISSUE THREAD

**Issue by bobin-abraham** [firebase/firebase-ios-sdk#11196] opened 2023-04-27 05:30 UTC
### Description

Hi Team,

I can see that you people are already given support for the watchos to the crashlytics . I am integrated the crashlytics to my watch extension using the cocoapods

But i can only generate the errors like below in the firebase console 

Crashlytics.crashlytics().record(error: NSError(domain: "Initial test crash", code: 00, userInfo: nil))

If i am making an array index out of bounds issue, it is not reporting in the console. Because of this i am doubtful how the real crashes will reported by crashlytics in watch extension

Please guide me to achieve my requirement

Thanking you all in advance 

### Reproducing the issue

1. Integrate the crashlytics with pod as below

  platform :watchos, '8.3'

  use_frameworks!
  
  # Pods for CrashAnalyser
  pod 'Firebase/Crashlytics'
  
  end
  
  2. Try a crash with code Crashlytics.crashlytics().record(error: NSError(domain: "Initial test crash", code: 00, userInfo: nil)). it will updated in console
  3. Now make a array index out of bounds crash in the watch extension
  4.  The firebase console is not reporting it
  

### Firebase SDK Version

10.1.0

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics

### Targeted Platforms

watchOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-04-27 15:30
This may be a duplicate of #6843

**Comment by bobin-abraham** [comment] 2023-04-28 08:25
Hi @paulb777 ,

I went through https://github.com/firebase/firebase-ios-sdk/issues/6843 . What I could understood from the whole discussion is "if watch app is running using swiftUI code and if some crash happening in swiftUI components , it won't report to crashlytics due to the limitation of watchOS"

In my case, the UI of the watch app is created with SwiftUI only as its a mandatory from watch OS 9 onwards. But the view models are written with Swift only and I am making the array index out of bounds issue inside the ViewModel class only which is connected to a SwiftUI button anyway

So please confirm the feasibility of showing the logs , so that i can communicate to my stakeholders who are really eager to wait for this feature in watch app

**Comment by samedson** [comment] 2023-04-28 17:35
@bobin-abraham, so the issue on watchOS is actually more general than just swiftUI. The technical aspects are pretty gritty, but essentially there are 3 ways the Crashlytics SDK captures crashes (this applies to crash reporting SDKs in general), but 1 of them is not supported on watchOS. This essentially means there are classes of crashes we can't capture, and that seems to include index out of bounds exceptions.

We're not really able to resolve this on our end without changes to the OS.

**Comment by samedson** [comment] 2023-04-28 19:48
Going to close this for now but feel free to reopen if there are more questions

**Closed by samedson** 2023-04-28 19:48 UTC
Labels: api: crashlytics, watchOS
