### ISSUE TITLE
158784204: Dynamic link is handled each time when installing app

### ISSUE THREAD

**Issue by odarynakorolevych** [firebase/firebase-ios-sdk#5789] opened 2020-06-10 21:56 UTC
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 5.20.2
  * Firebase Component: DynamicLinks
  * Component version: 5.20.2
  * Installation method: CocoaPods

#### Steps to reproduce:
 
Precondition: Application is not installed on device

 1. Click on the dynamic link (dynamic link should redirect you to AppStore).
 2. Install application from AppStore.
 3. Check that dynamic link is handled.
 4. Remove application.
 5. Install application again.
 6. Dynamic link is handled again, although user didn't click on it again.

#### Relevant Code:

`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool` is called again after reinstalling app. Is there a way to prevent it from handling the dynamic link more than once?

**Comment by paulb777** [comment] 2020-06-11 01:07
@odarynakorolevych Thanks for the report. Version 5.20.2 is more than a year old and several issues have been fixed since then. Would you `pod update` and see if the problem is still occurring?

**Comment by odarynakorolevych** [comment] 2020-06-11 10:45
Hi @paulb777,
I've updated the libraries to the latest version and the issue is still reproducible.

**Comment by pajtimid** [comment] 2020-06-23 09:26
Hi

I'm having same issue
- Firebase SDK version: 6.18.0

Any solution for this

**Comment by eldhosembabu** [comment] 2020-07-16 20:09
Hi @pajtimid ,

FDL SDK saves the information regarding whether the link handling is already done on UserDefaults and when you reinstall the app this value is getting cleared.

If the FDL SDK didn't find whether the link handling already done in user defaults, it would check whether there is any pending links available for this device specific to the app by checking the pasteboard and by checking on the server side. Usually this server side information regarding the link click for a specific app for a specific device is kept for 1 hour and so if you try to re-install the app after 1 hour, your app won't get the clicked link.

But Regardless of whether the app get the link or not, the above call back will get called at least once after the app is installed(As mentioned [here](https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app) in Step 7). So what you could do is to check for dynamicLink.url for not nil before calling your handling code.

    if let dynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
    if(dynamicLink.url != nil){
      // Your handling code here.
    }

**Comment by odarynakorolevych** [comment] 2020-07-19 19:20
Hi @eldhosembabu,

The issue is that the link is handled another time, when it shouldn't. The user install application, we handle the deeplink, and after he/she removes the applications, reinstalls and method WITH (dynamicLink.url != nil) is handled again, although that link was already handled successfully.

So you want to say, that if the user waits one hour or more, that link won't be handled again? Why wouldn't you store that value in Keychain or on the Server side to make it not cleared after reinstall?

Thank you for looking into it!

**Comment by eldhosembabu** [comment] 2020-07-24 18:12
Hi @odarynakorolevych,

The 1 hour can be looked at as the attribution window. Usually users don't install and re-install within this time period. If you're seeing it happening very frequently in app users, with varied uninstall->install time windows, please reach out to support and we can investigate further.

Also to clarify the previous comment, we are not saving anything to keychain.

**Comment by paulb777** [comment] 2023-07-11 02:53
Closing for staleness. Please comment or open a new issue to reopen.

**Closed by paulb777** 2023-07-11 02:53 UTC
Labels: api: dynamiclinks
